### ISSUE TITLE
关于技术交流群

### ISSUE THREAD

**Issue by Jerrick** [hugegraph/hugegraph#1]
我们建议大家使用Issues反馈使用HugeGraph遇到的问题。

但是国内开发者习惯通过微信群进行交流，所以也创建了HugeGraph微信技术讨论群，请加微信号：jerrick1989 或者 ija4444，添加时请备注一下：加入HugeGraph技术讨论群 

![wechatimg74](https://user-images.githubusercontent.com/1468472/43641581-d67c6bdc-9756-11e8-947f-19206b7b2f8d.jpeg)

**Comment by javeme** [comment]
请大家使用Issues反馈问题或建议，以为了让更多的人查到解决问题的方法。非常感谢。

**Comment by wanyouxian** [comment]
加群二维码失效了
