### ISSUE TITLE
[Question(pd-store)] HgStoreNodeService 初始化流程

### ISSUE THREAD

**Issue by VGalaxies** [hugegraph/hugegraph#1]
### Problem Type (问题类型)

struct / logic (架构 / 逻辑设计问题)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

- Server Version: the latest commit on the pd-store branch
- Backend: hstore

### Your Question (问题描述)

试分析 org.apache.hugegraph.store.node.grpc.HgStoreNodeService#init 的初始化流程及其中各个组件的作用

**Comment by VGalaxies** [comment]
@dosu-bot can you help me analyze this~

**Comment by VGalaxies** [comment]
@dosu-bot come on~

**Comment by imbajin** [comment]
@dosu-bot 

Please take some time to learn the `pd-store` branch(https://github.com/hugegraph/hugegraph/tree/pd-store), it will replace the master branch soon:)

The relative code is here:
https://github.com/hugegraph/hugegraph/blob/pd-store/hugegraph-store/hg-store-node/src/main/java/org/apache/hugegraph/store/node/grpc/HgStoreNodeService.java

然后重新分析一下 `HgStoreNodeServic.init()` 的初始化方法流程及其中各个组件的作用, 如果可以给流程图/时序图等图表化更好

**Comment by VGalaxies** [comment]
@dosu-bot the default branch has been switched to pd-store, can you answer this question based on the pd-store branch?

**Comment by VGalaxies** [comment]
> _🤖_
> 
> The `init` method in the `org.apache.hugegraph.store.node.grpc.HgStoreNodeService` class is responsible for initializing the `PartitionService` and adding a `PartitionStatusListener` to it. This listener is triggered when the state of a partition changes or when a partition is removed.
> 
> Here's a simplified version of the `init` method:
> 
> ```java
> public void init(PartitionService partitionService) {
>     this.partitionService = partitionService;
>     partitionService.addStatusListener(new PartitionStatusListener() {
>         @Override
>         public void onPartitionChanged(Metapb.Partition old, Metapb.Partition partition) {
>             // Code to handle partition state change
>         }
> 
>         @Override
>         public void onPartitionRemoved(Metapb.Partition partition) {
>             // Code to handle partition removal
>         }
>     });
> }
> ```
> 
> The `onPartitionChanged` method is triggered when the state of a partition changes. It updates the state of the shard group and the cluster status accordingly. If an exception occurs during this process, it is logged.
> 
> The `onPartitionRemoved` method is triggered when a partition is removed. However, in its current implementation, no action is taken. This method can be overridden to provide custom behavior when a partition is removed.
> 
> The `PartitionService` is a service that manages the partitions in the HugeGraph database. The `PartitionStatusListener` is a listener that reacts to changes in the state of the partitions. The `Metapb.Partition` objects represent the partitions in the database.
> 
> The `init` method is typically called during the startup of the HugeGraph server to initialize the `StoreNodeService` with the current `PartitionService`. This allows the `StoreNodeService` to react to changes in the state of the partitions, which is important for maintaining the consistency and availability of the data in the HugeGraph database.
> 
> The `PartitionService` in the HugeGraph database is responsible for managing the partitions of the graph data. It provides methods to create, update, and delete partitions, as well as to retrieve partition information based on various criteria such as graph name, partition ID, and store.
> 
> The `onPartitionChanged` and `onPartitionRemoved` methods in the `PartitionStatusListener` are called when a partition's state is updated or when a partition is removed, respectively. However, the context does not provide the implementation of these methods, so I cannot provide more details about their behavior.
> 
> For more details, you can refer to the source code of the `StoreNodeService` and `PartitionService` classes in the [pd-store branch of the HugeGraph repository](https://github.com/hugegraph/hugegraph/tree/pd-store?rgh-link-date=2024-02-19T05%3A25%3A57Z).
> 
> ## Sources
> * [hugegraph-pd/hg-pd-core/src/main/java/org/apache/hugegraph/pd/StoreNodeService.java](https://github.com/hugegraph/hugegraph/blob/pd-store/hugegraph-pd/hg-pd-core/src/main/java/org/apache/hugegraph/pd/StoreNodeService.java?rgh-link-date=2024-02-19T05%3A25%3A57Z)
> * [hugegraph-pd/hg-pd-core/src/main/java/org/apache/hugegraph/pd/PartitionService.java](https://github.com/hugegraph/hugegraph/blob/pd-store/hugegraph-pd/hg-pd-core/src/main/java/org/apache/hugegraph/pd/PartitionService.java?rgh-link-date=2024-02-19T05%3A25%3A57Z)
> 
> #### About Dosu



> _🤖_
> 
> The `init` method in the `org.apache.hugegraph.store.node.grpc.HgStoreNodeService` class is responsible for initializing the `PartitionService` and adding a `PartitionStatusListener` to it. This listener is triggered when the state of a partition changes or when a partition is removed.
> 
> Here's a simplified version of the `init` method:
> 
> ```java
> public void init(PartitionService partitionService) {
>     this.partitionService = partitionService;
>     partitionService.addStatusListener(new PartitionStatusListener() {
>         @Override
>         public void onPartitionChanged(Metapb.Partition old, Metapb.Partition partition) {
>             // Code to handle partition state change
>         }
> 
>         @Override
>         public void onPartitionRemoved(Metapb.Partition partition) {
>             // Code to handle partition removal
>         }
>     });
> }
> ```
> 
> The `onPartitionChanged` method is triggered when the state of a partition changes. It updates the state of the shard group and the cluster status accordingly. If an exception occurs during this process, it is logged.
> 
> The `onPartitionRemoved` method is triggered when a partition is removed. However, in its current implementation, no action is taken. This method can be overridden to provide custom behavior when a partition is removed.
> 
> The `PartitionService` is a service that manages the partitions in the HugeGraph database. The `PartitionStatusListener` is a listener that reacts to changes in the state of the partitions. The `Metapb.Partition` objects represent the partitions in the database.
> 
> The `init` method is typically called during the startup of the HugeGraph server to initialize the `StoreNodeService` with the current `PartitionService`. This allows the `StoreNodeService` to react to changes in the state of the partitions, which is important for maintaining the consistency and availability of the data in the HugeGraph database.
> 
> The `PartitionService` in the HugeGraph database is responsible for managing the partitions of the graph data. It provides methods to create, update, and delete partitions, as well as to retrieve partition information based on various criteria such as graph name, partition ID, and store.
> 
> The `onPartitionChanged` and `onPartitionRemoved` methods in the `PartitionStatusListener` are called when a partition's state is updated or when a partition is removed, respectively. However, the context does not provide the implementation of these methods, so I cannot provide more details about their behavior.
> 
> For more details, you can refer to the source code of the `StoreNodeService` and `PartitionService` classes in the [pd-store branch of the HugeGraph repository](https://github.com/hugegraph/hugegraph/tree/pd-store?rgh-link-date=2024-02-19T05%3A25%3A57Z).
> 
> ## Sources
> * [hugegraph-pd/hg-pd-core/src/main/java/org/apache/hugegraph/pd/StoreNodeService.java](https://github.com/hugegraph/hugegraph/blob/pd-store/hugegraph-pd/hg-pd-core/src/main/java/org/apache/hugegraph/pd/StoreNodeService.java?rgh-link-date=2024-02-19T05%3A25%3A57Z)
> * [hugegraph-pd/hg-pd-core/src/main/java/org/apache/hugegraph/pd/PartitionService.java](https://github.com/hugegraph/hugegraph/blob/pd-store/hugegraph-pd/hg-pd-core/src/main/java/org/apache/hugegraph/pd/PartitionService.java?rgh-link-date=2024-02-19T05%3A25%3A57Z)
> 
> #### About Dosu

@dosu-bot Please note that I'm interested in the initialization process of `HgStoreNodeService`, not the `StoreNodeService`. Also, please deeply analyze the initialization process of some internal components (like HgStoreEngine) during the HgStoreNodeService initialization, and so on.

**Comment by VGalaxies** [comment]
> _🤖_
> 
> The `HgStoreNodeService` class plays a crucial role in the HugeGraph database, particularly in managing the registration and keep-alive status of the Store nodes. It handles the registration of Store nodes, recording their IP addresses and generating unique store_IDs for first-time registrations. It also provides methods to retrieve Store information based on the store_ID, update Store information, handle the turnoff of a store, and list all stores or stores for a specific graph name.
> 
> The `init` method in the `HgStoreNodeService` class is used to initialize the `partitionService` instance variable and add a `PartitionStatusListener` to it. The `PartitionStatusListener` is an interface that listens for changes in the partition status. In the `init` method, an anonymous class is created that implements this interface. This anonymous class overrides two methods: `onPartitionChanged` and `onPartitionRemoved`.
> 
> The `onPartitionChanged` method is called when the partition status changes. It checks if the old partition state is different from the new one. If so, it updates the shard group state and the cluster status based on the new partition state.
> 
> The `onPartitionRemoved` method is called when a partition is removed. However, in this context, it doesn't perform any operations.
> 
> As for the `HgStoreEngine`, it is a core component of the HugeGraph database that manages the storage and retrieval of graph data. It is initialized during the startup of the HugeGraph server and is responsible for managing the lifecycle of the graph data, including the creation, update, deletion, and retrieval of vertices and edges. The `HgStoreEngine` interacts with the `HgStoreNodeService` through the `PartitionService`, which is responsible for managing the partitions of the graph data.
> 
> Unfortunately, without more specific code or context, it's difficult to provide a more detailed analysis of the initialization process of the `HgStoreEngine` during the `HgStoreNodeService` initialization. If you could provide more details or specific questions about this process, I would be happy to help further.
> 
> For more details, you can refer to the source code of the `StoreNodeService` and `PartitionService` classes in the [pd-store branch of the HugeGraph repository](https://github.com/hugegraph/hugegraph/tree/pd-store?rgh-link-date=2024-02-19T05%3A42%3A36Z).
> 
> ## Sources
> * [hugegraph-pd/hg-pd-core/src/main/java/org/apache/hugegraph/pd/StoreNodeService.java](https://github.com/hugegraph/hugegraph/blob/pd-store/hugegraph-pd/hg-pd-core/src/main/java/org/apache/hugegraph/pd/StoreNodeService.java?rgh-link-date=2024-02-19T05%3A42%3A36Z)
> * [hugegraph-pd/hg-pd-core/src/main/java/org/apache/hugegraph/pd/PartitionService.java](https://github.com/hugegraph/hugegraph/blob/pd-store/hugegraph-pd/hg-pd-core/src/main/java/org/apache/hugegraph/pd/PartitionService.java?rgh-link-date=2024-02-19T05%3A42%3A36Z)
> 
> ## Sources
> * [hugegraph-pd/hg-pd-core/src/main/java/org/apache/hugegraph/pd/StoreNodeService.java](https://github.com/hugegraph/hugegraph/blob/pd-store/hugegraph-pd/hg-pd-core/src/main/java/org/apache/hugegraph/pd/StoreNodeService.java?rgh-link-date=2024-02-19T05%3A42%3A36Z)
> 
> #### About Dosu

@dosu-bot I mean `hugegraph-store/hg-store-node/src/main/java/org/apache/hugegraph/store/node/grpc/HgStoreNodeService.java` instead of `hugegraph-pd/hg-pd-core/src/main/java/org/apache/hugegraph/pd/StoreNodeService.java`
