### ISSUE TITLE
索引类型问题

### ISSUE THREAD

**Issue by I-DO-NOT-KNOW** [hugegraph/hugegraph#1005]
属性property是text类型的，索引类型是secondary
g.V().has('property',eq('123'))    执行没有问题  
g.V().has('property',neq('123'))  报错：may not match secondary/range condition

如果将索引类型改为search
g.V().has('property',eq('123'))    报错：may not match secondary condition
g.V().has('property',neq('123'))   执行没有问题

想问下，对于secondary是不支持neq查询的吗？现在需要对属性进行等于、不等的的判断。

**Comment by javeme** [comment]
@I-DO-NOT-KNOW neq条件查询目前是不支持索引优化的
