### ISSUE TITLE
支持rdf数据导入吗？

### ISSUE THREAD

**Issue by jiebaHZ** [hugegraph/hugegraph#1006]
### 
支持rdf数据导入吗？
或者说有没有rdf到属性图结构的转换插件？

**Comment by javeme** [comment]
@jiebaHZ 可以先将rdf转换为csv或json格式，然后通过hugegraph-loader导入到图中。
转换方式有两个链接供参考：
https://www.withdata.com/blog/datafileconverter/convert-rdf-file-to-csv-file-without-programming.html
https://www.itdaan.com/blog/2013/09/05/3c51893fb558356eac54fdf1b71576d7.html

**Comment by jiebaHZ** [comment]
谢谢
