### ISSUE TITLE
使用hugegraph-client 链接hugegraph server 一组操作的事务问题怎么解决？

### ISSUE THREAD

**Issue by jiangjunlong** [hugegraph/hugegraph#1008]
### Expected behavior 期望表现
刚接触hugegraph 粗略看了一下client的文档和源码  没有找到相应的信息 不知道是否支持 远程调用的时候 手动开启事务 然后提交 或者通过注解也行
希望大神不吝赐教  业务系统横向比较选型中

**Comment by javeme** [comment]
@jiangjunlong 顶点或边的 batch api 默认就是在一个事务里面的，需要灵活的控制可以使用gremlin：
```
        graph.tx().open();

        Vertex james = graph.addVertex(T.label, "author", "id", 1,
                                       "name", "James Gosling",  "age", 62,
                                       "lived", "San Francisco Bay Area");
        Vertex book1 = graph.addVertex(T.label, "book", "name", "java-1");
        Vertex book2 = graph.addVertex(T.label, "book", "name", "java-2");
        Vertex book3 = graph.addVertex(T.label, "book", "name", "java-3");

        james.addEdge("write", book1, "time", "2017-4-28");
        james.addEdge("write", book2, "time", "2016-1-1");
        james.addEdge("write", book3, "time", "2017-4-28");

        graph.tx().commit();
```

**Comment by kevinliang-123** [comment]
> @jiangjunlong 顶点或边的 batch api 默认就是在一个事务里面的，需要灵活的控制可以使用gremlin：
> 
> ```
>         graph.tx().open();
> 
>         Vertex james = graph.addVertex(T.label, "author", "id", 1,
>                                        "name", "James Gosling",  "age", 62,
>                                        "lived", "San Francisco Bay Area");
>         Vertex book1 = graph.addVertex(T.label, "book", "name", "java-1");
>         Vertex book2 = graph.addVertex(T.label, "book", "name", "java-2");
>         Vertex book3 = graph.addVertex(T.label, "book", "name", "java-3");
> 
>         james.addEdge("write", book1, "time", "2017-4-28");
>         james.addEdge("write", book2, "time", "2016-1-1");
>         james.addEdge("write", book3, "time", "2017-4-28");
> 
>         graph.tx().commit();
> ```
  graph.tx()如何获得呢，在hugegraph-client中，HugeClient.graph()获得的是GraphManager，其并没有tx()函数啊
