### ISSUE TITLE
今天的更新  query by label without 80w limit   是不是表示g.V().hasLabel('role')当数据量大于80W时也可以正常返回

### ISSUE THREAD

**Issue by fisherinbox** [hugegraph/hugegraph#101]
### Expected behavior 期望表现
g.V().hasLabel('role')当数据量大于80W时也可以正常返回

### Actual behavior 实际表现
Internal Server Error
Failed to do request

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by zhoney** [comment]
@fisherinbox 
是的。
不过还是应该通过增加限定条件来减少查询涉及的数据量，可以提升查询速度，减少内存资源消耗。

**Comment by fisherinbox** [comment]
@zhoney 
但是我试了一下,返回还是跟原来一样,不过我是用新的server去连了之前已经建好的图,是需要用新的server重新init,导入才行吗

**Comment by zhoney** [comment]
@fisherinbox 
抱歉，我把这个问题跟 #81 当成同一个问题了。

#93 是为了取消了HugeGraphServer内部异步任务的query by label的80w限制。
g.V().hasLabel('role')是外部查询，还是有80w的限制。

想要绕过限制可以用异步gremlin，参见RESTful API 7.1.3：
https://hugegraph.github.io/hugegraph-doc/clients/restful-api/gremlin.html

**Comment by fisherinbox** [comment]
@zhoney 
这跟问题[#81](https://github.com/hugegraph/hugegraph/issues/81)应该是一样的,我试了一下[#81](https://github.com/hugegraph/hugegraph/issues/81)中的查询还是会返回80w限制的错误

**Comment by zhoney** [comment]
@fisherinbox 
这个问题跟 #81 不同：
- g.V().hasLabel().limit(10)，限制了查询的规模是10，即使符合条件的顶点数大于80w也是可以查询出来的
- g.V().hasLabel()，没有限制查询规模，当符合条件的顶点数大于80w的时候会因为到达上限而报错。

#81 是因为有bug，没处理limit的限制导致的，已经提交了patch #104

**Comment by fisherinbox** [comment]
@zhoney 好的,我的意思是结果是一样的,都是报错,确实应该是bug
