### ISSUE TITLE
hbase集群后端启动报错

### ISSUE THREAD

**Issue by jiebaHZ** [hugegraph/hugegraph#1010]
### 定义了三个hbase节点，hugegraph初始化时报错，日志如下
`2020-05-28 04:57:01 2382  [main] [INFO ] org.apache.hadoop.hbase.zookeeper.ReadOnlyZKClient [] - Connect 0x4bff64c2 to 192.168.164.147:2181,192.168.164.148:2181,192.168.164.149:2181 with session timeout=90000ms, retries 3, retry interval 1000ms, keepAlive=60000ms
2020-05-28 04:57:01 2417  [main] [WARN ] org.apache.hadoop.hbase.client.ConnectionImplementation [] - Retrieve cluster id failed
java.util.concurrent.ExecutionException: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /hbsae/hbaseid
……`

### 检查hbase启动正常，并且hbase-site.xml已经配置了：
`<property>  
	<name>zookeeper.znode.parent</name>
	<value>/hbase</value>  
</property>`

### hugegraph配置文件如下：
hbase.hosts=192.168.164.147,192.168.164.148,192.168.164.149
hbase.port=2181
hbase.znode_parent=/hbsae
hbase.threads_max=64`

**Comment by imbajin** [comment]
不好意思, 这里的hbase默认的znode的`hbase`拼写有误, 你更正一下就行

`hbase.znode_parent=/hbase`  (模板里写的是`/hbsae`)

在PR里已经更正了

**Comment by jiebaHZ** [comment]
好的，问题已解决，非常感谢
