### ISSUE TITLE
graph.getVertex('vertexId')得到的date类型的属性为Long型的时间戳，gremlin().gremlin(“g.V('VERTEXiD')”).execute()得到的date类型是String类型

### ISSUE THREAD

**Issue by I-DO-NOT-KNOW** [hugegraph/hugegraph#1011]
graph.getVertex('vertexId')得到的date类型的属性为Long型的时间戳，
但是如果是通过gremlin().gremlin(“g.V('VERTEXiD')”).execute()得到的date类型是String类型的

### Expected behavior 期望表现
{
希望类型保持一致
}

**Comment by javeme** [comment]
@I-DO-NOT-KNOW 感谢反馈，已确认存在该问题。我们会尽量保持一致。

@Linary 请看下使用哪种方式比较好？统一使用字符串是否对Hubble影响很大？
