### ISSUE TITLE
limit函数用于限制查询出来的元素数量么？

### ISSUE THREAD

**Issue by youngkangrui** [hugegraph/hugegraph#1018]
在使用limit过程中遇到一个问题：
hugeGraph.traversal().V().hasLabel(“user”)能查到数据
hugeGraph.traversal().V().hasLabel(“user”).limit(100)查不到数据;

**Comment by javeme** [comment]
@youngkangrui 可能是这个bug：https://github.com/hugegraph/hugegraph/issues/864，请参考：https://github.com/hugegraph/hugegraph/issues/864#issuecomment-620355552

@lxb1111 请验证下0.11版是否存在该问题。

**Comment by lxb1111** [comment]
0.11版本，已经验证过目前这个bug没有复现出来。
![image](https://user-images.githubusercontent.com/58289576/84360087-1fb0a500-abfc-11ea-98e8-836cb369f837.png)
![image](https://user-images.githubusercontent.com/58289576/84360146-3ce57380-abfc-11ea-8ed9-e38819a04eb6.png)
