### ISSUE TITLE
项目是否继续维护？

### ISSUE THREAD

**Issue by cmdares** [hugegraph/hugegraph#1019]
项目好久没有更新了？是否还维护？后期还有重要的里程碑发布吗？

**Comment by javeme** [comment]
@cmdares 一直有在更新的，包括issue和pr都在不断更新中，Q3即将会发布0.11版。

**Comment by gitriver** [comment]
版本发布有点慢。另外发布包能不能放在国内的服务器上，放在国外下载太慢了
