### ISSUE TITLE
Restful api和gremlin性能不同

### ISSUE THREAD

**Issue by shyingCy** [hugegraph/hugegraph#1022]
### Expected behavior 期望表现
http://ip:8080/graphs/hugegraph/traversers/shortestpath?source="a"&target="b"&max_depth=5&direction=BOTH

http://ip:8080/gremlin?gremlin=hugegraph.traversal().V().hasId("a").repeat(both().simplePath()).until(has("b").or().loops().is(lte(5))).has("b").path()

这两个都是获取a和b之间的最短路径，返回时间应该是差不多的

### Actual behavior 实际表现
实际上第一个能出来结果，第二个超时，没办法获取到结果

#### Vertex/Edge summary 数据量
- loaded vertices amount: 4300万
- loaded edges amount: 5亿

**Comment by javeme** [comment]
@shyingCy 如果功能满足的前提下建议优先使用定制的rest接口，gremlin特点是比较灵活，但性能优化较rest相对来说难一些。

**Comment by shyingCy** [comment]
> @shyingCy 如果功能满足的前提下建议优先使用定制的rest接口，gremlin特点是比较灵活，但性能优化较rest相对来说难一些。

好的。谢谢解答
