### ISSUE TITLE
【疑问】 g.E().groupCount().by(label) 与g.E().hasLabel('EDGE1').count() 性能差异

### ISSUE THREAD

**Issue by chencjiajy** [hugegraph/hugegraph#1023]
语句1：`g.E().groupCount().by(label)`
语句2： `g.E().hasLabel('EDGE1').count()`
语句1 与语句2的性能查询差异很大，语句1 可以查到库里每条边的计数，但是语句2如果边的数量比较多的话，可能会导致hugegraph的后端数据库挂掉。

使用profile查看性能分析，语句1的"traverserCount"和"elementCount"因为包括所有的边应该是更大的，hugegraph做了哪些优化，从而使语句1可以查询得到，语句2太慢而查不到？

**Comment by javeme** [comment]
@chencjiajy 后端数据库挂掉，使用的是什么后端？在v0.11版两个语句都已优化了的。查询优化包括索引表加速等方法。

**Comment by chencjiajy** [comment]
后端是hbase, hugegraph版本是0.10.4

**Comment by imbajin** [comment]
> 语句1：`g.E().groupCount().by(label)`
> 语句2： `g.E().hasLabel('EDGE1').count()`
> 语句1 与语句2的性能查询差异很大，语句1 可以查到库里每条边的计数，但是语句2如果边的数量比较多的话，可能会导致hugegraph的后端数据库挂掉。
> 
> 使用profile查看性能分析，语句1的"traverserCount"和"elementCount"因为包括所有的边应该是更大的，hugegraph做了哪些优化，从而使语句1可以查询得到，语句2太慢而查不到？

话说这个问题现在有结论了么? 你查询的 `count()` 总数多少, 是使用异步的 gremlin 方式查询的么, 可以基于新版试试

**Comment by chencjiajy** [comment]
> > 语句1：`g.E().groupCount().by(label)`
> > 语句2： `g.E().hasLabel('EDGE1').count()`
> > 语句1 与语句2的性能查询差异很大，语句1 可以查到库里每条边的计数，但是语句2如果边的数量比较多的话，可能会导致hugegraph的后端数据库挂掉。
> > 使用profile查看性能分析，语句1的"traverserCount"和"elementCount"因为包括所有的边应该是更大的，hugegraph做了哪些优化，从而使语句1可以查询得到，语句2太慢而查不到？
> 
> 话说这个问题现在有结论了么? 你查询的 `count()` 总数多少, 是使用异步的 gremlin 方式查询的么, 可以基于新版试试

`count()`总数是百万级， 不记得当时有没有测试使用异步的gremmin方式查询过了， 同步方式查询时语句2大概率会导致后端Hbase挂掉，一般统计个数主要也是为了了解数据量，知道会导致后端数据库挂掉之后，基本就没有直接使用语句2来统计了

**Comment by chencjiajy** [comment]
> > 语句1：`g.E().groupCount().by(label)`
> > 语句2： `g.E().hasLabel('EDGE1').count()`
> > 语句1 与语句2的性能查询差异很大，语句1 可以查到库里每条边的计数，但是语句2如果边的数量比较多的话，可能会导致hugegraph的后端数据库挂掉。
> > 使用profile查看性能分析，语句1的"traverserCount"和"elementCount"因为包括所有的边应该是更大的，hugegraph做了哪些优化，从而使语句1可以查询得到，语句2太慢而查不到？
> 
> 话说这个问题现在有结论了么? 你查询的 `count()` 总数多少, 是使用异步的 gremlin 方式查询的么, 可以基于新版试试

刚测了一下新版0.11.2，
对于语句1， 同步gremlin接口使用 的时候数据量超过80万会抛异常了( 应该是与[这个](https://github.com/hugegraph/hugegraph/pull/1088)有关系)
```
{'exception': 'com.baidu.hugegraph.exception.LimitExceedException',
 'message': 'Too many records(must <= 800000) for the query: `Query * from EDGE`',
 'cause': '[com.baidu.hugegraph.exception.LimitExceedException]'}
```

统计了几次耗时，语句2比语句1的速度要快了

**Comment by imbajin** [comment]
这类接近扫表的操作, 都应该使用异步接口来执行 `gremlin`, 都不会有你说的那个 `80w` 限制, 你可以试试.

**Comment by chencjiajy** [comment]
> 这类接近扫表的操作, 都应该使用异步接口来执行 `gremlin`, 都不会有你说的那个 `80w` 限制, 你可以试试.

是的，我忘记加一句说只能异步执行了，同步执行有80w限制，异步执行没有这个限制
