### ISSUE TITLE
有没有功能支持，输入gremlin语句的文本，解析后操作hugegraph，返回结果

### ISSUE THREAD

**Issue by youngkangrui** [hugegraph/hugegraph#1026]
输入文本g.V().hasLabel('person').out().has('name',within('vadas','josh'))
返回查询到的数据，就像在控制台操作一样

**Comment by javeme** [comment]
@youngkangrui 如果是需要纯粹的console控制台，可以启用gremlin-console（通过执行命令`bin/gremlin-console.sh`）；如果要集成到web页面，请使用gremlin rest api或者web-socket api。不过大部分情况使用hugegraph-studio或hugegraph-hubble界面会更加方便。

**Comment by youngkangrui** [comment]
> @youngkangrui 如果是需要纯粹的console控制台，可以启用gremlin-console（通过执行命令`bin/gremlin-console.sh`）；如果要集成到web页面，请使用gremlin rest api或者web-socket api。不过大部分情况使用hugegraph-studio或hugegraph-hubble界面会更加方便。

可以在spring中管理gremlin console吗?

**Comment by javeme** [comment]
@youngkangrui 可以集成到spring的，通过gremlin rest api的话，使用java-client即可：
```java
HugeClient client = new HugeClient("http://localhost:8080", "hugegraph");
GremlinManager gremlin = client.gremlin();
ResultSet resultSet = gremlin.gremlin("g.V().outE().path()").execute();
```

**Comment by youngkangrui** [comment]
> @youngkangrui 可以集成到spring的，通过gremlin rest api的话，使用java-client即可：
> 
> ```java
> HugeClient client = new HugeClient("http://localhost:8080", "hugegraph");
> GremlinManager gremlin = client.gremlin();
> ResultSet resultSet = gremlin.gremlin("g.V().outE().path()").execute();
> ```

多谢回复，我的需求是提供rpc服务，最后采用了下面这种方式，试了下没有问题，请问可以这么用吗？
 HugeScriptTraversal<Object, Object> traversal = new HugeScriptTraversal<>(hugeGraph.traversal(), "gremlin-groovy", script, bindings, aliases);
        while (traversal.hasNext()){
            ans.add(traversal.next().toString());
        }
