### ISSUE TITLE
在已经有了 edgelabel的情况下,能否为其加上multiTimes().sortKeys()

### ISSUE THREAD

**Issue by fisherinbox** [hugegraph/hugegraph#103]
### Expected behavior 期望表现
加上multiTimes().sortKeys()

### Actual behavior 实际表现
Not allowed to update frequency for edge label 'trade'

### Steps to reproduce the problem 复现步骤
1.schema.edgeLabel("trade").sourceLabel("role").targetLabel("role").properties("datetime","tradeType","server","ds").nullableKeys("datetime","tradeType","server","ds").ifNotExist().create();    已配置好,并且已经通过huegegraph-loader导入数据
2.在schema.groovy文档中加入一行,并重新导入数据schema.edgeLabel("trade").multiTimes().sortKeys("datetime").append();
或者通过hugegraph-client schema.edgeLabel("trade").multiTimes().sortKeys("datetime").append();
3. 

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by Linary** [comment]
目前是不允许给已存在的`EdgeLabel`追加`sortKeys`的，`EdgeLabel`允许追加的域仅包括：`properties`、`nullableKeys`和`userdata`
