### ISSUE TITLE
请教一个gremlin的连续指向语法。

### ISSUE THREAD

**Issue by 0x376h** [hugegraph/hugegraph#1031]
###基本定义：
点：kw。 点上有边。
边：nextword。定义：
{
    "id": 2,
    "name": "nextword",
    "source_label": "kw",
    "target_label": "kw",
    "frequency": "MULTIPLE",
    "sort_keys": [
        "sid",
        "start_pos"
    ],
    "nullable_keys": [],
    "index_labels": [
        "nextwordsid"
    ],
    "properties": [
        "start",
        "end",
        "start_pos",
        "end_pos",
        "sid"
    ],
    "enable_label_index": true,
    "user_data": {}
}
用来存储某个关键词的下一个词的位置（句子，开始位置，结束位置）。
目前能解决A ->nextword ->B的 sid
请教如何解决 A->nextword ->B ->nextword->C 。即一个组合词的下一个词。 而这个组合词可能由多个词组成？
 本来试过 多个nextword取交集，但本身数据量较大（约10多亿的边）。数据量大就会超时。

**Comment by javeme** [comment]
@0x376h 额没太明白问题是什么？是指怎么建模还是怎么用gremlin查询？另外可以详细说明下需求

**Comment by 0x376h** [comment]
目前情况如下：
使用hugegraph建立 具体的词 和句子 的关系，即：
1.一个词出现哪些句子中。
2.一个句子中出现哪些词
3.一个词的下一个词是什么
建立顶点 句子 词
边 
1.出现位置，词指向句子。包含句子id,出现位置
2.下一个词。词指向词。包含：句子id,开始位置，结束位置。
目前遇到问题。如果使用gremlin查询。
词ABC连续出现句子，并找到前一个情况下D的词聚合结果。

**Comment by javeme** [comment]
> 目前遇到问题。如果使用gremlin查询。
> 词ABC连续出现句子，并找到前一个情况下D的词聚合结果。

@0x376h 还是没明白问题是什么，希望完整的表达或加上示例
