### ISSUE TITLE
针对创建关系schema中sourceLable、targetLabel的设置

### ISSUE THREAD

**Issue by panxianglei** [hugegraph/hugegraph#1040]
我在用huge创建关系schema的时候，需要制定sourceLabel、targetLabel，但是在实际导入数据的时候，这两个的约束并没有起作用。这个有什么用呢？
比如：我创建的关系schema是：a-->b  但是我导入数据的是却是c--d的数据，他也能让导入到图数据库中。

**Comment by javeme** [comment]
@panxianglei 导入时使用`--check-vertex true`启用检查，可以防止这种情况，不过启用检查会影响性能。

**Comment by panxianglei** [comment]
如果不做检查，数据导入到huge中，在查询的时候会有什么问题吗？比如：和schema不匹配查询错误等
