### ISSUE TITLE
创建关系schema时，边label不能重复，那么双向问题如何解决呢？

### ISSUE THREAD

**Issue by panxianglei** [hugegraph/hugegraph#1041]
huge中约定创建关系边的label时不能重复，但是又有sourceLabel和targetLabel的约束，那么如果一条关系时双向该如何解决呢？
比如：a<-[gl]->b  这样我需要建两条关系吗？但是边的label都是gl，如何解决，还是说sourceLabel和targetLabel的限制没有作用到数据上。

**Comment by javeme** [comment]
@panxianglei 不太明确问题，是否可以具体说明下：双向边是指类似friend这种（比如person friend person），还是指类似follow这种?
如果是friend这种，比如有边：personA -friend-> personB，如果需要的话也可以再创建一条边：personB -friend->personA，这种情况没有限制的；当然一般情况下g.V(personB).both('friend')也可以查到personB的所有好友。
如果是follow这种，那么逻辑上这种边本身是具备方向，如果需要相互关注，也是可以的：personA -follow-> personB、personB -follow->personA；如果需要对同一种高效建立两个方向的边，则可以增加followedBy类型：personA -follow-> personB 或者 personB -followedBy->personA。

**Comment by javeme** [comment]
@panxianglei 不太明确问题，是否可以具体说明下：双向边是指类似friend这种（比如person friend person），还是指类似follow这种?
如果是friend这种，比如有边：personA -friend-> personB，如果需要的话也可以再创建一条边：personB -friend->personA，这种情况没有限制的；当然一般情况下g.V(personB).both('friend')也可以查到personB的所有好友。
如果是follow这种，那么逻辑上这种边本身是具备方向，如果需要相互关注，也是可以的：personA -follow-> personB、personB -follow->personA；如果需要对同一种高效建立两个方向的边，则可以增加followedBy类型：personA -follow-> personB 或者 personB -followedBy->personA。

**Comment by panxianglei** [comment]
schema.edgeLabel('friend').sourceLabel('Person').targetLabel('Dog').create(); //这个创建成功
schema.edgeLabel('friend').sourceLabel('Dog').targetLabel('Person').create(); //这个创建失败
