### ISSUE TITLE
使用GraphManager java api更新顶点属性的时候，报错：Automatic Id strategy is not supported now，但是数据已经更新了

### ISSUE THREAD

**Issue by hunter7727** [hugegraph/hugegraph#1046]
### Expected behavior 期望表现
做更新顶点属性时，正常执行，不报错

### Actual behavior 实际表现
执行报错，但顶点属性已经更新

### Steps to reproduce the problem 复现步骤
1、使用java client api版本为 hugegraph-client:1.8.5版本
2、执行下面代码复现
HugeClient hugeClient = new HugeClient("http://xxx.xxx.xxx.xxx:8080", "hugegraph");
        GraphManager graph = hugeClient.graph();

        Map<String, UpdateStrategy> updatingStrategies = new HashMap<>();
        updatingStrategies.put("normalizedName",UpdateStrategy.OVERRIDE);
        updatingStrategies.put("displayName",UpdateStrategy.OVERRIDE);
        updatingStrategies.put("lastKnownAffiliationId",UpdateStrategy.OVERRIDE);
        updatingStrategies.put("paperCount",UpdateStrategy.OVERRIDE);
        updatingStrategies.put("paperFamilyCount",UpdateStrategy.OVERRIDE);
        updatingStrategies.put("citationCount",UpdateStrategy.OVERRIDE);

        Vertex vertex = graph.getVertex(338280234207936512L);
        vertex.property("normalizedName","ssss");
        vertex.property("displayName","lll");
        List<Vertex> vertices = new LinkedList<>();
        vertices.add(vertex);

        BatchVertexRequest.Builder builder = BatchVertexRequest.createBuilder();
        builder.updatingStrategies(updatingStrategies);
        builder.vertices(vertices);
        BatchVertexRequest request = builder.build();

        graph.updateVertices(request);
3、报错堆栈信息：
Exception in thread "main" class java.lang.IllegalArgumentException: Automatic Id strategy is not supported now
	at com.baidu.hugegraph.exception.ServerException.fromResponse(ServerException.java:44)
	at com.baidu.hugegraph.client.RestClient.checkStatus(RestClient.java:100)
	at com.baidu.hugegraph.rest.RestClient.put(RestClient.java:185)
	at com.baidu.hugegraph.rest.RestClient.put(RestClient.java:167)
	at com.baidu.hugegraph.api.graph.VertexAPI.update(VertexAPI.java:72)
	at com.baidu.hugegraph.driver.GraphManager.updateVertices(GraphManager.java:178)
	at com.cyberplus.brain.hugeGraph.Example.main(Example.java:85)

### Specifications of environment 环境信息
- hugegraph version: 0.10.4
- operating system: centos 7.4, 16 CPUs, 128G RAM}
- hugegraph backend: cassandra 3.10, cluster with 3 nodes, 2 x 1.8TB SSD disk each node

**Comment by javeme** [comment]
@hunter7727 使用UpdateStrategy（updateVertices接口）的时候，不允许操作Automatic Id的顶点（因为语义冲突），可以使用appendVertexProperty接口

**Comment by hunter7727** [comment]
请问使用appendVertexProperty这个接口就是把之前的属性值给覆盖掉了对吗

**Comment by hunter7727** [comment]
> @hunter7727 使用UpdateStrategy（updateVertices接口）的时候，不允许操作Automatic Id的顶点（因为语义冲突），可以使用appendVertexProperty接口

请问使用appendVertexProperty这个接口就是把之前的属性值给覆盖掉了对吗
