### ISSUE TITLE
通过limit限制返回结果条件下仍报索引数超过80W错误

### ISSUE THREAD

**Issue by cxxly** [hugegraph/hugegraph#1049]
### Expected behavior 期望表现
返回正常结果

### Actual behavior 实际表现
Too many records(must <= 800000) for the query: Query for SECONDARY_INDEX where id in [] and [INDEX_LABEL_ID == 4, FIELD_VALUES == 26e33582-ba3d-479a-9e10-ccb719377be1]

### Steps to reproduce the problem 复现步骤
`g.V().hasLabel('process').has('timestamp', between('2020-06-03 04:34:25.000', '2020-06-03 04:39:25.000')).has('environmentId', 'xxxx-xxxx-xxxx-xxxx').limit(100)`
- environmentId有单列索引，索引节点数量超过80w

#### Vertex/Edge summary 数据量
- loaded vertices amount: {100万左右}
- loaded edges amount: {80左右}
- loaded time: {抛出异常}

### Specifications of environment 环境信息
- hugegraph version: {0.10.4}
- operating system: {centos 7.4, 32 CPUs, 128G RAM}
- hugegraph backend: {cassandra}

**Comment by javeme** [comment]
@lxb1111 请在0.10.4和0.11上分别尝试复现下，另外看了类似语句是否有问题：g.V('vid').inE().has('key', 'value').limit(100)（有无limit的两种情况对比）

**Comment by lxb1111** [comment]
@cxxly 谢谢你的问题反馈，确实存在上述情况，现在已经修复可以使用可以使用补丁版（https://github.com/hugegraph/hugegraph/releases/download/v0.10.4/hugegraph-0.10.4_2020-06-19.tar.gz）或最新版代码避免该问题

**Comment by shzcore** [comment]
Gremlin 执行失败，详细信息: Too many records(must <= 800000) for the query: Query for SECONDARY_INDEX where id in [] and [INDEX_LABEL_ID == 4, FIELD_VALUES == 26e33582-xxxxxxx-xxxxxxx]

**Comment by qq807274539** [comment]
我是0.10.4版本的，但是用了上面提到的那个补丁包还是不行。
语句：g.V().hasLabel("ZSTP_RY").filter({it.get().property("ZSTP_RY_GMSFHM").value().contains("610102")}).limit(200)
报错：Too many records(must <= 800000) for the query: Query for VERTEX_LABEL_INDEX where id prefix with 0x2d313a31ff and start with 0x2d313a31ff(inclusive)
---------------------------
@lxb1111 @javeme  请问可以帮忙看一下吗？十分感谢！
