### ISSUE TITLE
limit语句执行时机有误，导致查询结果不准确。

### ISSUE THREAD

**Issue by johnwaynerui** [hugegraph/hugegraph#1052]
### Expected behavior 期望表现
形如语句`g.V('1:837401253').bothE('know').has('act_id', '50069').limit(100)`

在没有limit条件下可以查询出500条数据，期望返回100条数据。

### Actual behavior 实际表现
实际返回5条数据，

### Steps to reproduce the problem 复现步骤

似乎先执行了limit和bothE，再执行has语句，导致查询结果变少。

**Comment by javeme** [comment]
类似的问题：
![image](https://user-images.githubusercontent.com/9625821/85613379-638bbb80-b68c-11ea-939c-ee84f7d891fb.png)
