### ISSUE TITLE
 gremlin-console 连接不上hugegrapg-server

### ISSUE THREAD

**Issue by jwdjqwyp** [hugegraph/hugegraph#1056]
sh gremlin-console.sh 

         \,,,/
         (o o)
-----oOOo-(3)-oOOo-----
plugin activated: HugeGraph
plugin activated: tinkerpop.server
plugin activated: tinkerpop.gephi
plugin activated: tinkerpop.utilities
plugin activated: tinkerpop.tinkergraph
gremlin> :remote connect tinkerpop.server conf/remote.yaml
==>Error during 'connect' - No such property: conf/remote.yaml for class: groovy.lang.Binding
gremlin> Configured 192.68.126.140:8182
groovysh_parse: 2: unexpected token: 126.140 @ line 2, column 19.
   Configured 192.68.126.140:8182
                     ^

1 error
Type ':help' or ':h' for help.
Display stack trace? [yN]
gremlin> Configured localhost/127.0.0.1:8182
groovysh_parse: 2: unexpected token: localhost @ line 2, column 12.
   Configured localhost/127.0.0.1:8182
              ^

1 error
Type ':help' or ':h' for help.
Display stack trace? [yN]
gremlin> 
gremlin> Configured localhost:8182
groovysh_parse: 2: unexpected token: localhost @ line 2, column 12.
   Configured localhost:8182
              ^

1 error
Type ':help' or ':h' for help.
Display stack trace? [yN]
gremlin> 
gremlin> Configured 127.0.0.1:8182
groovysh_parse: 2: unexpected token: 0.1 @ line 2, column 18.
   Configured 127.0.0.1:8182
                    ^

1 error
Type ':help' or ':h' for help.
Display stack trace? [yN]
gremlin>

**Comment by javeme** [comment]
@jwdjqwyp 执行gremlin-console.sh时的如果在bin目录中，则配置文件的目录需要改为"../conf/remote.yaml"，请参考：https://github.com/hugegraph/hugegraph/pull/1027#issuecomment-644627252
