### ISSUE TITLE
Don't accept query based on properties [name] that are not indexed in any label, may not match secondary conditio

### ISSUE THREAD

**Issue by wisdoms** [hugegraph/hugegraph#1061]
### Expected behavior 期望表现
能.够正常返回

### Actual behavior 实际表现
实际 返回错误信息： Don't accept query based on properties [name] that are not indexed in any label, may not match secondary conditio

### Steps to reproduce the problem 复现步骤
1. g.V().has('name','TIM').both().path()
2. 点击查询
3. 报错

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: 0.10.4
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by javeme** [comment]
@wisdoms 请在name属性上创建索引（index label）后再进行查询

**Comment by wisdoms** [comment]
按您说的这个方法，创建了索引后就不报错了，非常感谢，支持开源，支持百度。

**Comment by wisdoms** [comment]
在 name 属性上创建了索引后，索引类型 为  search(),  而且 name 属性是个主键，在使用语句  g.V().hasValue("测试").both() 查询时，报这样的错误： Error!
Not support query: Query for VERTEX where id in [] and [PROPERTIES containsv 测试] ，请问这种情况是什么原因？ hugegraph 库使用的是 rockdb ,

**Comment by wisdoms** [comment]
另外，还有个问题，我在特定的 label 中通过name 属性搜索时，也会报错，执行语句如下 ： g.V().hasLabel("entity").has('name',Text.contains("史雪梅")).bothE()
报错信息如下： Error!
Method userpropValues(List<String>) only used for secondary index, relation must be EQ, but got TEXT_CONTAINS
属性 name 上已创建了索引，索引类型： search 

但是在执行语句  g.V().has('name',Text.contains("史雪梅")).bothE()  不会报错，会把有其它 label 也都查出来了， 我只是想在特定的 label 中的进行查询

后端数据存储使用的是 rockdb ,

这种情况有没有什么解决办法？

**Comment by javeme** [comment]
> 另外，还有个问题，我在特定的 label 中通过name 属性搜索时，也会报错，执行语句如下 ： g.V().hasLabel("entity").has('name',Text.contains("史雪梅")).bothE()
> 报错信息如下： Error!
> Method userpropValues(List) only used for secondary index, relation must be EQ, but got TEXT_CONTAINS
> 属性 name 上已创建了索引，索引类型： search

@wisdoms 如果entity的索引是secondary类型，查询时请使用`g.V().hasLabel("entity").has('name', "史雪梅")`，如果需要使用`Text.contains`查询，需要对entity的name属性建立search索引。
可以使用如下语句查看所有的索引信息：`graph.schema().getIndexLabels()`

**Comment by javeme** [comment]
> 在 name 属性上创建了索引后，索引类型 为 search(), 而且 name 属性是个主键，在使用语句 g.V().hasValue("测试").both() 查询时，报这样的错误： Error!
> Not support query: Query for VERTEX where id in [] and [PROPERTIES containsv 测试] ，请问这种情况是什么原因？ hugegraph 库使用的是 rockdb ,

rocksdb不支持hasValue()对全图的查询

**Comment by wisdoms** [comment]
> > 另外，还有个问题，我在特定的 label 中通过name 属性搜索时，也会报错，执行语句如下 ： g.V().hasLabel("entity").has('name',Text.contains("史雪梅")).bothE()
> > 报错信息如下： Error!
> > Method userpropValues(List) only used for secondary index, relation must be EQ, but got TEXT_CONTAINS
> > 属性 name 上已创建了索引，索引类型： search
> 
> @wisdoms 如果entity的索引是secondary类型，查询时请使用`g.V().hasLabel("entity").has('name', "史雪梅")`，如果需要使用`Text.contains`查询，需要对entity的name属性建立search索引。
> 可以使用如下语句查看所有的索引信息：`graph.schema().getIndexLabels()`

**Comment by wisdoms** [comment]
> > 另外，还有个问题，我在特定的 label 中通过name 属性搜索时，也会报错，执行语句如下 ： g.V().hasLabel("entity").has('name',Text.contains("史雪梅")).bothE()
> > 报错信息如下： Error!
> > Method userpropValues(List) only used for secondary index, relation must be EQ, but got TEXT_CONTAINS
> > 属性 name 上已创建了索引，索引类型： search
> 
> @wisdoms 如果entity的索引是secondary类型，查询时请使用`g.V().hasLabel("entity").has('name', "史雪梅")`，如果需要使用`Text.contains`查询，需要对entity的name属性建立search索引。
> 可以使用如下语句查看所有的索引信息：`graph.schema().getIndexLabels()`

按照您说的这种方式，问题解决了，非常感谢！对 hugegraph  又多了进一步的了解

**Comment by wisdoms** [comment]
> > 在 name 属性上创建了索引后，索引类型 为 search(), 而且 name 属性是个主键，在使用语句 g.V().hasValue("测试").both() 查询时，报这样的错误： Error!
> > Not support query: Query for VERTEX where id in [] and [PROPERTIES containsv 测试] ，请问这种情况是什么原因？ hugegraph 库使用的是 rockdb ,
> 
> rocksdb不支持hasValue()对全图的查询

太感谢了，问题解决了。

**Comment by wisdoms** [comment]
另外想请教下这个 hugegraph 怎么发音呢？ 读   胡哥哥热佛 吗？
