### ISSUE TITLE
第一次 load 图失败，修改了 schema 再次 load 图时，此时 load 图所使用的 schema 还是第一次的 schema，这不合理吧

### ISSUE THREAD

**Issue by coooodeXjl** [hugegraph/hugegraph#1062]
### Expected behavior 期望表现
{type something here...}
第一次 load 图因为 schema 不正确失败，第二次 load 图使用修改后的 schema load 图

### Actual behavior 实际表现
{type something here...}
第一次 load 图因为 schema 不正确失败，第二次 load 图仍使用第一次 load 图时的 schema

### Steps to reproduce the problem 复现步骤
1. 初始化图
2. 制造一个错误的 schema文件，然后 load 图
3. 使用正确的 schema ，然后 load 图

### 版本
huge 0.10.4, loader 0.10.1

**Comment by Linary** [comment]
@coooodeXjl 这应该是你前后两次的schema同名，并且创建schema的语句使用了ifNotExist，ifNotExist 在 0.10.4版本中的语义是**如果已经存在同名的schema，就不再创建**，所以表现得像是使用了第一次的schema。

你有以下几种处理办法：

- 手动删除server的元数据，然后再次导入（相信你应该已经这么做了）；
- loader的master分支中，提供了一个命令行参数`--clear-all-data true`，导入前会删除server的全部数据，包括元数据；
- server的master分支中，优化了ifNotExist的语义，其变更为**如果存在完全相同的元数据则不创建**，如果只是名称相同但是有其他域（比如属性）不同，则会提示出错；

**Comment by coooodeXjl** [comment]
okk~ thanks
