### ISSUE TITLE
在多个时间段，俩节点发生了同一个关系，应当怎么存储多个时间

### ISSUE THREAD

**Issue by qingchengliu** [hugegraph/hugegraph#1063]
有这么一个场景：
目前图数据库中存在着 节点A-关系B-节点C，关系发生的时间为2020-01-01
此时有一个数据进来图数据库，节点A-关系B-节点C, 关系发生的时间为2020-06-30
之后我需要
1. 查询2019-12-12到2020-03-01这段时间内，节点A与节点C是否发生了关系B
2. 查询2020-04-01到2020-07-01这段时间内，节点A与节点C是否发生了关系B

对于此场景，我应该怎么存储节点A、关系B、节点C、与关系发生的时间

**Comment by javeme** [comment]
@qingchengliu 请使用sortkey，在创建edge-label时，指定边属性为sortkey即可（这里应该是【关系发生的时间】）

**Comment by qingchengliu** [comment]
> @qingchengliu 请使用sortkey，在创建edge-label时，指定边属性为sortkey即可（这里应该是【关系发生的时间】）

请问当frequency过多时，是否会使得查询时间指数级增加？

**Comment by javeme** [comment]
可以按照时间段合并，比如每周或每个月合并为1条边
