### ISSUE TITLE
调查：hbase后端增加配置项

### ISSUE THREAD

**Issue by javeme** [hugegraph/hugegraph#107]
由于hbase后端是0.7版才引入的，配置项还不完善，目前只支持设置服务端host与port，后续可以增加更多配置项。

**Comment by javeme** [comment]
zookeeper.znode.parent --反馈自tianzhijun

**Comment by imbadark** [comment]
> zookeeper.znode.parent --反馈自tianzhijun

+1, 同需要这个参数, 因为如果不是默认的`/hbase` , 比如多个ZK下改为了`/hbase2.0x` , 那么直接连接是肯定连不上的, 或者提供一下如何手动修改的方式
