### ISSUE TITLE
restful-api Gremlin traversal返回结果是乱码

### ISSUE THREAD

**Issue by lingxingzhang** [hugegraph/hugegraph#1072]
执行 curl -XGET "http://192.168.10.234:8081/gremlin?gremlin=hugegraph0701.traversal().V('1:account-00050')"
返回的结果 是压缩的结果吗？怎么解析呢？
![image](https://user-images.githubusercontent.com/64292411/86316471-6c1d5c80-bc5f-11ea-8892-d456e2d8427b.png)

**Comment by javeme** [comment]
@lingxingzhang 服务端返回的批量顶点/边是压缩（gzip）过的，可以使用管道重定向至gunzip进行解压（curl http://example | gunzip），也可以用Firefox的postman或者Chrome浏览器的restlet插件发请求，会自动解压缩响应数据。

**Comment by lingxingzhang** [comment]
好的 谢谢您
