### ISSUE TITLE
顶点属性是纯中文时，索引查询结果有误

### ISSUE THREAD

**Issue by javeme** [hugegraph/hugegraph#1074]
顶点属性是纯中文时，我测试的过程中是无法查询到结果的，如下面例子。
![image](https://user-images.githubusercontent.com/9625821/86329313-8ca5e080-bc78-11ea-8392-241344e6bfa3.png)
![image](https://user-images.githubusercontent.com/9625821/86329336-94658500-bc78-11ea-9b1b-7d9208ccebb2.png)

clone from: https://groups.google.com/forum/#!topic/hugegraph/qRUGxg_BYPQ

**Comment by javeme** [comment]
@lxb1111 请关注下这个问题

**Comment by lxb1111** [comment]
这个问题没有复现，创建search索引后， 正确的查询语句：g.V().hasLabel('PropertyTemplateSimple').has('name', Text.contains('防火等级'))

**Comment by zebraka** [comment]
graph.schema().indexLabel("PropertyTemplateSetByName2").onV("PropertyTemplate").by("name").search().ifNotExist().create();
g.V().hasLabel('PropertyTemplate').has('name',Text.contains('防火等级'));

创建了search索引，但执行查询时报错如下：
Error!

Don't accept query based on properties [name] that are not indexed in label 'PropertyTemplate', may not match secondary/search condition
