### ISSUE TITLE
rest API bindings 怎么绑定参数呢？

### ISSUE THREAD

**Issue by lingxingzhang** [hugegraph/hugegraph#1077]
POST http://192.168.10.234:8081/gremlin
{
    "gremlin": "g.V('11:marko')",
    "bindings": {},
    "language": "gremlin-groovy",
    "aliases": {
        "graph": "hugegraph0701", 
        "g": "__g_hugegraph0701"
    }
}

我可以使用bindings 将参数 11:marko 传入进去吗？怎么绑定参数呢？

**Comment by Linary** [comment]
@lingxingzhang 可以的，这样写：

```
{
    "gremlin": "g.V(a)",
    "bindings": {"a": "1:marko"},
    "language": "gremlin-groovy",
    "aliases": {"graph": "hugegraph0701", "g": "__g_hugegraph0701"}
}
```

**Comment by lingxingzhang** [comment]
@Linary 谢谢您
