### ISSUE TITLE
怎么查看异步任务的执行结果  

### ISSUE THREAD

**Issue by fisherinbox** [hugegraph/hugegraph#108]
### Expected behavior 期望表现
http://localhost:8080/graphs/hugegraph/jobs/gremlin
{
    "gremlin": "g.V('2:418700201').out().limit(10)",
    "bindings": {},
    "language": "gremlin-groovy",
    "aliases": {}
}
可以看到异步任务的执行结果,返回2:418700201  的10条out边

### Actual behavior 实际表现
通过GET http://localhost:8080/graphs/hugegraph/tasks/1  返回的"task_result": "10"并不是我想查询的结果

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by javeme** [comment]
结尾需要加上terminal step，比如g.V('2:418700201').out().limit(10).toList()

**Comment by yuyang0** [comment]
@javeme java客户端能不能给个示例代码？我得到了task的result，但是那字符串不知道是什么格式，总之不像是json

**Comment by javeme** [comment]
@yuyang0 Task的结果是Json格式的，请参考API文档：[6.1.2 查看某个异步任务的信息](https://hugegraph.github.io/hugegraph-doc/clients/restful-api/task.html)
 
java客户端示例如下：
```java
HugeClient client = new HugeClient("http://localhost:8080", "hugegraph");
Task task = client.task().get(id)
```

另外，异步执行gremlin示例如下：
```java
GremlinRequest.Builder builder = client.gremlin().gremlin(gremlin);
long taskId = builder.executeAsTask();
```

**Comment by yuyang0** [comment]
@javeme 我说的是result的部分，那是一个字符串，不知道是什么格式

**Comment by yuyang0** [comment]
@javeme 也就是说需要自己parse？

**Comment by javeme** [comment]
@yuyang0 是的需要自己解析，希望了解一下你的需求场景。
hugegraph的设计是不建议返回过于复杂的任务结果，任务的执行期间可通过如下方式来保存任务结果：更新属性、增加边或顶点等。

**Comment by javeme** [comment]
这个需求建议直接更新属性即可：
`g.V().has(xxx).outE().property('count', 'value-xxx').iterate()`

**Comment by yuyang0** [comment]
@javeme 我要增量更新，不能这样直接更新，必须得到原来的值，再说了即便可以直接更新也不是所有的边的值都一样

**Comment by zhoney** [comment]
@yuyang0 

**Gremlin异步执行**是为了解决一些执行时间比较长的任务，防止因请求超时而导致无法追踪执行情况的场景。

异步Task结构中的result是用来跟踪异步任务的执行结果，往往是:
- 最后一条语句的返回值
- 或是return的结果
是一个程序是否正常结束的标识，不建议用来记录大量的数据。
如果需要大量数据返回，可以在确认task正常结束后用同步的查询获取。

另外，Gremlin的异步执行是运行groovy程序，支持丰富的语法（包括局部变量，if-else，for循环等等）。上面提到的增量更新应该是可以在程序中做到的。

如有仍有疑问，可以描述一下您的场景、目标和程序片段，便于我们有针对性的帮您解决问题。
