### ISSUE TITLE
更新节点前如何避免写前读？

### ISSUE THREAD

**Issue by qingchengliu** [hugegraph/hugegraph#1080]
### Expected behavior 期望表现
更新节点时，避免写前读

### Steps to reproduce the problem 复现步骤

```
User = graph.schema().vertexLabel("User").properties("uid", "is_black", "is_frozen", "lmtime").primaryKeys("uid").nullableKeys("is_black", "is_frozen").ifNotExist().create()
Merchant = graph.schema().vertexLabel("Merchant").properties("mch_name", "mch_no", "lmtime").primaryKeys("mch_no", "mch_name").ifNotExist().create()

u = graph.addVertex(T.label, "User", "uid", 10086, "lmtime", "2020-02-04 00:00:00", "is_black", 1, "is_frozen", 0)
m = graph.addVertex(T.label, "Merchant", "mch_no", "10001", "lmtime", "2020-06-03 00:00:00", "mch_name", "测试2")
m.addEdge("MCH_CONN", u, "lmtime", "2020-02-03 00:00:00")
g.V().has("User", "uid", 10086).union(bothE(), bothE().bothV()).dedup()
```
此时我想更新 uid = 10086的lmtime，使用的是覆盖写
```
u = graph.addVertex(T.label, "User", "uid", 10086, "lmtime", "2020-07-04 00:00:00")
```
如果我使用覆盖写，原节点的`is_black`、`is_frozen`属性将会丢失
我应该怎么避免写前读且更新节点信息时不会丢失原有属性

**Comment by javeme** [comment]
@qingchengliu 属性更新包括：

- 单个属性更新：[2.1.3 更新顶点属性](https://hugegraph.github.io/hugegraph-doc/clients/restful-api/vertex.html)
- 批量属性更新（建议使用SSD盘）：[3.3.1 顶点和边映射 更新策略](https://hugegraph.github.io/hugegraph-doc/quickstart/hugegraph-loader.html)
- 极速更新部分属性：该功能仅商业版中才支持

**Comment by qingchengliu** [comment]
> @qingchengliu 属性更新包括：
> 
> * 单个属性更新：[2.1.3 更新顶点属性](https://hugegraph.github.io/hugegraph-doc/clients/restful-api/vertex.html)
> * 批量属性更新（建议使用SSD盘）：[3.3.1 顶点和边映射 更新策略](https://hugegraph.github.io/hugegraph-doc/quickstart/hugegraph-loader.html)
> * 极速更新部分属性：该功能仅商业版中才支持

我知道节点的id，但我不知道改id在不在数据库中（使用的是自定义id）。
如果按上述的方式，我需要先调用client的 `appendVertexProperty`，再根据返回的状态码（NoSuchElementException）来判断是否需要执行 `addVertex`。
这种方式会在发生写之前执行多了一次读操作（发生了多一次http请求）。
请问是否有类似于 `insertOrUpdate` 的接口（或者后续会不会开发此接口）
