### ISSUE TITLE
用Loader读取example时报错，log中出现不明文档内容

### ISSUE THREAD

**Issue by ZimengChen** [hugegraph/hugegraph#1081]
HugeGraph及Loader均为最新版0.10.*
后端为memory
按教程执行命令：bin/hugegraph-loader -g hugegraph -f example/file/struct.json -s example/file/schema.groovy
报错且没有终止运行，强行Ctrl+C终止后取log如下

方便阅读，已上传log文件
[hugegraph-loader.log](https://github.com/hugegraph/hugegraph/files/4878136/hugegraph-loader.log)

> 
> 2020-07-06 17:44:23 [main] [INFO ] com.baidu.hugegraph.loader.struct.GraphStruct [] - Checking vertex struct descriptions
> 2020-07-06 17:44:24 [main] [INFO ] com.baidu.hugegraph.loader.struct.GraphStruct [] - Checking edge struct descriptions
> 2020-07-06 17:44:25 [main] [ERROR] com.baidu.hugegraph.loader.HugeGraphLoader [] - ERROR: Failed to load
> com.baidu.hugegraph.rest.SerializeException: Failed to deserialize: <!DOCTYPE html><html>
>       <head>
>         <meta http-equiv="Content-type" content="text/html; charset=utf-8"/><link rel="stylesheet" href="/static/bootstrap.min.css" type="text/css"/><link rel="stylesheet" href="/static/vis.min.css" type="text/css"/><link rel="stylesheet" href="/static/webui.css" type="text/css"/><link rel="stylesheet" href="/static/timeline-view.css" type="text/css"/><script src="/static/sorttable.js"></script><script src="/static/jquery-1.12.4.min.js"></script><script src="/static/vis.min.js"></script><script src="/static/bootstrap-tooltip.js"></script><script src="/static/initialize-tooltips.js"></script><script src="/static/table.js"></script><script src="/static/additional-metrics.js"></script><script src="/static/timeline-view.js"></script><script src="/static/log-view.js"></script><script src="/static/webui.js"></script><script>setUIRoot('')</script>
>         
>         <link rel="shortcut icon" href="/static/spark-logo-77x50px-hd.png"></link>
>         <title>Spark Master at spark://spark-master:7077</title>
>       </head>
>       <body>
>         <div class="container-fluid">
>           <div class="row-fluid">
>             <div class="span12">
>               <h3 style="vertical-align: middle; display: inline-block;">
>                 <a style="text-decoration: none" href="/">
>                   <img src="/static/spark-logo-77x50px-hd.png"/>
>                   <span class="version" style="margin-right: 15px;">2.4.4</span>
>                 </a>
>                 Spark Master at spark://spark-master:7077
>               </h3>
>             </div>
>           </div>
>           <div class="row-fluid">
>           <div class="span12">
>             <ul class="unstyled">
>               <li><strong>URL:</strong> spark://spark-master:7077</li>
>               
>               <li><strong>Alive Workers:</strong> 1</li>
>               <li><strong>Cores in use:</strong> 32 Total,
>                 32 Used</li>
>               <li><strong>Memory in use:</strong>
>                 187.5 GB Total,
>                 1024.0 MB Used</li>
>               <li><strong>Applications:</strong>
>                 1 <a href="#running-app">Running</a>,
>                 13 <a href="#completed-app">Completed</a> </li>
>               <li><strong>Drivers:</strong>
>                 0 Running,
>                 0 Completed </li>
>               <li><strong>Status:</strong> ALIVE</li>
>             </ul>
>           </div>
>         </div><div class="row-fluid">
>           <div class="span12">
>             <span class="collapse-aggregated-workers collapse-table" onClick="collapseTable('collapse-aggregated-workers','aggregated-workers')">
>               <h4>
>                 <span class="collapse-table-arrow arrow-open"></span>
>                 <a>Workers (1)</a>
>               </h4>
>             </span>
>             <div class="aggregated-workers collapsible-table">
>               <table class="table table-bordered table-condensed table-striped sortable">
>       <thead><th width="" class="">Worker Id</th><th width="" class="">Address</th><th width="" class="">State</th><th width="" class="">Cores</th><th width="" class="">Memory</th></thead>
>       <tbody>
>         <tr>
>       <td>
>         <a href="http://172.18.0.5:8081">
>               worker-20200508034245-172.18.0.5-42373
>             </a>
>       </td>
>       <td>172.18.0.5:42373</td>
>       <td>ALIVE</td>
>       <td>32 (32 Used)</td>
>       <td sorttable_customkey="191998.1024">
>         187.5 GB
>         (1024.0 MB Used)
>       </td>
>     </tr>
>       </tbody>
>     </table>
>             </div>
>           </div>
>         </div><div class="row-fluid">
>           <div class="span12">
>             <span id="running-app" class="collapse-aggregated-activeApps collapse-table" onClick="collapseTable('collapse-aggregated-activeApps','aggregated-activeApps')">
>               <h4>
>                 <span class="collapse-table-arrow arrow-open"></span>
>                 <a>Running Applications (1)</a>
>               </h4>
>             </span>
>             <div class="aggregated-activeApps collapsible-table">
>               <table class="table table-bordered table-condensed table-striped sortable">
>       <thead><th width="" class="">Application ID</th><th width="" class="">Name</th><th width="" class="">Cores</th><th width="" class="">Memory per Executor</th><th width="" class="">Submitted Time</th><th width="" class="">User</th><th width="" class="">State</th><th width="" class="">Duration</th></thead>
>       <tbody>
>         <tr>
>       <td>
>         <a href="app?appId=app-20200701084434-0013">app-20200701084434-0013</a>
>         <form action="app/kill/" method="POST" style="display:inline">
>         <input type="hidden" name="id" value="app-20200701084434-0013"/>
>         <input type="hidden" name="terminate" value="true"/>
>         <a href="#" onclick="if (window.confirm('Are you sure you want to kill application app-20200701084434-0013 ?')) { this.parentNode.submit(); return true; } else { return false; }" class="kill-link">(kill)</a>
>       </form>
>       </td>
>       <td>
>         <a href="http://697520f3510b:4040">esc_tel_lightgbm</a>
>       </td>
>       <td>
>         32
>       </td>
>       <td sorttable_customkey="1024">
>         1024.0 MB
>       </td>
>       <td>2020/07/01 08:44:34</td>
>       <td>jovyan</td>
>       <td>RUNNING</td>
>       <td>121.0 h</td>
>     </tr>
>       </tbody>
>     </table>
>             </div>
>           </div>
>         </div><div>
>           
>         </div><div class="row-fluid">
>           <div class="span12">
>             <span id="completed-app" class="collapse-aggregated-completedApps collapse-table" onClick="collapseTable('collapse-aggregated-completedApps',
>                 'aggregated-completedApps')">
>               <h4>
>                 <span class="collapse-table-arrow arrow-open"></span>
>                 <a>Completed Applications (13)</a>
>               </h4>
>             </span>
>             <div class="aggregated-completedApps collapsible-table">
>               <table class="table table-bordered table-condensed table-striped sortable">
>       <thead><th width="" class="">Application ID</th><th width="" class="">Name</th><th width="" class="">Cores</th><th width="" class="">Memory per Executor</th><th width="" class="">Submitted Time</th><th width="" class="">User</th><th width="" class="">State</th><th width="" class="">Duration</th></thead>
>       <tbody>
>         <tr>
>       <td>
>         <a href="app?appId=app-20200701082853-0012">app-20200701082853-0012</a>
>         
>       </td>
>       <td>
>         esc_tel_lightgbm
>       </td>
>       <td>
>         32
>       </td>
>       <td sorttable_customkey="1024">
>         1024.0 MB
>       </td>
>       <td>2020/07/01 08:28:53</td>
>       <td>jovyan</td>
>       <td>FINISHED</td>
>       <td>15 min</td>
>     </tr><tr>
>       <td>
>         <a href="app?appId=app-20200701080119-0011">app-20200701080119-0011</a>
>         
>       </td>
>       <td>
>         esc_tel_lightgbm
>       </td>
>       <td>
>         32
>       </td>
>       <td sorttable_customkey="1024">
>         1024.0 MB
>       </td>
>       <td>2020/07/01 08:01:19</td>
>       <td>jovyan</td>
>       <td>FINISHED</td>
>       <td>27 min</td>
>     </tr><tr>
>       <td>
>         <a href="app?appId=app-20200701075548-0010">app-20200701075548-0010</a>
>         
>       </td>
>       <td>
>         esc_tel_lightgbm
>       </td>
>       <td>
>         32
>       </td>
>       <td sorttable_customkey="1024">
>         1024.0 MB
>       </td>
>       <td>2020/07/01 07:55:48</td>
>       <td>jovyan</td>
>       <td>FINISHED</td>
>       <td>5.3 min</td>
>     </tr><tr>
>       <td>
>         <a href="app?appId=app-20200619032946-0009">app-20200619032946-0009</a>
>         
>       </td>
>       <td>
>         train_lr_model
>       </td>
>       <td>
>         32
>       </td>
>       <td sorttable_customkey="1024">
>         1024.0 MB
>       </td>
>       <td>2020/06/19 03:29:46</td>
>       <td>jovyan</td>
>       <td>FINISHED</td>
>       <td>19 min</td>
>     </tr><tr>
>       <td>
>         <a href="app?appId=app-20200619032634-0008">app-20200619032634-0008</a>
>         
>       </td>
>       <td>
>         score_with_tel_model
>       </td>
>       <td>
>         32
>       </td>
>       <td sorttable_customkey="1024">
>         1024.0 MB
>       </td>
>       <td>2020/06/19 03:26:34</td>
>       <td>jovyan</td>
>       <td>FINISHED</td>
>       <td>3.2 min</td>
>     </tr><tr>
>       <td>
>         <a href="app?appId=app-20200619032417-0007">app-20200619032417-0007</a>
>         
>       </td>
>       <td>
>         score_with_user_model
>       </td>
>       <td>
>         32
>       </td>
>       <td sorttable_customkey="1024">
>         1024.0 MB
>       </td>
>       <td>2020/06/19 03:24:17</td>
>       <td>jovyan</td>
>       <td>FINISHED</td>
>       <td>2.3 min</td>
>     </tr><tr>
>       <td>
>         <a href="app?appId=app-20200619032111-0006">app-20200619032111-0006</a>
>         
>       </td>
>       <td>
>         evaluate_tel_model
>       </td>
>       <td>
>         32
>       </td>
>       <td sorttable_customkey="1024">
>         1024.0 MB
>       </td>
>       <td>2020/06/19 03:21:11</td>
>       <td>jovyan</td>
>       <td>FINISHED</td>
>       <td>2.7 min</td>
>     </tr><tr>
>       <td>
>         <a href="app?appId=app-20200619032101-0005">app-20200619032101-0005</a>
>         
>       </td>
>       <td>
>         train_tel_model
>       </td>
>       <td>
>         32
>       </td>
>       <td sorttable_customkey="1024">
>         1024.0 MB
>       </td>
>       <td>2020/06/19 03:21:01</td>
>       <td>jovyan</td>
>       <td>FINISHED</td>
>       <td>9 s</td>
>     </tr><tr>
>       <td>
>         <a href="app?appId=app-20200619031835-0004">app-20200619031835-0004</a>
>         
>       </td>
>       <td>
>         evaluate_user_model
>       </td>
>       <td>
>         32
>       </td>
>       <td sorttable_customkey="1024">
>         1024.0 MB
>       </td>
>       <td>2020/06/19 03:18:35</td>
>       <td>jovyan</td>
>       <td>FINISHED</td>
>       <td>2.2 min</td>
>     </tr><tr>
>       <td>
>         <a href="app?appId=app-20200619031828-0003">app-20200619031828-0003</a>
>         
>       </td>
>       <td>
>         train_user_model
>       </td>
>       <td>
>         32
>       </td>
>       <td sorttable_customkey="1024">
>         1024.0 MB
>       </td>
>       <td>2020/06/19 03:18:28</td>
>       <td>jovyan</td>
>       <td>FINISHED</td>
>       <td>7 s</td>
>     </tr><tr>
>       <td>
>         <a href="app?appId=app-20200619025857-0002">app-20200619025857-0002</a>
>         
>       </td>
>       <td>
>         parameter optimization
>       </td>
>       <td>
>         32
>       </td>
>       <td sorttable_customkey="1024">
>         1024.0 MB
>       </td>
>       <td>2020/06/19 02:58:57</td>
>       <td>jovyan</td>
>       <td>FINISHED</td>
>       <td>20 min</td>
>     </tr><tr>
>       <td>
>         <a href="app?appId=app-20200619025744-0001">app-20200619025744-0001</a>
>         
>       </td>
>       <td>
>         feature_selection
>       </td>
>       <td>
>         32
>       </td>
>       <td sorttable_customkey="1024">
>         1024.0 MB
>       </td>
>       <td>2020/06/19 02:57:44</td>
>       <td>jovyan</td>
>       <td>FINISHED</td>
>       <td>1.2 min</td>
>     </tr><tr>
>       <td>
>         <a href="app?appId=app-20200619025400-0000">app-20200619025400-0000</a>
>         
>       </td>
>       <td>
>         data_exploration
>       </td>
>       <td>
>         32
>       </td>
>       <td sorttable_customkey="1024">
>         1024.0 MB
>       </td>
>       <td>2020/06/19 02:54:00</td>
>       <td>jovyan</td>
>       <td>FINISHED</td>
>       <td>3.7 min</td>
>     </tr>
>       </tbody>
>     </table>
>             </div>
>           </div>
>         </div><div>
>           
>         </div>
>         </div>
>       </body>
>     </html>
> 	at com.baidu.hugegraph.rest.RestResult.readObject(RestResult.java:64) ~[hugegraph-common-1.6.11.jar:1.6.11.0]
> 	at com.baidu.hugegraph.api.version.VersionAPI.get(VersionAPI.java:42) ~[hugegraph-client-1.8.0.jar:1.8.0.0]
> 	at com.baidu.hugegraph.driver.VersionManager.getApiVersion(VersionManager.java:45) ~[hugegraph-client-1.8.0.jar:1.8.0.0]
> 	at com.baidu.hugegraph.driver.HugeClient.checkServerApiVersion(HugeClient.java:122) ~[hugegraph-client-1.8.0.jar:1.8.0.0]
> 	at com.baidu.hugegraph.driver.HugeClient.initManagers(HugeClient.java:108) ~[hugegraph-client-1.8.0.jar:1.8.0.0]
> 	at com.baidu.hugegraph.driver.HugeClient.<init>(HugeClient.java:72) ~[hugegraph-client-1.8.0.jar:1.8.0.0]
> 	at com.baidu.hugegraph.loader.util.HugeClientHolder.newHugeClient(HugeClientHolder.java:45) ~[hugegraph-loader-0.10.0.jar:?]
> 	at com.baidu.hugegraph.loader.util.HugeClientHolder.get(HugeClientHolder.java:33) ~[hugegraph-loader-0.10.0.jar:?]
> 	at com.baidu.hugegraph.loader.HugeGraphLoader.createSchema(HugeGraphLoader.java:108) ~[hugegraph-loader-0.10.0.jar:?]
> 	at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:85) [hugegraph-loader-0.10.0.jar:?]
> 	at com.baidu.hugegraph.loader.HugeGraphLoader.main(HugeGraphLoader.java:66) [hugegraph-loader-0.10.0.jar:?]
> Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
>  at [Source: <!DOCTYPE html><html>
>       <head>
>         <meta http-equiv="Content-type" content="text/html; charset=utf-8"/><link rel="stylesheet" href="/static/bootstrap.min.css" type="text/css"/><link rel="stylesheet" href="/static/vis.min.css" type="text/css"/><link rel="stylesheet" href="/static/webui.css" type="text/css"/><link rel="stylesheet" href="/static/timeline-view.css" type="text/css"/><script src="/static/sorttable.js"></script><script src="/static/jquery-1.12.4.min.js"></script><script src="/static/vis.min.js"></script><script src="/static/bootstrap-tooltip.js"></script><script src="/static/initialize-tooltips.js"></script><script src="/static/table.js"></script><script src="/static/additional-metrics.js"></script><script src="/static/timeline-view.js"></script><script src="/static/log-view.js"></script><script src="/static/webui.js"></script><script>setUIRoot('')</script>
>         
>         <link rel="shortcut icon" href="/static/spark-logo-77x50px-hd.png"></link>
>         <title>Spark Master at spark://spark-master:7077</title>
>       </head>
>       <body>
>         <div class="container-fluid">
>           <div class="row-fluid">
>             <div class="span12">
>               <h3 style="vertical-align: middle; display: inline-block;">
>                 <a style="text-decoration: none" href="/">
>                   <img src="/static/spark-logo-77x50px-hd.png"/>
>                   <span class="version" style="margin-right: 15px;">2.4.4</span>
>                 </a>
>                 Spark Master at spark://spark-master:7077
>               </h3>
>             </div>
>           </div>
>           <div class="row-fluid">
>           <div class="span12">
>             <ul class="unstyled">
>               <li><strong>URL:</strong> spark://spark-master:7077</li>
>               
>               <li><strong>Alive Workers:</strong> 1</li>
>               <li><strong>Cores in use:</strong> 32 Total,
>                 32 Used</li>
>               <li><strong>Memory in use:</strong>
>                 187.5 GB Total,
>                 1024.0 MB Used</li>
>               <li><strong>Applications:</strong>
>                 1 <a href="#running-app">Running</a>,
>                 13 <a href="#completed-app">Completed</a> </li>
>               <li><strong>Drivers:</strong>
>                 0 Running,
>                 0 Completed </li>
>               <li><strong>Status:</strong> ALIVE</li>
>             </ul>
>           </div>
>         </div><div class="row-fluid">
>           <div class="span12">
>             <span class="collapse-aggregated-workers collapse-table" onClick="collapseTable('collapse-aggregated-workers','aggregated-workers')">
>               <h4>
>                 <span class="collapse-table-arrow arrow-open"></span>
>                 <a>Workers (1)</a>
>               </h4>
>             </span>
>             <div class="aggregated-workers collapsible-table">
>               <table class="table table-bordered table-condensed table-striped sortable">
>       <thead><th width="" class="">Worker Id</th><th width="" class="">Address</th><th width="" class="">State</th><th width="" class="">Cores</th><th width="" class="">Memory</th></thead>
>       <tbody>
>         <tr>
>       <td>
>         <a href="http://172.18.0.5:8081">
>               worker-20200508034245-172.18.0.5-42373
>             </a>
>       </td>
>       <td>172.18.0.5:42373</td>
>       <td>ALIVE</td>
>       <td>32 (32 Used)</td>
>       <td sorttable_customkey="191998.1024">
>         187.5 GB
>         (1024.0 MB Used)
>       </td>
>     </tr>
>       </tbody>
>     </table>
>             </div>
>           </div>
>         </div><div class="row-fluid">
>           <div class="span12">
>             <span id="running-app" class="collapse-aggregated-activeApps collapse-table" onClick="collapseTable('collapse-aggregated-activeApps','aggregated-activeApps')">
>               <h4>
>                 <span class="collapse-table-arrow arrow-open"></span>
>                 <a>Running Applications (1)</a>
>               </h4>
>             </span>
>             <div class="aggregated-activeApps collapsible-table">
>               <table class="table table-bordered table-condensed table-striped sortable">
>       <thead><th width="" class="">Application ID</th><th width="" class="">Name</th><th width="" class="">Cores</th><th width="" class="">Memory per Executor</th><th width="" class="">Submitted Time</th><th width="" class="">User</th><th width="" class="">State</th><th width="" class="">Duration</th></thead>
>       <tbody>
>         <tr>
>       <td>
>         <a href="app?appId=app-20200701084434-0013">app-20200701084434-0013</a>
>         <form action="app/kill/" method="POST" style="display:inline">
>         <input type="hidden" name="id" value="app-20200701084434-0013"/>
>         <input type="hidden" name="terminate" value="true"/>
>         <a href="#" onclick="if (window.confirm('Are you sure you want to kill application app-20200701084434-0013 ?')) { this.parentNode.submit(); return true; } else { return false; }" class="kill-link">(kill)</a>
>       </form>
>       </td>
>       <td>
>         <a href="http://697520f3510b:4040">esc_tel_lightgbm</a>
>       </td>
>       <td>
>         32
>       </td>
>       <td sorttable_customkey="1024">
>         1024.0 MB
>       </td>
>       <td>2020/07/01 08:44:34</td>
>       <td>jovyan</td>
>       <td>RUNNING</td>
>       <td>121.0 h</td>
>     </tr>
>       </tbody>
>     </table>
>             </div>
>           </div>
>         </div><div>
>           
>         </div><div class="row-fluid">
>           <div class="span12">
>             <span id="completed-app" class="collapse-aggregated-completedApps collapse-table" onClick="collapseTable('collapse-aggregated-completedApps',
>                 'aggregated-completedApps')">
>               <h4>
>                 <span class="collapse-table-arrow arrow-open"></span>
>                 <a>Completed Applications (13)</a>
>               </h4>
>             </span>
>             <div class="aggregated-completedApps collapsible-table">
>               <table class="table table-bordered table-condensed table-striped sortable">
>       <thead><th width="" class="">Application ID</th><th width="" class="">Name</th><th width="" class="">Cores</th><th width="" class="">Memory per Executor</th><th width="" class="">Submitted Time</th><th width="" class="">User</th><th width="" class="">State</th><th width="" class="">Duration</th></thead>
>       <tbody>
>         <tr>
>       <td>
>         <a href="app?appId=app-20200701082853-0012">app-20200701082853-0012</a>
>         
>       </td>
>       <td>
>         esc_tel_lightgbm
>       </td>
>       <td>
>         32
>       </td>
>       <td sorttable_customkey="1024">
>         1024.0 MB
>       </td>
>       <td>2020/07/01 08:28:53</td>
>       <td>jovyan</td>
>       <td>FINISHED</td>
>       <td>15 min</td>
>     </tr><tr>
>       <td>
>         <a href="app?appId=app-20200701080119-0011">app-20200701080119-0011</a>
>         
>       </td>
>       <td>
>         esc_tel_lightgbm
>       </td>
>       <td>
>         32
>       </td>
>       <td sorttable_customkey="1024">
>         1024.0 MB
>       </td>
>       <td>2020/07/01 08:01:19</td>
>       <td>jovyan</td>
>       <td>FINISHED</td>
>       <td>27 min</td>
>     </tr><tr>
>       <td>
>         <a href="app?appId=app-20200701075548-0010">app-20200701075548-0010</a>
>         
>       </td>
>       <td>
>         esc_tel_lightgbm
>       </td>
>       <td>
>         32
>       </td>
>       <td sorttable_customkey="1024">
>         1024.0 MB
>       </td>
>       <td>2020/07/01 07:55:48</td>
>       <td>jovyan</td>
>       <td>FINISHED</td>
>       <td>5.3 min</td>
>     </tr><tr>
>       <td>
>         <a href="app?appId=app-20200619032946-0009">app-20200619032946-0009</a>
>         
>       </td>
>       <td>
>         train_lr_model
>       </td>
>       <td>
>         32
>       </td>
>       <td sorttable_customkey="1024">
>         1024.0 MB
>       </td>
>       <td>2020/06/19 03:29:46</td>
>       <td>jovyan</td>
>       <td>FINISHED</td>
>       <td>19 min</td>
>     </tr><tr>
>       <td>
>         <a href="app?appId=app-20200619032634-0008">app-20200619032634-0008</a>
>         
>       </td>
>       <td>
>         score_with_tel_model
>       </td>
>       <td>
>         32
>       </td>
>       <td sorttable_customkey="1024">
>         1024.0 MB
>       </td>
>       <td>2020/06/19 03:26:34</td>
>       <td>jovyan</td>
>       <td>FINISHED</td>
>       <td>3.2 min</td>
>     </tr><tr>
>       <td>
>         <a href="app?appId=app-20200619032417-0007">app-20200619032417-0007</a>
>         
>       </td>
>       <td>
>         score_with_user_model
>       </td>
>       <td>
>         32
>       </td>
>       <td sorttable_customkey="1024">
>         1024.0 MB
>       </td>
>       <td>2020/06/19 03:24:17</td>
>       <td>jovyan</td>
>       <td>FINISHED</td>
>       <td>2.3 min</td>
>     </tr><tr>
>       <td>
>         <a href="app?appId=app-20200619032111-0006">app-20200619032111-0006</a>
>         
>       </td>
>       <td>
>         evaluate_tel_model
>       </td>
>       <td>
>         32
>       </td>
>       <td sorttable_customkey="1024">
>         1024.0 MB
>       </td>
>       <td>2020/06/19 03:21:11</td>
>       <td>jovyan</td>
>       <td>FINISHED</td>
>       <td>2.7 min</td>
>     </tr><tr>
>       <td>
>         <a href="app?appId=app-20200619032101-0005">app-20200619032101-0005</a>
>         
>       </td>
>       <td>
>         train_tel_model
>       </td>
>       <td>
>         32
>       </td>
>       <td sorttable_customkey="1024">
>         1024.0 MB
>       </td>
>       <td>2020/06/19 03:21:01</td>
>       <td>jovyan</td>
>       <td>FINISHED</td>
>       <td>9 s</td>
>     </tr><tr>
>       <td>
>         <a href="app?appId=app-20200619031835-0004">app-20200619031835-0004</a>
>         
>       </td>
>       <td>
>         evaluate_user_model
>       </td>
>       <td>
>         32
>       </td>
>       <td sorttable_customkey="1024">
>         1024.0 MB
>       </td>
>       <td>2020/06/19 03:18:35</td>
>       <td>jovyan</td>
>       <td>FINISHED</td>
>       <td>2.2 min</td>
>     </tr><tr>
>       <td>
>         <a href="app?appId=app-20200619031828-0003">app-20200619031828-0003</a>
>         
>       </td>
>       <td>
>         train_user_model
>       </td>
>       <td>
>         32
>       </td>
>       <td sorttable_customkey="1024">
>         1024.0 MB
>       </td>
>       <td>2020/06/19 03:18:28</td>
>       <td>jovyan</td>
>       <td>FINISHED</td>
>       <td>7 s</td>
>     </tr><tr>
>       <td>
>         <a href="app?appId=app-20200619025857-0002">app-20200619025857-0002</a>
>         
>       </td>
>       <td>
>         parameter optimization
>       </td>
>       <td>
>         32
>       </td>
>       <td sorttable_customkey="1024">
>         1024.0 MB
>       </td>
>       <td>2020/06/19 02:58:57</td>
>       <td>jovyan</td>
>       <td>FINISHED</td>
>       <td>20 min</td>
>     </tr><tr>
>       <td>
>         <a href="app?appId=app-20200619025744-0001">app-20200619025744-0001</a>
>         
>       </td>
>       <td>
>         feature_selection
>       </td>
>       <td>
>         32
>       </td>
>       <td sorttable_customkey="1024">
>         1024.0 MB
>       </td>
>       <td>2020/06/19 02:57:44</td>
>       <td>jovyan</td>
>       <td>FINISHED</td>
>       <td>1.2 min</td>
>     </tr><tr>
>       <td>
>         <a href="app?appId=app-20200619025400-0000">app-20200619025400-0000</a>
>         
>       </td>
>       <td>
>         data_exploration
>       </td>
>       <td>
>         32
>       </td>
>       <td sorttable_customkey="1024">
>         1024.0 MB
>       </td>
>       <td>2020/06/19 02:54:00</td>
>       <td>jovyan</td>
>       <td>FINISHED</td>
>       <td>3.7 min</td>
>     </tr>
>       </tbody>
>     </table>
>             </div>
>           </div>
>         </div><div>
>           
>         </div>
>         </div>
>       </body>
>     </html>; line: 1, column: 2]
> 	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1487) ~[jackson-core-2.5.4.jar:2.5.4]
> 	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:518) ~[jackson-core-2.5.4.jar:2.5.4]
> 	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:447) ~[jackson-core-2.5.4.jar:2.5.4]
> 	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1461) ~[jackson-core-2.5.4.jar:2.5.4]
> 	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:683) ~[jackson-core-2.5.4.jar:2.5.4]
> 	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3604) ~[jackson-databind-2.5.4.jar:2.5.4]
> 	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3549) ~[jackson-databind-2.5.4.jar:2.5.4]
> 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2580) ~[jackson-databind-2.5.4.jar:2.5.4]
> 	at com.baidu.hugegraph.rest.RestResult.readObject(RestResult.java:62) ~[hugegraph-common-1.6.11.jar:1.6.11.0]
> 	... 10 more
> 2020-07-06 17:44:25 [main] [INFO ] com.baidu.hugegraph.loader.HugeGraphLoader [] - Stop loading then shutdown HugeGraphLoader
> 2020-07-06 17:45:28 [Thread-1] [INFO ] com.baidu.hugegraph.loader.HugeGraphLoader [] - Stop loading then shutdown HugeGraphLoader
>  
>

**Comment by javeme** [comment]
@ZimengChen 请检查下是否默认的端口8080属于其它程序的服务。

**Comment by Linary** [comment]
loader导入时默认往8080端口的hugegraph-server导，看你的日志应该时spark某个服务的端口占用了8080端口。导入命令中使用-p xxxx指定 hugegraph-server的端口。
