### ISSUE TITLE
loader 导入节点到 hbase 时，hugegraph:g_v表 488个分区全部写到同一台机器上

### ISSUE THREAD

**Issue by lingxingzhang** [hugegraph/hugegraph#1083]
hugegraph 版本说明 ：
      hugegraph-loader-0.10.1
      hugegraph-0.10.4
      hbase 2.0.0+6.0.1 （集群10台）

hugegraph 的存储后端是 hbase，使用loader导入节点 26亿数据，
   hugegraph:g_v 表有 488个分区 全部写到了同一个机器上了 ？？？？？
   hugegraph:g_si 表有165个分区 可以均匀的分布到其他的机器上 这个没有问题

日志报错：
       Failed to commit, there may be inconsistent states for HBase

**Comment by lingxingzhang** [comment]
@javeme 您好 您有空帮我看一下 🙏

**Comment by javeme** [comment]
@lingxingzhang 目前只能先通过预分区来防止该问题，后续会提供自动化完整的解决方案，请关注 #822 。相关信息请参考：#469 #762

**Comment by imbajin** [comment]
这是**Hbase**的问题, 和图基本没什么关系. 对图来说, 它相当于使用Hbase-Client而已. 并不会关注region分布和大小, 也**无法**控制.

然后我说一下可能的原因和解决方法. 原因**可能**有两个:
1. Hbase-procedure的[bug](https://issues.apache.org/jira/browse/HBASE-23564), 偶发. 通过Arthas/UI观察可以确定
2. Hbase的balance策略没有调整, 默认基于RegionServer节点, 可能造成机器均匀, 但表不匀

解决方案:
1. 修改balance策略为基于表(table), 相关配置你自己去hbase文档搜一下就行
2. **重启HMaster节点**, 手动执行一次balance (应用新策略, 然后也可以排除第一个可能的bug)
3. 如果1, 2完成后, 仍然没有改善, 再考虑尝试重启整个Hbase-RS集群, 如果仍存在问题, 可以再反馈

**Comment by lingxingzhang** [comment]
@imbajin 您好 我们这个问题还没有解决呢！要麻烦一下您
1 预建分区
	10台集群，我们预建了10个分区，然而每个表的分区的分裂也是到自己对应机器上并没有balance
2 修改 balance的级别
	hbase-site.xml 配置文件新增如下的配置 并重启整个hbase的集群
		hbase.master.loadbalance.bytable:true
		hbase.coprocessor.master.classes:org.apache.hadoop.hbase.regroup.RSGroupAdminEndpoint
		hbase.master.loadbalance.classes:org.apache.hadoop.hbase.regroup.RSGroupBasedLoadBalancer

 默认一个分区，没有预分区，依旧是所有的分区在一台机器上
 
 我们测试的时候 在我们的测试环境和开发环境都测试了
 测试环境 hbase 10台集群
 开发环境 hbase 18台集群

为什么hugegraph:g_v的分区都在同一台机器上 而hugegraph:g_si就可以均匀分布呢？

**Comment by imbajin** [comment]
1. 注意先看看是否有开启`RSGoup`呢, 默认是不开启的.  那你2/3的配置可能是不生效的.
2. 然后你再修改一下默认的balance划分策略, 默认是一个复杂策略, 改成`Simple`. 配置参考如下
  ```xml
<property>
  <name>hbase.rsgroup.grouploadbalancer.class</name>
  <value>org.apache.hadoop.hbase.master.balancer.SimpleLoadBalancer</value>
</property>
```
3. 配完重启HMaster, 然后手动hshell执行`balance`看看
4. 如果仍然没有变化, 尝试手动Hshell中move一下点表的region到其他节点, 看看能否成功, 是否会被搬回来.

至于你说两个集群都是一样的情况, 感觉就不太对劲
我们线上的测试/生产Hbase环境没有出现你说的情况, 当然Hbase和Server版本略有差别.
如果1~4你执行之后仍有问题, 可以补充一下:
- Hbase**具体**的版本
- 截图一下你Hbase的UI首页信息
- Hbase的详细配置
- 你说给图建了10个预分配的region, 你是怎么操作的呢? 是初始化完毕之后, 你手动split么, 没太明白.

**Comment by lingxingzhang** [comment]
@imbajin 您好 
 可以问一下您的公司hbase的版本，我们的hbase的版本是 hbase2.0.0-chd6.0.1，我们想直接尝试升级和你们一样的hbase版本
 你们在使用hugegraph的时候 会对所有的表进行预分区吗？还是其中的几张表进行预分区？

**Comment by wanghailin163** [comment]
@imbajin 您好
我们改了hbase的平衡策略后(已经改为org.apache.hadoop.hbase.master.balancer.SimpleLoadBalancer)，现在hugegraph:g_v表的region可以均匀分布，但是通过hugegraph-loader-0.10.1写入数据会比以前慢10倍，这是可能会是什么原因呢？如果是hbase参数不对，我们需要怎样优化hbase的参数？

**Comment by imbajin** [comment]
版本是2.2.x 你可以参考Hbase社区稳定GA版本. 

至于预分区的问题目前不好做, 图还没有原生支持. 默认情况是1个region自动分裂和balance, **初始化**导入速度的确会有比较大的影响, 但是还没见过你说的都在一台机器上的情况. 最终还是会均匀分配region的.

如果你们有人做数据采样, 然后自己改代码预分配另说.

**Comment by lingxingzhang** [comment]
@imbajin 感谢大佬的耐心解答 我们的hbase问题解决了 就是修改了平衡策略为simple，十分感谢大佬的解答！！！
