### ISSUE TITLE
关于图库 hugegraph 使用问题

### ISSUE THREAD

**Issue by wisdoms** [hugegraph/hugegraph#1091]
老师好，关于图库这个我问下 hugegraph  建议使用哪种数据库在存储图库的数据， 如果图数据从 cassandra 库  迁移到  hbase 中，会不会有数据丢失。 即 hugegraph 连接 cassandran , 通过 hugegraph 导出数据 ，然后 hugegraph 再连接 hbase , 将之前 导出的数据 导入进去， 这样数据 会不会丢失或导入不进？

**Comment by suesunss** [comment]
@wisdoms 可以使用 [HugeGraph-Tools](https://github.com/hugegraph/hugegraph-tools) 将 Cassandra 的数据备份到外置存储（比如 hdfs、本地磁盘），然后恢复到 hbase。

关于底层存储的建议，issue 里有很多参考，例如：
- [部署 hugegraph-server 对机器资源有特别的要求吗](https://github.com/hugegraph/hugegraph/issues/159)
- [hugegraph-server和loader的内存占用问题，以及性能问题](https://github.com/hugegraph/hugegraph/issues/116)

建议根据具体使用场景决定。

**Comment by suesunss** [comment]
@wisdoms 如果图在不同的 server，也可以使用 hugegraph-tools 的 migrate 命令。

**Comment by wisdoms** [comment]
在使用 Automatic  自动 id 策略时， 顶点 与顶点间的边在 hugegraph-studio 中查询 不到，只能查到孤立的点，边没有添加进去， 
在添加边时，如果 graph.addEdges(linkedEdge, true) , 第二个参数传递 true ，会报 java.lang.IllegalArgumentException: Invalid vertex id '347690486485483520'

**Comment by javeme** [comment]
@wisdoms 你是指使用hugegraph-tools无法正常导入导出Automatic的顶点吗？还是指使用client或api无法添加进去？前者是非预期的，后者是预期的，如果需要恢复数据建议使用hugegraph-tools。

@lxb1111 请验证下是否Automatic-Id策略的导入导出功能是否正常。

**Comment by lxb1111** [comment]
已经验证过hugegraph-tools导入导出Automatic的顶点的问题，可以正常使用。@wisdoms有什么问题可以详细描述一下方便快速定位问题。
