### ISSUE TITLE
hugegraph-tools-1.4.0备份时,没有备份边数据

### ISSUE THREAD

**Issue by gudehuang** [hugegraph/hugegraph#1097]
### Expected behavior 期望表现
执行命令
```
bin/hugegraph  --url http://localhost:8050 backup -t all -d localBackupDir/
```
期望可以备份所有数据(元数据,顶点,边)

### Actual behavior 实际表现
结果
```
Graph 'hugegraph' start backup!
Property key backup started
Property key backup finished: 90
Vertex label backup started
Vertex label backup finished: 20
Edge label backup started
Edge label backup finished: 35
Index label backup started
Index label backup finished: 68
Vertices backup started
Vertices has been backup: 491
Vertices backup finished: 491
Edges backup started
Edges has been backup: 0
Edges backup finished: 0
===============================================
backup summary: {
        property key number: 90,
        vertex label number: 20,
        edge label number: 35,
        index label number: 68,
        vertex number: 491,
        edge number: 0,
}
cost time(s): 0
```
实际情况:没有备份边数据.
图数据库中是有边数据的,但不知道为什么没有备份边数据

**Comment by zhoney** [comment]
@gudehuang 确定图数据库里是有边的吗？backup前后查询边确认一下。

如果问题还是存在的话，提供下复现步骤和部分示例数据，方便我们定位问题。

**Comment by gudehuang** [comment]
> @gudehuang 确定图数据库里是有边的吗？backup前后查询边确认一下。
> 
> 如果问题还是存在的话，提供下复现步骤和部分示例数据，方便我们定位问题。

![image](https://user-images.githubusercontent.com/20537541/87654826-074b2180-c78a-11ea-8773-559e793306ff.png)
我这里查边的时候提示有一些边的id有问题,可能是这些有问题的边导致无法备份边数据.
请问如何删除这些有问题的边?
![image](https://user-images.githubusercontent.com/20537541/87655143-70cb3000-c78a-11ea-936c-64c34f7a6608.png)

**Comment by gudehuang** [comment]
> @gudehuang 确定图数据库里是有边的吗？backup前后查询边确认一下。
> 
> 如果问题还是存在的话，console或者日志是否有错误信息，有的话提供下。另外也提供下复现步骤和部分示例数据，方便我们定位问题。

后端存储使用rocksdb
backend=rocksdb
数据文件如下
[rockdb_data.zip](https://github.com/hugegraph/hugegraph/files/4930728/rockdb_data.zip)

**Comment by zhoney** [comment]
@gudehuang 可以清理掉数据重来，清理方法:
1. tools的clear
2. clear RESTful API
3. 删掉rocksdb的数据目录，重新init-store，重新start server

**Comment by gudehuang** [comment]
> @gudehuang 可以清理掉数据重来，清理方法:
> 
> 1. tools的clear
> 2. clear RESTful API
> 3. 删掉rocksdb的数据目录，重新init-store，重新start server

请问如果我想保留现在的数据(顶点,边)该如何操作?
目前backup操作不能备份边数据.
