### ISSUE TITLE
不懂就问，请问有Python API吗？

### ISSUE THREAD

**Issue by xxh0523** [hugegraph/hugegraph#1099]
小白提问，请问支持Python直接操作数据库吗？比如gremlinpython可以吗？
新手问题，还望不吝解答。感谢！

**Comment by javeme** [comment]
目前官方仅提供java版client，python的client可自己根据rest-api实现。gremlinpython理论上也是可以使用的，不过功能只能使用gremlin子集。

**Comment by shangrilaxie** [comment]
不知道Hugegraph为什么不支持Connecting via withRemote？

**Comment by imbajin** [comment]
> 不知道Hugegraph为什么不支持Connecting via withRemote？
> 
> 

你说的是gremlin remote么，支持的，可以搜一下相关issue

另外可以说一下使用gremlin链接模式的必要性和场景么
