### ISSUE TITLE
启动HugeGraph提示失败，但线程已经起起来

### ISSUE THREAD

**Issue by kidleaf-jiang** [hugegraph/hugegraph#110]
### Expected behavior 期望表现
{type something here...}
启动HugeGraph server的时候，因为配置错误，提示启动失败，预期是程序没有起起来。 

### Actual behavior 实际表现
{type something here...}
实际上线程已经起起来了。但并没有生成pid file。 
stop脚本，是根据pid file，但这个时候，pid file还没有，所以stop的时候，说线程没起。 stop失败。
后续使用start脚本也会提示端口已经被占用，启动不起来。

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}  0.8.0
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}  centos 7.4
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node} Rocksdb

**Comment by javeme** [comment]
@Linary ![image](https://user-images.githubusercontent.com/9625821/46927767-bca6ed80-d069-11e8-9672-23a4bed107f4.png)

**Comment by zhouyang209117** [comment]
这个问题可以看下日志，只要提示启动失败，日志里面肯定会有报错的信息。
