### ISSUE TITLE
limit语句查询有问题

### ISSUE THREAD

**Issue by gudehuang** [hugegraph/hugegraph#1100]
### Expected behavior 期望表现
执行下面语句,可以查到数据
```
g.V().hasLabel('medicine').has('medicineName','雙花解毒膠囊').has('medicineType',0)
```
![2020-07-20-15-46-55](https://user-images.githubusercontent.com/20537541/87913043-058ea000-caa1-11ea-9fd1-b5ba0329fdd2.png)

在后面加上limit后
```
g.V().hasLabel('medicine').has('medicineName','雙花解毒膠囊').has('medicineType',0).limit(1)
```
![2020-07-20-15-47-50](https://user-images.githubusercontent.com/20537541/87913062-0a535400-caa1-11ea-9316-f177082aa0bc.png)

### Actual behavior 实际表现

在后面加上limit后
```
g.V().hasLabel('medicine').has('medicineName','雙花解毒膠囊').has('medicineType',0).limit(1)
```
查询结果为空
![2020-07-20-15-47-50](https://user-images.githubusercontent.com/20537541/87913062-0a535400-caa1-11ea-9316-f177082aa0bc.png)

目前有部分数据会出现这种情况,其它数据加上limit之后得到的结果是正常的

**Comment by javeme** [comment]
@gudehuang 这个是一个bug，多个has+limit存在该问题，正在修复中，类似 #1049
