### ISSUE TITLE
hugegraph loader 错误

### ISSUE THREAD

**Issue by liangshuang110** [hugegraph/hugegraph#1102]
插入大量顶点时，插入到180多万的时候报“ERROR: More than 500 vertices insert error, stop parsing and waiting other insert tasks finished”
log说是INSERT ERROR: Exception in backend 
什么原因造成的啊，是因为内存不够吗

**Comment by Linary** [comment]
看一下`logs/hugegraph-loader.log`，里面有出错的原因。

**Comment by liangshuang110** [comment]
添加顶点时候，属性主键是带空格、还有带http 作为插入不进去

**Comment by Linary** [comment]
什么意思？是说主键属性值里面有空格、http这样的字符吗？这个没影响的。

**Comment by liangshuang110** [comment]
主键属性值里面有http可以查到了，原因是“：”字符前面需要加上“`”字符；
主键属性值里面有空格字符还是查不到，例如，我顶点文件中有“     b” 字符串的数据，为什么g.V("     b")搜索不到，并且看loader的log也没有报错，全部读取成功

**Comment by liangshuang110** [comment]
“b”里面有空格，查询时候也把空格加里面

**Comment by javeme** [comment]
@liangshuang110 请使用如下语句进行查询：`g.V().hasLabel('xx').has('key', ' b')`

**Comment by liangshuang110** [comment]
ok，谢谢

**Comment by liangshuang110** [comment]
输入查询语句g.V().hasLabel('Entity').and(both().count().is(eq(0)))
web报错：
Error!
Failed to do request

**Comment by liangshuang110** [comment]
什么原因造成的，是数据量太大吗？其他数据量小的没有报错

**Comment by javeme** [comment]
@liangshuang110 应该是数据量太大超时了，可以增加limit试试：`g.V().hasLabel('Entity').limit(10000).and(both().count().is(eq(0)))`

**Comment by liangshuang110** [comment]
感谢大哥

**Comment by liangshuang110** [comment]
您好，我想对所有顶点进行遍历，不加limit()就请求超时，请问如何在不加limit()情况下请求不超时啊
