### ISSUE TITLE
如何将label的已有property移除掉？

### ISSUE THREAD

**Issue by youngkangrui** [hugegraph/hugegraph#1107]
![image](https://user-images.githubusercontent.com/23549507/88248292-40781a00-ccd3-11ea-90c6-6d1adc54db7f.png)
https://hugegraph.github.io/hugegraph-doc/changelog/hugegraph-0.9.2-release-notes.html

这个0.9的文档里有这部分的描述，请问具体怎么操作

**Comment by chencjiajy** [comment]
[文档](https://hugegraph.github.io/hugegraph-doc/clients/restful-api/vertexlabel.html)里说不支持移除property
> 1.2.2 为已存在的VertexLabel添加properties或userdata，或者移除userdata（目前不支持移除properties）

不过不确定是不是现在已经支持移除property了
