### ISSUE TITLE
异步任务的结果会一直缓存在内存中吗,只能删除异步任务吗,有没有过期时间设置

### ISSUE THREAD

**Issue by fisherinbox** [hugegraph/hugegraph#111]
### Expected behavior 期望表现
{type something here...}

### Actual behavior 实际表现
{type something here...}

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by javeme** [comment]
异步任务的结果在任务执行完成后会从内存中移除，仅仅存在于后端存储中。删除异步任务是指从后端存储中删除任务信息。

**Comment by fisherinbox** [comment]
@javeme 异步任务id会一直增长吗,删除了前面的异步任务之后,新的异步任务好像也没有使用前面的id

**Comment by javeme** [comment]
@fisherinbox 是的，异步任务id会一直增长。
