### ISSUE TITLE
gremlin语句执行超时，想要修改默认的超时时长，怎么修改呢？

### ISSUE THREAD

**Issue by lingxingzhang** [hugegraph/hugegraph#1112]
@imbajin 您好
我们执行的gremlin语句都比较耗时，会报错 read timed out，想要修改超时时长，可以在哪里设置吗？

**Comment by imbajin** [comment]
文档[配置页面](https://hugegraph.github.io/hugegraph-doc/config/config-option.html), 搜`timeout`
然后你把所有可以设置的都改成你想要的时间就行. 
`gremlin-server` 和 `rest-server` 两个配置文件里都有相应选项, 可以都改一下

**Comment by javeme** [comment]
@lingxingzhang 改以下2个配置，默认都是30s：
rest-server.properties `restserver.request_timeout`（单位秒）、
gremlin-server.yaml `scriptEvaluationTimeout`（单位毫秒）

如果是Cassandra也可以改：rest-server.properties `cassandra.read_timeout`

**Comment by lingxingzhang** [comment]
好的 谢谢您
