### ISSUE TITLE
gremlin语句查询结果问题

### ISSUE THREAD

**Issue by I-DO-NOT-KNOW** [hugegraph/hugegraph#1117]
如图，执行in()的时候返回的是没有数据的
但是使用count()的时候返回1

![gremlin1](https://user-images.githubusercontent.com/20416323/88641954-7281e580-d0f2-11ea-9475-c9f805bf2c18.png)
![gremlin2](https://user-images.githubusercontent.com/20416323/88642067-947b6800-d0f2-11ea-973e-549081e14abc.png)

### Specifications of environment 环境信息
- hugegraph version: 0.10

**Comment by javeme** [comment]
@I-DO-NOT-KNOW 是否提供一下复现的流程呢？谢谢
