### ISSUE TITLE
hugegraph 多图配置rocksdb报错

### ISSUE THREAD

**Issue by liangshuang110** [hugegraph/hugegraph#1118]
多图配置，ubuntu系统没有问题，centos系统就报错。
报错内容：[ERROR] com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore [] - Failed to open RocksDB 'rocksdb-data/m'
org.rocksdb.RocksDBException: lock : rocksdb-data/m/LOCK: 没有可用的锁
这是什么原因啊

**Comment by javeme** [comment]
@liangshuang110 清空一下目录rocksdb-data再重新初始化试试看？是否有更多的日志

**Comment by liangshuang110** [comment]
删除了，但还是没有成功；最后在多图配置的配置文件中，俩个图用不同的rocksdb路径就成功了，不知道会不会有影响

**Comment by javeme** [comment]
@liangshuang110 配到不同的目录不会有什么影响的。

**Comment by liangshuang110** [comment]
好的谢谢。还有个问题web输入g.V().hasLabel('Entity').count()
为什么返回
Error!
Failed to do request
是因为数据量太大的原因吗

**Comment by liangshuang110** [comment]
还有个问题，我输入g.V().hasLabel('Entity').map(outE('Contact').count()).max()类型的查询报
Error!
Too many records(must <= 800000) for the query: 
是和之前limit一样的问题吗？我用的10版本，到11版本就可以了吗
