### ISSUE TITLE
关于查询到目标数据库集后，返回的List<Vertex>如何能够包含与起点的“度”数，或者深度

### ISSUE THREAD

**Issue by kevinliang-123** [hugegraph/hugegraph#1122]
请问：
做一个是类人脉的需求，即已当前登录用户为起点，按照其输入的查询条件找到符合条件的目标用户集合，想在返回这个目标用户集合的同时，能够直到起点用户与每个目标用户所经历的度数（深度）；如何能在一个查询中完成？目前已经能够查询出目标用户集合，但是深度不知如何高效的一起出来？
语句如下：
g.V().hasLabel('person').has('userPlatId','9d7f406d8b9c48e3869d92ef67139cd4').repeat(both()).until(loops().is(gte(3)))
.emit(has('userName',Text.contains('大海')).or().has('companyName',Text.contains('大海')).or().has('userName',Text.contains('七匹狼')).or().has('companyName',Text.contains('七匹狼')))
.where(has('userName',Text.contains('大海')).or().has('companyName',Text.contains('大海')).or().has('userName',Text.contains('七匹狼')).or().has('companyName',Text.contains('七匹狼')))
.dedup().hasLabel('person')

结果集如下：
id	label	properties
2e08d272c5c44ba98e45c6b89a2f124e周少雄	person	{"companyName":"-广东七匹狼-测试企业","userPlatId":"9d7f406d8b9c48e3869d92ef67139cd4","userMembeId":"023e5031e00d43abafb260d9782633fa","userName":"周少雄","userPlatPhone":"17655356772","userMemberPhone":"13877658899","jobtitles":"会长"}
be031c37ba8e45e39a1418328005ba32熊大海	person	{"userPlatId":"d19853e2393946338c7e9e4bd28db6fe","userMembeId":"46c9803fddb04714a06dc8749bac8402","userName":"熊大海","userPlatPhone":"15788898899","userMemberPhone":"15788898899","jobtitles":"副主席"}
c239c41a028e496b88008831da735927大海朋友	person	{"userPlatId":"a8jeksd9sdsdu8f9sdf8sf9sdf89sf89","userName":"大海朋友","userPlatPhone":"17766776677"}

如何能够在在显示目标用户的同时，带有几度的值，也即使loops()的实际值

**Comment by javeme** [comment]
@kevinliang-123 请尝试path step，获取路径的长度。

**Comment by kevinliang-123** [comment]
> @kevinliang-123 请尝试path step，获取路径的长度。

谢谢，我尝试下。
