### ISSUE TITLE
Gremlin  step ValueMap报错

### ISSUE THREAD

**Issue by chencjiajy** [hugegraph/hugegraph#1125]
### Expected behavior 期望表现
查询所有数据时都可以使用ValueMap

### Actual behavior 实际表现
有些节点可以使用ValueMap， 有些不可以

### Steps to reproduce the problem 复现步骤
![example1](https://user-images.githubusercontent.com/19321967/88877835-0968b200-d259-11ea-934c-113f0e18301a.png)
![example2](https://user-images.githubusercontent.com/19321967/88877846-108fc000-d259-11ea-96cc-a805cb6e43c9.png)

### Specifications of environment 环境信息
- hugegraph version: 0.10.4
- hugegraph backend: Hbase

**Comment by javeme** [comment]
@chencjiajy 使用rest接口直接调用有问题吗？可能是studio的问题，是否因为Skill属性为集合属性触发的呢？

**Comment by chencjiajy** [comment]
> @chencjiajy 使用rest接口直接调用有问题吗？可能是studio的问题，是否因为Skill属性为集合属性触发的呢？

使用rest接口直接调用没有问题， Skill节点没有属性为集合属性， 都是string 类型的
