### ISSUE TITLE
100并发时，耗时与每秒事务数表现较差

### ISSUE THREAD

**Issue by qingchengliu** [hugegraph/hugegraph#1126]
### 期望表现
- 一度关联节点个数，在100+并发时times < 50ms, tps > 2000
- 二度关联节点个数，在100+并发时times < 80ms, tps > 1000

#### 数据量
- loaded vertices amount: 5亿
- loaded edges amount: 8亿

#### 修改的配置项：
- 服务端
	- rest-server.properties 新增 restserver.max_worker_threads=200
	- hugegraph-server.sh 修改 MAX_MEM=$((118 * 1024))
- Java Client客户端
	- HugeClient client = new HugeClient(ip, "hugegraph", 40, 50, 25);
		

#### 执行的Gremlin语句
- 一度关联：
	`g.V('User-%s').local(outE().hasLabel('DEV_REG','DEV_CREDIT', 'DEV_LOGON', 'DEV_REPAY', 'DEV_TRADE').has('modify_time', gt(%s)).limit(200))
	.inV().dedup().count()`
	其中 `%s` 为参数，会使用`String.format(tmp, uid, System.currentTimeMillis() - 31536000000L)`填充
	每次执行的结果 <= 10
- 二度关联：
	`g.V('User-%s').outE().hasLabel('DEV_REG', 'DEV_CREDIT', 'DEV_LOGON', 'DEV_REPAY', 'DEV_TRADE').has('modify_time', gt(%s)).inV().dedup().local(inE().has('modify_time', gt(%s)).limit(200)).outV().dedup().count()`

- 执行方式：
使用Java Client中的`.gremlin().gremlin(sql).execute()`
	
#### 环境信息
- hugegraph version: v0.10.4
- operating system:  40 CPUs, 128G RAM  2台
- hugegraph backend: hbase 12节点 8*960G SSD 
- hugegraph client: 2CPUs 4G RAM 10台

#### 压测时各端负载
Hbase CPU负载：
![Hbase-CPU负载](https://user-images.githubusercontent.com/20255838/88878558-ce677e00-d25a-11ea-9080-ede64dbd2ecb.png)
Hbase IO负载：
![Hbase-IO负载](https://user-images.githubusercontent.com/20255838/88878624-eccd7980-d25a-11ea-9c22-d5038ecf99e6.png)
Hugegraph-Server 负载：
![Hugegraph-Server](https://user-images.githubusercontent.com/20255838/88878690-0a024800-d25b-11ea-82db-5b06c7786343.png)
Hugegraph-Clinet 负载：
![Hugegraph-Clinet 负载](https://user-images.githubusercontent.com/20255838/88878722-1a1a2780-d25b-11ea-9fed-020b3b776052.png)
压测时Hugegraph-Server部分log：
![压测时Hugegraph-Server部分log](https://user-images.githubusercontent.com/20255838/88878753-2e5e2480-d25b-11ea-878c-0ba599ce99d7.png)
100并发时压测结论：
![压测结论数据](https://user-images.githubusercontent.com/20255838/88878866-741aed00-d25b-11ea-8664-305dee972fa3.png)

**Comment by javeme** [comment]
@qingchengliu 如果使用gremlin进行高并发访问时，可以考虑预编译语句，通过bindings来绑定变量。

**Comment by qingchengliu** [comment]
> @qingchengliu 如果使用gremlin进行高并发访问时，可以考虑预编译语句，通过bindings来绑定变量。

我使用bindings进行绑定变量后，发现单次查询仍不能降到50ms以内。
我在studio上通过profile()对gremlin的语句进行分析后，发现耗时主要集中获取节点的边&对边进行筛选上。
我使用Kneighbour接口对节点进行一度查询时，时间可以在50ms以内，但该接口没办法传多个label以及没办法对边的属性进行筛选。
我发现Kneighbour接口调用的`edgesOfVertex`是直接生成Query对象，而`edgesOfVertex`若传入`properties`，则会去使用`GraphTraversal`，再转换为HugegraphStep来生成Query对象（未确定）。
请问是否有接口，支持我查询类似”A节点一年内关联的B节点个数”的功能，且该接口在能达到1000tps以上、50ms以内，在我当前的数据量（5亿节点、8亿关系）

![gremlin profile](https://user-images.githubusercontent.com/20255838/89116451-d1ff3d00-d4c6-11ea-81ca-936cb2c669ec.png)

**Comment by qingchengliu** [comment]
使用预编译语句后，似乎解决了大部分问题。
