### ISSUE TITLE
Python调用 rest-api 大字段如何处理

### ISSUE THREAD

**Issue by CircleLife** [hugegraph/hugegraph#1128]
vertex 中有些属性字段比较大，超出了最大长度限制，导致插入不成功。如果将PropertyKey设置为Blob，那么会出现两种情况：
1）如果 requests.post 时大字段以字符串的形式传递给服务端，服务端会提示该属性字段值不是 byte[] 
2）如果 requests.post 时将大字段转换成 bytes，python又不支持 bytes 的 json 序列化

**Comment by javeme** [comment]
@CircleLife 请使用base64编码即可。

**Comment by CircleLife** [comment]
base64编码传过去的参数是一个 string，服务器端接受到 string 与 propertyKey（Blob）不相符，就会报错

**Comment by javeme** [comment]
@CircleLife 可能是低版本不兼容，可以使用最新的0.11版。Blob可通过byte array数组、hex字符串、base64字符串的任意一种方式输入，示例：
```json
[1, 3, 250, 254]
"0x0103fafe"
"AQPDusO+"
```
