### ISSUE TITLE
使用union后删除问题

### ISSUE THREAD

**Issue by gudehuang** [hugegraph/hugegraph#1129]
### Expected behavior 期望表现
- 1. union中,identity()在前时,查询得到的数据
```
g.V().hasLabel('medicine_category').has('name','测试分类').has('type',0)
 .union(identity(),__.in('medicine_to_category'))
```
![2020-07-31-14-26-26](https://user-images.githubusercontent.com/20537541/89007473-6472d580-d33b-11ea-9f18-e05edaa4b8ec.png)

- 2. union中,identity()在后面时,查询得到的数据
```
g.V().hasLabel('medicine_category').has('name','测试分类').has('type',0)
 .union(__.in('medicine_to_category'),identity())
```
![2020-07-31-14-26-54](https://user-images.githubusercontent.com/20537541/89007449-5a50d700-d33b-11ea-92ca-0c1c49ed3e0e.png)

这两种查到的数据是相同的,
 - 在1后面加drop()后,只删除了medicine_category节点,medicine节点没有删除
   ```
   g.V().hasLabel('medicine_category').has('name','测试分类').has('type',0)
    .union(identity(),__.in('medicine_to_category')).drop()
   ```
 - 在2后面加drop()后,同时删除了medicine_category节点和medicine节点
   ```
    g.V().hasLabel('medicine_category').has('name','测试分类').has('type',0)
    .union(__.in('medicine_to_category'),identity()).drop()
   ```

请问为什么union里的内容顺序不同会导致删除的内容不同呢?

**Comment by javeme** [comment]
@gudehuang drop的执行是深度优先的，先删除自身，就无法查到自身的邻居，从而无法被删除。
