### ISSUE TITLE
文档网页又又又打不开了，https://hugegraph.github.io/hugegraph-doc/

### ISSUE THREAD

**Issue by 1315861791** [hugegraph/hugegraph#1131]
https://hugegraph.github.io/hugegraph-doc/
![image](https://user-images.githubusercontent.com/24642133/89243494-adc26e00-d636-11ea-90b3-ebadec63b735.png)

**Comment by javeme** [comment]
@1315861791 目前已恢复，可以尝试使用内网备份地址：https://hugegraph.now.sh/

**Comment by 1315861791** [comment]
@javeme 谢谢了，昨天就打不开，要是早知道备用地址就好了
