### ISSUE TITLE
使用GraphTraversalSource,无法从gremlin server读取图

### ISSUE THREAD

**Issue by DaveRoey** [hugegraph/hugegraph#1136]
### Expected behavior 期望表现
使用gremlin driver 连接gremlin server，但是无法获取图内容
 GraphTraversalSource g = traversal().withRemote(conf);
 List<Vertex> name = g.V().has("name").toList();

### Actual behavior 实际表现
使用上面的方式获取不到图，使用以下方式能正确获取到
conf = new PropertiesConfiguration(propFileName);
cluster = Cluster.open(conf.getString("gremlin.remote.driver.clusterFile"));
 List<Result> results = client.submit("g.V()").all().get();
 System.out.println(results);

### Steps to reproduce the problem 复现步骤
1. 设置gremlin server为websocket方式
2. 修改empty-sample.groovy
  globals << [g : hugegraph.traversal()]
3. 使用java远程连接
   <dependency>
            <groupId>org.apache.tinkerpop</groupId>
            <artifactId>gremlin-driver</artifactId>
            <version>3.4.5</version>
        </dependency>
4. jgex-remote.properties
    gremlin.remote.remoteConnectionClass=org.apache.tinkerpop.gremlin.driver.remote.DriverRemoteConnection
    gremlin.remote.driver.clusterFile=remote-objects.yaml
    gremlin.remote.driver.sourceName=g
5. remote-objects.yaml
  hosts: [10.206.23.197]
  port: 8182
  serializer: {
    className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV1d0,
    config: {
      serializeResultToString: false,
      custom: [com.baidu.hugegraph.io.HugeGraphIoRegistry]
  }

 }

**Comment by javeme** [comment]
可以参考下类似问题：
- https://github.com/apache/incubator-hugegraph/issues/1871#issuecomment-1125808166
- https://github.com/apache/incubator-hugegraph/issues/1785#issuecomment-1072384009
- https://github.com/apache/incubator-hugegraph/issues/1501#issuecomment-862022028
