### ISSUE TITLE
使用count返回数量结果报80W异常

### ISSUE THREAD

**Issue by ezioasche** [hugegraph/hugegraph#1138]
### Expected behavior 期望表现
通过JAVA调用Client执行gremlin返回查询结果的数量

### Actual behavior 实际表现
抛出异常
com.baidu.hugegraph.exception.LimitExceedException: Too many records(must <= 800000) for the query: Query for VERTEX where id in [...]

### Steps to reproduce the problem 复现步骤
1. g.V(id).repeat(out().dedup()).times(depth).toSet().size()，计算k-hop(kout)节点数量，因为Client API不能返回数量（至少我没在手册里找到方法），所以我用gremlin返回数量（数量非常庞大平均点有一两千万）。
2. g.V(" + id + ").optional(__.repeat(__.out()).times(" + depth + ").path().unfold().dedup()).count()，这是我计算k-neighbor的gremlin（包括自己k=0），也是返回数量，同样抛出异常

#### Vertex/Edge summary 数据量
- loaded vertices amount: 40,000,000+
- loaded edges amount: 14亿+
- loaded time: 2h 14m

#### Vertex/Edge example 数据示例
vertex: id
edge: fromId , toId

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
schema.propertyKey("id").asLong().ifNotExist().create();
schema.vertexLabel("person").useCustomizeNumberId().properties().ifNotExist().create();
schema.edgeLabel("knows").sourceLabel("person").targetLabel("person").ifNotExist().create();

### Specifications of environment 环境信息
- hugegraph version: 0.10.4
- operating system: Ubuntu 16
- hugegraph backend: rocksdb

**Comment by DaveRoey** [comment]
兄台你使用gremlin java api 可以使用GraphTraversalSource吗，我使用GraphTraversalSource获取不了图

**Comment by ezioasche** [comment]
> 兄台你使用gremlin java api 可以使用GraphTraversalSource吗，我使用GraphTraversalSource获取不了图

GraphTraversalSource指什么？

**Comment by javeme** [comment]
@ezioasche 同步gremlin建议使用local limit：`g.V(id).repeat(local(out().limit(799999)).dedup()).times(depth).count()`，或者去掉limit使用异步gremlin（不会限制80w）。后续会在kout rest api中增加count功能。

**Comment by gaeduf** [comment]
> @ezioasche 同步gremlin建议使用local limit：`g.V(id).repeat(local(out().limit(799999)).dedup()).times(depth).count()`，或者去掉limit使用异步gremlin（不会限制80w）。后续会在kout rest api中增加count功能。

你所说的异步是调用huge-server 异步接口，然后定时查询任务状态的方式吗
