### ISSUE TITLE
hugegraph 统计问题

### ISSUE THREAD

**Issue by wisdoms** [hugegraph/hugegraph#1139]
老师们好， 请问hugegraph 中怎样统计 label 的数量？期待解惑。

**Comment by imbajin** [comment]
- 如果你说的 Label 是指的图的元信息, 比如 `vertex/edge/indexLabels` , 可参考[文档](https://hugegraph.github.io/hugegraph-doc/clients/restful-api/vertexlabel.html)
- 如果你是说统计 "点/边" 的数量, 且只是统计**总数**的话, 目前大数据量下应该没有通用的方式, 但特定后端有一些方法可供参考
  1. 后端是 `Cassandra`, 之前有提到过, 参考 #322
  2. 后端是 `Hbase`, 我想你可以导入全量数据后, 先做一次 major_compaction , 跑一下 spark/mr 任务直接读取 hfile 读取 rowkey 数目, 后续有新增数据, 可以每次做完 major_compaction 后, 根据 hfile 的大小**增幅**来**推测**当前的数据量
  3. 后端是`RocksDB`, 理论上也可以参考 Hbase 的方式统计.

**Comment by wisdoms** [comment]
好的，建议很有用，感谢老师的指导
