### ISSUE TITLE
算法最短路径： 起点和终点相同且顶点不存在时查出结果

### ISSUE THREAD

**Issue by 1436516871** [hugegraph/hugegraph#1140]
post  http://127.0.0.1:8080/api/v1.2/graph-connections/1/algorithms/shortpath

{
  "source": "11111",
  "target":"11111",
  "direction": "BOTH",
  "max_depth": "2",
  "label": "link",
  "max_degree": 10000,
  "skip_degree":0,
  "capacity": 10000000,
  "limit":1000000
}

**Comment by shzcore** [comment]
这个是bug，我跟进处理一下
