### ISSUE TITLE
Can't operate a tx in other threads，There are still dirty changes

### ISSUE THREAD

**Issue by HerovNL** [hugegraph/hugegraph#1141]
### Expected behavior 期望表现
系统全新环境，在scripts/empty-sample.groovy中添加注入的全局变量
def globals = [graph : hugegraph, g : hugegraph.traversal(), schema: hugegraph.schema()]
然后通过gremlin-console客户端连接hugegraph，此时系统只有这么一个客户端在连接，通过schema对象添加多条propertyKey，期望都能成功。

### Actual behavior 实际表现
加到第三条时不成功，报“Can't operate a tx in other threads”、“There are still dirty changes”，断开重连也不行
         \,,,/
         (o o)
-----oOOo-(3)-oOOo-----
plugin activated: tinkerpop.server
plugin activated: tinkerpop.utilities
plugin activated: tinkerpop.tinkergraph
gremlin> :remote connect tinkerpop.server conf/remote.yaml session
log4j:WARN No appenders could be found for logger (com.jcabi.manifests.Manifests).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
==>Configured 10.44.200.37/10.44.200.37:8182-[437a9d8b-688c-429a-8cee-2139a6362e72]
gremlin> :remote console
==>All scripts will now be sent to Gremlin Server - [10.44.200.37/10.44.200.37:8182]-[437a9d8b-688c-429a-8cee-2139a6362e72] - type ':remote console' to return to local mode
gremlin> g.V()
gremlin> schema.propertyKey("name").asText().ifNotExist().create();
==>name(id=2)
gremlin> schema.propertyKey("age").asInt().ifNotExist().create();
==>age(id=3)
gremlin> schema.propertyKey("city").asText().ifNotExist().create();
Can't operate a tx in other threads
Type ':help' or ':h' for help.
Display stack trace? [yN]
gremlin> hugegraph.tx().commit()
==>null
gremlin> schema.propertyKey("city").asText().ifNotExist().create();
There are still dirty changes
Type ':help' or ':h' for help.
Display stack trace? [yN]
gremlin> schema.propertyKey("lang").asText().ifNotExist().create();
There are still dirty changes
Type ':help' or ':h' for help.
Display stack trace? [yN]
gremlin> :remote close
==>Removed - Gremlin Server - [10.44.200.37/10.44.200.37:8182]-[437a9d8b-688c-429a-8cee-2139a6362e72]
gremlin> :remote connect tinkerpop.server conf/remote.yaml session
==>Configured 10.44.200.37/10.44.200.37:8182-[366009e8-d8b1-46d7-821e-72ed26d58a17]
gremlin> :remote console
==>All scripts will now be sent to Gremlin Server - [10.44.200.37/10.44.200.37:8182]-[366009e8-d8b1-46d7-821e-72ed26d58a17] - type ':remote console' to return to local mode
gremlin> g.V().count()
==>0
gremlin> schema.propertyKey("city").asText().ifNotExist().create();
There are still dirty changes

### Steps to reproduce the problem 复现步骤
1 系统全新环境，在scripts/empty-sample.groovy中添加注入的全局变量
def globals = [graph : hugegraph, g : hugegraph.traversal(), schema: hugegraph.schema()]
重启hugegraph
2 gremlin-console客户端连接hugegraph

### Status of loaded data 数据状态
刚安装完的全新环境
#### Vertex/Edge summary 数据量
0
#### Vertex/Edge example 数据示例
0
#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
0
### Specifications of environment 环境信息
- hugegraph version: {v0.10.4}
- operating system: {centos 7}
- hugegraph backend: {MySQL 5.7.28}

**Comment by 1436516871** [comment]
@HerovNL 这个问题已经复现，谢谢反馈，我们会抓紧解决 @javeme
