### ISSUE TITLE
hugegraphserver启动成功但jps显示无进程

### ISSUE THREAD

**Issue by H-Qiong** [hugegraph/hugegraph#1142]
bin/start-hugegraph.sh显示启动成功
但jps进程没有hugegraphserver
重复输入bin/start-hugegraph.sh报错
the port 8182 has been used

**Comment by imbajin** [comment]
唔... 首先 `jps` 本身是有局限的, 它默认只显示:
1. **当前用户**启动的 java 进程
2. 可能受到权限/JVM配置影响

比如以前 Cassandra 正常启动, 但默认就[不显示在 jps 中](https://support.datastax.com/hc/en-us/articles/208269876-Java-utilities-such-as-jps-or-jstat-unable-to-monitor-DSE-processes)

至于你的问题, 最简单的排除方式就是 `netstat / lsof` 看看哪个进程使用了 `8182 / 8080` 端口呗
- 如果不是图的进程, 那改下端口就行
- 如果是图的进程, 看看这个进程是**当前用户**启动的么.

**Comment by H-Qiong** [comment]
![QQ图片20200816200858](https://user-images.githubusercontent.com/66932477/90333919-6061db80-dffc-11ea-9e47-8bed610b20a1.png)
可以帮我看看吗，我有点迷茫

**Comment by imbajin** [comment]
唔... 为啥要用 `sudo` 启动图server呢, 你这样启动, 默认是以 `root` 用户为执行者呢
那你当前又不是 root 用户, 自然是 `jps` 看不到的呀, 上面已经说过了. (你切换到root用户, jps才可以看到)

你要确认是否有进程占用了 `8182/8080` 端口, 才应该使用 `sudo netstat` 以root用户去执行, 因为默认你只能看到当前用户的进程使用端口情况

最后, 你可以用 `curl 127.0.0.1:8080/graphs` 看看是否正常返回, 判断是否启动成功, 或者 `top` 里也可以看到所有进程的.
