### ISSUE TITLE
关于两个Vertex的合并

### ISSUE THREAD

**Issue by kevinliang-123** [hugegraph/hugegraph#1143]
请教一下：
对于图中两个Vertex，有函数或者其他方式，能够将两个有关系的Vertex进行合并么，也就是他们原有的edge都合并在一起？
谢谢

**Comment by imbajin** [comment]
目前没有吧, 话说这是什么需求呢.    

假设有三个点 A 和 B, C, 两条边如下:
`A --like--> C`
和
`B --dislike--> C`

那期望合并 A & B 之后, 是显示什么关系
`A & B --like & dislike --> C` 么?

**Comment by kevinliang-123** [comment]
需求是这样的：有两个用户（注册时手机号不同），初始状态是独立的，有自己各自的edge，但是后期发现这两个独立用户实际是同一个用户，也就是通常的用户合并；合并后，删除掉一个用户，但是需要将被删除用户的edge全部转到未删除用户的vertex上；但是这就需要找到被删除用户的全部边，然后放置到另一个用户上（对edge也需要排重的）；操作起来非常麻烦。

**Comment by kevinliang-123** [comment]
> 目前没有吧, 话说这是什么需求呢.
> 
> 假设有三个点 A 和 B, C, 两条边如下:
> `A --like--> C`
> 和
> `B --dislike--> C`
> 
> 那期望合并 A & B 之后, 是显示什么关系
> `A & B --like & dislike --> C` 么?

所有顶点之间不会出现互斥关系的；但是A和C之间确实会出现多个edge

**Comment by imbajin** [comment]
> 需求是这样的：有两个用户（注册时手机号不同），初始状态是独立的，有自己各自的edge，但是后期发现这两个独立用户实际是同一个用户，也就是通常的用户合并；合并后，删除掉一个用户，但是需要将被删除用户的edge全部转到未删除用户的vertex上；但是这就需要找到被删除用户的全部边，然后放置到另一个用户上（对edge也需要排重的）；操作起来非常麻烦。

就这个需求而言, 听起来像是图 schema 设计的问题吧, "手机", "人", "银行卡", "房产" 这些如果是重要信息, 应该**单独拆为**一类顶点

比如你的例子里, 多个手机号, 或者多个银行卡, 你应该是通过一条边**指向某个人**, 然后当你发现手机号 A 和手机号 B 其实 是一个人, 那就直接**更新**一下 A或B 手机的边信息, 让它指向同一个 "人" 顶点 就好了

你把大量可能属于多个实体的信息都放在一个顶点内, 才会出现你说的问题

**Comment by kevinliang-123** [comment]
> > 需求是这样的：有两个用户（注册时手机号不同），初始状态是独立的，有自己各自的edge，但是后期发现这两个独立用户实际是同一个用户，也就是通常的用户合并；合并后，删除掉一个用户，但是需要将被删除用户的edge全部转到未删除用户的vertex上；但是这就需要找到被删除用户的全部边，然后放置到另一个用户上（对edge也需要排重的）；操作起来非常麻烦。
> 
> 就这个需求而言, 听起来像是图 schema 设计的问题吧, "手机", "人", "银行卡", "房产" 这些如果是重要信息, 应该**单独拆为**一类顶点
> 
> 比如你的例子里, 多个手机号, 或者多个银行卡, 你应该是通过一条边**指向某个人**, 然后当你发现手机号 A 和手机号 B 其实 是一个人, 那就直接**更新**一下 A或B 手机的边信息, 让它指向同一个 "人" 顶点 就好了
> 
> 你把大量可能属于多个实体的信息都放在一个顶点内, 才会出现你说的问题

是的，是设计上有些问题，我调整一下模型，多谢！
