### ISSUE TITLE
由某一Vertex同时获取该顶点的边和对应相邻顶点的问题

### ISSUE THREAD

**Issue by Arecobaleno** [hugegraph/hugegraph#1144]
### Steps to reproduce the problem 复现步骤
我使用的语句是
g.V().hasLabel('xxx').hasValue('xxx').bothE().bothV().path()
或者
g.V().hasLabel('xxx').hasValue('xxx').inE().outV().path()

### Expected behavior 期望表现
同时data中具有此顶点(sourceVertex)的全部信息，边的全部信息，和目标顶点(targetVertex)的全部信息

### Actual behavior 实际表现
sourceVertex和边的信息包括properties信息都很完整，但是targetVertex只有id,label,type是完整的，properties变成了一个空{}。
如果只使用g.V().hasLabel('xxx').hasValue('xxx').out()的话两个顶点信息都完整

我想同时获得该边的全部信息和对应目标顶点的全部信息，或许有其他更方便的语句吗

### vertex schema
{
id:xx
label:xx
type:xx
properties:{
   name:xxx
   .........
   .........
}
}

**Comment by lxb1111** [comment]
我这使用server0.10.4  cassandra后端可以实现你说的需求如下：
![image](https://user-images.githubusercontent.com/58289576/94417647-eb64f280-01b2-11eb-8f89-fc6f78af7260.png)
![image](https://user-images.githubusercontent.com/58289576/94417856-341cab80-01b3-11eb-8c00-235763447f08.png)
想问一下你那边是什么后端，哪个接口进行请求的才能复现。
