### ISSUE TITLE
hugegraph-client的事务

### ISSUE THREAD

**Issue by kevinliang-123** [hugegraph/hugegraph#1145]
请问：hugegraph-client在 java端调用多个函数执行时，是否支持事务，或者如何实现事务（或者必须使用gremlin？）
比如：
GraphManager graph = ClientTool.getUserClient().graph();
moveEdge.source(keepV);
graph.removeVertex(beMoveV.id());		
先改变一个edge的source，然后再删除一个vertex；如何保证他们在一个事务中，同时成功或失败？

**Comment by javeme** [comment]
@kevinliang-123 目前只能使用gremlin
