### ISSUE TITLE
CPU负载突然发生抖动，且一直无法恢复

### ISSUE THREAD

**Issue by qingchengliu** [hugegraph/hugegraph#1146]
### Expected behavior 期望表现
排查出CPU抖动的原因，且使得该抖动能够自行恢复

### Actual behavior 实际表现
Server端运行一段时间后，在某个时间点CPU使用率突然上升，且无法降到未抖动前的CPU平均使用率。
在CPU使用率升高时更新Vertex的耗时会上升特别多。在重启Server端后恢复正常。
通过监控指标观察到Hbase负载无明显波动、写入Hugegraph的数据量无突增。
观察到的Server端日志如下：
![image](https://user-images.githubusercontent.com/20255838/90325295-6203b300-dfac-11ea-8edd-b0d4ede878ad.png)

### Specifications of environment 环境信息
- hugegraph version: v0.10.4
- operating system: 40 CPUs, 128G RAM
- hugegraph backend: hbase 12节点 8*960G SSD

**Comment by javeme** [comment]
@qingchengliu 从截图无法看出来原因，一般来说CPU突增可能是因为查询消耗大量内存并且内存不足时GC压力过大导致。

**Comment by qingchengliu** [comment]
> @qingchengliu 从截图无法看出来原因，一般来说CPU突增可能是因为查询消耗大量内存并且内存不足时GC压力过大导致。

还问题昨晚再次出现。凌晨02:00到08:00一直抖动，直至重启后恢复。CPU负载10%，单个节点更新耗时长达250ms，正常为4ms。请问我需要提供什么信息方便排查

**Comment by qingchengliu** [comment]
![image](https://user-images.githubusercontent.com/20255838/93284205-b8ab1980-f804-11ea-81ed-5b5dd3db18df.png)
@javeme 这是当时Hugegraph Server log中出现的错误日志。直至重启恢复后消失

**Comment by javeme** [comment]
@qingchengliu 从日志来看可能是hbase操作超时。是一直在打印错误日志吗？是否可以发送完整的日志？

可尝试：

- 调大hbase client线程数，设置配置项`hbase.threads_max`，默认是64，可以设置到2.5倍CPUs。
- 可以在问题发生的时候打一下jstack，分析各线程具体在做什么事情。


@imbajin 这个现象你那边有什么想法吗？

**Comment by qingchengliu** [comment]
@javeme 日志已附上，时间范围为 2020-09-15 03 开始，从日志看似乎是对索引进行操作的时候出现了问题。
目前已配置 `hbase.threads_max` 为128
有两个个疑惑点：
1. 如果是 GC，为何写边耗时没有太幅度上升
2. 如果是 Hbase 的问题，为何重启 Hugegraph Server 后问题消失

由于每次出现该现在，第一时间想着是恢复业务，所以一直没有打印火焰图。目前已加上 JMX 监控，后续可以观察 GC 情况。

[hugegraph-server-log.zip](https://github.com/hugegraph/hugegraph/files/5230771/hugegraph-server-log.zip)

**Comment by qingchengliu** [comment]
这是当时的CPU与内存平均使用率监控
![image](https://user-images.githubusercontent.com/20255838/93312806-3a696a00-f83a-11ea-8afb-fa91ead3975e.png)

**Comment by imbajin** [comment]
看起来有两个主要问题, 一个是**CPU飙升**, 另一个是**更新**点变慢. 不妨分开来看.

先说说CPU使用飙升:
1. CPU持续占用高, 最简单概览的做法先打[火焰图](https://github.com/jvm-profiling-tools/async-profiler). (60~600s为宜)
2. CPU使用高, 就算不打火焰图, 也可以看看server进程中, 哪些线程使用的, for循环间隔1s打下jstack. 总之确定一下CPU具体在忙什么才好去分析原因
3. 如果你提到需要快速恢复业务, 可以单开一个server进程 (独立机器/端口)都行, 然后让新的业务流量转过去(上层可挂一个虚IP) , 原有问题的server再继续排查

至于更新变慢, 不知你这里说的更新是`update` 操作么? 还是普通的覆盖写呢. 如果是前者, 那也许是读慢/异常了, 只不过更新封装了 "**读-改-写**" 的过程, 所以可能整体看起来是更新慢了. 得细化确认一下
1. 从你的日志简单看, 有**许多连续**的Hbase的线程**中断**异常导致图提交失败, 是Hbase自身有啥异常么? (GC情况? 有fullGC么?)
2. 不知道是否最近有执行过**删除**类的操作 (包括点删和lable删除等), 导致hbase存在脏数据?
3. 或者可以回想一下, 这个情况是什么时候突然出现的, 之前有什么**特殊**的操作么, 顺便你现在的日志都是Hbase-client层面的, 可以看看 `RegionSever` 上批量扫一下, 有没有同一时间出现的**异常**, 附上相应日志.
4. 至于说重启server问题就好了, 倒不一定说就跟hbase没关系, 很可能是因为中断了一波读写操作... 然后hbase缓了过来

**Comment by qingchengliu** [comment]
> 看起来有两个主要问题, 一个是**CPU飙升**, 另一个是**更新**点变慢. 不妨分开来看.
> 
> 先说说CPU使用飙升:
> 
> 1. CPU持续占用高, 最简单概览的做法先打[火焰图](https://github.com/jvm-profiling-tools/async-profiler). (60~600s为宜)
> 2. CPU使用高, 就算不打火焰图, 也可以看看server进程中, 哪些线程使用的, for循环间隔1s打下jstack. 总之确定一下CPU具体在忙什么才好去分析原因
> 3. 如果你提到需要快速恢复业务, 可以单开一个server进程 (独立机器/端口)都行, 然后让新的业务流量转过去(上层可挂一个虚IP) , 原有问题的server再继续排查
> 
> 至于更新变慢, 不知你这里说的更新是`update` 操作么? 还是普通的覆盖写呢. 如果是前者, 那也许是读慢/异常了, 只不过更新封装了 "**读-改-写**" 的过程, 所以可能整体看起来是更新慢了. 得细化确认一下
> 
> 1. 从你的日志简单看, 有**许多连续**的Hbase的线程**中断**异常导致图提交失败, 是Hbase自身有啥异常么? (GC情况? 有fullGC么?)
> 2. 不知道是否最近有执行过**删除**类的操作 (包括点删和lable删除等), 导致hbase存在脏数据?
> 3. 或者可以回想一下, 这个情况是什么时候突然出现的, 之前有什么**特殊**的操作么, 顺便你现在的日志都是Hbase-client层面的, 可以看看 `RegionSever` 上批量扫一下, 有没有同一时间出现的**异常**, 附上相应日志.
> 4. 至于说重启server问题就好了, 倒不一定说就跟hbase没关系, 很可能是因为中断了一波读写操作... 然后hbase缓了过来

1. 从Hbase的监控上看，没有Full GC，Young GC次数事发前后没明显变化
2. 最近没有执行过删除类的操作
3. DBA说 `RegionServer` 上扫了一下日志，最大的表 `g_v` 没有啥异常日志
4. 更新写中的读、写耗时都变慢了。（单点覆盖写、根据id读节点的耗时都有波动）。

![image](https://user-images.githubusercontent.com/20255838/93324144-157bf380-f848-11ea-8baf-3c028ea2bc8f.png)
![image](https://user-images.githubusercontent.com/20255838/93324058-f8472500-f847-11ea-8108-d1ce3b78dd6b.png)
![image](https://user-images.githubusercontent.com/20255838/93324519-9c30d080-f848-11ea-953a-ddfde51b9e70.png)

**Comment by imbajin** [comment]
从图的日志(Hbase client)输出来看, RS应该是有对应的异常才对, 或者至少慢日志之类的
毕竟这等于是读/写失败或者超时了.  

如果认为是图的问题, 那就应该先打个火焰图, 看看cpu在忙啥, 再进行下一步推断. 不然基本关于Hbase的全是**推测**...
何况你hbase还不是独立集群, 有多个业务使用, 至少应该看看你**重启Server** ~ **CPU飙升** 阶段到底发生了什么?

比你给的日志看(见下), 你9.2号的时候, hbase-client先表示自己异步读写请求已经在**等待**了, 不管RS那边发生了什么, 此时说明肯定压力比较大了, rs端都是有日志或者p99/p95能看出端倪.  (你可以搜一下exception/error 关键字)
```bash
[grizzly-http-server-42] [INFO ] *.hbase.client.AsyncRequestFutureImpl [] - #3, waiting for 2  actions to finish on table: hugegraph:g_v
# .... 类似日志
#  然后抛出gremlin超时
# 最后抛出大量中断异常
```

之后图这边就开始抛出server执行gremlin语句超时, 然后抛出中断的异常, 看起来的确像是超时之后把hbase-client中断了
其他至少日志上没看出什么端倪, 然后你8.22左右的日志Hbase-RS还有明显的服务停止报错, 这些我就没管了..

**Comment by javeme** [comment]
> 3\. DBA 说 `RegionServer` 上扫了一下日志，最大的表 `g_v` 没有啥异常日志

@qingchengliu  其它的表也应该关注下，比如g_si、g_li等表，在server日志中有打印这些表超时的。

**Comment by qingchengliu** [comment]
> 从图的日志(Hbase client)输出来看, RS应该是有对应的异常才对, 或者至少慢日志之类的
> 比你给的日志看(见下), 你9.2号的时候, hbase-client先表示自己异步读写请求已经在**等待**了, 不管RS那边发生了什么, 此时说明肯定压力比较大了, rs端都是有日志或者p99/p95能看出端倪. (你可以搜一下exception/error 关键字)

1. 从监控上看，CPU飙升 ~ 重启Server 期间RS端99.9%调用耗时是一天里最小的（晚上线上流量小）。
2. RS的日志中，扫了一遍确实没有exception/error，只有一些表compact的warn

![image](https://user-images.githubusercontent.com/20255838/93451028-3c4e2e80-f909-11ea-9e02-b706fb9554f7.png)

> 其他至少日志上没看出什么端倪, 然后你8.22左右的日志Hbase-RS还有明显的服务停止报错, 这些我就没管了..

8.22左右，是当时对Hugegraph进行压测后，发现 region 在某台机器上分布多很多，重新调整了下。

@imbajin @javeme 十分感谢两位的热心解答。目前看来只能等下次抖动发生时，通过火焰图/GC情况进行定位了。

**Comment by qingchengliu** [comment]
@javeme 目前通过监控观察到以下情况：
1. 存在full gc，单次full gc约能回收1G老年代空间，单词full gc耗时大于2s。一天约有2次full gc
2. 老年代使用空间持续增长。从重启后的5G到目前的17G，日增长约5G
3. full gc时，边的**覆盖写**耗时从4ms增长到5ms，点的**更新写**耗时从4ms增长到40ms，二度关联读从15ms增长到100ms，full gc后恢复
4. 存在young gc，约2.5min一次，每次新生代内存晋升大小约5M

我看到`util.sh`中会去计算xmx，对于我的配置，最后xms的值约为55G。
观察到8.15日的情况，当内存使用达到55G时，full gc没有有效回收老年代（内存使用率没有下降），此时遇到的情况与该issue中提到的一致。

**Comment by javeme** [comment]
@qingchengliu 最大内存是分配的55G还是100G呢？可以打印一下内存分配情况`jmap -heap PID`贴出来看看。
对于老年代垃圾持续增长，这个现象是不正常的，可以dump查看内存对象top10类型，看看具体是什么内容。

**Comment by qingchengliu** [comment]
> @qingchengliu 最大内存是分配的55G还是100G呢？可以打印一下内存分配情况`jmap -heap PID`贴出来看看。
> 对于老年代垃圾持续增长，这个现象是不正常的，可以dump查看内存对象top10类型，看看具体是什么内容。

JVM最多可用62400M，目前使用了G1垃圾回收器。
通过实验，当老年代内存为12G时，如果此时有线上流量，通过`jmap`触发full gc，只能回收不到1G；如果此时将流量切走，再触发full gc，可以回收7G空间。
