### ISSUE TITLE
发现Restful API中Gremlin的问题

### ISSUE THREAD

**Issue by chobits102** [hugegraph/hugegraph#1151]
### Expected behavior 期望表现
通过Restful API中的Gremlin对顶点修改属性

### Actual behavior 实际表现
有些id中有 +号，例如：
"id": "7:維C+鈣_101"
则无法获取顶点信息

### Steps to reproduce the problem 复现步骤
1. 使用浏览器打开，http://IP:8080/gremlin?gremlin=hugegraph.traversal().V("7:卵磷脂特強配方+鉻_134")，无法获取信息
2. 在HugeGraph-Studio中使用Gremlin，g.V("7:卵磷脂特強配方+鉻_134")，可以获取信息
3. {step 3}

#### Vertex/Edge summary 数据量
- 1
- 0
- 0

#### Vertex/Edge example 数据示例
{
  "requestId": "0fd036b9-48a4-444e-8602-fa07324d816e",
  "status": {
    "message": "",
    "code": 200,
    "attributes": {
      
    }
  },
  "result": {
    "data": [
      
    ],
    "meta": {
      
    }
  }
}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by javeme** [comment]
@chobits102 在url中需要对特殊字符进行编码，比如`+`编码为`%2b`
