### ISSUE TITLE
怎样删除schema中vertex上定义的属性

### ISSUE THREAD

**Issue by I-DO-NOT-KNOW** [hugegraph/hugegraph#1159]
### Steps to reproduce the problem 复现步骤
1.创建属性 schema.propertyKey("property1").asDouble().ifNotExist().create();
2.创建顶点  schema.vertexLabel("person").properties("name", "property1").ifNotExist().create();
3.想要把property1属性从person顶点删除 schema.propertyKey("property1").remove()
此时报错 Not allowed to remove property key: 'property1(id=9)' because the vertex label 'person' is still using it.

也尝试读取person中每个实例，一个一个的删除属性property1。但是之后执行 schema.propertyKey("property1").remove()还是会报错。
也尝试想从person中把property1属性删除，但是没有找到相关方法。

### Specifications of environment 环境信息
- hugegraph version: {v0.10.4}
- operating system: {centos 7.4, 32 }
- hugegraph backend: {mysql}

**Comment by javeme** [comment]
@I-DO-NOT-KNOW 目前不允许删除vertex label中的property key，如果一定要删除，可以尝试先删除vertex label，再删除property key本身，然后创建新的property key和vertex label。

**Comment by 2867021781** [comment]
> @I-DO-NOT-KNOW 目前不允许删除vertex label中的property key，如果一定要删除，可以尝试先删除vertex label，再删除property key本身，然后创建新的property key和vertex label。

现在可以移除具体类型下的属性了吗？
