### ISSUE TITLE
如何得到顶点全部label

### ISSUE THREAD

**Issue by break266** [hugegraph/hugegraph#1160]
请问一下hugegraph如何得到图中所有的label，相关api是什么？

**Comment by tmljob** [comment]
g.V().label()

**Comment by javeme** [comment]
@break266 如果是想获取vertex label元数据的话，可以使用vertex label list接口：
`GET http://localhost:8080/graphs/hugegraph/schema/vertexlabels`
接口文档参考 http://hugegraph.baidu.com/clients/restful-api/vertexlabel.html
