### ISSUE TITLE
Web端图形化展示如何实现？

### ISSUE THREAD

**Issue by captain-guo** [hugegraph/hugegraph#1161]
请问，如果想把图数据的关系图集成在自己的web项目中展示该如何去做？

**Comment by zhaojunnana** [comment]
可以借助一些前端框架做展示，例如d3或vis等,看具体场景的需要做选型

**Comment by captain-guo** [comment]
需求类似于元数据的血缘关系图的一个展示。说白了就是：HugeGraph-Studio组建里面的web图形化展示的那块东西。如果能基于HugeGraph-Studio提供的功能直接引入展示的这个界面就更好了。不知道是否支持？

**Comment by javeme** [comment]
@captain-guo 推荐使用vis.js，直接使用HugeGraph-Studio作为frame应该也是可以的。
