### ISSUE TITLE
选择Mysql存储引擎性能如何？

### ISSUE THREAD

**Issue by captain-guo** [hugegraph/hugegraph#1163]
当前在部署hugegraph-server服务，针对后端存储引擎的选择上面来讲，使用mysql的话性能如何？与Hbase、RocksDB差距大吗？我们的数据量级大概在千万级别

**Comment by javeme** [comment]
@captain-guo 建议优先使用rocksdb，数据规模完全可满足，写入性能好，读取性能出色。

**Comment by captain-guo** [comment]
thanks

**Comment by zsy-042** [comment]
做过一个不太严谨的实验，单实例虚拟机部署，使用rocksdb和mysql，插入性能差距不是很大，查询性能rocksdb几乎比mysql快一倍。以下数据仅供参考，不代表hugegraph的实际性能表现。

          RocksDB                                                                              | mysql
          插入1W顶点 | 查询1W顶点 | 插入500条边     | 5级图遍历  | 插入1W顶点 | 查询1W顶点 | 插入500条边     | 5级图遍历
          2631             | 228               | 472                    | 131            | 3076            | 684               | 780                    | 261
          2398             | 266               | 262                    | 105            | 1942            | 516               | 791                    | 195
          1871             | 236               | 298                    | 108            | 1702            | 495               | 615                    | 179
          1815             | 223               | 323                    | 97              | 1791            | 495               | 351                    | 224
          1852             | 258               | 268                    | 85              | 1238            | 456               | 570                    | 188
均值   2113.4          | 242.2             | 324.6                 | 105.2         | 1949.8         | 529.2             | 621.4                 | 209.4
