### ISSUE TITLE
studio查询问题

### ISSUE THREAD

**Issue by 860960342** [hugegraph/hugegraph#1166]
实验环境：hugegraph-server-0.10.4+hbase-XX
顶点量200w+，边数量1000w+

问题：查询节点A关联的邻节点，边存在，但返回的图中没有建立边

如下查询红色节点的边label为test的邻节点，限制5条，返回图中有2个节点没有与红色节点建立关联：
g.V('001b35fcc0e112c9581c8cd5b5e62b15').both('test').has('type','mutex').path().limit(5) 
![image](https://user-images.githubusercontent.com/58197479/92345361-a5f55e00-f0fb-11ea-8f91-a3e2328249e2.png)

但单独查这两个节点与红色节点的关联情况，又是存在边的：
g.V('001b35fcc0e112c9581c8cd5b5e62b15').outE('test').inV().hasId('mutex--2adeb645782d3e08ff7dcdb3da436bf7','mutex--13614928d2deda9fdc26ff67ffd07d3a').path()
![image](https://user-images.githubusercontent.com/58197479/92345377-ac83d580-f0fb-11ea-97ef-31e708a36a6f.png)

不是所有的节点都存在这个问题，请问这是什么原因？

**Comment by javeme** [comment]
@860960342 可能是界面渲染限制顶点数量的问题，可以尝试变换下语句：`g.V('001b35fcc0e112c9581c8cd5b5e62b15').bothE('test').otherV().has('type','mutex').path().limit(5)`

**Comment by 860960342** [comment]
@javeme 使用bothE('test').otherV()代替both('test')，可视化仍没有建立关联，但返回结果data下有节点和边数据。

还有个问题是，bothE('test').otherV()这种方式，在查询的边中如果有顶点不存在时会报错：Vertex 'f--a4808a329b071a1a37b8d03b1305b0cb' does not exist，请问这种问题用gremlin可以如何规避？

**Comment by javeme** [comment]
@860960342 悬空边的问题可以通过补上点来解决。
