### ISSUE TITLE
bug:Raft状态机的onApply方法中使用异步线程导致无法保证执行顺序

### ISSUE THREAD

**Issue by chentianlong1993** [hugegraph/hugegraph#1170]
**问题：**
1.节点重启后与停止前数据不一致。
2.主从节点可能存在数据不一致的情况。
**复现步骤：**
节点正常运行时，执行5次插入propertyKey，再执行5次删除propertyKey，然后重启该节点。
**期望现象：**
数据与重启前数据一致，propertyKey数量应为0。
**实际现象：**
每次重启propertyKey的数量都不一致。
**分析：**
按照状态机中onApply方法中的逻辑，follow节点执行任务时，或节点重启时，会使用线程池来执行任务，这样导致了无法保证顺序，Jraft保证了日志顺序，并且任务的开始顺序也是保证的，但犹豫是异步线程，无法保证执行完成顺序。所以可能执行删除时对应的数据还没有添加成功，变成了先删除后新增。加载到内存中转化为写盘指令时，应保证执行完成顺序，才能保证主从节点的数据一致性。
**解决思路：**
将线程池的核心线程数和最大线程数均设为1，阻塞队列容量设为Integer.MAXVALUE，保证顺序执行，并防止任务丢失。
**疑问：**
上述解决思路可以解决顺序问题，但效率可能较低，不清楚是否有其他方式解决，期望回复交流。

**Comment by javeme** [comment]
@chentianlong1993 欢迎交流，可以通过配置文件修改并发线程数为1来保证顺序，另外后续会通过版本号解决该问题。

**Comment by Linary** [comment]
@chentianlong1993 我们一开始就是使用单线程应用raft日志的，但确实吞吐量太低，后续会为每个操作带上版本号解决该问题。
