### ISSUE TITLE
垃圾回收指定g1时Could not find or load main class g1

### ISSUE THREAD

**Issue by kevinliang-123** [hugegraph/hugegraph#1172]
通过命令bin/start-hugegraph.sh  -g g1时，无法启动，提示Could not find or load main class g1；
版本用的时0.10.4；不知为何，否则垃圾回收一直有问题。

**Comment by imbajin** [comment]
多谢反馈, 我刚复现了一下. `0.10.4`的确有这个问题.   不过最新的`master / 0.11`分支是正常的

0.10 因为后面加了一个 `USER_OPTION` 选项,  它比 `GC_OPTION` 的优先级高, 但是默认为空, 此时会影响GC参数传入

我等下fix一下

**Comment by kevinliang-123** [comment]
> 多谢反馈, 我刚复现了一下. `0.10.4`的确有这个问题. 不过最新的`master / 0.11`分支是正常的
> 
> 0.10 因为后面加了一个 `USER_OPTION` 选项, 它比 `GC_OPTION` 的优先级高, 但是传参格式有点小问题, 影响GC参数读取
> 
> 我 fix 了一下, 就两行, 你可以直接对着改下就好

按照您的fix，可以正常启动，非常感谢！
