### ISSUE TITLE
怎么创建多个graph的问题，一个顶点在一个图创建了，就不能再创建相同名称的顶点，怎么解决

### ISSUE THREAD

**Issue by dyhyao6** [hugegraph/hugegraph#1176]
### Expected behavior 期望表现
{type something here...}

### Actual behavior 实际表现
{type something here...}

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by javeme** [comment]
@dyhyao6 多图配置可参考：https://hugegraph.github.io/hugegraph-doc/config/config-guide.html ，后续会支持通过api动态创建图。

**Comment by dyhyao6** [comment]
@javeme 我可能表达有误，我的意思是如何建立多个namespace空间，类似于postgresql的多个schema

**Comment by dyhyao6** [comment]
@javeme 一个图是否可以创建多个空间供不同的用户使用
