### ISSUE TITLE
如何实现数据的批量导入导出，以及对数据进行计算

### ISSUE THREAD

**Issue by dyhyao6** [hugegraph/hugegraph#1177]
### Expected behavior 期望表现
{type something here...}

### Actual behavior 实际表现
{type something here...}

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by javeme** [comment]
@dyhyao6 支持批量导入导出，请参考：
https://hugegraph.github.io/hugegraph-doc/quickstart/hugegraph-loader.html
https://hugegraph.github.io/hugegraph-doc/quickstart/hugegraph-tools.html

对数据进行计算是指哪方面计算？hg提供了图计算方面的能力，包括中心性算法、社区类算法、rank类算法、相似性算法、邻域类算法等。

**Comment by dyhyao6** [comment]
@javeme 批量导入导出能用程序实现吗？实际生产不可能使用loader工具吧

**Comment by dyhyao6** [comment]
@javeme 有关图计算的算法，pagerank,kout,knegbor等，谢谢
