### ISSUE TITLE
如何删除Vertex或者Edge的某一个属性，难道schema的Label确定了用哪些属性，对应的graph中的元素必须都要用起来？

### ISSUE THREAD

**Issue by smallmonkey33** [hugegraph/hugegraph#1180]
### Expected behavior 期望表现
{type something here...}
可以执行删除一个边或点的某个属性，
例如gremlin语句为g.E('S1:josh>2>>S2:lop').properties('date').drop()

### Actual behavior 实际表现
{type something here...}
执行失败，提示不运行删除非空属性
Exception in thread "main" java.lang.IllegalArgumentException: Can't remove non-null edge property 'p[date->Wed Nov 11 00:00:...]'

### Steps to reproduce the problem 复现步骤
1. {step 1} 已经配置了边，见client中的例子：josh.addEdge("created", lop, "date", "2009-11-11", "weight", 0.4);
2. {step 2} 执行gremlin语句，删除date属性：
3. {step 3} ResultSet resultSet = gremlin.gremlin("g.E('S1:josh>2>>S2:lop').properties('date').drop()").execute();

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by javeme** [comment]
@smallmonkey33 需要设置为可空属性才允许删除，示例：
```groovy
schema.vertexLabel("created")
              .properties("date")
              .nullableKeys("date")
              .append();
```
