### ISSUE TITLE
顶点默认显示的标签是能修改为顶点的属性里面的一列

### ISSUE THREAD

**Issue by zebraka** [hugegraph/hugegraph#1191]
### Expected behavior 期望表现
顶点的默认标签都是显示id，想修改为显示顶点属性中的名称。

**Comment by javeme** [comment]
@zebraka 即将发布的hugegraph-hubble已经支持该功能。

**Comment by zebraka** [comment]
@javeme 谢谢反馈，hugegraph-hubble发布的大概时间确定了吗，是否继续开源？
