### ISSUE TITLE
ApplicationConfig中GrapManagerFactory的provide()有时拿到null导致启动失败

### ISSUE THREAD

**Issue by HerovNL** [hugegraph/hugegraph#1195]
### Expected behavior 期望表现
ApplicationConfig中GrapManagerFactory的provide()有时拿到null导致启动失败，为此项目中进行了如下修改：
/**
     * Graph Manager Factory
     *
     */
    public class GraphManagerFactory extends AbstractBinder implements Factory<GraphManager> {
        private final    HugeConfig   hugeConfig;
        private volatile GraphManager manager = null;

        private GraphManagerFactory(HugeConfig conf) {
            this.hugeConfig = conf;
            register(new ApplicationEventListener() {
                @Override
                public void onEvent(ApplicationEvent event) {
                    if (event.getType() == ApplicationEvent.Type.INITIALIZATION_FINISHED) {
                        setManager();
                    }
                }

                @Override
                public RequestEventListener onRequest(RequestEvent event) {
                    return null;
                }
            });
        }

        /**
         * Patch for support multiple threads
         */
        private void setManager() {
            if (manager != null) {
                return;
            }
            synchronized (this) {
                if (manager == null) {
                    manager = new GraphManager(hugeConfig);
                }
            }
        }

        @Override
        public void dispose(GraphManager manager) {
            // pass
        }

        @Override
        protected void configure() {
            bindFactory(this).to(GraphManager.class).in(RequestScoped.class);
        }

        @Override
        public GraphManager provide() {
            setManager();
            return manager;
        }
    }

**Comment by javeme** [comment]
@HerovNL 启动成功之前不允许调用provide()方法的（会打出警告），这个是预期的表现。
