### ISSUE TITLE
多hugegraphserver部署，支持事务吗？

### ISSUE THREAD

**Issue by hanzhihua** [hugegraph/hugegraph#1198]
请问一下，如果hugegraphserver是无状态，是 不是可以  多机部署，那么事务 如何保证呢？
我看了一下代码，事务好像都是单机的，请指教

**Comment by javeme** [comment]
@hanzhihua 目前无法保证的

**Comment by HerovNL** [comment]
单纯通过Restful API封装Gremlin语句，这样client一次提交应该算一个事务，这个应该通过后端数据库保证事务性吧；
事务性如果都基于数据库的事务，hugegraph的多节点对数据库来说只是多个连接而已，只要hugegraph不缓存表数据而是直接用数据库内容来返回，应该多机系统下也能支持事务并发的；这样hugegraph相当于只是个接口转发、解码编码；只是hugegraph还有个根据graph路由、graphManager的功能，graph列表信息需要多机系统同步，单纯同步这个信息要求并不高，毕竟这个不是很频繁；
