### ISSUE TITLE
邻接边用limit查不到数据-后端rocksdb

### ISSUE THREAD

**Issue by h5615225** [hugegraph/hugegraph#1200]
### Expected behavior 期望表现
不带.limit(3)时，是可以查到数据的
<img width="805" alt="no limit" src="https://user-images.githubusercontent.com/9546983/94535702-73f79780-0274-11eb-80eb-1a260fefa0cc.png">

### Actual behavior 实际表现
带.limit(3)，查不到数据
<img width="482" alt="limit" src="https://user-images.githubusercontent.com/9546983/94535775-883b9480-0274-11eb-972d-16e01ead9782.png">

```diff
-已经用2020-6-19补丁包，做了更新，结果依然如此。

```

### Steps to reproduce the problem 复现步骤
1. 创建后端为rocksdb的图
2. 导入包含pid属性的边
3. 对边进行检索

#### Vertex/Edge summary 数据量
- loaded vertices amount: {5000万}
- loaded edges amount: {2.7亿}
- loaded time: {4小时}

#### Vertex/Edge example 数据示例
{1,"中国","China","亚洲国家","Country of Asia"}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构

schema.propertyKey("id").asInt().ifNotExist().create();
schema.propertyKey("zh").asText().ifNotExist().create();
schema.propertyKey("en").asText().ifNotExist().create();
schema.propertyKey("dz").asText().ifNotExist().create();
schema.propertyKey("de").asText().ifNotExist().create();
schema.propertyKey("pid").asInt().ifNotExist().create();

schema.vertexLabel("entity").properties("id", "zh", "en","dz","de").primaryKeys("id").ifNotExist().create();

schema.indexLabel("entityByZh").onV("entity").by("zh").search().ifNotExist().create();
schema.indexLabel("entityByEn").onV("entity").by("en").search().ifNotExist().create();

schema.edgeLabel("relation").link("entity","entity").properties("pid").ifNotExist().create();

schema.indexLabel("relationById").onE("relation").by("pid").secondary().ifNotExist().create();

### Specifications of environment 环境信息
- hugegraph version: {0.10.4，2020-6-19日版本}
- operating system: {ubuntu 18.04 16 CPUs, 64G RAM}
- hugegraph backend: {rocksdb, 单机, 4T硬盘}

**Comment by javeme** [comment]
@h5615225 这是一个Bug，可参考 https://github.com/hugegraph/hugegraph/issues/1052 ，最新的代码0.11版已修复（即将发版）。如果希望在0.10.4上打补丁，可以cherry-pick https://github.com/hugegraph/hugegraph/commit/3a7316dcc803b521a08096249abeadf7ca017fcd 。
