### ISSUE TITLE
带 TTL 的点边数据 : 点无法写入, 点边无法查询或自动删除（hbase)

### ISSUE THREAD

**Issue by DoubleBabylol** [hugegraph/hugegraph#1205]
### Expected behavior 期望表现
插入ttl点能够查询并定时被批量删除

### Actual behavior 实际表现
插入带label具有ttl的点 无法查询  ，查看 hbase shell `g_v`表没有写入数据
1. 带ttl的点未被写入hbase点表中，边可以写入
2. 带ttl的点边都无法查询
3. 带ttl的边未自动删除

### Steps to reproduce the problem 复现步骤

问题复现：
1.  先设置带ttl的vertex label 

```javascript
POST http://localhost:8080/graphs/hugegraph/schema/vertexlabels

{
    "name": "person3",
    "id_strategy": "DEFAULT",
    "properties": [
        "name",
        "age"
    ],
    "primary_keys": [
        "name"
    ],
    "nullable_keys": [],
    "enable_label_index": true,
    "ttl":700
}
```

2.  再插入点 

```javascript
POST http://localhost:8080/graphs/hugegraph/graph/vertices
{
    "label": "person3",
    "properties": {
        "name": "mark1",
        "age": 30
    }
}
返回成功json
{
    "id": "8:mark1",
    "label": "person3",
    "type": "vertex",
    "properties": {
        "name": "mark1",
        "age": 30
    }
}
```

3.  查询这个点

`GET http://localhost:8080/graphs/hugegraph/graph/vertices/"8:mark1"`

结果：无法查询

## 补充
1. 对于此类vertexlabel带有ttl的点，可正常插入hbase表hugegraph:g_vi 数据，但无法自动删除，但点表则是从未插入过
2. mysql 中TTL 功能正常

**Comment by zhoney** [comment]
@DoubleBabylol 
通过设置VertexLabel和EdgeLabel的TTL字段，可以控制该类顶点或者边的TTL。比如你的例子中，通过设置VertexLabel ”person3“的 ttl为700（单位为ms），可以使得所有”person3“类型的顶点从导入起生存700ms，超过700ms后将不再能够查询的到。而”person3“这个VertexLabel本身是不会超时或者被自动清理的。

如例子中所示，0.7s的TTL有点短，查询不到可能是因为已经超过了0.7s的生存周期，可以尝试增大ttl的时间再进行验证下。

**Comment by DoubleBabylol** [comment]
感谢作者的及时回复，非常抱歉，我没有注意到mysql中ttl是秒，hbase中是毫秒：
1.  经过测试，带的ttl点边可正常插入，查询，自动删除 
2. 顺便问一下，看了代码发现hbase使用原生的ttl功能，为何还需要在column中存储ttl字段？（推测两个原因，不知是否正确）
   - hbase自身ttl是隐性的，不易于查看和对比
   - 为了多个后端存储的表结构统一
3. mysql中ttl是否是图层面实现的？之后我再看代码确认一下。

**Comment by DoubleBabylol** [comment]
@zhoney

**Comment by DoubleBabylol** [comment]
@zhoney
