### ISSUE TITLE
使用 gremlin语句查询 主键 失败

### ISSUE THREAD

**Issue by zzialiuzi** [hugegraph/hugegraph#1206]
### Expected behavior 期望表现
g.V().has('name',without('josh','marko')).valueMap() 
希望可以查出结果

### Actual behavior 实际表现
 但是结果是 ：
Don't accept query based on properties [name] that are not indexed in any label, may not match range condition 。

## 然后我就想为 name 创建索引 ：
修改 schema :
schema.indexLabel("personByName")
      .onV("person")
      .by("name")
      .secondary()
      .ifNotExist()
      .create();

然后清除数据以后，重新导入，报错：告诉我 不必为主键创建索引
Caused by: class java.lang.IllegalArgumentException: No need to build index on properties [name], because they contains all primary keys [name] for vertex label 'person'

难道就不能用此方法来查询 name了吗？ 怎么破？

 
### Specifications of environment 环境信息
- hugegraph version: v0.10.4
- operating system:  centos 7.6
- hugegraph backend:  cassandra 3.10

**Comment by DoubleBabylol** [comment]
验证了一下可能的原因：
1.has查询需要加上label，才可查询主键，其他属性则不需要。比如：
g.V().has('person','name','josh'); 可查
g.V().has('name','josh'); 不可查，且会报你的错误

2. 是否支持without，目前我这里是不支持这样的语法。

**Comment by javeme** [comment]
@DoubleBabylol without条件是不支持索引查询的，并且主键属性查询必须指定label，普通索引属性查询支持不指定label（但是从性能角度建议也指定label查）。
