### ISSUE TITLE
Customized Paths 接口是不支持最大深度属性配置吗？

### ISSUE THREAD

**Issue by dudefu** [hugegraph/hugegraph#1208]
<img width="854" alt="批量" src="https://user-images.githubusercontent.com/5269023/95806344-05b5d900-0d3a-11eb-952d-a09ac4c13286.png">

根据功能介绍支持最大深度配置，但是在文档中并没有发现最大深度配置属性，请问这个属性暂时不支持吗？还有，返回的信息都是顶点信息，边的具体属性信息不能返回吗？

**Comment by zhoney** [comment]
@dudefu Customized Paths API的深度是由边规则确定的，有多少个step，就代表着最大深度是多少。

目前Customized Paths不支持返回边的具体属性信息，该功能计划在0.12版本中支持

**Comment by dudefu** [comment]
好的，谢谢
