### ISSUE TITLE
gremlin 语句请求数据量过大时超时

### ISSUE THREAD

**Issue by liangshuang110** [hugegraph/hugegraph#1211]
数据量过大时，不加limit()请求超时，如何在不加limit（）情况下解决超时问题；
将restserver.request_timeout设置为-1是否可以解决

**Comment by javeme** [comment]
@liangshuang110 由于同步请求过多数据不超时意味着内存可能OOM，建议增加条件使得结果返回减小，或者使用分页API进行全量数据获取。

**Comment by liangshuang110** [comment]
只有这俩种解决办法吗？我想在studio上输入gremlin语句展示top5个边最多的点，但由于数据量大于80w所以报错，如果用分页api的话就展示不了图了，请问我想在studio上展示数据量大于80w数据的top5个边最多的点能满足需求吗？

**Comment by javeme** [comment]
@liangshuang110 建议把语句贴出来，通用的话可以减少渲染的数据，比如`g.V(id1,id2,id3,id4,id5).local(both().limit(10)).path()`

**Comment by liangshuang110** [comment]
主要是数据量大于80w了并不知道那5个顶点id是多少？
我的语句g.V().hasLabel('Entity').limit(10000).where(out().count().is(lte(g.V().hasLabel('Entity').limit(10000).map(outE().count()).max()[0]))).order().by(outE().count()).tail(5)，如果不加limit就会报错

**Comment by javeme** [comment]
@liangshuang110 这种场景建议使用离线计算的方式，使用度中心性进行计算。
