### ISSUE TITLE
如何解决异步Germlin->g.V().hasLabel('XXX')数据量过大导致的内存溢出问题

### ISSUE THREAD

**Issue by tmljob** [hugegraph/hugegraph#1213]
g.V().hasLabel('XXX') 同步执行时不能超过80w，但改成异步执行的方式，会因为数据量过大导致内存溢出。有没有办法可以解决这类问题？

我目前的诉求是根据顶点或边的Label清除数据，但不删除schema，类似于传统数据库的truncate。希望通过如下gremin异步执行完成：
g.V().hasLabel('XXX').drop()

但在执行过程中因为这个顶点或边数据量很大（5千万）会导致hugegraphserver内存溢出。

请问下有没有好的方式，类似于流式的，匹配到1个，删除1个。

- arthas 查看的hugegraphserver进程的dashboard：

Memory                           used      total      max        usage      GC
heap                             10823M    12370M     12370M     87.50%     gc.ps_scavenge.count                  7126
ps_eden_space                    1546M     1546M      1546M      99.99%     gc.ps_scavenge.time(ms)               3414476
ps_survivor_space                0K        1583104K   1583104K   0.00%      gc.ps_marksweep.count                 311
ps_old_gen                       9277M     9277M      9277M      100.00%    gc.ps_marksweep.time(ms)              2559640
nonheap                          161M      166M       -1         96.94%
code_cache                       65M       66M        240M       27.10%
metaspace                        86M       89M        -1         96.47%
compressed_class_space           10M       11M        1024M      1.01%
direct                           0K        0K         -          Infinity%
mapped                           0K        0K         -          NaN%

- hugegraph server日志
2020-10-19 11:09:00 1729676513 [cache-expirer] [INFO ] com.baidu.hugegraph.backend.cache.Cache [] - Cache 'edge-hugegraph' expired 0 items cost 9445ms > 1000ms (size 0, expire 600000ms)
Exception in thread "Timer-for-arthas-dashboard-1ef14163-05bd-4fd2-a301-0490b4c3827f" java.lang.OutOfMemoryError: GC overhead limit exceeded
2020-10-19 11:11:00 1729796507 [task-worker-4] [WARN ] com.baidu.hugegraph.task.HugeTask [] - An exception occurred when running task: 34

**Comment by javeme** [comment]
@tmljob 是一个顶点的邻接边达到5千万吗？如果是的话，这种情况0.10只能先逐条边删除，0.11可以直接删除点。
至于truncate，图里面并不是每个类型label按表来存储的，所以没办法按label进行truncate（因为数据在物理上不连续），仅支持truncate这个图。

**Comment by tmljob** [comment]
1、是一个顶点，有5千万的数据，但这个顶点还没有导入邻接边导入，异步运行这个gremlin都会导致oom。
     g.V().hasLabel('XXX').count()或 g.V().hasLabel('XXX').drop()

备注：hugegraphserver的xmx是十几G，已经很大了。

2、目前我们是想通过 g.V().hasLabel('XXX').drop() 来实现对顶点或边清除数据，但不删除schema的。
      这个诉求的背景是，现场在开始导入数据时，有时导入完了，发现某个顶点或边的数据接错了，想把这个顶点或边的数据清理了，重新接入。这种情况下把整个图都清理了也不太合适。

**Comment by javeme** [comment]
@tmljob 感谢反馈背景。我们尝试复现一下这种场景，理论上来说0.11.2应该是已经解决了上述oom问题的，同时已经支持了drop超级点。

**Comment by tmljob** [comment]
0.11.2版本hasLabel('XXX')数据量过大内存溢出这个问题已经解决。这里说的drop超级点是 #1298 这个issue里面说的迭代删除的方式？

**Comment by Miliery** [comment]
> 1、是一个顶点，有5千万的数据，但这个顶点还没有导入邻接边导入，异步运行这个gremlin都会导致oom。
> g.V().hasLabel('XXX').count()或 g.V().hasLabel('XXX').drop()
> 
> 备注：hugegraphserver的xmx是十几G，已经很大了。
> 
> 2、目前我们是想通过 g.V().hasLabel('XXX').drop() 来实现对顶点或边清除数据，但不删除schema的。
> 这个诉求的背景是，现场在开始导入数据时，有时导入完了，发现某个顶点或边的数据接错了，想把这个顶点或边的数据清理了，重新接入。这种情况下把整个图都清理了也不太合适。

请问清空图全部数据有什么比较好的方式吗？除了g.E().drop() g.V().drop()@

**Comment by tmljob** [comment]
> > 1、是一个顶点，有5千万的数据，但这个顶点还没有导入邻接边导入，异步运行这个gremlin都会导致oom。
> > g.V().hasLabel('XXX').count()或 g.V().hasLabel('XXX').drop()
> > 备注：hugegraphserver的xmx是十几G，已经很大了。
> > 2、目前我们是想通过 g.V().hasLabel('XXX').drop() 来实现对顶点或边清除数据，但不删除schema的。
> > 这个诉求的背景是，现场在开始导入数据时，有时导入完了，发现某个顶点或边的数据接错了，想把这个顶点或边的数据清理了，重新接入。这种情况下把整个图都清理了也不太合适。
> 
> 请问清空图全部数据有什么比较好的方式吗？除了g.E().drop() g.V().drop()@

官方提供的方式是HugeGraph-Tools包，graph-clear命令，清除某个图的全部 schema 和 data。这个不仅是数据还包含schema吧。
