### ISSUE TITLE
Cannot addVertex when use Mysql as backend

### ISSUE THREAD

**Issue by leestorm** [hugegraph/hugegraph#1214]
I am learning the hugegraph following the steps  one by one from the documents for HugeGraph Studio : https://hugegraph.github.io/hugegraph-doc/quickstart/hugegraph-studio.html.

All steps can be run successfully , but when I get to the step " marko = graph.addVertex(T.label, "person", "name", "marko", "age", 29, "city", "Beijing")  " , it throws  an error and in the backend log it shows null pointer exception happened in MySqlSession class.

Anyone knows the reason or which step that I might do wrong ?

### Specifications of environment 
- hugegraph version: 0.10.4-2020-06-19
- hugegraph studio version: 0.10.4
- operating system: Centos 7.45 2 CPUs, 4G RAM
- hugegraph backend: Mysql 5.6

**Comment by javeme** [comment]
@leestorm Could you please paste some log?
