### ISSUE TITLE
支持对图历史时刻的查询吗？

### ISSUE THREAD

**Issue by big1white** [hugegraph/hugegraph#1215]
### Expected behavior 期望表现
{type something here...}

查询任意历史时刻的图的状态？？？
### Actual behavior 实际表现
{type something here...}

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by javeme** [comment]
@big1white 从需求上来看可能更适合使用时序数据库。
在图数据库中，如果是边的话，可以按照时间属性作为sortkey存储及索引边，然后按照sortkey进行时间范围过滤。如果是顶点的话，可以按照时间索引。
