### ISSUE TITLE
Text.contains匹配出来的结果有问题

### ISSUE THREAD

**Issue by I-DO-NOT-KNOW** [hugegraph/hugegraph#1216]
使用的分词器为
search.text_analyzer=jieba
search.text_analyzer_mode=INDEX

查询结果如下图：
![1](https://user-images.githubusercontent.com/20416323/96563903-14316100-12f5-11eb-8648-a97386394004.png)
![2](https://user-images.githubusercontent.com/20416323/96563922-1bf10580-12f5-11eb-91ed-504c9c62306a.png)

### Specifications of environment 环境信息
- hugegraph version: v0.10
- hugegraph backend: mysql

**Comment by javeme** [comment]
@I-DO-NOT-KNOW 分词器可能是把“部”作为一个词分出来了，搜索的时候会把含有“部”关键字的都检索出来。可以尝试在搜索的时候去掉“部”，或者只取top 1个结果。
