### ISSUE TITLE
大概何时hugegraph server会支持分布式

### ISSUE THREAD

**Issue by shuiruoyan** [hugegraph/hugegraph#1218]
看到之前看19年有提到会做hugegraph server的分布式，想了解一下后续，这个现在有规划么？

**Comment by dyhyao6** [comment]
商业版的会支持分布式

**Comment by cmdares** [comment]
@dyhyao6 
商业版本没看到相关的资料，可以提供下吗，感谢。

**Comment by JackyYangPassion** [comment]
商业版 分布式 是指 单个计算实现分布式计算吗？还是类似于HAProxy 那样轮训发送到hugegraph server，单查询还是基于单server 计算？

**Comment by JackyYangPassion** [comment]
> 商业版的会支持分布式

商业版 分布式 是指 单个计算实现分布式计算吗？还是类似于HAProxy 那样轮训发送到hugegraph server，单查询还是基于单server 计算？
