### ISSUE TITLE
对于多张图的访问权限和读写权限如何解决

### ISSUE THREAD

**Issue by dyhyao6** [hugegraph/hugegraph#1221]
### Expected behavior 期望表现
{type something here...}

### Actual behavior 实际表现
{type something here...}

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by dyhyao6** [comment]
@javeme

**Comment by javeme** [comment]
@dyhyao6 对于单个服务中的多个图的权限控制，目前社区版最新代码已经支持了，v0.11.2版本发布后即可使用。

**Comment by dyhyao6** [comment]
> @dyhyao6 对于单个服务中的多个图的权限控制，目前社区版最新代码已经支持了，v0.11.2版本发布后即可使用。

何时发布呢？

**Comment by dyhyao6** [comment]
> > @dyhyao6 对于单个服务中的多个图的权限控制，目前社区版最新代码已经支持了，v0.11.2版本发布后即可使用。
> 
> 何时发布呢？

你好，我可能表达的不清楚；关于huge的权限分配方式和权限控制有相应的资料吗？官网没有文档详细说明这块，谢谢

**Comment by javeme** [comment]
![image](https://user-images.githubusercontent.com/9625821/97265547-cde28180-1861-11eb-9af7-31233c7452e1.png)

举例说明：
场景：某用户只有北京地区的数据读取权限
`user(name=xx) -belong-> group(name=xx)  -access(read)-> target(graph=graph1, resource={label: person, city: Beijing})`

**Comment by dyhyao6** [comment]
> ![image](https://user-images.githubusercontent.com/9625821/97265547-cde28180-1861-11eb-9af7-31233c7452e1.png)
> 
> 举例说明：
> 场景：某用户只有北京地区的数据读取权限
> `user(name=xx) -belong-> group(name=xx) -access(read)-> target(graph=graph1, resource={label: person, city: Beijing})`

thanks! 能分享一下这方面的资料吗？

**Comment by dyhyao6** [comment]
> ![image](https://user-images.githubusercontent.com/9625821/97265547-cde28180-1861-11eb-9af7-31233c7452e1.png)
> 
> 举例说明：
> 场景：某用户只有北京地区的数据读取权限
> `user(name=xx) -belong-> group(name=xx) -access(read)-> target(graph=graph1, resource={label: person, city: Beijing})`
hi，不大明白对象的id只是啥， userid,group id等创建时并没有说明，所以对象的id在这里的唯一标识是name属性吗？
<img width="467" alt="企业微信截图_20201029101635" src="https://user-images.githubusercontent.com/49445844/97517457-35b6da80-19d0-11eb-94d3-735771176aaf.png">

**Comment by dyhyao6** [comment]
hi，不大明白对象的id表示的含义， userid,group       @javeme @houzhizhen id等创建时并没有说明，所以对象的id在这里的唯一标识是name属性吗？
<img width="467" alt="企业微信截图_20201029101635" src="https://user-images.githubusercontent.com/49445844/97517861-005ebc80-19d1-11eb-87a4-e3547fcfc57c.png">
