### ISSUE TITLE
目前是否支持动态新增图，而不用在配置文件里配置，初始化，重启等步骤，thx

### ISSUE THREAD

**Issue by dyhyao6** [hugegraph/hugegraph#1222]
### Expected behavior 期望表现
{type something here...}

### Actual behavior 实际表现
{type something here...}

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by dyhyao6** [comment]
@javeme

**Comment by javeme** [comment]
@dyhyao6 正在实现该功能，可以关注下PR https://github.com/hugegraph/hugegraph/pull/1065

**Comment by dyhyao6** [comment]
> @dyhyao6 正在实现该功能，可以关注下PR #1065

@javeme 看了一遍，是不是已经实现了动态建图，

**Comment by dyhyao6** [comment]
> @dyhyao6 正在实现该功能，可以关注下PR #1225
