### ISSUE TITLE
用mysql做输入源load，顶点属性如何把表中的字段名称自定义别名

### ISSUE THREAD

**Issue by feifei-git** [hugegraph/hugegraph#1228]
### Expected behavior 期望表现
{type something here...}

### Actual behavior 实际表现
{type something here...}

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by Linary** [comment]
使用`field_mapping`映射一下就好，示例：

```
"field_mapping": {
    "source_name": "name",
    "target_name": "name"
}
```

**Comment by feifei-git** [comment]
> 使用`field_mapping`映射一下就好，示例：
> 
> ```
> "field_mapping": {
>     "source_name": "name",
>     "target_name": "name"
> }
> ```

不起作用，我是直接load表中的数据，不是load  csv文件

**Comment by Linary** [comment]
文件和表都可以写的，如果确定没起作用，那可能是一个bug。

**Comment by Linary** [comment]
我看了下代码，应该是没问题的。如果你环境下确实不起作用的话，麻烦把问题复现的步骤写一下。

**Comment by Linary** [comment]
没啥问题就先关闭了。
