### ISSUE TITLE
hugegraph studio log

### ISSUE THREAD

**Issue by big1white** [hugegraph/hugegraph#1230]
### Expected behavior 期望表现
{type something here...}
在studio的网页界面输入Gremlin语句，期望有日志记录输入的语句

### Actual behavior 实际表现
{type something here...}
在studio下的log文件夹，未发现有用的log信息，所以是查看的log位置不对，还是并没有记录图操作语句的日志功能？

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by Linary** [comment]
@big1white 
gremlin语句有在你启动服务的控制台打印出来吗？

**Comment by big1white** [comment]
> @big1white
> gremlin语句有在你启动服务的控制台打印出来吗？

在控制台可以看见，关闭了就没了，没有存储在日志里这样持久化一些的吗？我看在board里也只是存储一条记录，如果没有这样的很多对图的操作记录在日志里的功能，请问哪些文件夹涉及到这些，方便增加这个功能呢？
