### ISSUE TITLE
indexlabel索引可否在任意时刻创建，以至于对已有的顶点或边生效

### ISSUE THREAD

**Issue by dyhyao6** [hugegraph/hugegraph#1235]
### Expected behavior 期望表现
  @javeme @Linary  在不清除未来的需求的情况下，向数据库中导入了大量的数据，然而事先并没有建立为这些数据建立索引，以至于无法对已有数据进行检索和遍历。

### Actual behavior 实际表现
<img width="605" alt="企业微信截图_20201030165223" src="https://user-images.githubusercontent.com/49445844/97679944-e60c0800-1ad0-11eb-8e79-1ac90da571fb.png">

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by javeme** [comment]
@dyhyao6 允许在存量数据之上建立索引的，不过一般来说比较耗时。

**Comment by dyhyao6** [comment]
> @dyhyao6 允许在存量数据之上建立索引的，不过一般来说比较耗时。

怎么在存量之上建立索引呢？为啥比较耗时。为啥我建索引查询不到之前的数据 @javeme

**Comment by javeme** [comment]
@dyhyao6 不论是存量数据还是空图，创建索引的方法都是一样的，可参考[2.5.2 创建 IndexLabel](https://hugegraph.github.io/hugegraph-doc/clients/hugegraph-client.html)。
存量数据耗时是因为需要先读一遍全量数据。
建索引查不到之前数据，是否有稳定的复现流程？以及是否有报错信息？

**Comment by dyhyao6** [comment]
> @dyhyao6 不论是存量数据还是空图，创建索引的方法都是一样的，可参考[2.5.2 创建 IndexLabel](https://hugegraph.github.io/hugegraph-doc/clients/hugegraph-client.html)。
> 存量数据耗时是因为需要先读一遍全量数据。
> 建索引查不到之前数据，是否有稳定的复现流程？以及是否有报错信息
@javeme 我明白了，存量数据可能需要一些时间索引才能生效，难怪我一建立索引就查询存量数据就会未建立索引异常，没截图；但是为啥现在查询存量数据怎么为empty呢？如下是全部数据，存量数据和建索引后插入的数据
graph.schema().indexLabel("personByname").onV("person").by("name").secondary().ifNotExist().create()
<img width="513" alt="企业微信截图_20201102153914" src="https://user-images.githubusercontent.com/49445844/97842658-ef8cae80-1d22-11eb-86c4-2fe011d1d282.png">
建索引后插入的数据，查询结果为
<img width="226" alt="企业微信截图_20201102154015" src="https://user-images.githubusercontent.com/49445844/97842800-2cf13c00-1d23-11eb-8c60-712aa222876e.png">
查询存量数据，
<img width="357" alt="企业微信截图_20201102154306" src="https://user-images.githubusercontent.com/49445844/97843056-97a27780-1d23-11eb-93c7-de3710295f87.png">

结果为
<img width="281" alt="企业微信截图_20201102154202" src="https://user-images.githubusercontent.com/49445844/97842914-6629ac00-1d23-11eb-8c74-222cccf4e198.png">

**Comment by javeme** [comment]
@dyhyao6 请给出复现流程，才容易找到原因。

**Comment by dyhyao6** [comment]
> @dyhyao6 请给出复现流程，才容易找到原因。
抱歉，复现可能有点麻烦。我说一下流程吧；下图是两拨数据，
<img width="578" alt="企业微信截图_20201102161352" src="https://user-images.githubusercontent.com/49445844/97844838-ab031200-1d26-11eb-8312-b54e267bb23f.png">
ID为001到004是存量数据，005-以上是建索引graph.schema().indexLabel("personByname").onV("person").by("name").secondary().ifNotExist().create()之后添加的数据；在对这两拨数据进行二度好友查询时，存量数据为空，新加的数据结果正确的；问题就是为啥存量数据查不到，谢谢
<img width="588" alt="企业微信截图_20201102161954" src="https://user-images.githubusercontent.com/49445844/97845223-48f6dc80-1d27-11eb-9ac8-95af2a90c19e.png">
