### ISSUE TITLE
huge client创建错误

### ISSUE THREAD

**Issue by big1white** [hugegraph/hugegraph#1236]
### Expected behavior 期望表现
{type something here...}
使用gitbook里的client模块流程创建client

### Actual behavior 实际表现
{type something here...}
![QQ截图20201102131154](https://user-images.githubusercontent.com/42825958/97832344-82bae980-1d0d-11eb-9012-a7c90f7ddebf.png)
![QQ截图20201102131107](https://user-images.githubusercontent.com/42825958/97832363-8a7a8e00-1d0d-11eb-9e83-c995646ae9c4.png)
![QQ截图20201102131033](https://user-images.githubusercontent.com/42825958/97832390-9ebe8b00-1d0d-11eb-9157-c26bf7c2b5fc.png)

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by javeme** [comment]
@big1white 可能是最新代码变更，建议使用Builder方式来创建client。@shzcore @Linary 请帮忙更新一下文档
