### ISSUE TITLE
 hugegraph商业版的服务如何对接，商业版有哪些好的特性，而社区版没有。@

### ISSUE THREAD

**Issue by dyhyao6** [hugegraph/hugegraph#1239]
### Expected behavior 期望表现
{type something here...}
@javeme @Linary 

### Actual behavior 实际表现
{type something here...}

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by zsy-042** [comment]
同问，商业版资料在哪里能找到，微信公众号也没相关信息呢。

**Comment by gybmike** [comment]
同问，社区版和商业版版本差异是什么？

**Comment by imbajin** [comment]
> 同问，商业版资料在哪里能找到，微信公众号也没相关信息呢。

可以加群然后咨询商务 / 产品同学呐, 商业版主要提供几个不同点:
- server 端的额外图计算算法 (社群发现等)
- server 端的 HA (包括缓存一致性)
- 实时的技术问题支持 + 优先的问题修复
- hubble(前端) 的无限制许可
- 图计算专用包以及后续的分布式计算框架
- 其它(...)
