### ISSUE TITLE
执行init初始化hbase时创建的那些表分别存储了什么数据，每张表的功能作用是啥？

### ISSUE THREAD

**Issue by dyhyao6** [hugegraph/hugegraph#1240]
### Expected behavior 期望表现
{type something here...}
@javeme @Linary 
<img width="960" alt="init2" src="https://user-images.githubusercontent.com/49445844/97965654-af4a3080-1df5-11eb-9955-3d9fa216c7e5.png">

### Actual behavior 实际表现
{type something here...}

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by dyhyao6** [comment]
@Linary 能说明一下每个table的作用吗？感谢

**Comment by imbajin** [comment]
你如果急着了解... 以前上手的时候我写过两篇(以[Cassandra](http://imbajin.com/2019-01-08-%E5%9B%BE%E7%B3%BB%E7%BB%9F-HugeGraph%E5%88%9D%E8%AF%86/)/[Hbase](http://imbajin.com/2019-01-10-%E5%9B%BE%E7%B3%BB%E7%BB%9F-HugeGraph%E5%88%9D%E8%AF%86%E4%BA%8C/)为例)表/索引的介绍

不过这个是基于0.8~0.9版本, 但是核心是类似的, 表名做了一下缩写, 你很快也能对应上. 

大概你知道核心的表是哪几个, 然后每个表做什么的, 存储的基本结构. Hbase新版把多个column合成了一个.
其他你可以等之后写的新的笔记完工.

**Comment by dyhyao6** [comment]
> 你如果急着了解... 以前上手的时候我写过两篇(以[Cassandra](http://imbajin.com/2019-01-08-%E5%9B%BE%E7%B3%BB%E7%BB%9F-HugeGraph%E5%88%9D%E8%AF%86/)/[Hbase](http://imbajin.com/2019-01-10-%E5%9B%BE%E7%B3%BB%E7%BB%9F-HugeGraph%E5%88%9D%E8%AF%86%E4%BA%8C/)为例)表/索引的介绍
> 
> 不过这个是基于0.8~0.9版本, 但是核心是类似的, 表名做了一下缩写, 你很快也能对应上.
> 
> 大概你知道核心的表是哪几个, 然后每个表做什么的, 存储的基本结构. Hbase新版把多个column合成了一个.
> 其他新版细节, 可以等手头事忙一下我会再更新的 (主要也是关注 "**点 + 边 + 索引**"三类表)

ok,感谢

**Comment by dyhyao6** [comment]
> > 你如果急着了解... 以前上手的时候我写过两篇(以[Cassandra](http://imbajin.com/2019-01-08-%E5%9B%BE%E7%B3%BB%E7%BB%9F-HugeGraph%E5%88%9D%E8%AF%86/)/[Hbase](http://imbajin.com/2019-01-10-%E5%9B%BE%E7%B3%BB%E7%BB%9F-HugeGraph%E5%88%9D%E8%AF%86%E4%BA%8C/)为例)表/索引的介绍
> > 不过这个是基于0.8~0.9版本, 但是核心是类似的, 表名做了一下缩写, 你很快也能对应上.
> > 大概你知道核心的表是哪几个, 然后每个表做什么的, 存储的基本结构. Hbase新版把多个column合成了一个.
> > 其他新版细节, 可以等手头事忙一下我会再更新的 (主要也是关注 "**点 + 边 + 索引**"三类表)
> 
> ok,感谢

请问文档更新了吗？ @imbajin

**Comment by imbajin** [comment]
> 请问文档更新了吗？ @imbajin

不好意思, 在忙其他的事, 还没呢, 最晚年前吧, 多谢提醒. 你可以先看看之前的C*和Hbase版本, 新版本质改动不大.
新的文档主要是说 bulkload 的, `顺便说一下表结构`

**Comment by javeme** [comment]
@dyhyao6 可以参考下这个总结：[HugeGraph RocksDB & HBase后端表结构设计](https://zhuanlan.zhihu.com/p/340949657)
