### ISSUE TITLE
关于模糊查询 search index

### ISSUE THREAD

**Issue by zx-6017** [hugegraph/hugegraph#1242]
### Expected behavior 期望表现
{type something here...}
顶点 ：
id：area_北京海淀
search_name : 北京海淀

search引擎：
search.text_analyzer=hanlp
search.text_analyzer_mode=standard

g.V().hasId('area_北京海淀').has('search_name',Text.contains('海淀')) 可以找到
g.V().hasId('area_北京海淀').has('search_name',Text.contains('海淀黄庄')) 找不到

有什么办法可以在搜索 "海淀黄庄" 可能找到这个顶点吗 
分词引擎在数据存储的时候 进行了分词，在查询的时候对查询条件不会分了吗？

**Comment by javeme** [comment]
@zx-6017 这个是因为已经给定了id的查询，不会走索引查询，这里Text.contains会退化为过滤条件，作为过滤条件时，查询文本需全部包含才满足。

**Comment by zx-6017** [comment]
name不用id查询呢  有什么办法吗

顶点 ：
name：area_北京海淀
search_name : 北京海淀

search引擎：
search.text_analyzer=hanlp
search.text_analyzer_mode=standard

g.V().has('name','area_北京海淀').has('search_name',Text.contains('海淀')) 可以找到
g.V().has('name','area_北京海淀').has('search_name',Text.contains('海淀黄庄')) 找不到

这样？ 谢谢

**Comment by javeme** [comment]
> g.V().has('name','area_北京海淀').has('search_name',Text.contains('海淀')) 可以找到
> g.V().has('name','area_北京海淀').has('search_name',Text.contains('海淀黄庄')) 找不到

@zx-6017 这个是预期的。
如果需要按照模糊查询，则使用`g.V().has('search_name',Text.contains('海淀黄庄'))`即可，如果需要额外过滤可以使用filter条件。主要还是按照你的需求来使用，原则就是 https://github.com/hugegraph/hugegraph/issues/1242#issuecomment-721556004 所说的。
