### ISSUE TITLE
graph 迭代器，不支持批量remove，有没有可以支持的方案？

### ISSUE THREAD

**Issue by tmljob** [hugegraph/hugegraph#1245]
graph 有一系列 iterateEdges() 方法返回迭代器，可以以分页的方式获取边，你只要不停地调用 hasNext() 
 和 next() 获取下一条即可。

```
// 每次请求1000条边
Iterator<Edge> edges = graph.iterateEdges(1000);
while (edges.hasNext()) {
    // 这一批的1000条迭代完会自动获取下一个1000条
    Edge edge = edges.next();
}
```

_Originally posted by @Linary in https://github.com/hugegraph/hugegraph/issues/148#issuecomment-434221086_

**Comment by tmljob** [comment]
Iterator<Vertex> vertices = graph.iterateVertices("rel_D_wuqianw", 10000);
while (vertices.hasNext()) {
    vertices.remove();
}

如上代码，会报异常：
java.lang.UnsupportedOperationException: remove
	at java.util.Iterator.remove(Iterator.java:93)

有没有可以支持的方案，来达到按照某一顶点或边label迭代遍历清空其所有数据？
@Linary

**Comment by javeme** [comment]
@tmljob 目前只能单条删除`removeVertex(vertexId)`。

```java
Iterator vertices = graph.iterateVertices("rel_D_wuqianw", 10000);
while (vertices.hasNext()) {
  graph.removeVertex(vertices.next());
}
```
另外大量删除数据会导致性能问题，建议尽量避免该操作。
