### ISSUE TITLE
server-0.10.4版本是否支持ttl设置？

### ISSUE THREAD

**Issue by tmljob** [hugegraph/hugegraph#1251]
server-0.10.4+client-1.8.0，client-1.8.0没有开放顶点/边 定义ttl。

1、仅升级client包，是否可以支持ttl设置？后端是hbase。

2、对于已经定义的顶点/边，原来没有设置ttl，如果可以通过升级client更新顶点/边的ttl，是否对修改前的数据生效？

**Comment by javeme** [comment]
@tmljob 必须要设计server到0.11.2版本才支持ttl的。

**Comment by tmljob** [comment]
1、只升级server就可以了嘛？后端存储如hbase，需要重新初始化吗？
2、支持ttl后，是不是通过ttl的设置删除数据，比直接删除数据性能好？
3、创建shcema定义时没有设置ttl，入库了一部分数据，后面修改schema定义设置ttl，对已入库的数据生效吗？

**Comment by zhoney** [comment]
@tmljob 
`1、只升级server就可以了嘛？后端存储如hbase，需要重新初始化吗？`
需要升级server到0.11，client到1.9，因为改了后端存储结构，需要重新初始化存储后端，并导入数据

`2、支持ttl后，是不是通过ttl的设置删除数据，比直接删除数据性能好？`
TTL使得用户查询时不再需要过滤过期的的数据，且不用考虑过期数据的删除，更为友好。在性能上来说，存储后端自带的ttl功能实现的，比如Cassandra和hbase，原则上比直接删除更好。

`3、创建shcema定义时没有设置ttl，入库了一部分数据，后面修改schema定义设置ttl，对已入库的数据生效吗？`
对已存在的schema无法增加ttl设置。

**Comment by tmljob** [comment]
> @tmljob
> 
> > 1、只升级server就可以了嘛？后端存储如hbase，需要重新初始化吗？
> 
> 需要升级server到0.11，client到1.9，因为改了后端存储结构，需要重新初始化存储后端，并导入数据
> 
> > 2、支持ttl后，是不是通过ttl的设置删除数据，比直接删除数据性能好？
> 
> TTL使得用户查询时不再需要过滤过期的的数据，且不用考虑过期数据的删除，更为友好。在性能上来说，存储后端自带的ttl功能实现的，比如Cassandra和hbase，原则上比直接删除更好。
> 
> > 3、创建shcema定义时没有设置ttl，入库了一部分数据，后面修改schema定义设置ttl，对已入库的数据生效吗？
> 
> 对已存在的schema无法增加ttl设置。

这个也就是说ttl在创建顶点或边schema时设置后就无法修改了是嘛？如果要修改只能删除顶点或边shcema重建？
