### ISSUE TITLE
huge-studio不能显示较大数量级的边，查询时只显示限定的顶点，而没有边

### ISSUE THREAD

**Issue by dyhyao6** [hugegraph/hugegraph#1259]
### Expected behavior 期望表现
{type something here...}
<img width="473" alt="企业微信截图_20201113085841" src="https://user-images.githubusercontent.com/49445844/99038652-d2789b00-25c0-11eb-95bb-a799a90a8230.png">

  @javeme @Linary **这是我导入的数据集，查询时只有顶点**，为啥没有不显示边
<img width="960" alt="企业微信截图_20201112203749" src="https://user-images.githubusercontent.com/49445844/99037540-d73c4f80-25be-11eb-831a-b93d9d3225eb.png">

### Actual behavior 实际表现
{type something here...}

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by Linary** [comment]
你选几个点双击一下试试，如果双节了没用，说明这些点就是没有边与之相连。另外你想看到边，可以用`g.E()`或者`g.V().bothE()`这类带边的语句。

**Comment by boo-boos** [comment]
您好，我这里也出现了不显示边的问题，能否请教下？希望能加QQ939172638

**Comment by javeme** [comment]
@boo-boos 可关注HugeGraph公众号加入微信交流群
