### ISSUE TITLE
schedule-backup 问题

### ISSUE THREAD

**Issue by big1white** [hugegraph/hugegraph#1261]
### Expected behavior 期望表现
{type something here...}
周期任务可以取消，可以更改

### Actual behavior 实际表现
{type something here...}
没有取消选项，后续设置也没法覆盖

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by zhoney** [comment]
@big1white schedule-backup目前是没有取消和更改功能的，只能增加。
另外，schedule-backup是借助crontab实现的，如果要更改可以用`crontab -e`，删除可以用`crontab -r`

**Comment by big1white** [comment]
> @big1white schedule-backup目前是没有取消和更改功能的，只能增加。
> 另外，schedule-backup是借助crontab实现的，如果要更改可以用`crontab -e`，删除可以用`crontab -r`

使用crontab -r 后以为没有周期任务了，但其实
周期备份任务一直存在，因为之前设置了多次该命令，导致后台挂着许多该进程，占据了大量内存，有点毒瘤啊，建议赶紧改掉
![QQ截图20201202185304](https://user-images.githubusercontent.com/42825958/100863790-07955080-34d0-11eb-9298-547693bbaf80.png)
![QQ截图20201202185347](https://user-images.githubusercontent.com/42825958/100863902-36132b80-34d0-11eb-9493-da02c9d6cd10.png)
![QQ截图20201202185358](https://user-images.githubusercontent.com/42825958/100863929-3f03fd00-34d0-11eb-9a09-3ccc297c2aaf.png)

**Comment by zhoney** [comment]
@big1white 
`crontab -r`是停止周期性的备份。

你的系统有这么多的备份任务，可能的原因是：
1. 之前的备份任务没有完成或者备份失败残留下来了
2. 使用`crontab -r`时的用户权限较低，并没有删掉`schedule-backup`生成的周期任务
