### ISSUE TITLE
restore和清空图

### ISSUE THREAD

**Issue by big1white** [hugegraph/hugegraph#1263]
### Expected behavior 期望表现
{type something here...}
restore要求一个新的图，我如果要频繁执行restore的话就需要创建多个图实例，然而这些图实例使用频率不会很高，可能仅仅使用一次，造成空间浪费，所以想问有可以把现有的图数据和元数据清空的方式吗？以便直接使用restore命令

### Actual behavior 实际表现
{type something here...}

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}
最新

**Comment by zhoney** [comment]
@big1white  tools里面有graph-clear命令可以用来清空图：https://hugegraph.github.io/hugegraph-doc/quickstart/hugegraph-tools.html
![image](https://user-images.githubusercontent.com/17330028/99253247-62ca1080-284b-11eb-9f79-0579e0ff5a9b.png)

另外，也可以直接使用RESTful的接口：https://hugegraph.github.io/hugegraph-doc/clients/restful-api/graphs.html
![image](https://user-images.githubusercontent.com/17330028/99253309-7e351b80-284b-11eb-9adb-df346bdbd0d2.png)
