### ISSUE TITLE
清空数据出错

### ISSUE THREAD

**Issue by big1white** [hugegraph/hugegraph#1265]
### Expected behavior 期望表现
{type something here...}
java下使用该命令删除数据
hugeClient.graphs().clear("hugegraph", "I'm sure to delete all data");

### Actual behavior 实际表现
{type something here...}

![QQ截图20201116173857](https://user-images.githubusercontent.com/42825958/99237115-03f89d00-2833-11eb-86f9-d2912ade459d.png)
数据量不大，只有两条数据
客户端，数据库都在本地
### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}
最新版本

**Comment by javeme** [comment]
@big1white 看报错是超时了，是否使用的hbase后端，一般hbase的clear耗时较长。

**Comment by big1white** [comment]
> @big1white 看报错是超时了，是否使用的hbase后端，一般hbase的clear耗时较长。可以重试或者调大超时时间。

后端是hbase，调长了hbase.rpc.timeout，hbase.client.operation.timeout，hbase.client.scanner.timeout.period没有效果，想问HugeClient的超时时间如何设置

**Comment by big1white** [comment]
> @big1white 看报错是超时了，是否使用的hbase后端，一般hbase的clear耗时较长。可以重试或者调大超时时间。

设置了HugeGraph Client的超时时间后正常了
