### ISSUE TITLE
如何在api查询中返回结果的总数量

### ISSUE THREAD

**Issue by zx-6017** [hugegraph/hugegraph#1266]
### Expected behavior 期望表现
{type something here...}
![image](https://user-images.githubusercontent.com/29519884/99342025-f50efa80-28c5-11eb-8462-0a2b672faf1b.png)
这样的api查询中  比如在图中总共有10000条信息被命中，怎么在结果中出现这个数值？
简单来说就是 如何在结果中返回命中的总数量 和 本次返回的数量

### Actual behavior 实际表现
{type something here...}

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by javeme** [comment]
@zx-6017 不太明确“命中”的含义，希望可以详细解释一下。结果的总数量可以使用`count`：`g.V().hasLabel('xx').has('k','v').count()`

**Comment by zx-6017** [comment]
所以总数量的查询 必须要额外的单独一次额外的查询吗
