### ISSUE TITLE
为什么会存在多个InitStore相关的进程(已完成初始化)

### ISSUE THREAD

**Issue by tmljob** [hugegraph/hugegraph#1273]
已完成后端初始化，但还存在多个InitStore相关的进程，如下。
（搭建了多套环境，只有1个有这种现象）

![image](https://user-images.githubusercontent.com/69188034/99648578-2803ea80-2a8e-11eb-87e8-ee6caac8456a.png)

**Comment by javeme** [comment]
@tmljob 检查下日志看看是否有发生什么错误导致进程没有结束。

**Comment by tmljob** [comment]
这个应该是0.10.2版本hbase作为后端存储，还没有支持Kerberos认证。而对接的hbase环境开启了Kerberos，执行初始化的时候报错了。
