### ISSUE TITLE
使用client访问hugegraph时，java代码中hugeclient找不到builder方法

### ISSUE THREAD

**Issue by lixuanhng** [hugegraph/hugegraph#1276]
### Expected behavior 期望表现
{正常获取图谱中的顶点或边}

### Actual behavior 实际表现
{在本地使用IDEA，按照doc说明，新建maven工程并添加hugegraph依赖，但是运行代码时提示找不到hugeclient.builder的方法，寻求方法多时无果，不知道是配置没有配好还是什么原因，还请指教}

报错贴图：
![在HugeClient中找不到builder](https://user-images.githubusercontent.com/40484583/99952496-b80da100-2dba-11eb-9a2e-7e6e5019ee87.png)

配置完成情况：
![maven配置1](https://user-images.githubusercontent.com/40484583/99952683-fe630000-2dba-11eb-83ff-7ac9dbd09819.png)

**Comment by Linary** [comment]
@lixuanhng 请使用 1.9.0 以上的 client

**Comment by lixuanhng** [comment]
> @lixuanhng 请使用 1.9.0 以上的 client

请问1.9.0的client支持0.10.4版本的hugegraph吗？

**Comment by Linary** [comment]
@lixuanhng 兼容的。
