### ISSUE TITLE
清空图过慢，restore命令又需要空图

### ISSUE THREAD

**Issue by big1white** [hugegraph/hugegraph#1277]
### Expected behavior 期望表现
{type something here...}
清空速度加快，restore命令不需要空图

### Actual behavior 实际表现
{type something here...}
清空图的命令过于缓慢，即使是小数据量的图依然很慢，不明白restore命令为什么必须要求一个空的图，因为这个要求每次使用这个命令都要清空图就很麻烦且缓慢

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by zhoney** [comment]
@big1white 采用的是什么存储后端？清空大概需要多久时间呢？

另外 restore也不一定需要清空图，根据你的需要选择，可以参考：https://hugegraph.github.io/hugegraph-doc/guides/backup-restore.html

**Comment by big1white** [comment]
> @big1white 采用的是什么存储后端？清空大概需要多久时间呢？
> 
> 另外 restore也不一定需要清空图，根据你的需要选择，可以参考：https://hugegraph.github.io/hugegraph-doc/guides/backup-restore.html

用的是hbase后端，用时10秒以上；不清空图的话，就得不停创建新的图也是比较麻烦，
另外这个是0.10.4版本，我看0.11版本在hbase后端的清除有些改进

**Comment by zhoney** [comment]
@big1white HBase和Cassandra是分布式存储，schema删除是慢一些。

> 我看0.11版本在hbase后端的清除有些改进
是的，0.11在清空HBase后端的场景有改进，可以试一下。

方便的话，可以描述一下业务场景，为什么需要经常restore数据到一个空图/新图，或许有其他的方案可以替代
