### ISSUE TITLE
文档上的最新版本都无法下载

### ISSUE THREAD

**Issue by jiyouyou125** [hugegraph/hugegraph#1278]
### Expected behavior 期望表现
![image](https://user-images.githubusercontent.com/696937/100201964-a4d60f00-2f3b-11eb-8c84-6e77826deb65.png)

### Actual behavior 实际表现
期望可下载

### Steps to reproduce the problem 复现步骤
实际都显示Not Found

**Comment by javeme** [comment]
@jiyouyou125 本周正在发布版本，目前已上传了server、loader、tools包。

**Comment by Linary** [comment]
@jiyouyou125 链接可用了。

**Comment by jiyouyou125** [comment]
@Linary hubble 1.5.0还是没有
