### ISSUE TITLE
使用postgres存储，配置项不能指定database，这样不好吧

### ISSUE THREAD

**Issue by dyhyao6** [hugegraph/hugegraph#1285]
### Expected behavior 期望表现
{type something here...}
@javeme 
jdbc.driver=org.postgresql.Driver
jdbc.url=jdbc:postgresql://localhost:5432/database
### Actual behavior 实际表现
{type something here...}
jdbc.driver=org.postgresql.Driver
jdbc.url=jdbc:postgresql://localhost:5432/
jdbc.username=
jdbc.password=
@Linary 
### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by Linary** [comment]
为什么要自己指定database呢？默认就是连当前这个图对应的database啊。

**Comment by javeme** [comment]
@dyhyao6 目前的设计是每个图实例对应的会创建一个database，创建多个图就有多个pg的database。

**Comment by dyhyao6** [comment]
> 为什么要自己指定database呢？默认就是连当前这个图对应的database啊。

抱歉，我表述有误。
问题是这样的：
我在pg里创建了huge用户，创建了名为hugegraph的database，配置用户名huge密码password。初始化时提示没有名为huge的database。于是我另外新建了名为huge的database，这是才初始化成功。我的问题就是，为啥需要创建和用户名一样的数据库。此问题没有截图，抱歉。 @ @javeme @Linary

**Comment by Linary** [comment]
你的配置文件`hugegraph.properties`中的store配置的值是什么？`hugegraph`执行`init-store.sh`时会在你的数据库中创建一个database，这个database的名字就是store的值，跟用户名没有关系的。

**Comment by dyhyao6** [comment]
> 你的配置文件`hugegraph.properties`中的store配置的值是什么？`hugegraph`执行`init-store.sh`时会在你的数据库中创建一个database，这个database的名字就是store的值，跟用户名没有关系的。

<img width="373" alt="企业微信截图_20201207183159" src="https://user-images.githubusercontent.com/49445844/101340362-9502e700-38ba-11eb-833e-5c8492709901.png">
<img width="334" alt="企业微信截图_20201207183143" src="https://user-images.githubusercontent.com/49445844/101340382-9c29f500-38ba-11eb-91c9-ae1689256bc4.png">
这是我的配置文件，值是hugegraeph。可是普通用户没有建库的权限呀。能按照我这样的配置初始化话吗？

**Comment by zhoney** [comment]
@dyhyao6 
`PostgreSQL`连接必须指定`database`，如果没有指定（我们代码里建库之前建立连接没有指定`database`），就会尝试连接跟`user`相同的`database`。这是出错的原因。

我在 #1293 中改进了下，只要指定的`user`具有`createDB`的权限，就可以`init-store`和`start-hugegraph`。

**Comment by dyhyao6** [comment]
> @dyhyao6
> 指定database是通过`store`，而不是`jdbc.url`
> 
> `PostgreSQL`连接必须指定`database`，如果没有指定（我们代码里建库之前建立连接没有指定`database`），就会尝试连接跟`user`相同的`database`。这是出错的原因。
> 
> 我在 #1293 中改进了下，只要指定的`user`具有`createDB`的权限，就可以`init-store`和`start-hugegraph`。

谢谢，这样讲我就明白了
