### ISSUE TITLE
server-api 版本问题

### ISSUE THREAD

**Issue by big1white** [hugegraph/hugegraph#1286]
### Expected behavior 期望表现
{type something here...}

### Actual behavior 实际表现
{type something here...}
![QQ截图20201202145343](https://user-images.githubusercontent.com/42825958/100838929-54682f80-34ae-11eb-9eb8-6a919f7a391a.png)
stuido下连接0.11版本的hugegraph-server出现该问题，想要了解修改哪部分内容可以兼容最近版的server

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by Linary** [comment]
这是studio用了旧版本的client，无法匹配高版本的server了，你可以使用新的前端产品hubble试试。
beta版链接:https://pan.baidu.com/s/1xGeshkZjKvhJWKYHFjETtw  密码:6vfn

**Comment by javeme** [comment]
> 想要了解修改哪部分内容可以兼容最近版的server

可以修改依赖的client版本号到1.9版本即可：https://mvnrepository.com/artifact/com.baidu.hugegraph/hugegraph-client/1.9.1
