### ISSUE TITLE
关于https的配置只是restserver配置么？gremlin server如何使用https

### ISSUE THREAD

**Issue by dyhyao6** [hugegraph/hugegraph#1291]
### Expected behavior 期望表现
{type something here...}
restserver和gremlin server同时开启https

### Actual behavior 实际表现
{type something here...}
配置https时实际配置如下图：
<img width="317" alt="企业微信截图_20201207194530" src="https://user-images.githubusercontent.com/49445844/101347818-98e83680-38c5-11eb-89e0-42aa02be19c1.png">

<img width="465" alt="企业微信截图_20201207194631" src="https://user-images.githubusercontent.com/49445844/101347858-a69dbc00-38c5-11eb-8865-32ce4a0cb22f.png">
<img width="299" alt="企业微信截图_20201207194724" src="https://user-images.githubusercontent.com/49445844/101347876-ac939d00-38c5-11eb-8c04-603e7817b88e.png">

请问这是配置好了吗？
@Linary @javeme 
有个疑问就是gremlin-server.yml配置中
<img width="248" alt="企业微信截图_20201207200010" src="https://user-images.githubusercontent.com/49445844/101348709-106a9580-38c7-11eb-9971-855e1345fb61.png">

起啥作用？是gremlinserver启用ssl吗？

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by dyhyao6** [comment]
还有个问题就是，我把huge-server.keystore文件的密码：ssl.keystore_password=wrangpassord，改为错误的密码后，启动 bin/start-hugegraph.sh。如下：
<img width="947" alt="企业微信截图_20201207195900" src="https://user-images.githubusercontent.com/49445844/101349060-ae5e6000-38c7-11eb-8a75-787f2aaf6a28.png">
密码错误
<img width="671" alt="企业微信截图_20201207195947" src="https://user-images.githubusercontent.com/49445844/101349080-b61e0480-38c7-11eb-931e-ade2133ca9c1.png">
查看进程，居然有hugegraphserver的进程，为啥？
<img width="298" alt="企业微信截图_20201207195928" src="https://user-images.githubusercontent.com/49445844/101349096-bd451280-38c7-11eb-8e72-ca114fc7c87c.png">
 @javeme @Linary

**Comment by dyhyao6** [comment]
@Linary @wenzhenghu 帮忙解决一下这个问题，谢谢

**Comment by javeme** [comment]
@dyhyao6 是的，参考这个文档配置即可：https://hugegraph.github.io/hugegraph-doc/config/config-https.html 。一般来说 gremlin server 不直接对外暴露服务，无需启用ssl，如果明确要启用可以修改gremlin-server.yml的ssl配置项。

**Comment by javeme** [comment]
> 还有个问题就是，我把huge-server.keystore文件的密码：ssl.keystore_password=wrangpassord，改为错误的密码后，启动 bin/start-hugegraph.sh。如下：
> <img alt="企业微信截图_20201207195900" width="947" src="https://user-images.githubusercontent.com/49445844/101349060-ae5e6000-38c7-11eb-8a75-787f2aaf6a28.png">
> 密码错误
> <img alt="企业微信截图_20201207195947" width="671" src="https://user-images.githubusercontent.com/49445844/101349080-b61e0480-38c7-11eb-931e-ade2133ca9c1.png">
> 查看进程，居然有hugegraphserver的进程，为啥？
> <img alt="企业微信截图_20201207195928" width="298" src="https://user-images.githubusercontent.com/49445844/101349096-bd451280-38c7-11eb-8e72-ca114fc7c87c.png">
> @javeme @Linary

@lxb1111 可以看看是否预期

**Comment by dyhyao6** [comment]
> @dyhyao6 是的，参考这个文档配置即可：https://hugegraph.github.io/hugegraph-doc/config/config-https.html 。一般来说 gremlin server 不直接对外暴露服务，无需启用ssl，如果明确要启用可以修改gremlin-server.yml的ssl配置项。
 @javeme 我修改了gremlin-server.yml的ssl=true，但是初始化出现了问题，您可以复现一下吗？确实会有错误
