### ISSUE TITLE
使用habse作为存储，开启kerbero后出现的错误

### ISSUE THREAD

**Issue by dyhyao6** [hugegraph/hugegraph#1292]
### Expected behavior 期望表现
{type something here...}

### Actual behavior 实际表现
{type something here...}
@javeme @Linary 这个问题如何解决
<img width="958" alt="企业微信截图_20201209105919" src="https://user-images.githubusercontent.com/49445844/101568614-d952cc00-3a0d-11eb-8a33-916518c1ef1d.png">
   我的配置和出现的问题，
<img width="440" alt="企业微信截图_20201209105943" src="https://user-images.githubusercontent.com/49445844/101568628-df48ad00-3a0d-11eb-937c-c1f3773d1457.png">

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by javeme** [comment]
@dyhyao6 可以参考下这两篇文章：
https://www.cnblogs.com/Amos-Turing/p/9620932.html
https://www.jianshu.com/p/d79876c6a931
