### ISSUE TITLE
海量数据查询性能问题

### ISSUE THREAD

**Issue by cmdares** [hugegraph/hugegraph#1297]
当点的数据达到亿级别的时候，最短路径查询出现Error!Failed to do request，不知道是由于什么原因导致该查询出现错误。
详细测试过程如下连接：
https://www.cnblogs.com/chenpu/p/12421490.html

**Comment by javeme** [comment]
@cmdares 请确保测试的2个顶点之间确实存在二度最短路径，也可以尝试使用性能更好的[Shortest Path API](https://hugegraph.github.io/hugegraph-doc/clients/restful-api/traverser.html)

另外，从测试数结果看，服务端写入速度一般在万/秒这个级别是比较正常的，可以看看是否客户端程序没有给服务足够的写入负载。

**Comment by javeme** [comment]
@cmdares 测试链接里面看到有`g.V().out()`这类测试，这个语句是查【全图的所有顶点的OUT方向邻接点】，一般来说这种查询在实际场景极少见，如果一定要测的话，可以试试异步任务跑`g.V().out().count()`。

也可以测试这些比较常见的场景（建议使用v0.11.2版）：
- g.V().count()：统计顶点的数量
- g.V().groupCount().by(out().count())：统计所有顶点的出度分布
- g.E().count()：统计边的数量

**Comment by cmdares** [comment]
首先要感谢你的回复，这里针对路径分析的需求较为复杂：
1、在路径寻找的过程中，需要指定边的属性和节点属性，比如：寻找姚明到拜登的关系网络中，中间多跳的连线关系只关心商业关系或房产关系。同时中间经历的人员年龄只要30至50岁的男性。
2、可否能够支持带权重的路径分析，如：不同边类型的权值不同，在计算两点最短路径的逻辑中，可以自定义权值计算逻辑。最后求出加权最短路径，在变量过程中还要能够支持问题1中的过滤逻辑。
在这类复杂场景的分析中，如何能够方便的实现这类逻辑，又能够达到速度最优，的确有些挑战。
此外这些能力也是在诸多图库平台上所面临的问题。
感谢，关注，希望Hugegraph能够深入。

**Comment by zhoney** [comment]
@cmdares 
HugeGraph一直在扩充、增强一些常用图遍历算法，比如0.11.2增加了像**加权最短路径**、多点最短路径、单源最短路径等10个算法，具体的可以参见[Traverse API](https://hugegraph.github.io/hugegraph-doc/clients/restful-api/traverser.html)。

虽然0.11.2支持了加权最短路径，但目前能够支持的情况有限，还达不到你的业务需要的灵活度。比如像指定权值计算逻辑，以及在遍历过程中对顶点和边的属性进行过滤这些能力目前还不具备，当前只能通过Gremlin来实现。

另外，你的这些业务诉求对我们也是一个方向性的参考，我们会在下一步增强遍历算法时考虑对这些能力的支持。

**Comment by cmdares** [comment]
@zhoney 感谢专家的关注，期待hugegraph能够更加实用。
