### ISSUE TITLE
bulkload功能有没有具体成功例子呀

### ISSUE THREAD

**Issue by 597477803** [hugegraph/hugegraph#1300]
图谱每天要导入几十亿（节点和关系），loader工具太慢了，bulkload功能有成功的例子或具体的说明么？

**Comment by javeme** [comment]
bulkload方式并不适用于每天增量导入，建议还是使用loader，每天按照四十亿算，只需要每秒5万的速度即可满足（小规模集群即可）。使用的是什么后端？目前loader的速度多少？

**Comment by 597477803** [comment]
> bulkload方式并不适用于每天增量导入，建议还是使用loader，每天按照四十亿算，只需要每秒5万的速度即可满足（小规模集群即可）。使用的是什么后端？目前loader的速度多少？
我们是每天全量的呀。使用hbase后端，具体速度因为加载失败了还没看到，后面看下。所以bulkload的方式有没说明资料呀？

**Comment by JackyYangPassion** [comment]
全量初始化 需要 bulkload ，底层我也是准备用HBase

**Comment by javeme** [comment]
@imbajin HBase的bulkload思路你可以分享下么

**Comment by JackyYangPassion** [comment]
我这边自己实现了一个图存储，很简单，vertex 和 edge 存储在一个HBase 表；然后依赖HBase bulkload 接口 利用MR 实现了离线BulkLoad 功能；
1. 因为表的rowkey 设计很简单，所以Bulkload 代码就是序列化rowkey 调用接口导入，好处就是离线导入不影响线上查询
2. 线上查询 主要是 利用 scan prefix filter 实现了 子图查询 及图特征计算

**Comment by JackyYangPassion** [comment]
目前正在调研新的图数据库，其中 hugegraph 要是支持HBase bulkload 功能，对于线上应用及导入数据意义很大，如果可能可以一起开发实现，我对HBase 比较熟悉

**Comment by imbajin** [comment]
可以的, 思路和大体方案其实跟上面说的类似, 目前是用MR的默认接口去实现.  (当然最好是用spark代替)
数据这边关键的也是在于转换parse这层, 然后区别在于bulkload的写法用的是内部自己的 (比如社区加载hfile是单机的, 我们也是并发的)

然后还有个比较大的区别, 在于我们除了批量写, 还有很重要的批量删, 和批量更新, 后面需要批量的 `scan` 表, 所以整个逻辑又会做整合. 

之后会把写过的图 + bulkload文章更新放一下. 可以保持交流. 能推个通用版到社区是更好

**Comment by javeme** [comment]
@imbajin @JackyYangPassion 可以启动一个独立项目来实现这个功能，做出一个比较通用的版本。

**Comment by JackyYangPassion** [comment]
可以的

**Comment by JackyYangPassion** [comment]
> @imbajin @JackyYangPassion 可以启动一个独立项目来实现这个功能，做出一个比较通用的版本。

可以的

**Comment by tmljob** [comment]
@JackyYangPassion @imbajin 
hugegraph 支持HBase bulkload 功能这个后面有进展嘛？很期待这个功能

**Comment by imbajin** [comment]
> @JackyYangPassion @imbajin
> hugegraph 支持HBase bulkload 功能这个后面有进展嘛？很期待这个功能

有的, 不过之前是写的内部版本, 依赖内部包, 得转换为一个通用社区版, 忙完手头事做一下.

**Comment by tmljob** [comment]
> > @JackyYangPassion @imbajin
> > hugegraph 支持HBase bulkload 功能这个后面有进展嘛？很期待这个功能
> 
> 有的, 不过之前是写的内部版本, 依赖内部包, 得转换为一个通用社区版, 忙完手头事做一下.

好的，期待尽快上线哈

**Comment by tmljob** [comment]
> > @JackyYangPassion @imbajin
> > hugegraph 支持HBase bulkload 功能这个后面有进展嘛？很期待这个功能
> 
> 有的, 不过之前是写的内部版本, 依赖内部包, 得转换为一个通用社区版, 忙完手头事做一下.

@imbajin ,这个支持HBase bulkload 通用社区版可以发布了吗？期待呀
