### ISSUE TITLE
RDF转适合hugegraph的属性图非常困难

### ISSUE THREAD

**Issue by happy-nlp** [hugegraph/hugegraph#1302]
遇到一个图设计的问题，我有一批数据需要从RDF形式转为属性图入库，感觉十分棘手，RDF可以说每个实体都是一个label，hugegraph似乎有意限定少量的实体类型，而且关系似乎也要约束很少的头尾实体label，转换起来似乎需要人工把所有数据重新定义一遍。而且强行压缩很多实体到一个类别里，会大大增加单个实体的属性数量，单个实体属性总量会非常大，也会超出限制。

想问下最多支持多少节点label，边label，实体最大属性数量是多少，从RDF转属性图入库，用hugegraph有什么借鉴经验吗，是否可以分享些文档，我在公司力推hugegraph，但是没有人能帮我解决问题，希望解决我两个棘手的问题，十分感谢！

**Comment by javeme** [comment]
@boo-boos 如果不希望精细化建模，那么可以使用抽象的label，可以高度灵活自由，比如顶点类型统一使用entity、边类型统一使用relation，entity内部通过一个属性来表示实体的具体类型，比如type、tag等属性。实体属性总量大没关系，设置为`可空`不影响。

精细化建模的好处是查询精确、性能更好，但是对数据结构化要求高。

**Comment by boo-boos** [comment]
> @boo-boos 如果不希望精细化建模，那么可以使用抽象的label，可以高度灵活自由，比如顶点类型统一使用entity、边类型统一使用relation，entity内部通过一个属性来表示实体的具体类型，比如type、tag等属性。实体属性总量大没关系，设置为`可空`不影响。
> 
> 精细化建模的好处是查询精确、性能更好，但是对数据结构化要求高。

您好，感谢回复。为了减小工作量，我目前采用的就是您所述的方法。但强行合并label后， 每个实体有1200多个属性，似乎超出了限制，每次都会报错，导致无法入库？
还有一个关系入库的bug困扰着我，我用csv方式存储的关系，每行只有两个自定义id用于建立连接，但是vertex中自定义id和name联合做主键，入库关系时报错Invalid id
例如某一行 sx27105,sx10945
写入关系时报错Invalid vertex id '1:null!sx27105'
经检索sx27105实体已经入库.我怀疑是你们仍然用name和id组合去查找实体了，但是我只用id属性做关联。

还有个小问题，默认展示的是主键，我想展示其他字段怎么设置呢？
