### ISSUE TITLE
Gremlin带索引的查询，返回相同数据量，使用limit返回速度随结果数量增长非线性增长

### ISSUE THREAD

**Issue by philipy1219** [hugegraph/hugegraph#1305]
### Expected behavior 期望表现
Gremlin带索引的查询，返回相同数据量，使用limit返回速度随结果数量增长为线性

### Actual behavior 实际表现
Gremlin带索引的查询，返回相同数据量，使用limit返回速度随结果数量增长非线性增长；而使用分页方式的总体耗时，低于一次性返回耗时。

但在不带索引的查询中，limit返回和分页返回的总耗时接近。

测试使用Scylla作为存储，使用Cassandra作为存储问题相同。

使用limit 返回查询结果的耗时
Scylla | 无索引 | secondary | range
-- | -- | -- | --
100 | 0.03 | 0.02 | 0.02
1000 | 0.09 | 0.15 | 0.14
10000 | 0.84 | 2.03 | 1.98
20000 | 1.53 | 7.18 | 7.07
50000 | 3.59 | >30 | >30

使用分页返回，页数为2的耗时
Scylla | 无索引 | secondary | range
-- | -- | -- | --
100 | 0.03 | 0.03 | 0.03
1000 | 0.09 | 0.16 | 0.16
10000 | 0.84 | 1.62 | 1.56
20000 | 1.53 | 4.14 | 4.00
50000 | 3.59 | 23.79 | 23.69

使用分页返回，页数为5的耗时
Scylla | 无索引 | secondary | range
-- | -- | -- | --
100 | 0.03 | 0.04 | 0.04
1000 | 0.13 | 0.17 | 0.19
10000 | 1.08 | 1.50 | 1.47
20000 | 1.94 | 3.01 | 2.85
50000 | 4.39 | 11.09 | 10.62

#### Vertex/Edge summary 数据量
- loaded vertices amount: 亿级
- loaded edges amount:  十亿级

### Specifications of environment 环境信息
hugegraph version: 0.10.4
operating system: centos 7.4, 16 CPUs, 128G RAM
hugegraph backend: scylladb 4.0.4 cluster with 3 nodes, 1 x 1TB SSD disk each node

**Comment by javeme** [comment]
@philipy1219 可以提供一下数据示例和查询语句吗？

**Comment by philipy1219** [comment]
查询语句 limit

无索引
	http://ip:8080/gremlin?gremlin=hugegraph.traversal().V().hasLabel("label").limit(1000)
Secondary索引
	http://ip:8080/gremlin?gremlin=hugegraph.traversal().V().hasLabel("label").has("country","CN").limit(1000)
Range索引
	http://ip:8080/gremlin?gremlin=hugegraph.traversal().V().hasLabel("label").has("appDate",P.eq("2017-12-29")).limit(1000)

查询语句 分页

无索引
	http://ip:8080/gremlin?gremlin=hugegraph.traversal().V().hasLabel("label").range(0,500)
        http://ip:8080/gremlin?gremlin=hugegraph.traversal().V().hasLabel("label").range(500,1000)
Secondary索引
	http://ip:8080/gremlin?gremlin=hugegraph.traversal().V().hasLabel("label").has("country","CN").range(0,500)
        http://ip:8080/gremlin?gremlin=hugegraph.traversal().V().hasLabel("label").has("country","CN").range(500,1000)
Range索引
	http://ip:8080/gremlin?gremlin=hugegraph.traversal().V().hasLabel("label").has("appDate",P.eq("2017-12-29")).range(0,500)
        http://ip:8080/gremlin?gremlin=hugegraph.traversal().V().hasLabel("label").has("appDate",P.eq("2017-12-29")).range(500,1000)

数据示例
`{
	"requestId": "a3cd645c-6e17-4c70-9c42-52b716516f80",
	"status": {
		"message": "",
		"code": 200,
		"attributes": {}
	},
	"result": {
		"data": [{
			"id": "3342298",
			"label": "label",
			"type": "vertex",
			"properties": {
				"appId": "17211058.7",
				"id": "3342298",
				"country": "DE",
				"status": "1",
				"pubDate": "2018-07-04 00:00:00.000",
				"appDate": "2017-12-29 00:00:00.000",
				"lang": "en",
				"firstDate": "2016-12-31 00:00:00.000",
				"relatedId": "[\"2016905399P\"]",
				"classification": "[\"41308\"]",
				"name1": "[{\"snm\": \"Mitton, Jo Ann\", \"fnm\": \"\", \"adr\": {\"str\": \"108/3 Gladstone Street\", \"city\": \"2042 Newton, New South Wales\", \"ctry\": \"AU\"}}]",
				"name2": "[{\"snm\": \"Mitton, Jo Ann\", \"adr\": {\"str\": \"108/3 Gladstone Street\", \"city\": \"2042 Newton, New South Wales\", \"ctry\": \"AU\"}}]",
				"name3": "[]",
				"name4": "[{\"snm\": \"Groth & Co. KB\", \"adr\": {\"str\": \"P.O. Box 6107\", \"city\": \"102 32 Stockholm\", \"ctry\": \"SE\"}}]"
			}
		}],
		"meta": {}
	}
}`

**Comment by philipy1219** [comment]
升级到0.11.2之后，问题解决，带索引的查询目前返回耗时是线性增长
