### ISSUE TITLE
查询n度以内关系不返回结果或超时

### ISSUE THREAD

**Issue by chentianlong1993** [hugegraph/hugegraph#1311]
需求：查询指定顶点n度以内关系，如，查询某一顶点3度以内所有关系，期望返回1、2、3度关系集合。
语句：g.V('13:00E0A220EEE85167E2CC57F14801903C').repeat(bothE().otherV().simplePath()).emit(loops().is(lte(3))).path().dedup()
结果：返回是十几条数据时正常返回，若需要返回的是5000条以上数据则抛出超时异常。

请问是语句问题还是其他问题呢？若语句有问题，为何少量数据还可以正常返回呢？是否有其他写法能满足这个需求呢？

**Comment by javeme** [comment]
请使用下面语句：
```java
g.V('13:00E0A220EEE85167E2CC57F14801903C')
 .repeat(bothE().otherV().simplePath())
 .until(loops().is(gte(3)))
 .path().dedup()
```

如果中间有超级点，可以使用local degree limit跳过或者使用local sample采样：
```java
g.V('13:00E0A220EEE85167E2CC57F14801903C')
 .repeat(local(bothE().otherV().simplePath().limit(10)))
 .until(loops().is(gte(3)))
 .path().dedup()
```

**Comment by chentianlong1993** [comment]
感谢回复,close了。

**Comment by chentianlong1993** [comment]
您上次回复的语句，好像只能返回3度关系，与repeat().times(n)这种写法的结果是一致的，如图。
![image](https://user-images.githubusercontent.com/49865532/103133915-52c60c00-46e8-11eb-8b04-23ef66571970.png)
![image](https://user-images.githubusercontent.com/49865532/103133928-61acbe80-46e8-11eb-9e0b-374ced5e8672.png)
而我们的需求是，要把3度以内，1、2、3度的关系都返回。麻烦再看下。
