### ISSUE TITLE
Failed to start HugeGraphServer, requires at least 512m free memory

### ISSUE THREAD

**Issue by 1170300802** [hugegraph/hugegraph#1315]
### Expected behavior 期望表现
{type something here...}

### Actual behavior 实际表现
下载0.11.2Server后，inialized finished，尝试启动hugegraph-server.sh，报title中显示的错，内存可用大小绝对够。

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: 0.11.2
- operating system: macOS Catalina10.15.6  2.6GHz, 32GB 2667 MHz DDR4
- hugegraph backend: Hbase 2.3.3

**Comment by javeme** [comment]
@1170300802 建议通过`top -l 1 -s 0 | grep PhysMem`确认下

**Comment by 1170300802** [comment]
> @1170300802 建议通过`top -l 1 -s 0 | grep PhysMem`确认下

PhysMem: 20G used (2730M wired), 12G unused.
内存是够的

**Comment by yangsirman** [comment]
这是macos下一个脚本的bug，util.sh的第157行替换一下free=$(($((`top -l 1 | head -n 10 | grep PhysMem | awk -F',' '{print $2}'| awk -F'G' '{print $1}'`))*1024))

**Comment by coderzc** [comment]
已经修复，请查看 #1396
