### ISSUE TITLE
使用RESTful-Traverser API查询两个顶点的公共邻居

### ISSUE THREAD

**Issue by lixuanhng** [hugegraph/hugegraph#1317]
### Expected behavior 期望表现
返回的公共邻居，如例子所示：
{
    "same_neighbors":[
        "2:lop"
    ]
}

### Actual behavior 实际表现
返回结果如下：
![WechatIMG29](https://user-images.githubusercontent.com/40484583/103184989-61cdd980-48f5-11eb-86b3-94105b647540.jpeg)
在studio中是可以看到这两个实体时间是存在两个公共邻居的，server端口号没有问题

### Steps to reproduce the problem 复现步骤
http://localhost:8089/graphs/hugegraph/traversers/jaccardsimilarity?vertex="6:钠"&other="4:乳类及制品"

### Specifications of environment 环境信息
- hugegraph version: v0.10.4
- operating system: macos11.0.1
- hugegraph backend: like cassandra 3.11.9

**Comment by javeme** [comment]
@lixuanhng v0.10.4版本不支持的，需要v0.11.2版本才支持该接口。

**Comment by lixuanhng** [comment]
> @lixuanhng v0.10.4版本不支持的，需要v0.11.2版本才支持该接口。

明白，谢谢
