### ISSUE TITLE
在studio中检索最短路径从来都是超时？

### ISSUE THREAD

**Issue by 597477803** [hugegraph/hugegraph#1320]
hbase做后端存储，节点8亿，关系16亿，在studio中检索最短路径都没有成功的（最大步数调成2都不行）？
rest-server.properties、gremlin-server.yaml、hugegraph-studio.properties三个是关于超时的时间都设置大了，也不生效，始终都是30秒超时？怎么解？

**Comment by Linary** [comment]
如果超时调了都没用的话说明是客户端超时导致的，应该是studio中使用HugeClient时写死了超时时间，另外studio已经不维护了，请使用hubble，hubble中可以用`client.request_timeout`设置客户端超时时间。
