### ISSUE TITLE
loader导入关系的问题

### ISSUE THREAD

**Issue by happy-nlp** [hugegraph/hugegraph#1328]
我使用name作为主键，用另一个id字段来连接关系，总是报错。
只能使用主键来连接吗？那会导致studio上显示节点名都是id，使用体验很差

**Comment by javeme** [comment]
- 如果使用主键方式，只能使用主键进行连接；
- 导入也可以使用自定义id列方式，则可使用id字段来连接；
- 最新的hubble支持自定义显示字段，可以设置显示哪些列；

**Comment by Linary** [comment]
> 我使用name作为主键，用另一个id字段来连接关系，总是报错。
> 只能使用主键来连接吗？那会导致studio上显示节点名都是id，使用体验很差

边的源顶点和目标顶点的Id策略没依赖关系，主键id、自定义id都可以。报错的日志可以贴一下。

**Comment by datagic** [comment]
@Linary @javeme 
由于我的主键字符超过128，所以我增加了自增主键，但是字符超过128的列值和主键没什么对应关系，我实际想链接的列，也是超过128字符的那个列，这样应该如何操作呢？  是否需要自定义一个有规则的主键hash来替代原来字符超过128的那个列用于连接呢？

必须要通过主键进行连接吗？非主键可以连接吗？

**Comment by javeme** [comment]
边是通过顶点id来连接的，顶点的主键会被作为顶点id。可以采取任何方式预先给顶点生成好id，简单的方式可以是hash(主列)。
