### ISSUE TITLE
[查询异常]post请求进行gremlin 查询异常 （rocksdb存储后端）

### ISSUE THREAD

**Issue by DoubleBabylol** [hugegraph/hugegraph#1331]
### Expected behavior 期望表现
使用get和post，查询同一条gremlin，结果应该一致

### Actual behavior 实际表现
使用post请求查询带path()的gremlin，返回结果异常,均为{\"empty\":false,\"simple\":true}

### 1. post请求查询body：
```
//api
http://ip:8080/graphs/xgraph/jobs/gremlin
//body
 {"gremlin": "g.V().hasLabel('file', 'network').has('uid', within(180550774,2653739512)).aggregate('x').in('drop', 'visit').path().by('uid')", "bindings": {}, "language": "gremlin-groovy"}
```
通过taskid查询结果，关注返回值**task_result**,均为{\"empty\":false,\"simple\":true}
![image](https://user-images.githubusercontent.com/48874214/104314029-ce5ef000-5513-11eb-8833-5e1e32e14112.png)

### 2. 通过get请求查询同一条gremlin：
```
//api
http://ip:8080/gremlin?gremlin=xgraph.traversal().V().hasLabel('file').has('uid', within(180550774,2653739512)).in().path()
```
结果
![image](https://user-images.githubusercontent.com/48874214/104314570-94dab480-5514-11eb-9449-e31c9ee75db6.png)

### 3.使用其他gremlin语句查询path():
get:

![image](https://user-images.githubusercontent.com/48874214/104317197-9c9c5800-5518-11eb-876c-05462aaa3e7b.png)

post查询同一条gremlin语句，**仍为异常结果**
![image](https://user-images.githubusercontent.com/48874214/104317400-e2592080-5518-11eb-8fd1-9938985c860f.png)

### Specifications of environment 环境信息
- hugegraph version: {0.11}
- hugegraph backend: {rocksdb}

**Comment by javeme** [comment]
@DoubleBabylol 需要对task_result字符串进行json二次解析。

**Comment by DoubleBabylol** [comment]
作者你好，要怎样解析呢，并不是斜杠/ 的问题，即使解析task_result 也仅仅是将 {\'empty': False, \'simple': True}转换为{'empty': False, 'simple': True} ，实际需要的是返回正常的业务json数据    目前需要去掉对path的查询才能够返回正常的业务数据

**Comment by tido914** [comment]
在压缩和解压缩异步任务的结果时，使用 LZ4 替代 Gzip（hugegraph #1198）
请问如何用LZ4解压返回数据

**Comment by javeme** [comment]
@tido914 具体可参考源代码

**Comment by javeme** [comment]
@DoubleBabylol 不好意思，之前没有看清楚问题，现在明确了问题是post返回的路径系列化不正确，我们会分析原因并解决，确认下版本号是0.11对吗？

**Comment by 1436516871** [comment]
@javeme 已确认，0.11版本存在此问题，这个bad case我们会加入到回归测试用例里。
@DoubleBabylol 稍后我们相关同学会解决这个问题。

**Comment by DoubleBabylol** [comment]
好的  感谢

**Comment by javeme** [comment]
0.11.的最新版本 `v0.11.2-b2` 补丁包 已解决该问题。
