### ISSUE TITLE
0.11.2版本数据兼容问题

### ISSUE THREAD

**Issue by gwny** [hugegraph/hugegraph#1335]
请问0.11.2版本是否不兼容之前版本的数据。
后端存储：rocksdb
操作步骤：
1. 之前用的是0.10.4版本的server，后端存储采用的是rocksdb，数据存储在某个目录下（对应rocksdb.data_disks配置）。
2. 现在将server升级到了0.11.2版本，client升级到了1.9.1版本，rocksdb的rocksdb.data_disks配置还指向原来的目录。
3. 查询报错。`Not found key 'TTL' from entry xxx`

看TTL好像是新加的功能，请问是否不兼容以前的数据？是否需要重建schema，然后将数据重新导入？谢谢。

**Comment by zhoney** [comment]
@gwny 是的，`0.11.2`相比`0.10.4`存储结构发生了变化，无法兼容之前版本的数据。

比较推荐的方式是新建一个`0.11.2`的server，然后用hugegraph-tools的`migrate`命令将`0.10.4`的数据迁移至`0.11.2`的系统中。

**Comment by gwny** [comment]
好的，谢谢。
