### ISSUE TITLE
ScyllaDB作为后端存储，分页查询有截断，触发Unexpected fetched page size错误

### ISSUE THREAD

**Issue by philipy1219** [hugegraph/hugegraph#1340]
### Expected behavior 期望表现
分页查询获得完整结果

### Actual behavior 实际表现
使用hugegraph-tools 1.4.0对以ScyllaDB为后端存储的数据进行backup操作，触发"Unexpected fetched page size"错误。

查看源码得知该错误位置
https://github.com/hugegraph/hugegraph/blob/ed610a0b889cc9a0539c5a43ea3be04ce3e6e940/hugegraph-cassandra/src/main/java/com/baidu/hugegraph/backend/store/cassandra/CassandraEntryIterator.java#L43-L59

猜测是由于ScyllaDB的分页大小限制为1MB导致，这是一个硬限制，无法调整。参考以下网页

https://www.scylladb.com/2017/11/17/7-rules-planning-queries-maximum-performance/

https://stackoverflow.com/questions/56697213/when-does-driver-datastax-driver-paging-yields-fewer-pages-than-requested

使用Cassandra为后端存储未发生该错误

参考DataStax 的Java API，我们做出以下修改：

https://github.com/hugegraph/hugegraph/blob/ed610a0b889cc9a0539c5a43ea3be04ce3e6e940/hugegraph-cassandra/src/main/java/com/baidu/hugegraph/backend/store/cassandra/CassandraEntryIterator.java#L67-L94

将上面的fetch函数修改为：

```java
protected final boolean fetch() { 
     assert this.current == null; 
     if (this.next != null) { 
         this.current = this.next; 
         this.next = null; 
     } 
     while (this.remaining > 0 && this.rows.hasNext()) { 
         if (this.query.paging()) { 
                if (!this.results.isFullyFetched())
		    this.results.fetchMoreResults();
             this.remaining--; 
         } 
         Row row = this.rows.next(); 
         BackendEntry merged = this.merger.apply(this.current, row); 
         if (this.current == null) { 
             // The first time to read 
             this.current = merged; 
         } else if (merged == this.current) { 
             // The next entry belongs to the current entry 
             assert merged != null; 
         } else { 
             // New entry 
             assert this.next == null; 
             this.next = merged; 
             break; 
         } 
     } 
     return this.current != null; 
 } 
```
强制执行isFullyFetched检测是否还有未获取的page，并执行fetchMoreResults函数。

经过修改之后，可以备份99.98%的数据，目前仍有千分之二的数据无法导出；且多次执行backup命令进行测试，没有导出的数据id不完全相同。

分页查询会影响到包括scan查询、索引重建等多个任务，麻烦hugegraph团队定位一下问题，感谢。

#### Vertex/Edge summary 数据量
- loaded vertices amount: 亿级
- loaded edges amount: 十亿级

### Specifications of environment 环境信息
- hugegraph version: 0.10.4
- operating system: centos 7.4, 16 CPUs, 128G RAM
- hugegraph backend: scylladb 4.0.4 cluster with 3 nodes, 1 x 1TB SSD disk each node

**Comment by javeme** [comment]
@philipy1219 从代码来看，可能是rows迭代器丢失了数据，`this.results.fetchMoreResults()` 之后，datastax接口内部之前返回的`this.rows`iterator不一定更新，可以详细定位一下。

**Comment by philipy1219** [comment]
@javeme 增加日志测试了一下，this.rows.hasNext()会在当前迭代器耗尽的时候自动fetchMoreResults，对应地，this.rows 也会更新。除了shard查询之外，正常使用Gremlin的查询的时候也会通过CassandraEntryIterator解析返回结果，对应的数据不会丢失。是否有可能从scyllab获得的shard结果存在不全？

**Comment by philipy1219** [comment]
@javeme 我们采用测试数据做了一些实验，[实验报告和测试数据](https://github.com/philipy1219/hugegraph-backup-test)

**Comment by philipy1219** [comment]
@javeme fix 1407 能够使单一分页的数据获取完全，但是我们测试发现，在超过10万条记录的分片中，数据备份会出现丢失现象，[实验报告和测试数据](https://github.com/philipy1219/hugegraph-backup-test/tree/master/v2)

**Comment by javeme** [comment]
@philipy1219 好的，总结下来就是scylla已经获取到本地的那一页数据，如果未完全返回给客户端，则剩余数据会被丢失。

**Comment by philipy1219** [comment]
@javeme 是这样的，我们尝试对reach limit的判断条件进行修改后，就可以获得这部分数据。
