### ISSUE TITLE
Can't access builder which is completed

### ISSUE THREAD

**Issue by litianqi12138** [hugegraph/hugegraph#1342]
### Expected behavior 期望表现
{type something here...}
通过java-client成功插入图属性

### Actual behavior 实际表现
{type something here...}
报异常，Can't access builder which is completed

### Steps to reproduce the problem 复现步骤
//自己写的单例方法获取client
 HugeClient hugeClient = HugeSingleFactory.getInstance();
 SchemaManager schema = hugeClient.schema();
//获取属性名
 String name = graphProperties.getName();
 Builder builder = schema.propertyKey(name);
//实际执行builder.asText(),就算是schema.propertyKey(name).asText()也报错
 Builder builder1 = transDataType(builder,graphProperties.getDatatype());
 if(0 != graphProperties.getCardinality()){
       Builder builder2 = transCardinality(builder1,graphProperties.getCardinality());
       builder2.ifNotExist().create();
 }

HugeSingleFactory.getInstance() 方法如下
public static HugeClient getInstanceRetry() throws Exception{
        Object ans = new RetryTemplete() {
            @Override
            protected Object doBis() throws Exception {
                hugeClient = HugeClient.builder(staticHclientProperties.getUrl(),
                        staticHclientProperties.getGraph()).build();
                return hugeClient;
            }
        }.setRetryTime(5).setSleepTime(10).setSleepTime(10).execute();
        if(null == ans){
            throw new GraphException("00001","hugegraph 连接创建失败，请检查hugegraph server 状态");
        }
        return (HugeClient)ans;
    }

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by litianqi12138** [comment]
还没有执行BuilderProxy的invoke方法finished就变为true了

**Comment by javeme** [comment]
@litianqi12138 请注意一下Builder不可以重用，是否有多次调用build了？

**Comment by Ckuangf** [comment]
![image](https://user-images.githubusercontent.com/31173360/118483241-5bc38280-b748-11eb-807f-9e4d26b2ac83.png)
类似这种的，直接拿builder对象的时候就已经返回true了，如果在创建label的时候需要根据条件判断建立属性，这时候是需要把builder对象单独拿出来按条件设值的呀，这种场景下有比较好的办法去做么
