### ISSUE TITLE
HugeGraph-Hubble界面上显示“社区版：支持图上限 3 个，图磁盘上限 100 GB “这个是HugeGraph社区版的限制还是HugeGraph-Hubble的限制

### ISSUE THREAD

**Issue by magicdoom** [hugegraph/hugegraph#1343]
HugeGraph-Hubble界面上显示“社区版：支持图上限 3 个，图磁盘上限 100 GB “。
请问这个是HugeGraph社区版的限制还是HugeGraph-Hubble的限制？

**Comment by Linary** [comment]
@magicdoom 这是hubble社区版的限制
