### ISSUE TITLE
建议像neo4j那样, 提供一个方便可用的docker镜像, 降低安装部署成本

### ISSUE THREAD

**Issue by pwypwy** [hugegraph/hugegraph#1346]
### Expected behavior 期望表现
就像这样, 快速部署

拉取最新的neo4j镜像
docker pull neo4j
运行Neo4j 容器
docker run -it -d -p 7474:7474 -p 7687:7687 neo4j:latest
打开Neo4j 浏览器管理界面
http://localhost:7474

**Comment by imbajin** [comment]
你好, 目前v0.10的 Server + Studio 的 Docker 镜像是有的, 包括构建的 `Dockerfile` [文件](https://github.com/hugegraph/hugegraph/blob/master/Dockerfile), 你可以自行定制

后续等新的前端 (hubble) 可以直接编译的时候, 会分拆为两个镜像, 使用 `docker-compose` 管理, 到时候顺便补上相关文档.
