### ISSUE TITLE
hugeloader的导入原理是相当于 hugeclient的batch 方式吗,还是single方式?

### ISSUE THREAD

**Issue by fisherinbox** [hugegraph/hugegraph#135]
### Expected behavior 期望表现
{type something here...}

### Actual behavior 实际表现
{type something here...}

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by Linary** [comment]
loader启动时会使用client的batch方式插入顶点或边，当某一批插入出错时，loader会包装出一个单条插入任务，该任务会对那一批数据循环做单条插入。

**Comment by fisherinbox** [comment]
@Linary 为什么用loader插入的时候,最后部分数据总会速度比较慢,一秒钟不到500条

**Comment by Linary** [comment]
最后比较慢可能有两个原因：
1、没有批次插入出错，全部都走的是batch的方式，这样应该是服务端“太忙”了，具体原因需要进一步分析；
2、有批次出错，那这些出错的记录会以单条的方式插入，而且目前release的版本中执行单条插入的仅有一个线程（[在这个提交中有改进](https://github.com/hugegraph/hugegraph-loader/pull/12)），这种情况下慢应该是正常的。
