### ISSUE TITLE
根据条件查询批量边报错

### ISSUE THREAD

**Issue by zhudouxiaolee** [hugegraph/hugegraph#1353]
### Expected behavior 期望表现
期望批量删除边，如下代码：
`
count = 0
def all = hugegraph.traversal().E().has("status","0").limit(10000)
while(all.hasNext()) {
    while(all.hasNext()) {
      all.next().remove()
      if (++count >= 500) {
        g.tx().commit()
        count = 0
      }
    }
    g.tx().commit()
    all = hugegraph.traversal().E().has("status", "0").limit(10000)
}
!all.hasNext()
`

### Actual behavior 实际表现

def all = hugegraph.traversal().E().has("status","0").limit(10000)
批量查询边语句直接报错；
报错信息：Gremlin 执行失败，详细信息: Invalid batch size value: -9749
![image](https://user-images.githubusercontent.com/23448947/106845444-e3c7d400-66e5-11eb-8151-008d5f9f9f5d.png)

### Steps to reproduce the problem 复现步骤
1. 在hubble平台查询
def all = hugegraph.traversal().E().has("status","0").limit(10000)
直接报错

#### Vertex/Edge summary 数据量
- loaded vertices amount: 3.5亿+
- loaded edges amount: 5.1亿+

#### Vertex/Edge example 数据示例
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: v0.11.2
- operating system: centos 6.3, 48 CPUs
- hugegraph backend: rocksdb

**Comment by javeme** [comment]
这是一个历史Bug，新的版本中已经修复：https://github.com/hugegraph/hugegraph/pull/1316/files#diff-e3202debf82179fda84d37c2ad34e790e07caa63f98a8dee2b0a9c60b90eef7fR1676
