### ISSUE TITLE
使用Hbase作为后端引擎的时候，初始化数据时，报连接补上zookeeper。

### ISSUE THREAD

**Issue by qq807274539** [hugegraph/hugegraph#1354]
Huge版本为0.10.4,
hbase为2.0.3,
hadoop为2.7.1，
zookeeper为3.4.6.
其中Hadoop和hbase都正常运行，可以连接，zookeeper也是。
huge日志如下：
![image](https://user-images.githubusercontent.com/37201361/106981540-20a2d200-679d-11eb-9788-17f5ec446f88.png)
huge的huge.properties的配置如下：
![image](https://user-images.githubusercontent.com/37201361/106981624-4af48f80-679d-11eb-9e63-8b8c4d40b867.png)

zookeeper日志如下：
zookeeper配置如下：
![image](https://user-images.githubusercontent.com/37201361/106981818-b50d3480-679d-11eb-9647-9a387313a566.png)
@Linary @javeme 麻烦帮忙看看了，十分感谢。

**Comment by javeme** [comment]
@qq807274539 看init-store的日志，是连接上了，并且成功了的（之前已经初始化好了）。

**Comment by qq807274539** [comment]
但是一启动（bin/start-hugegraph.sh），huge日志就报连接超时了。请问这是什么情况呀

**Comment by qq807274539** [comment]
> @qq807274539 看init-store的日志，是连接上了，并且成功了的（之前已经初始化好了）。

但是一启动（bin/start-hugegraph.sh），huge日志就报连接超时了。请问这是什么情况呀？（the operation timed out when attempting to connect to .....）

**Comment by qq807274539** [comment]
@javeme 可以帮忙看看吗？十分感谢，现在server能启动，但是一直报连接超时....

**Comment by javeme** [comment]
@qq807274539 从现有的信息看不出来，可以贴一下连接超时了的错误日志。
