### ISSUE TITLE
是否考虑在hubble上面增加图实例的metrics监控

### ISSUE THREAD

**Issue by xiaoleizi2016** [hugegraph/hugegraph#1356]
### Expected behavior 期望表现
1、在hubble上面增加图实例的metrics监控，方便排查问题、性能评估等。
2、增加索引建议和是否走了搜索的explain语法

### Actual behavior 实际表现
1、目前hubble上面没有对应的metrics监控。
2、目前没有索引建议和explain语法

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by JackyYangPassion** [comment]
目前这块metrics 展示在grafana了吗，看了下文档没发现如何采集 到 Prometheus

**Comment by xiaoleizi2016** [comment]
1、hugegraph自己的metric接口，没有实现日志打印的report，其数据的格式也不能使用普罗米修斯的json_exports来转化。
2、可以配置gremlin-server的metric接口，有consoleReporter、csvReporter、jmxReporter、slf4jReporter、gangliaReporter和graphiteReporter，我使用的是slf4jReporter，参考了这篇文章 http://tinkerpop.apache.org/docs/3.2.5-SNAPSHOT/reference/

**Comment by javeme** [comment]
@xiaoleizi2016 规划是会纳入到hubble中的，目前仅可使用接口的方式。

**Comment by JackyYangPassion** [comment]
> 有consoleReporter、csvReporter、jmxReporter、slf4jReporter、gangliaReporter和graphiteReporter，我使用的是slf4jReporter

这里指标可视化是用的什么 Grafna?
