### ISSUE TITLE
Huge-Loader加载hdfs问题

### ISSUE THREAD

**Issue by qq807274539** [hugegraph/hugegraph#1358]
如果我们的hdfs（hadoop）是需要进行认证，那么我们的loader在读取数据的时候就会出现认证问题，那么这个时候要如何解决？是通过修改源码还是？目前使用的hadoop是华为fushionInsign的，连接时有认证的步骤。 感谢百忙之中能提供答案！@Linary @javeme

**Comment by Linary** [comment]
如果是Kerberos认证的话直接在映射文件中添加配置即可，如果不是就得自行修改源码了。可以参考这个提交：https://github.com/hugegraph/hugegraph-loader/pull/176

**Comment by qq807274539** [comment]
> 如果是Kerberos认证的话直接在映射文件中添加配置即可，如果不是就得自行修改源码了。可以参考这个提交：[hugegraph/hugegraph-loader#176](https://github.com/hugegraph/hugegraph-loader/pull/176)

映射文件大概是要如何配置呢，将kerberos_enable设置为true，还有将core_site_path、hdfs_site_path的路径配置上，是不是这样子就可以了。但貌似还缺少用户认证和krb5配置文件这块吧？麻烦帮忙解答一下，谢谢！ @Linary

**Comment by Linary** [comment]
krb5配置文件也需要配上的，参考 KerberosConfig 这个类，配上 krb5_conf、principal、keytab。这些都按照你自己环境的相关信息给出，loader只是作为一个客户端传递一下。

**Comment by shengkai126** [comment]
映射文件添加以下配置，对应信息替换成自己的配置。
"kerberos_config": {
         "krb5_conf":"/xxx/krb5.conf",
         "enable":"true",
         "principal":"hdfs/_HOST@HADOOP.COM",
         "keytab":"/xxx/hdfs.keytab"
        }
