### ISSUE TITLE
开启StandardAuthenticator后，没有渠道进行用户管理

### ISSUE THREAD

**Issue by k8king** [hugegraph/hugegraph#1366]
版本：0.11.2
存储后端：hbase
开启StandtandAuthenticator安全认证，初始化脚本成功。
当使用HugeGraph-Hubble访问图数据库时，需要填写用户名和密码，到此无法进行下一步。
官方及网络上均没有文档介绍在此模式下如何进行admin账户的密码初始化及管理用户（添加，删除，授权等）的操作。

**Comment by javeme** [comment]
@k8king 根据文档配置权限后（https://hugegraph.github.io/hugegraph-doc/config/config-authentication.html ），初始化init-store时需要设置admin密码（命令行会提示输入admin密码）。服务启动后，后续操作可通过权限API进行操作，请参考Authentication API文档：https://hugegraph.github.io/hugegraph-doc/clients/restful-api/auth.html

**Comment by k8king** [comment]
您好，初始化时并没有提示设置admin密码啊，我初始化hbase后端成功，可以登录到hbase见到创建的表，中间没有要求我输入密码的步骤。

**Comment by javeme** [comment]
@k8king 可能是配置项不对未启用成功权限。能否提供下相关的配置文件？

**Comment by imbajin** [comment]
> 您好，初始化时并没有提示设置admin密码啊，我初始化hbase后端成功，可以登录到hbase见到创建的表，中间没有要求我输入密码的步骤。

首先, 请贴一下具体操作过的步骤, 包括修改过的配置文件:
- 权限认证默认没有开启, 需要启动 server 之前**手动**配置, 并不会自动提示你输入密码等
- 配置权限后, 也仅是保证 graph server 具有相关读写权限限制, 与后端存储(比如 hbase) 是否能查看/curd 没有任何关联

问题长时间未有更新, 暂时关闭, 有后续疑问可再开启
