### ISSUE TITLE
Shard索引与Secondary索引互斥？

### ISSUE THREAD

**Issue by philipy1219** [hugegraph/hugegraph#1370]
### Actual behavior 实际表现
通过文档我们了解到可以通过shard索引支持前缀匹配 + 数字范围联合查询。原有的数据库结构有一个secondary索引和range索引，我们想对这两个key建立shard索引，发现hugegraph需要首先删除secondary索引。如此，则不能单独对secondary索引进行查询。请问是否通过shard索引的key上面不能再单独建立secondary索引或者range索引？如果是这样，建议在文档中予以说明。

**Comment by Linary** [comment]
@philipy1219  如果已经在key1和key2上建立了shard索引，查询时可以传入这样的条件：

1. key1 = xxx
2. key1 = xxx && key2 > n

key1已经是前缀了，所以不需要再单独为key1建立secondary索引。

但是可以为key2单独建立range索引。
