### ISSUE TITLE
indexLabel的状态是INVALID

### ISSUE THREAD

**Issue by hunter7727** [hugegraph/hugegraph#1371]
### Steps to reproduce the problem 复现步骤
     1、图数据库中的一个节点有两个索引分别是 SECONDARY类型的isRoot和RANGE类型的date
     2、现在想把这两个索引合成一个索引 isRootAndDate
     3、在创建新索引isRootAndDate的时候，创建失败，此时isRoot的索引状态也变成了INVALID

### Specifications of environment 环境信息
- hugegraph version: {like v0.11.2}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like scylla, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by javeme** [comment]
@hunter7727 创建失败的日志信息可以提供一下吗？

**Comment by lxb1111** [comment]
@hunter7727  根据你目前反应的情况，没有复现你说的问题，可以在详细描述一下，包括日志，包括数据集，以及创建索引、查询的语句。
