### ISSUE TITLE
使用hbase做后端，为图实例初始化后，创建的表名均是缩写，不能很好的理解表内存储的数据含义

### ISSUE THREAD

**Issue by big1white** [hugegraph/hugegraph#1374]
### Expected behavior 期望表现
{type something here...}

### Actual behavior 实际表现
{type something here...}
hugegraph:el 还好理解，其他的不能见文知意，如s_fi,如何能查阅每个表所代表的意思？
![微信截图_20210303163126](https://user-images.githubusercontent.com/42825958/109776912-12ca5a80-7c3e-11eb-8fd7-ab6710765e20.png)

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by javeme** [comment]
@big1white 可以从这里看到对应关系：https://github.com/hugegraph/hugegraph/blob/ed610a0b889cc9a0539c5a43ea3be04ce3e6e940/hugegraph-core/src/main/java/com/baidu/hugegraph/type/HugeType.java#L32-L65
