### ISSUE TITLE
hubble启动成功后无法显示的问题

### ISSUE THREAD

**Issue by pdong524** [hugegraph/hugegraph#1382]
现有：
1.server启动成功，状态码为200
2.hubble启动显示：starting hugegraphHubble......OK
3.server和hubble版本适配，server为0.10.4，hubble为1.5.0
4.hubble日志一直停留在initializing Spring DispatcherServlet ‘dispatcherservlet ’

问题：
hubble启动后无法通过localhost:8088（ip和端口未做改变）加载进入

**Comment by Linary** [comment]
把配置项里面的host改成0.0.0.0试试

**Comment by pdong524** [comment]
> 把配置项里面的host改成0.0.0.0试试

换了还是不行呀
把server换成0.11.2效果还是一样的
还有其他什么可能的原因吗

**Comment by javeme** [comment]
@Linary @pdong524 是否因为版本号的原因，与下面问题类似？
https://stackoverflow.com/questions/53730899/spring-boot-application-stuck-at-initializing-spring-dispatcherservlet-dispatc

**Comment by Linary** [comment]
@javeme 无法确定，spring版本号从开发至今一直都是2.x的。

@pdong524 我按照上面的链接修改重新打个包传到这儿你试试吧。

**Comment by pdong524** [comment]
> @javeme 无法确定，spring版本号从开发至今一直都是2.x的。
> 
> @pdong524 我按照上面的链接修改重新打个包传到这儿你试试吧。

好的，麻烦您啦

**Comment by Linary** [comment]
@pdong524 这儿传不了太大的包。我把hubble后端的核心jar包传上来了，你替换一下试试。

[hubble-be-1.5.0.jar.zip](https://github.com/hugegraph/hugegraph/files/6148253/hubble-be-1.5.0.jar.zip)

> 记得将这个文件做一下unzip解压

**Comment by pdong524** [comment]
> 记得将这个文件做一下unzip解压
好的  感谢

**Comment by Linary** [comment]
@pdong524 这个包可以用吗？

**Comment by pdong524** [comment]
> @pdong524 这个包可以用吗？

还是不行，出现这个问题可能是我哪的配置有误，我再探索一下，问题解决后我会把解决方法写到这个问题下面。
再次感谢您！

**Comment by pdong524** [comment]
问题解决了：是centos6系统自带的火狐浏览器自带了拦截器，会把静态页面过滤掉，导致hubble启动之后一直加载不出来

**Comment by Linary** [comment]
@pdong524 好的，辛苦了。
