### ISSUE TITLE
too many records(must <= 800000) for the query?

### ISSUE THREAD

**Issue by roamerop** [hugegraph/hugegraph#1388]
Acconding the issues1049  ->  [issue](https://github.com/hugegraph/hugegraph/issues/1049) 
I upgrade hugegraph to version0.11.2, but still turns the errror.

### Expected behavior 期望表现
g.V().hasLabel('Person').or(values('name').is('张三'),values('name').is('李四')).limit(10)

### Actual behavior 实际表现
failed with `too many records(must <= 800000) for the query`

#### Vertex/Edge summary 数据量
- loaded vertices amount: 1million
- loaded edges amount: 50million

### Specifications of environment 环境信息
- hugegraph version: 0.11.2
- operating system: centos 7.2
- hugegraph backend: {hbase2.1.4, cluster with 6 nodes}

**Comment by javeme** [comment]
@roamerop This error is because you have triggered a large amount of filtering data. Please create an index label for "name" and use the following statement to query:
```java
g.V().hasLabel('Person').or(has('name', '张三'),has('name', '李四'))
```
