### ISSUE TITLE
0.11版RocksDB后端如何支持多个Server同时读写呢？

### ISSUE THREAD

**Issue by xxyp** [hugegraph/hugegraph#1393]
### Expected behavior 期望表现
{type something here...}

如题，0.11版RocksDB后端如何支持多个Server同时读写，应该怎么配置raft模式？

### Actual behavior 实际表现
{type something here...}

0.11版本server和RocksDB在同一台服务器，另外一台服务器如何读写这个RocksDB后端，让hugegraph server分布式提供服务

**Comment by javeme** [comment]
@xxyp 启用RaftMode模式后，RocksDB支持多个Server同时读写，每个Server读本地RocksDB。
