### ISSUE TITLE
RocksDB的data_path和wal_path是否支持HDFS？

### ISSUE THREAD

**Issue by liweidong1216** [hugegraph/hugegraph#1394]
RocksDB的data_path和wal_path是否支持HDFS？如果启用集群状态，是否每台服务器都写同一个data_path和wal_path都写入到同一个HDFS路径？

**Comment by liweidong1216** [comment]
版本为最新的0.11.2版本，打算部署生产上使用

**Comment by javeme** [comment]
@liweidong1216 如果使用HDFS文件系统，建议选用HBase后端。RocksDB不建议配data_path为HDFS，另外不允许多个服务共享一个数据目录，如果需要RocksDB高可用，可以采用RocksDB并开启RaftMode。

**Comment by liweidong1216** [comment]
> @liweidong1216 如果使用HDFS文件系统，建议选用HBase后端。RocksDB不建议配data_path为HDFS，另外不允许多个服务共享一个数据目录，如果需要RocksDB高可用，可以采用RocksDB并开启RaftMode。

目前使用的RcoksDB并开启了RaftMode，集群搭建好以后，出现有时候，元数据不能同步，假设现在三个节点，完全正常，复现步骤如下：
1、新建一个属性，这个时候查看别的节点，新建的属性也能够同步。
2、这个时候，关闭任意一个节点(模拟掉线一台服务器)，假设用户不知道，在另外两个正常节点任意一个节点新建一个属性，此时属性新建成功。在另一台剩余的正常节点上查看第二次新建的属性，发现这个时候，没有第二次新建的属性，也就是在掉线一台服务器的情况下，剩余的两台节点，元数据不能正常同步。
3、启动关闭的那台服务器，启动成功以后，发现第二次新建的属性，已经正常同步到了此台服务器上。但是在这之前的另外一台正常的服务器上(步骤2中没有同步元数据的服务器)，始终不会出现第二次新建的属性。
4、现在三个节点都正常启动，后台也没有报日志错误，在任意一台新建属性，另外两台都无法同步到元数据。
5、此时关闭三个节点，会发现有一个节点无法关闭，一直处于在打印【 Waiting for raft group 'default' election cost 57.016s】日志。
6、再次启动节点，现在步骤5中无法关闭的节点，能够关闭了，再次启动该节点。
7、其中有一个节点出现Can't update cache due to EventHub is too busy，该节点目前无法提供服务。目前只能把该节点的data和wal目录删除，重新新建，并重新init-store，再次启动该节点，恢复正常。
8、此时所有节点都正常启动。
9、再次在任意节点新建属性，发现属性都无法同步，另外两个节点都没有新建的属性

**Comment by liweidong1216** [comment]
配置文件如下：
链接:https://pan.baidu.com/s/1E-SbQYCgbYQac6h6hpE6mw 提取码:egdg 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by javeme** [comment]
@lxb1111 尝试下复现看看。

**Comment by 1436516871** [comment]
@liweidong1216 这个问题我们已经修复了，不久会发布一个补丁版。

**Comment by 1436516871** [comment]
@liweidong1216 下载这个包https://github.com/hugegraph/hugegraph/releases/download/v0.11.2-b2/hugegraph-0.11.2-b2.tar.gz可以使用

**Comment by liweidong1216** [comment]
> @liweidong1216 下载这个包可以使用：https://github.com/hugegraph/hugegraph/releases/download/v0.11.2-b2/hugegraph-0.11.2-b2.tar.gz

好的，非常感谢，试用以后，我及时给出反馈

**Comment by liweidong1216** [comment]
这个bug已经修复，感谢！
