### ISSUE TITLE
集群配置中server.role的参数说明

### ISSUE THREAD

**Issue by liweidong1216** [hugegraph/hugegraph#1395]
集群配置中rest-server.properties 中server.role 各角色的说明
master:主节点
worker:工作节点
computer:计算节点

三种角色具体的定义是什么呢？

### Specifications of environment 环境信息
- hugegraph version: {0.11.2}
- operating system: {centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {rocksdb}

**Comment by javeme** [comment]
@liweidong1216 分别用于：
- 处理OLTP查询
- 异步任务（比如Gremlin Job）
- 图计算任务

**Comment by liweidong1216** [comment]
> @liweidong1216 分别用于：
> 
> * 处理OLTP查询
> * 异步任务（比如Gremlin Job）
> * 图计算任务

我一个集群，3个节点，我配置一个master，两个worker，这样实现高可用应该没问题吧，存储后端选择了rocksdb，没有修改缓存策略，使用的是默认配置，目前测试好像是正常的

**Comment by imbajin** [comment]
> > @liweidong1216 分别用于：
> > 
> > * 处理 OLTP 查询
> > * 异步任务（比如 Gremlin Job）
> > * 图计算任务
> 
> 我一个集群，3 个节点，我配置一个 master，两个 worker，这样实现高可用应该没问题吧，存储后端选择了 rocksdb，没有修改缓存策略，使用的是默认配置，目前测试好像是正常的

测试效果如何呢, 可以**反馈**一下具体的**使用场景**或者**性能情况**, 要注意的是这个方案的分配粒度是 `task` 级, 类似一个轻量级负载均衡的作用.
