### ISSUE TITLE
关于图库数据搜索与清理问题

### ISSUE THREAD

**Issue by wisdoms** [hugegraph/hugegraph#1399]
### Expected behavior 期望表现
期望能删除图库中无效的 边，  索引 ， 顶点

### Actual behavior 实际表现
g.V() 查询时(在 hugegraph-studio-0.10.4)可视化界面上，有会会报  undefined  index label with id '2320'   或  undefined edge label with id '83'

### Steps to reproduce the problem 复现步骤
1. {step 1}   打开已经配置好的  hugegraph-studio-0.10.4
2. {step 2}   输入查询语句   g.V()
3. {step 3}   会报  undefined  index label with id '2320'   或  undefined edge label with id '83'

### Status of loaded data 数据状态
后端 数据存储在 rockdb 中

#### Vertex/Edge summary 数据量
小于 1万条

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version:  0.10.4
- operating system:  centos 7.4
- hugegraph backend: rockdb

### Question  2: 

问题描述： 图库中一些人名比如 国外人的中文译名 或少数民族的中文名字，这些名字大都是 3个汉字以上，而且很多是些生辟字组成，在搜索是怎么有时就查找 不到，或查找到后，与输入的关键词不相符， 比如搜索时人名输入一部分，这部分的长短与搜索结果 不相符， 有些真正需要的结果没有搜索到。

诉求： 怎么才能搜索到期望的结果 。

补充：  查了下  hugegraph-0.10.4-Relase 版本中的配置 ，有这么两个配置，这是源码 中的一些解释
search.text_analyzer：  
	Choose a text analyzer for searching thevertex/edge properties, available type are ：
	[word, ansj, hanlp, smartcn, jieba, jcseg, mmseg4j, ikanalyzer]

search.text_analyzer_mode: 
	Specify the mode for the text analyzer, the available mode of analyzer are : 

	word: [MaximumMatching, ReverseMaximumMatching, MinimumMatching, ReverseMinimumMatching, BidirectionalMaximumMatching, BidirectionalMinimumMatching, BidirectionalMaximumMinimumMatching, FullSegmentation, MinimalWordCount,MaxNgramScore, PureEnglish] 

	ansj: [BaseAnalysis, IndexAnalysis, ToAnalysis, NlpAnalysis]
	hanlp: [standard, nlp, index, nShort, shortest, speed
	smartcn: []
	jieba: [SEARCH, INDEX]
	jcseg: [Simple, Complex]
	mmseg4j: [Simple, Complex, MaxWord]
	ikanalyzer: [smart, max_word]

补充诉求：  这些配置都是什么含义， 在选择中文搜索时，如何选择合适的  analyzer_mode 与 analyer.

**Comment by javeme** [comment]
@wisdoms  请问下错误 "undefined index label with id '2320'" 是在做哪些操作后出现的？是否能给出选复现流程？
关于字符串检索问题，请参考： https://github.com/hugegraph/hugegraph/issues/294 、 https://github.com/hugegraph/hugegraph/issues/297 、 https://github.com/hugegraph/hugegraph/issues/449 。关于分词器的选择，可参考 https://github.com/hugegraph/hugegraph/issues/779 ，建议按业务场景实验后根据效果进行选择。

**Comment by wisdoms** [comment]
关于  undefined index label with id 2320 ,我在 [#1274]( https://github.com/hugegraph/hugegraph/issues/1274)中回复了
