### ISSUE TITLE
task_result is null

### ISSUE THREAD

**Issue by yuyang0** [hugegraph/hugegraph#140]
task completes successfully, but the `task_result` is null, my gremlin command is like this `g.V().has(xxx).outE().toList`, I think the result should not be `null`, even in case of empty result, it should return `[]`, I am not sure if it is a bug  in hugegraph.

**Comment by javeme** [comment]
Yes, the result should not be null. Is it possible to provide information about the task(response of task-get api) or steps to reproduce? thank you

**Comment by yuyang0** [comment]
@javeme  thanks for your reply, I can't reproduce the  problem stably, I need some time

**Comment by javeme** [comment]
Thanks for your information, it looks like there is race condition when getting task status, we will find and fix it, thank you!

**Comment by yuyang0** [comment]
0.8并没有修复这个问题 @javeme

**Comment by javeme** [comment]
@yuyang0 请问你是使用的hbase后端吗？如果是的话可能与hbase的时间戳问题有关，请参考：https://issues.apache.org/jira/browse/HBASE-2256 
类似问题 #230

**Comment by yuyang0** [comment]
我就用的rocksdb @javeme

**Comment by javeme** [comment]
@yuyang0 如果是rocksdb的话那可能是hg本身的bug，看看能不能找到一个稳定的复现过程。非常感谢反馈

**Comment by yuyang0** [comment]
@javeme 我如果能稳定的复现，我就自己修复了，弄得真心累，还遇到了过好几个问题，比如升级0.8，数据库server直接卡死，内存占用暴增（128G的服务器，hugegraph用掉了124G，如果服务器有更多空闲内存肯定还会用掉更多），结果这样卡了半个小时，直接挂了，删掉0.7创建的数据似乎又好了，还有其它小问题一堆，这个开源版本确实不是一个成熟可用的数据库

**Comment by javeme** [comment]
@yuyang0 建议在遇到问题的时候给我们反馈错误日志及操作流程，我们希望能帮助你解决这“一堆”问题。

**Comment by yuyang0** [comment]
出问题查日志我还是懂得，关键是日志没什么有用的信息，我说很多小问题真的不是乱说，比如说我折腾接近一个月，至少遇到过三次server莫名其妙的挂掉，日志没什么异常，我甚至都没做什么操作，但是就是挂掉了，你像这种问题我真的没法反馈，当然我这里说的只是这个开源版本，我最开始其实对hugegraph期望挺高的，但是现在看来确实不成熟，不管怎么说，还是希望hugegraph越做越好，至少可以多一个选择 @javeme
