### ISSUE TITLE
源码编译打包错误

### ISSUE THREAD

**Issue by xxyp** [hugegraph/hugegraph#1408]
从git下载HugeGraph master分支执行 mvn package -DskipTests 报错,请问是什么原因呢
jdk 1.8 
Maven 3.39

[INFO] hugegraph-palo ..................................... SUCCESS [  0.638 s]
[INFO] hugegraph-hbase .................................... SUCCESS [  1.312 s]
[INFO] hugegraph-postgresql ............................... SUCCESS [  0.529 s]
[INFO] hugegraph-dist ..................................... FAILURE [ 11.909 s]
[INFO] hugegraph-example .................................. SKIPPED
[INFO] hugegraph-test ..................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 32.154 s
[INFO] Finished at: 2021-03-30T21:11:58+08:00
[INFO] Final Memory: 81M/837M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.3:run (default) on project hugegraph-dist: An Ant BuildException has occured: Execute failed: java.io.IOException: Cannot run program "bash": CreateProcess error=2, 系统找不到指定的文件。 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :hugegraph-dist

**Comment by javeme** [comment]
@xxyp 缺少bash命令，是否非非linux环境中执行的？
可以搜索下问题："Cannot run program "bash"，网上有不少解决方法的。

**Comment by imbajin** [comment]
暂时不支持 windows 上**直接**打包, 相关打包脚本中的 `path` 解析会报错, 当然欢迎你尝试调整后提交 PR

如果只有 linux 环境, 推荐你使用win10内置的 [WSL2(Windows Subsystem for Linux)](https://docs.microsoft.com/zh-cn/windows/wsl/install-win10) 转换到 Linux 环境使用
