### ISSUE TITLE
Jmeter压测kout算法2度查询，报空指针异常

### ISSUE THREAD

**Issue by 1436516871** [hugegraph/hugegraph#1410]
### Expected behavior 期望表现
{type something here...}

### Actual behavior 实际表现
![image](https://user-images.githubusercontent.com/55084061/113108004-1c43e400-9237-11eb-84d6-2990be7bdc0c.png)

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {2亿}
- loaded edges amount: {34681188}
- loaded time: {}

#### Vertex/Edge example 数据示例
edge：
![image](https://user-images.githubusercontent.com/55084061/113107235-4517a980-9236-11eb-8904-51c256527453.png)
vertex：
![image](https://user-images.githubusercontent.com/55084061/113107324-5e205a80-9236-11eb-8de2-7363e55597b0.png)

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
"graph.schema().propertyKey('city').asText().ifNotExist().create();"
"graph.schema().propertyKey('num').asInt().ifNotExist().create();"
"graph.schema().vertexLabel('node').properties('num','city').useCustomizeNumberId().ifNotExist().create()",
"graph.schema().edgeLabel('link').sourceLabel('node').targetLabel('node').ifNotExist().create()"

### Specifications of environment 环境信息
- hugegraph version: {0.11.2}
- operating system: {}
- hugegraph backend: {rocksdb}

**Comment by Linary** [comment]
grizzly bug: https://github.com/eclipse-ee4j/grizzly/issues/1880
