### ISSUE TITLE
GREMLIN语句g.V(id)循环查询2000w顶点，内存会泄露

### ISSUE THREAD

**Issue by 1436516871** [hugegraph/hugegraph#1411]
### Expected behavior 期望表现
{type something here...}

### Actual behavior 实际表现
{type something here...}
![image](https://user-images.githubusercontent.com/55084061/113109068-39c57d80-9238-11eb-90dc-a56d687a2c5e.png)

### Steps to reproduce the problem 复现步骤
g.V(id),id为2000w个顶点的ID，不断循环查询

#### Vertex/Edge summary 数据量
- loaded vertices amount: {120 million}

#### Vertex/Edge example 数据示例
wdc数据集

### Specifications of environment 环境信息
- hugegraph version: {社区版}
- hugegraph backend: {rocksdb}

**Comment by Linary** [comment]
https://github.com/eclipse-ee4j/jersey/issues/3568

**Comment by Linary** [comment]
不过我们使用的是Apache Connector，并不是Netty Connector
