### ISSUE TITLE
SpringBoot集成hugegraph-client后，新增property报错

### ISSUE THREAD

**Issue by murmur123456** [hugegraph/hugegraph#1413]
### Expected behavior 期望表现
schema.propertyKey("name").asText().valueSet().ifNotExist().create();
期望表现为新增name属性

### Actual behavior 实际表现
报错：The name of property key can^t be null

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

### Specifications of environment 环境信息
- hugegraph version: {like v0.11.2}
- operating system: {like centos 7.6,
- hugegraph backend: {cassandra 3.11}

**Comment by javeme** [comment]
@murmur123456 可参考下：https://github.com/hugegraph/hugegraph/issues/5

**Comment by murmur123456** [comment]
确实是fastjson冲突导致的，换成gson后可正常使用
