### ISSUE TITLE
HugeGraph-Hubble平台导入中文数据读取变成乱码������

### ISSUE THREAD

**Issue by ibrillantx** [hugegraph/hugegraph#1415]
在导入数据前已把CSV文档的编码格式改成UTF-8，但是依旧显示乱码，请教如何解决..

**Comment by Linary** [comment]
导入的时候有选择编码方式吗？“显示乱码”是指在哪个地方显示的。

**Comment by ibrillantx** [comment]
> 导入的时候有选择编码方式吗？“显示乱码”是指在哪个地方显示的。

上传CSV文件后，文件设置选择UTF-8，点击保存；类型设置-创建顶点映射-选择ID列，此时出现乱码，就是CSV每一列开头的中文词语都变成了����这样....

**Comment by ibrillantx** [comment]
> 导入的时候有选择编码方式吗？“显示乱码”是指在哪个地方显示的。

**Comment by Linary** [comment]
你在上传前把文件设置为UTF-8的编码方式（确保这么设置后预览文件没有乱码），然后**重新上传一次文件**，再走你后续的流程试试。

**Comment by ibrillantx** [comment]
> 你在上传前把文件设置为UTF-8的编码方式（确保这么设置后预览文件没有乱码），然后**重新上传一次文件**，再走你后续的流程试试。

还是不可以呀,我确认本地已经改成了UTF8格式，还没有解决..
我的CSV文件最初是UTF-8 BOM，后来用notepad改成了UTF8格式，然后进行上传的

**Comment by javeme** [comment]
@ibrillantx 请先确保文件实际是UTF8，比如使用vim查看时无乱码，乱码一般是文件转码的时候容易出问题。另外可以新建一个UTF8编码的文件尝试导入流程，验证流程是否有问题。
