### ISSUE TITLE
java client的事务后续版本会支持吗？

### ISSUE THREAD

**Issue by zsy-042** [hugegraph/hugegraph#1417]
### Expected behavior 期望表现
使用java client在多个操作时可以支持事务，例如：创建两个顶点，两个顶点之间创建一条边。如果中间出现失败，整个流程不能完成回滚，会出现业务无效数据。

### Actual behavior 实际表现
目前java client不支持事务，无法保证多个操作同时成功或失败

**Comment by imbajin** [comment]
Client 端使用简单事务的画, 可以参考这个 issue -->  #1008 

然后你也可以从 Client 的测试源码里找到详细的例子

后续有相关问题也可以先在 `issue` 区搜一下, 大部分都会有参考,

**Comment by zsy-042** [comment]
> Client 端使用简单事务的画, 可以参考这个 issue --> #1008
> 
> 然后你也可以从 Client 的测试源码里找到详细的例子
> 
> 后续有相关问题也可以先在 `issue` 区搜一下, 大部分都会有参考,

client获取的GraphManager并没有tx()方法，关于事务的相关issue都已经看过了，client示例中也并没有开启事务的相关代码。

**Comment by imbajin** [comment]
嗯呢, 更新了一下, 是 Server 的[example源码](https://github.com/hugegraph/hugegraph/tree/master/hugegraph-example/src/main/java/com/baidu/hugegraph/example)里有事务使用参考, Client 端目前没有直接提供单独接口

不过你可以直接使用[ Gremlin 事务使用](https://tinkerpop.apache.org/docs/3.4.10/reference/#transactionshttps://github.com/hugegraph/hugegraph/tree/master/hugegraph-example/src/main/java/com/baidu/hugegraph/example) 开启/关闭, 就是在 gremlin 语句中嵌套, 这样也是同样的效果.

**Comment by zsy-042** [comment]
> 嗯呢, 更新了一下, 是 Server 的[example源码](https://github.com/hugegraph/hugegraph/tree/master/hugegraph-example/src/main/java/com/baidu/hugegraph/example)里有事务使用参考, Client 端目前没有直接提供单独接口
> 
> 不过你可以直接使用[ Gremlin 事务使用](https://tinkerpop.apache.org/docs/3.4.10/reference/#transactionshttps://github.com/hugegraph/hugegraph/tree/master/hugegraph-example/src/main/java/com/baidu/hugegraph/example) 开启/关闭, 就是在 gremlin 语句中嵌套, 这样也是同样的效果.

感谢您的回复，后续client端有支持事务的计划吗？

**Comment by imbajin** [comment]
> > 嗯呢, 更新了一下, 是 Server 的[example源码](https://github.com/hugegraph/hugegraph/tree/master/hugegraph-example/src/main/java/com/baidu/hugegraph/example)里有事务使用参考, Client 端目前没有直接提供单独接口
> > 不过你可以直接使用[ Gremlin 事务使用](https://tinkerpop.apache.org/docs/3.4.10/reference/#transactionshttps://github.com/hugegraph/hugegraph/tree/master/hugegraph-example/src/main/java/com/baidu/hugegraph/example) 开启/关闭, 就是在 gremlin 语句中嵌套, 这样也是同样的效果.
> 
> 感谢您的回复，后续client端有支持事务的计划吗？

目前用原生 `gremlin` 的方式客户端/前端/restful-api 里都是可以直接开关事务的, 当然这种用法易用性可读性要弱一些
后续 client 是否提供一个原生接口, 要看社区用户的需求程度呐
