### ISSUE TITLE
[性能] 超级顶点的出边如何查询 & 同时大量的随机点/边查如何提高性能?

### ISSUE THREAD

**Issue by DoubleBabylol** [hugegraph/hugegraph#1418]
Expected behavior 期望表现
希望能够获得批量点数据的出度和入度

Actual behavior 实际表现
1. 边太多慢
2. 当前主要是单条数据，如何获取十万顶点的出入度？

**Comment by imbajin** [comment]
1. 超级顶点(某个点的出边很多的情况), 一般要根据具体业务需求来做优化, 方案包括不限于:
    - 使用 sortkey (局限性是需要提前设计好, 有存储放大, 可能需要业务上层做处理)
    - 使用 limit / [分页](https://hugegraph.github.io/hugegraph-doc/clients/restful-api/vertex.html) 进行查询
2. 压测一下, 看看目前的并发数/时延增长趋势, 瓶颈值是多少, 然后观察 server+后端 此时的负载情况, 看看瓶颈在哪

**Comment by DoubleBabylol** [comment]
好的，谢谢大佬，😁

**Comment by DoubleBabylol** [comment]
不愧是巨佬！
