### ISSUE TITLE
使用GREMLIN 查询时同个顶点信息出现结果不一致

### ISSUE THREAD

**Issue by xiebin95** [hugegraph/hugegraph#1424]
### Expected behavior 期望表现
{type something here...}
出现一致的答案

### Actual behavior 实际表现
{type something here...}
通过边的进出关系查询出的顶点ID，显示顶点未定义，单独查询该顶点ID，又能显示出部分字段的信息，过段时间再去查就又出现全部字段的信息。

望相关人员能够解答相关问题
具体查询语句如下：
a,c为顶点 b为边
g.V(a).outE(b).inV().hasId(c)
该结果出现未定义的顶点ID为c
g.V(c)
该结果出现有定义的顶点ID为c

**Comment by lxb1111** [comment]
@xiebin95  g.V(a).outE(b).inV().hasId(c) 语句中 outE()中应该传入b的label 即：b边的类型

**Comment by xiebin95** [comment]
> @xiebin95 g.V(a).outE(b).inV().hasId(c) 语句中 outE()中应该传入b的label 即：b边的类型

谢谢解答，我们找到原因了，是因为生成边的时候 没有规范操作 导致出现了这个问题
