### ISSUE TITLE
边索引查询无效

### ISSUE THREAD

**Issue by veer150** [hugegraph/hugegraph#1427]
### Expected behavior 期望表现
使用边上带索引字段比不带索引字段查询时，查询速度更快

### Actual behavior 实际表现
使用边上带索引字段比不带索引字段查询耗时差不多

### Steps to reproduce the problem 复现步骤

BY_DT：String类型，不带索引，BY_DT_L:Long类型，范围索引，使用下面两个语句查询时，耗时都在18s左右
 --无索引
g.V().hasLabel('T_USER').has('USER_ID','6a15f7b').outE('E_BY').has('BY_DT',gte('20160118183746')).inV().inE().outV().has('USER_ID','1fc6f0e').path();
--有索引
g.V().hasLabel('T_USER').has('USER_ID','6a15f7b').outE('E_BY').has('BY_DT_L',gte(20160118183746)).inV().inE().outV().has('USER_ID','1fc6f0e').path();

#### Vertex/Edge summary 数据量
- loaded vertices amount: 6 hundred  million
- loaded edges amount: 12 hundred  million

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{
    "edgelabels": [
        {
            "id": 26,
            "name": "E_BY",
            "source_label": "T_USER",
            "target_label": "T_BY",
            "frequency": "SINGLE",
            "sort_keys": [],
            "nullable_keys": [],
            "index_labels": [
                "INDEX_BY_DT"
            ],
            "properties": [
                "BY_ID",
                "BY_DT",
                "BY_DT_L"
            ],
            "status": "CREATED",
            "ttl": 0,
            "enable_label_index": true,
            "user_data": {
                "~create_time": "2021-04-15 17:37:46.954",
                "~style": "{\"color\":\"#fd6ace\",\"with_arrow\":true,\"line_type\":\"SOLID\",\"thickness\":\"NORMAL\",\"display_fields\":[\"~id\"],\"join_symbols\":[\"-\"]}"
            }
        }
    ]
}

{
    "indexlabels": [
        {
            "id": 1,
            "name": "INDEX_BY_DT",
            "base_type": "EDGE_LABEL",
            "base_value": "E_BY",
            "index_type": "RANGE",
            "fields": [
                "BY_DT_L"
            ],
            "status": "CREATED",
            "user_data": {
                "~create_time": "2021-04-15 17:39:25.214"
            }
        }
    ]
}

### Specifications of environment 环境信息
- hugegraph version: 0.11.2
- operating system:  centos 7.4, 64 CPUs
- hugegraph backend: cassandra 3.11.8, cluster with 3 nodes

**Comment by imbajin** [comment]
有几个问题需要确认一下, 核心是第二个查询是否**命中了**索引:
- 索引是什么时候创建的? 先有了数据之后, 再创建的索引么? 还是提前就设置好了
- 如果是先有数据再创建了索引, 需要确认索引异步的重建完成, 可以查看一下异步任务情况
- 比较简单的检测办法就是, 你可以试着一个没导数据之前, 先创建索引, 两个 server 对比来看看

然后为了减少额外的影响, 可以先尽可能使用稍简短一些的 gremlin 语句确认索引命中
