### ISSUE TITLE
mariadb替换mysql出错

### ISSUE THREAD

**Issue by xfs1010** [hugegraph/hugegraph#1428]
### Expected behavior 期望表现
HugeGraph正常运行

### Actual behavior 实际表现
No suitable driver found for /jdbc:mariadb://xxxx:xxx/metadata/metadata?useSS

地址前面多了个 "/"，看起来像是`MySQLSeesion`->`buildUri`的URIBuilder让url地址带了"/"，然后mariadb的Driver connect方法识别不了直接报错了。

### Specifications of environment 环境信息
- hugegraph version: 0.11.2
- operating system: windows

**Comment by imbajin** [comment]
可以把相关的**修改**配置, 以及报错的详细异常信息贴一下~
简单看, 似乎只是补充一个`/`, 你也可以提供一下复现方式

```java
        String url = this.config.get(MysqlOptions.JDBC_URL); // deafult: jdbc:mysql://127.0.0.1:3306
        if (!url.endsWith("/")) {
            url = String.format("%s/", url);
        }
```

**Comment by imbajin** [comment]
最新版代码已经默认添加相关日志，暂时关闭 issue, 期待你的新反馈再开启
