### ISSUE TITLE
请求超时

### ISSUE THREAD

**Issue by djyrl** [hugegraph/hugegraph#1429]
### Expected behavior 期望表现
{type something here...}
长时间等待

### Actual behavior 实际表现
{type something here...}
30秒超时

### Specifications of environment 环境信息
- hugegraph version: {like v0.11.2}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like mysql 5.7}

已经设置
rest-server.properties restserver.request_timeout=900
gremlin-server.yaml scriptEvaluationTimeout=900

client:
configTimeout(900)
mysql 也设置了超时时间，jdbc连接字符串没有设置超时时间

**Comment by imbajin** [comment]
多谢提供了具体的修改地方, 不过仔细看下[文档](https://hugegraph.github.io/hugegraph-doc/config/config-option.html), `gremlin-serever.yaml` 里的超时单位是毫秒 ms

你设置900等于1s 就 `0.9s` gremlin 查询就超时了吧.  除此之外, 文档里全文搜索一下 `timeout` 相关 rest-server 中的超时配置可以也设置一下, 后续这里是应该优化一下

避免重复, 和过多的超时参数, 让用户比较难理解 , 或者提供一个简化的 `timeout_all` 参数控制所有超时.

**Comment by djyrl** [comment]
不意思，我设置的gremlin-serever.yaml=900000，我的失误，上面发文表达的是900秒的意思

**Comment by imbajin** [comment]
那有尝试过其他后端存储么. 比如用默认的 rocskdb, 看看是否还超时
另外你可以把 server 端其他的超时参数也设置一下, 至于 mysql 本身的超时, 你也可以看看有没有相关参数.

**Comment by djyrl** [comment]
我也使用了rocskdb，我使用postman模拟访问，postman的超时时间也设置成了不限制。我直接访问 rest-api，并不会30秒超时，调用client访问结果30秒超时， 
graph.TimeOut=90
hugeclient = new HugeClient(new HugeClientBuilder(url, databaseName)
                .configTimeout(graph.timeout)
                .configIdleTime(graph.idleTime));

**Comment by imbajin** [comment]
> 我也使用了rocskdb，我使用postman模拟访问，postman的超时时间也设置成了不限制。我直接访问 rest-api，并不会30秒超时，调用client访问结果30秒超时，
> graph.TimeOut=90
> hugeclient = new HugeClient(new HugeClientBuilder(url, databaseName)
> .configTimeout(graph.timeout)
> .configIdleTime(graph.idleTime));

如果基于最新版测试无误, 那大概率说明 server 端的超时参数应已经生效了, 客户端没生效, 稍后我尝试复现一下
你如果尝试不设置 client 超时时间是多久超时呢, 简单看了下默认似乎是20s才对, 为何是30s 超时呢

**Comment by javeme** [comment]
请求超时参数涉及到3个:

scriptEvaluationTimeout：gremlin-server的超时。（gremlin-server.yaml）
restserver.request_timeout：rest-server的超时。（rest-server.properties）
gremlinserver.timeout：rest-server连接gremlin-server的超时。（rest-server.properties）
参考：
https://hugegraph.github.io/hugegraph-doc/config/config-option.html
