### ISSUE TITLE
提供golang客户端

### ISSUE THREAD

**Issue by sessionboy** [hugegraph/hugegraph#1444]
如题

**Comment by imbajin** [comment]
目前这方面需求还不多,  不过因为和 server 通信走的都是 HTTP 方式
想简单测试读写性能, 可以简单封装一下核心的 HTTP 接口即可

_PS: 有兴趣也欢迎提交 client 代码呐~_

**Comment by imbajin** [comment]
> 不是需求不多，而是你们产品和生态没起来

需求有轻重缓急, 生态也需要时间和人力去构建,  `c++ / python / js / rust` 也都有对应的需求, 也需要看看用户占比和排期情况

另外 [gremlin 官方](https://github.com/apache/tinkerpop)有对应的 `py/js`库, 熟悉相关语言的话也可以直接使用调用

> 为啥不走rpc呢 ，走rpc很多语言都可以支持了，性能也比http高一个层级

用 RPC 很多语言就能(容易)支持么, 恰好相反吧? 用 HTTP 的优势就是方便**通用对接**, 用户可以不依赖任何后端/client访问server, 劣势是缺乏定制性, 性能会有一些影响, 这也是权衡利弊来看的
性能姑且不说影响多少, 抛开耗时占比去谈意义不大. 就像新项目也有不少序列化用"看起来"很老的 `thrift` 而没有用 `protobuf` , 也是类似的考量.

最后感谢建议, 社区生态是大家一起建立的, 欢迎添砖加瓦
