### ISSUE TITLE
使用gremlin-schedule返回结果为{“simple”:“false”}

### ISSUE THREAD

**Issue by zhaokanghuiasd** [hugegraph/hugegraph#1445]
### Expected behavior 期望表现
输出正常的结果，能把路径信息输出出来

### Actual behavior 实际表现
没能输出路径信息，应该输出路径信息的地方输出{“simple”:“false”}。

### 我的输入是：
./bin/hugegraph --url http://127.0.0.1:8080 --graph hugegraph gremlin-schedule --script "g.V().has('id','00001d3a4cd98317b53807e24372a83a').both().aggregate('x').not(has('id','00001d3a4cd98317b53807e24372a83a').hasLabel('phoneNumber')).both('contact').where(without('x')).both('contact').has('id','00001d3a4cd98317b53807e24372a83a').hasLabel('phoneNumber').path()"
最后希望输出所有的path。之前使用gremlin-execute，但数据量比较大超过80w报错，因此使用的gremlin-schedule。

### 输出：
Task info: {task_name=g.V().has('id','00001d3a4cd98317b53807e24372a83a').hasLabel('phoneNumber').in('open').out('open').aggregate('x').not(has('id','00001d3a4cd98317b53807e24372a83a').hasLabel('phoneNumber')).both('contact').where(without('x')).both('contact').has('id','00001d3, task_progress=0, task_create=1620803459093, task_status=success, task_update=1620803533878, task_result=[{"simple":false,"empty":false},{"simple":false,"empty":false},{"simple":false,"empty":false},{"simple":false,"empty":false},{"simple":false,"empty":false},{"simple":false,"empty":false},{"simple":false,"empty":false},{"simple":false,"empty":false},{"simple":false,"empty":false},{"simple":false,"empty":false},{"simple":false,"empty":false},{"simple":false,"empty":false},{"simple":false,"empty":false},{"simple":false,"empty":false},{"simple":false,"empty":false}], task_retries=0, id=20, task_type=gremlin, task_callable=com.baidu.hugegraph.job.GremlinJob, task_input={"gremlin":"g.V().has('id','00001d3a4cd98317b53807e24372a83a').hasLabel('phoneNumber').in('open').out('open').aggregate('x').not(has('id','00001d3a4cd98317b53807e24372a83a').hasLabel('phoneNumber')).both('contact').where(without('x')).both('contact').has('id','00001d3a4cd98317b53807e24372a83a').hasLabel('phoneNumber').path()","aliases":{"hugegraph":"graph"},"bindings":{},"language":"gremlin-groovy"}, task_server=server-1}

各位大佬帮忙看一下这个问题，感谢！

**Comment by imbajin** [comment]
麻烦多提供一些上下文信息.... (或者截图😢 )

**Comment by zhaokanghuiasd** [comment]
> 麻烦多提供一些上下文信息.... (或者截图😢 )

您好，刚补充了一下问题，您看是否还需要补充其它信息

**Comment by imbajin** [comment]
不好意思有段时间没注意, 这个问题在最新发布的 release 包 (11b) 已经修复, 可以换一下新包试试
