### ISSUE TITLE
边的数据结构一定要和节点类别绑定吗？

### ISSUE THREAD

**Issue by wqn1** [hugegraph/hugegraph#1446]
如果类型A的节点和类型B的节点之间的关系是belong，而类型B和类型C之间的关系类型也是belong，这样是不是就无法创建？这种情况下要怎样修改，求教

**Comment by imbajin** [comment]
同名不能创建, 最简单的方式就是换个名字即可, 或者采用一套你自己定义的规范, 例如:
- `A->B` 的边 Label 名取为 `a_belongs_a`
- `B->C` 的边 Label 名取为 `b_belongs_c`

这样一般也不影响具体使用, 还能知道同类的边的不同归属点
