### ISSUE TITLE
聊聊jraft 在hugegraph中的应用

### ISSUE THREAD

**Issue by JackyYangPassion** [hugegraph/hugegraph#1449]
如题；
目标：
1. 理顺 hugeserver raft 架构实现 
2. 开源线上版本如何应用

**Comment by imbajin** [comment]
是希望社区提供一些源码分析设计之类的文档么? 
这个估计得等相对稳定得时候再写, 不过也有社区同学自己写过得, 直接搜一下就有参考. 

也欢迎贡献一下相关的分析和心得呀, 之后在 `README` 里可以补充一个社区用户实践心得, 汇总这些文档

**Comment by JackyYangPassion** [comment]
是的：
1. 首先一些架构设计方面的文档搞起来，这样应用过程中解决问题能够快速些
2. 这部分也在看，有沉淀后会同步出来

**Comment by Linary** [comment]
hugegraph 目前的 raft 架构实现简单说的话，主要是增加一个 RaftBackendStore 的代理，将所有由上层发往存储层的请求都先经过此代理层的处理：

- 写请求：序列化后写入到 raft 日志项中，当过半节点都追加日志成功，然后再通过状态机应用日志，状态机里包含了真正的 RocksDB 写数据的逻辑；
- 读请求：如果接收请求的是 leader 节点或用户未开启一致性读，则直接读当前的数据并返回即可；如果接收请求的是 follower 节点并且用户开启了一致性读，则会通过 jraft 的 read index 技术，确保 follower 节点的日志应用跟上了 leader 节点后，再进行读取并返回；

目前只实现了多副本，还不支持数据分片。

我们自己修改过 jraft 的源码，所以社区中的代码你们直接编译是会有问题的，建议还是直接使用 release 版。
