### ISSUE TITLE
请问下目前建立的indexLabel，在后面使用的过程中不能进行字段的添加或者修改么，只能通过删除之后然后重新建立的方式进行索引的修改么

### ISSUE THREAD

**Issue by Ckuangf** [hugegraph/hugegraph#1450]
### Expected behavior 期望表现
{type something here...}

### Actual behavior 实际表现
{type something here...}

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by imbajin** [comment]
嗯呢, 本质原因是索引建立的原理: 它实际就是用额外的一份冗余数据, 通过空间换取了时间的加速

所以这种元信息修改, 就代表之前所有的索引数据都会失效, 所以这个操作很重, 一般都是先 remove 再新增

其他元信息的直接修改不允许也是类似的原因, 建议测试环境里先确定好核心的 schema, 避免生产环境会频繁出现这种变动

**Comment by Ckuangf** [comment]
> 嗯呢, 本质原因是索引建立的原理: 它实际就是用额外的一份冗余数据, 通过空间换取了时间的加速
> 
> 所以这种元信息修改, 就代表之前所有的索引数据都会失效, 所以这个操作很重, 一般都是先 remove 再新增
> 
> 其他元信息的直接修改不允许也是类似的原因, 建议测试环境里先确定好核心的 schema, 避免生产环境会频繁出现这种变动

好嘞 谢大佬
