### ISSUE TITLE
Hbase 后端根据 shard 遍历点边没返回预期的数据

### ISSUE THREAD

**Issue by lenqinxin** [hugegraph/hugegraph#1452]
### Expected behavior 期望表现
希望能获取所有节点和边的hdfs文件类型供spark GraphX使用
后端habase，已经手工进行分区 

### Actual behavior 实际表现
无法返回任何数据

### Steps to reproduce the problem 复现步骤
1. http://loacalhost:8080/graphs/hugegraph/traversers/vertices/shards?split_size=1048576 
{"shards": [{"start":"","end":"Dw8PDw8PDw8PDw8PDw8PDw==","length":0},{"start":"Dw8PDw8PDw8PDw8PDw8PDw==","end":"Hh4eHh4eHh4eHh4eHh4eHg==","length":0},{"start":"Hh4eHh4eHh4eHh4eHh4eHg==","end":"LS0tLS0tLS0tLS0tLS0tLQ==","length":0},{"start":"LS0tLS0tLS0tLS0tLS0tLQ==","end":"PDw8PDw8PDw8PDw8PDw8PA==","length":0},{"start":"PDw8PDw8PDw8PDw8PDw8PA==","end":"S0tLS0tLS0tLS0tLS0tLSw==","length":0},{"start":"S0tLS0tLS0tLS0tLS0tLSw==","end":"WlpaWlpaWlpaWlpaWlpaWg==","length":0},{"start":"WlpaWlpaWlpaWlpaWlpaWg==","end":"aWlpaWlpaWlpaWlpaWlpaQ==","length":0},{"start":"aWlpaWlpaWlpaWlpaWlpaQ==","end":"eHh4eHh4eHh4eHh4eHh4eA==","length":0},{"start":"eHh4eHh4eHh4eHh4eHh4eA==","end":"h4eHh4eHh4eHh4eHh4eHhw==","length":0},{"start":"h4eHh4eHh4eHh4eHh4eHhw==","end":"lpaWlpaWlpaWlpaWlpaWlg==","length":0},{"start":"lpaWlpaWlpaWlpaWlpaWlg==","end":"paWlpaWlpaWlpaWlpaWlpQ==","length":0},{"start":"paWlpaWlpaWlpaWlpaWlpQ==","end":"tLS0tLS0tLS0tLS0tLS0tA==","length":0},{"start":"tLS0tLS0tLS0tLS0tLS0tA==","end":"w8PDw8PDw8PDw8PDw8PDww==","length":0},{"start":"w8PDw8PDw8PDw8PDw8PDww==","end":"0tLS0tLS0tLS0tLS0tLS0g==","length":0},{"start":"0tLS0tLS0tLS0tLS0tLS0g==","end":"4eHh4eHh4eHh4eHh4eHh4Q==","length":0},{"start":"4eHh4eHh4eHh4eHh4eHh4Q==","end":"8PDw8PDw8PDw8PDw8PDw8A==","length":0},{"start":"8PDw8PDw8PDw8PDw8PDw8A==","end":"","length":0}]}
2. http://localhost:8080/graphs/hugegraph/traversers/vertices/scan?start=Dw8PDw8PDw8PDw8PDw8PDw==&end=Hh4eHh4eHh4eHh4eHh4eHg==
返回 {"vertices":[]}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10000}
- loaded edges amount: {like  8000}

#### Vertex/Edge example 数据示例
"458997453522206720"	"vulnerabilities"	{"cve_id":"","cnvd_id":"","reference_urls":["EulerOS-SA-2020-1021"],"vulnerable_packages":["openssl 1.1.1"]}

### Specifications of environment 环境信息
- hugegraph version: {like v0.11/2}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like hbase 2.3.0 , cluster with 3 nodes,  500G disk each node}

**Comment by imbajin** [comment]
麻烦帮忙确认一下, 这些返回的 `shard` 中, 是全部没有数据, 还是部分有部分空 (后者目前和计算方式是符合的)

如果全部都是空数据, 可以尝试先单个 region 不去分区导点数据看看, 是否 `shard` 返回数据
