### ISSUE TITLE
hugegraph hubble连接数据库host name may not be null

### ISSUE THREAD

**Issue by snrui** [hugegraph/hugegraph#1457]
环境信息
- hugegraph version: {like v0.11.2}
- operating system: {like centos 7.4, 32 CPUs, 35G RAM}
- hugegraph backend: {memory}
- hugegraph-hubble version 1.5

遇到的问题：
进入hugegraph-hubble创建图页面，填写主机名称点击创建后报错host may not be null，server发送http请求返回200，状态正常，监听主机配置为0.0.0.0，telnet服务器端口也是通的
![16214111832](https://user-images.githubusercontent.com/72593964/118778161-643cca00-b8bc-11eb-86ef-71d17bab92b8.jpg)

**Comment by imbajin** [comment]
> server 发送 http 请求返回 200，状态正常，监听主机配置为 0.0.0.0，telnet 服务器端口也是通的

提示简单看应该是填入的`host` 不合法或者没被识别, 你说 server 发送 http 请求是怎么发的? 麻烦贴一下具体语句

你应该在 `hubble` 的机器上 `curl` 发一个 简单的 HTTP 请求 (如`http://hostbane:8080/graphs`), "主机名 + 端口" 都与 浏览器中 `hubble` 填写的中一致, 然后**截图**发送的请求.

另外在你浏览器的机器也试试 `ping` 一下你填的 ip/域名, 看看是否存在任何的网络问题.  如果以上都排查过, 你可以 F12 打开浏览器调试模式, 看看报错的请求是否有其他详细信息, 包括看看 hubble 进程对应输出的**日志**, 是否有任何具体异常栈输出

**Comment by snrui** [comment]
按照文档中的步骤发送请求
![image](https://user-images.githubusercontent.com/72593964/118805879-0074ca00-b8d9-11eb-87af-b1cfd6cdee30.png)
简单的http请求
![image](https://user-images.githubusercontent.com/72593964/118806167-534e8180-b8d9-11eb-9d20-bf4e27aada17.png)
启动日志
![image](https://user-images.githubusercontent.com/72593964/118805688-cc010e00-b8d8-11eb-82fd-8bd0c3ed6d2b.png)

浏览器报错信息
![image](https://user-images.githubusercontent.com/72593964/118806442-a6c0cf80-b8d9-11eb-9bd9-2680b131fe1e.png)

浏览器机器ping虚拟机能ping通的，hubble文件夹下没有log文件

**Comment by imbajin** [comment]
多谢提供反馈, 浏览器是说 F12 的 `Network` 发/收请求的地方, 看看它的原生 response, 前端可能有封装, 不过估计是类似的.

不过从它请求的地方, 可以找到对应代码的**抛出入口**, 然后方便捕获一下完整的异常栈, 现在的信息有点过少的确不好排查.

另外, 有试过其他机器 / 非虚拟机环境下启动么? `server/hubble` 也可以在 Windows 环境启动的, 可以试着尽可能排除一下网络相关情况, 做一下对比测试
