### ISSUE TITLE
hugegraph兼容的java 11无法启动

### ISSUE THREAD

**Issue by snrui** [hugegraph/hugegraph#1458]
在java 8环境下可以正常运行，在java 11中重启服务报错
![image](https://user-images.githubusercontent.com/72593964/118795842-999de380-b8cd-11eb-8190-c3d192317127.png)
java版本
![image](https://user-images.githubusercontent.com/72593964/118796054-cf42cc80-b8cd-11eb-8399-3ad76a16df7c.png)
是不兼容java 11吗

**Comment by imbajin** [comment]
是的, 默认要求 JDK 版本在 `jdk8/1.8` , 开发环境基于 JDK8, 到 JDK11 肯定有不兼容的地方
很少有项目可以直接兼容使用的, 不过你可以提供一下 JDK11 报错的信息, 后续项目可考虑兼容到 JDK 11 / 15 长期支持版

当然还有一个重要考虑就是升级带来的好处, 比如升级 JDK 11 主要考量是什么呢, 欢迎反馈
