### ISSUE TITLE
task无法删掉

### ISSUE THREAD

**Issue by yuyang0** [hugegraph/hugegraph#146]
一个task把服务器搞挂了，重启之后，task一直是running状态，尝试删除该task，报错

    {"exception":"class javax.ws.rs.BadRequestException","message":"Can't delete task '5601' with unstable status 'RUNNING'","cause":""}

是所有没有结束的task都不能删除吗？还有大数据量查询的时候推荐什么方法？task还是分页？

**Comment by javeme** [comment]
@yuyang0 是的，没有结束的任务无法删除。可以先cancel任务再delete（0.8版本才会暴露cancel api）。

**Comment by yuyang0** [comment]
但是这个任务感觉像是卡死了，跑了一天还是running

**Comment by yuyang0** [comment]
这肯定又是一个bug

> {
task_name: "g.V().hasLabel("user").filter{it.get().property("lastRequestTime").value().contains("2018-10-17")}.group().by(id()).by(out("userIp").count()).order(local).by(values).unfold().tail(10).fold()",
task_progress: 0,
task_create: 1540799713841,
task_status: "running",
task_retries: 0,
id: 5601,
task_type: "gremlin",
task_callable: "com.baidu.hugegraph.api.job.GremlinAPI$GremlinJob",
task_input: "{"gremlin":"g.V().hasLabel(\"user\").filter{it.get().property(\"lastRequestTime\").value().contains(\"2018-10-17\")}.group().by(id()).by(out(\"userIp\").count()).order(local).by(values).unfold().tail(10).fold()","bindings":{},"language":"gremlin-groovy","aliases":{"hugegraph":"graph"}}"
}

跑了两天，一直是running @javeme

**Comment by javeme** [comment]
@yuyang0 运行过程中有重启服务器吗？

**Comment by yuyang0** [comment]
有，但是这是这个task把server搞挂了我才重新启动的，日志里面没发现什么有用的信息

**Comment by javeme** [comment]
如果重启后，0.7版时任务不会重新恢复运行，预计0.8才加入这个feature，请关注 #137

**Comment by yuyang0** [comment]
关键是这个状态是错误的，肯定没在跑，但是status却是running,弄得我删都删不掉

Jermy Li <notifications@github.com> 于 2018年10月31日周三 下午7:24写道：
