### ISSUE TITLE
请问能用 HugeGraph 做自适应推荐相关的功能吗

### ISSUE THREAD

**Issue by tjthink** [hugegraph/hugegraph#1464]
请问能用 HugeGraph 做自适应推荐相关的功能吗

**Comment by imbajin** [comment]
为了提高 issue 响应和处理效率, 提 Issue 前请参考相关注意事项:
- 提符合分类规范的 issue, 标题参考提供的 issue 模板
- 提供详细的上下文信息, 比如 "自适应推荐" 具体的上下文, 和参考的例子 / 链接等.

![image](https://user-images.githubusercontent.com/17706099/119600319-643b4d80-be19-11eb-9aed-272a2774abc8.png)
THX~
