### ISSUE TITLE
[Question] 自适应推荐相关功能和使用方式

### ISSUE THREAD

**Issue by tjthink** [hugegraph/hugegraph#1465]
## Environment ( 环境信息 - 必填 )
- **Server Version**: v0.11.2 (refer [here](https://hugegraph.github.io/hugegraph-doc/clients/restful-api/other.html))
- **Backend**: rocksdb, 1 nodes, HDD
- **OS**: 8  CPUs, 16 G RAM, Centos 7.x
- **Data Size**:  100W vertices, 1000W edges

## 问题描述 
请教知识点推荐方面的问题
1、通过维护知识点(其中有预估难度属性)，对这些知识点进行学习，最后经过一系列计算得出个人对此知识点的难度，以及此知识点的平均难度
2、如何根据平均难度推送某一知识点与之难度相近的知识点
3、知识点的平均难度是动态的，有没有建议的保存方式？是动态修改知识的平均难度属性还是采用其他方式

> 注: 图使用 / 配置相关问题, 请优先参考 [REST-API 文档](https://hugegraph.github.io/hugegraph-doc/clients/hugegraph-api.html), 以及 [Server 配置文档](https://hugegraph.github.io/hugegraph-doc/config/config-option.html)

### Related information ( 补充相关信息 ) :
<details>
<summary> Provide related "Data & Schema" info (Click to expand) </summary>

### Vertex/Edge example ( 问题点 / 边数据举例 )

```javascript
// JSON of Vertex / Edge ⬇

```

### Schema [VertexLabel, EdgeLabel, IndexLabel] ( 元数据结构 )

```javascript
// JSON of GraphSchema ⬇

```
</details>

**Comment by imbajin** [comment]
对推荐算法本身倒是不太了解, 整体看了下, 你说的三个点里:
1. 应该第一步如何算某个点, 是业务层自己实现的 (类似数据加工), 这部分**以后**可以放图计算框架自定义算法里做.
2. 第二步你说的推送, 可能是说类似打分**传递**到其他点并更新内存中的迭代的意思? 类似 [KNN](http://www.cqvip.com/qk/90453x/201601/667652258.html) 用来做推荐里的需要, 这个可以自己把这个传递逻辑在用户层实现, 也可以之后在图计算的框架里实现. (目前的图数据库里还不能自定义算法细节)
3. 保存方式也是分两个, 用图计算框架你可以保存到文件, 或者写回图数据库; 如果是业务层控制逻辑, 可考虑新增一个属性, 更新计算后这个属性的值就行. 

总之, 目前只使用图数据库的时候, 你可以考虑这些内置的 [Rank API](https://hugegraph.github.io/hugegraph-doc/clients/restful-api/rank.html) (比如 PageRank, NeighborRank, 还有 Traverser 里的算法 ), 看看是否有能够复用的, 动态修改结果为宜; 后续结合图计算框架, 再把逻辑下放到框架里.

**Comment by tjthink** [comment]
> 对推荐算法本身倒是不太了解, 整体看了下, 你说的三个点里:
> 
> 1. 应该第一步如何算某个点, 是业务层自己实现的 (类似数据加工), 这部分**以后**可以放图计算框架自定义算法里做.
> 2. 第二步你说的推送, 可能是说类似打分**传递**到其他点并更新内存中的迭代的意思? 类似 [KNN](http://www.cqvip.com/qk/90453x/201601/667652258.html) 用来做推荐里的需要, 这个可以自己把这个传递逻辑在用户层实现, 也可以之后在图计算的框架里实现. (目前的图数据库里还不能自定义算法细节)
> 3. 保存方式也是分两个, 用图计算框架你可以保存到文件, 或者写回图数据库; 如果是业务层控制逻辑, 可考虑新增一个属性, 更新计算后这个属性的值就行.
> 
> 总之, 目前只使用图数据库的时候, 你可以考虑这些内置的 [Rank API](https://hugegraph.github.io/hugegraph-doc/clients/restful-api/rank.html) (比如 PageRank, NeighborRank, 还有 Traverser 里的算法 ), 看看是否有能够复用的, 动态修改结果为宜; 后续结合图计算框架, 再把逻辑下放到框架里.

好的，另外请教下，我最终是要把知识点放到图数据库里的，这里是直接放进去还是说先放到关系性数据库，然后再同步到图数据库中

**Comment by imbajin** [comment]
没有特殊情况可以直接放到图里, 主要是生成数据的时候, 要符合图建模的规范

**Comment by tjthink** [comment]
> 没有特殊情况可以直接放到图里, 主要是生成数据的时候, 要符合图建模的规范

好，感谢，后面有问题再请教您
