### ISSUE TITLE
[Question] hugegraph 使用tinkpop  gremlin 的 相关查询predicate 

### ISSUE THREAD

**Issue by Ckuangf** [hugegraph/hugegraph#1467]
### Note ( 特别注意 ) : 

> 1. 请先**搜索**, 并**确认**现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有与您相同 / 相关的问题, 请勿重复提交
> 2. 我们需要尽可能**详细**的信息来**分析**问题, 越详细的信息 (包括**日志 / 截图 / 配置**等) 会**越快**被响应和处理
> 3. 请关注提交的 issue, 缺乏信息 / 长时间 ( > 14 天) 没有回复, issue 可能会被 **关闭** (需要时可再开启)

## Environment ( 环境信息 - 必填 )
- **Server Version**: v0.11.x (refer [here](https://hugegraph.github.io/hugegraph-doc/clients/restful-api/other.html))
- **Backend**: Cassandra 3.x, x nodes, HDD or SSD
- **OS**: xx CPUs, xx G RAM, Centos 7.x
- **Data Size**:  xx vertices, xx edges (like 1000W 点, 9000W 边)

## Your Question ( 问题描述 )
目前查询的时候想要使用startWith方法，但是直接报出不支持的情况
![image](https://user-images.githubusercontent.com/31173360/119653657-2b6f9880-be5a-11eb-8456-f82b42825de1.png)
我看TraversalUtil 这个类里面是有做部分predicate的转换的，是否是目前只能使用转换的这些呢
![image](https://user-images.githubusercontent.com/31173360/119653951-81dcd700-be5a-11eb-8c86-462bae9ad224.png)

xxx

> 注: 图使用 / 配置相关问题, 请优先参考 [REST-API 文档](https://hugegraph.github.io/hugegraph-doc/clients/hugegraph-api.html), 以及 [Server 配置文档](https://hugegraph.github.io/hugegraph-doc/config/config-option.html)

### Related information ( 补充相关信息 ) :
<details>
<summary> Provide related "Data & Schema" info (Click to expand) </summary>

### Vertex/Edge example ( 问题点 / 边数据举例 )

```javascript
// JSON of Vertex / Edge ⬇

```

### Schema [VertexLabel, EdgeLabel, IndexLabel] ( 元数据结构 )

```javascript
// JSON of GraphSchema ⬇

```
</details>

**Comment by imbajin** [comment]
gremlin 新版增加的 `startWith()` 暂没直接支持, 你可以用 `textContains()` 来代替 (目前)

**Comment by Ckuangf** [comment]
> gremlin 新版增加的 `startWith()` 暂未直接支持, 你(目前)可以用 `textContains()` 来代替

请问下这个需要怎么写呢，我尝试了g.V().has("globaleName",textContains("te"))和g.V().has("globaleName",Text.textContains("te")) 都不行

**Comment by imbajin** [comment]
可以参考 #1309,  gremlin 写法更新一下, rest-api 里现在也支持了.

**Comment by Ckuangf** [comment]
> 可以参考 #1309, gremlin 写法更新一下, rest-api 里现在也支持了.

![image](https://user-images.githubusercontent.com/31173360/119817695-e06c8880-bf20-11eb-85f1-082f8dbc523f.png)
我使用的hugegraph-server 是 官网下载的 0.11.2，在查询的时候还是不支持的，请问下这个语法是什么版本开始支持的呢

**Comment by imbajin** [comment]
看一下原 issue 内容,  你输错了方法名, 是 `g.V().has('xx', Text.contains('xx'))` , 不是你输的.

**Comment by Ckuangf** [comment]
> 看一下原 issue 内容, 你输错了方法名, 是 `g.V().has('xx', Text.contains('xx'))` , 不是你输的.
我理解错了，我之前以为是textcontains是和Text.contains() 不同的方法，我知道Text.contains()这个用法。如果我们跳过这个，我想了解的是目前huge graph 是否支持直接使用tinkpop 中gremlin 相关的一些predicate进行操作，除了startWith，像notContaining，endingWith是否目前都没有支持

**Comment by imbajin** [comment]
是的, 你可以看一下这些 gremlin 语法再 tinkerpop 支持的版本 `3.xx`. 然后社区有对应的支持版本, 高于版本的方法一般都是不支持的.

**Comment by Ckuangf** [comment]
> 是的, 暂不支持, 你可以看一下这些 gremlin 语法再 tinkerpop 支持的版本 `3.xx`. 然后社区有对应的支持版本, 高于版本的方法一般都是不支持的.
好的  多谢
