### ISSUE TITLE
[Question]请问动态创建多图已经完成了吗

### ISSUE THREAD

**Issue by tjthink** [hugegraph/hugegraph#1468]
Server Version: v0.11.2 (refer here)
Backend: rocksdb, 1 nodes, HDD
OS: 8 CPUs, 16 G RAM, Centos 7.x
Data Size: 100W vertices, 1000W edges

## Your Question ( 问题描述 )
 请问动态创建多图或多租户实现了吗，我看好多小伙伴都有问到，因为我们业务也需要用到，有点像saas业务

> 注: 图使用 / 配置相关问题, 请优先参考 [REST-API 文档](https://hugegraph.github.io/hugegraph-doc/clients/hugegraph-api.html), 以及 [Server 配置文档](https://hugegraph.github.io/hugegraph-doc/config/config-option.html)

### Related information ( 补充相关信息 ) :
<details>
<summary> Provide related "Data & Schema" info (Click to expand) </summary>

### Vertex/Edge example ( 问题点 / 边数据举例 )

```javascript
// JSON of Vertex / Edge ⬇

```

### Schema [VertexLabel, EdgeLabel, IndexLabel] ( 元数据结构 )

```javascript
// JSON of GraphSchema ⬇

```
</details>

**Comment by imbajin** [comment]
目前还没有, 可以在 PR 区看到相关功能 / 代码是否已合入. (另外标题请保持原有模板风格 -- `[Question] xxx`)
