### ISSUE TITLE
[Question]  统计的时候，如何通过自定义函数处理 group by 字段

### ISSUE THREAD

**Issue by jadepeng** [hugegraph/hugegraph#1476]
<details>

## 问题描述

在统计场景，我们需要按照create_time来进行分组计数，create_time存储的时间戳
在统计的时候希望可以按日期、月份、年份等不同维度来统计

希望可以采用类似下面的方式来进行查询：

```java
.groupCount().by(day(create_time)))
```

请问：

- 如何自定义day\month等函数？
- 在java里如何实现

</details>

**Comment by javeme** [comment]
示例：
`def firstChar = { it.value('name').substring(0, 1) }; g.V().groupCount().by(firstChar)`

**Comment by jadepeng** [comment]
> 示例：
> `def firstChar = { it.value('name').substring(0, 1) }; g.V().groupCount().by(firstChar)`

感谢回复，gremlin这样应该挺方便。

java直接调用的话，可以

```java
result = traversal.groupCount()
                              .by(it -> getGroupByKey(it, groupByProperty))
                              .toList().get(0);


...

public static String getGroupByKey(Object object, String... properties){
        B_O_Traverser<HugeVertex> traverser = (B_O_Traverser<HugeVertex>)object;
        HugeVertex vertex = traverser.get();
        // todo 从vertex获取属性，计算
    }


```
