### ISSUE TITLE
[Question] 当vertex的id由外部指定时，vertex同时有一个属性字段名也为id，且数据类型均为string，如何区分这两者？

### ISSUE THREAD

**Issue by hhhyang** [hugegraph/hugegraph#1485]
假设，我有一个vertex，信息如下：
```
id | label | properties
-- | -- | --
"akas" | "Dog" | {"id":"www","name":"akas"}
```
执行查询语句：
```
g.V('akas').valueMap('name').by(unfold()).with(WithOptions.tokens, WithOptions.ids)
```
结果为：
```
{"id":"akas","name":"akas"}
```
id值为vetex id的值

执行查询语句：
```
g.V('akas').valueMap().by(unfold()).with(WithOptions.tokens, WithOptions.ids)
```
结果为：
```
{"id":"www","name":"akas"}
```
id值为属性id的值

当查询结果同时包含vertex的id和属性的id时，实际结果只有属性id的值，请问这符合预期吗？

**Comment by imbajin** [comment]
这个目前是符合预期的.  如果你希望两个`id`同时显示, 直接 `g.V(vid)` 就可以了

用 `with()` 不知道是不是就是为了让两个 id 同时显示. 当然一般来说, 因为 id 名字算系统属性, 换另一个命名是更好的

**Comment by hhhyang** [comment]
现在的模型相当于id和label是保留关键字，业务的顶点或边的属性名如果是id或label的话，查询时就不能同时获取顶点或边的id/label值和作为属性的id/label值。由于业务本身的要求或从现有系统迁移到hugegraph，更改属性名会有阻碍。

**Comment by imbajin** [comment]
可是你直接 `g.V(vid)` 默认情况下展开的时候, 你的属性数组, 就是单独的二级成员不会冲突呀.

你只有在这种`valueMap()` 的封装下才会这样, 是有什么原因导致不能直接使用默认的返回封装么

**Comment by hhhyang** [comment]
因为用户查询的时候只需要返回用户在接口调用时动态指定的几个字段的值。
