### ISSUE TITLE
[Question] 在建立了search索引的字段上查询的时候，怎么进行“是”的查询

### ISSUE THREAD

**Issue by Ckuangf** [hugegraph/hugegraph#1497]
<details>
<summary> Note ( 特别注意, 点击展开 ) </summary>

### Note ( 特别注意 ) : 

> 1. 请先**搜索**, 并**确认**现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有与您相同 / 相关的问题, 请勿重复提交
> 2. 我们需要尽可能**详细**的信息来**分析**问题, 越详细的信息 (包括**日志 / 截图 / 配置**等) 会**越快**被响应和处理
> 3. Issue 标题请保持原有模板`[分类]`, 长段描述之间可以增加空行或使用`序号`标记, 保持排版清晰
> 4. 请关注提交的 issue, 缺乏信息 / 长时间 ( > 14 天) 没有回复, issue 可能会被 **关闭** (更新时会再开启)

</details>

## Environment ( 环境信息 - 必填 )
- **Server Version**: v0.11.x (refer [here](https://hugegraph.github.io/hugegraph-doc/clients/restful-api/other.html))
- **Backend**: Cassandra 3.x, x nodes, HDD or SSD
- **OS**: xx CPUs, xx G RAM, Centos 7.x
- **Data Size**:  xx vertices, xx edges 

## Your Question ( 问题描述 )
文档中表示，search建立的索引是可以使用 是或者包含的意义查询的，但是目前只有Text.contains 的方式使用，那 “是” 这种查询应该怎么写呢
![image](https://user-images.githubusercontent.com/31173360/121779932-a661de80-cbd0-11eb-8df9-5acc8a854418.png)

xxx

> 注: 图使用 / 配置相关问题, 请优先参考 [REST-API 文档](https://hugegraph.github.io/hugegraph-doc/clients/hugegraph-api.html), 以及 [Server 配置文档](https://hugegraph.github.io/hugegraph-doc/config/config-option.html)

### Related information ( 补充相关信息 ) :
<details>
<summary> Related "Data & Schema" info ( Click to expand ) </summary>

### Vertex/Edge example ( 问题点 / 边数据举例 )

```javascript
// JSON of Vertex / Edge ⬇

```

### Schema [VertexLabel, EdgeLabel, IndexLabel] ( 元数据结构 )

```javascript
// JSON of GraphSchema ⬇

```
</details>

**Comment by imbajin** [comment]
你可以参考以下已有的数个全文索引 / 模糊索引使用的 issue, 例如 #372

**Comment by Ckuangf** [comment]
> 你可以参考以下已有的数个全文索引 / 模糊索引使用的 issue, 例如 #372

有看过之前的一些issure，不过更多的是search索引  包含方式的创建，这样用Text.contains()就好了，但是在search索引中要执行 “是” 这种语义的操作的话，还没找到，而文档中又说是可以支持的。
