### ISSUE TITLE
[Question] 如何通过 api 查询一个顶点的所有边 (多层邻居)

### ISSUE THREAD

**Issue by s348268281** [hugegraph/hugegraph#1505]
<details>
<summary> Note ( 特别注意, 点击展开 ) </summary>

### Note ( 特别注意 ) : 

> 1. 请先**搜索**, 并**确认**现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有与您相同 / 相关的问题, 请勿重复提交
> 2. 我们需要尽可能**详细**的信息来**分析**问题, 越详细的信息 (包括**日志 / 截图 / 配置**等) 会**越快**被响应和处理
> 3. Issue 标题请保持原有模板`[分类]`, 长段描述之间可以增加空行或使用`序号`标记, 保持排版清晰
> 4. 请关注提交的 issue, 缺乏信息 / 长时间 ( > 14 天) 没有回复, issue 可能会被 **关闭** (更新时会再开启)

</details>

## Environment ( 环境信息 - 必填 )
- **Server Version**: v0.11.x (refer [here](https://hugegraph.github.io/hugegraph-doc/clients/restful-api/other.html))
- **Backend**: Cassandra 3.x, x nodes, HDD or SSD
- **OS**: xx CPUs, xx G RAM, Centos 7.x
- **Data Size**:  xx vertices, xx edges 

## Your Question ( 问题描述 )

请问如何通过api查询一个顶点的所有边？以及这个顶点所有边的所有边？我看获取符合条件的边的文档中的参数没有找到可以使用的。
就比如一个顶点是用户，关系是好友，如何获取用户的好友，以及好友的好友，并且其中的关联方向怎么查询？

> 注: 图使用 / 配置相关问题, 请优先参考 [REST-API 文档](https://hugegraph.github.io/hugegraph-doc/clients/hugegraph-api.html), 以及 [Server 配置文档](https://hugegraph.github.io/hugegraph-doc/config/config-option.html)

### Related information ( 补充相关信息 ) :
<details>
<summary> Related "Data & Schema" info ( Click to expand ) </summary>

### Vertex/Edge example ( 问题点 / 边数据举例 )

```javascript
// JSON of Vertex / Edge ⬇

```

### Schema [VertexLabel, EdgeLabel, IndexLabel] ( 元数据结构 )

```javascript
// JSON of GraphSchema ⬇

```
</details>

**Comment by imbajin** [comment]
简单看你的描述类似 K 步邻居 (kneighbor), 首先你可以用 `gremlin` 完成这些操作, 可以参考已有 issues.

然后, REST-api 里也有内置的 `kout` 和 `kneighbor` 算法, 还可以自定义查询方式, 详细参考 [traverser 文档](https://hugegraph.github.io/hugegraph-doc/clients/restful-api/traverser.html)

(另外标题和描述请保持原有模板风格 -- [Question] xxx, 方便更快了解问题)

**Comment by s348268281** [comment]
@imbajin  你好，我看了 traverser 文档，在使用K-out API：GET http://localhost:8080/graphs/{graph}/traversers/kout?source="1:marko"&max_depth=2时，报错{'exception': 'class javax.ws.rs.NotFoundException', 'message': "Graph '{graph}' does not exist", 'cause': ''}，请问url里的{graph}是什么含义？文档中也没有相关描述。
