### ISSUE TITLE
[Question] 请教几个列表型参数的最大支持规格问题

### ISSUE THREAD

**Issue by hhhyang** [hugegraph/hugegraph#1509]
查询时遇到一些列表型参数的数量规格支持问题，有小伙伴可以告知一下吗：

1、有些gremlin查询step参数可以是一个列表，如g.V(id1,id2...)，within(...)，valueMap(...)等，请问支持的最大参数个数是多少？可以通过参数配置吗？如果可以，在哪个配置文件通过哪个参数配置？

2、binding()绑定时，一个查询语句最多支持多少个binding参数？可以通过参数配置吗？如果可以，在哪个配置文件通过哪个参数配置？

3、binding()绑定时，如果绑定的参数值是一个列表，请问参数值列表的最大长度有限制吗？如果有，是否有参数调节最大长度值？在哪个配置文件通过哪个参数配置？

**Comment by javeme** [comment]
@hhhyang g.V()中的id属于方法参数，受语法影响，方法数组参数一次性最大支持250个id。binding理论上没有限制。
