### ISSUE TITLE
通过代码删除Schema时报错

### ISSUE THREAD

**Issue by baibingzhi** [hugegraph/hugegraph#151]
操作：
  SchemaManager schema = hugeClient.schema();
  schema.removeEdgeLabel("relationE");

Expected behavior 期望表现
  成功删除Schema

Actual behavior 实际表现
  Schema被删除，但是返回报错
  HugeException:Failed to update/query TaskStore

Specifications of environment 环境信息
- hugegraph version:  v0.7.4
- operating system:   @@centos
- hugegraph backend: memory

**Comment by Linary** [comment]
起的是Memory后端吗？这个问题疑似与 #99 相似，你可以试试拉取最新的 hugegraph 代码，自行编译打包看看还有没有这个问题。
