### ISSUE TITLE
g.V().hasLabel("label_name") 报错

### ISSUE THREAD

**Issue by GZYBigGG** [hugegraph/hugegraph#1516]
查询标签命令g.V().hasLabel("label_name") 时报错，具体错误为：
Gremlin 执行失败，详细信息: Don't accept query by label xxxx, label index is disabled，请问如何解决？
![image](https://user-images.githubusercontent.com/54423934/123223699-b26c6b00-d503-11eb-89cd-5d710bc2c16a.png)

**Comment by imbajin** [comment]
请先阅读 issue 须知, 按照 issue 模板提交问题.

![image](https://user-images.githubusercontent.com/17706099/123222546-a2a05700-d502-11eb-9acd-d2670f59c83e.png)


你说的这个问题在历史 issue 里有, 可以查阅一下.

**Comment by GZYBigGG** [comment]
> 请先阅读 issue 须知, 按照 issue 模板提交问题.
> 
> ![image](https://user-images.githubusercontent.com/17706099/123222546-a2a05700-d502-11eb-9acd-d2670f59c83e.png)
> 
> 你说的这个问题在历史 issue 里有, 可以查阅一下.

已进行查询，并没有相同的问题。在HugeGraph中，g.V().hasLabel("label_name")直接报错。

**Comment by GZYBigGG** [comment]
已解决。存储空间采用了RocksDB，RocksDB不支持通过label 查数据。
