### ISSUE TITLE
[Question] 高可用使用咨询

### ISSUE THREAD

**Issue by ingla9988** [hugegraph/hugegraph#1517]
环境部署情况：
1、使用最新版本HugeGraph 0.11.2部署server，后端存储用pg
2、server配置3个节点，第一个节点的rest-server.properties文件server.role=master，其他两个节点配置server.role=worker，三个节点都指向同一个后端pg

请问这样部署高可用是否可以？ 三个节点的缓存数据怎么保证一致性？是否还有其他注意的地方？ 最新版本的高可用部署有什么建议和参考文档嘛？
谢谢

**Comment by imbajin** [comment]
同学你好，请先阅读 **issue** 须知，按照 issue ** 模板 ** 基本规范提交问题. (标题 `[xx]` + 必填项 + 相关问题信息), 以方面社区更快更好的处理问题.

![image](https://user-images.githubusercontent.com/17706099/123222546-a2a05700-d502-11eb-9acd-d2670f59c83e.png)

你的配置是可以的, 多机缓存一致性可通过 RPC 通信保证, V0.12 版(或 master 分支)已经支持, 你可以自行测试.(Warn: Not GA)

另外你说的问题在历史 issue 里是有的，可以先参考一下历史提问和回复，然后仍有疑问再来补充反馈

后续麻烦修改 / 编辑标题 & 内容，感谢～😄

**Comment by ingla9988** [comment]
最新的社区版本不是HugeGraph 0.11.2吗？  V0.12 版是指哪里的版本呀？

**Comment by ingla9988** [comment]
> 同学你好，请先阅读 **issue** 须知，按照 issue **模板** 基本规范提交问题. (标题 `[xx]` + 必填项 + 相关问题信息), 以方面社区更快更好的处理问题.
> 
> ![image](https://user-images.githubusercontent.com/17706099/123222546-a2a05700-d502-11eb-9acd-d2670f59c83e.png)
> 
> 你的配置是可以的, 多机缓存一致性可通过 RPC 通信保证, V0.12 版(或 master 分支)已经支持, 你可以自行测试.(Warn: Not GA)
> 
> 另外你说的问题在历史 issue 里是有的，可以先参考一下历史提问和回复，然后仍有疑问再来补充反馈
> 
> 后续麻烦修改 / 编辑标题 & 内容，感谢～😄

最新的社区版本不是HugeGraph 0.11.2吗？ V0.12 版是指哪里的版本呀？

**Comment by imbajin** [comment]
那是 release 版本, 也可以理解为 GA / 稳定版, master 分支是 0.12 的版本

**Comment by ingla9988** [comment]
> 那是 release 版本, 也可以理解为 GA / 稳定版, master 分支是 0.12 的版本

有个疑问哈：
我看0.11版本的更新有这几条：
支持基于 Raft 的分布式一致性协议（hugegraph #1020）
支持 Raft 状态机更新缓存（hugegraph #1119）

这个不能保证各节点缓存数据的一致性吗？   得等你们 0.12的社区版本嘛？

**Comment by imbajin** [comment]
那个主要是存储层 rocksdb 的一致性读写相关, 和 RPC 保持的缓存一致性不是一个地方

你直接编译 master 分支代码也是可以用的
只是其他组件的兼容性要自己取 diy 一下或验证一下, release 版本就是说所有组件和测试都完整通过了一般

**Comment by ingla9988** [comment]
> 那个主要是存储层 rocksdb 的一致性读写相关, 和 RPC 保持的缓存一致性不是一个地方
> 
> 你直接编译 master 分支代码也是可以用的
> 只是其他组件的兼容性要自己取 diy 一下或验证一下, release 版本就是说所有组件和测试都完整通过了一般

好的，非常感谢
