### ISSUE TITLE
图库顶点在删除后，相关的边会自动删除吗

### ISSUE THREAD

**Issue by wisdoms** [hugegraph/hugegraph#1519]
图库的顶点在删除 后， 相关的边会自动 删除 吗？

**Comment by imbajin** [comment]
同学你好，请先阅读 **issue** 须知，按照 issue ** 模板 ** 基本规范提交问题. (标题 `[xx]` + 必填项 + 相关问题信息), 以方面社区更快更好的处理问题.

![image](https://user-images.githubusercontent.com/17706099/123222546-a2a05700-d502-11eb-9acd-d2670f59c83e.png)

另外你说的问题在历史 issue 里是有的，可以先参考一下历史提问和回复，然后仍有疑问再来补充反馈 (目前是会自动删除的, 否则会有大量残留的孤立边)

后续麻烦修改 / 编辑标题 & 内容，感谢～😄
