### ISSUE TITLE
[Question] 导入了孤立的点/边, Hubble 显示这样的终止点id 为 "null"，怎么过滤

### ISSUE THREAD

**Issue by pdong524** [hugegraph/hugegraph#1524]
<details>
<summary> Note ( 特别注意, 点击展开 ) </summary>

### Note ( 特别注意 ) : 

> 1. 请先**搜索**, 并**确认**现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有与您相同 / 相关的问题, 请勿重复提交
> 2. 我们需要尽可能**详细**的信息来**分析**问题, 越详细的信息 (包括**日志 / 截图 / 配置**等) 会**越快**被响应和处理
> 3. Issue 标题请保持原有模板`[分类]`, 长段描述之间可以增加空行或使用`序号`标记, 保持排版清晰
> 4. 请关注提交的 issue, 缺乏信息 / 长时间 ( > 14 天) 没有回复, issue 可能会被 **关闭** (更新时会再开启)
</details>

## Environment ( 环境信息 - 必填 )
- **Server Version**: v0.10.4
- **Backend**: hbase
- **OS**:  Centos 6
- **Data Size**: like 200 点, 100边

## Your Question ( 问题描述 )

请问导入数据时没有检查起点和终点的顶点是否存在，导入后出现了一部分终点为null的情况，应该是hugegraph给自动生成的，怎么样将相关的边全部过滤掉呢
在hubble中看相关边时，显示是这样的：
![b23394a18cf7ec1174be2cd9f6226f1](https://user-images.githubusercontent.com/67000603/123650864-91867b80-d85d-11eb-93c3-051b2fe83499.png)

xxx

> 注: 图使用 / 配置相关问题, 请优先参考 [REST-API 文档](https://hugegraph.github.io/hugegraph-doc/clients/hugegraph-api.html), 以及 [Server 配置文档](https://hugegraph.github.io/hugegraph-doc/config/config-option.html)

### Related information ( 补充相关信息 ) :

<summary> Related "Data & Schema" info ( Click to expand ) </summary>

### Vertex/Edge example ( 问题点 / 边数据举例 )
查询g.V().has('XSBZ', Text .contains('1')).bothE().otherV()时显示没有问题
但是查询g.V().has('XSBZ', Text .contains('1')).bothE().otherV().path()时会报错，具体错误如下：
Vertex '18:null' does not exist

```javascript
// JSON of Vertex / Edge ⬇

```

### Schema [VertexLabel, EdgeLabel, IndexLabel] ( 元数据结构 )

```javascript
// JSON of GraphSchema ⬇

```

**Comment by imbajin** [comment]
首先是数据量小的时候, 直接清空然后重新导入开启, 设置 `check_vertex = true` 就行了, 这样导入边的时候会检查对应点是否存在

另外大量数据下如果已经有了这种 `null` 的 vid, 在新版里应该是不会这样的, 麻烦确认一下两个事: (看你是0.10版)
1. 先用 rest-api, 比如 postman/IDEA 内置发送 http 请求, 导入一个 sourceVid 或 targetVid 并不存在的id(你可以随意指定) 看看是否是一样的情况 (期望应该不是 `18:null` , 而应该是你指定的比如 `18:fakeVid` 才对), 然后可以看看是否是 loader/hubble 的判空策略自动转换的. 
2. 可以使用 `0.11` 的包再试试复现你的情况, 另外如果不需要这样的点, 可以使用 `filter()` 类 step 来过滤, 如果想默认就过滤所有 包括 `null` 的点, 也可以自行在源码的 filter 相关处增加一个检查.
