### ISSUE TITLE
[Question] 使用不等于条件查询报错

### ISSUE THREAD

**Issue by Ckuangf** [hugegraph/hugegraph#1526]
<details>
<summary> Note ( 特别注意, 点击展开 ) </summary>

### Note ( 特别注意 ) : 

> 1. 请先**搜索**, 并**确认**现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有与您相同 / 相关的问题, 请勿重复提交
> 2. 我们需要尽可能**详细**的信息来**分析**问题, 越详细的信息 (包括**日志 / 截图 / 配置**等) 会**越快**被响应和处理
> 3. Issue 标题请保持原有模板`[分类]`, 长段描述之间可以增加空行或使用`序号`标记, 保持排版清晰
> 4. 请关注提交的 issue, 缺乏信息 / 长时间 ( > 14 天) 没有回复, issue 可能会被 **关闭** (更新时会再开启)

</details>

## Environment ( 环境信息 - 必填 )
- **Server Version**: v0.11.x (refer [here](https://hugegraph.github.io/hugegraph-doc/clients/restful-api/other.html))
- **Backend**: Cassandra 3.x, x nodes, HDD or SSD
- **OS**: xx CPUs, xx G RAM, Centos 7.x
- **Data Size**:  xx vertices, xx edges 

## Your Question ( 问题描述 )
![image](https://user-images.githubusercontent.com/31173360/123774252-d105a400-d8ff-11eb-95c3-31ad9c3eeff4.png)
如果要查询属性不等于某个值的情况应该怎么查询呢
xxx

> 注: 图使用 / 配置相关问题, 请优先参考 [REST-API 文档](https://hugegraph.github.io/hugegraph-doc/clients/hugegraph-api.html), 以及 [Server 配置文档](https://hugegraph.github.io/hugegraph-doc/config/config-option.html)

### Related information ( 补充相关信息 ) :
<details>
<summary> Related "Data & Schema" info ( Click to expand ) </summary>

### Vertex/Edge example ( 问题点 / 边数据举例 )

```javascript
// JSON of Vertex / Edge ⬇

```

### Schema [VertexLabel, EdgeLabel, IndexLabel] ( 元数据结构 )

```javascript
// JSON of GraphSchema ⬇

```
</details>

**Comment by zyxxoo** [comment]
额，可以用 g.V().values('name').is(not(eq("bob")))

**Comment by hhhyang** [comment]
@zyxxoo 厉害，完美规避了huge当前anchor查询要求所有的过滤条件比较走索引查询的约束。

个人觉得huge这个自加的约束有点过于强了，丧失了用户使用的便利性和gremlin语言的遵从性

不知huge后续这个地方是否可以优化一下不？

**Comment by Ckuangf** [comment]
> 额，可以用 g.V().values('name').is(not(eq("bob"))), 或者 g.V().has('name', is(neq('bob')))

可以了感谢大佬，学习了

**Comment by imbajin** [comment]
> @zyxxoo 厉害，完美规避了 huge 当前 anchor 查询要求所有的过滤条件比较走索引查询的约束。
> 
> 个人觉得 huge 这个自加的约束有点过于强了，丧失了用户使用的便利性和 gremlin 语言的遵从性
> 
> 不知 huge 后续这个地方是否可以优化一下不？

这种写法, 跟之前[提问里](https://github.com/hugegraph/hugegraph/issues/1481#issuecomment-853801026)提到的 `filter()` 本质是类似的, 如果一个属性没有索引查询, 那就都需要扫表. 只能在小数据量时使用才能不超时

不过后续的确可以给一个选项参数, 比如 `ensure_scan_table`, 默认 `false`, 手动开启后允许扫表类的查询, 有更好的建议可以反馈, 避免大数据量下误扫表带来的很大影响

**Comment by hhhyang** [comment]
@imbajin 
这个地方我有一些个人的理解：
1）现在的情况是huge支持一些语法进行扫表，另一些语法不支持进行扫表；我觉得我们应该避免的是全表扫描吧，而不是不支持特定的查询语句吧？
2）我觉得这个场景跟 #1481 提问里的场景还是不一样的。#1481 并不需要全表扫描，只是数据过滤，因为有查询过滤条件是走索引的

**Comment by imbajin** [comment]
> 这个地方我有一些个人的理解：
> 1）现在的情况是 huge 支持一些语法进行扫表，另一些语法不支持进行扫表；我觉得我们应该避免的是全表扫描吧，而不是不支持特定的查询语句吧？
> 2）我觉得这个场景跟 #1481 提问里的场景还是不一样的。#1481 并不需要全表扫描，只是数据过滤，因为有查询过滤条件是走索引的

第一个其实应该不是部分支持部分不支持, 支持的应该算是之前**漏排查**了(没有特意全 ban 掉), 按之前的强约束, 这类可能扫表的 `step` 在没有索引的情况下默认都应该是禁止的, 因为用户并不知道底下逻辑, 大数据量下随便一个语法触发了这些扫表的情况又无法立刻中断, 会影响很大. (现在这可能算是`漏网之🐟`)

第二个也是类似意思, 只是说 `filter()` 是类似上面的写法, 应该没有本质区别 (不涉及你那个场景的)

总之这里如果用户体验觉得不友好, 那的确是可以改进的, 我的思路是, 默认扫表的 step 在没有索引的情况下都禁, 有参数允许的情况下都可允许, 或者细粒度可加个 step --> `scanTable(true)`, 例如 `g.V().has(property, "tom").scanTable(true)`

**Comment by hhhyang** [comment]
@imbajin 
如果图库中数据量很大，我其实是支持禁止全表扫描的。
我期望改进的点是：比如查询语句：g.V().has('A','valueA').has('B','valueB')，其中A建了索引，B没有建索引。或者查询g.V().has('A','valueA').has('B',neq('valueB'))，其中A建了索引，B也建了索引。这两种情况也支持查询，因为A是建了索引的，并不需要全表扫描，后面的has条件是过滤的。至于需要过滤的数据量和性能，可以交由用户去衡量，而不是完全禁止这种查询。

**Comment by hhhyang** [comment]
@imbajin 

我的想法总结一句话就是：是不是全表扫描，需要根据整个查询语句来确定，而不是根据单个过滤条件来确定。
