### ISSUE TITLE
[Question] 部分字段的within查询功能异常

### ISSUE THREAD

**Issue by hhhyang** [hugegraph/hugegraph#1534]
### Problem Type (问题类型)

struct / logic (架构 / 逻辑设计问题)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.2-b2
- Backend: Cassandra 3.11 
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

我的应用中节点有一个名字叫做cluster的字段，在某些查询情况下使用within查询时只返回了within中第一个过滤条件的数据

比如我有如下几个查询：
第一个查询：
```
gremlin> :> g.V().has('cluster',within('AA1')).has('role',within('BB1','BB2')).id()
```
第二个查询：
```
gremlin> :> g.V().has('cluster',within('AA1','AA2')).has('role',within('BB1','BB2')).id()
```
第三个查询：
```
gremlin> :> g.V().has('cluster',within('AA2')).has('role',within('BB1','BB2')).id()
```
第四个查询：
```
gremlin> :> g.V().has('cluster',within('AA2','AA1')).has('role',within('BB1','BB2')).id()
```
第五个查询：
```
gremlin> :> g.V().has('cluster',within('AA2','AA1','AA3')).has('role',within('BB1','BB2')).id()
```
第二个查询的结果与第一个查询的结果一样，第四个和第五个查询的结果与第三个查询的结果一样。（PS：第一个和第三个查询结果不一样，符合预期）

如果去掉后面的过滤条件，如第二个查询改为：
```
gremlin> :> g.V().has('cluster',within('AA1','AA2')).id()
```
查询结果符合预期

开始怀疑是哪个地方数据有损坏，把cassandra数据清除，重新部署一个全新的系统，然后重新导入数据，但是导入数据后结果还是一样。

请问这会是什么原因呢？

**Comment by zyxxoo** [comment]
hi， 可以先描述下原数据的情况吗，比如图里面 'cluster'  有哪些， role 分别是什么

**Comment by hhhyang** [comment]
这个跟cluster和role的具体的值有关吗？具体的值比较多

**Comment by hhhyang** [comment]
今天有遇到一个类似的问题，只是查询的字段不一样
查询语句
```
g.V().has('idc','NJXG').has('role',within('DC','ADC')).id()
```
与查询语句
```
g.V().has('idc','NJXG').has('role',within('ADC','DC')).id()
```
返回结果不一样，第一个查询语句只返回了role值DC的节点，第二个查询语句只返回了role值为ADC的节点

请问这个问题可能是什么原因？如何修复啊？

**Comment by javeme** [comment]
![image](https://user-images.githubusercontent.com/9625821/144616089-e5525a15-8c0d-4e0b-af84-28b78dde169e.png)
