### ISSUE TITLE
[Question] 关于docker运行hugegraph-studio

### ISSUE THREAD

**Issue by s348268281** [hugegraph/hugegraph#1536]
### Problem Type (问题类型)

others (please edit later)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.x
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

我看了https://github.com/hugegraph/hugegraph/pull/845，只有关于hugegraph部署的示例，请问hugegraph-studio应该怎么用docker部署呢？
![image](https://user-images.githubusercontent.com/43004817/124449539-25080100-ddb6-11eb-9708-8c0c054fbb2e.png)
上图中的第二个-p参数是配置hugegraph-studio的吗？（应该不是吧，测试了下，访问不了），如果不是应该怎么配置呢？

另外：
![image](https://user-images.githubusercontent.com/43004817/124449840-6bf5f680-ddb6-11eb-9c1d-e7e544fcbca9.png)
上图中的镜像名是错的，应该是imbajin/hugegraph

**Comment by imbajin** [comment]
多谢反馈, 镜像名那个的确是手误了, 按 `dockerhub` 上的语法就行了, 我也已经修正了 pr 里提到的步骤

> 上图中的第二个 - p 参数是配置 hugegraph-studio 的吗？（应该不是吧，测试了下，访问不了），如果不是应该怎么配置呢？

第二个参数是 `studio` 的, 你可以看看我在上面 3 末尾写的注释.⬇️
>  If you want to start studio, enter the container to start it.

这里的参数只是先把 studio 默认对应的端口开启了, 方便之后启动 studio 后不用再重启容器. 你参考步骤2(可选) 自己进入容器内, 然后启动 studio 就可以了.

**Comment by s348268281** [comment]
> > 上图中的第二个 - p 参数是配置 hugegraph-studio 的吗？（应该不是吧，测试了下，访问不了），如果不是应该怎么配置呢？
> 
> 第二个参数是 `studio` 的, 你可以看看我在上面 3 末尾写的注释.⬇️
> 
> > If you want to start studio, enter the container to start it.
> 
> 这里的参数只是先把 studio 默认对应的端口开启了, 方便之后启动 studio 后不用再重启容器. 你参考步骤2(可选) 自己进入容器内, 然后启动 studio 就可以了.
> 
> 多谢反馈, 镜像名那个的确是手误了, 当时手敲只是想给一个大概的参考, 刚也已经修正了

感谢回复，我去试试。

**Comment by s348268281** [comment]
> > > 上图中的第二个 - p 参数是配置 hugegraph-studio 的吗？（应该不是吧，测试了下，访问不了），如果不是应该怎么配置呢？
> > 
> > 
> > 第二个参数是 `studio` 的, 你可以看看我在上面 3 末尾写的注释.⬇️
> > > If you want to start studio, enter the container to start it.
> > 
> > 
> > 这里的参数只是先把 studio 默认对应的端口开启了, 方便之后启动 studio 后不用再重启容器. 你参考步骤2(可选) 自己进入容器内, 然后启动 studio 就可以了.
> > 多谢反馈, 镜像名那个的确是手误了, 当时手敲只是想给一个大概的参考, 刚也已经修正了
> 
> 感谢回复，我去试试。

麻烦再问下，我想挂载数据库和日志的目录，请问应该挂载哪两个目录呢？hugegraph-loader可以在容器里启动吗？

**Comment by s348268281** [comment]
> > 上图中的第二个 - p 参数是配置 hugegraph-studio 的吗？（应该不是吧，测试了下，访问不了），如果不是应该怎么配置呢？
> 
> 第二个参数是 `studio` 的, 你可以看看我在上面 3 末尾写的注释.⬇️
> 
> > If you want to start studio, enter the container to start it.
> 
> 这里的参数只是先把 studio 默认对应的端口开启了, 方便之后启动 studio 后不用再重启容器. 你参考步骤2(可选) 自己进入容器内, 然后启动 studio 就可以了.
> 
> 多谢反馈, 镜像名那个的确是手误了, 当时手敲只是想给一个大概的参考, 刚也已经修正了

麻烦再问下，我想挂载数据库和日志的目录，请问应该挂载哪两个目录呢？hugegraph-loader可以在容器里启动吗？

**Comment by imbajin** [comment]
> 麻烦再问下，我想挂载数据库和日志的目录，请问应该挂载哪两个目录呢？hugegraph-loader 可以在容器里启动吗？

1. 挂载目录持久化这, 我默认在镜像里挂载了 `/root` 目录, 也就是说删除容器后宿主机还有持久化. 至于你问的具体位置, 都在 server 的 `rocksdb-data` 目录 和 `logs` 目录下, 简单起见挂整个 server 所在路径更简单.
2. 可以在同一容器内启动的, 但是根据容器化的推荐组织方案, 不太建议在一个容器内起很多服务, 最好是解耦拆开. 免得一挂全挂了. hugegraph 的组件基本都是无状态的, 没有特殊的地方, 当普通应用(进程)看就行, 至于容器相关实践可以自行查阅一下

**Comment by s348268281** [comment]
> > 麻烦再问下，我想挂载数据库和日志的目录，请问应该挂载哪两个目录呢？hugegraph-loader 可以在容器里启动吗？
> 
> 1. 挂载目录持久化这, 我默认在镜像里挂载了 `/root` 目录, 也就是说删除容器后宿主机还有持久化. 至于你问的具体位置, 都在 server 的 `rocksdb-data` 目录 和 `logs` 目录下, 简单起见挂整个 server 所在路径更简单.
> 2. 可以在同一容器内启动的, 但是根据容器化的推荐组织方案, 不太建议在一个容器内起很多服务, 最好是解耦拆开. 免得一挂全挂了. hugegraph 的组件基本都是无状态的, 没有特殊的地方, 当普通应用(进程)看就行, 至于容器相关实践可以自行查阅一下

好的，感谢！
