### ISSUE TITLE
[Question] 关于索引的一些疑惑

### ISSUE THREAD

**Issue by s348268281** [hugegraph/hugegraph#1539]
### Problem Type (问题类型)

others (please edit later)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: latest

### Your Question (问题描述)

1. gremlin可以使用主键索引策略，那主键会有唯一约束吗？是否还需要创建唯一索引？
2. 看之前的提问里有回答说创建了唯一索引不支持查询，还需要创建二级索引，最新版依然一样吗？
3. 我想使用自己的id，以name为主键，在指定了name为主键情况下，还可以创建id属性，导入数据吗？
4. 可以创建组合索引吗？类似`schema.indexLabel("xx").onV("xx").by("xx","xx").secondary().ifNotExist().create()`的写法。

**Comment by imbajin** [comment]
依次回复一下:
1. gremlin 可使用主键索引是啥意思? 可以给一下具体的单词描述, 我们似乎没有主键索引这个说法..索引和 gremlin 应该也没有直接关联才对. 如果你说的是创建 vertexLabel 设置的 primaryKey (属性主键模式), 那你需要保证选择的属性值唯一, 此时同样的 vid 会被覆盖. 至于是否需要唯一索引, 你可以看一下之前 issue 里唯一索引使用场景的描述, 看是否需要
2. uniqIndex 是支持查询的, 你说的是应该是之前反馈的 bug(有标记), 修复后会关闭 issue, 可以关注后续, 至于它和二级索引的功能并不相同, 你可以搜一下 Huge 中各种索引的区别和使用场景对比一下
3. Graph 里没有主键这个抽象的说法, 很容易有语义误解, 还麻烦用具体例子描述一下, `id`名字的属性现在是允许创建的, 可以自己试试就知道了. 其他的地方需要举例一下
4. 据我所知应该不能这样写... 也不推荐这样做

**Comment by s348268281** [comment]
> 依次回复一下:
> 
> 1. gremlin 可使用主键索引是啥意思? 可以给一下具体的单词描述, 我们似乎没有主键索引这个说法..索引和 gremlin 应该也没有直接关联才对. 如果你说的是创建 vertexLabel 设置的 primaryKey (属性主键模式), 那你需要保证选择的属性值唯一, 此时同样的 vid 会被覆盖. 至于是否需要唯一索引, 你可以看一下之前 issue 里唯一索引使用场景的描述, 看是否需要
> 2. uniqIndex 是支持查询的, 你说的是应该是之前反馈的 bug(有标记), 修复后会关闭 issue, 可以关注后续, 至于它和二级索引的功能并不相同, 你可以搜一下 Huge 中各种索引的区别和使用场景对比一下
> 3. Graph 里没有主键这个抽象的说法, 很容易有语义误解, 还麻烦用具体例子描述一下, `id`名字的属性现在是允许创建的, 可以自己试试就知道了. 其他的地方需要举例一下
> 4. 据我所知应该不能这样写... 也不推荐这样做

感谢解答，受教了！

**Comment by s348268281** [comment]
> 依次回复一下:
> 
> 1. gremlin 可使用主键索引是啥意思? 可以给一下具体的单词描述, 我们似乎没有主键索引这个说法..索引和 gremlin 应该也没有直接关联才对. 如果你说的是创建 vertexLabel 设置的 primaryKey (属性主键模式), 那你需要保证选择的属性值唯一, 此时同样的 vid 会被覆盖. 至于是否需要唯一索引, 你可以看一下之前 issue 里唯一索引使用场景的描述, 看是否需要
> 2. uniqIndex 是支持查询的, 你说的是应该是之前反馈的 bug(有标记), 修复后会关闭 issue, 可以关注后续, 至于它和二级索引的功能并不相同, 你可以搜一下 Huge 中各种索引的区别和使用场景对比一下
> 3. Graph 里没有主键这个抽象的说法, 很容易有语义误解, 还麻烦用具体例子描述一下, `id`名字的属性现在是允许创建的, 可以自己试试就知道了. 其他的地方需要举例一下
> 4. 据我所知应该不能这样写... 也不推荐这样做

1.![image](https://user-images.githubusercontent.com/43004817/125383840-a3722d80-e3ca-11eb-99ad-dbc7d408185e.png)
我看文档里说，可以建立复合索引呀，难道不是我上面4举例的那种写法吗？不是的话应该怎么写呢？
文档例子中也有类似写法：
![image](https://user-images.githubusercontent.com/43004817/125384196-21cecf80-e3cb-11eb-88cb-87acfdb8d7e1.png)

2.我还想问下，属性主键模式无论加在哪个属性，在导入数据编写数据源映射文件时，vertices的id都必须为null吗？
比如：我有user顶点有id，name属性，想使用自定义的id列作为id，创建U顶点语句如下，数据源映射文件（2.0版本）的id还可以指定csv中的id列吗？
schema.vertexLabel("U").properties("id","name").primaryKeys("name").ifNotExist().create();时，
struct.json必须写为：
 "vertices": [
        {
          "label": "U",
          "skip": false,
          "id": null,    # 这里必须为null吗，还是可以指定“id”列
          "unfold": false,
          "field_mapping": {},
          "value_mapping": {},
          "selected": [],
          "ignored": [],
          "null_values": [
            ""
          ],

**Comment by imbajin** [comment]
第一个更新更正了, 之前误解了意思... 没仔细看语句, 以为你要把多种不同类型的索引一起创建..

第二个 `schema.json` 文件里的 `id` 我没记错的话好像不是一个意思把, 那个是 v2.0版特有的标识? (麻烦你看下 loader 文档确认一下, 我记得有提过)

然后它跟主键模式应该也没有啥关系, 如果查阅了 loader 的文档 + 测试后还是存疑, 可以直接在 loader 的地方提相关 issue
这样分类更清晰也方便其他同学参考

**Comment by s348268281** [comment]
> 第一个更新更正了, 之前误解了意思... 没仔细看语句, 以为你要把多种不同类型的索引一起创建..
> 
> 第二个 `schema.json` 文件里的 `id` 我没记错的话好像不是一个意思把, 那个是 v2.0版特有的标识? (麻烦你看下 loader 文档确认一下, 我记得有提过)
> 
> 然后它跟主键模式应该也没有啥关系, 如果查阅了 loader 的文档 + 测试后还是存疑, 可以直接在 loader 的地方提相关 issue
> 这样分类更清晰也方便其他同学参考

好的，感谢回复，我试验后给您回复
