### ISSUE TITLE
choose...option... 语句返回问题

### ISSUE THREAD

**Issue by baibingzhi** [hugegraph/hugegraph#154]
gremlin语句：
 g.V().hasLabel('businessApply').has("serialNo","12***12").choose(values('businessTerm')).option(3, values('businessTerm')).option(1,constant('NNLL'));

 Expected behavior 期望表现
  根据库中数据应该返回 3

Actual behavior 实际表现
  返回EMPTY

Schema: 元数据结构
   vertexLabel: businessApply
   primaryKey: serialNo ( string类型 ) 
   properties: businessTerm ( double 类型 ) 

Specifications of environment 环境信息
hugegraph version: v0.7.4
operating system: @@CentOS
hugegraph backend: memory

备注：
  语义大致相同的choose语句可以正常返回3   g.V().hasLabel('businessApply').has("serialNo","12***12").choose(values('businessTerm').is(3),values('businessTerm'),constant('NNLL'))

**Comment by javeme** [comment]
由于是double类型的属性，所以需要使用double的条件：
option(**(double)** 3, values('businessTerm'))
