### ISSUE TITLE
[Question] 顶点标签未加索引报错

### ISSUE THREAD

**Issue by s348268281** [hugegraph/hugegraph#1542]
### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: lastest
- OS:Centos 7.x 
- Data Size:  200w vertices, 9000w edges 

### Your Question (问题描述)

我有顶点，label为’U‘，有BSch和BYear属性，并且为BSch，BYear创建了组合索引：schema.indexLabel("UBSchBYear").onV("U").by("BSch","BYear").secondary().ifNotExist().create();

我想查询BSch=xxx，BYear=xxx的顶点，查询语句如下：

g.V().hasLabel('U').and(has('BSch',16102),has('BYear',2006))

报错：Don't accept query based on properties [BSch, BYear] that are not indexed in label 'U', may not match secondary condition

但我看文档没找到还能给顶点标签加索引的方法？

我尝试换个语法：
g.V().filter {it.get().properties('BSch') == 16102}.filter {it.get().properties('BYear') == 2006}.limit(10)
但报错：Too many records(must <= 800000) for the query: Query for VERTEX
我看之前的回答说这个问题修复了，但我的还存在这种问题，我的huge是在docker里运行的，studio也是，我在容器里没找到studio相关的版本信息，所以我也不知道容器里用的studio是哪个版本的，是否修复了limit这个问题。

我又尝试了如下写法：
g.V().hasLabel('U').values('BSch').is(eq(16102)).values('BYear').is(eq(2006)).limit(10)
报错：Too many records(must <= 800000) for the query: Query for VERTEX where id in [0, 1, 6, 8, 1029, 1213, 1328.......

尝试：g.v().has('BSch',16102).has('BYear',2006).limit(10)
报错：
![image](https://user-images.githubusercontent.com/43004817/125738039-e8ce5f20-a29d-4432-a0d8-0005b2197fb3.png)

**Comment by s348268281** [comment]
> ### Problem Type (问题类型)
> _No response_
> 
> ### Before submit
> * [x]  我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题
> 
> ### Environment (环境信息)
> * Server Version: lastest
> * OS:Centos 7.x
> * Data Size:  200w vertices, 9000w edges
> 
> ### Your Question (问题描述)
> 我有顶点，label为’U‘，有BSch和BYear属性，并且为BSch，BYear创建了组合索引：schema.indexLabel("UBSchBYear").onV("U").by("BSch","BYear").secondary().ifNotExist().create();
> 
> 我想查询BSch=xxx，BYear=xxx的顶点，查询语句如下：
> 
> g.V().hasLabel('U').and(has('BSch',16102),has('BYear',2006))
> 
> 报错：Don't accept query based on properties [BSch, BYear] that are not indexed in label 'U', may not match secondary condition
> 
> 但我看文档没找到还能给顶点标签加索引的方法？
> 
> 我尝试换个语法：
> g.V().filter {it.get().properties('BSch') == 16102}.filter {it.get().properties('BYear') == 2006}.limit(10)
> 但报错：Too many records(must <= 800000) for the query: Query for VERTEX
> 我看之前的回答说这个问题修复了，但我的还存在这种问题，我的huge是在docker里运行的，studio也是，我在容器里没找到studio相关的版本信息，所以我也不知道容器里用的studio是哪个版本的，是否修复了limit这个问题。
> 
> 我又尝试了如下写法：
> g.V().hasLabel('U').values('BSch').is(eq(16102)).values('BYear').is(eq(2006)).limit(10)
> 报错：Too many records(must <= 800000) for the query: Query for VERTEX where id in [0, 1, 6, 8, 1029, 1213, 1328.......
> 
> 尝试：g.v().has('BSch',16102).has('BYear',2006).limit(10)
> 报错：
> ![image](https://user-images.githubusercontent.com/43004817/125738039-e8ce5f20-a29d-4432-a0d8-0005b2197fb3.png)

最终用
g.V().where(__.and(values('BSch').is(16102),values('BYear').is(2006))).values('name').limit(1000)
查出来了，但上述错误原因犹未可知

**Comment by imbajin** [comment]
你用的 studio 是19年的版本, 很早就停止维护了更新了, 后续我们会提供 docker 化的新前端 hubble (下一个大版本发布时候)

至于你说的组合索引, 可能是由于使用了 `hasLabel()` 这个本来就走了一层 label 的索引(只不过是系统默认开启, 所以你没有感知) 
然后等于先走了一次 label 的索引的前提下, 有走了一层二级索引, 问题类似之前有个 issue 里提过的. 

后续这里会一并确认优化一下, 感谢反馈

**Comment by s348268281** [comment]
> 你用的 studio 是19年的版本, 很早就停止维护了更新了, 后续我们会提供 docker 化的新前端 hubble (下一个大版本发布时候)
> 
> 至于你说的组合索引, 可能是由于使用了 `hasLabel()` 这个本来就走了一层 label 的索引(只不过是系统默认开启, 所以你没有感知)
> 然后等于先走了一次 label 的索引的前提下, 有走了一层二级索引, 问题类似之前有个 issue 里提过的.
> 
> 后续这里会一并确认优化一下, 感谢反馈

感谢大佬百忙中的解答
