### ISSUE TITLE
[Question] 如何实现禁用某些gremlin语法

### ISSUE THREAD

**Issue by chencjiajy** [hugegraph/hugegraph#1547]
### Problem Type (问题类型)

others (please edit later)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.2
- Backend: Hbase, HDD 

### Your Question (问题描述)

向hugegraph server [发送gremlin语句请求](https://hugegraph.github.io/hugegraph-doc/clients/restful-api/gremlin.html)
官方接口支持所有有效gremlin查询，如果想禁止某些语法的使用，比如不支持drop操作，有没有地方配置呢？或者有什么好的建议吗？（目前能想到的方案是用正则匹配来过滤掉一些想禁止的语法）

**Comment by imbajin** [comment]
> 如果想禁止某些 gremlin 语法的使用，比如不支持 drop 操作，有没有地方配置呢？或者有什么好的建议吗？（目前能想到的方案是用正则匹配来过滤掉一些想禁止的语法）

1. gremlin 官方是否支持禁用某些语法这个不太确定(貌似没看到), 你可以看看最新版文档或者tinkerpop 的 issue 确认一下
2. 目前内部的 api 是不能直接禁用 gremlin 语句的, 修改 tinkerpop 源码可以达到你说的效果, 但是不太建议
3. 比较推荐的做法是开启权限管理, 可以细粒度到 CRUD (增删改查)整个权限控制, 这样你调用 `drop()` 也会触发权限检查和记录

**Comment by chencjiajy** [comment]
谢谢！
