### ISSUE TITLE
[Question] server 访问提示 401 需要鉴权

### ISSUE THREAD

**Issue by hunanxinhua** [hugegraph/hugegraph#1551]
### Problem Type (问题类型)

rest-api (结果不合预期)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.x
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

根据文档部署好HugeGraph-Server，通过curl访问，提示401（You must authenticate to access this dashboard），需要怎么处理，我看文档说默认是关闭认证的

**Comment by imbajin** [comment]
首先权限的确是默认关闭的, 开启需要修改配置, 你可以对照开启权限那确认自己的配置是无权限版本.
确认你的配置文件无误, 包括 `gremlin-server`, `hugegraph`, `rest-server` 三个都有影响

如果确认了, 请提供 curl 或用 http 直接访问基本的 `versions` api 的完整返回结果, `401` 如果真的是鉴权失败, 那会有额外提示信息, 另外请补充你的 server 版本, 现在提供的信息过少

**Comment by hunanxinhua** [comment]
> 首先权限的确是默认关闭的, 开启需要修改配置, 你可以对照开启权限那确认自己的配置是无权限版本.
> 确认你的配置文件无误, 包括 `gremlin-server`, `hugegraph`, `rest-server` 三个都有影响
> 
> 如果确认了, 请提供 curl 或用 http 直接访问基本的 `versions` api 的完整返回结果, `401` 如果真的是鉴权失败, 那会有额外提示信息, 另外请补充你的 server 版本, 现在提供的信息过少

**Comment by hunanxinhua** [comment]
hugegraph-server版本是hugegraph-0.11.2，目前我只修改了rest-server.properties文件的restserver.url和gremlinserver.url两个参数，先执行sh bin/init-store.sh，然后执行sh bin/start-hugegraph.sh 这个命令
![image](https://user-images.githubusercontent.com/8371454/127615084-94e30d00-013c-4cad-a1eb-9fda35b99ebf.png)，执行这个命令就报401。然后我部署完HugeGraph-Studio，在页面填入命令就报You must authenticate to access this dashboard

**Comment by hunanxinhua** [comment]
hugegraph-studio的版本是hugegraph-studio-0.11.0

**Comment by hunanxinhua** [comment]
![image](https://user-images.githubusercontent.com/8371454/127615716-1a3bece6-62d8-49c0-ac1c-eb8641d3012a.png)
这个是curl命令

**Comment by imbajin** [comment]
你能试试用 postman 类标准的 http 放松端试试么? curl 要带一下参数, http response 里有补充的返回信息

你直接用专门的 HTTP 发送程序就能更简单看.  

另外是问题已经解决了么?

**Comment by hunanxinhua** [comment]
嗯嗯，非常感谢，问题已经解决了，我自己的问题
