### ISSUE TITLE
[Question] “com.baidu.hugegraph.config.HugeConfig”的对应Java文件缺失

### ISSUE THREAD

**Issue by liuyuanOUC** [hugegraph/hugegraph#1553]
### Problem Type (问题类型)

others (please edit later)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

无

### Your Question (问题描述)

部分Java文件导入了`com.baidu.hugegraph.config.HugeConfig`类，但在源代码中未查找到`HugeConfig.java`文件

### Vertex/Edge example (问题点 / 边数据举例)

```javascript
无
```

**Comment by imbajin** [comment]
详细一点的问题上下文和相关报错贴图可以给一下么...
组件版本, 具体什么类, 复现方式之类的

**Comment by liuyuanOUC** [comment]
@imbajin 您好，感谢您的及时回复。

我并不是软件开发人员，而是正在研究软件配置类型的一名研究生。

我发现`com.baidu.hugegraph.config.HugeConfig`类应该是HugeGraph的一个配置类型，所以想要进一步查看其源代码。但当我想要在代码目录定位到该类所在的源文件`HugeConfig.java`时，发现并没有该文件，并且点击类名`HugeConfig`时，只能跳转到`HugeConfig.class`文件。进一步检查maven依赖后发现，`HugeConfig`类可能位于`hugegraph-common`中，但`hugegraph-common`并没有配置在`pom.xml`中的`modules`标签中。请问我的猜测是否正确，此外`hugegraph-common`是否能开源呢？

感谢！

**Comment by imbajin** [comment]
首先你打开项目的方式可以改一下, 改成 `graph` 下包含所有 hugegraph 相关的模块, 这样你就不会存在无法直接跳转 common 模块的问题了, 如下图所示:
![image](https://user-images.githubusercontent.com/17706099/127822535-65ea8c6e-515e-4465-b2b8-6b1137c993ef.png)


至于单独解耦是因为方便各模块独立管理

**Comment by liuyuanOUC** [comment]
@imbajin  感谢！
