### ISSUE TITLE
[Question] StandardAuthenticator 用户认证模式如何找回admin 密码

### ISSUE THREAD

**Issue by chencjiajy** [hugegraph/hugegraph#1555]
### Problem Type (问题类型)

others (please edit later)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.2
- Backend: HBASE, HDD

### Your Question (问题描述)

StandardAuthenticator 用户认证模式如何找回admin 密码

目前设置StandardAuthenticator用户认证之后，首次初始化图的时候，会弹出输入admin命令的交互信息，因为没有二次认证，如果在输入的时候不小心输错了，就无法使用server的api接口了。

api 文档中[8.2.3修改用户接口](https://hugegraph.github.io/hugegraph-doc/clients/restful-api/auth.html) 修改admin，需要知道admin密码，所以无法使用这个接口来召回admin密码

如果hugegraph 有多个图，暂时的解决办法是：如果不小心输错了，就把rest-server.properties文件中的`auth.graph_store`换一个图存储，再重新初始化输入admin的密码。

**Comment by imbajin** [comment]
目前应该没有简单的办法, 如果是 rocksdb 类存储, 可以简单直接删除 db 文件重新初始化. Hbase/C* 这种稍麻烦一点, 也可以写个脚本一键删 tables, 重新 init.
