### ISSUE TITLE
[Question] Kneighbor 高级版http://localhost:8080/graphs/hugegraph_test/traversers/kout报405错误

### ISSUE THREAD

**Issue by fancy-dawning** [hugegraph/hugegraph#1565]
### Problem Type (问题类型)

rest-api (结果不合预期)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.x
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

Kneighbor 高级版http://localhost:8080/graphs/hugegraph_test/traversers/kout报405错误

**Comment by imbajin** [comment]
rest-api 相关问题, 请在 `Vertex/Edge example (问题点 / 边数据举例)` 给出具体发送的查询语句

并且给出具体的发送方式, 然后 `405` 相关报错一般说明你 `GET/POST/PUT/DELETE` 没有选择正确, 历史 issues 也有类似问题, 不知道是否确认过, 希望有更多具体的反馈信息

**Comment by javeme** [comment]
@fancy-dawning 请确保http请求头中包含“content-type”是“application/json”。
