### ISSUE TITLE
[Question] hugeclient连接失败, 提示 The property key 'date' has existed 

### ISSUE THREAD

**Issue by lomodays207** [hugegraph/hugegraph#1568]
### Problem Type (问题类型)

gremlin (结果不合预期)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.2
- Backend: Mem 1 nodes, HDD 

![image](https://user-images.githubusercontent.com/16081650/129121057-a513cd7a-a2d1-4bc9-b102-4b8a0a3cab5a.png)

### Your Question (问题描述)

![image](https://user-images.githubusercontent.com/16081650/129121189-9c01a95c-b174-4517-b728-851a03feead9.png)

如上图所示，在完全新的工程里面，使用SingleExample 执行示例代码，执行到 “date” 属性的时候出现报错，
 client 版本为1.9.6 ，麻烦帮忙看看是否是环境问题，非常感谢~

**Comment by imbajin** [comment]
> 在完全新的工程里面，使用SingleExample 执行示例代码，执行到 “date” 属性的时候出现报错，看看是否是环境问题

多谢详细的截图和基本信息, 从提示和你给的信息来看, 你应该排除以下可能:
1. 首先通过 HTTP-api, 或者 client 的 `getProperties` 获取当前图的所有属性, 确认 `date` 是的确不存在的
2. 环境问题的话, 排除一下 `fastjson` 这样的冲突依赖, 其他是没啥的 (之前 issue 有提到过)

**Comment by lomodays207** [comment]
@imbajin  非常感谢，根据您的建议，已经知道原因了。 通过 HTTP-api, 获取当前图的所有属性存在 `date` 属性，跟字段类型跟Java 代码（asDate）中的类型不一致，导致 ifNotExist() 判断不生效。

![image](https://user-images.githubusercontent.com/16081650/129141493-fc2a8785-c2b4-4dd2-8a59-6bf46c4886fe.png)

**Comment by imbajin** [comment]
嗯呐没事, 这也是当时 issue 里特意补充这段的原因, 提供完整的 schema 信息可以排除很多问题

![image](https://user-images.githubusercontent.com/17706099/129146952-b9a94e58-f18a-487c-9a02-411ad3e2df48.png)
