### ISSUE TITLE
union 语句中无法识别日期

### ISSUE THREAD

**Issue by baibingzhi** [hugegraph/hugegraph#157]
g.V().has("createTime",gt('2018-01-10 01:01:01.000')).count()
g.V().union(has("createTime",gt('2018-01-10 01:01:01.000')).count())

Expected behavior 期望表现
两条语句都正常返回相同条目数

Actual behavior 实际表现
第二条语句报Error 
java.lang.String cannot be cast to java.util.Date

Vertex/Edge summary 数据量
 loaded vertices amount: 10k

Specifications of environment 环境信息
hugegraph version: v0.7.4
operating system: @@CentOS
hugegraph backend: memory

**Comment by Linary** [comment]
#147
