### ISSUE TITLE
[Question] 当 edge 有多对 source vertex 和 target vertex ，在HugeGraph 中是否可以支持

### ISSUE THREAD

**Issue by lomodays207** [hugegraph/hugegraph#1570]
### Feature Description (功能描述)

比如有Tomcat、Weblogic 、 Linux 这三类顶点，想用图数据库表示如下关系：

Tomcat **运行在** Linux 上 ， Weblogic **运行在** Linux 上， 而 **运行在** 这个edge 只能有一对 source vertex和target vertex , 

麻烦问下有啥其他方式可以实现不？

**Comment by imbajin** [comment]
你说的意思其实之前 issue 里是有问过的, 比较简单的方式是, 把边名拆成多个

`run` 作为一个动作/关系, 拆成以下三类不同的边名:
1. a-run-d
2. b-run-d
3. c-run-d

这样的好处有两个:
1. 想查询某类 run 的点边还能避免扫所有 run 的数据
2. 如果每类 run 的边都有不同的 sortkey 或属性, 还能各自定义

当然这样的弊端是设计起来比较冗余, 易用性降低了, 如果要查所有的 run, 那就需要把三类边一起放进去 (性能上来说其实没啥影响)

PS: issue 的`[Question]` 或 `[Bug]` 标签不用移除, 方便外面整体查看, 也有个简单分类~
