### ISSUE TITLE
[Question] api能设置顶点的颜色、大小、形状吗

### ISSUE THREAD

**Issue by tjthink** [hugegraph/hugegraph#1571]
### Problem Type (问题类型)

rest-api (结果不合预期)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.2
- Backend: RocksDB x nodes, HDD or SSD 
- OS: 8 CPUs, 16 G RAM, Centos 7.x 
- Data Size:  100Wvertices, 1000W edges

### Your Question (问题描述)

请问如果自己在画图，在web上显示，api能设置顶点的颜色、大小、形状、边的颜色吗

**Comment by imbajin** [comment]
ahh? 其实没太理解, 是问 server 的 api 么, 它只是单纯返回一个 json 数据呢

你说的颜色之类的是前端(hubble/studio)可视化渲染的效果, 跟后端其实没有任何关系的, 所以 rest-api 自然也不会有这些

**Comment by tjthink** [comment]
> ahh? 其实没太理解, 是问 server 的 api 么, 它只是单纯返回一个 json 数据呢
> 
> 你说的颜色之类的是前端(hubble/studio)可视化渲染的效果, 跟后端其实没有任何关系的, 所以 rest-api 自然也不会有这些

就是我们准备自己画图，想要顶点可以自定义形状、颜色、大小
