### ISSUE TITLE
[Question] 如何根据顶点某个属性的长度对顶点进行过滤查询

### ISSUE THREAD

**Issue by Tea996** [hugegraph/hugegraph#1572]
### Problem Type (问题类型)

gremlin (结果不合预期)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.2
- Backend: cassandra

### Your Question (问题描述)

需要根据顶点上某个属性的字段长度对顶点进行过滤，请问目前有restful接口或者gremlin语句做到这些吗

**Comment by Tea996** [comment]
还有一个问题，能否根据顶点上某个属性值是否含有某个关键字进行过滤查询？

**Comment by imbajin** [comment]
1. 根据属性长度(length) 过滤属性这个不清楚有没有内置 step, 估计没有吧, 你可以搜一下 `filter()` 类似的语法有没, 另外它就算有也是先把所有读出来然后内存过滤, 数据不大你也可以上层自己做
2. 第二个可以, 搜索历史 issue, 全文索引, 或关键字都有类似的案例和用法
