### ISSUE TITLE
[Question] k8s部署Cassandra 后端图时, 重启Cassandra后IP变化无法自动重连原有域名

### ISSUE THREAD

**Issue by Ckuangf** [hugegraph/hugegraph#1574]
### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.x
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

我使用的是cassandra作为存储后端，正常情况下，配置cassandra的地址之后，cassandra就算重启了，hugegraph也会根据这个地址去进行重连，但是由于cassandra使用的是k8s的形式部署的，每次重启之后，域名不会改变，但是ip会变化，而查看日志发现，hugegraph 的重连好像会将域名解析成ip之后通过ip进行连接，导致连接失败。
因为hugegraph-server中的异常只会抛出无可用节点的异常信息：
![image](https://user-images.githubusercontent.com/31173360/129521652-e80a1a8c-db7e-4ac4-bdc0-548173204003.png)

下面的截图是执行init-store.sh的异常日志，可以看出hugegraph所连接的ip实际上是已经失效的cassandra IP，但是该域名是有效的。
![image](https://user-images.githubusercontent.com/31173360/129521493-a4782c65-e842-4872-a0c1-0359055420f1.png)

**Comment by imbajin** [comment]
> hugegraph 的重连好像会将域名解析成ip之后通过ip进行连接，导致连接失败

我理解 HG 应该只是调用 C* 的 client, 传入你给的域名或者 IP 参数, 具体的解析过程应该是在 C* 自己那边实现的, 你可以追着代码确认一下就知道了.

另外如果是C*缓存的话, 简单的可以试着重启一下 server, 做好一点可以看看 C* 那边是否有这样的 API, 定时flush-cache 一下

**Comment by Ckuangf** [comment]
> > hugegraph 的重连好像会将域名解析成ip之后通过ip进行连接，导致连接失败
> 
> 我理解 HG 应该只是调用 C* 的 client, 传入你给的域名或者 IP 参数, 具体的解析过程应该是在 C* 自己那边实现的, 你可以追着代码确认一下就知道了.
> 
> 另外如果是C_缓存的话, 简单的可以试着重启一下 server, 做好一点可以看看 C_ 那边是否有这样的 API, 定时flush-cache 一下

因为跟的时候，看到的就是最后调用的连接池去连接C*了，连接池的参数应该也是我们自己指定的吧，就想知道目前有没有开放出来相关的配置参数

**Comment by imbajin** [comment]
有开的参数都在 `C*Options` 里能找到, 需要添加额外的可以自己试试, 看看它的 client-api 文档应该就能有, 另外可以在 C* 的官方 issue 问一下这个问题, 我想应该更准确快速

**Comment by Ckuangf** [comment]
> 有开的参数都在 `C*Options` 里能找到, 需要添加额外的可以自己试试, 看看它的 client-api 文档应该就能有, 另外可以在 C* 的官方 issue 问一下这个问题, 我想应该更准确快速

嗯嗯，谢谢
