### ISSUE TITLE
[Bug] HugeGraph could not process Inifnity/NaN value in float/double 

### ISSUE THREAD

**Issue by zhengyingying** [hugegraph/hugegraph#1575]
### Bug Type (问题类型)

gremlin (结果不合预期)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.2
- Backend: Memory 
- OS: 10 CPUs, 125 G RAM, Centos 7.x 
- Data Size:  100 vertices, 200 edges 

### Expected & Actual behavior (期望与实际表现)

**Expected Behavior**
We expected to write `Double.Infinity` value into HugeGraph. 

**Current Behavior**

An exception was thrown.
```
class java.lang.IllegalArgumentException: Invalid property value 'Infinity' for key 'price', expect a value of type Double, actual type String
at com.baidu.hugegraph.exception.ServerException.fromResponse(ServerException.java:47)
at com.baidu.hugegraph.client.RestClient.checkStatus(RestClient.java:93)
at com.baidu.hugegraph.rest.AbstractRestClient.post(AbstractRestClient.java:198)
at com.baidu.hugegraph.rest.AbstractRestClient.post(AbstractRestClient.java:178)
at com.baidu.hugegraph.api.graph.VertexAPI.create(VertexAPI.java:58)
at com.baidu.hugegraph.driver.GraphManager.addVertices(GraphManager.java:96)
```

**Steps to Reproduce**
```
hugegraph.schema().propertyKey("name").asText().ifNotExist().create();
hugegraph.schema().propertyKey("price").asDouble().ifNotExist().create();

// vertex
hugegraph.schema().vertexLabel("person").properties("name").nullableKeys("name").create();
hugegraph.schema().indexLabel("personbyname").onV("person").by("name").shard().ifNotExist().create();
hugegraph.schema().vertexLabel("product").properties("name","price").nullableKeys("name","price").create();
hugegraph.schema().indexLabel("productbyname").onV("product").by("name").shard().ifNotExist().create();
hugegraph.schema().indexLabel("productbyprice").onV("product").by("price").shard().ifNotExist().create();

GraphManager graph = hugegraph.graph();

/** create graph data */
Vertex nancy = new Vertex("person").property("name", "nancy");
Vertex product1 = new Vertex("product").property("name", "product1").property("price", 3.254615);
Vertex product2 = new Vertex("product").property("name", "product2").property("price", new Double(1029.98 / 0));

graph.addVertices(Arrays.asList(nancy, product1, product2));
```

**Comment by imbajin** [comment]
u define a pk `price` with `Double` type, however what dose `Double.Infinity` mean?

or u can paste the phrase like `xx.property("price", 3.254615)` for us to understand

**Comment by zhengyingying** [comment]
Thanks for your advice. Double.Infinity value means an infinite value of type Double. It is a special constant which is equal to the value returned by Double.longBitsToDouble (0x7ff0000000000000L). When the divisor is equal to 0, the result returns the Double.Infinity value.

In our case, new Double(1029.98 / 0) is the Double.Infinity value. We can do this in both JanusGraph and Neo4j-Gremlin but not in HugeGraph. That’s why we think HugeGraph could not process Double.Inifnity value.

**Comment by imbajin** [comment]
Get it, the reason is we skip `infinite` & `NaN` value before

And consider support it soon.

**Comment by imbajin** [comment]
@zhengyingying, hi, I submit a PR for this issues, u can cherry-pick it or copy the [DataType](https://github.com/hugegraph/hugegraph/blob/6e28e63981c13e58912d7ad12717d2df5c095fd0/hugegraph-core/src/main/java/com/baidu/hugegraph/type/define/DataType.java) code directly, then test in client & your cases to test if it's suitable.

Hope to get your reply & suggestion. THX

**Comment by zhengyingying** [comment]
@imbajin Thanks for your reply. We will test it in our cases.

**Comment by imbajin** [comment]
Any response for the linked PR? (Need to ensure it's suitable for user to use)

Wait for your test result, THX ~ ⏲️

**Comment by imbajin** [comment]
Due to long time with no response, we merge the linked pr first now.

Looking forward to your follow-up feedback on this issue (and close it)
