### ISSUE TITLE
[Question] StandardAuthenticator 用户认证开启后清空auth.graph_store配置的图，用户信息会丢失

### ISSUE THREAD

**Issue by chencjiajy** [hugegraph/hugegraph#1576]
### Problem Type (问题类型)

struct / logic (架构 / 逻辑设计问题)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.2
- Backend: HBase, HDD 
- OS: Centos 7.x 

### Your Question (问题描述)

如[认证配置](https://hugegraph.github.io/hugegraph-doc/config/config-authentication.html) 所述，开启StandardAuthenticator认证需要配置`auth.graph_store`用来存储用户信息，测试了如果使用hugegraph-tools将配置的图清空，用户信息会丢失，这样就必须有一个图专门用来存储用户信息，除非确定这个图没有清空的需求。

请问`auth.graph_store`配置的图不能被清空，是符合设计预期的吗？

**Comment by imbajin** [comment]
是符合的, 不过之前的文档还没详细介绍完整的 auth-server 结构设计, 其实最佳的实现是单独一个进程存储权限的信息, 然后多个 `graph_server` 可以连到一个 `auth-server` 进程, 就不会有你说的那个情况了

如果是单进程的情况下, 你也可以启动两个图, 另一个交`auth_graph`, 然后不清空它就行了.
