### ISSUE TITLE
[Bug] Can not create more than one edge of same label between two vertexes

### ISSUE THREAD

**Issue by Yicheng-Wang** [hugegraph/hugegraph#1577]
### Bug Type (问题类型)

gremlin (结果不合预期)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.2
- Backend: memory 
- OS: 16 CPUs, 64 G RAM, windows10 WSL 
- Data Size:  200 vertices, 100 edges 

#### Expected behavior
We expecte to create two or more edges of same label between two vertexes, just as we did in other gremlin-based Graph Databases.

#### Actual behavior
When we create the second edge, it would overwrite the first edge we created, for the edge ID of the second edge generated automatically by HugeGraph is exactly the same as the that of the first edge. We find that the naming rules of edge ID in HugeGraph is the combination of in/out vertex ID and edge label, which could lead to reduplicated edge ID and cause unsupported reduplicated creation. 

If we try to avoid repetition by modifying the edge ID before we insert the edge into the graph, we get the exception:
```
com.baidu.hugegraph.exception.InvalidOperationException: Not allowed to custom id for edge: '{id=xx, sourceId=xxxx, sourceLabel=xx, targetId=xxxx, targetLabel=xx, label=xx, properties={xx=xxx}}'
	at com.baidu.hugegraph.driver.GraphManager.addEdge(GraphManager.java:214)
```
#### Example to reproduce
```
        hugegraph.schema().propertyKey("name").asText().ifNotExist().create();
        hugegraph.schema().propertyKey("course").asText().ifNotExist().create();
        hugegraph.schema().propertyKey("grade").asInt().ifNotExist().create();

// vertex
        hugegraph.schema().vertexLabel("teacher").properties("name").nullableKeys("name").create();
        hugegraph.schema().vertexLabel("student").properties("name").nullableKeys("name").create();


// edge
        hugegraph.schema().edgeLabel("teach").sourceLabel("teacher").targetLabel("student").properties("course", "grade").ifNotExist().create();

        GraphManager graph = hugegraph.graph();

// create graph data
        Vertex mary = new Vertex("student").property("name", "mary");
        Vertex david = new Vertex("teacher").property("name", "david");

        graph.addVertices(Arrays.asList(mary, david));

        Edge firstcourse = new Edge("teach").source(david).target(mary).property("course","math").property("grade",7);
        Edge secondcourse = new Edge("teach").source(david).target(mary).property("course","physics").property("grade",8);

        Edge addfirst = graph.addEdge(firstcourse);
        Edge addsecond = graph.addEdge(secondcourse);
```
Edge *addfirst* and *addsecond* get the same ID. And if we check the graph, we can only find one edge added.

**Comment by imbajin** [comment]
maybe ensure the current `issues` first, search `sortkey` for keyword, u'll get the answer~ (Also include the specific cases)

**Comment by Yicheng-Wang** [comment]
> maybe ensure the current `issues` first, search `sortkey` for keyword, u'll get the answer~ (Also include the specific cases)

Thank you for the response,  that helps~
