### ISSUE TITLE
[Question] Edge的id生成

### ISSUE THREAD

**Issue by fancy-dawning** [hugegraph/hugegraph#1580]
### Problem Type (问题类型)

others (please edit later)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.x
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

文档中说：EdgeId是由 src-vertex-id + direction + label + sort-values + tgt-vertex-id 拼接而成。这里的direction是具体是怎样得来呢，生成的数据边的id里面direction都是1，但是在官方给的例子中有看到direction为2的情况，比如S1:peter>2>>S2:lop。没有看到相关说明，烦请解答。

**Comment by imbajin** [comment]
in 方向和 both 方向, 目前没有直接使用, 设计上是可以直接支持的.
in 的边(对应你说的序号2), 在图里已经自动做了

**Comment by fancy-dawning** [comment]
所以是序号1：out方向，2：IN方向，3：BOTH方向吗？如果我要根据顶点的id来生成边的id然后去查询边，这里怎么确定生成边的公式src-vertex-id + direction + label + sort-values + tgt-vertex-id 里面的direction呢？

**Comment by fancy-dawning** [comment]
> in 方向和 both 方向, 目前用户层无需直接使用, 图已经自动使用了.
> in 的边(对应你说的序号2), 在图里已经自动做了 (也就是写入一条 A--out-->B 的边, 会自动写入一个 `B<--in--A` 的边)
> 
> 所以用户就无需关心 in 的边了
所以是序号1：out方向，2：IN方向，3：BOTH方向吗？如果我要根据顶点的id来生成边的id然后去查询边，这里怎么确定生成边的公式src-vertex-id + direction + label + sort-values + tgt-vertex-id 里面的direction呢？

**Comment by imbajin** [comment]
可以看看图的存储结构设计 (每个表的, 比如用 mysql 导几个测试数据), 出边只有方向为 out 的边, 入边只有方向为 in 的边.
也就是说只需要区分表, 不用区分方向, 表内是唯一的.
