### ISSUE TITLE
[Question] 关于 server 的高可用实现

### ISSUE THREAD

**Issue by ghostmickey** [hugegraph/hugegraph#1581]
### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.x
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

现在社区版不支持hugegraph-server的高可用，通过启动多个hugegraph-server，在前面加nginx做负载均衡，看到之前的帖子说因为现在缓存是单机的，所以可能在多个节点上查询时会出现数据不一致的可能。那么我有个设想，是不是可以自己做二开，把缓存改成分布式的，比如嵌入式的ignite、hazelcast之类的分布式数据网格来做缓存的话，就可以直接起多个server来做高可用了呢？这样实现会不会有什么问题？

**Comment by imbajin** [comment]
缓存是可以实现一致性的 `0.12` 就可以了, 图目前内置的缓存和后端单独的缓存还是有区别
主要在于缓存的粒度和最小单位不同, 图这层的缓存自然是最贴近查询的.

类似的问题也同于 OS 缓存 vs db存储缓存 vs 图缓存的区别

**Comment by ghostmickey** [comment]
> 缓存是可以实现一致性的 `v0.12` 的 server 就可以了, 图目前内置的缓存和后端单独的缓存还是有区别
> 主要在于缓存的粒度和最小单位不同, 图这层的缓存自然是最贴近查询的.
> 
> 类似的问题也同于 OS 缓存 vs db存储缓存 vs 图缓存的区别

但是0.10和0.11在底层存储的表结构上已经有一些变化了，到了0.12是否还会有变化？对于已有的系统，数据迁移也是一项非常大的工作，所以要在低版本上支持高可用，我说的方案是否可行？

**Comment by imbajin** [comment]
如果要做二开, 那理论上选择就很多了, 也看你们对一致性有多少要求, 就算是低版本, 你也可以把同步缓存的 RPC 模块迁移过去. 也不用迁数据

**Comment by ghostmickey** [comment]
> 如果要做二开, 那理论上选择就很多了, 也看你们对一致性有多少要求, 就算是低版本, 你也可以把同步缓存的 RPC 模块迁移过去. 也不用迁数据

几个版本API变化还是比较大的，序列化类里面很多方法也不一样，直接迁模块估计够呛
为了解决0.10上只有RAM缓存导致频繁Fullgc的问题，我前几天把0.11的off-heap缓存迁到0.10上都折腾了不少功夫。

**Comment by imbajin** [comment]
缓存一致性的保证和底下的 api 倒是没多少耦合, 当然合并大功能自然是少不了费些功夫的. 但是架一个外置缓存同样需要折腾, 还引入了额外组件, 也不会轻的

另外顺便问一下, 堆外缓存的使用效果如何? 特别是大(容量)缓存的情况下 (另外大内存建议使用 g1gc, 启动 server 的时候带上 `-g g1` 参数就可以了

**Comment by ghostmickey** [comment]
目前没有做性能测试，功能试下来没什么问题。ignite嵌入还算比较容易的，基本只要改缓存那部分就行了，backend还是使用hbase不受影响，需要改的大概也就四五个类就搞定了。序列化沿用0.11提供的offcache里面的方式，只是把底层cache改成了ignite。这样缓存不用另外架，是嵌入到server里面起来的，使用ignite的网络发现机制，纯自己写的代码也就300行左右

**Comment by imbajin** [comment]
> 目前没有做性能测试，功能试下来没什么问题
这是说的堆外缓存么? 有空可以简单对比一下

> ignite嵌入还算比较容易的，基本只要改缓存那部分就行了
如果嵌入简单, 也实现了, 可以作为一个类似堆外缓存的可选项, 嵌入到社区版中, 也方便后续代码合并之类, 提交后有兼容问题我们会给建议的~ 😄

**Comment by ghostmickey** [comment]
我先做仔细测试吧，如果没问题再提交
上周开发的时候没注意，schema也有缓存信息的，这周我把schema的缓存也换成分布式的。
schema的缓存还不太一样，因为不能过期。。
