### ISSUE TITLE
[Question] Cassandra的两个配置选项在"CassandraOptions.java"未找到定义。

### ISSUE THREAD

**Issue by liuyuanOUC** [hugegraph/hugegraph#1583]
### Problem Type (问题类型)

configs (配置项 / 文档相关)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

无

### Your Question (问题描述)

阅读源代码时，未找到下图所示Cassdndra的两个选项在源代码中的定义。
![image](https://user-images.githubusercontent.com/27879832/130356469-f788eb19-8ef8-4ad4-97e7-f20d1cd227ef.png)
请问，这个选项是什么意思呢？还是说他们是在CoreOptions中定义的呢？

**Comment by imbajin** [comment]
这个是说通用的图配置里的, 你看看 `hugegraph.properties` 默认的模板文件就知道了.

**Comment by liuyuanOUC** [comment]
@imbajin 多谢！
