### ISSUE TITLE
部署 hugegraph-server 对机器资源有特别的要求吗？

### ISSUE THREAD

**Issue by baibingzhi** [hugegraph/hugegraph#159]
如题，谢谢！

**Comment by javeme** [comment]
视后端存储而定，亿级别规模的图推荐配置如下：
- RocksDB Backend 嵌入式后端：16~32 CPUs，64G+ Memory。注意RocksDB本身占用内存也是hugegraph-server的一部分。磁盘推荐使用SSD。
- Cassandra Backend、HBase Backend等分布式后端：16+ CPUs，32G+ Memory。

**Comment by paddy0914** [comment]
亿级别规模，现在的配置是20 CPUs，128G内存，1.6TB SSD，后端存储RocksDB和HBase选哪种性能更高？

**Comment by javeme** [comment]
@paddy0914 RocksDB后端性能更好，亿级别规模建议选择RocksDB。

**Comment by paddy0914** [comment]
> @paddy0914 RocksDB后端性能更好，亿级别规模建议选择RocksDB。

感谢，看官方文档HugeGraph因为充分利用后端存储的特性，比JanusGraph性能要提升不少且代码结构更清晰，目前正准备上测试看看效果。

**Comment by denghaiai** [comment]
@javeme  这个亿级别是指的顶点数量吗？还是边？

**Comment by cmdares** [comment]
scylla在网上看到的资料，感觉速度爆棚，不知道有没测试一下和rocks对比下关于图的操作性能。

**Comment by denghaiai** [comment]
@javeme  另外 cpu 核数指的是 虚拟cpu 核数吧？

**Comment by javeme** [comment]
> 这个亿级别是指的顶点数量吗？还是边？

@denghaiai 是指顶点+边的总数量。

> 另外 cpu 核数指的是 虚拟cpu 核数吧？

@denghaiai 是指逻辑核数，物理机或虚拟机上均可。

**Comment by javeme** [comment]
> scylla在网上看到的资料，感觉速度爆棚，不知道有没测试一下和rocks对比下关于图的操作性能。

@cmdares 经我们测试，Scylla在图数据库场景中的性能测试并没有比RocksDB快。如果你们进行测试有不一样的结果的话可以把结果反馈到这，谢谢。

**Comment by denghaiai** [comment]
@javeme   你好，你们有没有测试过0.3.1 的janusGraph的性能？ 我们对比过hugegraph和janusGraph，hugegraph主要在检索两个点之间的路径有非常大的优势，优化的比较多。普通的扩线比janusGrpah性能差。

**Comment by javeme** [comment]
> 普通的扩线比janusGrpah性能差。

@denghaiai 如果要求性能的话请尝试使用[3.1.2 K-out API](https://hugegraph.github.io/hugegraph-doc/clients/restful-api/traverser.html)。

**Comment by Ronniexie** [comment]
> 
> 
> @paddy0914 RocksDB后端性能更好，亿级别规模建议选择RocksDB。

请求可以解释下为什么RocksDB比HBASE的性能更好？
