### ISSUE TITLE
[Question] 存量数据情况下为节点属性添加SECONDARY索引，索引状态变为CREATED后，使用属性进行查询仍然失败

### ISSUE THREAD

**Issue by hhhyang** [hugegraph/hugegraph#1594]
### Problem Type (问题类型)

gremlin (结果不合预期)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.x
- Backend: Cassandra 3.11 

### Your Question (问题描述)

在数据库已有数据的情况下，停止数据写，保持正常查询。通过hugegraph-hubble为节点某属性建立secondary索引，等索引状态变为created后，通过gremlin-console进行查询，结果报异常，信息如下：

```
gremlin> :> hugegraph.schema().getIndexLabel('netwareByVendor')
==>[id:51,name:netwareByVendor,base_type:VERTEX_LABEL,base_value:Netware,index_type:SECONDARY,fields:[vendor],status:CREATED,user_data:[~create_time:2021-08-26 17:09:41.090]]
gremlin> :> g.V().hasLabel('Netware').has('vendor','XXXX').id()
Don't accept query based on properties [vendor] that are not indexed in label 'Netware', may not match secondary condition
Type ':help' or ':h' for help.
Display stack trace? [yN]

```

**Comment by imbajin** [comment]
有数据的时候创建索引是一个异步操作, 所以完成比例以异步任务的结果为标致比较准确, 记录了进度(是否完成)

另外可以给个 test 图, 简单试试写一些数据, 看看索引是否生成, 能否复现就好确定了, C*里也都是明文格式很好确认

**Comment by hhhyang** [comment]
@imbajin 
hubble上面看任务早就完成了，而且到现在这个现象还是存在的

**Comment by hhhyang** [comment]
补充一点信息：重启hugegraph后，重启的hugegraph节点上查询不到对应的索引了。直接查询cassandra后端数据库，显式对应的索引状态为invalid

**Comment by javeme** [comment]
请问是否有错误日志信息或者复现流程呢？
