### ISSUE TITLE
[Bug] describe the main problem

### ISSUE THREAD

**Issue by ighack** [hugegraph/hugegraph#1596]
### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.2
- Backend: hbase with kerberos

### Expected & Actual behavior (期望与实际表现)

我在 studio中删除一个顶点报错
g.V('1:task1').drop()

> 2021-08-30 16:52:10 120272979 [hconnection-0x60b1ff3b-metaLookup-shared--pool5-t13] [INFO ] org.apache.hadoop.hbase.client.RpcRetryingCallerImpl [] - Call exception, tries=9, retries=11, started=28301 ms ago, cancelled=false, msg=Call to bigdser4/10.3.87.26:16020 failed on local exception: javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)], details=row 'hugegraph:el,,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=bigdser4,16020,1629333247249, seqNum=-1, see https://s.apache.org/timeout
> 2021-08-30 16:52:11 120274678 [gremlin-server-worker-1] [WARN ] org.apache.tinkerpop.gremlin.server.handler.HttpGremlinEndpointHandler [] - Invalid request - responding with 500 Internal Server Error and Script evaluation exceeded the configured 'scriptEvaluationTimeout' threshold of 30000 ms or evaluation was otherwise cancelled directly for request [g.V('1:task1').drop()]
> java.util.concurrent.TimeoutException: Script evaluation exceeded the configured 'scriptEvaluationTimeout' threshold of 30000 ms or evaluation was otherwise cancelled directly for request [g.V('1:task1').drop()]
> 	at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$1(GremlinExecutor.java:315) ~[gremlin-groovy-3.4.3.jar:3.4.3]
> 	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) [netty-all-4.1.13.Final.jar:4.1.13.Final]
> 	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120) [netty-all-4.1.13.Final.jar:4.1.13.Final]
> 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-all-4.1.13.Final.jar:4.1.13.Final]
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [netty-all-4.1.13.Final.jar:4.1.13.Final]
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462) [netty-all-4.1.13.Final.jar:4.1.13.Final]
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.13.Final.jar:4.1.13.Final]
> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_271]

感觉是kerberos认证失败样的。但我可以创建节点，边都没问题。我也可以删除边。怎么删除顶点就报错呢。是不是我的写法有问题啊

**Comment by imbajin** [comment]
是否 kerberos 可以通过 rocksdb 这种后端对比就知道了, 你可以同时加载两图 (内置rocksdb 作为对比图), 这是一个通用的办法

至于删除 `drop()` 使用, 可以参考历史已有 issues, 另外 studio 直接是不维护了的, 请使用它的新版 hubble

**Comment by ighack** [comment]
换了hubble好像就可以了
