### ISSUE TITLE
[Question] 边索引和点索引哪个速度更快？

### ISSUE THREAD

**Issue by Tea996** [hugegraph/hugegraph#1599]
### Problem Type (问题类型)

performence (性能优化)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.x
- Backend: cassandra
- OS:  Centos 7.4 

### Your Question (问题描述)

如果有一个索引即可以建在边上也可以建在点上，是不是建在边上速度更快，实际应用场景有何倾向

**Comment by imbajin** [comment]
上文提供得略少, 没有具体的举例和 schema, 也缺少具体什么类型的索引搜索..

另外提示一下边是有单独设计优化的 sortkey 索引排序的, 你可以搜一下 issues 里关于 sortkey 适用场景的说明, 以及历史里关于不同索引实现区别的介绍

**Comment by Tea996** [comment]
现在有两种应用场景：
（1）模糊匹配，A人员B地址，A->居住在->B。B的主键是中文地址，现在要对地址进行模糊查询，直接把全文索引加到B的主键上不起作用，报`Method userpropValues(List<String>) only used for secondary index, relation must be EQ, but got TEXT_CONTAINS`的错误，所以准备另加一个字段专门做模糊匹配，这个字段加在点上查询快还是边上查询快，如果速度差不多的话是不是加在点上更合理一些？
（2）时间查询，A人员B旅行地，A->旅行->B，主要目的是为了找到一起出发旅行的同伴，现在B的主键是旅行日期+旅行地址，此时如果要通过旅行日期范围过滤，是在B点上加范围索引比较好还是在旅行这条边上加sortkey比较好？

**Comment by Tea996** [comment]
我看了 #372那个不需要添加索引就能模糊匹配的写法，里面也提到了这种写法数据量大的时候效率不好的问题，我们还是希望能把索引用起来的
