### ISSUE TITLE
Too many records(must <= 800000)

### ISSUE THREAD

**Issue by KirubakaranSP** [hugegraph/hugegraph#1605]
### Problem Type (问题类型)

gremlin (结果不合预期)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.x
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

When i try to execute a query it results in error.Error message was Too many records(must <= 800000).How to fix this?

**Comment by imbajin** [comment]
maybe search in the issues first
![image](https://user-images.githubusercontent.com/17706099/133250646-91e13bbb-7320-4b29-8a44-5bf9e1fd8946.png)

like #586 (use async way or use restapi [page-for-vertices](https://hugegraph.github.io/hugegraph-doc/clients/restful-api/vertex.html#216-%E8%8E%B7%E5%8F%96%E7%AC%A6%E5%90%88%E6%9D%A1%E4%BB%B6%E7%9A%84%E9%A1%B6%E7%82%B9)) and other closed issues #1388
