### ISSUE TITLE
[Question] 启动时设置了jvm 的-Xms 和 -Xmx一样大，用了一段时间之后，hugegraph占用的内存仍在不断上涨

### ISSUE THREAD

**Issue by chencjiajy** [hugegraph/hugegraph#1606]
### Problem Type (问题类型)

server status (启动/运行异常)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.10.4
- Backend: Hbase, 3 nodes, HDD
- OS: 2 CPUs, 8 G RAM, Centos 7.8
- Data Size: 170000 vertices, 530000 edges

### Your Question (问题描述)

因为系统一共8G内存，在启动hugegraph 时，配置了 -Xms5120m -Xmx5120m。 
hugegraph运行一段时间之后，占用内存超过了5g， 并且一直在增加

早上：
![企业微信截图_dc673ecf-381a-4c93-92bb-1a1ceb47496f](https://user-images.githubusercontent.com/19321967/133385065-52e60e96-8ed6-42ff-a5ed-9d6e1d1554a4.png)

晚上：
![企业微信截图_aa7e9cb4-d2e9-4697-bfd4-c0c754d0a74a](https://user-images.githubusercontent.com/19321967/133385161-c8ea2b52-4e4f-4ba4-b687-5aa9ab4b69cf.png)

hugegraph主要用来进行gremlin 查询

### Vertex/Edge example (问题点 / 边数据举例)

```javascript
无
```

### Schema [VertexLabel, EdgeLabel, IndexLabel] (元数据结构)

```javascript
无
```

**Comment by imbajin** [comment]
先确定一下给的参数生效了, `jps -v` 或者是 `ps -ef` 截图一下当前 server 进程对应的详细 jvm 启动参数

然后是否有切换到 g1gc 呢? 默认是cms

**Comment by chencjiajy** [comment]
> 先确定一下给的参数生效了, `jps -v` 或者是 `ps -ef` 截图一下当前 server 进程对应的详细 jvm 启动参数
> 
> 然后是否有切换到 g1gc 呢? 默认是cms

给的参数是有生效的，没有使用g1gc，前文的截图是昨天截的，因为内存一直涨，怀疑hugegraph使用了堆外内存，所以我在`hugegraph-server.sh`添加了参数MaxDirectMemorySize之后重启了，重启之后使用`jps -v`详情如下：
<img width="1177" alt="企业微信截图_7580cb37-fbfc-4dbb-824e-78960cb6e635" src="https://user-images.githubusercontent.com/19321967/133405363-b39e22b3-dad1-42d5-9c06-8cf166f315d4.png">

**Comment by imbajin** [comment]
堆外缓存默认是没开的才对, 你可以看看 gc 的情况和 dump 看看内存里最大的对象是啥 (或者也可换0.11最新发布试试, 看看有没有同样的问题)

**Comment by chencjiajy** [comment]
> 堆外缓存默认是没开的才对, 你可以看看 gc 的情况和 dump 看看内存里最大的对象是啥 (或者也可换0.11最新发布试试, 看看有没有同样的问题)
> 
> 另外, 还有一个很简单的排除方式, 你把缓存的时间和个数调小 (properties)文件里. 然后观察一下 gc 和内存使用.

之前我已经将缓存时间和个数都设置的已经很小了， 我的疑问主要是为什么hugegraph的内存占用会超过我设置的最大内存那么多。因为重启了，暂时没有办法复现了。
 感谢回复！

ps:这是昨天内存一直涨的时候，查看的jmap和gc情况
![企业微信截图_ead32d76-3afd-4238-8066-a8fb67e947e2](https://user-images.githubusercontent.com/19321967/133423422-4adbc7a7-8c05-407e-825a-967455949d15.png)
![企业微信截图_96a5dc25-f04c-4226-bded-4fdb0d6171a5](https://user-images.githubusercontent.com/19321967/133423664-805e652e-84da-424e-8db4-6700c8f37ed0.png)

**Comment by imbajin** [comment]
其实你设置最大最小堆的执行者本来也是 jvm, 如果 huge 都能直接影响 jvm 是否超出内存, 那等于自己控制了内存管理了~

除了 jvm 自身本身的一定额外内存占用, 以及 g1gc 的不确定较大比例超出, 剩下还是要从内存堆栈信息, 比如 jmap 里 fullgc 后存活的对象来分析一下, 如果是缓存, 那应该是可以复现的. (或者可以与0.11进行对比)
