### ISSUE TITLE
[Question] 高可用咨询，目前发现只有master节点能够删除schema，同时一个cluster只能有一个master，请问这块要怎么保证高可用

### ISSUE THREAD

**Issue by vincentshu** [hugegraph/hugegraph#1609]
### Problem Type (问题类型)

struct / logic (架构 / 逻辑设计问题)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.2
- Backend: RocksDB 3 nodes, HDD or SSD 
- OS: 8 CPUs, 16 G RAM, Centos 7.x 

### Your Question (问题描述)

尝试3个raft节点做高可用，但是只有一个节点能配置成master，其他节点只能配置成non-master，我这边配置成2个worker，当删除schema的请求打到worer节点，会报Can't %s task on non-master server，
请问要怎么配置能保证高可用，或者目前是否支持，谢谢

**Comment by imbajin** [comment]
请贴出详细的**配置文件**, 因为你理解的 master 可能和 raft 的 leader 不是一个, 我们支持过两种方案

**Comment by vincentshu** [comment]
感谢您的回复。
下面是我配置的3个节点的配置文件。我的理解是多个raft节点，leader只能是一个。
而下发删除或取消的任务的节点只能是master节点，但是如果只能这样配置，master节点宕机了
整个集群就不能删除schema了，这块具体要怎么配置呢，不知道我的理解有没有问题。期盼您的回复，谢谢
节点1：
hugegraph:
  gremlin:
    graph: com.baidu.hugegraph.HugeFactory

  backend: rocksdb
  serializer: binary
  #  backend: mysql
  #  serializer: mysql

  store: hugegraph
  connection_wait_timeout: 300
  nodeRole: master
  serverId: server1
  rocksdb:
    data_path: E:\hugegraph\rocksdb\data
    wal_path: E:\hugegraph\rocksdb\wal
  raft:
    mode: true
    safe_read: false
    use_snapshot: true
    endpoint: 127.0.0.1:9902
    group_peers: 127.0.0.1:9902,127.0.0.1:9903,127.0.0.1:9904
    path: ./raftlog1

节点2：
hugegraph:
  gremlin:
    graph: com.baidu.hugegraph.HugeFactory

  backend: rocksdb
  serializer: binary
  #  backend: mysql
  #  serializer: mysql

  store: hugegraph
  connection_wait_timeout: 300
  nodeRole: master
  serverId: server2
  rocksdb:
    data_path: E:\hugegraph\rocksdb2\data
    wal_path: E:\hugegraph\rocksdb2\wal
  raft:
    mode: true
    safe_read: false
    use_snapshot: true
    endpoint: 127.0.0.1:9903
    group_peers: 127.0.0.1:9902,127.0.0.1:9903,127.0.0.1:9904
    path: ./raftlog2

节点3：
hugegraph:
  gremlin:
    graph: com.baidu.hugegraph.HugeFactory

  backend: rocksdb
  serializer: binary
  #  backend: mysql
  #  serializer: mysql

  store: hugegraph
  connection_wait_timeout: 300
  nodeRole: master
  serverId: server3
  rocksdb:
    data_path: E:\hugegraph\rocksdb3\data
    wal_path: E:\hugegraph\rocksdb3\wal
  raft:
    mode: true
    safe_read: false
    use_snapshot: true
    endpoint: 127.0.0.1:9904
    group_peers: 127.0.0.1:9902,127.0.0.1:9903,127.0.0.1:9904
    path: ./raftlog3

**Comment by imbajin** [comment]
贴配置的时候可以参考 #1462, 把不同配置文件的配置分开 (放一起可能容易误会/看串)

目前的 raft 的 leader/follower, 与在 rest-server 中配置的 master/worker 你可以理解为是没有任何直接关系的, 后者是独立于 raft 存在的, 它的目的你可以看看历史 issue, 是一个分发**异步任务**的轻量级负载均衡, 它并不是用来做高可用的. (raft 才是)

但是因为历史原因, master/worker 的机制先提供了, 的确有你说的这个问题, master 对应的节点挂了就没法工作, 目前简单的办法是你可以写个 crontab 定时检查拉起 graph server 来自动化处理一下, 根本上的话, 需要后续相关代码, 允许关闭/屏蔽调 master/worker 这套负载均衡机制, 这样就不会影响 raft 的多副本机制了

**Comment by vincentshu** [comment]
感谢您的回复。
我这边去掉了只能有一个master的校验代码，本地能够正常的启动3个master  raft节点，但是发现每次commit的时候，都会转发到leader节点，我这边有一个场景，一个请求的逻辑处理中，会在循环中依次给一个顶点label增加一个字段，然后给这个字段增加索引，增加字段的处理最后转发到了leader节点，然后当前follower节点继续处理增加索引的处理，在IndexLabelBuilder.checkFields方法的执行过程中，有时候会出现下面这个错误。
        E.checkArgument(properties.containsAll(fields),
                        "Not all index fields '%s' are contained in " +
                        "schema properties '%s'", fields, properties);
感觉好像是前一步增加字段的操作数据，并没有同步到当前的followeri节点，这个问题在我前端增加一个顶点数据，然后马上查询，有时候查不到最新数据好像是同一个问题，我猜测是数据同步需要时间，而在同步成功之前，查询请求打到的节点正好还没拿到最新的数据。
基于以上，我有2个问题：
1.去掉master节点的校验，尝试启动3个master的raft node，这种做法是否可行。
2.数据同步在多个节点中会存在延时，导致查询不到最新的数据，这个问题是否是一个普遍的问题，有没有解决方法。
期盼您的回复，谢谢

**Comment by Linary** [comment]
@vincentshu 感谢反馈。

有一个概念需要先纠正一下：在hugegraph里，master/worker 和 raft 里的 leader/follower 不是同样的概念，它们的角色之间没有任何关系。master/worker 是用来做异步任务调度的，你可以启动3个master，然后执行删除schema之类的异步任务试试，如果能执行就说明这种做法可行。

数据同步时在多个节点存在延迟这是raft协议的正常现象，如果你请求是发往 leader 节点的不会出现这个延迟的问题，发给follower可能会出现的。如果你希望发给follower也保证一致性读的话，可以把 safe_read 设置为 true，这样就没有问题了，不过读的延迟会高一些。
