### ISSUE TITLE
[Question] hugegraph server多节点缓存一致性如何保证

### ISSUE THREAD

**Issue by z7658329** [hugegraph/hugegraph#1611]
### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.x
- Backend: mysql  
- OS: 8 CPUs, 16 G RAM, Centos 7.x 
- Data Size:  1000W vertices, 6000w edges 

### Your Question (问题描述)

#1239
#18
1.缓存一致性由RPC同步保证 这块代码在哪里？某个server节点执行了写入操作，这个时候是直接RPC同步到其他server节点？如果部署了10+节点，每个写入操作都是轮询一遍server list，每个server发起一次rpc么;
2.如果缓存一致性是在商业版提供，此时我又想启动多个server来保证HA，要怎么处理呢？
![5e5f6ad62debf9132a8abe7a89d30ba](https://user-images.githubusercontent.com/5474723/134620063-5fc8a180-6c95-41b6-90ba-589be44f39f8.png)

### Vertex/Edge example (问题点 / 边数据举例)

```javascript
nothing
```

### Schema [VertexLabel, EdgeLabel, IndexLabel] (元数据结构)

```javascript
nothing
```

**Comment by imbajin** [comment]
1. 可以参考一下 AuthServer / AuthCache 相关代码, 一致性是可选的, 默认不开启
2. 在普通的点边读写这, 默认也是没开的, 如果开也不会是立刻同步, 会异步的进行同步, 减少性能影响
3. 如果是对元信息的 CRUD, 一般是考虑立刻同步, 因为这种操作也极少, 并且影响大
4. RPC 的同步机制等可以参考封装的 RPC 代码/配置
5. 商业版是优先提供更细粒度 + 一键化的 HA 服务/拉起/配置 (社区版需要手工操作)
6. 如果关闭图点边缓存的情况, 基本就不会存在明显的一致性问题, 对元信息的修改, 可以调用 invalidateCache 的 api 使其他 server 的缓存失效也行, 但都需要自己手动管理 
7. 关闭点边缓存对重复查询性能影响明显, 对小数据量或离散查询不大, 自己可以测试考虑 (或者降低缓存过期时间)

**Comment by z7658329** [comment]
> 1. 可以参考一下 AuthServer / AuthCache 相关代码, 一致性是可选的, 默认不开启
> 2. 在普通的点边读写这, 默认也是没开的, 如果开也不会是立刻同步, 会异步的进行同步, 减少性能影响
> 3. 如果是对元信息的 CRUD, 一般是考虑立刻同步, 因为这种操作也极少, 并且影响大
> 4. RPC 的同步机制等可以参考封装的 RPC 代码/配置
> 5. 商业版是优先提供更细粒度 + 一键化的 HA 服务/拉起/配置 (社区版需要手工操作)
> 6. 如果关闭图点边缓存的情况, 基本就不会存在明显的一致性问题, 对元信息的修改, 可以调用 invalidateCache 的 api 使其他 server 的缓存失效也行, 但都需要自己手动管理
> 7. 关闭点边缓存对重复查询性能影响明显, 对小数据量或离散查询不大, 自己可以测试考虑 (或者降低缓存过期时间)

![image](https://user-images.githubusercontent.com/5474723/134620560-0728e08e-25f4-4d6b-b886-9fe1f5bc8c63.png)
1.这些配置项注释掉就代表关闭点边缓存了吧
2.可以考虑提供spi扩展点出来，比如我现在想直接存分布式缓存来解决 多server部署的本地缓存一致性问题

**Comment by imbajin** [comment]
1. 缓存默认开启, 你控制缓存时间大小就能等价于控制关闭, 之后有考虑提供一个一键关闭缓存的开关 (也可以自己加一下)
2. 堆外缓存文档配置文件有 `vertex.cache_type` (l2是堆外, 也可代码里确认)
3. 可参考 #1581, 另外社区版 RPC 同步看 Auth 相关代码调用作为参考
