### ISSUE TITLE
[Question] 存储层mysql和hbase的性能压测数据咨询

### ISSUE THREAD

**Issue by z7658329** [hugegraph/hugegraph#1612]
### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.x
- Backend: mysql 1 nodes,   SSD 
- OS: 8 CPUs, 16 G RAM, Centos 7.x 
- Data Size:  500w vertices, 500w edges 

### Your Question (问题描述)

backend这块使用mysql / hbase作为存储层的话，性能压测数据有参考吗？

### Vertex/Edge example (问题点 / 边数据举例)

```javascript
nothing
```

### Schema [VertexLabel, EdgeLabel, IndexLabel] (元数据结构)

```javascript
nothing
```

**Comment by imbajin** [comment]
可以参考一下网络上有的测试文章, 版本不同存储和性能也有差异, 最好是自己实测一下为好.
写入的 case 还好, 读的情况差别比较多, rocksdb 是性能最好的单机而言, mysql 一般不太建议, 数据量大一点就很慢了

**Comment by waynecookie** [comment]
请问后来找到解决方案了吗
