### ISSUE TITLE
[Bug] 添加顶点-offheap报错

### ISSUE THREAD

**Issue by z7658329** [hugegraph/hugegraph#1614]
### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.x
- Backend: mysql ssd
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### Expected & Actual behavior (期望与实际表现)

顶点类型如下：
![image](https://user-images.githubusercontent.com/5474723/135224533-482ff7ae-e5aa-42b2-84bf-e0c622ec43a7.png)

serviceName&sourceType 作为primary keys
测试创建顶点 代码首次insert成功，有一个顶点，serviceName sourceType属性 作为primary keys；测试主键冲突的UT，同样的数据首次创建顶点成功，返回了顶点ID为：6:A!14
然后用同样的数据再次创建顶点，返回的不是主键冲突异常 却是offheap错误：Unsupported type of serialize value: 'v[6:A!14]' ，不是应该报主键冲突的错误吗？怎么会报这种错

![1632901063](https://user-images.githubusercontent.com/5474723/135224831-edaf08c0-c0bc-4589-8537-39ed6817ac44.jpg)

**Comment by imbajin** [comment]
可以把问题上下文描述清晰一点, 从简单的描述来看, 如果只有堆外缓存有这个问题, 有可能是 bug (可以试试普通缓存是正常的么)

麻烦能试试提供一个最小的可复现 case 么? 例如 issue 1590 或最近一些 gremlin 查询结果不一致的提问.

然后在 HugeClient 和 HugeGraph 的模块里都有对应堆外缓存测试的 case, 你可以直接试试跑一下, 或者新增一个你的测试用例

看看是否能复现. 多谢

**Comment by javeme** [comment]
@z7658329 这个确实是个Bug，应该是增加`HugeVertex4Insert`类时，未适配offheap类别缓存导致的。

**Comment by javeme** [comment]
@z7658329 可以验证一下是否已经解决该Bug，如果没有解决的话可以重新打开并继续留言~
