### ISSUE TITLE
[Question] hugegraph后端支持 一些自己开发的存储么

### ISSUE THREAD

**Issue by liufei26** [hugegraph/hugegraph#1615]
### Problem Type (问题类型)

struct / logic (架构 / 逻辑设计问题)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.x
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

hugegraph后端支持挂其他的存储么。比如我使用公司内部开发的存储，然后在代理层通过api存储数据，hugegraph只使用解析gremlin语法的功能。

**Comment by imbajin** [comment]
支持的, 这是 HG 很大的一个特色, 你可以参考代码支持不同存储的方式. 这里做了一层统一的抽象隔离
