### ISSUE TITLE
[Question] hugegraph 权限认证

### ISSUE THREAD

**Issue by emotschen** [hugegraph/hugegraph#1617]
### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.x
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

![image](https://user-images.githubusercontent.com/17001185/136514149-06ce9e12-720c-4823-b8dc-40d2bdde999d.png)
我们通过官网 配置StandardAuthenticator 权限认证。
通过POST http://10.77.0.245:8080/graphs/hugegraph/auth/users
但是返回：
{
    "exception": "class javax.ws.rs.BadRequestException",
    "message": "Only HTTP Basic authentication is supported",
    "cause": ""
}
这是需要商业版么？

**Comment by emotschen** [comment]
这个功能是需要商业版 才提供？

**Comment by imbajin** [comment]
你的图似乎挂了, 请在 `preview` 栏确认图片加载正常再点 comment, 因为图片默认传海外可能比较慢

**Comment by emotschen** [comment]
多谢，认证这块我已经安装通过了。不过 接着有个问题是，我创建了新用户。
也成功了。
但是登录hugegraph-hubble 时候显示：
User not authorized.  这个我不是很明白
{
    "user_password": "$2a$04$XLfGtFXELi7MTWK/44dt9eJPnXFQaIrBeeBEIk5y6djge97EDvZgm",
    "user_email": "123@xx.com",
    "user_update": "2021-10-08 17:40:33.735",
    "user_name": "boss",
    "user_creator": "admin",
    "user_phone": "182****9088",
    "id": "-63:boss",
    "user_create": "2021-10-08 17:40:33.735"
}
