### ISSUE TITLE
[Question] Text.contains匹配结果异常

### ISSUE THREAD

**Issue by Ckuangf** [hugegraph/hugegraph#1619]
### Problem Type (问题类型)

gremlin (结果不合预期)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.2
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

![image](https://user-images.githubusercontent.com/31173360/137091899-7d01d786-cc68-4ee5-a19e-9122d3e7470a.png)
查询时希望通过contains匹配出来projectAliasText中包括db5的顶点，但是匹配出来的结果全部都是db1的

建立的索引是search类型的

分词器：
search.text_analyzer=ikanalyzer
search.text_analyzer_mode=max_word

查询语句：g.V().has("clusterNameText",Text.contains("dGVybWludXMtZGV2")).has("projectAliasText",Text.contains("db5"))

**Comment by javeme** [comment]
> 分词器：
search.text_analyzer=ikanalyzer
search.text_analyzer_mode=max_word

该分词器会将db5拆分为3个词（"db5", "db", "5"），所以搜索"db5"时能匹配上"db1"，原理如下：通过第2个词"db"匹配到"db1"里面的第2个分词（"db1", "db", "1"）。
```java
        analyzer = AnalyzerFactory.analyzer("ikanalyzer", "max_word");
        Assert.assertEquals(setOf("db5", "db", "5"), analyzer.segment("db5"));
```

**Comment by Ckuangf** [comment]
> > 分词器：
> > search.text_analyzer=ikanalyzer
> > search.text_analyzer_mode=max_word
> 
> 该分词器会将db5拆分为3个词（"db5", "db", "5"），所以搜索"db5"时能匹配上"db1"，原理如下：通过第2个词"db"匹配到"db1"里面的第2个分词（"db1", "db", "1"）。
> 
> ```java
> analyzer = AnalyzerFactory.analyzer("ikanalyzer", "max_word");
> Assert.assertEquals(setOf("db5", "db", "5"), analyzer.segment("db5"));
> ```
这个处理方式和我猜测的一样，但是这种对于查询条件中的值是否需要进行分词，或者说是否有其他办法绕过这个先进行分词然后再匹配的动作呢。因为这种对查询条件的值进行分词查询应该更多的属于关键字匹配搜索，而不是contains匹配

**Comment by javeme** [comment]
@Ckuangf 可以考虑其它分词器，比如参考一下：https://github.com/hugegraph/hugegraph/issues/779#issuecomment-561492880
