### ISSUE TITLE
[Question] 语句执行触发FGC

### ISSUE THREAD

**Issue by z7658329** [hugegraph/hugegraph#1622]
### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.x
- Backend: mysql 1node SSD 
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

业务场景：统计一下 没有领导指向的员工
g.V().hasLabel("v_staff").where(inE("e_lead_of_staff").count().is(0)).limit(1)
v_staff 员工顶点
e_lead_of_staff 领导指向员工的边
统计了一下staff员工的数量 一共6W条数据

这种语句执行 hubble报错超时，我看后端hugegraph server触发FGC了... 
1.为啥会触发FGC？
2.针对该业务需求 有解决办法吗？

**Comment by javeme** [comment]
已确认是mysql后端存储时，statement泄露导致，具体见 #1626
