### ISSUE TITLE
[Bug] mysql 后端运行一段时间可能内存泄漏

### ISSUE THREAD

**Issue by z7658329** [hugegraph/hugegraph#1626]
### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.x
- Backend: mysql nodes, HDD or SSD 
- OS: 8 CPUs, 32 G RAM, Centos 7.x 
- Data Size:  50W vertices, 130W edges 

### 1.参数配置说明：
1. backend后端mysql  实际数据量 顶点数 50W 边数量 130W
2. 有个业务进程会对huge CRUD，大概的读写 每分钟2000左右 大部分是read  
3. jvm配置：
 java -server 
-Dname=HugeGraphServer 
-Dlog4j.configurationFile=/scripts/hugegraph-0.11.2/conf/log4j2.xml 
-Djava.security.manager=com.baidu.hugegraph.security.HugeSecurityManager 
-Xms16g -Xmx16g 
-XX:+HeapDumpOnOutOfMemoryError 
-XX:HeapDumpPath=/scripts/hugegraph-0.11.2/logs 
-XX:+UseGCLogFileRotation 
-XX:GCLogFileSize=10M 
-XX:NumberOfGCLogFiles=3 
-Xloggc:/scripts/hugegraph-0.11.2/logs/gc.log 
-XX:+PrintHeapAtGC 
-XX:+PrintGCDetails 
-XX:+PrintGCDateStamps 
-XX:+UseG1GC 
-XX:MaxGCPauseMillis=1000 
-XX:+ParallelRefProcEnabled 
-XX:InitiatingHeapOccupancyPercent=50 
-XX:G1RSetUpdatingPauseTimePercent=5 
4.顶点边的缓存配置：
hugegraph.properties：开启了l2 堆外
     vertex.cache_type=l2
     vertex.cache_expire=300
     edge.cache_type=l2
     edge.cache_expire=300
### 2.期望表现
1.在发生老年代 GC 时，可以回收掉一部分对象，使得老年代使用量不是持续走高。(实际运行一段时间后高居不下最后FGC，时长高达43s)

### 3.实际情况
![gc](https://user-images.githubusercontent.com/5474723/139630483-d5ddf85f-067d-43ba-8e6e-8842e721ddce.png)

jmap统计对象数据：
![image](https://user-images.githubusercontent.com/5474723/139630644-3322e47d-df27-4ae9-82c6-ee66d89f1b51.png)
存活对象：
![f0abcbe2ba279b0fb74316a9ba99ab0](https://user-images.githubusercontent.com/5474723/139630697-d4cf213c-1c18-4687-abdb-0724eccaa621.png)

GC日志：
[gc.log.zip](https://github.com/hugegraph/hugegraph/files/7451158/gc.log.zip)

**Comment by z7658329** [comment]
![image](https://user-images.githubusercontent.com/5474723/139653638-cfee14d4-304a-4d8c-924f-e8f5fe69d3c7.png)

本地自测同样复现

**Comment by javeme** [comment]
分析了一下，是 MySQL Statement 未及时关闭导致的，可以按照如下方式修复：

![image](https://user-images.githubusercontent.com/9625821/139654276-f0c691c7-e611-443e-9e48-dffd9d8f28f6.png)

修改为如下步骤：
```java
Statement statement = this.conn.createStatement();
ResultSet rs = statement.executeQuery(sql);
return new ResultSetWrapper(rs, statement);
```

然后通过ResultSetWrapper的close()方法来关闭ResultSet和Statement，通过results()方法来获得实际的ResultSet：
```java
class ResultSetWrapper {
    ResultSet rs;
    Statement statement;

    ResultSet results() {
        return this.rs;
    }

    close() {
        this.rs.close();
        this.statement.close();
    }
}
```


历史用户反馈类似问题：https://github.com/hugegraph/hugegraph/issues/1203#issuecomment-720980290

**Comment by z7658329** [comment]
### count语句未关闭statement

![b4102f88928667f1f5c1e42f78f3eb3](https://user-images.githubusercontent.com/5474723/141058636-e84b716d-2b97-444c-8110-1dbef78c19e2.png)
