### ISSUE TITLE
[Question] 关于容器部署的host配置咨询

### ISSUE THREAD

**Issue by z7658329** [hugegraph/hugegraph#1628]
### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

Server Version: v0.11.x
Backend: mysql nodes, HDD or SSD
OS: 8 CPUs, 32 G RAM, Centos 7.x
Data Size: 50W vertices, 130W edges

### Your Question (问题描述)

想咨询一下容器部署情况下  
--这个rest-server.properties 下的restserver.url  gremlinserver.url 以及gremlin-server.yaml下的host/port 需要怎么配置？维持127.0.0.1吗？ 通过容器端口映射外部宿主机端口方式吗？

我这边公司自己build的镜像，测试如果使用127.0.0.1配置的话，无法通过域名/IP:Port的方式访问

![image](https://user-images.githubusercontent.com/5474723/140008836-affad6ea-820b-4937-b704-c656b521d18b.png)

报错如下，只能手动改一下配置里的127.0.0.1 修改为对应的ip
![image](https://user-images.githubusercontent.com/5474723/140008859-538929ae-a6b9-4382-acbf-c109a5289e3a.png)

**Comment by imbajin** [comment]
类似社区 [Dockerfile](https://github.com/hugegraph/hugegraph/blob/master/Dockerfile) 里改成 0.0.0.0 就行了, `127.0.0.1` 本身就限制了只能本机访问的. (其实觉得默认值应该改成 0.0.0.0 更友好点)
