### ISSUE TITLE
[Bug] 删除/添加schema索引但cache并未实时同步

### ISSUE THREAD

**Issue by z7658329** [hugegraph/hugegraph#1637]
### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

Server Version: v0.11.x
Backend: mysql nodes, HDD or SSD
OS: 8 CPUs, 32 G RAM, Centos 7.x
Data Size: 50W vertices, 130W edges

### Expected & Actual behavior (期望与实际表现)

现象：大部分情况下的删除和新增索引都没问题，内存cache及时同步，但是存在个别处理没有及时同步的问题。

动态删除索引后发现cache并未清理掉，内存中id=24的数据已经被删除，DB已经不存在该记录，debug源码如下：
![企业微信截图_16364512299724](https://user-images.githubusercontent.com/5474723/140901548-91f913fc-0264-47de-9303-8a20eb8e0311.png)

同时也偶发了一个添加索引 但是cache不存在的情况：
![a541b887ad2b33e7e1404362735daca](https://user-images.githubusercontent.com/5474723/140902058-ca641c2f-4400-490a-99b8-752d4cf8f89e.png)

### Expected & Actual behavior (期望与实际表现)
预期动态对schema的新增和删除，能及时同步到cache中

建议add一个兜底处理：CachedSchemaTransaction提供一个timer定时器，处理逻辑定期检查DB和cache的schema数据，将DB的数据同步scheme的Ramcache中

**Comment by javeme** [comment]
可以前移removeIndexLabelFromBaseLabel()到graphTx.removeIndex()之前来规避不一致问题，这样可以避免删除一半索引时出错，而导致base label未更新：
![image](https://user-images.githubusercontent.com/9625821/141072326-705ce935-bfa0-4450-9fb0-5950726e9c83.png)

**Comment by javeme** [comment]
related issue: #1594
