### ISSUE TITLE
Exception while inserting special char values like '\\u0000' 

### ISSUE THREAD

**Issue by KirubakaranSP** [hugegraph/hugegraph#1638]
### Problem Type (问题类型)

Exception while inserting special chars

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.x
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

When i try to push the constant value '\\u0000' through JAVA API ,it results in java.lang.IllegalArgumentException.How to insert these type of values in hugegraph?

### Vertex/Edge example (问题点 / 边数据举例)

```javascript
[
  {
    "label": "CONSTANT",
    "id": 1,
    "properties": {
      "VALUE": "\u0000",
      "CLASS_NAME": "Ljava/lang/String;"
    }
  }
]
```

**Comment by javeme** [comment]
@KirubakaranSP could you provide specific error message? 
Is it `Illegal char '\\u0000' in index property`? because '\u0000'  ~ '\u0003' are reserved characters with special meaning, you can use "\u0004" or "abc\u0000" instead.

**Comment by KirubakaranSP** [comment]
Illegal char '\\u0000' in index property: '\u0000 this is the specific error message.FYKI, I cannot able to alter the value, i want to insert the value \u0000 as constant value.Escaping the special characters will work right? or is there any options in hugegraph ?

**Comment by KirubakaranSP** [comment]
hi any update on this?

**Comment by javeme** [comment]
Not mean that any content contains special characters cannot be inserted, it's just not allowed if one (and only one) character is in the range` '\u0000' ` ~  `'\u0003'`. It's allowed if there are multiple characters but contains ` '\u0000' `, , such as `"abc\u0000xyz"`.

**Comment by KirubakaranSP** [comment]
I have to query the constant value so the property has been indexed (Search indexed).So i am unable to insert the value 
"abc\u0000xyz".Is there any other indexing properties available?

**Comment by KirubakaranSP** [comment]
Here is my sample json,
[
  {
    "label": "CONSTANT",
    "id": 1,
    "properties": {
      "VALUE": "\u0000",
      "CLASS_NAME": "Ljava/lang/String;"
    }
  }
]
I've indexed (search index) the property "VALUE" for that vertex label CONSTANT.So when i insert any of the values like '\u0000' or 'xyz\u0000abc' it results in the below exception

 **{"exception":"class java.lang.IllegalArgumentException","message":"Illegal char '\\u0000' in index property: 'xyz\u0000abc'","cause":""}**

As you stated above, escaping the values or values like 'xyz\u0000abc' is also results in same exception. and Kindly help me on this.

**Comment by javeme** [comment]
The key point here is the search index (my description above is based on the secondary index), the text of search-index field we pass in will be segmented into multiple words(include word '\u0000'). We generally only consider creating a search index for visible characters, this kind of usage is beyond the expected design. We can improve codes in the last two weeks, such as ignoring meaningless '\u0000' word from segmented words.

**Comment by javeme** [comment]
@KirubakaranSP Could you please try to submit a patch? Welcome to contribute.

We can remove special characters from the words set:
```java
    private Set<String> segmentWords(String text) {
        Set<String> words = this.textAnalyzer.segment(text);
        for (char ch = INDEX_SYM_ENDING; ch <= INDEX_SYM_MAX; ch++) {
            words.remove(ch);
        }
        return words;
    }
```
https://github.com/hugegraph/hugegraph/blob/cc509f9061e4221cadc041cbdeabd41611d0ff6d/hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java#L888

**Comment by KirubakaranSP** [comment]
Hi,
 Thanks for considering me as contributor .Its a great pleasure to contribute a open source project like this.Can you please give me a permission to create a separate branch so that i can submit this patch?

**Comment by imbajin** [comment]
> Hi, Thanks for considering me as contributor .Its a great pleasure to contribute a open source project like this.Can you please give me a permission to create a separate branch so that i can submit this patch?

Thanks for contributing, u can refer [here](https://github.com/hugegraph/hugegraph/blob/master/CONTRIBUTING.md) to **prepare the env** u need (fork project then submit a PR)

**Comment by KirubakaranSP** [comment]
Hi ,I've submitted the merge request.Kindly check and update

**Comment by KirubakaranSP** [comment]
Why I am getting this error after fixing the above bug ?
{"exception":"class java.lang.IllegalArgumentException","message":"The SECONDARY_INDEX type index id can't contains byte '0x00', but got: 0x503a78797a00616263","cause":""}

**Comment by javeme** [comment]
could you please fetch the #1664 code and try again?
```java
git fetch origin pull/1664/head:BRANCHNAME
git checkout BRANCHNAME
```

**Comment by KirubakaranSP** [comment]
am using lastest master

**Comment by KirubakaranSP** [comment]
Am using latest master and the problem still exists.

**Comment by javeme** [comment]
`0x00` is not allowed to contained in the secondary index if the three backend is one of [rocksdb, hbase, and pgsql], the above patch only solves the `0x00` issue of search index.

**Comment by KirubakaranSP** [comment]
Am using search index but i still got the error.
Configuration : Index.createSearchIndexOnVertex(schema, "Constant_ValueIndex", VertexLabel.CONSTANT, Property.VALUE);
error : {"exception":"class java.lang.IllegalArgumentException","message":"The SECONDARY_INDEX type index id can't contains byte '0x00', but got: 0x503a78797a00616263","cause":""}

**Comment by KirubakaranSP** [comment]
any update on this?

**Comment by KirubakaranSP** [comment]
is there any issue with the above mentioned fix ? Is that unicode characters still creating problem?

**Comment by javeme** [comment]
The reason to add the original text to segments (`segments.add(text)`) at the insertion stage is that we can query by a whole string at the query stage, like `Text.contains("(hello world)")`.  if you don't need to query by a whole string,  like `Text.contains("hello world")`(means any result that contains 'hello' or 'world'), please ensure don't add the original text to segments, and feel free to remove the following line in your own code:
https://github.com/hugegraph/hugegraph/pull/1652/files#diff-73ea76c02232c6e703e87380a800acddb7dd181433688417b271aaf133f7d965R903

**Comment by KirubakaranSP** [comment]
private Set<String> segmentWords(String text) {
        Set<String> words = this.textAnalyzer.segment(text);
        for (char ch = INDEX_SYM_ENDING; ch <= INDEX_SYM_MAX; ch++) {
            words.remove(ch);
        }
        return words;
    }

Is the above code enough to fix the special char in secondary indexed properties? Because after changing this code am getting below error 

{"exception":"class java.lang.IllegalArgumentException","message":"Illegal leading char '\\u1' in index property: '\u0001'","cause":""}

Kindly update me with proper solution.Am trying this 0.12.0 version and below are my changes 
**search.text_analyzer=ikanalyzer
search.text_analyzer_mode=max_word**

and in  GraphIndexTransaction above code is replaced in segmentWords method

**Comment by KirubakaranSP** [comment]
Thanks this issue has been fixed.But still exceptions occurs while querying search indexed properties in gremlin.Already issue raised [here](https://github.com/hugegraph/hugegraph/issues/1693).

**Comment by KirubakaranSP** [comment]
Issue fixed in search index but Exception still occurs in secondary index.
Exception : **{"exception":"class java.lang.IllegalArgumentException","message":"The SECONDARY_INDEX type index id can't contains byte '0x00', but got: 0x443a0000","cause":""}**

Fixed code : 
**ConditionQuery.java**

```
 private static String escapeSpecialValueIfNeeded(String value) {
        if (value.isEmpty()) {
            // Escape empty String to INDEX_SYM_EMPTY (char `\u0002`)
            value = INDEX_SYM_EMPTY;
        } else if (value == INDEX_VALUE_EMPTY) {
            value = "";
        } else {
            char ch = value.charAt(0);
            if (ch <= INDEX_SYM_MAX) {
                // escape special symbols, such as just let escape return '\u0000' + value
                value = escape(value);
            }
        }
        return value;
    }
    
    private static String escape(String value) {
    	 return '\u0000' + value;
    }
```

**Comment by KirubakaranSP** [comment]
Can you please check and update on this ?

**Comment by javeme** [comment]
Sorry for the wrong way mentioned earlier. you may try to implement escape() like:
```java
private static String escape(String value) {
    value = value.replace("\u0000", "\u0003")
    return '\u0003' + value;
}
```

**Comment by KirubakaranSP** [comment]
How can i use hugegraph-hubble for 0.12.0 version? Hubble shows version mismatch error for server version 0.12.0.
