### ISSUE TITLE
[Question] hugegraph支持TP运行的pagerank算法吗

### ISSUE THREAD

**Issue by Catriminal** [hugegraph/hugegraph#1650]
### Problem Type (问题类型)

others (please edit later)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.x
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

请问现在hugegraph支持单机运行的pagerank算法吗，只找到hugegraph-computer那边的分布式算法，另外如果支持自定义算法开发的话，请问是哪个模块呢？谢谢！

**Comment by imbajin** [comment]
支持的, 参考一下文档/代码里的 [traverser](https://github.com/hugegraph/hugegraph/tree/master/hugegraph-api/src/main/java/com/baidu/hugegraph/api/traversers) 包下, 所有自定义的算法都可以放这. 单机实现后也欢迎推到社区, 会帮忙 review

**Comment by Catriminal** [comment]
请问有提供并行将边属性聚合到顶点属性上的接口嘛？谢谢~

**Comment by Catriminal** [comment]
> 支持的, 参考一下文档/代码里的 [traverser](https://github.com/hugegraph/hugegraph/tree/master/hugegraph-api/src/main/java/com/baidu/hugegraph/api/traversers) 包下, 所有自定义的算法都可以放这. 单机实现后也欢迎推到社区, 会帮忙 review

那请问有提供并行将边属性聚合到顶点属性上的接口嘛？谢谢~

**Comment by imbajin** [comment]
> > 支持的, 参考一下文档/代码里的 [traverser](https://github.com/hugegraph/hugegraph/tree/master/hugegraph-api/src/main/java/com/baidu/hugegraph/api/traversers?rgh-link-date=2021-11-18T09%3A03%3A53Z) 包下, 所有自定义的算法都可以放这. 单机实现后也欢迎推到社区, 会帮忙 review
> 
> 那请问有提供并行将边属性聚合到顶点属性上的接口嘛？谢谢~

TP 这边似乎没有这种接口
