### ISSUE TITLE
[Question] 有提供metrics监控接口吗？能否通过prometheus的json_exporter实现监控指标数据的转换

### ISSUE THREAD

**Issue by huangcaiyun** [hugegraph/hugegraph#1656]
### Problem Type (问题类型)

others (please edit later)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.2
- Backend: RocksDB x nodes, HDD or SSD 

### Your Question (问题描述)

在prometheus的环境下，访问ip:18080/metrics ，得到的页面结果如下：
![d9536287313c814f99335d29b2460c1](https://user-images.githubusercontent.com/16162632/141969824-6deb2716-7d14-405b-9dd2-d78820b21919.png)
![9e5b3b1cdaf38e1b1a451cec022adc5](https://user-images.githubusercontent.com/16162632/141969846-b9a513d7-468a-4819-b238-e26fb40ea359.png)

出现这个错误的原因是因为prometheus无法转化metrics的数据导致的吗？目前有没有提供exporter来解决数据转换的问题呢？

**Comment by imbajin** [comment]
是的, 原本的 metrics 格式是自定义的, prometheus 的接口如果是你们自己使用, 可以参考一个测试的 exporter [接口](https://github.com/starhugegraph/hugegraph/blob/a48961c16ca52fb32f7866bca3bca5d3c1f30da3/hugegraph-api/src/main/java/com/baidu/hugegraph/api/metrics/MetricsAPI.java#L292)实现.

社区版后续会集成进来. 也欢迎你基于 beta 版重构一下

**Comment by huangcaiyun** [comment]
这个exporter是实现了promethues的接口吗？这个是你们在新版本中集成进来测试的代码？

**Comment by imbajin** [comment]
> 这个exporter是实现了promethues的接口吗？这个是你们在新版本中集成进来测试的代码？

细节我没看, 你可以简单看看, 应该是做了个适配转换. 可以确认它是可用的, 也是先做个测试看看效果

**Comment by jiayouchongmingniao** [comment]
https://github.com/starhugegraph/hugegraph/blob/a48961c16ca52fb32f7866bca3bca5d3c1f30da3/hugegraph-api/src/main/java/com/baidu/hugegraph/api/metrics/MetricsAPI.java#L292

修改290行，APPLICATION_TEXT_WITH_CHARSET 为 APPLICATION_JSON_WITH_CHARSET，成功。谢谢楼上各位 @imbajin @huangcaiyun
