### ISSUE TITLE
执行参数超过255个报错

### ISSUE THREAD

**Issue by z7658329** [hugegraph/hugegraph#1665]
### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.x
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

General error during class generation: The max number of supported arguments is 255, but found 732
java.lang.IllegalArgumentException: The max number of supported arguments is 255, but found 732

or语句里不能超过255个，超过就报上面的错误  这种应该如何避免呢？fieldA加了second索引，执行语句：
g.V().hasLabel("v_x").or(
has("fieldA","x1"),
 has("fieldA","x2"),
 has("fieldA","x3")
 ...
 ).range(0,100)

**Comment by z7658329** [comment]
暂时想到的是如果参数超过255则按照255分组，然后通过union 多个or的结果， 执行了一下 能实现，但是性能非常差... 
和上面的语句 查询时间有10倍以上的差别....
g.V().hasLabel("v_x").union(
or(has("fieldA","x1"),has("fieldA","x2")),
  
or(has("fieldA","x3"),has("fieldA","x4"))
  ).range(0,100)

**Comment by imbajin** [comment]
有试过 `binding()` 么.  (refer #1509 )

**Comment by z7658329** [comment]
![image](https://user-images.githubusercontent.com/5474723/142962846-f6f957b2-bd1a-437d-8057-37430082843c.png)

**Comment by javeme** [comment]
可以使用`within`语句代替`or`：
```java
g.V().hasLabel(label).has('field', within('v1', 'v2', 'v3'...))
```
