### ISSUE TITLE
[Question] How to create a new build?

### ISSUE THREAD

**Issue by KirubakaranSP** [hugegraph/hugegraph#1671]
### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.x
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

I want to release a new build with latest changes.Can you please guide me how to create a build ?

**Comment by imbajin** [comment]
refer #1668 , u could do the following steps:
1. `mvn package -DskipTests ` in hugegraph directory , and u'll get the dir `0.12.x` & tar package
2. find the jraft jar in v0.11.2 ./lib
3. replace the `jraft*.jar` in 0.12 `./lib` with the`./lib/jraft-core-1.3.5.jar` in  version `0.11.2` .
4. init-store & start the server

And any more exception with the log u could paster here.

**Comment by KirubakaranSP** [comment]
This is the exception am facing while connecting from java API

java.lang.IllegalStateException: The version 0.66.0.0 of 'hugegraph-api in server' is not in [0.38, 0.59)|
com.google.common.base.Preconditions.checkState(Preconditions.java:531)|
com.baidu.hugegraph.util.E.checkState(E.java:68)|
com.baidu.hugegraph.util.VersionUtil.check(VersionUtil.java:65)|
com.baidu.hugegraph.driver.HugeClient.checkServerApiVersion(HugeClient.java:100)|
com.baidu.hugegraph.driver.HugeClient.initManagers(HugeClient.java:83)|
com.baidu.hugegraph.driver.HugeClient.<init>(HugeClient.java:63)|
com.baidu.hugegraph.driver.HugeClientBuilder.build(HugeClientBuilder.java:67)|

**Comment by imbajin** [comment]
> 

seems u are using the older version for `HugeClient`, it doesn't allow use  lower version for client, try 3 ways:
1. update your client version to adopt with the latest server
2. comment the version [check code](https://github.com/hugegraph/hugegraph-client/blob/6f4876f9911362698dfbf2a652f0843df2103bdd/src/main/java/com/baidu/hugegraph/driver/HugeClient.java#L83) by yourself in huge client (warn: it will lack version protection and hide some version inconsistent problem)
3. turn down the server version from 0.66 -> 0.58 in [APIVersion](https://github.com/hugegraph/hugegraph/blob/03fb38008307e3e514d8aa1d39306d9cda1d27ff/hugegraph-api/src/main/java/com/baidu/hugegraph/version/ApiVersion.java#L122) (have the same risk as above)

**Comment by KirubakaranSP** [comment]
After updating the client version from 1.9.1 to 1.9.6 ,still facing the same problem.And FYKI , the jraft jar version in 0.11.2 is jraft-core-1.3.3.jar not .jraft-core-1.3.5.jar.Is there any problem with this?

**Comment by imbajin** [comment]
> 

if the latest client version still lower than server, u could try another 2 way (hard code), we'll release the new client version for V0.12 in December (this year)

**Comment by KirubakaranSP** [comment]
Thanks for the info !!Worked

**Comment by KirubakaranSP** [comment]
changing version from 0.58 still creates same error .error log 

ERROR :: java.lang.IllegalStateException: The version 0.66.0.0 of 'hugegraph-api in server' is not in [0.38, 0.66)
