### ISSUE TITLE
[Question] 针对order by的字段需要添加索引吗

### ISSUE THREAD

**Issue by z7658329** [hugegraph/hugegraph#1676]
### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.x
- Backend: MYSQL 
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  100W vertices, 200W edges 

### Your Question (问题描述)

针对order by语句，需要为排序字段添加索引处理吗？底层原理是内存排序？
![image](https://user-images.githubusercontent.com/5474723/144207896-81e4c18f-92d0-433c-9f6b-e8eb3aa2805b.png)

如上图，不做orderby的查询 要快很多

**Comment by imbajin** [comment]
如果你说的 order.by 在 gremlin 的实现那肯定是内存排序, 就是先把数据读上来然后做了个语法糖.

huge 对有些操作做了计算下推, 这个排序应该没有, 如果这个字段经常有范围类查询, 可以添加 range 索引的. (边可以用 sortKey)
