### ISSUE TITLE
[Question] range分页查询出现数据重复

### ISSUE THREAD

**Issue by z7658329** [hugegraph/hugegraph#1677]
### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

Server Version: v0.11.x
Backend: MYSQL
OS: xx CPUs, xx G RAM, Centos 7.x
Data Size: 100W vertices, 200W edges

### Your Question (问题描述)

g.V().hasLabel("v_app").has("appSrcType","taf").count()总数量为1W条，然后想通过range实现分页，发现从第3条语句开始返回数据是一样的，请问为什么？
1.g.V().hasLabel("v_app").has("appSrcType","taf").range(0,500)
2.g.V().hasLabel("v_app").has("appSrcType","taf").range(500,1000)
3.g.V().hasLabel("v_app").has("appSrcType","taf").range(1000,1500)
4.g.V().hasLabel("v_app").has("appSrcType","taf").range(1500,2000)
5.g.V().hasLabel("v_app").has("appSrcType","taf").range(2000,2500)

下图是第3和第4次查询的结果，结果里都是重复的数据
![image](https://user-images.githubusercontent.com/5474723/144237785-b70a2d39-56fa-4840-baee-b4d2795d02b5.png)

**Comment by javeme** [comment]
@z7658329 看起来可能是因为有残留索引（关于残留索引可参考：https://github.com/hugegraph/hugegraph/issues/1495 ），请问是否有大量覆盖过数据？


不过分页确实建议使用rest api，以page参数的方式获取。

**Comment by z7658329** [comment]
感谢回复，确实该顶点类型我们覆盖过数据 这种要怎么修数？
