### ISSUE TITLE
hugegraph是高可用的吗，是否支持动态扩展？如何进行配置

### ISSUE THREAD

**Issue by bigdata-eqxiu** [hugegraph/hugegraph#17]
同上

**Comment by zhoney** [comment]
高可用可以从多个维度来讲，包括
- 图的server引擎高可用，目前HugeGraphServer服务本身并没有高可用实现，只有一套简单的服务监控及失效拉起的功能（server的高可用在开发计划中）
- 存储后端高可用，Cassandra或HBase等本身支持高可用。

**Comment by bigdata-eqxiu** [comment]
@zhoney 如果元数据与数据都在Cassandra数据库中存储 ，理论上我是可以启动多个HugeGraphServer来对我服务的对吗？？

**Comment by zhoney** [comment]
@bigdata-eqxiu HugeGraphServer服务有缓存机制，元数据和图数据都会缓存，多个HugeGraphServer同时连一个Cassandra后端，可能会出现数据不一致的现象

**Comment by sunxiang0918** [comment]
那是否就是说 目前的 hugegraph是没有高可用的么?

**Comment by javeme** [comment]
@sunxiang0918 目前hugegraph商业版支持HA高可用。

**Comment by suesunss** [comment]
@javeme Hi, 请问目前商业版有 offers/pricing 说明吗，我在 hugegraph-doc 上没有找到。

**Comment by javeme** [comment]
@suesunss 有的，你可以关注一下微信公众号`HugeGraph`进行留言。

**Comment by oushu1liwenhui1** [comment]
> @sunxiang0918 目前hugegraph商业版支持HA高可用。

麻烦问下，商业版是否就是BGraph?

**Comment by javeme** [comment]
> 麻烦问下，商业版是否就是BGraph?

@oushu1liwenhui1 不是的，名称还是HugeGraph。

**Comment by zhoney** [comment]
Close this issue now due to having not been updated in a long time. Feel free to reopen it if needed.
