### ISSUE TITLE
hugegraph 0.8.0请问预计什么时候发布？

### ISSUE THREAD

**Issue by hklmuaqmn** [hugegraph/hugegraph#171]
hugegraph 0.8.0请问预计什么时候发布？ 等着新的API还有 cassandra的二级索引bug修复解救我们。。

**Comment by Linary** [comment]
初步预计 2018.11.16 发布 0.8.0 版本，如遇意外情况，最多推迟一周。

**Comment by yuyang0** [comment]
我觉得应该尽量发一些小版本来修复bug，现在一些已知的bug导致数据库基本没法用。 @Linary
