### ISSUE TITLE
创建边时，基于不同的顶点，能否创建相同类型的边？

### ISSUE THREAD

**Issue by alfredliukai** [hugegraph/hugegraph#1718]
### Problem Type (问题类型)

struct / logic (架构 / 逻辑设计问题)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

HugeGraph-Hubble模块

### Your Question (问题描述)

搭建好HugeGraph-Hubble模块，创建边元数据时，基于不同的顶点，创建相同类型的边。目前系统不满足需求？

**Comment by imbajin** [comment]
历史 issue 里有相关问题可以查一下. 目前的确不支持, 不过你可以先用顶点label 作为前缀区分

**Comment by alfredliukai** [comment]
好的，谢谢。我查找下。
