### ISSUE TITLE
[创建节点] 调用服务测试创建节点

### ISSUE THREAD

**Issue by megodlike** [hugegraph/hugegraph#1728]
### Problem Type (问题类型)

rest-api (结果不合预期)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.12.0
- Backend: postgresql, HDD
- OS: 4 CPUs, 4 G RAM, Centos 7.x  vm虚拟机
- Data Size:  1 vertices

### Your Question (问题描述)

c#调用创建节点服务，报400错误
![image](https://user-images.githubusercontent.com/34566983/148873452-da876c51-8405-44fa-9554-db736c610647.png)
![image](https://user-images.githubusercontent.com/34566983/148873489-10f8626d-517e-4dc4-958b-1d85e1127327.png)

**Comment by imbajin** [comment]
可以麻烦先用 curl 的方式请求一下 http 请求, 看一下具体的返回值么.

先可以不用 c# 的方式访问, 这样方便排除问题.

**Comment by megodlike** [comment]
调整了一下参数和配置，现在报下面错误了
参数：
{"label": "node1","properties": {"name": "www.soso.com","code":"12"}}
错误信息：
{"exception":"class java.lang.IllegalArgumentException","message":"Must customize vertex string id when id strategy is 'CUSTOMIZE_STRING' for vertex label 'node1'","cause":""}

**Comment by megodlike** [comment]
应该是参数有问题，帮助里面也提到了，但是我实在搞不清楚应该是什么样子，麻烦指正一下，谢谢！

**Comment by megodlike** [comment]
刚修改了对象，增加了节点id，如下：然后就好了，似乎帮助里面没看到啊
{"label": "node1","properties": {"name": "www.soso.com","code":"12"},**"id":"234"**}

**Comment by imbajin** [comment]
在 http 的 url 里面可以直接传入 `id` 字段, 跟在参数后就行, post 里主键模式也可以不用指定 id, **自定义数值/字符串模式**才需要. 你说的文档应该是用的主键模式自动生成的 id

**Comment by megodlike** [comment]
> 在 http 的 url 里面可以直接传入 `id` 字段, 跟在参数后就行, post 里主键模式也可以不用指定 id, **自定义数值/字符串模式**才需要. 你说的文档应该是用的主键模式自动生成的 id

我的ID采用的自定义的数值类型或者文本类型，非自动生成的
![image](https://user-images.githubusercontent.com/34566983/148925456-533b102a-bc7a-4a97-a3ea-2e7fb81a2158.png)
![image](https://user-images.githubusercontent.com/34566983/148925498-78365ff6-2dab-4d7e-a59b-693fe4d8a7de.png)


url后面直接跟着id不行吧
http://192.168.10.137:8080/graphs/postgresql/graph/vertices/2
body:
{"label": "city_region","properties": {"name": "上海市"}}
报错：{"exception":"class javax.ws.rs.NotAllowedException","message":"HTTP 405 Method Not Allowed","cause":""}


http://192.168.10.137:8080/graphs/postgresql/graph/vertices
body：
{"label": "city_region","properties": {"name": "上海市"},"id":2}
可以正确执行

**Comment by imbajin** [comment]
> 我的 ID 采用的自定义的数值类型或者文本类型，非自动生成的

意思是, 你说文档没有提到 `id` , 原因应是它基于自动生成 id 作为前提写的应该

> url 后面直接跟着 id 不行吧
> http://192.168.10.137:8080/graphs/postgresql/graph/vertices/2

意思两个是, 一是 POST 请求也可以 URL 中携带属性参数, 另一个是你可以参考一下历史 issue 里的传入方式有具体格式, 最后你提示 405 似乎是请求方式就被拒绝了

总之, 创建点/边的时候, 根据是否指定 ID, 来决定是否需要传入 `id` 字段.

**Comment by megodlike** [comment]
@imbajin 好的，谢谢明白了，另外昨天还遇到一个问题，可能需要发起一个新提问，非常感谢！
