### ISSUE TITLE
[Question] HugeGraph运行一段时间后 rest请求方式插入数据一直报错"exception":"class com.baidu.hugegraph.HugeException","message":"The rest server is too busy to write

### ISSUE THREAD

**Issue by linkarl** [hugegraph/hugegraph#1744]
### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.2
- Backend: Mysql
- OS: 8 CPUs, 32 G RAM, Centos 7.x 
- Data Size:  10k vertices, 10k edges 

### Your Question (问题描述)

在我们业务运行一段时间后 HugeGraph无法使用rest请求的方式插入数据报错为The rest server is too busy to write
使用HugeGraph-Hubble也无法连接上此数据库  就算连上了也一直查询时间超时
我们后端使用的是mysql数据库存储 排查mysql数据连接500+ 远小于5000的限制 重启mysql数据库 也没有恢复 
重启HugeGraph服务后正常 
我们使用的线程配置  restserver.max_worker_threads=64
然后我排查了 磁盘空间 内存什么的 都够用 还不清楚是什么问题造成的

**Comment by imbajin** [comment]
可以稳定复现么, 可以尝试构建一下最小的复现方式?

另外, 你有试过重启 hugeserver 么, 出现这个报错先尝试重启 server.   至与恢复问题, 得结合版本来看

可以尝试升级到 0.12 最新版看看有没有这个问题. 因为链接 mysql 这块做了优化, 之前逻辑优化了

**Comment by linkarl** [comment]
重启 hugeserver是好了  好的  我试下升级下 0.12
另外restserver.max_worker_threads=64 会出现说 我rest调用暂用完hugegraph的64连接？  
我们业务有两个库在HugeGraph上 其中一个库是运行一段时候有问题插入不了数据 另一个访问量少些的就没问题

**Comment by imbajin** [comment]
那个参数默认是 rest-server 线程池的连接数吧, 你可以通过 jstack 或者 arthas 查看下线上是否会占用满 (一般不会)

如果满了可以调大一些, 或者调整一下 `batch_insert` (导入数据) 占用线程池的比例
