### ISSUE TITLE
从0.11.2升级到0.12.0版本，同样的gremlin语句执行返回的结果不一样，有没有相关的迁移注意事项或指引

### ISSUE THREAD

**Issue by vincentshu** [hugegraph/hugegraph#1745]
### Bug Type (问题类型)

gremlin (结果不合预期)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.12.0
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  少于1000vertices, 少于1000 edges 

### Expected & Actual behavior (期望与实际表现)

```groovy
g.V().hasLabel('cmdb_model_group').has('cmdb_parent_id', '-1')
  .repeat(__.out('cmdb_parent').has('tenant_id', 'operate'))
  .until(__.outE('cmdb_parent').count().is(0)).tree()
```

同样的gremlin语句，在0.11.2版本中执行返回的数据和在0.12.0版本中执行返回的数据不一样。
数据库的数据是一样的。
期望：执行结果一样
实际：执行结果不一样

[result.zip](https://github.com/hugegraph/hugegraph/files/7965322/result.zip)

**Comment by imbajin** [comment]
能贴一下你那边不同的结果截图么(看到有个附件下载失败了), 然后看看能不能提供一个最小复现的数据集

方便复现一下看看, 能尽可能减少语句长度和数据集大小为宜.

**Comment by vincentshu** [comment]
我跟踪了一下代码，发现是HugeVertexStepStrategy 这块优化后导致tree()查询结果和之前的0.11.2版本不一样了。
看代码好像是没有path查询，就做了优化。
我照着withPath的方法写了一个withTree的方法，然后结果就和原来一致了，不知道这样改行不行
我修改了类**HugeVertexStepStrategy 
    protected static boolean containsTree(Traversal.Admin<?, ?> traversal) {
        boolean hasPath = TraversalHelper.getStepsOfClass(
                TreeStep.class, traversal).size() > 0;
        if (hasPath) {
            return true;
        } else if (traversal instanceof EmptyTraversal) {
            return false;
        }

        TraversalParent parent = traversal.getParent();
        return containsTree(parent.asStep().getTraversal());
    }**

       boolean batchOptimize = false;
        if (!steps.isEmpty()) {
            boolean withPath = HugeVertexStepStrategy.containsPath(traversal);
            **boolean withTree = HugeVertexStepStrategy.containsTree(traversal);**
            boolean supportIn = TraversalUtil.getGraph(steps.get(0))
                                             .backendStoreFeatures()
                                             .supportsQueryWithInCondition();
            batchOptimize =**!withTree** && !withPath && supportIn;
        }

**Comment by javeme** [comment]
@vincentshu 非常感谢你的分析，应该是这个原因导致的（当时可能没有考虑到tree这种场景），如果可以的话，非常欢迎你贡献以上代码，感谢。
代码贡献流程：https://github.com/hugegraph/hugegraph/blob/master/CONTRIBUTING.md

**Comment by javeme** [comment]
@vincentshu 感谢贡献代码~ 代码还需要一些小修改，详见review comments，修改之后，可使用如下命令追加到分枝后面进行提交：
```sh
git commit -a
git push vincentshu bugfix-branch
```
