### ISSUE TITLE
内存使用不断增长，应该是堆外内存在不断增长

### ISSUE THREAD

**Issue by vincentshu** [hugegraph/hugegraph#1750]
### Problem Type (问题类型)

performence (性能优化)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.12.0
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  1000- vertices, 1000- edges 

### Your Question (问题描述)

项目启动后，top命令观察到的使用的内存就一直在增长。
数据量很小，都不超过1000
后台只有一个定时查询，每3分钟一次，
堆使用时正常的，没有发生堆内存溢出，所以怀疑是堆外内存在一直增长。
按照我的理解，现在这种使用场景，内存使用不应该一直增长，如果没用缓存，内存使用应该只在查询的那一刻会增长，然后应该就会下降下来，如果用了缓存，定时查询的请求参数是一样的，也不应该会一直增长。

所以我的问题是，现在对于堆外内存的使用，具体是怎么定义的，哪些操作或使用方式会使用堆外内存，堆外内存会不会释放，什么时候释放，堆外内存使用有没有设置使用上限。
以上问题，麻烦帮忙解答下，不胜感谢！

**Comment by javeme** [comment]
请给出具体的增长情况，包括堆内存（jmap -heap PID）、进程内存（top PID）。

需要注意的是：hugegraph服务启动时，分配的堆内存默认并不会归还给操作系统（出于性能考虑），如果有需要归还，可以配置min heap size（比如`-Xmx512m`）比max heap size小，此外还可以调整MaxHeapFreeRatio到更小值（默认70%）。

目前堆外内存可能会占用较大的场景：
1. 堆外缓存（启用l2 cache的情况下会占用。内存大小可通过cache capacity进行限制）
2. RocksDB会占用堆外内存（使用RocksDB后端存储的情况下会占用，主要包括memtable/pin-iterator/block-cacher/bloom-filter等。内存大小根据数据量而定）

**Comment by imbajin** [comment]
可以给一下你用 `jstat -gcutil` 和 `jinfo` 的信息, 以及相关的变化监控内存走势图

本地可以直接用自带的 vmtools / jprofiler 工具更好, 看看堆内外内存变化情况, 以及到底是什么对象占了内存. 特别是你的测试数据集很小, 本地 attach 然后动态看看最好, 然后截图贴一下, thx~

**Comment by imbajin** [comment]
可以给一下你用 `jstat -gcutil` 和 `jinfo` 的信息, 以及相关的变化监控内存走势图

本地可以直接用自带的 vmtools / jprofiler 工具更好, 看看堆内外内存变化情况, 以及到底是什么对象占了内存. 特别是你的测试数据集很小, 本地 attach 然后动态看看最好, 然后截图贴一下, thx~
