### ISSUE TITLE
[Question] hugegraph升级到0.12.0版本后，查询报错：gremlin执行失败，too many conditions(130) each query

### ISSUE THREAD

**Issue by aerobe** [hugegraph/hugegraph#1751]
### Problem Type (问题类型)

gremlin (结果不合预期)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

不依赖环境

### Your Question (问题描述)

[Question] hugegraph从0.10.4升级到0.12.0版本后，查询报错：gremlin执行失败，too many conditions(130) each query。经过测试条件在100以下（定向过滤很多不同类型的边）时可正常执行，请问下如何修改配置解决该问题，谢谢

**Comment by imbajin** [comment]
可以参考一下 #1665  下面的回复, 以及关联 PR
