### ISSUE TITLE
[Question] hugegraph 0.12 用hbase作单机后端存储导入Twitter-2010的数据落盘有500g+

### ISSUE THREAD

**Issue by YT-FF** [hugegraph/hugegraph#1752]
### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.12.0
- Backend: Hbase, HDD 
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  4000万点，14亿边，Twitter-2010

### Your Question (问题描述)

hugegraph 0.12 用hbase作单机后端存储导入Twitter-2010的数据，看落盘大小有500g+，原始数据只有24.6g，这是为什么

**Comment by imbajin** [comment]
应该不能吧?  有几个问题需要确认一下:
- hbase 作为**单机**后端是啥意思? 这里单机是说单个 hbase rs 节点么, 还是 hdfs 单节点
- 另外落盘大小是如何统计的呢? (算3副本, 还是除以副本数之后, 正常计算应该算文件大小-1副本)
- hbase 自身的 wal 临时目录有算入么, 还是只算的 hfile 的数据目录

相关信息可以贴全一些, 或者截图一下看看

另外可以**同时**试试用 rocksdb 后端(内置)直接导试试, 推特数据小, loader 估计几小时也可以导完.

**Comment by YT-FF** [comment]
> 应该不能吧? 有几个问题需要确认一下:
> 
> * hbase 作为**单机**后端是啥意思? 这里单机是说单个 hbase rs 节点么, 还是 hdfs 单节点
> * 另外落盘大小是如何统计的呢? (算3副本, 还是除以副本数之后, 正常计算应该算文件大小-1副本)
> * hbase 自身的 wal 临时目录有算入么, 还是只算的 hfile 的数据目录
> 
> 相关信息可以贴全一些, 或者截图一下看看
> 
> 另外可以**同时**试试用 rocksdb 后端(内置)直接导试试, 这样直接 `du` 查看目录最简单, 推特数据小, loader 估计几小时也可以导完.

是Hbase伪分布式部署，测落盘大小用的 hadoop fs -du -h

**Comment by imbajin** [comment]
截图就好分析多了
![image](https://user-images.githubusercontent.com/17706099/153394298-9d120d09-7f80-4339-9d52-b655816a3bb9.png)

另外不知道这是什么版本的 hdfs, 显示的是1副本大小么, 新版(hdfs)应该会备注副本数在第二列才对

**Comment by YT-FF** [comment]
> 截图就好分析多了
> 
> 另外不知道这是什么版本的 hdfs, 显示的是1副本大小么, 新版(hdfs)应该会备注副本数在第二列才对

hadoop版本2.6.0，没有设置副本数量应该是默认3副本，hadoop fs -du -h我不知道是否计算了备份的大小

**Comment by imbajin** [comment]
2.6的 hdfs 应该会显示三列吧, 你可以直接用 `fs -ls` 查看一下, 它会在第几列显示副本数. 不知道是不是你这个 hdfs client 的版本较低导致的.

然后你可以尝试对 `g_ie` 和 `g_oe` 做一次 major_compact.  然后关闭一下默认开启的 label 索引 (在创建 schema 的时候, 设置enableLabelIndex(false), 详细可以看看文档)
