### ISSUE TITLE
[Question] 请问HugeGraph是否提供sdk

### ISSUE THREAD

**Issue by bachml** [hugegraph/hugegraph#1754]
### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.x
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

请问HugeGraph是否有sdk形态，可以作为jar包提供给其他项目来使用？
谢谢

**Comment by javeme** [comment]
官方提供了Java版的Client：
https://github.com/hugegraph/hugegraph-client
Maven地址：
https://mvnrepository.com/artifact/com.baidu.hugegraph/hugegraph-client

请在项目中添加如下依赖即可：
```xml
<!-- https://mvnrepository.com/artifact/com.baidu.hugegraph/hugegraph-client -->
<dependency>
    <groupId>com.baidu.hugegraph</groupId>
    <artifactId>hugegraph-client</artifactId>
    <version>2.0.1</version>
</dependency>

```

**Comment by bachml** [comment]
> 官方提供了Java版的Client： https://github.com/hugegraph/hugegraph-client Maven地址： https://mvnrepository.com/artifact/com.baidu.hugegraph/hugegraph-client
> 
> 请在项目中添加如下依赖即可：
> 
> ```
> 
> <dependency>
>     <groupId>com.baidu.hugegraph</groupId>
>     <artifactId>hugegraph-client</artifactId>
>     <version>2.0.1</version>
> </dependency>
> ```

hi，谢谢你的回复。

hugegraph-client似乎仍然需要启动server，我的需求是希望在不启动server的情况下把hugegraph作为一个三方件导入到另一个项目，接受用户的gremlin语句，解析后转而调用Core的代码。请问有这样的接口吗？谢谢。

**Comment by imbajin** [comment]
如果只是需要调用 core 解析, 你可以尝试直接引入 `hugegraph-core` 的 maven 依赖就行.

**Comment by javeme** [comment]
如果需要将hugegraph嵌入到了一个项目，可以参考hugegraph-example子项目：
https://github.com/hugegraph/hugegraph/blob/master/hugegraph-example/pom.xml#L17
https://github.com/hugegraph/hugegraph/blob/master/hugegraph-example/src/main/java/com/baidu/hugegraph/example/Example1.java#L64
