### ISSUE TITLE
[Bug]Dockerfile执行到第30行时报错

### ISSUE THREAD

**Issue by creact1990** [hugegraph/hugegraph#1759]
### Problem Type (问题类型)

other exception / error (其他异常报错)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.12.0
- Backend: RocksDB
- OS: xx CPUs, xx G RAM, ubuntu 
- Data Size:  0 vertices, 0 edges 

### Your Question (问题描述)

使用[Dockerfile](https://github.com/hugegraph/hugegraph/blob/master/Dockerfile)构建镜像失败，经过定位是第30行的
sed -n '63p' ./bin/start-hugegraph.sh | grep "&" > /dev/null && sed -i 63{s/\&$/#/g} ./bin/start-hugegraph.sh
返回code=1，请问这句的作用是？同样31行的sed也返回1。
定位过程见下面两个截图。
![image](https://user-images.githubusercontent.com/11734822/154233306-55818f8b-31a9-44f7-a834-cd1a09bf3ccd.png)
![image](https://user-images.githubusercontent.com/11734822/154233409-7b1a0966-e57b-4130-885f-8c2c42670ffa.png)

另外，如果把30和31行两个sed注释掉，构建出的镜像可以启动，但启动成功后容器自动kill，这可能是什么原因？
![image](https://user-images.githubusercontent.com/11734822/154234316-fae54231-7704-4b38-bb9a-56973d82c802.png)

而把51行的ENTRYPOINT注释掉后，手动进入镜像执行start-hugegraph.sh则可以正常服务。

**Comment by imbajin** [comment]
你用了最新的代码呢, 新旧版的脚本行数有点小区别, 你可以先临时改一下行数 (逻辑其实很简单, 就是让 server 保持前台运行)

后续我们会更新最新的 Dockerfile, 也欢迎你贡献, 相关 issue 见 #840

**Comment by creact1990** [comment]
> 
是的，用最新的0.12.0。
对，果然是30行的原因导致进程无法前台运行。
后续大概什么时候能更新Dockerfile？

**Comment by imbajin** [comment]
大概时间在项目进入 Apache 社区左右? 相关需要和讨论可以在 #840 那个 issue 里说, 最好的后台解决应该是加一个开关, 而不是现在这样 hard code 注释或修改, 这样后续也都能兼容
