### ISSUE TITLE
开源最新版本hugegraphServer高可用支持了吗？

### ISSUE THREAD

**Issue by wuchaojing** [hugegraph/hugegraph#1760]
### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

无

### Your Question (问题描述)

看之前的issue是说最新开源版本已经支持了hugegraphServer的高可用（缓存的一致性），请问下相应的代码在哪块呢？感谢回复。https://github.com/hugegraph/hugegraph/issues/435

**Comment by javeme** [comment]
已经支持了，请启用rpc族配置项即可，比如：
```ini
rpc.server_host=host1
rpc.remote_url=host1,host2,host3
```

**Comment by wuchaojing** [comment]
> 
好的，感谢
