### ISSUE TITLE
The version 0.27.0.0 of 'hugegraph-api in server' is not in [0.38, 0.68)

### ISSUE THREAD

**Issue by yangZhengW** [hugegraph/hugegraph#1762]
### Problem Type (问题类型)

server status (启动/运行异常)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

hugegraph
-release release-0.7

hugestudio
- master分支

### Your Question (问题描述)

http://127.0.0.1:8078/graphs 
反馈正常

huge studio 启动正常 执行命令报错
Failed to connect HugeGraphServer: java.lang.IllegalStateException: The version 0.27.0.0 of 'hugegraph-api in server' is not in [0.38, 0.68)

**Comment by imbajin** [comment]
报错信息来看, 你的 huge server 版本也太低了吧? 0.27 应该是上古时期的了? 考虑升级一下
