### ISSUE TITLE
hugegraph不存在

### ISSUE THREAD

**Issue by xiamuyuan** [hugegraph/hugegraph#1765]
### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

![image](https://user-images.githubusercontent.com/45248954/155670479-242ca7c5-9769-4345-a50e-84d984b66df3.png)

### Your Question (问题描述)

您好

背景：我在ubuntu下载和解压了HugeGraphServer，仅仅操作修改 hugegraph.properties

backend=memory
serializer=text
![image](https://user-images.githubusercontent.com/45248954/155676240-741b57bf-c5aa-4351-8bc9-c1be5e5352a7.png)
![image](https://user-images.githubusercontent.com/45248954/155676256-b91fe2ba-3cc5-48cf-911b-2e1c0fd67994.png)

然后执行如下截图的步骤
问题：图没有显示，查了很久不知道什么原因，麻烦看下，非常感谢

![image](https://user-images.githubusercontent.com/45248954/155675622-0800219f-b4f9-485e-baee-dc47e70a4886.png)

**Comment by imbajin** [comment]
感谢反馈, 你直接访问 `graphs` api 提示有什么图呢? 看你命令里尝试了一下, 不过没有 curl 查了.
先确认一下图名是否存在. 然后可以试试新增一个图, 用 rocksdb 看看是不是正常. 应该就能排查了

**Comment by xiamuyuan** [comment]
![image](https://user-images.githubusercontent.com/45248954/155915502-d6e428bb-c44f-4500-ba44-63e344584662.png)
hi，原本的操作，显示如上所示

现在问题已经得到解决，删除hugegraph-0.12.0文件后重新操作，这次通过vim conf/graphs/hugegraph.properties修改配置，不是直接通过windows打开文件进行修改。谢谢你

![image](https://user-images.githubusercontent.com/45248954/155929515-fae207bd-8d89-46be-8d19-97589c24697a.png)
![image](https://user-images.githubusercontent.com/45248954/155929526-8451565e-2bb4-4e10-b289-b0e611293518.png)
