### ISSUE TITLE
[Feature] maven仓库还未收录0.12.0版本

### ISSUE THREAD

**Issue by linkarl** [hugegraph/hugegraph#1766]
### Feature Description (功能描述)

https://mvnrepository.com/artifact/com.baidu.hugegraph/hugegraph-core
还没有最新的0.12.0版本
可以帮忙上传收录下么

**Comment by imbajin** [comment]
@javeme seems we forget to upload it? (release ci may do it?)

感谢反馈. 另外你着急用可以先本地把源码包下 lib 里的 0.12 的库安装到本地, 这样就可以先用了

**Comment by linkarl** [comment]
我们流水线构建依赖这块  是否可以把最新版本0.12.0推送到maven仓库？当前maven库中的还是0.11.2的版本

**Comment by javeme** [comment]
@coderzc May be the release ci doesn't take effect?
https://github.com/hugegraph/hugegraph/blob/master/.github/workflows/release.yml

**Comment by coderzc** [comment]
> @coderzc May be the release ci doesn't take effect? https://github.com/hugegraph/hugegraph/blob/master/.github/workflows/release.yml

yes, the release ci failed

**Comment by linkarl** [comment]
老哥们 中心仓库还是没有0.12.0版本  https://mvnrepository.com/artifact/com.baidu.hugegraph/hugegraph-core
