### ISSUE TITLE
[Question] hugegraph未来规划

### ISSUE THREAD

**Issue by wuchaojing** [hugegraph/hugegraph#1774]
### Problem Type (问题类型)

others (please edit later)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.x
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

可以列一下hugegraph开源版未来半年或一年的重点规划吗？避免各使用方有同样的计划重复造轮子了😄

**Comment by javeme** [comment]
@wuchaojing 感谢关注HugeGraph，HugeGraph计划加入Apache基金会。

大方向上的计划可以参考Apache Proposal的`Initial Goals`部分：
https://cwiki.apache.org/confluence/display/INCUBATOR/HugeGraphProposal
