### ISSUE TITLE
[Question] 手动初始化hbase后，启动进程报错

### ISSUE THREAD

**Issue by wuchaojing** [hugegraph/hugegraph#1782]
### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: 最新
- Backend: hbase
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

手动初始化hbase，包括
1. 建ns 和 table，成功
2. 通过执行this.storeProvider.initSystemInfo(this);向表内插入元数据，成功

表里已有元数据
<img width="1785" alt="image" src="https://user-images.githubusercontent.com/37741352/158574448-a5849ffd-a20f-4564-94e7-6b5537181854.png">

此时启动进程，报错如下，The backend store of 'HUGEGRAPH' has not been initialized
<img width="1788" alt="image" src="https://user-images.githubusercontent.com/37741352/158574630-e2758d8c-32c2-49f6-ba66-fbfe2342d2ca.png">

如果重新执行init-store.sh，则报错：Already exists backend info of graph 'HUGEGRAPH' in backend 'hbase'
<img width="1787" alt="image" src="https://user-images.githubusercontent.com/37741352/158574856-229db6f4-5548-4b0d-af50-8be924f8340f.png">

辛苦帮看下是什么原因呢？感谢

**Comment by imbajin** [comment]
> 通过执行 this.storeProvider.initSystemInfo (this); 向表内插入元数据，成功

细节应该是执行这个步骤的时候有些出入吧, 核心思路差不多, 可以看看检查初始化完成以及图完成那块的代码上下文, 看看是不是少了点啥.

**Comment by wuchaojing** [comment]
> 

查了半天，原因是线上集群没有对namespace授权，所以本来初始化完成的，再去check的时候由于拿不到namespace就报错了。对namespace授权之后就没问题了
