### ISSUE TITLE
[Question] rocksdb的存储流程是怎样的

### ISSUE THREAD

**Issue by wuchaojing** [hugegraph/hugegraph#1789]
### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.12.0
- Backend: RocksDB
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

请问下rocksdb的写入流程是怎样的？是先写rocksdb_log（wal），再统一写到rocksdb_data吗？

1、如果是的话，rocksdb_log写到什么程度才会写rocksdb_data呢？
2、系统已存入130w+顶点和90w+边，属性个数小于5，存储占用300M左右，这正常吗？
<img width="1194" alt="image" src="https://user-images.githubusercontent.com/37741352/159154547-e5b72259-cb3f-44ee-a284-a22b8d696121.png">

3、当我手动把rocksdb_data和rocksdb_log删除后，在hubble上仍然可以执行g.V()等操作，是因为缓存吗？缓存多久呢？

配置：
<img width="878" alt="image" src="https://user-images.githubusercontent.com/37741352/159154592-170fc6df-6dec-4c70-8aa4-0a72662d5a4a.png">

**Comment by javeme** [comment]
> 请问下rocksdb的写入流程是怎样的？是先写rocksdb_log（wal），再统一写到rocksdb_data吗？

答复：rocksdb的写入流程比较复杂，不过可以简化理解下其核心流程：

1. 写日志：WAL。
2. 写内存Buffer：MemTable。
3. 当MemTable积攒到一定程度（HugeGraph默认128MB。如有需要也可以配置其它相关因素：所有MemTable总大小和WAL大小），会将MemTable flush刷到磁盘，也就是上面所说的rocksdb_data目录。

> 系统已存入130w+顶点和90w+边，属性个数小于5，存储占用300M左右，这正常吗？

答复：数据占用大小影响因素较多，包括顶点表、出入边表、Label索引表、Id长度、原始数据本身大小。

> 当我手动把rocksdb_data和rocksdb_log删除后，在hubble上仍然可以执行g.V()等操作，是因为缓存吗？缓存多久呢？

答复：该操作与缓存没有关系的。如果未停止服务的情况下手动删除数据，进程依然持有着文件，文件系统并不会真正删除数据，需要在引用为0时才实际删除。
