### ISSUE TITLE
graph_vertices中顺序获取特定label id的顶点 方案请教

### ISSUE THREAD

**Issue by hklmuaqmn** [hugegraph/hugegraph#179]
请教下， 生产环境我们用的hugegraph+cassandra集群存放图数据，顶点在1.5亿左右，边在2亿左右，顶点的label类别有3类，对应ID：1, 2, 3
现在有个业务场景: 我们要从顶点表graph_vertices中全量获取label id为2的顶点(label id为1或者3的顶点暂时忽略)做分析(分析用的Python)， 请教下， 现有的Hugegraph rest接口中有没有效率较高的  不重复顺序获取目标顶点的方式？非常感谢

**Comment by javeme** [comment]
@hklmuaqmn 目前的遍历API支持全量获取所有顶点或边，但是没办法按label分页获取（预计0.9版本支持）。谢谢
