### ISSUE TITLE
[Bug] 源码编译环境问题

### ISSUE THREAD

**Issue by JackyYangPassion** [hugegraph/hugegraph#1793]
### Bug Type (问题类型)

other exception / error (其他异常报错)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: 源码 0.12.0 及 master
- 编译环境： mac, idea

### Expected & Actual behavior (期望与实际表现)

本地编译打包成功 
编译命令 mvn clean package -DskipTests

运行测试用例
`BinarySerializerTest.testEdge()`

抛出异常

` java: 找不到符号
  符号:   类 ProtocolMessageEnum
  位置: 程序包 com.google.protobuf`

对应的类：
`com.baidu.hugegraph.backend.store.raft.rpc.RaftRequests`

查看了下整个项目的pom文件 缺少以下mvn 以来引入
```xml
<dependency>
    <groupId>com.alipay.sofa</groupId>
    <artifactId>sofa-rpc-all</artifactId>
    <version>xxx</version>
</dependency>
<dependency>
    <groupId>com.google.protobuf</groupId>
    <artifactId>protobuf-java</artifactId>
    <version>xxx</version>
</dependency>
```

这个大家本地编译后 如何解决此问题

**Comment by javeme** [comment]
最新的master代码理论上是包含了sofa-rpc-all依赖的，通过[hugegraph-rpc](https://github.com/hugegraph/hugegraph-common/blob/master/hugegraph-rpc/pom.xml#L50)引入了sofa-rpc-all的。protobuf-java包缺失比较奇怪，可以考虑使用`mvn dependency:tree`命令打印一下依赖树，搜索”protobuf-java“是否存在（可能的原因是包被排除了或依赖冲突）。

**Comment by JackyYangPassion** [comment]
确认了下 依赖树中 以上两个jar 均被其他jar 引入了
`[INFO] +- com.baidu.hugegraph:hugegraph-rpc:jar:2.0.1:compile
[INFO] |  +- com.lmax:disruptor:jar:3.3.7:compile
[INFO] |  \- com.alipay.sofa:sofa-rpc-all:jar:5.7.6:compile
[INFO] |     +- com.alipay.sofa:tracer-core:jar:3.0.8:compile
[INFO] |     |  +- io.opentracing:opentracing-api:jar:0.22.0:compile
[INFO] |     |  +- io.opentracing:opentracing-noop:jar:0.22.0:compile
[INFO] |     |  +- io.opentracing:opentracing-mock:jar:0.22.0:compile
`

`[INFO] |  +- com.alipay.sofa:jraft-core:jar:1.3.9:compile
[INFO] |  |  +- org.ow2.asm:asm:jar:6.0:compile
[INFO] |  |  +- com.lmax:disruptor:jar:3.3.7:compile
[INFO] |  |  +- com.google.protobuf:protobuf-java:jar:3.5.1:compile
[INFO] |  |  +- commons-lang:commons-lang:jar:2.6:compile
[INFO] |  |  +- com.alipay.sofa:bolt:jar:1.6.4:compile
[INFO] |  |  |  \- com.alipay.sofa.common:sofa-common-tools:jar:1.0.12:compile
[INFO] |  |  \- com.alipay.sofa:hessian:jar:3.3.6:compile
`
目前是编译打包没有错误，就是本地运行测试代码 显示缺少依赖

**Comment by javeme** [comment]
`mvn package`打包后的lib目录里面有sofa-rpc-all、protobuf-java这两个jar包吗？

或者尝试本地安装一下后再跑test呢？`mvn clean install -DskipTests`

**Comment by JackyYangPassion** [comment]
> `mvn package`打包后的lib目录里面有sofa-rpc-all、protobuf-java这两个jar包吗？
> 
> 或者尝试本地安装一下后再跑test呢？`mvn clean install -DskipTests`

lib 中是有的；mvn clean install -DskipTests 这个之前尝试过 运行后

**Comment by JackyYangPassion** [comment]
问题已找见 IDEA中 maven 配置有问题 已修复 不是huge 源码的问题
