### ISSUE TITLE
hugegraph server可以在多台机器上启动吗？

### ISSUE THREAD

**Issue by bigdata-eqxiu** [hugegraph/hugegraph#18]
hugegraph 什么架构 server可以在多台机器上启动吗？ 和janusgraph有什么区别

**Comment by zhoney** [comment]
HugeGraphServer目前不支持集群模式，目前常用方式有两种：
- HugeGraphServer+RocksDB后端存储，单机模式。
- HugeGraphServer + Cassandra或者HBase，集群模式。（HugeGraphServer是单点）

**Comment by bigdata-eqxiu** [comment]
HugeGraphServer能否启动多个实例来访问相同的Cassandra后端， 如果只能单点工作 那么计算就会出现天花板 无法做到线性扩张，

**Comment by zhoney** [comment]
@bigdata-eqxiu 由于HugeGraphServer有元数据和图数据的缓存，目前只能启动单个HugeGraphServer链接一个后端，多个HugeGraphServer连接相同后端有可能导致数据不一致

**Comment by zhoney** [comment]
Close this issue now due to having not been updated in a long time. Feel free to reopen it if needed.
