### ISSUE TITLE
请问支持前缀查询吗

### ISSUE THREAD

**Issue by CrazyBeeline** [hugegraph/hugegraph#1811]
### Problem Type (问题类型)

others (please edit later)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.12.0
- Backend: RocksDB 1 nodes, HDD
- OS: xx CPUs, xx G RAM, Centos 7.x 

### Your Question (问题描述)

官网显示支持前缀查询
![image](https://user-images.githubusercontent.com/25030234/162137734-926c3152-a326-4a01-ae17-cc8e7acf0eca.png)
我的测试
![image](https://user-images.githubusercontent.com/25030234/162137984-2efcba90-7b27-404d-8d8d-3773581db11e.png)
请问我改怎么实现前缀查询

**Comment by imbajin** [comment]
可以参考一下历史 issue, 直接 `Text.contains(xx)` 就能使用

More principle  info could refer #884

**Comment by CrazyBeeline** [comment]
> 可以参考一下历史 issue, 直接 `Text.contains(xx)` 就能使用
> 
> More principle info could refer #
全文索引是可以解决一些查询的问题，但是代价很大。
手机号最多前8位查询标签person顶点，需要自定义分词，索引的数据就会膨胀8倍

**Comment by imbajin** [comment]
模糊索引和前缀索引毕竟原理相差比较多, 前者分词就是个很麻烦的事, 后者是前缀匹配, 你问的或者需求不是后者么?

如果是精准的前 X 位查询, 前缀索引就可以了.

**Comment by javeme** [comment]
secondary-index和shard-index中的前缀查询，是指多个属性联合索引是，比如以city+age这两个属性建立索引，可以按照city前缀来查询，比如：

- secondary-index、shard-index均支持：`has('city', '南京')`、`has('city', '南京').has('age', 18)`
- shard-index支持：`has('city', '南京').has('age', gt(18))`

如果需要按照某一个属性的部分前缀内容查询，比如`has('city', startingWith('南'))`，目前是还不支持的。

关于该功能可以保持关注 https://github.com/hugegraph/hugegraph/issues/791 ，当然欢迎贡献代码。

**Comment by CrazyBeeline** [comment]
了解 谢谢各位 @javeme  @imbajin
