### ISSUE TITLE
[Bug] set类型contains查询报错

### ISSUE THREAD

**Issue by wuchaojing** [hugegraph/hugegraph#1812]
### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: master
- Backend: RocksDB
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### Expected & Actual behavior (期望与实际表现)

类型定义：schema.propertyKey('origins').asText().valueSet().ifNotExist().create();

根据#1474 的方法查询，报错如下：
1、不使用contains语句
<img width="878" alt="image" src="https://user-images.githubusercontent.com/37741352/162206351-317c9a9d-12cf-42d0-bcd6-ce137618c0eb.png">

2、使用contains
<img width="1521" alt="image" src="https://user-images.githubusercontent.com/37741352/162206350-d9c5f0b6-3d86-4866-8e3f-ed12252c1cd1.png">

另外问下，
1、set类型如何查询包含多个值，比如contains('hello', 'world') ？
2、set类型如何通过gremlin语句查询【包含且仅包含】关系，比如set就包含一个值，且是['hello']

辛苦帮忙解答，感谢！

**Comment by javeme** [comment]
感谢反馈。
需要导出一下com.baidu.hugegraph.traversal.optimize.ConditionP，欢迎贡献代码，增加到如下位置:
https://github.com/hugegraph/hugegraph/blob/master/hugegraph-dist/src/assembly/static/conf/gremlin-server.yaml#L44

**Comment by javeme** [comment]
> 1、set类型如何查询包含多个值，比如contains('hello', 'world') ？

可以尝试：
`g.V().hasLabel('user').or(has('origins', contains('hello')), has('origins', contains('world')))`

> 2、set类型如何通过gremlin语句查询【包含且仅包含】关系，比如set就包含一个值，且是['hello']

可以尝试：
`g.V().hasLabel('user').has('origins', ConditionP.contains('hello')).where(values('origins').unfold().count(local).is(1))`

**Comment by wuchaojing** [comment]
好的。感谢！
