### ISSUE TITLE
可否提供更轻量的查询顶点的API

### ISSUE THREAD

**Issue by hklmuaqmn** [hugegraph/hugegraph#183]
现在查询Vertex的API主要是：
GET http://localhost:8080/graphs/hugegraph/graph/vertices
无论是按照属性过滤还是按照分页查询， 返回的都是节点的全量信息,太厚重了， 能不能指定返回的properties列表， 比如只返回vertex的id？

**Comment by javeme** [comment]
@hklmuaqmn 多谢反馈，后续我们会考虑加入这个特性

**Comment by hklmuaqmn** [comment]
我们现在顶点存放的有好几类， 比如用户id,文档id  用户可以分享读文档/写文档， 我们需要找出两个用户潜在的多种关系关系，需要先查询出用户id，然后做推理， 用户包含的属性现在还不关注

**Comment by javeme** [comment]
@hklmuaqmn 好的了解了
