### ISSUE TITLE
请问单个图如果解决权限问题

### ISSUE THREAD

**Issue by eternalxj** [hugegraph/hugegraph#187]
例如某用户只能访问某些顶点和边 其他不能访问、如何限制？

**Comment by eternalxj** [comment]
@javeme 主要就是HugeGraph-Studio 会有很多个部门的人员访问，底层图数据主要是基于数仓的数据、需要区分权限如下、不同部门的人员对底层图数据只读、只能对自己创建的图数据进行编辑和修改 不能修改他人的数据

**Comment by javeme** [comment]
closed since implemented by #209
