### ISSUE TITLE
基于表达式排序实现提问

### ISSUE THREAD

**Issue by zhang374723384** [hugegraph/hugegraph#194]
g.V().order().by(map{it.get().value("total_loan_cnt")*6+it.get().value("max_overdue_day_cnt")},decr) 像这样by里面写表达式进行排序使用java如何实现啊，请教

**Comment by javeme** [comment]
@zhang374723384 上述gremlin语句等价的java实现：
`g.V().order().by(__.<Vertex, Long>map(it->it.get().<Long>value("total_loan_cnt")*6+it.get().<Long>value("max_overdue_day_cnt")),Order.decr);`
