### ISSUE TITLE
使用Rest接口 http://localhost:8080/gremlin 查询分页的时候，生成下一页的pageid无法访问

### ISSUE THREAD

**Issue by hklmuaqmn** [hugegraph/hugegraph#195]
使用Rest接口 http://localhost:8080/gremlin 查询分页的时候，生成下一页的pageid无法访问

场景：
本地hugegraph+mysql对接，模拟数据在一直往hugegraph插入顶点和边
使用Python下发Rest接口， 分页查询数据(分页查询数据参考的https://hugegraph.github.io/hugegraph-doc/clients/restful-api/vertex.html)每次都是根据前一次返回的下一页id，重新组装URL下发，发现执行到第四页以后，第五页执行报错(第四页返回的第五页的id跟前面几页的id长度都不一致)

第一页URL：http://127.0.0.1:8080/graphs/hugegraph/graph/vertices?**limit=2000&page**
第二页URL：http://127.0.0.1:8080/graphs/hugegraph/graph/vertices?limit=2000&**page=eyJMQUJFTCI6MiwiUFJPUEVSVElFUyI6IntcIjEzXCI6XCJ1c2VyaWRfMjc5OVwifSIsIklEIjoiUzI6dXNlcmlkXzI3OTkifQ==**
第三页URL：http://127.0.0.1:8080/graphs/hugegraph/graph/vertices?limit=2000&**page=eyJMQUJFTCI6MiwiUFJPUEVSVElFUyI6IntcIjEzXCI6XCJ1c2VyaWRfNDU5OVwifSIsIklEIjoiUzI6dXNlcmlkXzQ1OTkifQ==**
第四页URL：http://127.0.0.1:8080/graphs/hugegraph/graph/vertices?limit=2000&**page=eyJMQUJFTCI6MiwiUFJPUEVSVElFUyI6IntcIjEzXCI6XCJ1c2VyaWRfNjM5OVwifSIsIklEIjoiUzI6dXNlcmlkXzYzOTkifQ==**
第五页URL：http://127.0.0.1:8080/graphs/hugegraph/graph/vertices?limit=2000&**page=eyJMQUJFTCI6MiwiUFJPUEVSVElFUyI6IntcIjEzXCI6XCJ1c2VyaWRfODJcIn0iLCJJRCI6IlMyOnVzZXJpZF84MiJ9**
第五页的URL执行报错

**Comment by Linary** [comment]
@hklmuaqmn 感谢反馈，这个问题是一个已知的BUG，我们已经提交了[pr](https://github.com/hugegraph/hugegraph-client/issues/13)

**Comment by hklmuaqmn** [comment]
请问0.8合入了么？

**Comment by Linary** [comment]
还没有，预计本周五（2018-11-16）会发布。
