### ISSUE TITLE
hugegraph对接cassandra配置请教

### ISSUE THREAD

**Issue by hklmuaqmn** [hugegraph/hugegraph#210]
对于hugegraph.properties中的配置项：
cassandra.host=
cassandra.port=
cassandra.username
cassandra.password

请教下
cassandra.host是否可以将cassandra集群中的所有节点IP 都写上？

**Comment by javeme** [comment]
@hklmuaqmn 可以的，请使用逗号分隔各IP即可：`cassandra.host=ip1,ip2,ip3`

**Comment by hklmuaqmn** [comment]
@javeme  请问只写一个节点的ip跟写集群的所有ip， 对于hugegraph和cassandra而言， 在查询和写入时性能有差异么？

**Comment by javeme** [comment]
@hklmuaqmn 写多少个ip不会影响性能， Cassandra是根据这个ip获取的集群信息再进行操作的，建议写一个最快的。更多细节请参考文档：[Which Node to Connect ](https://teddyma.gitbooks.io/learncassandra/content/client/which_node_to_connect.html)
