### ISSUE TITLE
请问ScyllaDB生产离线怎么安装,要疯了,哪位知道,有安装教程吗

### ISSUE THREAD

**Issue by eternalxj** [hugegraph/hugegraph#218]
请问ScyllaDB生产离线怎么安装,要疯了,哪位知道,有安装教程吗

**Comment by javeme** [comment]
ScyllaDB对内核及依赖库版本要求比较高（如果依赖库不满足需要先手动进行升级），请参考官网教程：
https://www.scylladb.com/download/ubuntu/
https://www.scylladb.com/download/centos_rpm/

**Comment by eternalxj** [comment]
@javeme 升级内核然后 rpm挨个手动安装的 总算安装成功了，不过设置xfs的磁盘格式貌似没什么用处，还是需要开启开发者模式才能启动服务
