### ISSUE TITLE
./bin/start-hugegraph.sh 链接的服务器没有 hostname

### ISSUE THREAD

**Issue by xy83918** [hugegraph/hugegraph#225]
### Expected behavior 期望表现
{type something here...}

### Actual behavior 实际表现
```
Starting HugeGraphServer...
Connecting to HugeGraphServer (http://:8080/graphs)............
```

### Steps to reproduce the problem 复现步骤
1. `./bin/start-hugegraph.sh`
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by Linary** [comment]
请问是使用hugegraph-tools还是hugegraph的脚本启动的？我看这个问题与 https://github.com/hugegraph/hugegraph-tools/issues/15 很相似，是同一个问题吗？

**Comment by xy83918** [comment]
不是同一个问题， 是那边启动不了，我尝试自己编译启动的时候遇到的问题，目前环境没搭建起来

**Comment by xy83918** [comment]
我现在0.8.0的源码 自己build 用这个脚本是可以启动的

**Comment by Linary** [comment]
> 我现在0.8.0的源码 自己build 用这个脚本是可以启动的

这个你有修改脚本吗？

**Comment by xy83918** [comment]
![image](https://user-images.githubusercontent.com/2715268/49075511-e9a60d00-f271-11e8-99b7-d3ac5c828371.png)

**Comment by xy83918** [comment]
hugeGraph 服务器部分现在已经启动起来了，使用curl命令也可以得到正常的结果，现在的问题是客户端和studio都连不上

**Comment by xy83918** [comment]
客户端和 studio都是git clone的最新程序，配置server的域名

**Comment by Linary** [comment]
你先把以下几个地方都改成机器的ip（172.20.121.169）试试：

- resetserver.url
- client 连接 url
- loader 的 -h 参数
- studio 的 studio.server.host 和 graph.server.host
