### ISSUE TITLE
CASSANDRA_COMPRESSION配置项疑问

### ISSUE THREAD

**Issue by hklmuaqmn** [hugegraph/hugegraph#227]
CASSANDRA_COMPRESSION 配置项目前可选 [none, snappy, lz4]  想咨询下， 之前我们用的是none配置项，  现在想换成lz4试试效果， 请问， 这个需要重新执行Init-store吧？需要重启cassandra集群么？

**Comment by javeme** [comment]
@hklmuaqmn 注意`cassandra.compression_type`配置项是用来设置Cassandra传输数据的压缩格式，不是存储数据的压缩格式。所以**无需**要重新执行Init-store，也**无需**重启cassandra集群。
