### ISSUE TITLE
退出gremlin-console.sh时，会断开服务器连接

### ISSUE THREAD

**Issue by xuchaoigo** [hugegraph/hugegraph#228]
### Actual behavior 实际表现
:exit或ctrl+c退出 bin/gremlin-console.sh时，会断开服务器连接（必现）

### Steps to reproduce the problem 复现步骤
1. 在client01和cymirr15两台机器上均可复现

### Specifications of environment 环境信息
- hugegraph version: {latest}
- operating system: {centos}
- hugegraph backend: {cassandra 3.10, cluster with 3 nodes}

**Comment by zhoney** [comment]
@xuchaoigo 连接同样的服务器没有复现问题，请自查secureCRT的配置
