### ISSUE TITLE
初始化时schema的设置问题

### ISSUE THREAD

**Issue by jingfongyu** [hugegraph/hugegraph#232]
看了huge的说明书，在初始化图数据库数据时需要设置schema，这边存在如下几个问题：
1、设置vertexLabel和edgeLabel是类似OrientDB的class吗？
2、设置IndexLable的时候的依据是什么呢？是需要将vertex和edge所有的属性都设置比较好吗？
3、设置edgeLabel的时候需要制定sourceLabel和targetLabel，这些都是必须的，这样是不是必须在设置schema的时候就需要限定好class到class的关系，如果是这样的话，在关系的发现中该如何去生成关系呢？还需要提前定义schema？

**Comment by zhoney** [comment]
@jingfongyu 
> 1、设置vertexLabel和edgeLabel是类似OrientDB的class吗？

是的

> 2、设置IndexLable的时候的依据是什么呢？是需要将vertex和edge所有的属性都设置比较好吗？

1. IndexLabel最好在数据导入前设置，这样可以在导入顶点和边时创建索引信息，导入顶点和边结束后就可以查询了。
2. 需要建哪些索引，是要根据自身的应用场景来判断的。并不建议给所有的属性都建立，因为索引占用存储空间，而且数据越多对查询性能也会有影响。
3. 另外，即使在导入顶点和边之前没有建立IndexLabel，想要根据某个属性查询时，也可以先建立索引再查询。当已经导入的顶点或者边量很大时，集中建立索引会需要较长的时间。

> 3、设置edgeLabel的时候需要制定sourceLabel和targetLabel，这些都是必须的，这样是不是必须在设置schema的时候就需要限定好class到class的关系，如果是这样的话，在关系的发现中该如何去生成关系呢？还需要提前定义schema？

1. 在增加顶点和边之前必须有**对应的**schema。但并不要求所有schema要在所有数据导入前定义完成。
2. 如果需要动态建立schema，只需要在导入对应的顶点和边前，把其需要的对应schema建立出来即可。
