### ISSUE TITLE
关于id策略的边连接问题

### ISSUE THREAD

**Issue by eternalxj** [hugegraph/hugegraph#237]
@Linary @javeme 各位同学有个问题请教
配置文件如下 执行loader导入报错PROPERTY_KEY with name 'id' does not exist
看报错的内容他是再找叫id的property_key 我的想法是基于id(.useCustomizeStringId())连接边
请问基于id连接边 配置文件是那个地方需要修改吗
1、schema.groovy
schema.propertyKey("test_name").asText().ifNotExist().create();
...省略
// 使用自定义字符策略使用"test_name"作为id
schema.vertexLabel("test_person").useCustomizeStringId().properties("test_age", "test_city").ifNotExist().create();
schema.edgeLabel("test_knows").sourceLabel("test_person").targetLabel("test_person").properties("date", "weight").ifNotExist().create();

2、struct.json
"vertices": [
    {
      "label": "test_person",
      "input": {
        "type": "file",
        "path": "example/vertex_person.csv",
        "format": "CSV",
        "header": [
          "id",
          "test_age",
          "test_city"
        ],
        "charset": "UTF-8"
      },
      "id": "id"
    }

"edges": [
       {
       "label": "test_knows",
       "source": ["source_name"],
       "target": ["target_name"],
       "input": {
       "type": "file",
       "path": "example/edge_knows.json",
       "format": "JSON"
       },
       "mapping": {
       "source_name": "id",
       "target_name": "id"
       }
       }
3、vertex_person.csv 顶点文件
marko,29,Beijing
vadas,27,Hongkong
4、edge_knows.json 边文件
{"id": "marko", "id": "vadas", "date": "20160110", "weight": 0.5}
{"id": "marko", "id": "josh", "date": "20130220", "weight": 1.0}

**Comment by eternalxj** [comment]
如果有了id还需要指定一个同样的PROPERTY_KEY就会增加占用的存储，不知道能不能通过id进行边连接

**Comment by eternalxj** [comment]
这样顶点是可以加载成功的,目前边没有创建成功

**Comment by Linary** [comment]
@eternalxj 边文件的内容应该像这样：

```
{"source_name": "marko", "target_name": "vadas", "date": "20160110", "weight": 0.5}
{"source_name": "marko", "target_name": "josh", "date": "20130220", "weight": 1.0}
```

**Comment by eternalxj** [comment]
@Linary 光改边文件还是保之前的错误  边文件里面的source_name、target_name 其实应该是顶点里面useCustomizeStringId指定的id

**Comment by eternalxj** [comment]
感觉最主要的是struct.json文件里面的edges的设置

**Comment by eternalxj** [comment]
struct.json里面的设置不清楚要如何对应到useCustomizeStringId 这个id上面

**Comment by Linary** [comment]
抱歉，这的确是一个BUG，测试中也忽略了此问题。我们会立马修复，另外，你可以自己修改源码：

将EdgeParser类buildVertexId方法的

```
String key = this.source.mappingField(fieldName);
Object value = this.validatePropertyValue(key, fieldValue);
```

这两行移到 else 里面。

**Comment by Linary** [comment]
@eternalxj 欢迎贡献代码

**Comment by eternalxj** [comment]
@Linary 改完发我个tar包呗，不是coding人员 怕改出问题

**Comment by eternalxj** [comment]
@Linary 另外改过之后只要按照你说的只改边文件就可以了吗，还是还要修改别的配置文件那

**Comment by Linary** [comment]
[hugegraph-loader-0.8.0.tar.gz](https://github.com/hugegraph/hugegraph/files/2624179/hugegraph-loader-0.8.0.tar.gz)

配置文件和边文件像下面这样写

struct.json
```
"edges": [
{
"label": "test_knows",
"source": ["source_name"],
"target": ["target_name"],
"input": {
"type": "file",
"path": "example/edge_knows.json",
"format": "JSON"
}
}
]
```

edge_knows.json 边文件
```
{"source_name": "marko", "target_name": "vadas", "date": "20160110", "weight": 0.5}
{"source_name": "marko", "target_name": "josh", "date": "20130220", "weight": 1.0}
```

**Comment by eternalxj** [comment]
@Linary 按照这个是可以加载成功的，不过奇怪配置文件里面没见到指定id的地方，为什么就按照id连边了那？

**Comment by Linary** [comment]
@eternalxj 当顶点使用自定义的Id策略时，边的配置文件中的`source`和`target`填上文件中的代表源顶点和目标顶点id的列。

**Comment by eternalxj** [comment]
@Linary  就是不写下面的mapping ,他就会按照source_name去找id是吧
"mapping": {
"source_name": "id",
"target_name": "id"
}

**Comment by Linary** [comment]
> @Linary 就是不写下面的mapping ,他就会按照source_name去找id是吧
> "mapping": {
> "source_name": "id",
> "target_name": "id"
> }

是的
