### ISSUE TITLE
task index-label id has conflicts with system label index or schema name index

### ISSUE THREAD

**Issue by zhoney** [hugegraph/hugegraph#239]
### Actual behavior 实际表现
{type something here...}
![image](https://user-images.githubusercontent.com/17330028/49158734-cfe1f400-f35d-11e8-808b-83ab6e07a58c.png)

operate tx in other thread exception appears after fix first bug

![image](https://user-images.githubusercontent.com/17330028/49166551-92d22d80-f36e-11e8-9945-870fe2820e5a.png)

**Comment by hklmuaqmn** [comment]
hugegraph-0.8是不是有这个bug？
