### ISSUE TITLE
关于id的索引问题

### ISSUE THREAD

**Issue by eternalxj** [hugegraph/hugegraph#242]
请问，正常顶点的属性可以通过主键或者索引的手段提高查询速度，那么id是否自带索引那，如果不是自带索引如何提高查询效率那

**Comment by Linary** [comment]
id不需要索引，id是直接能定位到一条记录的。索引存在的目的就是为了通过属性找到id，再通过id找到记录，所以有id了不需要索引。

**Comment by eternalxj** [comment]
@Linary 感谢解答
