### ISSUE TITLE
关于property keys中文问题

### ISSUE THREAD

**Issue by jingfongyu** [hugegraph/hugegraph#243]
### Expected behavior 期望表现
设置property_keys的时候设置的是中文，执行schema和add vertex的时候能够增加成功

### Actual behavior 实际表现
发现设置property_keys为中文的时候是成功的，在表property_keys中也能找到数据，但是在add vertex的时候发生报错了，报错信息如下：
java.lang.IllegalArgumentException: All non-null property keys [名称, 接收单位, 党费收取, 办理负责人, 介绍信抬头, 负责人, 如何借用] of vertex label '党组织关系事件' must be setted, missed keys [接收单位, 党费收取, 办理负责人, 介绍信抬头, 负责人]

请问下property_keys是不是不支持中文，且其他schema是否也不支持中文？

**Comment by Linary** [comment]
都是支持中文的，出现这个问题的原因是schema没有写对。你应该把[接收单位, 党费收取, 办理负责人, 介绍信抬头, 负责人]设置为可空属性。示例如下：

```
schema.vertexLabel("xxx").properties("xxx", ...)
      .nullableKeys("接收单位", "党费收取", "办理负责人", 介绍信抬头", "负责人")
      ...
```
