### ISSUE TITLE
rings 与rays接口查询报错

### ISSUE THREAD

**Issue by fisherinbox** [hugegraph/hugegraph#250]
### Expected behavior 期望表现
比如这种查询 http://localhost:8080/graphs/gods_relation_2/traversers/rings?source="1:pluto"&direction=OUT&max_depth=5

### Actual behavior 实际表现
{
    "exception": "class java.lang.IllegalArgumentException",
    "message": "Paths max depth must be > 0, but got '0'",
    "cause": ""
}

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by zhoney** [comment]
@fisherinbox rings和rays的深度参数是depth，不是max_depth。参见：https://hugegraph.github.io/hugegraph-doc/clients/restful-api/traverser.html

![image](https://user-images.githubusercontent.com/17330028/49272508-bd2a0500-f4ac-11e8-9cef-dc9b2fd79678.png)

![image](https://user-images.githubusercontent.com/17330028/49272526-cb782100-f4ac-11e8-93c4-71ec6d191080.png)

**Comment by javeme** [comment]
@fisherinbox 可能有些不一致的地方，接下来会统一一下这些参数的命名。

**Comment by fisherinbox** [comment]
@javeme 那例子url里面写错啊,建议尽快改一下
![image](https://user-images.githubusercontent.com/7240400/49272954-4a218e00-f4ae-11e8-94d9-b16cccdb1c0f.png)

**Comment by zhoney** [comment]
@fisherinbox 已更新，参见：

https://hugegraph.github.io/hugegraph-doc/clients/restful-api/traverser.html

截图如下：

![image](https://user-images.githubusercontent.com/17330028/49351905-74628e00-f6f0-11e8-8f59-9250469aae89.png)

![image](https://user-images.githubusercontent.com/17330028/49351928-86dcc780-f6f0-11e8-8c1c-9b304860f8ef.png)

下一版本会统一命名，多谢您的反馈！
