### ISSUE TITLE
换新版本之后 hbase上的数据需要重新导入吗?通过老版本导入的数据适用于新版本吗

### ISSUE THREAD

**Issue by fisherinbox** [hugegraph/hugegraph#251]
### Expected behavior 期望表现
{type something here...}

### Actual behavior 实际表现
现在看起来是需要重新导入数据的,用老的数据新加的几个API查不出结果

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by javeme** [comment]
@fisherinbox 根据兼容性检查结果而定，如果两个版本兼容的话就不需要重新导入，不兼容则可以通过tools的备份恢复工具来迁移数据。

**Comment by javeme** [comment]
相关问题 https://github.com/hugegraph/hugegraph-tools/issues/35
