### ISSUE TITLE
请教下hugegraph的分页机制原理

### ISSUE THREAD

**Issue by hklmuaqmn** [hugegraph/hugegraph#253]
我们现在查询顶点用的是hugegraph提供的一个分页查询接口， http://127.0.0.1:8080/graphs/hugegraph/graph/vertices?limit=2000&page=XXXXX  每次下一页的pageid需要从上一页的response中获取， 请问， 这个pageid是依据什么原则产生的? 现在由于顶点个数较多，按2000/页总共有2W页， 顺序获取pageid 太麻烦了， 请问这个pageid 每次获取都是不一样的么？ 比如我今天获取了2w个pageid， 明天我可以不顺序获取pageid了， 直接拿今天的pageid可以直接进行查询么？ 期待解惑，谢谢！！！

**Comment by Linary** [comment]
pageid 的生成规则是将下一页的第一条记录的 id 进行 base64 编码。比如分页大小为100，那取完第一页顺带的 pageid 就是第 101 条的 id 的 base64 编码值，下一个就是第 201 条的编码值。

如果你的数据没有变，且每次都以相同的页面大小获取，那每一页的 pageid 都是固定的。

**Comment by hklmuaqmn** [comment]
感谢！

**Comment by hklmuaqmn** [comment]
感谢！
