### ISSUE TITLE
HugeGraph Java Client例子程序，依赖打jar包后运行，报check ClientVersion错误

### ISSUE THREAD

**Issue by xuchaoigo** [hugegraph/hugegraph#257]
### Actual behavior 实际表现
用IDEA编译HugeGraph Java Client例子程序，采用全部依赖打jar包的方式，在服务器运行Client的jar包时，会报check ClientVersion错误：“The version to match is null”

![image](https://user-images.githubusercontent.com/17330028/49488235-b9b5c580-f880-11e8-85a8-e4d8864d8b35.png)

### Specifications of environment 环境信息
- hugegraph version: v0.7.4

**Comment by zhoney** [comment]
@xuchaoigo 这是由于把基于hugegraph-client二次开发的程序和依赖打包成一个大的jar包导致的。

1. hugegraph-client依赖于hugegraph-common，为避免多版本之间的混乱，hugegraph-client会检查hugegraph-common包的版本是否符合需要。
2. 检查版本的方式是借助于hugegraph-common jar包/META-INF/MANIFEST.MF中的IMPLEMENTATION_VERSION版本号实现的。
3. 当基于hugegraph-client二次开发的程序把所有依赖包打包成一个大的jar包时，会导致/META-INF/MANIFEST.MF中的信息丢失。

解决办法：

不要把基于hugegraph-client二次开发的程序和依赖包打成一个大的jar包（主要是不要破坏hugegraph-common jar包结构），而是把所有依赖包放到lib目录下
