### ISSUE TITLE
hugeloader边导入自动创建点问题

### ISSUE THREAD

**Issue by zhang374723384** [hugegraph/hugegraph#260]
hugeloader边导入时,如果点不存在时能否自动创建点呢

**Comment by Linary** [comment]
不会自动创建

**Comment by zhang374723384** [comment]
> 不会自动创建

没有这方面的设置么

**Comment by Linary** [comment]
目前没有这样的设置，因为边文件中一般只存在顶点的id，不包含顶点的属性，所以无法构造出完整的顶点。你的数据是顶点除了id，没有其他属性吗？
