### ISSUE TITLE
hugegraph对于大数据量实际应用后端数据库是用scylladb好还是hbase好？

### ISSUE THREAD

**Issue by eternalxj** [hugegraph/hugegraph#264]
@Linary @javeme  请问 hugegraph对于大数据量实际应用后端数据库是用scylladb好还是hbase好？
或者说scylladb可以支持多大数据量的查询

**Comment by eternalxj** [comment]
或者说后端用scylladb相对于hbase有什么优点和缺点

**Comment by javeme** [comment]
@eternalxj scylladb和hbase都支持容量横向扩展（容量上它们一般不会是瓶颈），scylladb的定位是低延迟（没有Java GC停顿、高效的网络库等），hbase生态更加完善及稳定性较好。

**Comment by cmdares** [comment]
也就是说如果仅仅考虑高可用性、易扩容行、低延时入库，不考虑生态的话，还是建议scylla，是吧？

**Comment by zhoney** [comment]
@cmdares ScyllaDB相对较新，在成熟度和稳定性方面考虑，推荐Cassandra。

> Cassandra也具备高可用和易扩容。
