### ISSUE TITLE
请问hugegraph-spark现在能用吗？

### ISSUE THREAD

**Issue by hklmuaqmn** [hugegraph/hugegraph#265]
请问现在hugegraph-spark对外开放么？好像没看到下载地址了
另外， 请教下hugegraph-spark支持哪些特性啊？

**Comment by javeme** [comment]
@hklmuaqmn hugegraph-spark目前被纳入到商业版本了，因此无法对外开放在社区上传源码。关于hugegraph商业版原则：hugegraph的核心组件会一直以开源的方式发布。
hugegraph-spark包含的功能请参考[graphx algorithms](https://spark.apache.org/docs/latest/graphx-programming-guide.html#graph-algorithms)，另外hugegraph-spark主要是基于[Shard API 3.2.3](https://hugegraph.github.io/hugegraph-doc/clients/restful-api/traverser.html)与hugegraph集成的。
