### ISSUE TITLE
使用rocksdb,多个图配置相同的路径,重启增加新图的时候,重新init没问题,启动还是会超时

### ISSUE THREAD

**Issue by fisherinbox** [hugegraph/hugegraph#268]
### Expected behavior 期望表现
{type something here...}

### Actual behavior 实际表现
{type something here...}

2018-12-10 16:11:04 3464  [main] [ERROR] com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore [] - Failed to open Rock    sDB './d_1/schema'
 75 org.rocksdb.RocksDBException: While lock file: ./d_1/schema/LOCK: 没有可用的锁
 76         at org.rocksdb.RocksDB.open(Native Method) ~[rocksdbjni-5.8.6.jar:?]
 77         at org.rocksdb.RocksDB.open(RocksDB.java:286) ~[rocksdbjni-5.8.6.jar:?]
 78         at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStdSessions.<init>(RocksDBStdSessions.java:112) ~[hugegraph-    rocksdb-0.8.0.jar:?]
 79         at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.openSessionPool(RocksDBStore.java:229) ~[hugegraph-roc    ksdb-0.8.0.jar:?]
 80         at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.open(RocksDBStore.java:169) [hugegraph-rocksdb-0.8.0.j    ar:?]
 81         at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.open(RocksDBStore.java:149) [hugegraph-rocksdb-0.8.0.j    ar:?]
 82         at com.baidu.hugegraph.backend.tx.AbstractTransaction.<init>(AbstractTransaction.java:72) [hugegraph-core-0.8.0.    jar:0.8.0.0]
 83         at com.baidu.hugegraph.backend.tx.IndexableTransaction.<init>(IndexableTransaction.java:30) [hugegraph-core-0.8.    0.jar:0.8.0.0]
 84         at com.baidu.hugegraph.backend.tx.SchemaTransaction.<init>(SchemaTransaction.java:68) [hugegraph-core-0.8.0.jar:    0.8.0.0]
 85         at com.baidu.hugegraph.backend.cache.CachedSchemaTransaction.<init>(CachedSchemaTransaction.java:54) [hugegraph-    core-0.8.0.jar:0.8.0.0]
 86         at com.baidu.hugegraph.HugeGraph.openSchemaTransaction(HugeGraph.java:247) [hugegraph-core-0.8.0.jar:0.8.0.0]
 87         at com.baidu.hugegraph.HugeGraph.access$300(HugeGraph.java:81) [hugegraph-core-0.8.0.jar:0.8.0.0]
 88         at com.baidu.hugegraph.HugeGraph$TinkerpopTransaction.schemaTransaction(HugeGraph.java:721) [hugegraph-core-0.8.    0.jar:0.8.0.0]
 89         at com.baidu.hugegraph.HugeGraph$TinkerpopTransaction.access$000(HugeGraph.java:574) [hugegraph-core-0.8.0.jar:0    .8.0.0]
 90         at com.baidu.hugegraph.HugeGraph.schemaTransaction(HugeGraph.java:298) [hugegraph-core-0.8.0.jar:0.8.0.0]
 91         at com.baidu.hugegraph.backend.store.BackendStoreSystemInfo.info(BackendStoreSystemInfo.java:64) [hugegraph-core    -0.8.0.jar:0.8.0.0]
 92         at com.baidu.hugegraph.backend.store.BackendStoreSystemInfo.exist(BackendStoreSystemInfo.java:75) [hugegraph-cor    e-0.8.0.jar:0.8.0.0]
 93         at com.baidu.hugegraph.core.GraphManager.checkBackendVersionOrExit(GraphManager.java:197) [hugegraph-api-0.8.0.j    ar:0.31.0.0]
 94         at com.baidu.hugegraph.core.GraphManager.<init>(GraphManager.java:76) [hugegraph-api-0.8.0.jar:0.31.0.0]
 95         at com.baidu.hugegraph.server.ApplicationConfig$GraphManagerFactory$1.onEvent(ApplicationConfig.java:102) [hugeg    raph-api-0.8.0.jar:0.31.0.0]
 96         at org.glassfish.jersey.server.internal.monitoring.CompositeApplicationEventListener.onEvent(CompositeApplicatio    nEventListener.java:74) [jersey-server-2.25.1.jar:?]
 97         at org.glassfish.jersey.server.internal.monitoring.MonitoringContainerListener.onStartup(MonitoringContainerList    ener.java:81) [jersey-server-2.25.1.jar:?]
 98         at org.glassfish.jersey.server.ApplicationHandler.onStartup(ApplicationHandler.java:1180) [jersey-server-2.25.1.    jar:?]
 99         at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.start(GrizzlyHttpContainer.java:357) [jersey-co    ntainer-grizzly2-http-2.25.1.jar:?]
100         at org.glassfish.grizzly.http.server.HttpHandlerChain.start(HttpHandlerChain.java:422) [grizzly-http-server-2.3.    28.jar:2.3.28]
101         at org.glassfish.grizzly.http.server.HttpServer.setupHttpHandler(HttpServer.java:314) [grizzly-http-server-2.3.2    8.jar:2.3.28]

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by javeme** [comment]
@fisherinbox 看到日志里面包含“没有可用的锁”，是不是系统是中文环境？
由于RocksDB java API异常中没有详细错误码或错误类型，而是根据异常字符串来判断错误类型的，因此中文环境下的错误信息导致逻辑判断不对。

目前有两种解决方案（暂时这个问题可能没办法彻底解决）：
1. 切换为英文环境：在启动程序之前的设置为英文，比如`LANG="en_US.UTF-8"`
2. 配置各个图到不同的目录

**Comment by fisherinbox** [comment]
@javeme 感谢,这两个方案都试了,确实能解决
