### ISSUE TITLE
启动异常提示"Schema specific part is opaque"

### ISSUE THREAD

**Issue by liuzhiwei** [hugegraph/hugegraph#269]
### Actual behavior 实际表现

启动时报异常，"Schema specific part is opaque"，见图

![image](https://user-images.githubusercontent.com/2460599/49720232-3807d280-fc9a-11e8-8788-7c6a7a54c7ac.png)

**Comment by liuzhiwei** [comment]
原因是在 new HugeClient 时候指定 URL，漏写了 http 导致的。

补上 http:// 已经修复了这个异常

**Comment by javeme** [comment]
@liuzhiwei 多谢反馈
