### ISSUE TITLE
Support pagination when single index query

### ISSUE THREAD

**Issue by Linary** [hugegraph/hugegraph#287]

**Comment by Linary** [comment]
1. 分页模式时，不会对结果去重；
2. 多个IndexLabel的组合分页查询时，先取完第一个IndexLabel的全部，再取完第二个的，以此类推；
3. 优化分页查询的IdPrefixQuery构造，对于每个IndexLabel而言，每次分页的IdPrefix都是一样的，可以省去重复构造的

**Comment by javeme** [comment]
implemented at #328
