### ISSUE TITLE
index rebuild exceeds 80w limit and 65536 cassandra limit

### ISSUE THREAD

**Issue by zhoney** [hugegraph/hugegraph#291]
### Actual behavior 实际表现
> HugeException: Too many records(must <=800000) for the query: ....

or

> HugeException: Batch statement cannot contain more than 65535 statements...

### Steps to reproduce the problem 复现步骤
1. insert > 80w vertices
2. create secondary/range index

### Specifications of environment 环境信息
- hugegraph version: 0.8.0

**Comment by megodlike** [comment]
v0.12.0本版执行g.V().out().limit(10)还是报这个错误啊，大约120W条数据一共
