### ISSUE TITLE
indexType的search类型是什么？

### ISSUE THREAD

**Issue by JhihJian** [hugegraph/hugegraph#297]
在hugeclient 中创建indexlabel时，选择indexType类型，在secondary和range之外，还有另一个选择是search，请问它怎么样的，我再文档中并没有找到有关于search类型的描述

**Comment by Linary** [comment]
search是来做全文检索的，详细可以参考：
https://github.com/hugegraph/hugegraph/issues/258
https://github.com/hugegraph/hugegraph/issues/294

**Comment by 1315861791** [comment]
是用来做全文检索的，匹配的字符串粒度跟分词器的选择有关。
