### ISSUE TITLE
相同硬件下对比一下 ArangoDB、OrientDB 和hugegraph的性能指标

### ISSUE THREAD

**Issue by cmdares** [hugegraph/hugegraph#298]
同上，相同硬件下对比一下 ArangoDB、OrientDB 和Hugegraph的性能指标。
目前正在图库选型，希望优先支持一下开源国货！
正在考察ArangoDB、OrientDB（均是分布式）和Hugegraph对比下性能、评估下指标。
希望官方可以给出一个综合可信赖的评测对比。
感谢。

**Comment by Linary** [comment]
@cmdares 感谢关注，我们会尽快给出评测对比。

**Comment by cmdares** [comment]
ArangoDB OrientDB 这两个数据库近期进展较为激进，每次版本提交之后的性能都有大幅度提升。而网上的评测基本都是在旧版本进行的。所以希望我们在最新版本上做评测，同时需要考虑到这几个数据库上的调优设置，才能得出相对可靠的分析报告。
期待专家给予图库方面的先进技术和能力的提升。

**Comment by cmdares** [comment]
@Linary 您好，专家不清楚huge和其他两个图库的测试情况，推进的如何了。
