### ISSUE TITLE
如果获取从一个点到另一个点最早建立的那条路径（edge path）?

### ISSUE THREAD

**Issue by bigdata-eqxiu** [hugegraph/hugegraph#30]
从一点出发到达目标顶点会经过多个边与多个顶点，如何根据边的时间属性排序 ，获取边最早建立的路径

**Comment by javeme** [comment]
可以通过order-by实现：

`g.V(vertexId).outE("edge-label").order().by("time", incr)`

更多详细信息可参考tinkerpop文档：http://tinkerpop.apache.org/docs/current/reference/#order-step

**Comment by zhoney** [comment]
Close this issue now due to having not been updated in a long time. Feel free to reopen it if needed.
