### ISSUE TITLE
label上是否可以有属性，例如点的图标,同一个label只有一个图标，如果存在每个点上的话数据冗余

### ISSUE THREAD

**Issue by 1315861791** [hugegraph/hugegraph#308]
### Expected behavior 期望表现
如题;label上是否可以有属性，例如点的图标

**Comment by 1315861791** [comment]
@Linary 感谢您的解答，添加userdata的时候这个属性会不会存储在每个点上面。我的一个label只要同一个图标。不想在每个点上冗余存储。

**Comment by Linary** [comment]
@1315861791 userdata不会存在点上，只会存在与label上

**Comment by 1315861791** [comment]
@Linary 是的，感谢解答。我已经测试过了。
for(VertexLabel label : hugeClient.schema().getVertexLabels()){
            System.out.println(label);
            System.out.println(hugeClient.schema().getVertexLabel(label.name()).userdata().get("icon"));
        }
输出如下：
{name=电话, idStrategy=CUSTOMIZE_STRING, primaryKeys=[], nullableKeys=[电话号码], properties=[电话号码]}
tubiao_ceshi

**Comment by 1315861791** [comment]
@Linary 我以前用的NEO4J，刚开始使用hugegraph，还不是很熟练，有些东西咱们的文档中也没写，得一点点摸索，感谢你的帮助。

**Comment by Linary** [comment]
@1315861791 感谢使用，我们的文档会尽快补充。
