### ISSUE TITLE
求助：从一点出发找出n步内可以形成的环路怎么用gremlin写啦？

### ISSUE THREAD

**Issue by 1315861791** [hugegraph/hugegraph#312]
如题，求高手指点下怎么求环路（如a-->b-->c-->a）

**Comment by Linary** [comment]
可以使用 `repeat + until + cyclicPath` 试试。

这是大概的框架：
```
g.V().has('name', 'a').repeat(out()).until(has('name','a')).cyclicPath().path()
```

**Comment by 1315861791** [comment]
![image](https://user-images.githubusercontent.com/24642133/50633622-f14e8500-0f86-11e9-8e19-921bf6a2202e.png)
![image](https://user-images.githubusercontent.com/24642133/50633636-ff040a80-0f86-11e9-8991-edc084729f36.png)

**Comment by 1315861791** [comment]
@Linary 感谢您的指导，我也用这种类似的写法实现了一个，但结果跟你的一样，中间会来回重复
我的代码如下：
g.V('貂蝉')
.repeat(outE().inV())
.until(loops().is(gte(6))).dedup().hasId('貂蝉')
.cyclicPath().path()

**Comment by Linary** [comment]
试试这个呢。
```
g.V("貂蝉")
 .repeat(out())
 .until(id().is("貂蝉"))
 .cyclicPath()
 .path();
```

**Comment by 1315861791** [comment]
![image](https://user-images.githubusercontent.com/24642133/50637035-53ad8280-0f93-11e9-8683-766f02d9a1dc.png)
@Linary 执行不了

**Comment by Linary** [comment]
@1315861791 抱歉，语句写的有问题，应该是：

```
g.V('貂蝉').repeat(out()).until(hasId('貂蝉')).cyclicPath().path()
```

如果这样还不行，那就找一个“貂蝉这个顶点有的属性”，将判定条件换成对该属性的判断。比如“貂蝉”这个点有一个属性“name”也叫“貂蝉”，那就：

```
g.V('貂蝉').repeat(out()).until(has('name', '貂蝉')).cyclicPath().path()
```

**Comment by 1315861791** [comment]
@Linary ganxie感谢大神！！！
![image](https://user-images.githubusercontent.com/24642133/50677217-91fa7e80-1033-11e9-83ea-0ebc52ed49f7.png)
![image](https://user-images.githubusercontent.com/24642133/50677231-a0e13100-1033-11e9-89f7-04ec94f8a367.png)
