### ISSUE TITLE
是否可以使用gremlin driver 链接hugegraph 执行gremlin语句？

### ISSUE THREAD

**Issue by tsregll** [hugegraph/hugegraph#327]
### Expected behavior 期望表现
能够正确执行gremlin语句并返回

### Actual behavior 实际表现
出现异常
WARN org.apache.tinkerpop.gremlin.driver.MessageSerializer - Response [PooledUnsafeDirectByteBuf(ridx: 138, widx: 138, cap: 138)] could not be deserialized by org.apache.tinkerpop.gremlin.driver.ser.AbstractGryoMessageSerializerV1d0.
java.lang.IndexOutOfBoundsException: Index: 121, Size: 0

### Steps to reproduce the problem 复现步骤
1. 配置gremlin driver
3.3.3 版本 的gremlin driver 使用如下配置：
hosts: [xxx.xxx.xxx.xxx]
port: 8182
serializer: {className: org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV1d0,config: {serializeResultToString: false}}
connectionPool: {minSize: 5,maxSize: 30,maxContentLength: 6553200,maxWaitForConnection: 1000,maxInProcessPerConnection: 20}

2. 执行如下代码
	Cluster cluster;
		Client client;
	    File tempFile = new File("xxxx");
        if(!tempFile.exists()){
            //文件不存在，则创建
            try {
				tempFile.createNewFile();
			} catch (IOException e) {
				e.printStackTrace();
			}
        }
		cluster = Cluster.build(tempFile).create();
		client = cluster.connect();

		if (null != client) {
			client.init();
		} else {
			System.exit(0);
		}
		
		String gremlinStr = "return g.V().properties()";

		ResultSet results = client.submit(gremlinStr);
		if(results.toString().contains("Completed normally")){
			System.out.println("Success"+results.toString());
		}else if(results.toString().contains("Completed exceptionally")){
			System.out.println("Failure"+results.toString());

**Comment by Linary** [comment]
@tsregll 如果想使用gremlin-driver，首先应该修改gremlin-server.yaml的`channelizer`为`org.apache.tinkerpop.gremlin.server.channel.WebSocketChannelizer`，然后最好使用3.2.5版本的gremlin-driver（与hugegraph保持一致）再去尝试。

hugegraph还是推荐使用自己的HugeGraphServer，HugeGraphServer内部包装了一个原生的GremlinServer，但是并不敢保证某些上层的改动没有影响到GremlinServer，你可以按照我上面说的试试，但不保证能用。

**Comment by tsregll** [comment]
> @tsregll 如果想使用gremlin-driver，首先应该修改gremlin-server.yaml的`channelizer`为`org.apache.tinkerpop.gremlin.server.channel.WebSocketChannelizer`，然后最好使用3.2.5版本的gremlin-driver（与hugegraph保持一致）再去尝试。
> 
> hugegraph还是推荐使用自己的HugeGraphServer，HugeGraphServer内部包装了一个原生的GremlinServer，但是并不敢保证某些上层的改动没有影响到GremlinServer，我们也没有测试过用gremlin-driver是否可行，你可以按照我上面说的试试。

谢谢回答，我建议可以做一下这方面的兼容，目前很多使用titan或者是janusgraph的用户使用的客户端都是gremlin-driver，如果兼容较好的话，能够很好地和现有系统进行融合，从而更好地做出比较，做出技术选择

**Comment by Linary** [comment]
@tsregll 感谢您的建议，hugegraph会兼容gremlin-driver的。

**Comment by Linary** [comment]
@tsregll 我找到了一种可以运行的配置方式，请参考：https://github.com/hugegraph/hugegraph/issues/345
