### ISSUE TITLE
hugegraph-loader疑问

### ISSUE THREAD

**Issue by hklmuaqmn** [hugegraph/hugegraph#334]
使用hugegraph-loader导入顶点+边时， 请问顶点数据可以重复么？ 比如person.csv存放的是顶点的id+name属性， 如果该文件中存在两行完全相同的记录时， 批量导入时请问会不会有什么影响？

**Comment by javeme** [comment]
@hklmuaqmn 可以重复的，相同记录会覆盖前面已经存在的。

**Comment by hklmuaqmn** [comment]
@javeme
