### ISSUE TITLE
请问hugegraph顶点或边可以支持多标签吗？

### ISSUE THREAD

**Issue by learn-xujun** [hugegraph/hugegraph#339]
我们公司最近正在调研图数据库，考虑使用hugegraph，粗略看了下api，好像只能单个label，请问可以支持多标签吗？

**Comment by Linary** [comment]
@jizhidezhaojun hugegraph目前不支持多label

**Comment by jizhidezhaojun** [comment]
那请问是出于什么原因没有支持多标签呢？后续有没有支持多标签的计划？^_^
因为我们觉得多标签对于构建labeled property graph还是蛮重要的。

**Comment by Linary** [comment]
@jizhidezhaojun 目前没有支持主要是因为多标签会让元数据管理变得更为复杂。我们此前也曾考虑过支持多标签，但是因为某些原因搁置了。能简单描述一下你的需求场景吗，这可以帮助我们细化需求，制定方向。

**Comment by javeme** [comment]
@jizhidezhaojun 主要原因是由于hugegraph遵循的Apache Tinkerpop规范中仅支持单label。
不太清楚你那边的具体使用场景，如果需要分类的话可以使用一个单独地属性来标记。另外后续我们会考虑支持标签的继承。

**Comment by jadepeng** [comment]
> @jizhidezhaojun 主要原因是由于hugegraph遵循的Apache Tinkerpop规范中仅支持单label。
> 不太清楚你那边的具体使用场景，如果需要分类的话可以使用一个单独地属性来标记。另外后续我们会考虑支持标签的继承。

你好，label的继承又在做了吗？计划什么时候可以支持

今天使用hugegraph，遇到这个问题，看你们的文档中的例子（https://hugegraph.github.io/hugegraph-doc/language/hugegraph-example.html），通过额外的字段type回避这个问题

>因此本例子将原TitanDB中的monster, god, human, demigod均使用相同的vertex label: character来表示, 同时增加属性type来标识人物的类型。edge label与原TitanDB保持一致。当然为了满足edge label约束，也可以通过调整edge label的name来实现。

**Comment by javeme** [comment]
> 你好，label的继承在做了吗？计划什么时候可以支持

@jadepeng 目前还没有启动，一直被优先级更高的任务delay了，是否可以分享一下你的应用场景？
若不便公开的话可以加我们公众号联系管理员。

**Comment by javeme** [comment]
Label的继承 Issue #447

**Comment by jadepeng** [comment]
> @jadepeng 目前还没有启动，一直被优先级更高的任务delay了，是否可以分享一下你的应用场景？
> 若不便公开的话可以加我们公众号联系管理员。

你好，这边有一些图谱，按照学术界的RDF设计的概念树，概念（concept）存在继承关系，共性的关系定义在父概念，关系定义的时候sourceLabel，targetLabel是父概念，真实的rdf三元组，则是子概念。

**Comment by javeme** [comment]
@jadepeng 好的了解了，我们会进一步考虑该功能。
