### ISSUE TITLE
启动服务有时候会提示“The operation time out when attempting to connect to http://xxx:port/graphs”

### ISSUE THREAD

**Issue by angerlinalv** [hugegraph/hugegraph#34]
使用rocksdb存储，启动服务，服务已经启动成功，但是提示“The operation time out when attempting to connect to http://xxx:port/graphs”

**Comment by Linary** [comment]
@angerlinalv 这个应该是gremlin-server的端口被占用导致。我们会尽快修复该问题

**Comment by Linary** [comment]
@angerlinalv 该问题已经在该 [提交](https://github.com/hugegraph/hugegraph/commit/21271715b437f0805636245f2ca798a7af2222c1)中修复
