### ISSUE TITLE
HugeGraph0.8存在的问题

### ISSUE THREAD

**Issue by xu0612204126** [hugegraph/hugegraph#346]
**问题1：多图库，在initStore的时候，是不是所有的图库都被初始化了，数据都被清空了？**
 *问题描述：*在已经存在一个图库hugeGraph的前提下，又按照https://hugegraph.github.io/hugegraph-doc/config/config-guide.html的提示，添加了hugeGraph2，但是最后一步是需要** init-strore ,结果我在执行 init-Store的时候，后端提示是在初始化hugeGraph2 ，可是当使用 hugeGraph studio查询图库的时候，发现图库中的点 和边的个数都是0 了，这是为什么？
 HugeGraph studio中的配置如下：
[root@root conf]# vim hugegraph-studio.properties 
studio.server.port=8088
studio.server.host=192.168.28.128

graph.server.host=192.168.28.128
graph.server.port=8080
graph.name=hugegraph
**问题2 ：多图库时，如何使用suodio访问hugeGraph2**
我把 hugegraph-studio.properties  中的graph.name改成了hugegraph2的时候，再调用g.V().count(),浏览器返回的值为：

Error!
Could not rebind [g] to [__g_hugegraph2] as [__g_hugegraph2] not in the Graph or TraversalSource global bindings

不知道怎么做才能访问到 hugegraph2

**问题3：HugeGraph0.8版本是否支持模糊检索，后台的模糊的分词策略是什么？**

**Comment by Linary** [comment]
@xu0612204126 

> 问题1：多图库，在initStore的时候，是不是所有的图库都被初始化了，数据都被清空了？
只有新添加的图会被初始化，不会清空原有图的数据。

> 问题2 ：多图库时，如何使用suodio访问hugegraph2
将`hugegraph-studio.properties`的`graph.name`修改为`hugegraph2`，如下：
```
studio.server.port=8088
studio.server.host=192.168.28.128

graph.server.host=192.168.28.128
graph.server.port=8080
graph.name=hugegraph2
```

> 问题3：HugeGraph0.8版本是否支持模糊检索，后台的模糊的分词策略是什么？
0.8版本支持模糊检索，默认的分词器为`ikanalyzer`，选用的是它的`smart`模式。

**Comment by xu0612204126** [comment]
模糊检索，使用greemlin怎么检索？ 有文档说明吗？

**Comment by Linary** [comment]
@xu0612204126 文档还不完善，可以先参考一下：https://github.com/hugegraph/hugegraph/issues/294
