### ISSUE TITLE
hbase作为后端 server在初始化的时候会默认找zookeeper的hbase节点

### ISSUE THREAD

**Issue by eternalxj** [hugegraph/hugegraph#348]
hbase作为后端 server在初始化的时候会默认找zookeeper的hbase节点
/hbase/master、/hbase/hbaseid等等
而实际hbase配置在zookeeper的/hbase-unsecure/master 、/hbase-unsecure/hbaseid
这个如何在hugeserver上做配置修改？
@javeme @Linary

**Comment by Linary** [comment]
master分支上有一个提交 https://github.com/hugegraph/hugegraph/pull/333 
这个提交增加了一个配置项`hbase.znode_parent`可以指定hbase的zookeeper节点，默认值为/hbase，你修改成/hbase-unsecure即可。

**Comment by eternalxj** [comment]
@Linary 好的了解了，因为非coding人员 改起来可能有些困难，期望这个配置尽快上线
