### ISSUE TITLE
The operation timed out when attempting to connect to http://127.0.0.1:8080/graphs

### ISSUE THREAD

**Issue by oushu1liwenhui1** [hugegraph/hugegraph#349]
### Expected behavior 期望表现
{type something here...}

### Actual behavior 实际表现
{type something here...}

Starting HugeGraphServer...
Connecting to HugeGraphServer (http://127.0.0.1:8080/graphs)...............The operation timed out when attempting to connect to http://127.0.0.1:8080/graphs
See /Users/lwh/dev/hugegraph/distribution/hugegraph-0.8.0/logs/hugegraph-server.log for HugeGraphServer log output.
Failed to start HugeGraphServer, requires at least 512m free memory

但我确信不是内存问题，请问是怎么回事
### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by Linary** [comment]
你起服务的时候剩余的内存有多少呢？另外可以多提供一些你的环境信息吗？

**Comment by oushu1liwenhui1** [comment]
可以了，是内存不足
