### ISSUE TITLE
导数据慢，cpu闲置多

### ISSUE THREAD

**Issue by oushu1liwenhui1** [hugegraph/hugegraph#350]
我在mac上运行，后端cassandra
自己生成了大概800万个节点和1000万条边的数据，用loader导进去，但是速度很慢，大概1个半小时才导了100万个节点。并且cpu闲置很多，可见程序并未全力运行。
但是这篇博文说他每秒导入30万个节点。
https://blog.csdn.net/u010260089/article/details/84982777
请问是我哪里设置不对吗？
命令是这个，bin/hugegraph-loader -g hugegraph -f test/struct.json -s test/schema.groovy
数据大致是这样：
schema:
schema.propertyKey("身份证号").asText().ifNotExist().create();
schema.propertyKey("电话号码").asText().ifNotExist().create();
schema.propertyKey("犯罪类型").asText().ifNotExist().create();
schema.propertyKey("犯罪时间").asText().ifNotExist().create();
schema.propertyKey("是否涉毒").asText().ifNotExist().create();
schema.propertyKey("开始时间").asText().ifNotExist().create();
schema.propertyKey("通话时长").asInt().ifNotExist().create();
schema.vertexLabel("人物").properties("身份证号", "电话号码", "犯罪类型","犯罪时间","是否涉毒").primaryKeys("身份证号").nullableKeys("犯罪类>型", "犯罪时间","是否涉毒").ifNotExist().create();
schema.indexLabel("personByCode").onV("人物").by("身份证号").secondary().ifNotExist().create();
schema.edgeLabel("致电").sourceLabel("人物").targetLabel("人物").properties("开始时间", "通话时长").ifNotExist().create();
schema.indexLabel("phoneByDate").onE("致电").by("通话时长").range().ifNotExist().create();

节点：
155068735097041242,15975526234,null,null,false
168094109458937390,13105700894,null,null,false
184974733060149379,15980972008,类型2,2017/12/07/22:52,false
。。。
边：
{"sourceid": "216933876347098755", "targetid": "361416455139955988", "开始时间": "2018/08/07/12:39", "通话时长": 339}
{"sourceid": "484816396636289759", "targetid": "183602052220178371", "开始时间": "2018/07/19/20:11", "通话时长": 313}
{"sourceid": "249145893679126899", "targetid": "249058675166296461", "开始时间": "2017/02/16/09:45", "通话时长": 266}
{"sourceid": "114291298397849284", "targetid": "188168685830406410", "开始时间": "2017/09/02/00:42", "通话时长": 224}

**Comment by lazyermax** [comment]
后端数据局使用的什么？我用Cassandra也遇到这样的问题，每秒100+的效率不知道哪里问题

**Comment by imbajin** [comment]
> 后端数据局使用的什么？我用 Cassandra 也遇到这样的问题，每秒 100 + 的效率不知道哪里问题

100+ 一般是很明显的问题把, parse 异常,  低版本的 bug, 或者是 server 端/ loader 端的明显配置错误.
最简单的办法是, 你在 server 端同时开启一个 rocksdb 的后端(内置可一键启动, 无需额外配置)

然后对比一下同样的数据, 导入 rocksdb 的性能是否正常. (控制变量)
