### ISSUE TITLE
关于性能优化

### ISSUE THREAD

**Issue by eternalxj** [hugegraph/hugegraph#354]
目前有7亿的顶点 几千亿的边 边的导入性能还没有测试 
顶点的导入性能如下
前3分 加载了530w
63分钟 加载了8800W
170分钟 加载了 17000W
可以看出数据加载到越大 速度相对越慢
如果边的速度与顶点相似、那么可能要花费 十几天甚至一个月的时间导入
@Linary @javeme  是否能通过调整什么进行优化那？
对于这种数量级的查询 是否会存在问题？如何优化？

**Comment by javeme** [comment]
@eternalxj 请提供一下环境信息（比如后端类型、节点数量、ID策略及平均ID长度），每个顶点及边的平均长度多少字节？（长度越长插入速度越慢）
千亿级以上建议通过增加存储节点来提升导入性能，比如我们使用loader测试（20亿边的网址关联数据）Cassandra 20节点是`6.3w edges/s`的导入速度。
另外如果不需要按label查询的话可以关闭label-index提升性能。
查询理论上不会有问题，但是需要关注超级点会影响查询性能，另外大量删除数据后再做查询会严重影响读取性能（请避免做大量删除操作，如果必要的话可通过拷贝图并过滤来规避）。

**Comment by eternalxj** [comment]
存储是阿里云的存储、应该是普通的硬盘
huge后端存储是hbase 6个节点 每个节点2T存储    
顶点是基于id策略存储的 长度18位。
昨天使用6亿的顶点数据测试导入。导入到4亿多就没有继续导入，不清楚具体没有导入完成原因
目前g.v().count()查询不出具体数量
@javeme

**Comment by javeme** [comment]
@eternalxj hbase导入大量数据越来越慢确实是一个普遍的问题，可以网上搜索一下有不少解决方案（核心思想是优化：flush、compact、split）。
如果可以的话更建议使用Cassandra集群，根据我们的经验来说C*稳定性和性能均好一些，也易于维护。

**Comment by javeme** [comment]
> 顶点是基于id策略存储的

@eternalxj 这个是没有写全吗？

**Comment by zhangmeihaoaiya** [comment]
> @eternalxj hbase导入大量数据越来越慢确实是一个普遍的问题，可以网上搜索一下有不少解决方案（核心思想是优化：flush、compact、split）。
> 如果可以的话更建议使用Cassandra集群，根据我们的经验来说C*稳定性和性能均好一些，也易于维护。

造成"大量删除数据后再做查询会严重影响读取性能" 的原因是啥？如果做了大量删除，如何规避这个问题？重启server吗？

**Comment by javeme** [comment]
> 造成"大量删除数据后再做查询会严重影响读取性能" 的原因是啥？如果做了大量删除，如何规避这个问题？重启server吗？
@zhangmeihaoaiya 主要原因是读取时会从磁盘读取到大量的墓碑，并且最终被丢弃，同时还产生大量的垃圾导致GC压力大。
规避的话，可通过拷贝图并过滤来规避删除，或者大量删除后手动做compaction操作。
