### ISSUE TITLE
数据一致性问题

### ISSUE THREAD

**Issue by ghost** [hugegraph/hugegraph#358]
你好，有两个问题
1 看到以前的issue提过多个hugegraph sever会导致数据不一致的问题。请问这个不一致是否只是不同server缓存里的数据不一致，但cassandra里的数据是一致的？cassandra本身是否保证并发读写的时候数据一致？
2 用loader导数据时，将一个图分成多个文件，用多个hugegraph server同时导数据是否可以？

**Comment by zhoney** [comment]
@oushu1liwenhui1 

> 1 看到以前的issue提过多个hugegraph sever会导致数据不一致的问题。请问这个不一致是否只是不同server缓存里的数据不一致，但cassandra里的数据是一致的？cassandra本身是否保证并发读写的时候数据一致？

是的。只有缓存里的数据不一致。Cassandra本身可以保证并发读写一致性。

> 2 用loader导数据时，将一个图分成多个文件，用多个hugegraph server同时导数据是否可以？

理论上，可以这么做，因为导入数据不涉及HugeGraphServer的缓存。

请根据实际情况评估是否需要这么做。一般后端Cassandra/Hbase集群规模不太大时，单个loader的导入速度可以压满server端。

**Comment by choleraehyq** [comment]
@zhoney 想了解下，hugegraph 中怎么保证存储后端（hbase、cassandra等）中的数据与索引后端（ES 等）中的索引的一致性呢？

**Comment by oushu1liwenhui1** [comment]
> @zhoney 想了解下，hugegraph 中怎么保证存储后端（hbase、cassandra等）中的数据与索引后端（ES 等）中的索引的一致性呢？

每个索引都有读写锁，数据读出后会再过滤一遍，保证正确性。
