### ISSUE TITLE
后端支持pg和oracle

### ISSUE THREAD

**Issue by cmdares** [hugegraph/hugegraph#363]
当前图库可以支持mysql作为后端存储。能否再考虑改造下程序能够支持pg和oracle呢？
目前有一些小数据的场景，是pg或oracle环境。希望平台能给予支撑。
感谢!

**Comment by javeme** [comment]
@cmdares 理论上确实可以通过改造一下mysql后端驱动进行支持，不过由于之前没有该需求和环境。接下来我们可以一起来加入这个特性。

**Comment by cmdares** [comment]
感谢！辛苦！
