### ISSUE TITLE
关于按照边属性检索的问题

### ISSUE THREAD

**Issue by eternalxj** [hugegraph/hugegraph#365]
请教下，
场景:根据边trans的fee属性做筛查 求多度关系人
情况:有trans的边 边有fee这个属性，这个属性是有索引的,求00426064这个顶点有trans边关系的2度关系人
同时限定 fee <=470
具体语句如下
g.V('00426064').outE('trans').has('fee',lte('470.0')).inV().outE('trans').has('fee',lte('470.0')).inV() 执行不成功
报错Vertex '320722198411200048' does not exist 
查了下 g.V('320722198411200048') 是没有这个顶点的
但是g.V('00426064').outE('trans').inV().outE('trans').inV()  不加has条件则可以执行成功
但是g.V('00426064').outE('trans').inV().outE('trans').inV().path() 有会报错
Vertex '310104198801090107' does not exist 查了下也是没有这个顶点的

想知道出现这种情况是什么原因
想实现这个场景有什么其他解决方案吗？

@Linary @javeme

**Comment by javeme** [comment]
@eternalxj 看起来是顶点导入不全导致的，请尝试导入不存在的顶点再看看。
原因是路径中经过的点不存在，不同语句表现差异的根源我们会进一步分析，能否验证下一度关系是否也会报错：g.V('00426064').outE('trans').inV().path()

**Comment by eternalxj** [comment]
@javeme 一度也会报错 Vertex '310104198801090107' does not exist 
我理解是如果点不存在 那么边出现顶点则会连不上 
如果要这种情况 可以设置吗 ？

**Comment by eternalxj** [comment]
@javeme @Linary  同学，对于上面提到的场景可能更希望 导入边的时候当边需要的顶点不存在的时候，那么这条边是创建不成功的，在按照边属性查询的时候不会出现Vertex 'xxx' does not exist这种类似的问题

**Comment by Linary** [comment]
@eternalxj 你的数据量大吗？如果不大，可以重新导一遍，把 check-vertex 参数置为 true。

**Comment by eternalxj** [comment]
@Linary 挺大的目前是一百亿，计划是千亿左右 想了解下 如果加上这个参数大概速度回降低多少，比如不加是2s导入完成 加上一般会延迟到多久，目前是十亿顶点，3亿边 如果延迟比较大 那可能就只有在上游去控制顶点的问题了

**Comment by Linary** [comment]
@eternalxj 这么大的规模还是不要重新导入了，不加是2s，加了估计是3s多，影响还是比较明显的。

**Comment by eternalxj** [comment]
好的 了解 加了估计会延迟一倍左右，那我这边优先看看通过上游限制，多谢了

**Comment by baibingzhi** [comment]
@Linary @eternalxj  请问一下 check-vertex 参数 在哪里配置？谢谢！

**Comment by Linary** [comment]
@baibingzhi 该参数是在命令行中添加的

```
bin/hugegraph-loader --check-vertex true -g {GRAPH_NAME} -f ${INPUT_DESC_FILE} -s ${SCHEMA_FILE} -h {HOST} -p {PORT}
```
