### ISSUE TITLE
关于存储的问题

### ISSUE THREAD

**Issue by eternalxj** [hugegraph/hugegraph#366]
导入的顶点、边基本为text、json格式，占据空间较大，hugegraph-loader 可否导入其他格式的文件？
如果可以导入其他格式文件 那实际解析完传到graph(hbase后端)上 占据空间与使用text、json格式占据空间是否相同？
@Linary @javeme

**Comment by Linary** [comment]
目前loader仅支持本地磁盘的text（可自定义分隔符）、csv和json格式的文件，下一版本的数据源会支持hdfs和部分关系型数据库，hdfs除了继续支持上述的文本文件，还会支持一些压缩格式。

存储到hugegraph的数据一般都会比原始文件大，因为要保存一些额外的结构信息，比如元数据、索引等。

**Comment by zhoney** [comment]
@eternalxj 

文本格式的数据导入图数据库，由于存储格式的变化和辅助数据会有一定的膨胀。

另外需要额外注意的是，当使用Hbase或者Cassandra作为存储后端时，**replication**会线性增加所需的存储空间。

**Comment by eternalxj** [comment]
@Linary @zhoney 好的了解了，期待后续的数据压缩方案
另外  之前有  关于数据导入的问题 #356 这个问题 如果成型的版本支持解决这个问题 麻烦告知哈
