### ISSUE TITLE
重启HugeGraphServer超时，RocksDB不能被打开

### ISSUE THREAD

**Issue by suesunss** [hugegraph/hugegraph#367]
### Expected behavior 期望表现

**后端使用 RocksDB**

手动添加图配置后，重新 init 并启动 HugeGraphServer。

### Actual behavior 实际表现

重新 init，出现错误，如下：

```java
[event-worker-1] [WARN] com.baidu.hugegraph.event.EventHub [] - Failed to handle event : Event{name= 'store.inited', args = [com.baidu.hugegraph.backend.store.rocksdb.RocksDBStoreProvider]}

com.baidu.hugegraph.HugeException: Failed to update/query TaskStore
            at com.baidu.hugegraph.task.TaskScheduler.call(TaskScheduler.java: 397)
            ...
```

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

Number of graphs: around 100
Each: around 100,000 vertices, 10,000,000 edges

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
`0.9.1`
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
`Linux {username} 4.9.0-0.bpo.6-amd64 #1 SMP Debian 4.9.88-1+deb9u1~bpo8+1 (2018-05-13) x86_64 GNU/Linux`
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}
`RocksDB`

**Comment by zhoney** [comment]
@suesunss 请提供一下详细的复现步骤和配置文件。

包括：
- 是添加了一个图，还是在原来的基础上修改了图？
- 修改或者添加了哪些配置项？
- 修改或者添加图的具体步骤

**Comment by suesunss** [comment]
@zhoney 谢谢回复。

* 新添加了一个图
* 新增了图的 properties文件，在 `gremlin-server.yaml` 的 `graphs` 下加入了图的配置，也在`rest-server.properties`中添加了新图的配置
* 步骤
   * 关闭 HugeGraphServer，新增配置上述配置文件和配置
   * 重新执行 init.sh 脚本，init 出现失败
* init 的日志如下所示
```java
[event-worker-1] [WARN] com.baidu.hugegraph.event.EventHub [] - Failed to handle event : Event{name= 'store.inited', args = [com.baidu.hugegraph.backend.store.rocksdb.RocksDBStoreProvider]}

com.baidu.hugegraph.HugeException: Failed to update/query TaskStore
            at com.baidu.hugegraph.task.TaskScheduler.call(TaskScheduler.java: 397)
            ...
```
(完整的日志找不到了)

**Comment by zhoney** [comment]
@suesunss 

请尝试复现问题，确认问题是否仍存在。
如果问题仍存在，请并提供完整的错误信息（包括控制台和日志logs/hugegraph-server.log），以方便我们复现、解决。

新添加图流程：

0. 执行`bin/stop-hugegraph.sh`关闭原来的图
1. 增加图配置文件，例如conf/hugegraph1.properties
    - 如果是跟原图同样的后端，例如都是RocksDB，假设原图是`store=hugegraph1`，为新图使用不同的数据库名字`store=hugegraph1`
    - 如果需要，配置新图的存储位置，也可以不修改
2. 修改rest-server.properties文件，增加新图：
    - graphs=[hugegraph:conf/hugegraph.properties, hugegraph1:conf/hugegraph1.properties]
3. 修改conf/gremlin-server.yaml文件，增加新图：
    ```yaml
    graphs: {
      hugegraph: conf/hugegraph.properties,
      hugegraph1: conf/hugegraph1.properties
    }
    ```
4. 初始化新图，执行`bin/init-store.sh`，已经初始化的原图不会受影响
5. 启动两个图，`bin/start-hugegraph.sh`

**Comment by suesunss** [comment]
@zhoney 好的，我复现一下，谢谢回复。
