### ISSUE TITLE
关于正则匹配及模糊查询的问题？

### ISSUE THREAD

**Issue by oushu1zhangxiangxuan1** [hugegraph/hugegraph#372]
请问hugegraph目前支持全局的text的正则匹配或模糊查询吗？
TinkerPop官网说3.4.0版本支持简单的文本predicates，不知道hugegraph0.8.0版本的支不支持
![image](https://user-images.githubusercontent.com/39079736/53390634-b426d200-39ce-11e9-8d54-cf51146f3697.png)
或者有没有其他方法实现类似的功能
在网上搜到了其他的操作，但这种不能在hugegraph中使用，好像只支持JanusGraph
https://blog.csdn.net/Lindsey_Tai/article/details/81628883
![image](https://user-images.githubusercontent.com/39079736/53390722-167fd280-39cf-11e9-959b-40f1ac5065f7.png)

**Comment by suesunss** [comment]
参考这个[issue](https://github.com/hugegraph/hugegraph/issues/294)

**Comment by oushu1zhangxiangxuan1** [comment]
> 参考这个[issue](https://github.com/hugegraph/hugegraph/issues/294)

多谢，但是这个好像只支持分词后的全词匹配，不支持正则和模糊查询

例如“海淀区”用单独一个“淀”或者“淀区”是无法匹配到的，英文也是匹配整个word才行

请问还有什么workaround来支持正则吗

**Comment by javeme** [comment]
@oushu1zhangxiangxuan1 目前hugegraph的全文索引支持contains，还不支持regex与fuzzy。TinkerPop 3.4.0确实加入了TextP算子集以支持文本搜索，不过只是定义了标准，默认实现性能较差，后续hugegraph升级到TinkerPop 3.4.0预计也仅能提供默认实现版本（目前是TinkerPop 3.2.5）。

workaround可以通过词典映射来匹配，比如如下映射：
```
{
淀：[海淀, 白洋淀]
淀区：[海淀、海淀区]
}
```
另外，就是像janus一样依赖外部索引库实现，比如ES等。

**Comment by oushu1zhangxiangxuan1** [comment]
找到了一种不需要es和词典映射的方法实现子字符串匹配，但仍无法支持正则且大小写敏感
供大家参考：
// hugegraph.traversal().V().filter(values('lang','tag','addr','FullText1','weight','FullText','开始时间','name','犯罪类型','电话号码','涉毒','犯罪时间','身份证号').is(Text.contains('remlin')))

**Comment by oushu1zhangxiangxuan1** [comment]
> 找到了一种不需要es和词典映射的方法实现子字符串匹配，可以解决[#372 (comment)](https://github.com/hugegraph/hugegraph/issues/372#issuecomment-467702921)
> 中的无法匹配单个汉字或英文字母的问题，
> 但仍无法支持正则且大小写敏感
> 供大家参考：
> // hugegraph.traversal().V().filter(values('lang','tag','addr','FullText1','weight','FullText','开始时间','name','犯罪类型','电话号码','涉毒','犯罪时间','身份证号').is(Text.contains('remlin')))

而且不需要建立索引

**Comment by oushu1zhangxiangxuan1** [comment]
Done.

> 找到了一种不需要es和词典映射的方法实现子字符串匹配，可以解决[#372 (comment)](https://github.com/hugegraph/hugegraph/issues/372#issuecomment-467702921)
> 中的无法匹配单个汉字或英文字母的问题，
> 但仍无法支持正则且大小写敏感
> 供大家参考：
> // hugegraph.traversal().V().filter(values('lang','tag','addr','FullText1','weight','FullText','开始时间','name','犯罪类型','电话号码','涉毒','犯罪时间','身份证号').is(Text.contains('remlin')))

而且不需要建立索引

**Comment by javeme** [comment]
@oushu1zhangxiangxuan1 使用filter方式也是可以的，但是数据量大的时候效率不好，因此生产环境不建议在大数据量上进行filter。

**Comment by oushu1zhangxiangxuan1** [comment]
看来还是用ES做外部索引比较靠谱
