### ISSUE TITLE
关于用hbase作为存储后端表的问题

### ISSUE THREAD

**Issue by lookatkkkkkk** [hugegraph/hugegraph#378]
请问，用hbase作为存储后端，初始化完数据库后，hbase中出现一堆前缀为hugegraph:的表，比如：hugegraph:c、hugegraph:el、hugegraph:graph_fi......，怎么理解这些呢？

**Comment by javeme** [comment]
@lookatkkkkkk 这些表是用于存储元数据schema和图数据vertex、edge等信息的，比如`
hugegraph:el`用于存储边类型edge-label信息。
