### ISSUE TITLE
有计划支持两个vertex之间多条edge吗？

### ISSUE THREAD

**Issue by oushu1zhangxiangxuan1** [hugegraph/hugegraph#380]
![image](https://user-images.githubusercontent.com/39079736/53714450-5c361280-3e89-11e9-8ab4-2c675d244e1d.png)

**Comment by javeme** [comment]
@oushu1zhangxiangxuan1 非常抱歉，这个文档表达的意思可能不太准确（后续我们会修正），实际上hugegraph支持两类顶点之间有多重边类型，比如“人”与“人”之间既可以有“朋友”边也可以是“同学”边，不过hugegraph不允许“同学”作用其它类型的顶点上了，比如“人”与“书”之间。

**Comment by oushu1zhangxiangxuan1** [comment]
好的多谢啦
