### ISSUE TITLE
求教：BackendException 

### ISSUE THREAD

**Issue by baibingzhi** [hugegraph/hugegraph#381]
自己写的导入代码，
    while(...){
        graph.addVertices(subList);
    }
subList的size为100。一共几十万条数据，开始一直没问题，最后报了一次如下的错误，麻烦问下是什么原因造成的？谢谢！

"调用异常：class com.baidu.hugegraph.backend.BackendException: Failed to commit 893 statements: 'UPDATE graph_vertices SET LABEL=17,PROPERTIES=....."

**Comment by zhoney** [comment]
@baibingzhi 

这是后端存储是Cassandra时，一次性提交的数据量过大时出现的异常。

### 解决方法
修改Cassandra的配置文件中的批量操作数据大小

```
# Fail any batch exceeding this value. 50kb (10x warn threshold) by default.
batch_size_fail_threshold_in_kb: 50
```
