### ISSUE TITLE
请教十亿＋数据的查询 问题

### ISSUE THREAD

**Issue by platypus0127** [hugegraph/hugegraph#385]
刚接触图计算，对使用还不了解，请教一个问题：现在有10亿＋的数据， 想实现给定N个顶点，查出这所有顶点组成的图的子图。请问这个用gremlin语句实现呀。
  例如：给100个顶点，查询这100个顶点组成的图的所有子图？

谢谢！

**Comment by javeme** [comment]
@platypus0127 查询子图可以使用 [3.1.3 k-neighbor API](https://hugegraph.github.io/hugegraph-doc/clients/restful-api/traverser.html)

**Comment by platypus0127** [comment]
> @platypus0127 查询子图可以使用 [3.1.3 k-neighbor API](https://hugegraph.github.io/hugegraph-doc/clients/restful-api/traverser.html)

@javeme  那如果有一个100个节点构成的图，怎么把这图图作为参数传进去(ps: 我看了这个APi的参数，有起始点和终点但是没有图这个入参)。
谢谢！

**Comment by platypus0127** [comment]
> @platypus0127 查询子图可以使用 [3.1.3 k-neighbor API](https://hugegraph.github.io/hugegraph-doc/clients/restful-api/traverser.html)

![Uploading image.png…]()
这个api是查询每个节点联通哪些节点吧

**Comment by javeme** [comment]
> 这个api是查询每个节点联通哪些节点吧
@platypus0127 是的，我个人的建议是可以通过一个点为中心找到尽可能多的能圈住另外99个点的子图，因此推荐使用 k-neighbor API。
