### ISSUE TITLE
API使用：怎么把图作为参数传入API？

### ISSUE THREAD

**Issue by platypus0127** [hugegraph/hugegraph#389]
### Expected behavior 期望表现
在调用一个APi的时候怎么传递图

### Actual behavior 实际表现
请教各位：在#385 ， @javeme 大神提到了可以3.1.3 k-neighbor API完成子图查询，我的问题是怎么把这个图传入到这个api里（假入有100个节点构成的图，我该怎么把这100个节点构成的图封装后传入这个API呀?）？谢谢！

**Comment by platypus0127** [comment]
请教各位：在https://github.com/hugegraph/hugegraph/issues/385 ， @javeme  大神提到了可以3.1.3 k-neighbor API完成子图查询，我的问题是怎么把这个图传入到这个api里（假入有100个节点构成的图，我该怎么把这100个节点构成的图封装后传入这个API呀?）？  
谢谢！

**Comment by javeme** [comment]
@platypus0127  k-neighbor API不支持这个场景。“100个点构成的图”可能是一个相当复杂问题，有可能根本无法构成图（这种情况需要遍历整个图的所有数据后才能得出此结果）。我个人的建议是可以通过一个点为中心找到尽可能多的能圈住另外99个点的子图，因此推荐使用 k-neighbor API。
