### ISSUE TITLE
怎么调节http服务的并发数？

### ISSUE THREAD

**Issue by platypus0127** [hugegraph/hugegraph#390]
谢谢！

数据规模：亿节点与边

情况是这样的，我通过Http 请求调Hugegraph服务，单次请求耗时4S左右，然后我在shell模仿并发访问，5条的时候耗时约20S,  10条的时候带到了50S，通过并发实现得到的结论是并发没有去作用（程序已经检查过了没问题），我怀疑是不是Hugegraph的并发是不是需要修改配置文件，但在官网没有找到（https://hugegraph.github.io/hugegraph-doc/config/config-option.html）  

ps:大家在做并发测试的时候有没有遇到这样的怪毛病呀？谢谢！

**Comment by javeme** [comment]
@platypus0127 首先解答一下，目前http服务线程数不允许手动设置，只支持自动设置（数量为 2 * CPUs），即将发布的0.9版本支持手动配置该值。
另外并发慢的原因可能是和查询语句有关，可以提供一下查询语句、环境信息（CPU、内存、后端类型、磁盘类型）以供分析。单次请求耗时4S可能意味着一个请求本身会触发大量的数据访问，或许可以根据场景尝试优化一下查询。

**Comment by platypus0127** [comment]
> @ platypus0127首先解答一下，目前http服务线程数不允许手动设置，只支持自动设置（数量为2 * CPUs），即将发布的0.9版本支持手动配置该值。另外
> 并发慢的原因可能是和查询语句有关，可以提供一下查询语句，环境信息（CPU，内存，后端类型，磁盘类型）以供分析。单次请求耗时4S可能意味着一个请求本身会触发大量的数据访问，或许可以根据场景尝试优化一下查询。

非常感谢 @javeme , 如你所说，我们当时耗时长的原因找到了，是数据访问太的，路径查询的时候会经过了超级节点。现在避免超级节点后响应很快了。

**Comment by baibingzhi** [comment]
@platypus0127 请问下 如何避免超级节点的？
