### ISSUE TITLE
忽视超级节点的最短路径

### ISSUE THREAD

**Issue by platypus0127** [hugegraph/hugegraph#391]
### Expected behavior 期望表现
谢谢！
请教，我想实现忽视超级节点的最短路径，
使用的是api:https://hugegraph.github.io/hugegraph-doc/clients/restful-api/traverser.html 的 Shortest Path
现在有3个节点，马云、我、还有阿里巴巴公司， 如果不加筛选，我与马云的最短路径就是  我-》阿里巴巴-》马云， 但我设置 了超级节点（假如定义每个节点边数量待遇10000就要跳过这个节点），我希望在查找我与马云的最短路径的时候不要选  我-》阿里巴巴-》马云这条路，选其他的

### Actual behavior 实际表现
实际过程中我就使用了shortestPath 接口。 里面有一个参数degree(查询过程中，单个顶点最大边数目) ，让后我也设置了这个degree为一个10000的值，但是发现最短路径里还是包含了边数量待遇10000的节点。

问题：是不是我对这个参数理解有误呀？如果这个参数表达的不是这个意思，那怎么才能够实现我的要求呀？

谢谢！

**Comment by javeme** [comment]
@platypus0127 参数`degree`的含义是指最多只访问一个顶点的边的数量。如果需要跳过超级点目前需要使用Gremlin接口，我们也会考虑Shortest Path API以后支持该特性。

@zhoney 请关注。

**Comment by platypus0127** [comment]
> @platypus0127 参数`degree`的含义是指最多只访问一个顶点的边的数量。如果需要跳过超级点目前需要使用Gremlin接口，我们也会考虑Shortest Path API以后支持该特性。
> 
> @zhoney 请关注。

@javeme @zhoney 

你们好，还是关于超级节点的问题，我在改造最短路径会经过超级节点的问题，我阅读了Shortest Path API的源码（作为菜鸟，有的还没看懂0.0）,按照自己的理解加了if判断，避免超级节点，麻烦两位看看逻辑与位置对不对？谢谢 0.0！ 具体的情况见我上传的图片

ps: 代码不规范的地方麻烦先忽略
![image](https://user-images.githubusercontent.com/26076823/54589382-77477b80-4a60-11e9-9980-ef71853efdc4.png)

**Comment by zhoney** [comment]
@platypus0127 欢迎贡献代码^-^

- `v.path()`返回的是到达当前顶点经过的路径。
    - 比如存在路径：`v1->v2->v3`，当前的`v`是`v3`的话，`v.path()`返回的就是`[v1, v2, v3]`，并非当前顶点的边的数目

- 想要判断顶点的边的数目，应该是用`Iterator<Edge> edges=...`的数目来进行判断。
    - 例如，可以在查询时就通过设置`limit`参数为`max+1`进行限制，根据查回的结果判断是否超级点

    ```
    if (边的数目 == max + 1) {
        是超级点，跳过
    } else {
        不是超级点，继续
    }
    ```

**Comment by javeme** [comment]
> 2：我想把更改后的代码，提交到社区，那我是直接在这个ShortestPathAPI 修改好，还是另外起一个呀？

@platypus0127 首先非常感谢贡献代码。这个功能属于增强API，因此直接修改现有的ShortestPath即可，谢谢。

**Comment by zhoney** [comment]
@platypus0127 提交的最短路径代码有些修改意见，请及时更新代码。如果有不同意见也可以在pull request页面讨论，谢谢。
