### ISSUE TITLE
请问hugegraph支持无向边吗？

### ISSUE THREAD

**Issue by ChenBinaBGitHub** [hugegraph/hugegraph#394]
### Expected behavior 期望表现
{type something here...}

### Actual behavior 实际表现
{type something here...}

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by ChenBinaBGitHub** [comment]
请问hugegraph支持无向边吗？

**Comment by javeme** [comment]
@ChenBinaBGitHub hugegraph支持有向边（如“关注”关系），所以也兼容无向边（如“好友”关系），比如查询一个人的好友可以使用`g.V(id).both('friends')`。
