### ISSUE TITLE
请问，hugegraph支持修改属性名称吗？

### ISSUE THREAD

**Issue by ChenBinaBGitHub** [hugegraph/hugegraph#395]
### Expected behavior 期望表现
是否有如下类似的方法
schema.changeproperty('phone','dhhm') (changeproperty 假设是修改属性名称的方法)
将属性 phone 的名称 改成 dhhm

### Actual behavior 实际表现
{type something here...}

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by ChenBinaBGitHub** [comment]
janusGrpah 修改属性名称如下：
mgmt = graph.openManagement()
place = mgmt.getPropertyKey('place')
mgmt.changeName(place, 'location')
mgmt.commit()

hugeGraph 是否也有类似的方法呢

**Comment by javeme** [comment]
@ChenBinaBGitHub hugegraph目前还不支持PropertyKey changeName，不过如果使用loader导入数据的话可以用mapping方式将别名映射为属性名。changeName的需求如果较多的话我们后续也会考虑支持。

**Comment by ChenBinaBGitHub** [comment]
好的，谢谢
