### ISSUE TITLE
hugegraph对elasticsearch作为外部索引的支持

### ISSUE THREAD

**Issue by oushu1zhangxiangxuan1** [hugegraph/hugegraph#396]
### Expected behavior 期望表现
目前hugegraph貌似没有类似于janugraph的配置外部索引的地方，
如果要实现类似功能，应该怎么配置
![image](https://user-images.githubusercontent.com/39079736/54591045-53863480-4a64-11e9-8f4f-88adc440d635.png)
这个配置项好像是配置分词器的
![image](https://user-images.githubusercontent.com/39079736/54591120-84666980-4a64-11e9-840a-468fde1f5208.png)

### Actual behavior 实际表现
{type something here...}

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by javeme** [comment]
@oushu1zhangxiangxuan1 是的hugegraph目前内部不支持ES，如果需要集成ES可在应用层实现。

**Comment by oushu1zhangxiangxuan1** [comment]
thanks @javeme
