### ISSUE TITLE
边上的属性如何进行sum

### ISSUE THREAD

**Issue by 1315861791** [hugegraph/hugegraph#400]
![image](https://user-images.githubusercontent.com/24642133/54735365-bdc3e400-4be0-11e9-8b64-b3c3831b013a.png)
有这样三个点，我想先查到中间的点，然后对跟他关联的点分组，边上的属性求和，应该怎么写啦？我下面这个写法会报错，求大神指教：
g.V('12697902').bothE().as('e').otherV().as('v').group().by(values('电话号码')).by('e'.values('通话时长').sum())

**Comment by javeme** [comment]
@1315861791 上述语句有一点小错误，请尝试下是否需要这个效果：`g.V('12697902').bothE().as('e').otherV().as('v').group().by('电话号码').by(select('e').values('通话时长').sum())`

**Comment by 1315861791** [comment]
![image](https://user-images.githubusercontent.com/24642133/54801363-7e110100-4ca1-11e9-9c17-53f8216e10fb.png)
这样语法不报错了，只是不出来东西，谢谢指点

**Comment by 1315861791** [comment]
搞定了，谢谢大神！

**Comment by 1315861791** [comment]
@javeme 麻烦再请教一下，我分组的时候同时求sum和count可以吗？

**Comment by 1315861791** [comment]
![image](https://user-images.githubusercontent.com/24642133/54804289-d948f080-4cad-11e9-9dc2-ca24a28e935a.png)
我用union语句写了一个，但我觉得分组的动作进行了两次，效率可能比较低
