### ISSUE TITLE
边上的字符串属性，中间两位比较大小，如何截取

### ISSUE THREAD

**Issue by 1315861791** [hugegraph/hugegraph#404]
边上的字符串属性，中间两位比较大小，如何截取

**Comment by javeme** [comment]
@1315861791 截取可使用函数`property.substring(int beginIndex, int endIndex)`

**Comment by 1315861791** [comment]
谢谢

**Comment by 1315861791** [comment]
@javeme 
![image](https://user-images.githubusercontent.com/24642133/54908406-c8ed7b80-4f22-11e9-9a96-f7885fd9519c.png)麻烦问下这个应该怎么写啦？能给我推荐一下可以学习这些语法的资料吗？

**Comment by 1315861791** [comment]
@javeme gremlin和hugegraph相关的资料太难找了，不用说书籍，一个小册子都找不到。强烈建议你这么有能力的人出一本相关的书。

**Comment by 1315861791** [comment]
![image](https://user-images.githubusercontent.com/24642133/54909226-aa887f80-4f24-11e9-81d9-e7273fe5f85a.png)
@javeme 您有空时麻烦指点下在这个语句中怎么写截取

**Comment by javeme** [comment]
> gremlin和hugegraph相关的资料太难找了，不用说书籍，一个小册子都找不到。强烈建议你这么有能力的人出一本相关的书。

@1315861791 Gremlin可以参考一下[深入学习图数据库语言Gremlin 系列文章链接汇总](https://blog.csdn.net/javeme/article/details/82631834)

**Comment by 1315861791** [comment]
恩恩这个系列的文章我去年10月份认真跟着操作过一遍。能帮忙指点下我这个语句怎么写吗？

**Comment by javeme** [comment]
@1315861791 纯粹的截取字符串可以使用如下语句：
`g.V('10086').bothE().values('开始时间').map{it.get().substring(0, 3)}`

如果是过滤可以用filter代替map。

**Comment by 1315861791** [comment]
非常感谢！！！
