### ISSUE TITLE
是否可以在window上运行源码

### ISSUE THREAD

**Issue by shaohj** [hugegraph/hugegraph#406]
### Expected behavior 期望表现
window上使用idea或eclipse运行源码，若可以的话，能否举个例子，如在eclipse和idea中启动步骤。

### Actual behavior 实际表现
目前发现只能在linux上用相关的.sh启动

**Comment by javeme** [comment]
@shaohj 由于Windows用户较少所以没有进行适配，理论上hugegraph是可以跨平台的。有Windows环境需求的同学可以尝试适配主要包括：依赖库适配、脚本适配，有什么问题我们可以提供帮助，当然我们也期待能贡献到社区来。

**Comment by shaohj** [comment]
@javeme 好的，多谢。
