### ISSUE TITLE
hugeClient.graphs().clear(graphName,"I'm sure to delete all data");

### ISSUE THREAD

**Issue by 1315861791** [hugegraph/hugegraph#407]
![image](https://user-images.githubusercontent.com/24642133/54901460-7ce60b00-4f11-11e9-879d-a17b98cc5e69.png)
![image](https://user-images.githubusercontent.com/24642133/54901477-87a0a000-4f11-11e9-9297-173e68aef82d.png)
执行了一次hugeClient.graphs().clear(graphName,"I'm sure to delete all data");之后所有操作都会报这个错了

**Comment by Linary** [comment]
@1315861791 你构造HugeClient的语句是怎样的？

**Comment by javeme** [comment]
@1315861791 服务端日志是否有如下类似报错信息：
```
com.baidu.hugegraph.HugeException: Failed to update/query TaskStore
Caused by: java.lang.IllegalArgumentException: Undefined vertex label: '~task'
```

**Comment by 1315861791** [comment]
![image](https://user-images.githubusercontent.com/24642133/55213574-aadb9000-522e-11e9-9f5c-c80cdf62573c.png)
![image](https://user-images.githubusercontent.com/24642133/55213598-c21a7d80-522e-11e9-84cc-9e5df0c3c65e.png)
@Linary 出错之后我把hbase中相关的表都删了，重新初始化数据库之后这段时间没再报错。您看看这么写有毛病吗？虽然生产上不会出现清除全库的情况，但还是想弄明白原因
