### ISSUE TITLE
union 里面不能有toSet() 或toSet().Size()的结果吗？

### ISSUE THREAD

**Issue by baibingzhi** [hugegraph/hugegraph#408]
union 里面不能有toSet() 或toSet().Size()的结果吗？

现象1：
执行gremlin:
g.V().limit(1).union(g.V(xxx).emit().repeat(both().simplePath()).until(__.not(both().simplePath()).or().loops().is(5)).toSet())
报错：
Error!
No signature of method: org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.DefaultGraphTraversal.union() is applicable for argument types: (java.util.HashSet) values: [[]] Possible solutions: init(), min(), unique(), join(java.lang.String), find(), unique(java.util.Comparator)

现象2：
执行gremlin：g.V().limit(1).union(g.V(xxx).emit().repeat(both().simplePath()).until(__.not(both().simplePath()).or().loops().is(5)).toSet().size())
报错：
Error!
No signature of method: org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.DefaultGraphTraversal.union() is applicable for argument types: (java.lang.Integer) values: [0] Possible solutions: init(), min(), unique(), join(java.lang.String), find(), unique(java.util.Comparator)

**Comment by zhoney** [comment]
@baibingzhi `union()`里面只能用traversal，`toSet()`和`toSet().size()`分别是`Set<Vertex>`和`int`
