### ISSUE TITLE
K-out 接口返回异常请教

### ISSUE THREAD

**Issue by Ghosttttt** [hugegraph/hugegraph#410]
### Expected behavior 期望表现

#
![image](https://user-images.githubusercontent.com/33200069/55052455-01609700-5094-11e9-9e5e-5de9cc8c90a2.png)
## Actual behavior 实际表现
{type something here...}
![image](https://user-images.githubusercontent.com/33200069/55052324-74b5d900-5093-11e9-9523-cf10434da7a2.png)

### Steps to reproduce the problem 复现步骤
采用hugegraph-client中k-out的测试样例，
![image](https://user-images.githubusercontent.com/33200069/55052409-c8c0bd80-5093-11e9-9301-b49370bc2c75.png)
其中遍历深度确认是给定的，疑惑为什么还会报这种错？

**Comment by zhoney** [comment]
@Ghosttttt 请提供一下使用的hugegraph和hugegraph-client版本号。

**Comment by Ghosttttt** [comment]
hugegraph-client:1.6.9
 hugegraph:0.9.1 @zhoney 
直接是在client中跑的test

**Comment by zhoney** [comment]
@Ghosttttt 
0.9属于未发布版，开发过程中会有变动。可以把server端更新为最新的master分支来解决问题。

根据你的报错信息，server端不是最新的master分支。
k-out的参数在0.9有一个变动，`depth`->`max_depth`，你使用的版本可能恰好是更新过程中的。

**Comment by Ghosttttt** [comment]
非常感谢回答， 但是我是直接使用hugegraph-cliet的代码进行测试的，和hugegraph的version应该没有关系吧？

**Comment by zhoney** [comment]
@Ghosttttt hugegraph-client是封装的RESTful API，比如最新的发送的参数是`max_depth`，而server端预期接收的参数是`depth`，所以就认为没有传参数，认为`depth`参数是0，所以检查参数时会报错。

**Comment by Ghosttttt** [comment]
好的 非常感谢
