### ISSUE TITLE
请教统计性能比较，shark与异步任务

### ISSUE THREAD

**Issue by JhihJian** [hugegraph/hugegraph#415]
请问在大数据量的情况下，
使用java client 查询shard做节点统计、
和用gremlin语言 异步任务count
哪种方式会更好？

**Comment by javeme** [comment]
@JhihJian 单机建议使用gremlin的count，若是存储集群的话可以多线程并发查shard进行统计，程序控制的好的话有可能会快一些。

**Comment by JhihJian** [comment]
> @JhihJian 单机建议使用gremlin的count，若是存储集群的话可以多线程并发查shard进行统计，程序控制的好的话有可能会快一些。

好嘞，非常感谢您的回复！
