### ISSUE TITLE
异步执行count任务拿到结果与预期不符？

### ISSUE THREAD

**Issue by Ghosttttt** [hugegraph/hugegraph#420]
### Expected behavior 期望表现
![image](https://user-images.githubusercontent.com/33200069/55217159-c5ffcd00-5239-11e9-8384-7ba7a5bd4ea1.png)
返回点的个数

### Actual behavior 实际表现
![image](https://user-images.githubusercontent.com/33200069/55217211-ea5ba980-5239-11e9-8c5e-9c1601e5b986.png)
试了几次拿到的结果都是1，是在执行异步任务的时候有什么别的需要注意的吗？

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by javeme** [comment]
@Ghosttttt 这里的1表示结果的数量，可以使用`g.V().count().next()`获取count本身的值。
