### ISSUE TITLE
执行init-store.sh时报错

### ISSUE THREAD

**Issue by chrischeng021** [hugegraph/hugegraph#425]
### Expected behavior 期望表现
{type something here...}

### Actual behavior 实际表现
root@ubuntu:/opt/hugegraph-0.8.0# **./bin/init-store.sh**
Initing HugeGraph Store...
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Java版本如下：**
root@ubuntu:/opt/hugegraph-0.8.0# java -version
openjdk version "9"
OpenJDK Runtime Environment (build 9+181)
OpenJDK 64-Bit Server VM (build 9+181, mixed mode)

**手动指定_JAVA_OPTIONS=-Xms512m时仍然报同样的错**

**系统可用内存如下：**
root@ubuntu:/opt/hugegraph-0.8.0# free -h
              total        used        free      shared  buff/cache   available
Mem:           125G        6.5G        8.9G        1.3G        110G        117G
Swap:            0B          0B          0B

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: 0.8.0
- operating system: ubuntu on Docker
- hugegraph backend: rocksdb

**Comment by javeme** [comment]
duplicated by hugegraph/hugegraph-tools#25
