### ISSUE TITLE
设定后端存储为memory时启动报错

### ISSUE THREAD

**Issue by chrischeng021** [hugegraph/hugegraph#426]
### Expected behavior 期望表现
HugeGraph正常启动

### Actual behavior 实际表现
HugeGraph启动失败

### Steps to reproduce the problem 复现步骤
**hugegraph.properties配置如下：**
backend=memory
serializer=text
store=hugegraph

**执行启动脚本：**
root@ubuntu:/opt/hugegraph-0.8.0# ./bin/start-hugegraph.sh
Starting HugeGraphServer...
Connecting to HugeGraphServer (http://127.0.0.1:8080/graphs)...............The operation timed out when attempting to connect to http://127.0.0.1:8080/graphs
See /opt/hugegraph-0.8.0/logs/hugegraph-server.log for HugeGraphServer log output.

**错误日志：**
root@ubuntu:/opt/hugegraph-0.8.0# cat logs/hugegraph-server.log
Exception in thread "main" java.lang.IllegalStateException: Can't read file '/backend.properties' as stream
	at com.google.common.base.Preconditions.checkState(Preconditions.java:199)
	at com.baidu.hugegraph.util.E.checkState(E.java:68)
	at com.baidu.hugegraph.dist.RegisterUtil.registerBackends(RegisterUtil.java:55)
	at com.baidu.hugegraph.dist.HugeRestServer.register(HugeRestServer.java:50)
	at com.baidu.hugegraph.dist.HugeGraphServer.main(HugeGraphServer.java:46)
2019-04-01 18:37:15 1229  [Thread-0] [INFO ] com.baidu.hugegraph.dist.HugeGraphServer [] - HugeGraphServer stopped
Please make sure that the JDK is installed and the version >= 1.8

**Java版本信息：**
root@ubuntu:/opt/hugegraph-0.8.0# java -version
Picked up _JAVA_OPTIONS: -Xmx512m
openjdk version "9"
OpenJDK Runtime Environment (build 9+181)
OpenJDK 64-Bit Server VM (build 9+181, mixed mode)

PS: 取消JVM参数限制后，错误相同

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by javeme** [comment]
@chrischeng021 请问你是否使用了Linux系统发行版发布的JDK？这个看起来是JDK不兼容导致的。
解决方法：请手动下载官方的OpenJDK或者OracleJDK。
下载地址：http://openjdk.java.net/install/index.html ，安装后记得修改环境变量。


ps 这是我本地正常运行的Java环境：
```
$ java -version
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
```

**Comment by javeme** [comment]
duplicated by https://github.com/hugegraph/hugegraph-tools/issues/25
