### ISSUE TITLE
hugegraph-server 的cpu和io如何保证？

### ISSUE THREAD

**Issue by Ghosttttt** [hugegraph/hugegraph#430]
### Expected behavior 期望表现
hugegraph-server 目前只支持单机，那要是线上查询和插入数据量或者次数增多，那是否机器cpu和io都无法保证，从而影响性能?

**Comment by javeme** [comment]
@Ghosttttt 一般场景不存在这个瓶颈。为了具体评估请提供一下数据规模与需求场景，以及硬件情况（CPU、内存、磁盘）、tps和qps（包括典型查询语句复杂度）。
