### ISSUE TITLE
hugegraph-server高可用大概何时可以支持？

### ISSUE THREAD

**Issue by Ghosttttt** [hugegraph/hugegraph#435]
### Expected behavior 期望表现
如标题，1.看之前的issue说server高可用在开发计划中，预计什么时候可以支持呢？2.其次，多个server连接同一个后端会有缓存数据不一致的问题，那如果关闭缓存，那是否就意味着可以线性扩展server了呢？

**Comment by javeme** [comment]
@Ghosttttt 分别解答：
> 1.看之前的issue说server高可用在开发计划中，预计什么时候可以支持呢？

1.HA目前已经支持，不过放在了商业版本中。

> 2.其次，多个server连接同一个后端会有缓存数据不一致的问题，那如果关闭缓存，那是否就意味着可以线性扩展server了呢？

2.如果说没有同时的在线写入操作，那么理论上关闭缓存后是可以扩展server的；如果有写入操作建议只在一个server节点进行写入，此外请勿更新schema元数据。

**Comment by Ghosttttt** [comment]
@javeme 好的，感谢  还有一个疑问，写入操作建议只在一个server节点写入的原因是？

**Comment by oushu1liwenhui1** [comment]
> @Ghosttttt 分别解答：
> 
> > 1.看之前的issue说server高可用在开发计划中，预计什么时候可以支持呢？
> 
> 1.HA目前已经支持，不过放在了商业版本中。
> 
> > 2.其次，多个server连接同一个后端会有缓存数据不一致的问题，那如果关闭缓存，那是否就意味着可以线性扩展server了呢？
> 
> 2.如果说没有同时的在线写入操作，那么理论上关闭缓存后是可以扩展server的；如果有写入操作建议只在一个server节点进行写入，此外请勿更新schema元数据。

请问下，关闭缓存后，不能多节点同时写入吗？为什么？HBase或cassandra不是能保证一致性吗？

**Comment by javeme** [comment]
@oushu1liwenhui1 理论上在不更新schema元数据的情况下多个server写入**可能**也没什么问题。后期HugeGraph会支持分布式的server以及支持原子的read-update-write操作。

**Comment by javeme** [comment]
相关HA问题：#17

**Comment by JackyYangPassion** [comment]
> @oushu1liwenhui1 理论上在不更新schema元数据的情况下多个server写入**可能**也没什么问题。后期HugeGraph会支持分布式的server以及支持原子的read-update-write操作。

@javeme 目前最新版本0.11.2 几个问题
1. hugegraph-server已经支持分布式了 看配置文件中有相关配置项 但是从官方文档没看到具体咋应用
`raft.mode=false
raft.safe_read=false
raft.use_snapshot=false
raft.endpoint=127.0.0.1:8281
raft.group_peers=127.0.0.1:8281,127.0.0.1:8282,127.0.0.1:8283
raft.path=./raft-log
raft.use_replicator_pipeline=true
raft.election_timeout=10000
raft.snapshot_interval=3600
raft.backend_threads=48
raft.read_index_threads=8
raft.queue_size=16384
raft.queue_publish_timeout=60
raft.apply_batch=1
raft.rpc_threads=80
raft.rpc_connect_timeout=5000
raft.rpc_timeout=60000`
2. 如果不支持，看完issue 是不是在不用缓存的情况下 用HAProxy 或 Nginx 做负载均衡 有具体应用建议吗

**Comment by JackyYangPassion** [comment]
> @Ghosttttt 分别解答：
> 
> > 1.看之前的issue说server高可用在开发计划中，预计什么时候可以支持呢？
> 
> 1.HA目前已经支持，不过放在了商业版本中。
> 
> > 2.其次，多个server连接同一个后端会有缓存数据不一致的问题，那如果关闭缓存，那是否就意味着可以线性扩展server了呢？
> 
> 2.如果说没有同时的在线写入操作，那么理论上关闭缓存后是可以扩展server的；如果有写入操作建议只在一个server节点进行写入，此外请勿更新schema元数据。

@javeme 商业版有功能介绍吗 想具体了解下

**Comment by javeme** [comment]
@JackyYangPassion 使用HBase的情况下，多个Server可以一写多读的方式。社区版缓存同步预计会在下个版本支持。RocksDB后端0.11版支持多个Server同时读写。

**Comment by JackyYangPassion** [comment]
嗯，通过阅读源码今天部署起来了，HugeGraph越来越强～

**Comment by JackyYangPassion** [comment]
> @JackyYangPassion 使用HBase的情况下，多个Server可以一写多读的方式。社区版缓存同步预计会在下个版本支持。RocksDB后端0.11版支持多个Server同时读写。

统一缓存对于提升OLTP性能会很赞

**Comment by zsy-042** [comment]
@JackyYangPassion 方便分享一下分布式部署的思路吗？有教程就更好啦

**Comment by JackyYangPassion** [comment]
> @JackyYangPassion 方便分享一下分布式部署的思路吗？

用 HAProxy 做负载均衡，后端挂载多个HugeServer；后端存储分布式我这边采用的是HBase作为后端存储

**Comment by liweidong1216** [comment]
> > @JackyYangPassion 方便分享一下分布式部署的思路吗？
> 
> 用 HAProxy 做负载均衡，后端挂载多个HugeServer；后端存储分布式我这边采用的是HBase作为后端存储

现在部署用的是0.11.2这个版本么？实现的高可用是一写多读还是，多写多读的方式呢？

**Comment by liweidong1216** [comment]
> > @JackyYangPassion 方便分享一下分布式部署的思路吗？
> 
> 用 HAProxy 做负载均衡，后端挂载多个HugeServer；后端存储分布式我这边采用的是HBase作为后端存储

现在缓存状态是启用还是关闭来搭建的高可用集群呢？

**Comment by chencjiajy** [comment]
> 理论上在不更新schema元数据的情况下多个server写入**可能**也没什么问题。后期HugeGraph会支持分布式的server以及支持原子的read-update-write操作。
@javeme 
不太懂java，看了些源码，还在学习中，目前为止还不理解以下几个问题：
1. 为什么不能更新schema 元数据？
2. 多个server 写入为什么是**可能**也没什么问题，而不是不会有问题（跟原子的read-update-write操作有关系吗）
3. HugeGraph 支持分布式的server 预计什么时候发布呢？

**Comment by ghostmickey** [comment]
我有个设想，是不是可以做二开，把缓存改成分布式的，比如嵌入式的ignite、hazelcast之类的分布式数据网格来做缓存的话，就可以直接起多个server前面挂nginx来做高可用了呢？这样实现会不会有什么问题？

**Comment by javeme** [comment]
最新发布的0.12.0版已经内置支持高可用特性了
