### ISSUE TITLE
删除操作是会将底层存储的数据删掉吗？

### ISSUE THREAD

**Issue by 1315861791** [hugegraph/hugegraph#436]
麻烦问一下：下面这种删除操作会删掉存储在hbase中的数据吗？
hugeClient.schema().removeVertexLabel("电话");
hugeClient.schema().removeEdgeLabel("通话");
hugeClient.graph().removeEdge(id);
hugeClient.graph().removeVertex(id);
另外能不能通过list<id>的形式批量删除点或者边？

**Comment by 1315861791** [comment]
@Linary 麻烦问一下图库对索引的数量有要求吗？建多了索引会不会有什么副作用？另外再请教一下通过上述操作删除点和边是在磁盘层面删除吗？还是给数据做个标记并不释放磁盘占用？

**Comment by 1315861791** [comment]
这两种删除方式哪一种效率高一些啦：
schema.vertexLabel(name).remove();
hugeClient.schema().removeVertexLabel("电话");

**Comment by Linary** [comment]
> 麻烦问一下：下面这种删除操作会删掉存储在hbase中的数据吗？
> hugeClient.schema().removeVertexLabel("电话");
> hugeClient.schema().removeEdgeLabel("通话");
> hugeClient.graph().removeEdge(id);
> hugeClient.graph().removeVertex(id);
> 另外能不能通过list的形式批量删除点或者边？

会删掉存储在hbase中的数据。目前没有批量删除顶点/边的RESTful API。

**Comment by 1315861791** [comment]
好的，谢谢

**Comment by Linary** [comment]
> @Linary 麻烦问一下图库对索引的数量有要求吗？建多了索引会不会有什么副作用？另外再请教一下通过上述操作删除点和边是在磁盘层面删除吗？还是给数据做个标记并不释放磁盘占用？

图库对索引数量理论上没要求，建多了最明显的副作用就是插入数据时会变慢了一些。通过上述操作删除点和边对于现有的大多数hugegraph后端都是标记删除法，先给待删除的数据做一个标记，等到一个合适的时机再真正的删除磁盘数据。

**Comment by Linary** [comment]
> 这两种删除方式哪一种效率高一些啦：
> schema.vertexLabel(name).remove();
> hugeClient.schema().removeVertexLabel("电话");

效率完全一样，第一种方式只是多了一次本地函数调用，不会对效率有任何影响。

**Comment by 1315861791** [comment]
@Linary 感谢解答，想再问一下：对于hbase后端来说真正删除磁盘数据的机制是什么样的？
