### ISSUE TITLE
请问search index是干什么用的？

### ISSUE THREAD

**Issue by ghost** [hugegraph/hugegraph#449]
我为某属性建了search index,但使用时并不支持搜索，
如查询语句为，g.V().has('身份证号','140922194606032661')，会出现如下错误 
Don't accept query based on properties [身份证号] that are not indexed in any label, may not match secondary condition

那么，这个索引应该怎么用？

**Comment by 1315861791** [comment]
看ID应该是偶数的朋友，你问的这点我刚好知道：是用于字符串的模糊搜索的，配置文件中可以配上分词器，查询语句可以这么写：g.V().has('身份证号',Text.contains('140922194606032661')）

**Comment by oushu1liwenhui1** [comment]
> 看ID应该是偶数的朋友，你问的这点我刚好知道：是用于字符串的模糊搜索的，配置文件中可以配上分词器，查询语句可以这么写：g.V().has('身份证号',Text.contains('140922194606032661')）

感谢赐教，还有个问题，我用restapi想在已有数据上建索引，request为
{
    "name": "personByName2",
    "base_type": "VERTEX_LABEL",
    "base_value": "person",
    "index_type": "SEARCH",
    "fields": [
        "姓名"
    ]
}
但是返回错误
{
    "exception": "class javax.ws.rs.NotSupportedException",
    "message": "HTTP 415 Unsupported Media Type",
    "cause": ""
}
请问这是怎么回事？

**Comment by 1315861791** [comment]
要使用SEARCH得修改hugegraphservice的配置文件

**Comment by oushu1liwenhui1** [comment]
> 要使用SEARCH得修改hugegraphservice的配置文件

请问应该如何改？另外，我觉得这个错误不是索引类型的问题，因为我把类型改为secondary也会报错。不知道hugegraph现在是否支持在已有数据中建索引？

**Comment by 1315861791** [comment]
可一建多个索引，只要不重名就行

**Comment by 1315861791** [comment]
你的报错我没遇到过，不清楚咋回事

**Comment by 1315861791** [comment]
SEARCH可以这么配置：
在hugegraph.properties 中加入
search.text_analyzer=jieba
search.text_analyzer_mode=INDEX

**Comment by oushu1liwenhui1** [comment]
> SEARCH可以这么配置：
> 在hugegraph.properties 中加入
> search.text_analyzer=jieba
> search.text_analyzer_mode=INDEX

收到，谢谢

**Comment by javeme** [comment]
多谢 @1315861791 的解答。
@oushu1liwenhui1 看你举例中的身份证号，如果需要完全匹配的话，其实建议使用secondary index。search index更多的是用于描述信息的检索，如爱好、住址等信息根据部分词来搜索。

> 但是返回错误
> {
> "exception": "class javax.ws.rs.NotSupportedException",
> "message": "HTTP 415 Unsupported Media Type",
> "cause": ""
> }
> 请问这是怎么回事？

发送HTTP请求的时候请设置`Content-Type: application/json`。

**Comment by oushu1liwenhui1** [comment]
> 多谢 @1315861791 的解答。
> @oushu1liwenhui1 看你举例中的身份证号，如果需要完全匹配的话，其实建议使用secondary index。search index更多的是用于描述信息的检索，如爱好、住址等信息根据部分词来搜索。
> 
> > 但是返回错误
> > {
> > "exception": "class javax.ws.rs.NotSupportedException",
> > "message": "HTTP 415 Unsupported Media Type",
> > "cause": ""
> > }
> > 请问这是怎么回事？
> 
> 发送HTTP请求的时候请设置`Content-Type: application/json`。

收到，谢谢
