### ISSUE TITLE
rocksdb存储，Undefined vertex label:‘~task’

### ISSUE THREAD

**Issue by JhihJian** [hugegraph/hugegraph#454]
暂无稳定复现步骤，但这个问题出现好多次了。
先前是可以正常使用的，但某次操作之后就会出现这个问题，查询异步task和删除schema都会报这个错
java.util.concurrent.ExecutionException:java.lang.IllegalArgumentException:Undefined vertex label:'~task'
进行的操作包括但不限于通过restful api删除所有数据，使用java client 删除schema信息

**Comment by javeme** [comment]
@JhihJian 这个问题已经解决了 #314 ，将会在0.9版本中发布。
