### ISSUE TITLE
Http-Clinet连接不上显示

### ISSUE THREAD

**Issue by ychmc** [hugegraph/hugegraph#457]
HugeClient hugeClient = new HugeClient("http://localhost:8088", "hugegraph");
这一句连接报错
Exception in thread "main" java.lang.ExceptionInInitializerError
at com.baidu.hugegraph.driver.HugeClient.(HugeClient.java:34)
at HugegraphApi.BatchExample.main(BatchExample.java:53)
Caused by: java.lang.IllegalArgumentException: The version to match is null
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:146)
at com.baidu.hugegraph.util.E.checkArgumentNotNull(E.java:62)
at com.baidu.hugegraph.util.VersionUtil.match(VersionUtil.java:37)
at com.baidu.hugegraph.util.VersionUtil.check(VersionUtil.java:52)
at com.baidu.hugegraph.version.ClientVersion.check(ClientVersion.java:38)
at com.baidu.hugegraph.version.ClientVersion.(ClientVersion.java:29)

我是使用maven-assembly-plugin进行打包成一个jar执行
pom文件配置如下
    <dependencies>
        <dependency>
            <groupId>com.baidu.hugegraph</groupId>
            <artifactId>hugegraph-client</artifactId>
            <version>1.6.4</version>
        </dependency>
        
        <dependency>
            <groupId>org.apache.tinkerpop</groupId>
            <artifactId>gremlin-driver</artifactId>
            <version>3.3.3</version>
        </dependency>
        
        <dependency>
            <groupId>com.baidu.hugegraph</groupId>
            <artifactId>hugegraph-common</artifactId>
            <version>1.5.3</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.1</version>
                <configuration>
                    <source>8</source>
                    <target>8</target>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifest>
                            <mainClass>Test.SubGraph</mainClass>
                        </manifest>
                    </archive>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                </configuration>
                
                <executions>
                    <execution>
                        <id>make-assemble</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

**Comment by javeme** [comment]
@ychmc 请参考 #257 。这个问题也会在0.9版中允许打包成一个jar。
