### ISSUE TITLE
日期数据只支持"yyyy-MM-dd HH:mm:ss.SSS"这一种格式吗

### ISSUE THREAD

**Issue by 1315861791** [hugegraph/hugegraph#460]
日期数据只支持"yyyy-MM-dd HH:mm:ss.SSS"这一种格式吗？

**Comment by Linary** [comment]
目前支持三种格式的日期格式：
```
"yyyy-MM-dd",
"yyyy-MM-dd HH:mm:ss",
"yyyy-MM-dd HH:mm:ss.SSS"
```
可以查看DateUtil类的VALID_DFS结构

**Comment by 1315861791** [comment]
如果一个日期属性中已经存在一部分"yyyy-MM-dd HH:mm:ss.SSS"格式的数据再写入"yyyy-MM-dd"格式的数据时是否会报错。我这边遇到这个情况了，导致我以为只支持第三种格式
![image](https://user-images.githubusercontent.com/24642133/56272663-c51dd500-612d-11e9-983a-111506fc5986.png)

**Comment by Linary** [comment]
@1315861791 你用的是哪个版本？0.8是只支持yyyy-MM-dd HH:mm:ss.SSS的，master和即将发布的0.9是支持上述三种。

**Comment by 1315861791** [comment]
用的0.8，期待0.9
