### ISSUE TITLE
可否绕过server直接bulk生成HFile？

### ISSUE THREAD

**Issue by minilop** [hugegraph/hugegraph#466]
10台hbase节点。vertex有20亿左右，edge在13亿左右。数据导入速度较慢，后期目测一秒不到1万条。backend为hbase，请问可否跳过hugeserver，直接生成HFile，bulk到hbase。不知以下步骤是否可行？（没有IndexLabel，没有二级索引，关闭label index，没有SearchIndex，只根据primaryKey查询）

1. 通过api生成schema。
2. bulk vertex的HFile到hugegraph:graph_v。
3. bulk edge的HFile到hugegraph:graph_ie 和 hugegraph:graph_oe。
4. hugegraph:c是否为记录各个vertex和edge的总条数。是的话，计算最终的相关数据条数，插入hugegraph:c。

**Comment by javeme** [comment]
@minilop 上述提到的方法理论上是可以的，不过可能实现与操作起来比较麻烦。
事实上我们早期有尝试Cassandra以及RocksDB的bulkload功能，但效果均不怎么理想，而且会使流程变得非常复杂。
若实现的话，期待你的效果反馈，如果有什么问题欢迎交流探讨。
