### ISSUE TITLE
多线程导入数据时报错

### ISSUE THREAD

**Issue by 1315861791** [hugegraph/hugegraph#467]
![image](https://user-images.githubusercontent.com/24642133/56403930-4327cc00-6253-11e9-9a77-01cdd8958cc8.png)
麻烦问一下，这是什么情况，该如何避免

**Comment by suesunss** [comment]
看样子是 rest server 处理不过来请求了，可以尝试把 loader 的线程数调小一些试试

**Comment by 1315861791** [comment]
麻烦再问一下：线程数应该根据什么去设定这个参数啦？

**Comment by 1315861791** [comment]
我现在的并发数是5-25，后台用的3台hbase

**Comment by 1315861791** [comment]
com.baidu.hugegraph.exception.ServerException: The rest server is too busy to write
这个问题能通过调整hugegraph服务的参数来解决吗？

**Comment by suesunss** [comment]
参考 Loader 页面的参数：

https://hugegraph.github.io/hugegraph-doc/quickstart/hugegraph-loader.html

一般来讲 server 是单机的，所以应该能同时处理的线程等于 cpu 的核数。

**Comment by 1315861791** [comment]
我用javaAPI批量入库的，三元组的形式，每250条边+500个点启动一个写线程。
hugeClient.graph().addVertices(vertexList);//顶点批量写入hugegraph
hugeClient.graph().addEdges(edgeList);//批量写入边到hugegraph

**Comment by javeme** [comment]
@1315861791 请问server的CPU与内存是多大？也可尝试调大服务端的批量写线程数 `batch.max_write_ratio` ，具体可参考 #431
