### ISSUE TITLE
backend为hbase时，有分区吗 

### ISSUE THREAD

**Issue by minilop** [hugegraph/hugegraph#469]
backend为hbase，load vertex时，发现对hbase的write操作全部集中在一个region上，导致经常报RegionTooBusyException，而经常retry。

**Comment by javeme** [comment]
@minilop hugegraph使用的是hbase的默认分区策略。

请参考下面的方法（https://community.hortonworks.com/questions/37196/im-getting-regiontoobusyexception-when-trying-to-i.html）：
> Two major reasons for RegionTooBusyException
> 
> Failure to acquire region lock (look for " failed to get a lock in " in map task log)
> Region memstore is above limit and flushes can not keep up with load (look for "Above memstore limit")
> To mitigate 1. you can increase maximum busy wait timeout hbase.ipc.client.call.purge.timeout in ms (default is 120000) directly but do not forget to increase hbase.rpc.timeout accordingly (set it to the same value)
> 
> To mitigate 2. you can increase hbase.hregion.memstore.block.multiplier from default(4) to some higher value.


也可以根据数据的分布特点对 hbase 做更加均衡的预分区。
