### ISSUE TITLE
日期类型不能用between比较吗

### ISSUE THREAD

**Issue by 1315861791** [hugegraph/hugegraph#475]
![image](https://user-images.githubusercontent.com/24642133/56492562-c3ce1d00-651e-11e9-83bb-91f3b0b1952e.png)

**Comment by Linary** [comment]
可以的

1. 在 date 上创建 range 索引
2. 查询语句换成`g.E(xxx).has('开始时间', between('2019-01-13 xxx', '2019-01-15 yyy'))`

**Comment by 1315861791** [comment]
好的，我的索引类型建错了，谢谢。
