### ISSUE TITLE
HugeGraph-core 上传到 Maven 中心仓库？

### ISSUE THREAD

**Issue by suesunss** [hugegraph/hugegraph#477]
### Expected behavior 期望表现
HugeGraph-core 上传到 Maven 中心仓库，可通过 pom.xml 拉取到相关 jar 包。

### Actual behavior 实际表现
目前 Maven 中心仓库上 HugeGraph 的版本还处于 0.8.0 版本。

**Comment by zhoney** [comment]
@suesunss 各组件0.9.2版本jar包已上传。

**Comment by suesunss** [comment]
@zhoney Thanks!
