### ISSUE TITLE
使用mysql做后端的时候，出现中文乱码情况

### ISSUE THREAD

**Issue by aiyongyyy** [hugegraph/hugegraph#482]
写入Vertex的属性包含中文，再次查询Vertex后，中文出现乱码的情况。
mysql数据库查看过了编码是UTF8编码，但是值确实是乱码。如图所示。问一下这个情况怎么解决呢，谢谢了
![无标题](https://user-images.githubusercontent.com/1321464/56654760-72ab5e00-66c3-11e9-848f-e7860b3c723b.png)

**Comment by javeme** [comment]
@aiyongyyy 可能是导入的时候没有使用UTF-8导致的，请检查下读取文件的编码，如果是GBK的话需要指定 "charset": "GBK" [4.3 编写输入源映射文件](http://hugegraph.baidu.com/quickstart/hugegraph-loader.html)

**Comment by Codelone** [comment]
我也遇到了这个错误，但是我检查了文件的编码和struct.json里边写的都是UTF-8，但是还是乱码。

**Comment by javeme** [comment]
@Codelone 如果你的数据文件是中文编码（比如GBK），那么需要在struct.json指定为`"charset": "GBK"`（**注意这里不是写UTF-8**）。

**Comment by Codelone** [comment]
> @Codelone如果你的数据文件是中文编码（比如GBK），那么需要在struct.json指定为`"charset": "GBK"`（**注意这里不是写UTF-8**）。

我已经尝试将文件改为GBK然后struct.json也指定为GBK，但是中文依然是问号，我指定UTF-8编码，文件是GBK的时候，导入的数据是乱码的，但是不是问号。我猜测应该不是编码不一致的问题。

**Comment by javeme** [comment]
@Codelone 可以在studio中验证一下hugegraph-server对中文支持是否正确：
```java
graph.addVertex(T.label, "person", "name", "张三（中文）", "age", 29, "city", "Beijing")
```
理论上hugegraph-server编码是完全支持中文的。解决编码问题最简单的办法是把控制台（包括：启动server服务、启动loader、展示结果数据等）、数据文件、程序读写等均统一为UTF-8编码。

**Comment by scxj** [comment]
@javeme HugeGraph-Server使用0.9.2，数据存储使用mysql，数据库编码是支持中文，使用studio插入数据，数据库中文乱码，使用内存则不会出现该问题。想知道jdbc连接的时候，配置文件中如何配置编码集，尝试在url后面添加编码，但是不可行。谢谢了。

**Comment by Linary** [comment]
@scxj 经过检查和测试，发现代码中确实是少了JDBC的编码参数，在加上该参数后，使用 mysql 自带的client 和 navicat 都能正确显示中文。如图所示：
![image](https://user-images.githubusercontent.com/9151831/58612553-8dd24480-82e5-11e9-8ba4-9326a897ba4c.png)
![image](https://user-images.githubusercontent.com/9151831/58612573-9fb3e780-82e5-11e9-9529-70d9f3cc28b2.png)
我的 navicat 的连接的高级设置中`Encoding`选择的是`AUTO`

**Comment by Linary** [comment]
refer https://github.com/hugegraph/hugegraph/pull/543
