### ISSUE TITLE
如何在子图上实现社区发现算法啦？

### ISSUE THREAD

**Issue by 1315861791** [hugegraph/hugegraph#486]
想要在hugegraph的子图上做社区发现和骨干成员发现等算法，查了traverser API没找到相关的接口，自己做的话哪位大神能指点个思路吗？LPA和Louvain任意一种就能满足我的需求了。

**Comment by 1315861791** [comment]
已解决

**Comment by xudaddd** [comment]
哇塞怎么解决的？
