### ISSUE TITLE
rings接口文档中说明的选填项，在接口中怎么是必填项，升级后发生变化了吗

### ISSUE THREAD

**Issue by 1315861791** [hugegraph/hugegraph#487]
```
public List<Path> rings(Object sourceId, Direction direction, String label, int depth, long degree, long capacity, long limit) {
        return this.ringsAPI.get(sourceId, direction, label, depth, degree, capacity, limit);
    }
```
![image](https://user-images.githubusercontent.com/24642133/56859664-b0a8ca80-69c0-11e9-8893-98fb06158156.png)

**Comment by zhoney** [comment]
@1315861791 

- 接口文档是对RESTful API的说明，是API的规范
- client是对RESTful API的封装
    - RESTful API的所有参数都可以通过client来指定
    - 但client并不一定都是按照“必填项”和“选填项”的参数方式实现的

使用client时根据需要填写一下“选填项”参数即可。

**Comment by 1315861791** [comment]
您可能误解了，我想表达的是，文档中rings，rays这两个接口的label是选填项，但client中是必填项。
另外想问问可不可以在检测环路的时候在边上添加过滤条件。在反洗钱的场景中这是很有必要的，不添加条件的环路意义不大
