### ISSUE TITLE
请教下neighbor rank 算法的原理是跟KNN类似吗？

### ISSUE THREAD

**Issue by 1315861791** [hugegraph/hugegraph#489]
如题，想知道neighbor rank 的原理

**Comment by 1315861791** [comment]
neighborRank和personalRank在client中传参有些复杂。

**Comment by Linary** [comment]
@1315861791 neighbor rank 与 knn 原理上并不相同，甚至可以说毫无关系，但在结果上（大小关系）有些相似。一般情况下都是距离源点近的权重高，距离远的权重低，但是也可能存在某一个距离远的顶点由于上一层有很多顶点指向它（给他贡献），导致他的权重比上一层的还高的情况。neighbor rank 的文档可以参考：https://github.com/hugegraph/hugegraph-doc/pull/28，目前参数确实较多，但大部分都有默认值，我们后续会优化。

**Comment by 1315861791** [comment]
感谢解答。
![image](https://user-images.githubusercontent.com/24642133/57204889-4067fd80-6fed-11e9-95a9-08aaed99562d.png)
抱歉，第二个问题我可能表达的太含蓄了，这两个API在client中传入的是一个对象，但不知道这个对象怎么构造

**Comment by Linary** [comment]
@1315861791 用`NeighborRankAPI.Request.Builder`构造，你可以参考源码中test包下的`com.baidu.hugegraph.api.NeighborRankApiTest`中的testXXX()，里面有构造request的示例。

**Comment by 1315861791** [comment]
好的，谢谢。我下载源码去。

**Comment by 1315861791** [comment]
![image](https://user-images.githubusercontent.com/24642133/57205651-9d19e700-6ff2-11e9-8841-b6348978f2fe.png)
再问一下：com.baidu.hugegraph.api.NeighborRankApiTest这个类我在源码中没找到啊。
![image](https://user-images.githubusercontent.com/24642133/57205725-0b5ea980-6ff3-11e9-8db3-ed59e51c4e71.png)

**Comment by Linary** [comment]
@1315861791 抱歉，我没说清楚，这个类是在 hugegraph-client 项目中的 test 包下。

**Comment by 1315861791** [comment]
谢谢，是我太蠢找错地方了
