### ISSUE TITLE
HugeGraph-Studio（0.7.0）启动失败

### ISSUE THREAD

**Issue by Blessness** [hugegraph/hugegraph#49]
配置项：
![image](https://user-images.githubusercontent.com/17780229/45155729-8a0a0980-b20e-11e8-9c07-e98bf6d0fd4b.png)

但执行启动命令后，日志如下：
------------------------------------------------------------------------------------------------------------------

14:33:24.260 [main] DEBUG com.baidu.hugegraph.config.OptionSpace ID:  TS: - Registered options for OptionHolder: StudioServerOptions
14:33:24.298 [main] WARN  com.baidu.hugegraph.config.HugeConfig ID:  TS: - The config option 'graph.server.host' is redundant, please ensure it has been registered
14:33:24.298 [main] WARN  com.baidu.hugegraph.config.HugeConfig ID:  TS: - The config option 'graph.server.port' is redundant, please ensure it has been registered
14:33:24.298 [main] WARN  com.baidu.hugegraph.config.HugeConfig ID:  TS: - The config option 'graph.name' is redundant, please ensure it has been registered
14:33:24.298 [main] WARN  com.baidu.hugegraph.config.HugeConfig ID:  TS: - The config option 'data.base_directory' is redundant, please ensure it has been registered
14:33:24.298 [main] WARN  com.baidu.hugegraph.config.HugeConfig ID:  TS: - The config option 'show.limit.data' is redundant, please ensure it has been registered
14:33:24.298 [main] WARN  com.baidu.hugegraph.config.HugeConfig ID:  TS: - The config option 'show.limit.edge.total' is redundant, please ensure it has been registered
14:33:24.299 [main] WARN  com.baidu.hugegraph.config.HugeConfig ID:  TS: - The config option 'show.limit.edge.increment' is redundant, please ensure it has been registered
14:33:24.299 [main] WARN  com.baidu.hugegraph.config.HugeConfig ID:  TS: - The config option 'gremlin.limit_suffix' is redundant, please ensure it has been registered
14:33:24.299 [main] WARN  com.baidu.hugegraph.config.HugeConfig ID:  TS: - The config option 'vertex.vis.font.color' is redundant, please ensure it has been registered
14:33:24.299 [main] WARN  com.baidu.hugegraph.config.HugeConfig ID:  TS: - The config option 'vertex.vis.font.size' is redundant, please ensure it has been registered
14:33:24.299 [main] WARN  com.baidu.hugegraph.config.HugeConfig ID:  TS: - The config option 'vertex.vis.size' is redundant, please ensure it has been registered
14:33:24.299 [main] WARN  com.baidu.hugegraph.config.HugeConfig ID:  TS: - The config option 'vertex.vis.scaling.min' is redundant, please ensure it has been registered
14:33:24.299 [main] WARN  com.baidu.hugegraph.config.HugeConfig ID:  TS: - The config option 'vertex.vis.scaling.max' is redundant, please ensure it has been registered
14:33:24.299 [main] WARN  com.baidu.hugegraph.config.HugeConfig ID:  TS: - The config option 'vertex.vis.shape' is redundant, please ensure it has been registered
14:33:24.300 [main] WARN  com.baidu.hugegraph.config.HugeConfig ID:  TS: - The config option 'vertex.vis.color' is redundant, please ensure it has been registered
14:33:24.300 [main] WARN  com.baidu.hugegraph.config.HugeConfig ID:  TS: - The config option 'edge.vis.color.default' is redundant, please ensure it has been registered
14:33:24.300 [main] WARN  com.baidu.hugegraph.config.HugeConfig ID:  TS: - The config option 'edge.vis.color.hover' is redundant, please ensure it has been registered
14:33:24.300 [main] WARN  com.baidu.hugegraph.config.HugeConfig ID:  TS: - The config option 'edge.vis.color.highlight' is redundant, please ensure it has been registered
14:33:24.300 [main] WARN  com.baidu.hugegraph.config.HugeConfig ID:  TS: - The config option 'edge.vis.font.color' is redundant, please ensure it has been registered
14:33:24.300 [main] WARN  com.baidu.hugegraph.config.HugeConfig ID:  TS: - The config option 'edge.vis.font.size' is redundant, please ensure it has been registered
Sep 06, 2018 2:33:24 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-nio-192.168.3.31-8088"]
Sep 06, 2018 2:33:24 PM org.apache.tomcat.util.net.NioSelectorPool getSharedSelector
INFO: Using a shared selector for servlet write/read
Sep 06, 2018 2:33:24 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Tomcat
Sep 06, 2018 2:33:24 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/8.5.2
Sep 06, 2018 2:33:24 PM org.apache.catalina.startup.ContextConfig getDefaultWebXmlFragment
INFO: No global web.xml found
Sep 06, 2018 2:33:26 PM org.apache.jasper.servlet.TldScanner scanJars
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
Sep 06, 2018 2:33:29 PM org.apache.jasper.servlet.TldScanner scanJars
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
Sep 06, 2018 2:33:29 PM org.apache.catalina.core.ApplicationContext log
INFO: Spring WebApplicationInitializers detected on classpath: [org.glassfish.jersey.server.spring.SpringWebApplicationInitializer@64d936fe]
Sep 06, 2018 2:33:29 PM org.apache.catalina.core.ApplicationContext log
INFO: Initializing Spring root WebApplicationContext
Sep 06, 2018 2:33:29 PM org.springframework.web.context.ContextLoader initWebApplicationContext
INFO: Root WebApplicationContext: initialization started
Sep 06, 2018 2:33:29 PM org.springframework.context.support.AbstractApplicationContext prepareRefresh
INFO: Refreshing Root WebApplicationContext: startup date [Thu Sep 06 14:33:29 CST 2018]; root of context hierarchy
Sep 06, 2018 2:33:29 PM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFO: Loading XML bean definitions from class path resource [applicationContext.xml]
Sep 06, 2018 2:33:30 PM org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor <init>
INFO: JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/root/hugegraph_studio/hugegraph-studio-0.7.0/lib/log4j-slf4j-impl-2.8.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/root/hugegraph_studio/hugegraph-studio-0.7.0/bin/tomcat.8088/webapps/api/WEB-INF/lib/log4j-slf4j-impl-2.8.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
14:33:30.702 [192.168.3.31-startStop-1] DEBUG com.baidu.hugegraph.config.OptionSpace ID:  TS: - Registered options for OptionHolder: StudioApiOptions
14:33:30.736 [192.168.3.31-startStop-1] WARN  com.baidu.hugegraph.config.HugeConfig ID:  TS: - The config option 'studio.server.port' is redundant, please ensure it has been registered
14:33:30.737 [192.168.3.31-startStop-1] WARN  com.baidu.hugegraph.config.HugeConfig ID:  TS: - The config option 'studio.server.host' is redundant, please ensure it has been registered
14:33:30.737 [192.168.3.31-startStop-1] WARN  com.baidu.hugegraph.config.HugeConfig ID:  TS: - The config option 'studio.server.ui' is redundant, please ensure it has been registered
14:33:30.737 [192.168.3.31-startStop-1] WARN  com.baidu.hugegraph.config.HugeConfig ID:  TS: - The config option 'studio.server.api.war' is redundant, please ensure it has been registered
14:33:30.738 [192.168.3.31-startStop-1] INFO  com.baidu.hugegraph.studio.board.serializer.BoardSerializer ID:  TS: - The board file path is: /root/.hugegraph-studio/board
Sep 06, 2018 2:33:30 PM org.springframework.web.context.ContextLoader initWebApplicationContext
INFO: Root WebApplicationContext: initialization completed in 1023 ms
Sep 06, 2018 2:33:31 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler [http-nio-192.168.3.31-8088]
14:33:31.337 [main] INFO  com.baidu.hugegraph.studio.HugeGraphStudio ID:  TS: - HugeGraphStudio is now running on: http://192.168.3.31:8088

--------------------------------------------------------------------------------------------------------------

执行 lsof -i:8088 发现此端口并没有被服务所拥有。

**Comment by Blessness** [comment]
访问不了，端口都没被使用

**Comment by Linary** [comment]
访问 http://192.168.3.31:8088  提示的是什么

**Comment by Blessness** [comment]
jps没有HugeGraphStudio进程，只有HugeGraphServer。

访问 http://192.168.3.31:8088 提示 “无法访问此网站“

----------------------------------------------------------启动日志
17:58:09.987 [main] DEBUG com.baidu.hugegraph.config.OptionSpace ID:  TS: - Registered options for OptionHolder: StudioServerOptions
17:58:10.022 [main] WARN  com.baidu.hugegraph.config.HugeConfig ID:  TS: - The config option 'graph.server.host' is redundant, please ensure it has been registered
17:58:10.022 [main] WARN  com.baidu.hugegraph.config.HugeConfig ID:  TS: - The config option 'graph.server.port' is redundant, please ensure it has been registered
17:58:10.022 [main] WARN  com.baidu.hugegraph.config.HugeConfig ID:  TS: - The config option 'graph.name' is redundant, please ensure it has been registered
17:58:10.022 [main] WARN  com.baidu.hugegraph.config.HugeConfig ID:  TS: - The config option 'data.base_directory' is redundant, please ensure it has been registered
17:58:10.022 [main] WARN  com.baidu.hugegraph.config.HugeConfig ID:  TS: - The config option 'show.limit.data' is redundant, please ensure it has been registered
17:58:10.023 [main] WARN  com.baidu.hugegraph.config.HugeConfig ID:  TS: - The config option 'show.limit.edge.total' is redundant, please ensure it has been registered
17:58:10.023 [main] WARN  com.baidu.hugegraph.config.HugeConfig ID:  TS: - The config option 'show.limit.edge.increment' is redundant, please ensure it has been registered
17:58:10.023 [main] WARN  com.baidu.hugegraph.config.HugeConfig ID:  TS: - The config option 'gremlin.limit_suffix' is redundant, please ensure it has been registered
17:58:10.023 [main] WARN  com.baidu.hugegraph.config.HugeConfig ID:  TS: - The config option 'vertex.vis.font.color' is redundant, please ensure it has been registered
17:58:10.023 [main] WARN  com.baidu.hugegraph.config.HugeConfig ID:  TS: - The config option 'vertex.vis.font.size' is redundant, please ensure it has been registered
17:58:10.023 [main] WARN  com.baidu.hugegraph.config.HugeConfig ID:  TS: - The config option 'vertex.vis.size' is redundant, please ensure it has been registered
17:58:10.023 [main] WARN  com.baidu.hugegraph.config.HugeConfig ID:  TS: - The config option 'vertex.vis.scaling.min' is redundant, please ensure it has been registered
17:58:10.023 [main] WARN  com.baidu.hugegraph.config.HugeConfig ID:  TS: - The config option 'vertex.vis.scaling.max' is redundant, please ensure it has been registered
17:58:10.023 [main] WARN  com.baidu.hugegraph.config.HugeConfig ID:  TS: - The config option 'vertex.vis.shape' is redundant, please ensure it has been registered
17:58:10.023 [main] WARN  com.baidu.hugegraph.config.HugeConfig ID:  TS: - The config option 'vertex.vis.color' is redundant, please ensure it has been registered
17:58:10.023 [main] WARN  com.baidu.hugegraph.config.HugeConfig ID:  TS: - The config option 'edge.vis.color.default' is redundant, please ensure it has been registered
17:58:10.024 [main] WARN  com.baidu.hugegraph.config.HugeConfig ID:  TS: - The config option 'edge.vis.color.hover' is redundant, please ensure it has been registered
17:58:10.024 [main] WARN  com.baidu.hugegraph.config.HugeConfig ID:  TS: - The config option 'edge.vis.color.highlight' is redundant, please ensure it has been registered
17:58:10.024 [main] WARN  com.baidu.hugegraph.config.HugeConfig ID:  TS: - The config option 'edge.vis.font.color' is redundant, please ensure it has been registered
17:58:10.024 [main] WARN  com.baidu.hugegraph.config.HugeConfig ID:  TS: - The config option 'edge.vis.font.size' is redundant, please ensure it has been registered
Sep 07, 2018 5:58:10 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-nio-192.168.3.31-8088"]
Sep 07, 2018 5:58:10 PM org.apache.tomcat.util.net.NioSelectorPool getSharedSelector
INFO: Using a shared selector for servlet write/read
Sep 07, 2018 5:58:10 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Tomcat
Sep 07, 2018 5:58:10 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/8.5.2
Sep 07, 2018 5:58:10 PM org.apache.catalina.startup.ContextConfig getDefaultWebXmlFragment
INFO: No global web.xml found
Sep 07, 2018 5:58:12 PM org.apache.jasper.servlet.TldScanner scanJars
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
Sep 07, 2018 5:58:14 PM org.apache.jasper.servlet.TldScanner scanJars
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
Sep 07, 2018 5:58:14 PM org.apache.catalina.core.ApplicationContext log
INFO: Spring WebApplicationInitializers detected on classpath: [org.glassfish.jersey.server.spring.SpringWebApplicationInitializer@153bfa19]
Sep 07, 2018 5:58:15 PM org.apache.catalina.core.ApplicationContext log
INFO: Initializing Spring root WebApplicationContext
Sep 07, 2018 5:58:15 PM org.springframework.web.context.ContextLoader initWebApplicationContext
INFO: Root WebApplicationContext: initialization started
Sep 07, 2018 5:58:15 PM org.springframework.context.support.AbstractApplicationContext prepareRefresh
INFO: Refreshing Root WebApplicationContext: startup date [Fri Sep 07 17:58:15 CST 2018]; root of context hierarchy
Sep 07, 2018 5:58:15 PM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFO: Loading XML bean definitions from class path resource [applicationContext.xml]
Sep 07, 2018 5:58:15 PM org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor <init>
INFO: JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/root/hugegraph_studio/hugegraph-studio-0.7.0/lib/log4j-slf4j-impl-2.8.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/root/hugegraph_studio/hugegraph-studio-0.7.0/bin/tomcat.8088/webapps/api/WEB-INF/lib/log4j-slf4j-impl-2.8.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
17:58:16.014 [192.168.3.31-startStop-1] DEBUG com.baidu.hugegraph.config.OptionSpace ID:  TS: - Registered options for OptionHolder: StudioApiOptions
17:58:16.050 [192.168.3.31-startStop-1] WARN  com.baidu.hugegraph.config.HugeConfig ID:  TS: - The config option 'studio.server.port' is redundant, please ensure it has been registered
17:58:16.051 [192.168.3.31-startStop-1] WARN  com.baidu.hugegraph.config.HugeConfig ID:  TS: - The config option 'studio.server.host' is redundant, please ensure it has been registered
17:58:16.051 [192.168.3.31-startStop-1] WARN  com.baidu.hugegraph.config.HugeConfig ID:  TS: - The config option 'studio.server.ui' is redundant, please ensure it has been registered
17:58:16.051 [192.168.3.31-startStop-1] WARN  com.baidu.hugegraph.config.HugeConfig ID:  TS: - The config option 'studio.server.api.war' is redundant, please ensure it has been registered
17:58:16.052 [192.168.3.31-startStop-1] INFO  com.baidu.hugegraph.studio.board.serializer.BoardSerializer ID:  TS: - The board file path is: /root/.hugegraph-studio/board
Sep 07, 2018 5:58:16 PM org.springframework.web.context.ContextLoader initWebApplicationContext
INFO: Root WebApplicationContext: initialization completed in 990 ms
Sep 07, 2018 5:58:16 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler [http-nio-192.168.3.31-8088]
17:58:16.666 [main] INFO  com.baidu.hugegraph.studio.HugeGraphStudio ID:  TS: - HugeGraphStudio is now running on: http://192.168.3.31:8088

**Comment by Linary** [comment]
Jps都没有HugeGraphStudio的话说明没有启动成功。Studio的启动`bin/hugegraph-studio.sh`是一个前台进程，跟Server的不一样，你应该没有在启动后又ctrl+c吧

**Comment by Blessness** [comment]
![image](https://user-images.githubusercontent.com/17780229/45275443-70f3a800-b4ef-11e8-9d53-54655167fd1a.png)

之前确实ctrl+c了，这个 bin/hugegraph-studio.sh 需要结合nohub一起使用？
然后界面进去后，与教程描述的不一样....
没有setting按钮？
