### ISSUE TITLE
页面没有返回

### ISSUE THREAD

**Issue by suqingbo** [hugegraph/hugegraph#494]
### Expected behavior 期望表现
{type something here...}
![图片](https://user-images.githubusercontent.com/26301885/56951127-9bbb6b00-6b69-11e9-9831-6608fd433a35.png)

### Actual behavior 实际表现
{type something here...}
![图片](https://user-images.githubusercontent.com/26301885/56951149-a6760000-6b69-11e9-8b39-3f0178f10b1f.png)
变成灰色，没有任何反应

### Steps to reproduce the problem 复现步骤
1. 按照官方教程安装好以后，在另外一台机器上面通过浏览器访问
2. 输入1 + 1，期望输出2.可是结果页面没有任何反应
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by Linary** [comment]
@suqingbo 之前发布的 hugegraph-studio 确实存在 BUG，上周已替换，请再下载新的 release 包试试。

**Comment by Linary** [comment]
refer https://github.com/hugegraph/hugegraph-studio/issues/18
