### ISSUE TITLE
希望升级几个组件

### ISSUE THREAD

**Issue by cmdares** [hugegraph/hugegraph#495]
希望升级几个关键组件
1.希望把thinkerpop升级到apache官方的最新版本，阅读了相关的更新功能列表，发现一些能力的提升是有必要的。
2.希望能够支持rocksdb为6.x，同样后端数据库的一些高可用型和性能的提升，如锁、压缩等造成的等待。
感谢。

**Comment by javeme** [comment]
@cmdares 感谢反馈，我们会尽早规划thinkerpop的升级，rocksdb的版本在刚刚发布的0.9中已经升级了一次，rocksdb 6.0版本刚刚发布不久，hugegraph对其依赖版本可能需要一段时间之后才会进行升级。
hugegraph 0.9依赖的thinkerpop版本是3.2.5（较老，2017年6月），rocksdb版本是5.17.2（较新，2018年11月）。
