### ISSUE TITLE
请问什么情况下会rebuild index

### ISSUE THREAD

**Issue by ghost** [hugegraph/hugegraph#496]
今天查数据的时候显示 Lock [hugegraph_il_delete:2] is locked by other operation,跟了代码发现是rebuildindex线程占了锁，但我并没有做这个操作，请问什么情况下它会自动rebuild？

**Comment by zhoney** [comment]
@oushu1liwenhui1 重建索引的情况包括：

1. 显式重建，对VertexLabel，EdgeLabel和IndexLabel进行显式重建
2. 隐式重建，对已经存在数据（顶点或者边）的VertexLabel和EdgeLabel创建索引时发生

**Comment by oushu1liwenhui1** [comment]
> @oushu1liwenhui1 重建索引的情况包括：
> 
> 1. 显式重建，对VertexLabel，EdgeLabel和IndexLabel进行显式重建
> 2. 隐式重建，对已经存在数据（顶点或者边）的VertexLabel和EdgeLabel创建索引时发生

但是重建的时候貌似有问题，cassandra batchsize超过65535就会报错，那么是不是节点数超过65535就无法重建了？

**Comment by oushu1liwenhui1** [comment]
还有个问题，刚重启了server以后，发现其立刻进行了rebuild index，请问这是什么原理？
