### ISSUE TITLE
hugeClient.traverser().rings()接口如果能过滤掉来回重复的路径就好了

### ISSUE THREAD

**Issue by 1315861791** [hugegraph/hugegraph#497]
[
  {
    "labels": [],
    "objects": [
      "1",
      "0",
      "1"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "155",
      "1"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "2",
      "1"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "233",
      "1"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "3",
      "1"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "234",
      "1"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "4",
      "1"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "235",
      "1"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "3943",
      "1"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "185",
      "1"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "233",
      "102284",
      "233"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "155",
      "107371",
      "155"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "234",
      "1057",
      "234"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "4",
      "1056",
      "4"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "235",
      "10230",
      "235"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "155",
      "101587",
      "155"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "155",
      "101588",
      "155"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "185",
      "100337",
      "185"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "185",
      "100711",
      "185"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "0",
      "10",
      "0"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "185",
      "102590",
      "185"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "233",
      "106771",
      "233"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "234",
      "106771",
      "234"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "235",
      "106771",
      "235"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "234",
      "102394",
      "234"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "233",
      "102396",
      "233"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "155",
      "102395",
      "155"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "235",
      "105324",
      "235"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "4",
      "102376",
      "4"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "4",
      "1033",
      "4"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "185",
      "1055",
      "185"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "4",
      "1032",
      "4"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "4",
      "10228",
      "4"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "155",
      "10228",
      "155"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "2",
      "0",
      "2"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "3",
      "0",
      "3"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "4",
      "0",
      "4"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "2",
      "0",
      "1"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "3",
      "0",
      "1"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "4",
      "0",
      "1"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "185",
      "101538",
      "185"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "0",
      "2",
      "0"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "0",
      "2",
      "1"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "0",
      "3",
      "0"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "0",
      "3",
      "1"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "0",
      "4",
      "0"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "0",
      "4",
      "1"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "0",
      "5",
      "0"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "0",
      "6",
      "0"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "0",
      "7",
      "0"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "0",
      "8",
      "0"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "0",
      "9",
      "0"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "185",
      "105339",
      "185"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "155",
      "10266",
      "155"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "235",
      "10266",
      "235"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "155",
      "102500",
      "155"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "155",
      "102502",
      "155"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "185",
      "101635",
      "185"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "185",
      "101636",
      "185"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "155",
      "10228",
      "89",
      "10228"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "4",
      "10228",
      "89",
      "10228"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "235",
      "10230",
      "89",
      "10230"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "155",
      "10266",
      "89",
      "10266"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "235",
      "10266",
      "89",
      "10266"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "155",
      "101587",
      "89",
      "101587"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "155",
      "101588",
      "89",
      "101588"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "234",
      "102394",
      "89",
      "102394"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "155",
      "102500",
      "89",
      "102500"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "155",
      "102502",
      "89",
      "102502"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "235",
      "105324",
      "89",
      "105324"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "155",
      "107371",
      "89",
      "107371"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "155",
      "101587",
      "26719",
      "101587"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "234",
      "102394",
      "14056",
      "102394"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "155",
      "102395",
      "14056",
      "102395"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "233",
      "106771",
      "7446",
      "106771"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "234",
      "106771",
      "7446",
      "106771"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "235",
      "106771",
      "7446",
      "106771"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "234",
      "102394",
      "14055",
      "102394"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "155",
      "102395",
      "14055",
      "102395"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "0",
      "8",
      "1061",
      "8"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "234",
      "1057",
      "1061",
      "1057"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "0",
      "8",
      "1060",
      "8"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "4",
      "1056",
      "1060",
      "1056"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "4",
      "1056",
      "1060",
      "1056"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "234",
      "1057",
      "1060",
      "1057"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "234",
      "1057",
      "1060",
      "1057"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "4",
      "1056",
      "1060",
      "1056"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "4",
      "1056",
      "1060",
      "1056"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "234",
      "1057",
      "1060",
      "1057"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "234",
      "1057",
      "1060",
      "1057"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "185",
      "102590",
      "170729",
      "102590"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "4",
      "102376",
      "143740",
      "102376"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "234",
      "106771",
      "233",
      "1"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "235",
      "106771",
      "233",
      "1"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "234",
      "106771",
      "233",
      "106771"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "235",
      "106771",
      "233",
      "106771"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "0",
      "10",
      "355",
      "10"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "4",
      "102376",
      "355",
      "102376"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "233",
      "106771",
      "234",
      "1"
    ],
    "crosspoint": null
  },
  {
    "labels": [],
    "objects": [
      "1",
      "235",
      "106771",
      "234",
      "1"
    ],
    "crosspoint": null
  }
]

**Comment by zhoney** [comment]
@1315861791 `rings`是查找从一个顶点出发可以到达的环路。

“来回重复”的路径也是环路的一种。可以通过限制`direction`的方式过滤掉部分这种同一条边来回震荡的情况。

另外，要查询从同一个顶点出发的无环路径，可以用`rays`

**Comment by 1315861791** [comment]
恩恩，已经解决掉了，所以就关闭了。谢谢您的赖心解答！
还有个比较头疼的问题：怎么在图上做社区发现算法？不想用先把数据查出来在外部计算的方式。还望不吝赐教，感激不尽！
