### ISSUE TITLE
hugegraph在服务器上运行时间久了比较吃内存

### ISSUE THREAD

**Issue by 1315861791** [hugegraph/hugegraph#499]
运行hugegraph服务的机器过几个月就会发现内存吃紧的情况，
通过echo 3 > /proc/sys/vm/drop_caches命令清理缓存效果不明显，
重启hugegraph后会空出1/3的内存来。
想了解下hugegraph的缓存及清理机制

**Comment by oushu1liwenhui1** [comment]
据我观察，缓存有个上限值，使用中会保持在这个上限，并不会清0。

**Comment by 1315861791** [comment]
有上限就好，就担心把服务器上的内存都吃完了。谢谢文辉

**Comment by javeme** [comment]
@1315861791 可以调整配置[cache_capacity](https://hugegraph.github.io/hugegraph-doc/config/config-option.html)以调节缓存上限

**Comment by 1315861791** [comment]
@javeme 好的，谢谢

**Comment by RustRw** [comment]
这个缓存貌似设置不当经常会出问题哦, 我导入数据的时候也出了问题, 频繁fullgc. 这里缓存是否可以考虑自动优化一下呢? 比如 控制在不容易触发fullgc的水平.
