### ISSUE TITLE
执行demo报错 : The name of property key can't be null

### ISSUE THREAD

**Issue by Weaving-Zim** [hugegraph/hugegraph#5]
本地启动了hugegraph使用下面链接的demo执行 , 新建schema时报错 :  
https://hugegraph.github.io/hugegraph-doc//quickstart/hugegraph-client.html
```java
schema.propertyKey("name").asText().ifNotExist().create();
```
```
Caused by: com.baidu.hugegraph.exception.ServerException: The name of property key can't be null
```
逐一排查项目依赖 , 发现去掉对fastjson的依赖 , 或强制指定fastjson的依赖为1.1.x , 可以解决此问题 ;

我使用的hugegraph版本:
client : 1.5.8
server : 0.7.4

复现此问题的方法 : 
在上面demo项目里面加上对 fastjson 1.2.x 的依赖 : com.alibaba:fastjson:1.2.44

**Comment by 472732787** [comment]
有用，  此外 和jackson-databind 也有冲突（具体版本= 没测试） 项目中去掉该依赖 加入  jackson-annotations（2.10.2） 问题解决

**Comment by Ckuangf** [comment]
fastjson的冲突是因为1.2.36版本以上 实现了Jersey 的AutoDiscoverable  导致的，在工程启动类中把 FastJsonAutoDiscoverable的autoDiscover设置为false可以解决高版本fastjson冲突问题，

**Comment by javeme** [comment]
如果更换了`fastjson`版本依然有问题，请尝试通过命令`mvn dependency:tree`查看具体冲突版本，然后尝试找到一个可兼容的中间版本。

**Comment by dongma** [comment]
> fastjson的冲突是因为1.2.36版本以上 实现了Jersey 的AutoDiscoverable 导致的，在工程启动类中把 FastJsonAutoDiscoverable的autoDiscover设置为false可以解决高版本fastjson冲突问题，


```java
package com.alibaba.fastjson.support.jaxrs;

import jakarta.ws.rs.core.FeatureContext;
import org.glassfish.jersey.internal.spi.AutoDiscoverable;

/**
 * @Title: FastJsonAutoDiscoverable
 * @Description: fastjson使用SPI在jvm中加载class,高版本与hugegraph结合使用时，并不存在javax.ws的包，
 * 	重写内容，编译后替换classpath中fastjson的同名class文件
 */
public class FastJsonAutoDiscoverable implements AutoDiscoverable {

    public static final String FASTJSON_AUTO_DISCOVERABLE = "fastjson.auto.discoverable";

    public volatile static boolean autoDiscover = true;

    static {
        try {
            autoDiscover = Boolean.parseBoolean(
                    System.getProperty(FASTJSON_AUTO_DISCOVERABLE, String.valueOf(autoDiscover)));
        } catch (Throwable ex) {
            //skip
        }
    }

    public void configure(final FeatureContext context) {

    }

}
```
