### ISSUE TITLE
Customized Paths例子问题

### ISSUE THREAD

**Issue by czhcc** [hugegraph/hugegraph#501]
请问，Customized Paths例子中，最后“张艺谋”应该是点数据吧，这个要怎么放到路径的条件里呢？

**Comment by zhoney** [comment]
@czhcc 这个是写的例子不对。customized paths支持的过滤包括：
1. 起始顶点的条件过滤和label过滤
2. 中间经过的边的条件过滤和label过滤

改为”看过张艺谋所导演的电影的用户所关注的大V的路径“。

感谢反馈！
