### ISSUE TITLE
技术交流群与管理员无法添加

### ISSUE THREAD

**Issue by wanyouxian** [hugegraph/hugegraph#505]
我尝试多次添加管理员，期望能加入技术群，但是管理员均没有响应，请问还有其他渠道加入吗？

**Comment by javeme** [comment]
@wanyouxian 请问是关注微信公众号“HugeGraph”后按照提示添加的管理员微信，然后没有响应吗？我问下情况给你反馈

**Comment by cavities** [comment]
没反馈

**Comment by imbajin** [comment]
> 没反馈

同学你好, 你是关注公众号之后申请加群的么? 如果没响应可以回复 id (后续可删) 我们确认一下, 多谢

**Comment by cavities** [comment]
申请二维码已经过期
----- 原始邮件 -----
发件人：imbajin ***@***.***>
收件人：hugegraph/hugegraph ***@***.***>
抄送人：cavities ***@***.***>,  Comment ***@***.***>
主题：Re:_[hugegraph/hugegraph]_技术交流群与管理员无法添加_(#505)
日期：2021年07月12日 22点35分





没反馈



同学你好, 你是关注公众号之后申请加群的么? 如果没响应可以回复 id (后续可删) 我们确认一下, 多谢



&mdash;

**Comment by imbajin** [comment]
@cavities 不好意思, 你可以发一下你的 wechatID 给我的邮箱或者直接回复 (之后 delete) 我拉一下你
