### ISSUE TITLE
hugegraph配置完，studio ui可以查询，但hugegraph本身的gremlin-console无法查询

### ISSUE THREAD

**Issue by WilliamShen2019** [hugegraph/hugegraph#507]
利用loader成功导入数据，且hugegraph-studio成功查询结果，依据文档修改配置后，用hugegraph集成的gremlin-console查询，未成功

以下是我的配置：
gremlin-driver-settings.yaml
hosts:[0.0.0.0]
port:8190

rest-server.properties
restserverurl=http://0.0.0.0:8096
#gremlinserverurl=http://0.0.0.0:8190
graphs=[peopleAndSoft:conf/peopleAndSoft.properties]

gremlin-server.yaml
graphs:{peopleAndSoft:conf/peopleAndSoft.properties}

remote.yaml
hosts:[0.0.0.0] 
port:8190

remote-objects.yaml
hosts:[0.0.0.0] 
port:8190

以上配置后，studio可以正常查询;

依据官方文档改了配置文件：
gremlin-server.yaml：
channelizer: org.apache.tinkerpop.gremlin.server.channel.WebSocketChannelizer

rest-server.properties
restserverurl=http://0.0.0.0:8096
gremlinserverurl=http://0.0.0.0:8190
graphs=[peopleAndSoft:conf/peopleAndSoft.properties]

使用gremlin-console也可以通过remote.yaml连接到库中,返回如下日志
gremlin> :remote connect tinkerpop.server conf/remote.yaml
2018-01-15 15:30:31 11538 [main] [INFO ] org.apache.tinkerpop.gremlin.driver.ConnectionPool [] - Opening connection pool on Host{address=0.0.0.0/0.0.0.0:8190, hostUri=ws://0.0.0.0:8190/gremlin} with core size of 2
==>Configured 0.0.0.0/0.0.0.0:8190
对比官方文档里发现少了如下两行：
2018-01-15 15:30:31 11528 [main] [INFO ] org.apache.tinkerpop.gremlin.driver.Connection [] - Created new connection for ws://localhost:8182/gremlin
2018-01-15 15:30:31 11538 [main] [INFO ] org.apache.tinkerpop.gremlin.driver.Connection [] - Created new connection for ws://localhost:8182/gremlin

无法使用库里的图名(peopleAndSoft)操作： 
gremlin> peopleAndSoft
No such property: peopleAndSoft for class: groovysh_evaluate

**Comment by zhoney** [comment]
@WilliamShen2019 使用remote连接方式，执行命令时，需要加`:>`，例如：

```
gremlin> :remote connect tinkerpop.server conf/remote.yaml
gremlin> :> peopleAndSoft
gremlin> :> peopleAndSoft.traversal()
```

**Comment by WilliamShen2019** [comment]
这个我试过了，不行的，报错如下：
gremlin> :> peopleAndSoft1
org.apache.tinkerpop.gremlin.groovy.plugin.RemoteException:Host did not respond in a timely fashion - check the server status again
我觉得是我的某一步骤的ip和port配的不对,
我的配置
remote.yaml
hosts:[0.0.0.0]    //这里我也尝试改成我本机的IP，也不行
port:8190

remote-objects.yaml
hosts:[0.0.0.0]      //这里我也尝试改成我本机的IP，也不行
port:8190

还有哪里可能出问题，我怎么确定当hugegraph-server启动后gremlin-server也启动了呢

**Comment by zhoney** [comment]
@WilliamShen2019 现在gremlin-server.yaml默认配置gremlin-server在localhost:8182，你是否配置了？

如果没配置，在rest-server.properties中配置`gremlinserver.url`为你的实际地址，然后在gremlin-server.yaml中配置`host`和`port`

可以参考[配置说明](https://hugegraph.github.io/hugegraph-doc/config/config-guide.html)

**Comment by WilliamShen2019** [comment]
@zhoney 
按您说的配置了，之后HugeGraphServer都起不来了，报超时错误：
Connecting to HugeGraphServer (http://0.0.0.0:8096/graphs) .....................The operation timed out when attempting to connect to http://0.0.0.0:8096/graphs

另外remote-objects.yaml，remote.yaml这俩文件的hosts和ip是不是也要配置为gremlin-server.yaml中的host和port，我现在就是这么配置的，如果不是，要配置为什么样

**Comment by zhoney** [comment]
@WilliamShen2019 服务启动不起来，看下日志中有什么错误，日志文件为：`logs/hugegraph-server.log`，同时把你目前的`conf/rest-server.properties`和`conf/gremlin-server.yaml`配置贴一下

一般正常使用都是用本机ip，`0.0.0.0`多用于做负载均衡或者HA的时候。
