### ISSUE TITLE
亿级数据量下3度K-out查询过慢

### ISSUE THREAD

**Issue by zekepower** [hugegraph/hugegraph#508]
大家好，

我在一台32G内存，8核的机器上安装了HugeGraph-Server 0.9.2，HugeGraph-Loader 0.9.0和HugeGraph-Studio 0.9.0. 基本采用默认配置。

我使用loader导入了大概1亿多节点，2亿多关系，总共数据量30多GB。
我的节点有两种，一个是contact包含一个tel属性作为主键，另一个是role包含一个roleId属性作为主键。
我的关系也有两种，一个是contact和role的关系，名为roleis表示一个联系人的角色是啥。另一个是contact和contact的关系，名为hastelcontact表示联系人之间的关系。

我看文档里写HugeGraph的K-out性能很强。所以我尝试写了一个查找二级联系人的角色有哪些的，也就是一个3度的查询如下：
`g.V().has('contact', 'tel', '++1Nt22p5ENYT4Kr0P2Rtw==').repeat(out('hastelcontact').dedup()).times(2).out('roleis').dedup().values('roleId').toSet()`

我在studio里执行这个查询，结果30秒内没有返回超时了。看上去执行得不够快。
执行过后，我又执行了如下profile
`g.V().has('contact', 'tel', '++1Nt22p5ENYT4Kr0P2Rtw==').repeat(out('hastelcontact').dedup()).times(2).out('roleis').dedup().values('roleId').profile()`

应该是之前的执行在系统里产生了缓存，profile返回得很快。profile的结果如下
<img width="868" alt="图片" src="https://user-images.githubusercontent.com/49972790/57572578-e92fb600-744e-11e9-9b3e-2b16eff69924.png">
<img width="229" alt="图片" src="https://user-images.githubusercontent.com/49972790/57572597-2b58f780-744f-11e9-95ff-029f23589614.png">

我现在的问题主要有几点：
1. 我的查询语句是否合适？如果可以优化，麻烦指点一下。
2. 在配置上是否有什么可以优化的地方？
3. 我的机器性能是不是不够，如果不够需要提升到什么样的程度，能让我这个case在第一次查询的时候以秒级返回？
4. 使用HugeGraph-Client来查询，会更快吗？如果方便的话，能否提供一些核心代码，让我可以参考？

谢谢！

**Comment by zhoney** [comment]
@zekepower 

> 我的查询语句是否合适？如果可以优化，麻烦指点一下。

Gremlin语句可以达到期望的结果。

> 在配置上是否有什么可以优化的地方？

存储后端是RocksDB的话，可以尝试配置多盘；后端是Cassandra或者Hbase等分布式存储的话，根据需要调整规模。可以参考 (HugeGraph配置项)[https://hugegraph.github.io/hugegraph-doc/config/config-option.html]

> 我的机器性能是不是不够，如果不够需要提升到什么样的程度，能让我这个case在第一次查询的时候以秒级返回？

这个查询没有返回是因为超时，默认30s，根据profile的结果可以看到，需要执行300s以上。

超时的原因需要进一步分析，主要包括：

1. 分析一层邻居和二层邻居的contact的数目，数目多耗时自然比较长，可以使用limit()语句限制规模
2. 观察执行时server端内存消耗，根据需要判断是否增大内存（建议配置是48 core，128GB内存以上）

> 使用HugeGraph-Client来查询，会更快吗？如果方便的话，能否提供一些核心代码，让我可以参考？

用client或者RESTful API的话，可以用customized paths API，步骤如下：
1. 通过customized paths获取全部路径，路径中最后一个顶点则是role顶点的id
2. 如果需要完整role顶点小信息，则根据所有路径中最后一个顶点的id列表获取全部的role顶点
