### ISSUE TITLE
hasValue()语法错误，请大神指点

### ISSUE THREAD

**Issue by 1315861791** [hugegraph/hugegraph#510]
![image](https://user-images.githubusercontent.com/24642133/57608110-f8257e00-759e-11e9-9565-7a7436816312.png)

**Comment by zhoney** [comment]
@1315861791 在不建立索引的情况下，目前只有Cassandra后端支持这种hasValue()查询。

建议对要进行查询的属性建立索引，用has(key,value)形式进行查询

**Comment by 1315861791** [comment]
我建了search索引。这种索引不支持hasValue语法吗

**Comment by javeme** [comment]
@1315861791 Search索引用法可以参考 #449
