### ISSUE TITLE
关于分布式hbase zookeeper的ip配置，hbase.hosts配置项中多个ip或hostname之间是用逗号分隔么

### ISSUE THREAD

**Issue by oushu1zhangxiangxuan1** [hugegraph/hugegraph#511]

**Comment by minilop** [comment]
用逗号分隔
<property>                                                                                                                                                
   <name>hbase.zookeeper.quorum</name>                                                                                                                    
   <value>zk1,zk2,zk3</value>                                                                                                                    
</property>

**Comment by Linary** [comment]
使用逗号分隔，感谢 @minilop 。

**Comment by oushu1zhangxiangxuan1** [comment]
@Linary @minilop 多谢两位，希望随便更新一下官方文档

**Comment by oushu1zhangxiangxuan1** [comment]
@Linary 我改了一下，在doc repo里提了个pr   https://github.com/hugegraph/hugegraph-doc/pull/32
