### ISSUE TITLE
使用Rest API 创建点边报错：HTTP 415

### ISSUE THREAD

**Issue by fuling1999** [hugegraph/hugegraph#516]
按RESTFUL API可以查询，但是创建点和边时都报错误：HTTP 415 Unsupported Media Type。如下：

[root@localhost hugegraph-0.9.2]# curl -X POST http://localhost:8080/graphs/hugegraph/graph/vertices -d '

{
"label": "domain",
"properties": {
"DOMAIN": "www.soso.com"
}
}'
{"exception":"class javax.ws.rs.NotSupportedException","message":"HTTP 415 Unsupported Media Type","cause":""}

 @fuling1999

**Comment by fuling1999** [comment]
按RESTFUL API可以查询，但是创建点和边时都报错误：HTTP 415 Unsupported Media Type。如下：

[root@localhost hugegraph-0.9.2]# curl -X POST http://localhost:8080/graphs/hugegraph/graph/vertices -d '
> {
>     "label": "domain",
>     "properties": {
>         "DOMAIN": "www.soso.com"
>     }
> }'
{"exception":"class javax.ws.rs.NotSupportedException","message":"HTTP 415 Unsupported Media Type","cause":""}

**Comment by Linary** [comment]
你得加上 -H "Content-Type:application/json"
