### ISSUE TITLE
报错java.util.ArrayList cannot be cast to org.apache.tinkerpop.gremlin.process.traversal.traverser.util.TraverserSet

### ISSUE THREAD

**Issue by 1315861791** [hugegraph/hugegraph#518]
不指定方向时查询结果正常，如下：
![image](https://user-images.githubusercontent.com/24642133/58159192-948e0580-7cae-11e9-9801-db5040f0c727.png)
指定方向事报错
![image](https://user-images.githubusercontent.com/24642133/58159227-9fe13100-7cae-11e9-8337-b187667ce387.png)
请问是我的写法有问题吗？我要做的操作是扩展一阶邻节点，以点ID分组，得到每组的边ID集合

**Comment by 1315861791** [comment]
经测试在这个语句中只能写otherV，其他的几种（outV，inV，bothV）都报这个错误，请大神指点

**Comment by javeme** [comment]
@1315861791 可以使用这个语句：`g.V(source).outE().as('e').inV().as('v').group().by().by(select('e').by(id().fold()))`

另外`otherV`不报错是因为其（MapStep）与另外几种（FlatMapStep）的性质不一样。

**Comment by 1315861791** [comment]
果然可以了，谢谢大神
![image](https://user-images.githubusercontent.com/24642133/58167873-88f70a80-7cbf-11e9-9770-9291e89bbe02.png)
