### ISSUE TITLE
0.9.2中property的数据结构是否已经与0.8.0中的不同？

### ISSUE THREAD

**Issue by oushu1zhangxiangxuan1** [hugegraph/hugegraph#521]
还是数据的问题？数据都是用各自版本中的godsgraph中示例代码

#### Vertex/Edge example 数据示例
0.8.0
![image](https://user-images.githubusercontent.com/39079736/58221918-de2a2f00-7d46-11e9-9dc3-33f2c3d741b1.png)

0.9.2
![image](https://user-images.githubusercontent.com/39079736/58222489-c8b60480-7d48-11e9-9d9f-e710cc555ddc.png)

请问除此以及release-notes所提到的更改之外，在0.8.0升级到0.9.2的过程中，还需要注意哪些问题？

**Comment by javeme** [comment]
@oushu1zhangxiangxuan1 是的，0.9对顶点属性的结构做了简化，变得更加直观自然。不过没有在文档中进行说明确实是我们的疏漏。
