### ISSUE TITLE
请教一个gremlin语句的写法：人员分组问题

### ISSUE THREAD

**Issue by WilliamShen2019** [hugegraph/hugegraph#524]
@zhoney 
@javeme 
@Linary 
在hugegraph里导入了一张图，包含两种label的点：演员 actor，电影 movie，每种点都只包含一个name属性，包含一种边 acted ，现在想求出至少三个人，同时参演过至少三部电影的分组，并把参演人员和参演电影展示出来，结果类似以下：
[actor1,actor3,actor4]->[movie1,movie3,movie5]
[actor1,actor3,actor7]->[movie1,movie3,movie8]
[actor1,actor2,actor4,actor7,actor9]->[movie1,movie4,movie5,movie10]
[actor1,actor6,actor8,actor9]->[movie6,movie7,movie8]

请高手赐教

**Comment by javeme** [comment]
@WilliamShen2019 这个可能涉及到较为复杂的逻辑，而且需要数据来校验。建议你先尝试自己写gremlin，如果遇到什么问题可以继续提出来。

**Comment by WilliamShen2019** [comment]
我自己写过同时参演三部电影的演员，
gremlin> g.V().hasLabel('movie').as('ma').in('actedIn').as('aa').out('actedIn').as('mb').in('actedIn').as('aa').out('actedIn').as('mc').in('actedIn').as('aa').where('ma',neq('mb')).where('ma',neq('mc')).where('mb',neq('mc')).select('ma','mb','mc','aa').by('name')
结果：
==>{ma=Fast & Furious3, mb=Fast & Furious8, mc=Fast & Furious7, aa=Lucas Black}
==>{ma=Fast & Furious3, mb=Fast & Furious7, mc=Fast & Furious8, aa=Lucas Black}
==>{ma=逃学威龙3, mb=功夫, mc=国产凌凌漆, aa=周星驰}
==>{ma=逃学威龙3, mb=功夫, mc=逃学威龙1, aa=周星驰}
==>{ma=逃学威龙3, mb=功夫, mc=喜剧之王, aa=周星驰}
==>{ma=逃学威龙3, mb=功夫, mc=大话西游, aa=周星驰}
==>{ma=逃学威龙3, mb=功夫, mc=逃学威龙2, aa=周星驰}
==>{ma=逃学威龙3, mb=功夫, mc=少林足球, aa=周星驰}
==>{ma=逃学威龙3, mb=国产凌凌漆, mc=功夫, aa=周星驰}
==>{ma=逃学威龙3, mb=国产凌凌漆, mc=逃学威龙1, aa=周星驰}
==>{ma=逃学威龙3, mb=国产凌凌漆, mc=喜剧之王, aa=周星驰}
==>{ma=逃学威龙3, mb=国产凌凌漆, mc=大话西游, aa=吴孟达}
==>{ma=逃学威龙3, mb=国产凌凌漆, mc=逃学威龙2, aa=周星驰}
==>{ma=逃学威龙3, mb=国产凌凌漆, mc=少林足球, aa=吴孟达}
==>{ma=逃学威龙3, mb=逃学威龙1, mc=功夫, aa=周星驰}
==>{ma=逃学威龙3, mb=逃学威龙1, mc=国产凌凌漆, aa=周星驰}
==>{ma=逃学威龙3, mb=逃学威龙1, mc=喜剧之王, aa=吴孟达}
==>{ma=逃学威龙3, mb=逃学威龙1, mc=大话西游, aa=吴孟达}
我想按照结果中的电影 ma+mb 为演员 aa 来分组，不知道怎么写

**Comment by cmdares** [comment]
@javeme 该场景应为图模式发现问题，希望您给点可行的思路，我这边也有类似的问题。感谢。
