### ISSUE TITLE
Gremlin查询出来的Vertex，不能执行addEdge

### ISSUE THREAD

**Issue by 306495389li** [hugegraph/hugegraph#525]
### Expected behavior 期望表现
通过Gremlin查询出来的Vertex，和新建的顶点建立推荐关系

### Actual behavior 实际表现
Gremlin查询出来的Vertex没有GraphManager

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: 0.9.2
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by Linary** [comment]
@306495389li 感谢反馈，这确实是一个问题，我们会立马修复。

**Comment by Linary** [comment]
已修复：https://github.com/hugegraph/hugegraph-client/pull/49
