### ISSUE TITLE
Postgresql existDatabase(), dropDatabase() and rollback() not work

### ISSUE THREAD

**Issue by zhoney** [hugegraph/hugegraph#530]
### Actual behavior 实际表现
- existDatabase()无法用metadata实现
- dropDatabase()由于有其他session连接，无法强制删除
- rollback()在commit()异常后调用，会由于Transaction处于autoCommit状态失败

### Specifications of environment 环境信息
- hugegraph version: 0.9.2
- hugegraph backend: postgresql

**Comment by javeme** [comment]
rollback问题表现：
```
com.baidu.hugegraph.backend.BackendException: Failed to rollback
Caused by: org.postgresql.util.PSQLException: Cannot rollback when autoCommit is enabled.
```
