### ISSUE TITLE
【问题】是否支持多个字段建立联合的全文索引

### ISSUE THREAD

**Issue by Xaprice** [hugegraph/hugegraph#532]
请教一个问题，
使用RocksDB的后端，对单个字段建全文索引然后查询没有问题，然后尝试用：
```java
 schema.indexLabel("xxx")
                .onV("person")
                .by("content","city","name").search().ifNotExist().create();
```
对多个字段建全文索引，没有报错，不知道是否可以这样建，如果支持这种建法的话怎么查询？

**Comment by javeme** [comment]
@Xaprice 目前还不支持search索引的联合索引（在插入数据时如果检测到多列值作为索引内容会报错），目前建议分开创建。

当然我们可以考虑支持这个功能，如果你那边的使用场景合理的话，不过查询的时候按什么语义去查确实是个问题。
