### ISSUE TITLE
hugegraph-studio-0.9.0执行语句报错

### ISSUE THREAD

**Issue by 306495389li** [hugegraph/hugegraph#535]
### Expected behavior 期望表现
hugegraph-studio-0.9.0可以正常操作图数据库

### Actual behavior 实际表现
java代码可以正常读写操作，但是hugegraph-studio-0.9.0，使用ip端口，可以访问页面，但是执行g.V()时谷歌浏览器71.0.3578.98报错
Uncaught Error: ace.edit can't find div #card_default_editor，后台无法收到请求

### Specifications of environment 环境信息
-operating system:Linux version 2.6.32-696.28.1.el6.x86_64 (mockbuild@x86-01.bsys.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-18) (GCC) ) #1 SMP Wed May 9 23:09:02 UTC 2018
- hugegraph version: 0.9.2
- hugegraph-studio-0.9.0

**Comment by Linary** [comment]
@306495389li 这个问题在 https://github.com/hugegraph/hugegraph-studio/issues/18 中已修复，你的release 包是最新下载的吗？

**Comment by 306495389li** [comment]
我目前下载的是从https://github.com/hugegraph/hugegraph-doc/blob/master/download.md下载的最新的，还是需要git源码编译
