### ISSUE TITLE
API类重复

### ISSUE THREAD

**Issue by whuawell** [hugegraph/hugegraph#537]
### Expected behavior 期望表现
{type something here...}

### Actual behavior 实际表现
{type something here...}
client.jar包中 com.baidu.hugegraph.api.API
和 api.jar中 com.baidu.hugegraph.api.API类有两个，导致VersionAPI构造出错。

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
		<hugegraph.dist.version>0.9.2</hugegraph.dist.version>
		<hugegraph.client.version>1.7.0</hugegraph.client.version>

**Comment by Linary** [comment]
@whuawell 感谢反馈
这个问题确实存在，但是一般不会同时依赖 dist 和 client 的，你这么写是有什么特定的需求吗？

**Comment by whuawell** [comment]
没有特定需求，我测试了下hugegraph-benchmark下rest性能时，发现有冲突
