### ISSUE TITLE
更新对象属性有延迟

### ISSUE THREAD

**Issue by a453414953** [hugegraph/hugegraph#540]
### Expected behavior 期望表现
某种对象类型有4个属性，存在一个对象，只有三个属性有值，更新这个对象的第四个属性后，立即查询这个对象，其他3个属性不变，第四个属性更新。
 

### Actual behavior 实际表现
更新完毕后，立即查询会出现两种情况，1.还是原来的三个属性，2.一个主键属性外加第四个新增的属性。一段时间后，查询结果是前三个属性存在不变，第四个属性也存在。

### Steps to reproduce the problem 复现步骤
1. 数据准备
graph.schema().propertyKey("name").asText().ifNotExist().create()
graph.schema().propertyKey("age").asInt().ifNotExist().create()
graph.schema().propertyKey("city").asText().ifNotExist().create()
graph.schema().propertyKey("sex").asText().ifNotExist().create()
graph.schema().propertyKey("date").asText().ifNotExist().create()
people = graph.schema().vertexLabel("people").properties("name", "age", "city", "sex").nullableKeys("age", "city", "sex").primaryKeys("name").ifNotExist().create()
friend = graph.schema().edgeLabel("friend").sourceLabel("people").targetLabel("people").properties("date").ifNotExist().create()
marko = graph.addVertex(T.label, "people", "name", "marko", "age", 29, "city", "Beijing")
vadas = graph.addVertex(T.label, "people", "name", "vadas", "age", 27, "city", "Hongkong")
marko.addEdge("friend", vadas, "date", "20160110")

2. 更新数据
graph.addVertex(T.label, "people", "name", "marko", "sex", "male")

3. 查询更新结果
g.V().hasLabel('people').has('name', 'marko')
结果：
{"city":[{"id":"8:marko>city","value":"Beijing"}],"sex":[{"id":"8:marko>sex","value":"male"}],"name":[{"id":"8:marko>name","value":"marko"}],"age":[{"id":"8:marko>age","value":29}]}

g.V('8:marko')
结果：
{"sex":[{"id":"8:marko>sex","value":"male"}],"name":[{"id":"8:marko>name","value":"marko"}]}

g.V().hasLabel('people').has('name', 'vadas').both()
结果：
{"sex":[{"id":"8:marko>sex","value":"male"}],"name":[{"id":"8:marko>name","value":"marko"}]}

一段时间后，三个查询结果一致，都是：
{"city":[{"id":"8:marko>city","value":"Beijing"}],"sex":[{"id":"8:marko>sex","value":"male"}],"name":[{"id":"8:marko>name","value":"marko"}],"age":[{"id":"8:marko>age","value":29}]}

#### Vertex/Edge summary 数据量
- loaded vertices amount: 2
- loaded edges amount: 1
- loaded time: 

#### Vertex/Edge example 数据示例
marko = graph.addVertex(T.label, "people", "name", "marko", "age", 29, "city", "Beijing")
vadas = graph.addVertex(T.label, "people", "name", "vadas", "age", 27, "city", "Hongkong")
marko.addEdge("friend", vadas, "date", "20160110")

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
graph.schema().propertyKey("name").asText().ifNotExist().create()
graph.schema().propertyKey("age").asInt().ifNotExist().create()
graph.schema().propertyKey("city").asText().ifNotExist().create()
graph.schema().propertyKey("sex").asText().ifNotExist().create()
graph.schema().propertyKey("date").asText().ifNotExist().create()
people = graph.schema().vertexLabel("people").properties("name", "age", "city", "sex").nullableKeys("age", "city", "sex").primaryKeys("name").ifNotExist().create()
friend = graph.schema().edgeLabel("friend").sourceLabel("people").targetLabel("people").properties("date").ifNotExist().create()

### Specifications of environment 环境信息
- hugegraph version:  v0.8.0
- operating system: centos 6.5, 8 CPUs, 32G RAM
- hugegraph backend: hbase 1.2.0-cdh5.7.6

**Comment by javeme** [comment]
@a453414953 更新属性的时候建议使用
`g.V().hasLabel('people').has('name', 'marko').property("sex", "male")`
来代替
`graph.addVertex(T.label, "people", "name", "marko", "sex", "male")`
