### ISSUE TITLE
Date属性建索引，查询报错：not match secondary/range condition

### ISSUE THREAD

**Issue by fuling1999** [hugegraph/hugegraph#541]
### Expected behavior 期望表现
正常执行查询

### Actual behavior 实际表现
Error!
Don't accept query based on properties [time] that are not indexed in label 'attack', may not match secondary/range condition

### Steps to reproduce the problem 复现步骤
为边attack上的 time 属性（Date类型）建立了索引，查询情况如下：
1. g.E().hasLabel('attack').has('time','2018-12-12 00:00:00') 正常
2. g.E().hasLabel('attack').has('time', gt('2019-02-20 00:00:00')) 错误如上
3. g.V().hasLabel('ip').outE("attack").has('time', gt('2019-02-20 00:00:00')) 正常

奇怪的是为何3 可以，而2 却报错？这两个查询基本上是等价的啊

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
time 属性 是Date类型，索引如下：
      {
            "id": 5,
            "name": "time",
            "base_type": "EDGE_LABEL",
            "base_value": "attack",
            "index_type": "SECONDARY",
            "fields": [
                "time"
            ]
        }

### Specifications of environment 环境信息
- hugegraph version: v0.9.2

**Comment by javeme** [comment]
@fuling1999 这种报错是预期的，如果需要进行第2种查询请建立range索引。

**Comment by fuling1999** [comment]
> @fuling1999 这种报错是预期的，如果需要进行第2种查询请建立range索引。

谢谢，已经改了，range索引的确可以，只是很奇怪为何第3种查询在SECONDARY索引就可以。
