### ISSUE TITLE
并发查询的问题

### ISSUE THREAD

**Issue by 306495389li** [hugegraph/hugegraph#544]
### Expected behavior 期望表现
在做压力测试时，50个并发，过一会会报错
### Actual behavior 实际表现
报错如下：com.baidu.hugegraph.exception.ServerException: The server is too busy to process the request, please try again later
跑过一段时间：com.baidu.hugegraph.exception.ServerException: GC overhead limit exceeded
### Specifications of environment 环境信息
- hugegraph version: v0.9.0
- operating system: Linux version 2.6.32-696.28.1.el6.x86_64 (mockbuild@x86-01.bsys.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-18) (GCC) ) #1 SMP Wed May 9 23:09:02 UTC 2018

**Comment by javeme** [comment]
@306495389li 可以把占用内存、JVM分配内存等信息反馈一下么？
通用情况下，极有可能是内存不够导致，请加大内存或者请调小缓存大小。

**Comment by 306495389li** [comment]
在哪里修改这些配置，现在使用的默认配置启动的

**Comment by 306495389li** [comment]
现在连接的是mysql
