### ISSUE TITLE
HugeClient的kneighbor操作可以返回顶点的所有属性信息吗？

### ISSUE THREAD

**Issue by pengjianbo** [hugegraph/hugegraph#545]
```java
List<Object> list = hugeClient.traverser().kneighbor(vertexId, Direction.BOTH, 3)
```
这样执行返回的是N度关系的顶点ID列表，可以顺便把顶点的属性也返回吗

**Comment by imbajin** [comment]
可能是考虑到返回完整的点数据太大, 你可以再使用[批量点](https://hugegraph.github.io/hugegraph-doc/clients/restful-api/traverser.html#32101-%E6%A0%B9%E6%8D%AE%E9%A1%B6%E7%82%B9%E7%9A%84id%E5%88%97%E8%A1%A8%EF%BC%8C%E6%89%B9%E9%87%8F%E6%9F%A5%E8%AF%A2%E9%A1%B6%E7%82%B9)/边查的接口取出详细信息, 
关键问题是, 你在没有**点对应的边**信息的情况下, 只知道某点出发3跳的所有其它点的集合, 然后怎么使用呢.

**Comment by pengjianbo** [comment]
估计是。那我只能再通过顶点Id找一下Vertex实例了。目前我们只需要考虑一点出发的N关系下面的所有顶点信息，不需要考虑路线
