### ISSUE TITLE
out,both 正常，in语法报错，求大神指点

### ISSUE THREAD

**Issue by 1315861791** [hugegraph/hugegraph#550]
![image](https://user-images.githubusercontent.com/24642133/58856474-5bee2300-86d5-11e9-8a29-71a4591b14b1.png)
![image](https://user-images.githubusercontent.com/24642133/58856509-70322000-86d5-11e9-9540-54ae858b5911.png)
![image](https://user-images.githubusercontent.com/24642133/58856544-850eb380-86d5-11e9-885e-534e94d2e2b6.png)

**Comment by Linary** [comment]
你写成`__.in()`试试

**Comment by 1315861791** [comment]
这样写是可以的。麻烦问一下为什么会这样啦？

**Comment by 1315861791** [comment]
> 写成你`__.in()`试试

感谢大神指点
