### ISSUE TITLE
关于条件查询顶点的两个疑问

### ISSUE THREAD

**Issue by pengjianbo** [hugegraph/hugegraph#560]
顶点上有一个`createTime`属性（该属性有加索引），我想把所有`createTime`小于某个时间戳的顶点查出来。我有几个疑问想请教下：
* 1、通过`HugeClient`的`iterateVertices(...)`好像是实现不了是吧？那`HugeClient`中有没有其他方法可以实现？
* 2、如果通过`Gremlin`语言的`lte`条件来实现的话，结果数据太大好像没法分页吧。

入门小白，还请两位大神指教，感谢感谢~ 
@javeme @Linary

**Comment by javeme** [comment]
@pengjianbo 分别解答如下
> * 1、通过`HugeClient`的`iterateVertices(...)`好像是实现不了是吧？那`HugeClient`中有没有其他方法可以实现？

`iterateVertices`接口目前没有提供小于及大于语义的条件查询，仅提供了等于条件查询，所以确实无法实现。

> * 2、如果通过`Gremlin`语言的`lte`条件来实现的话，结果数据太大好像没法分页吧。

Gremlin更加自由，完全支持小于条件查询，但是Gremlin语法目前没有支持分页的机制，所以如你所说也没办法分页。如果结果集大于百万以上，建议每次查询再加上大于条件，相当于分为一个一个时间区间进行查询。

**Comment by pengjianbo** [comment]
@javeme 明白了，感谢。希望`iterateVertices`方法能够加上'<'或'>'这样的条件查询，感觉这样的查询条件用的还不少。
