### ISSUE TITLE
查询多次偶尔报错

### ISSUE THREAD

**Issue by 306495389li** [hugegraph/hugegraph#565]
### Expected behavior 期望表现
稳定查询
### Actual behavior 实际表现
{type something here...}
查询多次偶尔报错，Failed to query [Query for VERTEX page=null, offset=0, limit=9223372036854775807, order by {} where id in [S2c711441-13d1-4a4e-8672-b530b4cca2581560332875636]]

### Specifications of environment 环境信息
hugegraph version: v0.9.0
operating system: Linux version 2.6.32-696.28.1.el6.x86_64 (mockbuild@x86-01.bsys.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-18) (GCC) ) #1 SMP Wed May 9 23:09:02 UTC 2018

**Comment by javeme** [comment]
@306495389li 请问是否与这个问题类似 https://github.com/hugegraph/hugegraph/issues/561，若是mysql连接断开问题的话，可以手动打包一下新的代码（最新代码目前还没有发布，如果有需要我们可以提供tar包）。

**Comment by 306495389li** [comment]
@javeme 类似于#561这个问题也存在，现在在正常连接的情况下，昨天连续出现多次报错，今天没有出现，能提供下最新的包吗？谢谢了，拉下来代码，编译总是报错

**Comment by Linary** [comment]
@306495389li 抱歉，tar包太大，没法在这儿上传。

**Comment by javeme** [comment]
@306495389li 这里无法上传tar包的话，你可以通过HugeGraph微信公众号联系我们，直接给你传tar包。
