### ISSUE TITLE
源码编译报错

### ISSUE THREAD

**Issue by 306495389li** [hugegraph/hugegraph#568]
源码编译报错：
 Failed to execute goal on project hugegraph-core: Could not resolve dependencies for project com.baidu.hugegraph:hugegraph-core:jar:0.10.0: The following artifacts could not be resolved: org.codehaus.groovy:groovy:jar:indy:2.4.11, org.codehaus.groovy:groovy:jar:2.4.11, com.h2database:h2:jar:1.3.171, org.mockito:mockito-core:jar:1.9.5: Could not transfer artifact org.codehaus.groovy:groovy:jar:indy:2.4.11 from/to nexus-aliyun (http://maven.aliyun.com/nexus/content/groups/public): GET request of: org/codehaus/groovy/groovy/2.4.11/groovy-2.4.11-indy.jar from nexus-aliyun failed: Premature end of Content-Length delimited message body (expected: 4529296; received: 3766917 -> [Help 1]
相关环境
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-11T00:41:47+08:00)
Maven home: C:\develop\apache-maven-3.3.9\bin\..
Java version: 1.8.0_181, vendor: Oracle Corporation
Java home: C:\develop\Java\jdk1.8.0_181\jre
Default locale: zh_CN, platform encoding: GBK
OS name: "windows 10", version: "10.0", arch: "amd64", family: "dos"

**Comment by Linary** [comment]
你可以按照如下步骤重新试试：
1. 进入到你本地的 maven 仓库，一般在 ~/.m2/repository，删除那些报错的 jar 包，比如 `org.codehaus.groovy:groovy:jar:indy:2.4.11`，进入目录 org/codehaus/groovy/groovy/，删除子目录 `2.4.11`，避免有下了一半的依赖包影响再次导入
2. 注释aliyun的镜像配置，像这样
```
<mirrors>
    <!-- <mirror>
        <id>nexus-aliyun</id>
        <mirrorOf>*</mirrorOf>
        <name>Nexus aliyun</name>
        <url>http://maven.aliyun.com/nexus/content/groups/public</url>
    </mirror>
    <mirror>
        <id>alimaven</id>
        <name>aliyun maven</name>
        <url>http://maven.aliyun.com/nexus/content/groups/public/</url>
        <mirrorOf>central</mirrorOf>
    </mirror> -->
  </mirrors>
```
3. 进入hugegraph的主目录，执行`mvn install -DskipTests`

**Comment by 306495389li** [comment]
@Linary 最新打包的启动失败Starting HugeGraphServer...
Connecting to HugeGraphServer (http://192.168.15.128:8183/graphs)................The operation timed out when attempting to connect to http://192.168.15.128:8183/graphs
See /opt/HugeGraph/hugegraph-0.10.0/logs/hugegraph-server.log for HugeGraphServer log output.
这个目录下/opt/HugeGraph/hugegraph-0.10.0/logs/没有错误日志

**Comment by Linary** [comment]
控制台和日志里面都没有错误信息吗？

**Comment by 306495389li** [comment]
没有，控制台就显示超时，目录下没有日志，相同的配置，使用0.9.2正常启动

**Comment by Linary** [comment]
你启动新的服务的时候旧版的服务有在运行吗？如果有在运行，你有修改新服务的gremlin-server的端口吗？

**Comment by 306495389li** [comment]
@Linary 我是先关闭旧版本，在运行的新版本
