### ISSUE TITLE
根据文档刚刚部署HugeGraph-studio，操作报错不太明白，望大神指点

### ISSUE THREAD

**Issue by jackchen-c** [hugegraph/hugegraph#569]
代码如下：
knows = graph.schema().edgeLabel("knows").sourceLabel("person").targetLabel("person").properties("date").ifNotExist().create()

marko = graph.addVertex(T.label, "person", "name", "marko", "age", 29, "city", "Beijing")
vadas = graph.addVertex(T.label, "person", "name", "vadas", "age", 27, "city", "Hongkong")
marko.addEdge("knows", vadas, "date", "20160110")
报错如下：
Error!
All non-null property keys: [weight, date] of edge label 'knows' must be setted, but missed keys: [weight]

**Comment by Linary** [comment]
两种改法

1. 把`weight`和`date`设置为可空属性
```
graph.schema().edgeLabel("knows").nullableKeys("weight", "date").append();
```

2. 添加边的时候把`weight`和`date`都写上
```
marko.addEdge("knows", vadas, "weight", 0.5, "date", "20160110")
```
