### ISSUE TITLE
hugegraph-loader 导入postgresql表是该用哪个驱动

### ISSUE THREAD

**Issue by 1315861791** [hugegraph/hugegraph#570]
![image](https://user-images.githubusercontent.com/24642133/59560154-e9b7ff80-903f-11e9-8c2e-785e749533c8.png)

我驱动应该没写对，请大神指点

**Comment by 1315861791** [comment]
![image](https://user-images.githubusercontent.com/24642133/59560280-06553700-9042-11e9-84be-7dffd1e3a06d.png)

求大神指点迷津给个解决思路

**Comment by 1315861791** [comment]
我在lib目录下加入了驱动包的jar之后不报上面那个错了，但还是导入失败了。恳求大神指点！！！
![image](https://user-images.githubusercontent.com/24642133/59560326-e4a87f80-9042-11e9-935f-b14c1492fbe2.png)

**Comment by 1315861791** [comment]
报错日志如下：
![image](https://user-images.githubusercontent.com/24642133/59560439-9f854d00-9044-11e9-8430-08efcda35dea.png)


![image](https://user-images.githubusercontent.com/24642133/59560446-add36900-9044-11e9-978b-384a33bb8737.png)

**Comment by Linary** [comment]
@1315861791 抱歉，错误提示地不够清晰。

看看你的`schema.groovy`和`struct.json`，还有表中的数据截个图（几条即可）。

**Comment by 1315861791** [comment]
![image](https://user-images.githubusercontent.com/24642133/59599328-d89aeb80-9130-11e9-8944-4e30cf39f25d.png)
![image](https://user-images.githubusercontent.com/24642133/59599877-3aa82080-9132-11e9-87b6-d99e1eda36ec.png)
![image](https://user-images.githubusercontent.com/24642133/59599934-5e6b6680-9132-11e9-99db-5da87101ae2c.png)
数据就是咱们loader例子中的数据

**Comment by 1315861791** [comment]
@Linary 求大神指点

**Comment by Linary** [comment]
@1315861791 你的 postgresql 版本是多少？你可以把源码拉下来，把`RowFetcher`这个类中`readHeader()`方法的`TABLE_SCHEMA`改成`TABLE_CATALOG`然后再打包运行试试。

就像这样

```
String sql = String.format("SELECT COLUMN_NAME " +
                                   "FROM INFORMATION_SCHEMA.COLUMNS " +
                                   "WHERE TABLE_NAME = '%s' " +
                                   "AND TABLE_CATALOG = '%s';",
                                   this.table, this.database);
```

**Comment by 1315861791** [comment]
![image](https://user-images.githubusercontent.com/24642133/59651520-c1a1db00-91bc-11e9-9fe4-38ba720bd036.png)
我改完以后在本地测试了一下，还是报这个错。我用的驱动包如下：
![image](https://user-images.githubusercontent.com/24642133/59651538-ccf50680-91bc-11e9-9257-a0fe1489282f.png)

用这个驱动直接操作数据库是没问题的

**Comment by 1315861791** [comment]
![image](https://user-images.githubusercontent.com/24642133/59655122-d46fdc00-91cb-11e9-953c-014c03096a34.png)
这两个值完全一样的，应该问题不在这个地方
@Linary

**Comment by Linary** [comment]
@1315861791 抱歉，我这边复现不了这个问题。

你可以在本地调试一下，运行 HugeGraphLoader 类，配置上参数，比如：`-g xxx -s demo-pg/schema.groovy -f demo-pg/struct.json`，从 `ElementBuilder.next()` 开始跟踪。

**Comment by 1315861791** [comment]
好的，感谢

**Comment by 1315861791** [comment]
@Linary 麻烦问一下抽取HDFS文件时支持ORC文件吗？
![image](https://user-images.githubusercontent.com/24642133/59663818-6edb1a00-91e2-11e9-9e2a-d4633fff6928.png)

**Comment by Linary** [comment]
@1315861791 暂时不支持，不过有计划支持 https://github.com/hugegraph/hugegraph-loader/issues/45

**Comment by 1315861791** [comment]
明白了，谢谢
