### ISSUE TITLE
多个操作之间是否可以添加事务

### ISSUE THREAD

**Issue by 306495389li** [hugegraph/hugegraph#571]
### Expected behavior 期望表现
现在有个需求是，在一定条件下可以修改推荐关系，删除之前的推荐关系，新建关系，希望2步骤可以同时成功，失败

### Actual behavior 实际表现
现在偶尔出现，关系删除成功，但是新的关系没有建立成功

### Specifications of environment 环境信息
- hugegraph version: 0.9.2
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by javeme** [comment]
@306495389li 多次调用restapi确实会存在这种情况，目前可以使用gremlin的drop+addE等操作，最后进行commit达到你所期望的效果。
