### ISSUE TITLE
HugeGraph后端数据库是HBase时rowKey是否支持reverse

### ISSUE THREAD

**Issue by pengjianbo** [hugegraph/hugegraph#572]
我们有很多顶点的ID是手机号，手机号都是1开头的，我们一般会对rowkey进行反转。HugeGraph内部是否会对rowkey进行反转呢?

**Comment by javeme** [comment]
@pengjianbo hugegraph 有计划支持逆序Sortkey的 #442 ，想了解一下你们具体的需求场景？（比如edgelabel什么样的、高频查询是什么样的）
