### ISSUE TITLE
查询边path（）报错 Undefined edge label id:13 

### ISSUE THREAD

**Issue by bingle2000** [hugegraph/hugegraph#573]
### Expected behavior 期望表现
能够正常查询出图

### Actual behavior 实际表现
Error: Undefined edge label id:13 

### Steps to reproduce the problem 复现步骤
1. g.V().in('resolve').limit(10).path() 正常，可以显示10个点及边
2. g.V().in('resolve').limit(100) 正常，可以显示100个点，没有边
3. g.V().in('resolve').limit(100).path() 异常，报错如上

### Status of loaded data 数据状态
使用restful api查询边的schema，发现边的最大id为19，没有id为13的边，resolve边的id为10，应该是中间删除过边。

#### Vertex/Edge summary 数据量
resolve边10万级

### Specifications of environment 环境信息
- hugegraph version: 0.9.2}

**Comment by javeme** [comment]
@fuling1999 看起来是数据不一致导致的，可以描述一下中间删除edge label的过程吗？使用的是什么后端存储？

**Comment by fuling1999** [comment]
> @fuling1999 看起来是数据不一致导致的，可以描述一下中间删除edge label的过程吗？使用的是什么后端存储？

使用的是RocksDB，具体删除过程记不太清楚了，就是用rest api删除边的schema： DELETE http://localhost:8080/graphs/hugegraph/schema/edgelabels/elabelname ，成功后又重新导数据，重新创建了边；是否也删除了点的schema不记得了。
