### ISSUE TITLE
hugeGraph 的顶点和边的属性的数量有限制码？有推荐范围吗？

### ISSUE THREAD

**Issue by baibingzhi** [hugegraph/hugegraph#576]
如题，谢谢！！

**Comment by javeme** [comment]
@baibingzhi 没有硬性的限制，但是为了达到较好的性能，属性数量建议20个以内。图数据库的核心优势是做关联关系查询及分析，如果确实有较多的属性（大于50个）也可以使用其它存储系统进行冷属性的存储。
