### ISSUE TITLE
g.v(ids)查询时id的列表长了会报错，请问这个限制可以配置吗

### ISSUE THREAD

**Issue by 1315861791** [hugegraph/hugegraph#577]
![image](https://user-images.githubusercontent.com/24642133/59733573-f5463900-9280-11e9-8aac-ad6e0023c9f8.png)

**Comment by javeme** [comment]
@1315861791 这个是groovy语言的限制，没有办法配置的，建议分批进行请求（比如每份250个id）。

**Comment by 1315861791** [comment]
明白了，谢谢您的及时解答
