### ISSUE TITLE
查询结果80w的限制问题

### ISSUE THREAD

**Issue by bingle2000** [hugegraph/hugegraph#586]
查询结果80w的限制，对于大数据量真的很麻烦啊，比如一个 groupCount().by() 查询就已经无法执行了。

另外，如下为何第4正常，而第3居然报错，这是说hasLabel上有80w的限制，而其他步骤上没有吗？

### Actual behavior 实际表现
Error!
Too many records(must <=800000) for the query

### Steps to reproduce the problem 复现步骤
1. 导入100w+ ip顶点，少量设置isp属性，并建立二级索引
2. g.V().hasLabel('ip').groupCount().by('isp') ：报错如上
3、g.V().hasLabel('ip').has('isp').count() ： 报错如上
4、g.V().has('isp').count() ： 居然正常??
5、g.V().groupCount().by('isp') ： 报错The property does not exist as the key has no associated value for the provided element （因为还有其他label顶点，但是没有isp属性的，这样缺少了label的过滤，报错是一方面，需要处理的节点数量也大了啊）
6、g.V().hasLabel('ip').has('isp','cmcc').count() ：正常

难道为了统计一下每种isp属性上的点数量，还需要附带一个字典数据库，然后循环的把每个isp的数量分别查一遍？

### Specifications of environment 环境信息
- hugegraph version: {like v0.9.2

**Comment by javeme** [comment]
@fuling1999 超过80w数据不建议使用TP API查询。

**Comment by hunter7727** [comment]
请问超过80w数据建议用哪种方式？现在我用gremlin 的range(800000,801000)分页查询 也是报这个错误

**Comment by javeme** [comment]
> 请问超过80w数据建议用哪种方式？现在我用gremlin 的range(800000,801000)分页查询 也是报这个错误

返回结果大于80w时，可以使用异步任务，或者使用图计算方式。

分页查询请直接使用rest api方式，使用page参数即可：https://hugegraph.github.io/hugegraph-doc/clients/restful-api/vertex.html

**Comment by megodlike** [comment]
![image](https://user-images.githubusercontent.com/34566983/149049401-b057fdc1-458b-4add-9d6c-78e2a8b0f068.png)
gremlin超过80W这问题治不了了是嘛

**Comment by imbajin** [comment]
> ![image](https://user-images.githubusercontent.com/34566983/149049401-b057fdc1-458b-4add-9d6c-78e2a8b0f068.png) gremlin 超过 80W 这问题治不了了是嘛

@megodlike 方法有不少, 首先你的写法可以改一下.  `g.V().limit(1000).out()` 提前限制, 因为你扫一遍所有点其实也没有多少意义, 当然后续这种语法我们也可以做优化, 把它提前限制.

另外, 80w 的限制也可以代码里调整一下, 我们后续可以提供一个参数供大家自己选择.

**Comment by zhuiyi1** [comment]
> > ![image](https://user-images.githubusercontent.com/34566983/149049401-b057fdc1-458b-4add-9d6c-78e2a8b0f068.png) gremlin 超过 80W 这问题治不了了是嘛
> 
> @megodlike 方法有不少, 首先你的写法可以改一下. `g.V().limit(1000).out()` 提前限制, 因为你扫一遍所有点其实也没有多少意义, 当然后续这种语法我们也可以做优化, 把它提前限制. 然后包括当前 issue 里写到的, 使用 page 分页也可以查询, 跟 mysql 类似, 一般 db 也不会让你扫全表的 (不过后续我们可以让用户自行决定)
> 
> 另外, 80w 的限制也可以代码里调整一下, 我们后续可以提供一个参数供大家自己选择.

大佬请问下在代码中如何调整呢？

**Comment by zhuiyi1** [comment]
> > ![image](https://user-images.githubusercontent.com/34566983/149049401-b057fdc1-458b-4add-9d6c-78e2a8b0f068.png) gremlin 超过 80W 这问题治不了了是嘛
> 
> @megodlike 方法有不少, 首先你的写法可以改一下. `g.V().limit(1000).out()` 提前限制, 因为你扫一遍所有点其实也没有多少意义, 当然后续这种语法我们也可以做优化, 把它提前限制. 然后包括当前 issue 里写到的, 使用 page 分页也可以查询, 跟 mysql 类似, 一般 db 也不会让你扫全表的 (不过后续我们可以让用户自行决定)
> 
> 另外, 80w 的限制也可以代码里调整一下, 我们后续可以提供一个参数供大家自己选择.

@imbajin 大佬在在启动服务时报错  Too many records(must <= 800000) for the query

![559fa9755f45d36b38f03cffd0ca7c8](https://github.com/apache/incubator-hugegraph/assets/100415085/3edb33cb-62a1-483e-8c99-327cf408c0a0)

**Comment by zhuiyi1** [comment]
> > ![image](https://user-images.githubusercontent.com/34566983/149049401-b057fdc1-458b-4add-9d6c-78e2a8b0f068.png) gremlin 超过 80W 这问题治不了了是嘛
> 
> @megodlike 方法有不少, 首先你的写法可以改一下. `g.V().limit(1000).out()` 提前限制, 因为你扫一遍所有点其实也没有多少意义, 当然后续这种语法我们也可以做优化, 把它提前限制. 然后包括当前 issue 里写到的, 使用 page 分页也可以查询, 跟 mysql 类似, 一般 db 也不会让你扫全表的 (不过后续我们可以让用户自行决定)
> 
> 另外, 80w 的限制也可以代码里调整一下, 我们后续可以提供一个参数供大家自己选择.

@imbajin 大佬zai在启动服务时报错 Too many records(must <= 800000) for the query: `Query * from VERTEX`
![1713259283117](https://github.com/apache/incubator-hugegraph/assets/100415085/a666495c-a4ac-417d-a6dc-64f90b346624)

**Comment by zhuiyi1** [comment]
> > > > ![image](https://user-images.githubusercontent.com/34566983/149049401-b057fdc1-458b-4add-9d6c-78e2a8b0f068.png) gremlin 超过 80W 这问题治不了了是嘛
> > > 
> > > 
> > > @megodlike 方法有不少, 首先你的写法可以改一下. `g.V().limit(1000).out()` 提前限制, 因为你扫一遍所有点其实也没有多少意义, 当然后续这种语法我们也可以做优化, 把它提前限制. 然后包括当前 issue 里写到的, 使用 page 分页也可以查询, 跟 mysql 类似, 一般 db 也不会让你扫全表的 (不过后续我们可以让用户自行决定)
> > > 另外, 80w 的限制也可以代码里调整一下, 我们后续可以提供一个参数供大家自己选择.
> > 
> > 
> > @imbajin 大佬zai在启动服务时报错 Too many records(must <= 800000) for the query: `Query * from VERTEX` ![1713259283117](https://private-user-images.githubusercontent.com/100415085/322785205-a666495c-a4ac-417d-a6dc-64f90b346624.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNTk4NDYsIm5iZiI6MTcxMzI1OTU0NiwicGF0aCI6Ii8xMDA0MTUwODUvMzIyNzg1MjA1LWE2NjY0OTVjLWE0YWMtNDE3ZC1hNmRjLTY0ZjkwYjM0NjYyNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNlQwOTI1NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MTQ1Yzk0OTE5NmNiZTFhODExNjc1OGRhMmZhNWNiNjA5NWZhOWNjODAxZTBkZGI5YjIzODU1YTVhMWQ4YWY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3HSZs2_y9UVmVBhJHZWBv5Ic6t8BzWYeEX5_lK0r0js)
> 
> @zhuiyi1 maybe try it first:
> 
> <img alt="image" width="725" src="https://private-user-images.githubusercontent.com/17706099/322787594-d488aabd-2e7e-412d-8ba8-2bca445909dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNjA2NDEsIm5iZiI6MTcxMzI2MDM0MSwicGF0aCI6Ii8xNzcwNjA5OS8zMjI3ODc1OTQtZDQ4OGFhYmQtMmU3ZS00MTJkLThiYTgtMmJjYTQ0NTkwOWRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDA5MzkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiZmVmMTU3ZGE3ODM5MGFhM2JmZjg3YTQ3ODU3NjQ3MzgxYjdmN2Q3ZDA2YmZhZGMyNDc5YzJkNDdiNTJiZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Kalk9e9ePt4LPXopZMMdautVc_wObbzbNpgC-5yg8Jg">
> And u could also build index(IndexLabel) to what u want to search (on Vertex/Edge)

@imbajin 大佬是这样的  现在服务器中有100多玩的节点数据，是在重启服务的时候报的错，还没有进行查询的操作呢，有没有办法改源码或者配置文件 能让服务正常起来呢？

**Comment by imbajin** [comment]
> @imbajin 大佬是这样的 现在服务器中有100多玩的节点数据，是在重启服务的时候报的错，还没有进行查询的操作呢，有没有办法改源码或者配置文件 能让服务正常起来呢？

我是大菜, 虽然不清楚你怎么重启服务遇到这个问题的, 如果可以复现可以给一下复现方式

临时的话, 你可以修改源码, 限制 80w 是之前代码里写死的, 不过这个的确是一个 TODO 一直忘记改了, 应该改为一个可配置的参数,你代码里改了之后可以方便把它抽一下参数化, 提交一个 PR 么? 核心就几行

**Comment by zhuiyi1** [comment]
> > @imbajin 大佬是这样的 现在服务器中有100多玩的节点数据，是在重启服务的时候报的错，还没有进行查询的操作呢，有没有办法改源码或者配置文件 能让服务正常起来呢？
> 
> @zhuiyi1 我是大菜, 虽然不清楚你怎么重启服务遇到这个问题的, 如果可以复现可以给一下复现方式
> 
> 临时的话, 你可以修改源码, 限制 80w 是之前代码里写死的, 不过这个的确是一个 TODO 一直忘记改了, 应该改为一个可配置的参数,你代码里改了之后可以方便把它抽一下参数化, 提交一个 PR 么? 核心就几行

@imbajin 主要是找不到

> > @imbajin 大佬是这样的 现在服务器中有100多玩的节点数据，是在重启服务的时候报的错，还没有进行查询的操作呢，有没有办法改源码或者配置文件 能让服务正常起来呢？
> 
> @zhuiyi1 我是大菜, 虽然不清楚你怎么重启服务遇到这个问题的, 如果可以复现可以给一下复现方式
> 
> 临时的话, 你可以修改源码, 限制 80w 是之前代码里写死的, 不过这个的确是一个 TODO 一直忘记改了, 应该改为一个可配置的参数,你代码里改了之后可以方便把它抽一下参数化, 提交一个 PR 么? 核心就几行

@imbajin 奈何本人太菜找不到 [苦笑]！！！

**Comment by imbajin** [comment]
> > > @imbajin 大佬是这样的 现在服务器中有100多玩的节点数据，是在重启服务的时候报的错，还没有进行查询的操作呢，有没有办法改源码或者配置文件 能让服务正常起来呢？
> > 
> > 
> > @zhuiyi1 我是大菜, 虽然不清楚你怎么重启服务遇到这个问题的, 如果可以复现可以给一下复现方式
> > 临时的话, 你可以修改源码, 限制 80w 是之前代码里写死的, 不过这个的确是一个 TODO 一直忘记改了, 应该改为一个可配置的参数,你代码里改了之后可以方便把它抽一下参数化, 提交一个 PR 么? 核心就几行
> 
> @imbajin 主要是找不到
> 
> > > @imbajin 大佬是这样的 现在服务器中有100多玩的节点数据，是在重启服务的时候报的错，还没有进行查询的操作呢，有没有办法改源码或者配置文件 能让服务正常起来呢？
> > 
> > 
> > @zhuiyi1 我是大菜, 虽然不清楚你怎么重启服务遇到这个问题的, 如果可以复现可以给一下复现方式
> > 临时的话, 你可以修改源码, 限制 80w 是之前代码里写死的, 不过这个的确是一个 TODO 一直忘记改了, 应该改为一个可配置的参数,你代码里改了之后可以方便把它抽一下参数化, 提交一个 PR 么? 核心就几行
> 
> @imbajin 奈何本人太菜找不到 [苦笑]！！！

@zhuiyi1 你可以直接提交一个新的 issue, 然后 @🤖 来帮你找, 基本没有问题的, 它可以提供你比较完整的上下文而且 (如果描述 context 的比较清晰, 支持多语言提问/回复, 英文描述效果更好)

例如:
<img width="673" alt="image" src="https://github.com/apache/incubator-hugegraph/assets/17706099/be9b5952-8a95-4a60-944f-00d39f477af8">
