### ISSUE TITLE
请教下hbase后端时hugegraph如何保证数据原子性的?

### ISSUE THREAD

**Issue by yuyang0** [hugegraph/hugegraph#588]
我看了下代码,hbase存储实现上面有batch操作,但是这不是原子操作,hbase似乎也没有事务支持, 这是不是就意味着用hbase做后端可能出现数据不一致?

**Comment by javeme** [comment]
@yuyang0 是的hbase只保证行写入的原子性，多行写入如果要保证原子写的话需要使用hbase行锁。

**Comment by yuyang0** [comment]
@javeme 既然hbase作为hugegraph的存储可能会有数据不一致, 那是不是可以考虑支持一些有事务支持的分布式存储?

**Comment by javeme** [comment]
@yuyang0 如果对事务要求较强可以使用MySQL或PostgreSQL后端存储（可以使用兼容这两个协议的对应分布式NewSQL数据库）
