### ISSUE TITLE
hugegraph-loader导入太慢，如何优化

### ISSUE THREAD

**Issue by 1315861791** [hugegraph/hugegraph#592]
我导入了1亿条数据，没有建索引，每个点有两个属性，边有两个属性，共耗时8个多小时，跟官网提供的性能相去甚远，跪求优化方法！！！我存储用的hbase，hugegraph相关版本都用的当前最新的，下面是导入截图：
![image](https://user-images.githubusercontent.com/24642133/60146354-dbb26d80-97fb-11e9-848a-90539d69a66b.png)

**Comment by 1315861791** [comment]
![image](https://user-images.githubusercontent.com/24642133/60146560-a3f7f580-97fc-11e9-9d9a-bbb400c19e7b.png)
这个截图是导入的详细过程，可以看出，导入边的时候非常慢，求大神指点

**Comment by imbajin** [comment]
性能问题一般不是一两句简单描述就能解决的, 建议补充以下信息, 方便分析:
1. Hbase集群配置(几台机器. 大概配置, HDFS版本)
2. 导入的时候Server端负载情况+ Loader端导边的时候是否有明显**卡顿**(并**对比**执行耗时图)
3. Hbase集群在导入点边时的负载情况**对比**(每秒接受请求数和写延迟等)

然后如果能从细节上定位到具体**慢在什么地方**, 对解决根本问题会有价值的多. (比如为什么导点速度正常, 导边就慢了十倍, 具体是哪个**函数**执行耗时过长了? 对比点来说)
详细的方法方式可以参考一下之前写的[笔记](https://www.imbajin.com/2019-06-06-Hugegraph-Server%E6%80%A7%E8%83%BD%E9%97%AE%E9%A2%98%E5%88%86%E6%9E%90/), 如果细节定位, 把方法改为`EdgeAPI.create()`就行.

**Comment by Linary** [comment]
感谢 @imbajin 的答复。

@1315861791 
1. 你的 Hbase 集群规模和配置如何
2. loader 端的 --check-vertex 参数是 true 还是 false
3. 服务端的写线程数比例是多少 `batch.max_write_ratio`

**Comment by 1315861791** [comment]
感谢两位大神解答。
1，HBASE是3个节点
2，--check-vertex没设置，默认值应该是false
3，batch.max_write_ratio=80
4，hdfs版本为2.6

**Comment by Linary** [comment]
你的 hbase 集群在你测试的时候有在跑别的任务吗？看日志似乎 20:00-03:00 之间集群负载很高

**Comment by 1315861791** [comment]
这个是研发环境，没有定时任务，晚上服务器资源都空闲着。只跑这一个测试任务，我最不理解的就是这个导入速度不稳定。
