### ISSUE TITLE
类似vertex-edge-vertex的查询语句无法获取后一个vertex的properties

### ISSUE THREAD

**Issue by aiyongyyy** [hugegraph/hugegraph#595]
hugegrpah 0.9.2  版本  后端存储是cassandra
查询 vertex-edge-vertex 的语句，例如
g.V().as('a').bothE().as('b'),otherV().as('c').select('a', 'b', 'c') 
无法获取'c' 的properties属性
使用的是 gremlin的java api
hugeClient.gremlin().execute()方法，在studio中执行语句也无法在data中获取‘c' 的properties

类似 vertex-edge-vertex的gremlin语句都发现有后一个vertex无法得到properties的情况，
而如果不查询edge，查询vertex-vertex，例如g.V().as('a').both().as('b').select('a','b') 就没有这个情况

想问一下有没有办法可以解决，多谢了

后来发现 hugegraph 0.8 版本是正常的

**Comment by javeme** [comment]
@aiyongyyy 多谢反馈，我们会进行定位分析，并给出解决办法。
