### ISSUE TITLE
使用gremlin语言清空图中的数据，然而库中的数据并没有真正的删除

### ISSUE THREAD

**Issue by lixiaobiao** [hugegraph/hugegraph#599]
###  执行的操作
1、rocksdb存储后端
2、执行：
{"gremlin": "hugegraph.clearBackend(); hugegraph.initBackend()","bindings": {}, "language": "gremlin-groovy", "aliases": {"g":"__g_hugegraph"}}
3、查看服务器中的图数据的存储路径中，数据是否clear

### Expected behavior 期望表现
使用gremlin语言清空图数据后，相应的服务器中的相关数据也应该清空

### Actual behavior 实际表现
执行gremlin语言后，使用时确实图显示数据为空。然而图的数据仍然保存在服务器中，占用存储空间。

**Comment by javeme** [comment]
@lixiaobiao rocksdb的clear数据会在6小时周期或重启的时候被真正的删除。
