### ISSUE TITLE
最新的hugestudio7 无法下载

### ISSUE THREAD

**Issue by bigdata-eqxiu** [hugegraph/hugegraph#6]
请问在那里可以下载最新hugestudio7

**Comment by javeme** [comment]
仓库已更新，hugegraph-studio v0.7下载地址：[hugegraph-studio-0.7.0.tar.gz ](https://github.com/hugegraph/hugegraph-studio/releases/download/v0.7.0/hugegraph-studio-0.7.0.tar.gz)。谢谢
