### ISSUE TITLE
RocksDB后端的内存消耗统计不准确

### ISSUE THREAD

**Issue by zhoney** [hugegraph/hugegraph#602]
### Actual behavior 实际表现

hugegraph后端存储是RocksDB时，

1. `top`和`ps`看到的HugeGraphServer进程使用的物理内存是51GB
2. `metrics/system/` API返回堆内存总共13GB，已使用8GB，空闲5GB
3. `/metrics/backend` API返回已使用内存是26GB

1和2中的统计都是准确的，所以`/metrics/backend` API统计的RocksDB内存占用少了
`12GB = 51GB - 13GB - 26GB`

### Steps to reproduce the problem 复现步骤

使用loader持续导入数据达10亿（9亿边，5000万顶点）

### Specifications of environment 环境信息
- hugegraph version: 0.9.2
- operating system: centos 6.3， 32 core，198GB memory
- hugegraph backend: RocksDB，所有日志数据都使用同一块机械盘2.7TB

**Comment by javeme** [comment]
@kidleaf-jiang 请提交pr到这个issue
