### ISSUE TITLE
hugegraph-loader 对同一类点再次导入时有新增属性会报错

### ISSUE THREAD

**Issue by 1315861791** [hugegraph/hugegraph#605]
![image](https://user-images.githubusercontent.com/24642133/60806352-55ac0480-a1b5-11e9-9eb0-6e71a2f7d4de.png)
我第一次导入的时候正常，第二次导入的时候新增了“地址”属性，然后就报错了，求大神指点。如果把库清空再导入就能成功

**Comment by suesunss** [comment]
@1315861791 请详细说下你的 schema 是怎么建立的，**地址**属性是如何append 上去的，一般这种情况可能的原因是地址属性没有建立，或者新增的地址属性和之前导入的数据不兼容。

**Comment by 1315861791** [comment]
> @ 1315861791请详细说下你的架构是怎么建立的，**地址**属性是如何追加上去的，一般这种情况可能的原因是地址属性没有建立，或者新增的地址属性和之前导入的数据不兼容。
谢谢兄台相助，搞定了。是我创建schema文件的时候用了.ifNotExist().create()，而不是append
