### ISSUE TITLE
RocksDB压缩算法如何配置

### ISSUE THREAD

**Issue by wanghiver** [hugegraph/hugegraph#606]
registerBackends()设置缺省为snappy。在hugegraph.properties中添加rocksdb.compression，会提示config option is redundant。请问要怎样设置呢？谢谢！

**Comment by javeme** [comment]
@wanghiver 分两种情况：

一、目前0.9及之前版本，请使用如下配置项设置压缩：`rocksdb.compression_type`，详细请参考[config-option文档](https://hugegraph.github.io/hugegraph-doc/config/config-option.html)。

二、后续0.10版本可以使用如下配置项设置压缩：
1. 大部分场景使用，适用于所有层：`rocksdb.compression`
2. 也可以使用这个来设置各层的压缩方式（第1个将会失效）：`rocksdb.compression_per_level`
3. 还可以单独设置最外层压缩方式（若设置则最优先使用）：`rocksdb.bottommost_compression`

**Comment by wanghiver** [comment]
谢谢！
