### ISSUE TITLE
关于gremlin设置limit后结果不正确问题

### ISSUE THREAD

**Issue by pengjianbo** [hugegraph/hugegraph#608]
* limit设置为10000时，查询不到结果
![image](https://user-images.githubusercontent.com/3264712/61041351-b4b38880-a404-11e9-8f77-83105ca54fcf.png)
* limit设置20000时可以查到结果
![image](https://user-images.githubusercontent.com/3264712/61041445-e6c4ea80-a404-11e9-81c8-13b15cca6cca.png)

前1w条数据是我删掉了的，按理来说我删掉了1w条后继续查询的话也能返回数据才对

**Comment by javeme** [comment]
@pengjianbo 感谢反馈，可以把环境信息贴一下吗？包括后端类型、数据量大小、索引建立情况等。

**Comment by pengjianbo** [comment]
@javeme `createTime`属性我是加了所以的，后端数据库时hbase，顶点数20亿左右，边50亿左右。我发现是has+limit组合就会有这个问题的，而`g.V().where(__.values('createTime').is(lt(1531531531531))).limit(10000).id()`是没有问题的，但是where+limit组合结果数量小于指定limit数量时会报500错误。如下图所示：
![image](https://user-images.githubusercontent.com/3264712/61194839-ccd22300-a6f6-11e9-881d-00c17a9b4720.png)

**Comment by javeme** [comment]
@pengjianbo 我这边尝试了v0.9.2 hugegraph + hbase，但是并未复现。可能的话提供一下复现流程。
```java
        schema.propertyKey("name").asText().create();
        schema.propertyKey("timestamp").asDate().create();

        schema.vertexLabel("reviewer").properties("name", "timestamp")
              .primaryKeys("name").create();
        schema.indexLabel("reviewerByTimestamp").onV("reviewer")
              .by("timestamp").range().create();

        long now = System.currentTimeMillis();
        for (int i = 0; i < 20000; i++) {
            graph.addVertex(T.label, "reviewer", "name", "r-" + i,
                            "timestamp", now + i);
            if (i % 500 == 0) {
                graph.tx().commit();
            }
        }
```

第一次查询数量：
```
// 14313
g.V().has('timestamp', inside('2019-07-15 17:35:01', '2019-07-15 17:35:20')).count()
```
删除1w个：
```
// drop 1w
g.V().has('timestamp', inside('2019-07-15 17:35:01', '2019-07-15 17:35:20')).limit(10000).drop()
```
再次查询数量（正常的话预期返回4313，如果复现的话预期返回0）：
```
// 4313
g.V().has('timestamp', inside('2019-07-15 17:35:01', '2019-07-15 17:35:20')).limit(10000).count()
```

**Comment by pengjianbo** [comment]
@javeme `timestamp`属性定义的是时间戳`schema.propertyKey("timestamp").asLong().create();`

我的语句：
```
g.V().where(__.values('createTime').is(lt(1531531531531))).limit(10000).id()
```
这里前面加上了where，按我的这样的写法试下。这个问题在我这边是必现

**Comment by pengjianbo** [comment]
附加：
这样的语句也会报500异常。
![image](https://user-images.githubusercontent.com/3264712/61216476-07ac7900-a740-11e9-9e23-48d1e018ef9a.png)

**Comment by javeme** [comment]
@pengjianbo 微信联系我也OK，where语句报错是预期的，我们也不建议使用where而建议使用has进行条件过滤，后者更加高效。
