### ISSUE TITLE
请问HugeClient有必要做一个连接池吗

### ISSUE THREAD

**Issue by 1315861791** [hugegraph/hugegraph#609]
测试的时候我在静态代码块中创建了client，上生产的时候有必要实现一个连接池吗？
![image](https://user-images.githubusercontent.com/24642133/61105125-88067c00-a4ab-11e9-867e-6c58e6482463.png)

**Comment by imbajin** [comment]
如果是说发送HTTP请求的连接池, client内置的`http-server`内部已有, 构造函数也对应有参数配置, 可以参考[HugeClient代码](https://github.com/hugegraph/hugegraph-client/blob/df4a54847fa75f4d9028027de229cded58924eb1/src/main/java/com/baidu/hugegraph/driver/HugeClient.java#L87), 可以通过观察client启动后对应的网络连接数确定是否符合预期.

如果是申请多个不同的HugeClient对象, 似乎也没必要放一起管理(这时候可能类似开多个Hugegraph-Loader了)

**Comment by 1315861791** [comment]
好的，谢谢。
