### ISSUE TITLE
一条查询的response time如何获取

### ISSUE THREAD

**Issue by DoubleDue** [hugegraph/hugegraph#615]
提供的例如shortest path的查询方式，查询结果中没有返回时间，要在哪里看呀，谢谢

**Comment by javeme** [comment]
@DoubleDue 查询结果中不包含返回时间的，查询时间cost如果想统计的话，需要调用方自己在调用前后获取时间差。

**Comment by DoubleDue** [comment]
感谢及时回复，我通过curl +http请求的方式获得的响应时间应该也可以吧

**Comment by javeme** [comment]
@DoubleDue 可以的。
不过curl请求会每次建立TCP连接需要耗费不少时间，如果需要衡量精确的请求时间建议使用client或连接池进行测试。
