### ISSUE TITLE
hugegraph说的是属性作为一条边来存储，为什么节点里面还有个字段存储了所有的节点属性呀

### ISSUE THREAD

**Issue by DoubleDue** [hugegraph/hugegraph#619]
请问是否支持单机的hbase作为backend呀

**Comment by DoubleDue** [comment]
hugegraph说的是属性作为一条边来存储，为什么节点里面还有个字段存储了所有的节点属性呀，我看最后有个properties,里面存了属性的json字符串

**Comment by imbajin** [comment]
1. 支持的, 或者说这其实是问`Hbase`是否支持单点模式. 图这层主要是一个接口层.
2. 如果是说的官方文档里[这段内容](https://hugegraph.github.io/hugegraph-doc/guides/desgin-concept.html#1-property-graph), 那是因为这应该是之前的设计图. 后面还没有更新, 所以可以不用在意文档里的说法. 目前Hbase存储时边的属性是被整合在一起存的.
