### ISSUE TITLE
huge-server服务JVM参数支持可配吗

### ISSUE THREAD

**Issue by hklmuaqmn** [hugegraph/hugegraph#62]
huge-server服务JVM参数支持可配吗?检查配置文件貌似没看到可以配置的地方

**Comment by javeme** [comment]
@hklmuaqmn HugeGraph-Server JVM参数可以配置的：解压tar包后，修改脚本`bin/hugegraph-server.sh`中`JAVA_OPTIONS`的值即可。

**Comment by zhoney** [comment]
Close this issue now due to having not been updated in a long time. Feel free to reopen it if needed.
