### ISSUE TITLE
name&graph搜索结果展示有误

### ISSUE THREAD

**Issue by renpingguo** [hugegraph/hugegraph#623]
### Expected behavior 期望表现
{type something here...}展示相应搜索结果

### Actual behavior 实际表现
{type something here...}name&graph搜索结果均展示全部

### Steps to reproduce the problem 复现步骤
1. {step 1}http://cp01-sjws-dx074.cp01.baidu.com:8181/api/v1.1/graph-connections?content=testGraphV3
2. {step 2}http://cp01-sjws-dx074.cp01.baidu.com:8181/api/v1.1/graph-connections?content=test4
3. {step 3}查看搜索展示内容

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by lixiaobiao** [comment]
this question is migrated to "https://github.com/hugegraph/hugegraph-hubble/issues/"
