### ISSUE TITLE
麻烦问一下：百度知心用到hugegraph了吗？

### ISSUE THREAD

**Issue by 1315861791** [hugegraph/hugegraph#625]
如题，用hugegraph建好了图之后不知道如何实现推理，还望大神指点。

**Comment by javeme** [comment]
@1315861791 关于图推理，最简单的理解就是”按图索骥“方式比如2层关联关系查询，另外还可以是更加复杂的分析：比如路径分析、特征匹配、Rank排名分析、中心性分析、团伙发现等等。hugegraph在技术上已经提供了比较丰富而通用的方法，具体业务可根据需求来定使用哪种或组合多种分析方法即可，业务不方便公开讨论的话也可以前往HugeGraph公众号取得联系。

**Comment by 1315861791** [comment]
好的，谢谢

**Comment by 1315861791** [comment]
我是想在图上通过推理，实现任何两个人的亲戚关系（姥姥，表哥）这种复杂的多度的人物关系推理，没什么思路，就想学习下用hugegraph如何做深层/隐藏关系推理。
