### ISSUE TITLE
支撑clickhouse

### ISSUE THREAD

**Issue by cmdares** [hugegraph/hugegraph#626]
clickhouse数据导入和查询性能非常强悍，可否针对大数据场景，兼容clickhouse，既然像palo这样的引擎能够对接，相信使用clickhouse作为后端，应该问题不是太大。
感谢！

**Comment by javeme** [comment]
@cmdares 感谢你的反馈，可行性上来说支持clickhouse应该没什么问题，但是目前排期实在比较紧张。如果你那边有强烈的意愿来贡献代码、推动这个事情，我们会提供最大的支持，包括流程指导、设计讨论、代码Review、测试等。期待~

**Comment by caosuwenwu** [comment]
@javeme hi, 我这边自己根据mysql, 去增加了对clickhouse的支持，但是遇到一些问题，可以请教你
1、版本0.10.4
2、问题，对于clickhouse对于delete不支持或者不友好，例如启动server时，delete 操作s_si表，该有什么其他替代办法，不让删数据，或者让更新，或者放内存处理之类
3、对于初始化initStore 有27张表，这个表之间或者表作用还是理解不够，希望解惑一下
期待你恢复

**Comment by javeme** [comment]
@caosuwenwu 分别解答如下：

> 对于clickhouse对于delete不支持或者不友好

不是很理解clickhouse不友好的地方，是否有具体例子呢？

> 例如启动server时，delete 操作s_si表

启动HugeGraph Server的时候，是不会有delete任何表操作的，仅在clear操作才会truncate表。

> 对于初始化initStore 有27张表，这个表之间或者表作用还是理解不够，希望解惑一下

主要包括元数据表m、数据表g、系统表s，数据表中包括顶点、边、索引等表，索引分为二级索引、范围索引、全文索引等。

**Comment by caosuwenwu** [comment]
@javeme  感谢你的回复
1、之前delete 操作，是初始化表结构没有改好，启动时候影响
2、不友好，是因为clickhouse 的delete 和update，写法alter table xxx update/delete
3、按照mysql基础上修改还是有些问题，a,对于元数据表c, vl操作,主要vl操作用~task任务更新时replace into 覆盖的数据，clickhouse没有
b.事务ck不支持，能有不用预处理的方式，是不是继承AbstractTransaction，重写方法？，这样是不是a也可以解决？
如有错误理解，还望指出

**Comment by javeme** [comment]
@caosuwenwu 应该不需要改动那么大，具体代码可以参考postgresql继承mysql的实现： hugegraph-postgresql/src/main/java/com/baidu/hugegraph/backend/store/postgresql/PostgresqlTable.java

**Comment by caosuwenwu** [comment]
@javeme  好的。还再请教个问题，关于s_si 这个表是干什么的，初始化27张表具体每个表的作用，字段含义有没有文档？
