### ISSUE TITLE
二级索引问题

### ISSUE THREAD

**Issue by cmdares** [hugegraph/hugegraph#627]
能否解释下目前HugeGraph的二级索引的机制，比如我想查询条件是：
字段A in(1,2,3) and 字段B>30 and 字段B<50 and 字段C在某个时间范围内出现对象的X(节点）的一跳关系网络中，关联的节点类型=Y的节点，能够和X组成环路的所有子图。
该查询分析中会利用到多个属性做与的过滤，不知针对当前版本的图库能否提供二级索引的高效查找，比如X节点数据量在数十亿。
按照常规的大数据建设方法，这些二级索引基本都是在es中，gremlin逻辑可以拆解成
1、先上es去查找多条件的X
2、使用hbase并发去查找X的一条关系网络（含下推过滤类别过滤出Y节点和相应的边）
3、使用图相关的算法逻辑寻找环形节点和边
类似这个问题，如何高效求解，希望社区能够给出一个合理的方法。
期待能够通过gremlin语句和逻辑简单的求解，同时希望性能有一定的优化。
感谢。

**Comment by javeme** [comment]
@cmdares 只需要hugegraph系统就可以高效完成上述场景的查询分析，你可以将具体要求说明一下，或者联系HugeGraph公众号讨论针对业务来讨论解决方案。
