### ISSUE TITLE
全文检索支持按相关性排序吗？

### ISSUE THREAD

**Issue by wslovenide** [hugegraph/hugegraph#630]
查询的语句入下:
g.V().has("user","nickname",Text.contains("老人与酒！")).limit(20).values("nickname")

期望命中 ”老人与酒“ 的这条数据排在第一位，单实际效果好像没有根据相关性排序，查询的结果入下：

["98年老人带你吃鸡","牧羊老人","海边老人爱吃鱼","养法斗的空巢老人","文艺老人","空巢老人^^","空巢老人mm","体力透支的老人","**老人与酒**！","98年的老人","🌸河畔老人🍃","时光老人it","快要入土的老人","空巣老人","老人与🐶","自闭老人","成长的老人","小老人","90后空巢老人#6460","空巢老人寻爱记"]

期望 ” 老人与酒“ 这个数据排在第一位

**Comment by javeme** [comment]
@wslovenide 目前还没有支持，不过会考虑支持的。请问一下是期望查询词匹配的程度越高排在越前面吗？

**Comment by wslovenide** [comment]
是的，是按照匹配程度排序
