### ISSUE TITLE
获取某个子图下边所有的顶点数量

### ISSUE THREAD

**Issue by YuiFn** [hugegraph/hugegraph#637]
查询某个子树下边的所有顶点数量，一个大节点，下边大概有100w个子节点，层级深度100，有没有办法能在秒级返回该节点下的所有订单数

**Comment by javeme** [comment]
@YuiFn 这种场景下100w查询理论上是需要分钟级。另外层级深度为何会100那么深？看起来是一个比较独特的场景。
