### ISSUE TITLE
hugegraph loader 使用jdbc模式url建议

### ISSUE THREAD

**Issue by 0xqq** [hugegraph/hugegraph#647]
### Expected behavior 期望表现
{type something here...}

### Actual behavior 实际表现
{type something here...}
{
    "vertices": [
        {
            "label": "person",
            "input": {
                "type": "jdbc",
                "driver":"com.mysql.cj.jdbc.Driver",
                "url":"jdbc:mysql://0.0.0.0:3306",
                "database":"xx",
                "table":"friend_v",
                "username":"xxx",
                "password":"xxx",
                "reconnect_max_times":0,
                "reconnect_interval":0,
                "batch_size":500
            }
        }
    ],
    "edges": [
        {
            "label": "friend",
            "source": ["source_id"],
            "target": ["target_id"],
            "input": {
                "type": "jdbc",
                "driver":"com.mysql.cj.jdbc.Driver",
                "url":"jdbc:mysql://0.0.0..0:3306",
                "database":"xxx",
                "table":"friend_e",
                "username":"xxx",
                "password":"xxxx",
                "reconnect_max_times":0,
                "reconnect_interval":0,
                "batch_size":500
            },
            "field_mapping": {
                "source_id": "id",
                "target_id": "id"
            }
        }
    ]
}
提示------
Wed Aug 14 15:57:19 CST 2019 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
建议url配置为 jdbc:mysql://localhost:3306/{db}?characterEncoding=utf-8&useSSL=false
### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by Linary** [comment]
@0xqq 出于对其他数据库的兼容，我们还是决定保持现有格式，以保证风格一致。
