### ISSUE TITLE
能在现有的节点上新增新的属性吗

### ISSUE THREAD

**Issue by wslovenide** [hugegraph/hugegraph#649]
怎么在已有的节点上添加新的属性字段？

**Comment by Linary** [comment]
先给该顶点的vertexlabel添加属性，然后获取到该顶点，执行更新属性操作即可。

示例，为已存在的某个person类型顶点添加新的属性xxx。

schema.vertexLabel("person").properties("xxx").append();

g.V('vid').property('xxx', 'value');

**Comment by wslovenide** [comment]
我在网页上执行:
schema.vertexLabel("person").properties("xxx").append();
报错：
Error!
No such property: schema for class: Script113

难道上面那个脚本不是在网页上执行的吗？
