### ISSUE TITLE
有没有能够限制hugegraph-server内存的地方,比如配置文件或者代码里面

### ISSUE THREAD

**Issue by fisherinbox** [hugegraph/hugegraph#65]
### Expected behavior 期望表现
能够自行限制server的内存

### Actual behavior 实际表现
{type something here...}

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by hklmuaqmn** [comment]
https://github.com/hugegraph/hugegraph/issues/62
 HugeGraph-Server JVM参数可以配置的：解压tar包后，修改脚本bin/hugegraph-server.sh中JAVA_OPTIONS的值即可。

**Comment by fisherinbox** [comment]
> #62
> HugeGraph-Server JVM参数可以配置的：解压tar包后，修改脚本bin/hugegraph-server.sh中JAVA_OPTIONS的值即可。

是MAX_MEM,MIN_MEM这两个参数吗
