### ISSUE TITLE
HugeGraph-Loader导入数据报错

### ISSUE THREAD

**Issue by 306495389li** [hugegraph/hugegraph#652]
### Expected behavior 期望表现
谁用HugeGraph-Loader导入数据，Boolean类型的数据有问题

### Actual behavior 实际表现
>>>> PARSE ERROR: The value 'true' can't convert to class class java.lang.Boolean with cardinality SINGLE
1|39309691526354826263|KFC_APP_SHARING1807|18795801091||2019-08-15 16:08:30.440|30|true|"[{\"rewardKey\":\"KCKFCMS226201807\",\"rewardName\":\"\",\"sendDate\":1565856510424,\"rewardType\":2}]"|False|

**Comment by Linary** [comment]
@306495389li 抱歉，这是一个BUG，已提交https://github.com/hugegraph/hugegraph-loader/pull/92
