### ISSUE TITLE
使用api的时候如果id有#号会异常

### ISSUE THREAD

**Issue by lftx1986** [hugegraph/hugegraph#656]
### Expected behavior 期望表现
{type something here...}
使用api进行相关分析

### Actual behavior 实际表现
{type something here...}
定点id是premarykey()自动构建的，id中带有#号使用api进行k-out的时候 报错，
The vertex id must be formatted as String or Number, but got 。。。
但是如果去掉#号就没有报错。

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by javeme** [comment]
@lftx1986 需要注意#号在URL中是特殊字符，如果作为内容需要转义为`%23`。
