### ISSUE TITLE
性能优化建议

### ISSUE THREAD

**Issue by linkerlin** [hugegraph/hugegraph#663]
https://github.com/hugegraph/hugegraph/blob/459c090e254d73fe0225cbc4568a7c6a2468862c/hugegraph-core/src/main/java/com/baidu/hugegraph/backend/cache/RamCache.java#L332

这里的values()换成entrySet()会好一些, 尤其是缓存很大的时候.

**Comment by javeme** [comment]
@linkerlin 感谢反馈，欢迎给HugeGraph[贡献代码](https://github.com/hugegraph/hugegraph/blob/master/CONTRIBUTING.md)
