### ISSUE TITLE
麻烦问下新版本啥时候发布

### ISSUE THREAD

**Issue by 1315861791** [hugegraph/hugegraph#666]
如题

**Comment by javeme** [comment]
@1315861791 预计v0.10版9月底发布。

**Comment by 1315861791** [comment]
新版本的引擎会支持分布式吗？去年的时候听说你们有这个计划。

**Comment by javeme** [comment]
@1315861791 v0.10依然只支持分布式存储、还不支持分布式的计算，目前主要是在完善OLTP功能。我们会尽快启动支持分布式计算，感谢关注。

**Comment by 1315861791** [comment]
非常期待新版本
