### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by linkerlin** [hugegraph/hugegraph#668]
https://github.com/hugegraph/hugegraph/blob/459c090e254d73fe0225cbc4568a7c6a2468862c/hugegraph-core/src/main/java/com/baidu/hugegraph/io/HugeGraphSONModule.java#L59
HugeGraphSONModule  >>> HugeGraphJSONModule

**Comment by Linary** [comment]
这个命名风格我们是参考了TinkerGraph
`org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerIoRegistry`
```
private TinkerIoRegistry() {
        register(GryoIo.class, TinkerGraph.class, new TinkerGraphGryoSerializer());
        register(GraphSONIo.class, null, new TinkerModule());
    }
```

`org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONIo`
