### ISSUE TITLE
最短路径不支持权重图吗？

### ISSUE THREAD

**Issue by 1315861791** [hugegraph/hugegraph#669]
![image](https://user-images.githubusercontent.com/24642133/63906097-0f528380-ca49-11e9-9a85-964bc02f354f.png)
计算最短路径的时候每条边的权重是不等价的，能不能选择边上的某个属性作为权重进行计算最短路径啦？

**Comment by javeme** [comment]
@1315861791 两点之间的带权重最短路径计算代价太高，所以目前还没有支持。可以考虑使用单点出发的权重路径实现：[3.2.8 Customized Paths](https://hugegraph.github.io/hugegraph-doc/clients/restful-api/traverser.html)

**Comment by 1315861791** [comment]
好的，谢谢

**Comment by 1315861791** [comment]
@javeme 麻烦问下有没有可以交流hugegraph的微信群或者QQ群啦？

**Comment by javeme** [comment]
@1315861791 可以关注`HugeGraph`微信公众号，联系管理员加入群。

**Comment by 1315861791** [comment]
公众号上的二维码已过期
