### ISSUE TITLE
restfulAPI-2.1.5 获取符合条件的顶点 查询不到

### ISSUE THREAD

**Issue by hungryforit** [hugegraph/hugegraph#672]
### Expected behavior 期望表现
给属性建立index后,根据属性查询vertex

### Actual behavior 实际表现
{type something here...}
http://ip:8080/graphs/hugegraphproindextest/graph/vertices?label=person&properties={"age":29}&limit=1
b'{"vertices":[]}'

### Steps to reproduce the problem 复现步骤
1. {根据restfulAPI 生成完全一样的数据}
2. {给属性建立索引也和restfulAPI的indexlabel一样}
3. {根据restfulAPI的‘2.1.5 获取符合条件的顶点’执行}

### Status of loaded data 数据状态
http://我的ip:8080/graphs/hugegraphproindextest/graph/vertices?label=person&properties={"age":29}&limit=1
b'{"vertices":[]}'

我自己的测试图数据 和 restful中每一步demo建立的图数据 这两个数据都测试了 根据属性获取顶点 返回都是b'{"vertices":[]}' 没有数据

**Comment by javeme** [comment]
@hungryforit 是在什么情况下出现的？是否有稳定的复现流程呢？我这边是没问题的：
![image](https://user-images.githubusercontent.com/9625821/64027064-918a9700-cb72-11e9-9112-49ff5353b414.png)

**Comment by hungryforit** [comment]
@javeme  我找到我错误的原因了,url中age属性的值,我给29就不好使,给“29”就好使.但是建立age属性时指定的数据类型是INT.......
 不过你那里是好使的兄弟.......
<img width="774" alt="屏幕快照 2019-08-31 下午11 49 17" src="https://user-images.githubusercontent.com/36147819/64066296-5bb8e180-cc4a-11e9-9716-6f2b1a718a5e.png">
<img width="597" alt="屏幕快照 2019-08-31 下午11 37 20" src="https://user-images.githubusercontent.com/36147819/64066307-873bcc00-cc4a-11e9-8092-e09a1772c42b.png">

**Comment by javeme** [comment]
@hungryforit 从结果看，age属性应该是Text类型的。看你截图数据类型是INT的貌似服务器地址不一样（localhost）。

**Comment by hungryforit** [comment]
@javeme 我确认了下 建模的时候确实写成了Text......属性查询结果:{"propertykeys": [{"id":4,"name":"age","data_type":"TEXT","cardinality":"SINGLE","properties":[],"user_data":{}},......]} 多谢
