### ISSUE TITLE
启动hugegraphServer报错:java.lang.IllegalStateException: Please wait for the server to initialize

### ISSUE THREAD

**Issue by hungryforit** [hugegraph/hugegraph#681]
### 前置环境
图库server已经运行了挺久了
后端是hbase
一直在用很多个图来回切换
<img width="503" alt="屏幕快照 2019-09-05 下午2 31 04" src="https://user-images.githubusercontent.com/36147819/64317280-cde24b00-cfe9-11e9-9196-520b0e272676.png">
一直都好使
### 问题产生前操作
昨天新配置了hugegraphwsyloop2test.properties这个图
init后
再重新启动server服务 log日志就报错了:
<img width="608" alt="屏幕快照 2019-09-05 下午2 27 42" src="https://user-images.githubusercontent.com/36147819/64317355-05e98e00-cfea-11e9-9eec-a6d86b861983.png">

### 尝试解决但无效:
重新init
重新启动server
依然报错

### 环境信息
0.HugeGraph-Server 0.8版本
1.hbase在HDFS的数据存储目录 的 数据量 是94208
<img width="384" alt="屏幕快照 2019-09-05 下午3 11 20" src="https://user-images.githubusercontent.com/36147819/64319763-ba39e300-cfef-11e9-95cc-b7826ff2d959.png">

#### 根据报错信息 没想到解决办法 搜索不到 期待帮助

**Comment by imbajin** [comment]
初始化过程相对是有一点慢的, 猜测有可能是没有初始化完全 
这时候再重新初始化只要标志位有就会跳过, 不能解决缺失部分元信息的问题.
可以尝试这样做:
1.  先剔除`hugegraphwsyloop2test`这个图,看server是否能正常启动其它, 如果能再尝试后续
2.  hbase-shell手动删除所有`hugegraphwsyloop2test`相关表.
3. 再重新初始化看看

**补充:**  检查一下配置变量, 包括是否是同一Hbase集群, 配置信息. 以及查看`hugegraphwsyloop2test` 这个namespace是否有相同数目的表等(貌似是18张)

**Comment by hungryforit** [comment]
@imbajin  我觉得你思路很好,在你回复之前,我刚刚用hbase-shell干掉了hugegraph所有图的所有的表.....没想到先干掉hugegraphwsyloop2test图的数据试试......(现在来不及了......) ; 删掉了数据,重新init,启动server 就成功了  多谢
