### ISSUE TITLE
请问使用 Spark 查询的时候是否先要有 ETL 把数据导入到 hdfs ？

### ISSUE THREAD

**Issue by yetingsky** [hugegraph/hugegraph#685]
### Expected behavior 期望表现
{type something here...}

请问使用 Spark 查询的时候是否先要有 ETL 把数据导入到 hdfs ？

### Actual behavior 实际表现
{type something here...}

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by javeme** [comment]
> 请问使用 Spark 查询的时候是否先要有 ETL 把数据导入到 hdfs ？

@yetingsky 不用的，hugegraph里面已经是图了。ETL的过程是在数据导入到hugegraph的过程中，由[hugegraph-loader](https://hugegraph.github.io/hugegraph-doc/quickstart/hugegraph-loader.html)完成的。

**Comment by yetingsky** [comment]
也就是 spark 直接通过 hugegraph api 取的数据？如果 hugegraph 的后端存储是 rocksdb 或者 MySQL，扛得住吗？还是说推荐再把数据导入到 hdfs。
