### ISSUE TITLE
HugeGraph-Studio如何通过配置连接多图

### ISSUE THREAD

**Issue by chobits102** [hugegraph/hugegraph#687]
HugeGraph-Studio如何通过配置连接多图

**Comment by javeme** [comment]
@chobits102 HugeGraph-Studio只能连接单个图。不过即将要发布新版的前端界面HugeGraph-Hubble，是支持连接多个图的，并且拥有更加丰富的功能。

**Comment by chobits102** [comment]
> @ chobits102 HugeGraph-Studio只能连接单个图。不过即将要发布新版的前端界面HugeGraph-Hubble，是支持连接多个图的，并且拥有更多丰富的功能。

谢谢
