### ISSUE TITLE
Windows环境下运行hugegraph-master中的Example1时报错，rocksdb无法启动

### ISSUE THREAD

**Issue by JimmyXiaodong** [hugegraph/hugegraph#690]
### Expected behavior 期望表现
Opening backend store 'rocksdb' for graph 'hugegraph'

### Actual behavior 实际表现
 Failed to open RocksDB '.\m'
![image](https://user-images.githubusercontent.com/11945318/64939274-107e1000-d893-11e9-88aa-8a7598f043d7.png)
但可以使用 Column Families方式成功启动rocksdb

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {Windows 10}
- hugegraph backend: {rocksdb}

**Comment by JimmyXiaodong** [comment]
通过在com/baidu/hugegraph/backend/store/rocksdb/RocksDBOptions.java 的LEVELS_COMPRESSIONS常量中将压缩方法全部设置为none可以解决。能不能在hugegraph.properties开放rocksdb.compression_per_level，rocksdb.bottommost_compression，rocksdb.compression配置选项？

**Comment by javeme** [comment]
@JimmyXiaodong 这些配置项可以在hugegraph.properties进行设置的，添加上即可（默认没有）。
