### ISSUE TITLE
麻烦请教下图中的点和边如何控制用户操作权限？

### ISSUE THREAD

**Issue by 1315861791** [hugegraph/hugegraph#692]
我有这样一个需求，请教下大神如何实现：
每个用户导入到hugegraph中的点和边是私有的，只有他自己能看得到，但他可以选择共享为公有数据，让所有人都能看到，或者共享给某些用户。这种细粒度的权限该如何控制啦？

**Comment by javeme** [comment]
@1315861791 是精确到某类顶点/边Label还是精确到某一个顶点/边？

**Comment by javeme** [comment]
一般来说，可以基于角色的控制做粗粒度权限，细粒度则需要使用基于资源的控制，比如用户bob拥有movie类顶点的读权限，可以在用户上分配资源的权限（可以使用多层抽象比如权限组）；如果需要具体到一个顶点，比如读电影【阿甘正传】的权限，那么可以在顶点属性上存用户的权限信息，如property_permissions: {user1: read, user2: read, user3: update, user4: delete}

**Comment by 1315861791** [comment]
明白了，非常感谢！
