### ISSUE TITLE
建立节点的时候，primarykey中有特殊字符返回的id会出现问题

### ISSUE THREAD

**Issue by bdlddn** [hugegraph/hugegraph#699]
### Expected behavior 期望表现
   建立节点的时候，primarykey中有特殊字符时（比如 !和:）返回的id会再这些特殊字符前增加`符号。比如建立域名顶点，primarykey为www.baidu.com!，我希望数据库给我返回的id为n:www.baidu.com!

而实际数据库给我返回的id是n:www.baidu.com`!
请问是数据库对这些特殊字符这样处理是有什么特殊考虑么，是否能够设置id能够向我期望的那样。

### Specifications of environment 环境信息
- hugegraph version: v0.9.2
- operating system: ubuntu
- hugegraph backend: rockdb

**Comment by imbajin** [comment]
先说结论, 你说的`!`正好是**多个主键**的分隔符,  所以会被替换处理, 以免冲突, 这就好比多个字段间总要有分隔符号, 而分隔符难免在某些场景会有冲突. 

解决办法我只想到后续可考虑把这种点边ID的分隔符也抽取出来让用户可以自定义?

---
以下是之前笔记里的举例分析: 
```c
// 假设是导入点, 导入时会对主键做如下处理
// 第一列是原始数据值, 第二列是中间处理值, 第三列是最后vertexID值
   1. jin --> jin! --> 1:jin
   2. ji:n --> ji`:n! --> 1:ji`:n (同理!也会被转为`!)
   3. jin + HK --> jin!HK! --> 1:jin!HK  (联合主键,比如姓名+城市, 此时!分隔多主键)
```

需要注意的是: 在**边的id**解析的时候,`和> 两个字符也会作为分隔符标识, 容易有冲突, 所以点ID里最好也别在**末尾**出现这种字符, 详细可以参考源码, 这里是用正则的零宽断言来判断的..
```bash
# 以下断言的含义是,匹配 > ,但不匹配 `>
(?<!`)>

# 比如边ID:
a>b>c  -->  a b c  # 切为3个
a`>b>c -->  a`>b  c  # 切为2个,这时候`>不会被匹配, 边ID就会错误切分(报错)
a>>b>c --> a _ b c # 切为4个, 第二个是空字符, 同样不能得到a>这个整体
```

**Comment by bdlddn** [comment]
好的明白了，除了!、:、>，`之外还有哪些字符在primarykey中会有特殊处理呢？

**Comment by imbajin** [comment]
> 好的明白了，除了!、:、>，`之外还有哪些字符在primarykey中会有特殊处理呢？

目前**印象里**似乎就这些, >和`只是不能直接出现在尾部, 中间是可以的, 你可以看看相关地方代码处理逻辑, 这个也不一定一直不变的
