### ISSUE TITLE
init的时候报错：init是报Could not find or load main class .root.hugegraph-0.7.4.lib.hugegraph-dist-0.7.4-javadoc.jar

### ISSUE THREAD

**Issue by Jerrick** [hugegraph/hugegraph#7]
sh bin/init-store.sh
Initing HugeGraph Store...
Error: Could not find or load main class .root.hugegraph-0.7.4.lib.hugegraph-dist-0.7.4-javadoc.jar

可以通过修改 bin/init-store.sh倒数第二行	
exec $JAVA -cp $LIB   -->  exec $JAVA -cp $CLASSPATH:$LIB 

来解决

**Comment by zhoney** [comment]
已经发布了新的0.7版本的tar包，该问题已经解决
