### ISSUE TITLE
官网例子中useAutomaticId()和primaryKeys()可以同时使用，但实际操作中为啥会报错

### ISSUE THREAD

**Issue by 1315861791** [hugegraph/hugegraph#707]
![image](https://user-images.githubusercontent.com/24642133/66472686-5f991880-eac0-11e9-8a78-cae9f790d1ab.png)

**Comment by chobits102** [comment]
以新版本的hg loader里面的例子为准

**Comment by Linary** [comment]
@1315861791 抱歉，文档有误。
