### ISSUE TITLE
通过RESTful API获取顶点 Shards 列表只返回一条数据问题

### ISSUE THREAD

**Issue by pengjianbo** [hugegraph/hugegraph#712]
图库中有5亿的顶点2亿的边，约30GB的数据，通过RESTful API获取到的shards信息只有一个。把split_size参数调小也是如此。
![cnet2](https://user-images.githubusercontent.com/3264712/67075277-6e1cb980-f1bd-11e9-9548-0993c45cd411.png)
通过微信上跟@javeme 大佬沟通了下，叫我用代码直接连hbase看看getRegionMetrics和getStoreFileSize返回值。执行结果如下（单位MB）：
![cnet](https://user-images.githubusercontent.com/3264712/67075726-53971000-f1be-11e9-8ebe-50d358d28e4b.png)

**在开始组大网的时候hbase上region只有一个，然后我手动对表region进行了分裂及major_compat操作，会不会是因为我的这个操作引起的问题？**

* HBase版本：2.1.0-cdh6.1.0

**Comment by imbajin** [comment]
问题可以复现, 我抽空看看~

**Comment by imbajin** [comment]
刚跟了一下, 问题原因很简单, 就是Hbase2这里接口默认返回的fileSize是`MB`为单位, 而图切分shard的时候用的`byte` 为单位, 所以相除基本都是0了.

如果急着用的话, 可以用[Arthas](https://alibaba.github.io/arthas/install-detail.html)直接改一下[这三行代码](https://github.com/hugegraph/hugegraph/pull/713/files)就行, 也很方便~
```bash
# 三板斧, 写了个参考
$ sc  -d *HbaseSessions # 获取classLoaderHash
$ mc -c 18b4aac2 /tmp/HbaseSessions.java -d /tmp  # 建议在本地改好丢服务器下,jad代码多容易出错
$ redefine /tmp/com/baidu/hugegraph/backend/store/hbase/HbaseSessions.class
```
---

题外话:
分享一下个人心得, 图的这种细节问题都可以优先用Arthas来定位, 这样基本不用多写代码, 而且熟悉使用之后发现问题的速度也挺快的
比如我的排查思路就是先从代码找到`shard-api`接口在调hbase-client这层之前的地方, 发现在`HbaseSessions`类的`storeSize`方法, 那么打开Arthas, 连上server进程. 这样写就行了
```bash
$ watch *HbaseSessions storeSize '{params[0],returnObj}' -n 5
Press Q or Ctrl+C to abort.
Affect(class-cnt:1 , method-cnt:1) cost in 172 ms.
ts=2019-10-18 21:33:21; [cost=33.789464ms] result=@ArrayList[
    @String[graph_v],   # 函数入参值
    @Long[92733],   # 函数返回值
]
```
然后如果要更细的信息, 加日志也可以参考上面`mc/redefine`的三板斧临时加一下日志观察, 这样排错体验/性能问题分析会好很多 ~

**Comment by pengjianbo** [comment]
@imbajin 大神，可以帮我改下编译一个jar包给我试试吗。hugegraph 0.9.2版的

**Comment by imbajin** [comment]
周末没有开发环境... 但就用我上面说的方法很快的, 一分钟就搞定了... 比重新编译简单多了

如果想永久生效, 也不需要编译代码, 把原有jar包里面`HbaseSessions.class`替换一下就行了, 也不需要你去下源码的.

我把前面的步骤再补充一下...
```bash
# 1. 服务端下载这个类的0.9.2的源码
wget -P /tmp https://raw.githubusercontent.com/hugegraph/hugegraph/release-0.9/hugegraph-hbase/src/main/java/com/baidu/hugegraph/backend/store/hbase/HbaseSessions.java

# 2. 下载启动Arthas
wget https://alibaba.github.io/arthas/arthas-boot.jar && java -jar arthas-boot.jar

# 3. 修改一下源码那两行, 按上面的方式mc编译, 然后redefine覆盖加载当前jvm中.
# 或者直接把编译好的class文件替换你原有jar包里对应的class文件. 重新启动就是.
```
> 最后... 我是大菜  .... 你才是大神呀 :godmode:

**Comment by pengjianbo** [comment]
@imbajin 好的。感谢

**Comment by pengjianbo** [comment]
@imbajin 按照你说的方法改确实可以了。@javeme 新版hugegraph上会修复这个问题吧

**Comment by javeme** [comment]
@pengjianbo v0.10就会修复该问题的
