### ISSUE TITLE
图用久了速度变慢

### ISSUE THREAD

**Issue by 306495389li** [hugegraph/hugegraph#715]
### Expected behavior 期望表现
希望可以查询速度一直快

### Actual behavior 实际表现
现在因为经常有图数据新增，所以用了一段时间图就变慢了，有什么优化的办法
如果想删除索引重新创建要怎么操作，我见studo不支持删除
#### Vertex/Edge summary 数据量
有130w左右的数据

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: 0.10.0
- operating system: 32G内存
- hugegraph backend: mysql

**Comment by javeme** [comment]
@306495389li 理论上是不会变慢的，需要具体分析。是否有经常删除数据呢？这个往往会导致墓碑过多变慢。
重建索引请参考[rebuild API](https://hugegraph.github.io/hugegraph-doc/clients/restful-api/rebuild.html)，删除索引的代价是非常高的，特别是在数据量过亿的时候。

**Comment by 306495389li** [comment]
@javeme 没有删除，会有数据新增和关系重建，大约1周时间就会变慢，重启图速度会重新变快，大约有140W的数据量，重建索引会要耗时多久

**Comment by javeme** [comment]
@306495389li 变慢原因需要具体分析，可以检查一下变慢时内存使用情况。

**Comment by 306495389li** [comment]
@javeme 上次变慢的时候查看系统还有10G的内存没有使用，如果是内存问题的话会报错，这次不报错，就是越来越慢，我们是粉拉粉系统，会经常有新数据进入，目前该图有80多w的点，关系为1对多

**Comment by javeme** [comment]
@306495389li 可以收集一下如下信息：
JVM分配的最大内存是多少？ 
另外，在变慢的时候，查看一下内存使用量和GC压力。

- 查看内存限额：
 `ps -ef | grep HugeGraphServer | grep Xmx`  或者  `jinfo {PID}`
 
- 查看内存使用：
 `jmap -heap {PID}`
 
- 查看GC压力：
 `jstat -gcutil {PID} 1000 10`

**Comment by 306495389li** [comment]
@javeme 
这个前两天重启过,服务器32G装了mysql和图，目前不慢
jinfo {PID}
VM Flags:
Non-default VM flags: -XX:CICompilerCount=4 -XX:InitialHeapSize=536870912 -XX:MaxHeapSize=13140754432 -XX:MaxNewSize=4379901952 -XX:MinHeapDeltaBytes=524288 -XX:NewSize=178782208 -XX:OldSize=358088704 -XX:+UseCompressedClassPointers -XX:+UseCompressedOops -XX:+UseFastUnorderedTimeStamps -XX:+UseParallelGC 
Command line:  -Dname=HugeGraphServer -Dlog4j.configurationFile=/opt/hugegraph/hugegraph-0.10.2/conf/log4j2.xml -Djava.security.manager=com.baidu.hugegraph.security.HugeSecurityManager -Xms512m -Xmx12532m -javaagent:/opt/hugegraph/hugegraph-0.10.2/lib/jamm-0.3.0.jar
jmap -heap
Debugger attached successfully.
Server compiler detected.
JVM version is 25.111-b14

using thread-local object allocation.
Parallel GC with 8 thread(s)

Heap Configuration:
   MinHeapFreeRatio         = 0
   MaxHeapFreeRatio         = 100
   MaxHeapSize              = 13140754432 (12532.0MB)
   NewSize                  = 178782208 (170.5MB)
   MaxNewSize               = 4379901952 (4177.0MB)
   OldSize                  = 358088704 (341.5MB)
   NewRatio                 = 2
   SurvivorRatio            = 8
   MetaspaceSize            = 21807104 (20.796875MB)
   CompressedClassSpaceSize = 1073741824 (1024.0MB)
   MaxMetaspaceSize         = 17592186044415 MB
   G1HeapRegionSize         = 0 (0.0MB)

Heap Usage:
PS Young Generation
Eden Space:
   capacity = 903348224 (861.5MB)
   used     = 175343592 (167.2206802368164MB)
   free     = 728004632 (694.2793197631836MB)
   19.410409777924134% used
From Space:
   capacity = 88080384 (84.0MB)
   used     = 87771952 (83.70585632324219MB)
   free     = 308432 (0.2941436767578125MB)
   99.6498289562407% used
To Space:
   capacity = 509607936 (486.0MB)
   used     = 0 (0.0MB)
   free     = 509607936 (486.0MB)
   0.0% used
PS Old Generation
   capacity = 2123890688 (2025.5MB)
   used     = 1280687472 (1221.3587493896484MB)
   free     = 843203216 (804.1412506103516MB)
   60.299123643033745% used

30901 interned Strings occupying 3982464 bytes

jstat -gcutil 5018 1000 10
  S0     S1     E      O      M     CCS    YGC     YGCT    FGC    FGCT     GCT   
  0.00  99.65  19.78  60.30  90.16  64.17     29    1.057     5    0.716    1.772
  0.00  99.65  19.78  60.30  90.16  64.17     29    1.057     5    0.716    1.772
  0.00  99.65  19.78  60.30  90.16  64.17     29    1.057     5    0.716    1.772
  0.00  99.65  19.78  60.30  90.16  64.17     29    1.057     5    0.716    1.772
  0.00  99.65  19.78  60.30  90.16  64.17     29    1.057     5    0.716    1.772
  0.00  99.65  19.78  60.30  90.16  64.17     29    1.057     5    0.716    1.772
  0.00  99.65  19.78  60.30  90.16  64.17     29    1.057     5    0.716    1.772
  0.00  99.65  19.78  60.30  90.16  64.17     29    1.057     5    0.716    1.772
  0.00  99.65  19.78  60.30  90.16  64.17     29    1.057     5    0.716    1.772
  0.00  99.65  19.78  60.30  90.16  64.17     29    1.057     5    0.716    1.772

**Comment by javeme** [comment]
@306495389li 收到，可以在变慢的时候再收集一次信息。

**Comment by 306495389li** [comment]
@javeme 好的，谢了，等变慢了我再发一次

**Comment by 306495389li** [comment]
现在又慢了
VM Flags:
Non-default VM flags: -XX:CICompilerCount=4 -XX:InitialHeapSize=536870912 -XX:MaxHeapSize=13140754432 -XX:MaxNewSize=4379901952 -XX:MinHeapDeltaBytes=524288 -XX:NewSize=178782208 -XX:OldSize=358088704 -XX:+UseCompressedClassPointers -XX:+UseCompressedOops -XX:+UseFastUnorderedTimeStamps -XX:+UseParallelGC 
Command line:  -Dname=HugeGraphServer -Dlog4j.configurationFile=/opt/hugegraph/hugegraph-0.10.2/conf/log4j2.xml -Djava.security.manager=com.baidu.hugegraph.security.HugeSecurityManager -Xms512m -Xmx12532m -javaagent:/opt/hugegraph/hugegraph-0.10.2/lib/jamm-0.3.0.jar
jmap -heap 5018
Attaching to process ID 5018, please wait...
Debugger attached successfully.
Server compiler detected.
JVM version is 25.111-b14

using thread-local object allocation.
Parallel GC with 8 thread(s)

Heap Configuration:
   MinHeapFreeRatio         = 0
   MaxHeapFreeRatio         = 100
   MaxHeapSize              = 13140754432 (12532.0MB)
   NewSize                  = 178782208 (170.5MB)
   MaxNewSize               = 4379901952 (4177.0MB)
   OldSize                  = 358088704 (341.5MB)
   NewRatio                 = 2
   SurvivorRatio            = 8
   MetaspaceSize            = 21807104 (20.796875MB)
   CompressedClassSpaceSize = 1073741824 (1024.0MB)
   MaxMetaspaceSize         = 17592186044415 MB
   G1HeapRegionSize         = 0 (0.0MB)

Heap Usage:
PS Young Generation
Eden Space:
   capacity = 1599078400 (1525.0MB)
   used     = 1490562136 (1421.5108261108398MB)
   free     = 108516264 (103.48917388916016MB)
   93.2138246630059% used
From Space:
   capacity = 734527488 (700.5MB)
   used     = 387611496 (369.6551284790039MB)
   free     = 346915992 (330.8448715209961MB)
   52.77018250949378% used
To Space:
   capacity = 715128832 (682.0MB)
   used     = 0 (0.0MB)
   free     = 715128832 (682.0MB)
   0.0% used
PS Old Generation
   capacity = 4622123008 (4408.0MB)
   used     = 3353889592 (3198.5183639526367MB)
   free     = 1268233416 (1209.4816360473633MB)
   72.56166887369865% used

 jstat -gcutil 5018 1000 10
  S0     S1     E      O      M     CCS    YGC     YGCT    FGC    FGCT     GCT   
  0.00  52.77  91.02  72.56  37.65  11.03    399   22.817    10    5.600   28.417
  0.00  52.77  91.02  72.56  37.65  11.03    399   22.817    10    5.600   28.417
  0.00  52.77  91.02  72.56  37.65  11.03    399   22.817    10    5.600   28.417
  0.00  52.77  91.02  72.56  37.65  11.03    399   22.817    10    5.600   28.417
  0.00  52.77  91.02  72.56  37.65  11.03    399   22.817    10    5.600   28.417
  0.00  52.77  91.02  72.56  37.65  11.03    399   22.817    10    5.600   28.417
  0.00  52.77  91.02  72.56  37.65  11.03    399   22.817    10    5.600   28.417
  0.00  52.77  91.02  72.56  37.65  11.03    399   22.817    10    5.600   28.417
  0.00  52.77  91.02  72.56  37.65  11.03    399   22.817    10    5.600   28.417
  0.00  52.77  91.02  72.56  37.65  11.03    399   22.817    10    5.600   28.417
