### ISSUE TITLE
请问在hugegraph中怎么使用Louvain算法？有API么？希望您能给出一个事例或者相关讲解网址，万分感谢，

### ISSUE THREAD

**Issue by ghost** [hugegraph/hugegraph#724]
### Expected behavior 期望表现
{type something here...}

### Actual behavior 实际表现
{type something here...}

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by javeme** [comment]
@oushu1wangyang1 目前hugegraph还还没有提供Louvain API，这个属于离线计算AP部分。

Louvain社区发现算法的原理还是比较易懂的，不过在大规模数据上性能优化较难。网上有不少Louvain讲解资料，这里我简单说下个人的理解：

- Louvain的核心思想是把一个点放到最适合它放的邻居社区中去，根据一个叫模块度的衡量指标，如果加入某个邻居能使得模块度变大则加入该邻居，如果多个邻居能使模块度变大则选一个最大的邻居加入，本质上是局部最优算法。模块度变化是指：一个点（或社区）和另一个社区相互独立时的模块度  与 它们合并为一个社区之后的模块度 之间的差值。模块度可以这么理解：社区内所有点连接的紧密程度 - 社区内的点与社区外的点连接程度。紧密程度可以简单理解为社区内部边的条数。
- 事实上最简单的社区发现算法LPA，也是通过各邻居给一个点投票来决定这个点划分到哪个社区。LPA优点是速度快。LPA缺点是没法控制社区的大小，并且票数相同时社区有随机性。
