### ISSUE TITLE
hugegraph0.10.4 因netty-all，初始化后端cassandra库失败

### ISSUE THREAD

**Issue by 0xqq** [hugegraph/hugegraph#734]
### Expected behavior 期望表现
{type something here...}
cassandra版本为3.11.5；hugegraph版本为0.10.4，在初始化cassandra后端库，发生错误。
如果用旧版本的netty-all-4.0.44.Final 替换hugegraph lib下的netty-all版本，初始化成功。
### Actual behavior 实际表现
{type something here...}

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by zhoney** [comment]
@0xqq 感谢反馈！

我在本地使用master最新代码打包`hugegraph-0.10.4.tar.gz`，部署`apache-cassandra-3.11.5-bin.tar.gz`，可以正常`init-store`和`start-hugegraph`，并未复现你的问题，如果有更多信息，请补充说明，谢谢！

**Comment by maxiujin** [comment]
Are the nodes cassandra or hugegraph or both?
