### ISSUE TITLE
使用Restful API时出现跨域访问问题

### ISSUE THREAD

**Issue by LuciaRan** [hugegraph/hugegraph#740]
具体报错如下：
Access to XMLHttpRequest at 'http://XXX.XXX.XXX.XXX.:8080/gremlin' from origin 'http://XXX.XXX.XXX.XXX.:9999' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

我想请教一下相关hugegraph服务器代码应该在哪个目录中修改

版本是hugegraph-server-0.9.2

**Comment by LuciaRan** [comment]
版本是hugegraph-server-0.9.2

**Comment by Linary** [comment]
代码位于 `hugegraph-api` 模块下，server 包是关于 `RestServer` 本身的配置，api 包下是所有的 API。
