### ISSUE TITLE
HugeGraph大量数据如何更新节点属性(load方式)？

### ISSUE THREAD

**Issue by fansichao** [hugegraph/hugegraph#744]
业务场景:
1. 进行load的数据导入。（已设置唯一ID）
能够指定 create节点(存在时不创建) 
还是merge节点(存在时更新,不存在时创建)

**Comment by Linary** [comment]
可以在映射文件中添加一个 update_strategies 域，它能设置指定属性的更新策略，未被指定的属性则不更新。支持的的更新策略包括：SUM、BIGGER、SMALLER、UNION、INTERSECTION、APPEND、ELIMINATE、OVERRIDE。你这里应该是使用 OVERRIDE 即可。你可以参考这个提交中的示例: https://github.com/hugegraph/hugegraph-loader/pull/97/commits/54bcf1299f38622999c58cbf65dc78a2d3df6c14

**Comment by fansichao** [comment]
好的，谢谢啦。
https://hugegraph.github.io/hugegraph-doc/quickstart/hugegraph-loader.html

![image](https://user-images.githubusercontent.com/25975418/68645053-d8711180-0551-11ea-938d-6509c27acd62.png)
