### ISSUE TITLE
hugegraph-dist0.9.2无法查询hugegraph-sever0.10.4的数据

### ISSUE THREAD

**Issue by firepation** [hugegraph/hugegraph#747]
### Expected behavior 期望表现
使用 java api 查询 hugegraph 的元数据和点边数据

### Actual behavior 实际表现
查找出的元数据为空，点边数据量为 0。使用 1.8.0 版本的 hugegraph-client 可以读取数据，是否是因为低版本的 hugegraph-dist 不能读取高版本 server 中的数据

### Steps to reproduce the problem 复现步骤
使用 0.9.2 版本的 hugegraph-dist java api 读取 0.10.4 版本 hugegraph-server 中的数据

### Specifications of environment 环境信息
- hugegraph version: 0.10.4 
- hugegraph-dist : 0.9.2
- hugegraph backend: cassandra

**Comment by javeme** [comment]
@firepation 是的，dist和server是一体的，必须要一致的版本。高版本client可以兼容低版本的server。

**Comment by firepation** [comment]
> @firepation 是的，dist和server是一体的，必须要一致的版本。高版本client可以兼容低版本的server。

了解了，谢谢
