### ISSUE TITLE
使用Restful-API更新边属性出错

### ISSUE THREAD

**Issue by TheGodOfObelisk** [hugegraph/hugegraph#752]
### Expected behavior 期望表现
获取vertex_id为1:202.77.162.213,且类型为icmp_echo_ping的边数据.

### Actual behavior 实际表现
```
<html><head><title>Grizzly 2.3.28</title><style><!--div.header {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#003300;font-size:22px;-moz-border-radius-topleft: 10px;border-top-left-radius: 10px;-moz-border-radius-topright: 10px;border-top-right-radius: 10px;padding-left: 5px}div.body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:#FFFFCC;font-size:16px;padding-top:10px;padding-bottom:10px;padding-left:10px}div.footer {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#666633;font-size:14px;-moz-border-radius-bottomleft: 10px;border-bottom-left-radius: 10px;-moz-border-radius-bottomright: 10px;border-bottom-right-radius: 10px;padding-left: 5px}BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;}B {font-family:Tahoma,Arial,sans-serif;color:black;}A {color : black;}HR {color : #999966;}--></style> </head><body><div class="header">Internal Server Error</div><div class="body"><b>java.net.URISyntaxException: Illegal character in path at index 68: http://localhost:8080/graphs/hugegraph/graph/edges/S1:202.77.162.213>1>>S1:172.16.112.94?action=append</b><pre>     1: org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.getRequestUri(GrizzlyHttpContainer.java:491)
     2: org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:366)
     3: org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
     4: org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593)
     5: org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573)
     6: java.lang.Thread.run(Thread.java:748)
</pre><b>Root Cause: java.net.URISyntaxException: Illegal character in path at index 68: http://localhost:8080/graphs/hugegraph/graph/edges/S1:202.77.162.213>1>>S1:172.16.112.94?action=append</b><pre>     1: java.net.URI$Parser.fail(URI.java:2848)
     2: java.net.URI$Parser.checkChars(URI.java:3021)
     3: java.net.URI$Parser.parseHierarchical(URI.java:3105)
     4: java.net.URI$Parser.parse(URI.java:3053)
     5: java.net.URI.<init>(URI.java:588)
     6: org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.getRequestUri(GrizzlyHttpContainer.java:489)
     7: org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:366)
     8: org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
     9: org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593)
    10: org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573)
        ... 1 more</pre>Please see the log for more detail.</div><div class="footer">Grizzly 2.3.28</div></body></html>
```
### Steps to reproduce the problem 复现步骤
1. 导入数据
2. PUT指令更新
curl -X PUT http://localhost:8080/graphs/hugegraph/graph/edges/'S1:202.77.162.213>1>>S1:172.16.112.94'?action=append -d '{
            "properties": {
                "frequency": 2
            }
        }'
3. 得到错误信息

### Status of loaded data 数据状态
无

#### Vertex/Edge summary 数据量
- loaded vertices amount: 768
- loaded edges amount: 914
- loaded time: 无

#### Vertex/Edge example 数据示例
Vertex example:
{
    "label": "entity",
    "type": "vertex",
    "properties": {
        "ip": "172.16.113.23",
        "ts": "952440709.570045",
        "vertex_type": "asset",
        "ips": "2000-03-07-22:51:49|172.16.113.23",
        "status": "unknown"
    },
    "id": "1:172.16.113.23"
}
Edge example:
{
    "id": "S1:172.16.112.10>4>>S1:202.77.162.213",
    "label": "rpc_reply",
    "type": "edge",
    "inVLabel": "entity",
    "outVLabel": "entity",
    "inV": "1:202.77.162.213",
    "outV": "1:172.16.112.10",
    "properties": {
        "ts": "952443286.703873",
        "edge_type": "basic_event",
        "time": "2000-03-07-23:34:46",
        "src_ip": "172.16.112.10",
        "src_p": "55636",
        "dst_ip": "202.77.162.213",
        "dst_p": "694",
        "description": "RPC_SUCCESS",
        "frequency": 1
    }
}
#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
entity = graph.schema().vertexLabel("entity").properties("ip", "ips", "ts", "vertex_type", "status").primaryKeys("ip").ifNotExist().create()

rpc_reply = graph.schema().edgeLabel("rpc_reply").sourceLabel("entity").targetLabel("entity").properties("edge_type", "ts", "time", "frequency", "src_ip", "src_p", "dst_ip", "dst_p", "description").ifNotExist().create()

关于属性"frequency":
{"id":13,"name":"frequency","data_type":"INT","cardinality":"SINGLE","properties":[],"user_data":{}}]}

未创建IndexLabel
### Specifications of environment 环境信息
- hugegraph version: v0.9.2
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}Ubuntu 16.04 3.10GHz × 4  15.6 GiB
- hugegraph backend: RocksDB

求指点,谢谢!
我只是想修改边上frequency的值.

**Comment by javeme** [comment]
@TheGodOfObelisk URL中的`>`是特殊字符，需要编码为`%3E`，更多编码规范可参考：
https://www.w3cschool.cn/htmltags/html-urlencode.html

**Comment by TheGodOfObelisk** [comment]
> @TheGodOfObelisk URL中的`>`是特殊字符，需要编码为`%3E`，更多编码规范可参考：
> https://www.w3cschool.cn/htmltags/html-urlencode.html

谢谢你.
