### ISSUE TITLE
delete aways fail

### ISSUE THREAD

**Issue by RustRw** [hugegraph/hugegraph#754]
### Expected behavior 期望表现
删除的表现能够较为正常, 类似于插入

### Actual behavior 实际表现
基本上不可用

### Steps to reproduce the problem 复现步骤
1. 删除一个节点的, 边多的话超时
2. 循环遍历边进行删除  也会超时 如下错误:
{
    "exception": "class com.baidu.hugegraph.backend.BackendException",
    "message": "Interrupted, maybe it is timed out",
    "cause": ""
}
3. 很多时候长时间测试, 会报 被KIll掉, 服务挂掉了. 

#### Vertex/Edge summary 数据量
每个顶点 1~2w个边这样

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
[
    {
        "id": 1,
        "class": "person",
        "properties": [
            {
                "name": "name",
                "type": "TEXT",
                "indexType": null
            }
        ],
        "primary_key": "name",
        "nullable_keys": null
    }
]

[
    {
        "id": 1,
        "class": "knows",
        "source_class": "person",
        "target_class": "person",
        "properties": [],
        "sort_keys": null,
        "nullable_keys": null
    }
]

### Specifications of environment 环境信息
- hugegraph version: {like v0.10.3}
- operating system: {like ubuntu 16.04, 8 CPUs,32G RAM}
- hugegraph backend: rocksdb

**Comment by javeme** [comment]
@RustRw 由于LSMTree结构的后端对于大量删除操作的处理瓶颈，所以确实容易引起超时。另外大量删除操作会导致查询大量墓碑而占用过多内存，内存不够时可能引起服务挂掉。
目前只能用其它方式绕过该问题，有2个建议：

1. 尽量避免大量删除数据，可以反过来，采用移动需要数据到新库的方式剔除不需要的数据；
2. 利用TTL让数据自动过期删除，该[Feature](https://github.com/hugegraph/hugegraph/issues/295)目前正在开发中。

**Comment by javeme** [comment]
@RustRw 另外，能否提供下具体删除数据的量？以及删除的场景（比如数据的删除条件）？看看找一个比较针对性的方案。

**Comment by RustRw** [comment]
> @RustRw 查询大量墓碑而占用过多内存，内存不够时可能引起服务挂掉。

这块可能出现内存泄露吗?  我发现有个奇怪的现象是, jvm显示的内存和外存正常, 但是整个进程就一直内存暴增.  不知道跟我当时使用Jprofile查看性能是否有关系, Jprofile本身占用应该也会体现在jvm中.所以这块也很奇怪.

**Comment by RustRw** [comment]
> @RustRw 另外，能否提供下具体删除数据的量？以及删除的场景（比如数据的删除条件）？看看找一个比较针对性的方案。

谢谢回复, 这块我只是做了一个测试,发现有这个非常慢的问题, 另外对代码逻辑也进行了一下学习, 的确在为了兼容通用的事物,  代码好像没有对特定场景做优化, 感谢回复.
