### ISSUE TITLE
属性支持aggregate问题

### ISSUE THREAD

**Issue by gwny** [hugegraph/hugegraph#755]
你好，
   从[#693](https://github.com/hugegraph/hugegraph/pull/693)和[#493](https://github.com/hugegraph/hugegraph/pull/493)来看，目前对于属性已经支持按策略更新，但是使用rocksdb作为后端存储时，提示不支持该特性，看了一下代码，好像其他数据库也不支持。
  从文档上也没有看到该特性的介绍，请问是否暂时还不开放该功能，谢谢。

hugegraph版本：0.10.4
后端存储：rocksdb
报错：
`the rocksdb store does not support aggregate propety`

**Comment by javeme** [comment]
@gwny 上述两个Issues链接并不是代表同一个功能，目前可以按照 #493 的策略更新属性的，但是aggregate属性只能特定的后端才支持，所以是的暂时还没有该功能。

**Comment by gwny** [comment]
> @gwny 上述两个Issues链接并不是代表同一个功能，目前可以按照 #493 的策略更新属性的，但是aggregate属性只能特定的后端才支持，所以是的暂时还没有该功能。

好的，谢谢
