### ISSUE TITLE
通过loader导入图数据库之后，图数据库里的时间格式的数据，要比导入的真实数据晚8个小时

### ISSUE THREAD

**Issue by dongxuej** [hugegraph/hugegraph#757]
### Expected behavior 期望表现
加载到图数据库里面的数据与原始数据完全一致

### Actual behavior 实际表现
通过loader导入图数据库之后，图数据库里的时间格式的数据，要比导入的真实数据晚8个小时；同时我们也测了通过rest的方式直接post点进图数据库，这时候时间数据是正常的；最后我们也确定了安装loader机器的时区没有问题

### Steps to reproduce the problem 复现步骤
通过loader导入带有时间的数据，schema定义为date类型

#### Vertex/Edge example 数据示例
原始数据：
![image](https://user-images.githubusercontent.com/24312864/69243696-8d549f80-0bde-11ea-8316-15a47d00e515.png)
图查询数据：
![image](https://user-images.githubusercontent.com/24312864/69244030-326f7800-0bdf-11ea-8169-9b7e9291da26.png)

**Comment by Linary** [comment]
#https://github.com/hugegraph/hugegraph-loader/pull/107
