### ISSUE TITLE
索引创建失败Requested permits (0) must be positive

### ISSUE THREAD

**Issue by 860960342** [hugegraph/hugegraph#760]
导入数据后再创建的索引，顶点量约65w

用hugegraph-studio执行graph.schema().indexLabel("testByhas_Conclusion").onV("TEST").by("has_Conclusion").secondary().ifNotExist().create();
报错：Task '116' was not completed in 10 seconds
查看hugegraph日志：java.lang.IllegalArgumentException: Requested permits (0) must be positive

使用hugegraph-tools执行异步任务：
 [hugegraph-tools-1.3.0]$ ./bin/hugegraph gremlin-schedule -s "graph.schema().indexLabel("testByhas_Conclusion").onV("TEST").by("has_Conclusion").secondary().ifNotExist().create();"
查看任务信息：
Task info: {task_name=graph.schema().indexLabel(testByhas_Conclusion).onV(TEST).by(has_Conclusion).secondary().ifNotExist().create();, task_progress=0, task_create=1574731429860, **task_status=failed**, task_update=1574731430378, **task_result=java.lang.IllegalArgumentException: Requested permits (0) must be positive**, task_retries=0, id=118, task_type=gremlin, task_callable=com.baidu.hugegraph.api.job.GremlinAPI$GremlinJob, task_input={"gremlin":"graph.schema().indexLabel(testByhas_Conclusion).onV(TEST).by(has_Conclusion).secondary().ifNotExist().create();","aliases":{"hugegraph":"graph"},"bindings":{},"language":"gremlin-groovy"}}

### Specifications of environment 环境信息
- hugegraph version: 0.9.2
- operating system: centos 7.4
- hugegraph backend: hbase 2.2

请问这是什么原因？

**Comment by javeme** [comment]
@860960342 从目前提供的错误信息还无法找到原因，请问这个问题是必然复现的吗？是否有一些触发条件或者有利于我们重现分析的步骤？

**Comment by 860960342** [comment]
@javeme 尝试了对不同属性建索引，都是报错java.lang.IllegalArgumentException: Requested permits (0) must be positive

**Comment by 860960342** [comment]
@javeme 报错位置在guava的checkArgument：
![image](https://user-images.githubusercontent.com/58197479/69839756-df0ec100-1293-11ea-8ac6-e0a29aac50e1.png)

**Comment by javeme** [comment]
@860960342 感谢反馈，是不是开启了限速配置项？这个应该是Bug，我们会尽快修复。
