### ISSUE TITLE
通过修改源码想 clear 图库实例时保持region分区原样，但未有效

### ISSUE THREAD

**Issue by lihuimintu** [hugegraph/hugegraph#762]
### Expected behavior 期望表现
期望 clear 图库实例时，HBase 的表的Region 分区能保持原样，不要恢复成一个Region。
根据阅读源码和HBase的知识。我找到了对应位置，并修改了源码 HbaseSessions的truncateTable方法。

truncateTable方法调用的truncateTableAsync方法的preserveSplits参数改成true。

![image](https://user-images.githubusercontent.com/24488282/69690970-6c250f00-1108-11ea-8770-70563980207f.png)

将其编译打包上传到测试环境上，并替换lib路径下的 hugegraph-hbase-0.9.2.jar 包。

### Actual behavior 实际表现
执行clear方式清除图实例，发现还是将HBase表恢复成只有一个Region 

### Steps to reproduce the problem 复现步骤
1. 初始化图实例bin/init-store.sh后，在hbase shell 上手动删除 graph_v， 新建一个预分区的 graph_v。create 'hugegraph:graph_v', 'f', SPLITS => ['0x8', '0x9', '0xa', '0xb', '0xc', '0xd', '0xe', '0xf']
2. 使用 postman 向图服务发送clear清除请求。http://{hostIP}:8080/graphs/hugegraph/clear?confirm_message=I%27m+sure+to+delete+all+data 
3. hbase 的 web UI上查看graph_v表的region个数

### Specifications of environment 环境信息
- hugegraph version:  v0.9.2
- operating system:  centos 7.5
- hugegraph backend: hbase 2.1.0+cdh6.3.1, cluster with 4 nodes

**Comment by imbajin** [comment]
简单看了一下图server代码, 没有生效的原因应该是你改错了地方. 
图实际清空数据是直接调用的`truncateTableAsync`, 而不是truncateTable,  详见`HbaseSessions`[源码](https://github.com/hugegraph/hugegraph/blob/5878d8f61d39b6da8c7d3120e4ceb2b066d04ad7/hugegraph-hbase/src/main/java/com/baidu/hugegraph/backend/store/hbase/HbaseSessions.java#L208)

当然,  我觉得如果要修改, 应该是修改图server的源码, 不是更简单直接么~
可以参考之前类似的[问题](https://github.com/hugegraph/hugegraph/issues/712#issuecomment-543775508), 先用Arthas快速修改看看是否有效. 再去实际修改

最后就是, 情况Hbase数据的时候默认应该保留region结构么? 似乎可以改成默认保留, 用户如果需要删除直接hbase删除表就行了 @javeme

**Comment by javeme** [comment]
@imbajin 默认保留region结构可以的（可能是大部分场景的需求，不过不确定是否有需要干净分区的场景）

@lihuimintu 修改参数`preserveSplits=true`不成功，可能是操作步骤不对（比如没有重启server），能否提供详细具体的步骤？另外，欢迎给hugegraph贡献代码  [how to contribute](https://github.com/hugegraph/hugegraph/blob/master/CONTRIBUTING.md)

**Comment by imbajin** [comment]
实际来看干净区分的需求应该很少, 大多数的场景是业务开始使用图, 各种原因然后频繁的`clear`... 
业务hbase这里不好预分配region(split key太集中) 
而如果是清成1个region, 最大的问题是前期导入数据很容易出现`region too busy`的异常(并且此时只有一个节点干活, 必须得等它自己切分并`balance`之后, 才好一点.
实际的情况是经常得手动去split然后move热点region, 很麻烦, 所以如果这个设置没啥隐患, 那的确是很有用的

**Comment by lihuimintu** [comment]
正如 @imbajin 所说，clear之后再重新导入数据会出现HBaes单机负载高，需要手动split后再move。因此才想修改源码来解决该问题。
@javeme 下方是我具体的尝试步骤
1 针对业务分析，我司图库主键需求都是采用String Id，阅读源码发现String Id的rowkey前缀是String的长度跟0x80做或运算。
BytesBuffer类的writeId方法
![image](https://user-images.githubusercontent.com/24488282/69773512-0ac77380-11ce-11ea-8a44-aa5b6cd96bb2.png)
这样的话，觉得就在新建HBase graph_v表时做好预分区，这样对新建的图库实例更友好些。
修改 HbaseSessions类的createTable方法如下
![image](https://user-images.githubusercontent.com/24488282/69773697-7f021700-11ce-11ea-9174-37d55a6938e7.png)
2 另外就如之前所说打算在clear 图库实例时，只清空Hbase数据并保留region结构。
修改 truncateTable 方法调用的truncateTableAsync方法的preserveSplits参数，将该参数改成true。
![image](https://user-images.githubusercontent.com/24488282/69773862-0f405c00-11cf-11ea-90c0-61c01d852fb2.png)
3 目前只修改了这两处，想验证下修改效果，将hugegraph-hbase 项目编译打包，并替换测试环境hugegraph-0.9.2/lib路径下的 hugegraph-hbase-0.9.2.jar 包
4 停止server服务，修改conf目录下相关文件添加新图库实例
5 bin/init-store.sh 初始化图库，bin/start-hugegraph.sh 启动server
6 查看HBase Web UI 页面发现 graph_v 表有进行预分区，说明修改createTable方法有效
![image](https://user-images.githubusercontent.com/24488282/69774806-f08f9480-11d1-11ea-821e-82a0763424d4.png)
7 使用 postman 向hugegraph发送clear清除请求。http://{hostIP}:8080/graphs/hugegraph/clear?confirm_message=I%27m+sure+to+delete+all+data
8 查看UI页面发现 graph_v 表region 结构未保留。说明修改truncateTable 方法未有效
![image](https://user-images.githubusercontent.com/24488282/69774974-58de7600-11d2-11ea-83fb-3c266d761fe3.png)
9 中间尝试过打印日志的方式确认 clear 时会进入truncateTable 方法清除HBase表，还将` return admin.truncateTableAsync(tableName, true);`方法注释换成`return null;`让其不清空HBase表看看效果，发现最终呈现的还是清空了HBase表。这让我怀疑clear 并不是调用truncateTable方法，但是根据阅读源码我只能找到truncateTable方法会清空HBase表。
![image](https://user-images.githubusercontent.com/24488282/69775092-a8bd3d00-11d2-11ea-85cb-3617f335022c.png)

---
Arthas 工具暂不熟悉，后续处理图库细节问题时我会尝试使用。谢谢传授经验

**Comment by javeme** [comment]
> 换成return null;让其不清空HBase表看看效果，发现最终呈现的还是清空了HBase表。

@lihuimintu 第9步看起来是没有成功替换新代码，建议增加一些日志打印：
```java
private static final Logger LOG = Log.logger(HbaseSessions.class);
LOG.info("truncateTable {}", table);
```

**Comment by lihuimintu** [comment]
增加两处日志
1 在HbaseStore类的truncate方法中添加`LOG.info("Truncate table {}", table);`
![image](https://user-images.githubusercontent.com/24488282/69777889-24bc8280-11dd-11ea-8d70-e0b0bda6d472.png)
2 在HbaseSessions类的truncateTable方法添加`LOG.info("truncateTable {}", table);`
![image](https://user-images.githubusercontent.com/24488282/69777962-6cdba500-11dd-11ea-801e-e9b6624940d2.png)
查看server日志发现有 HbaseStore 的日志打印，未有HbaseSessions的日志打印，看起来是能够进入HbaseStore类的truncate方法，但是未能够进入HbaseSessions类的truncateTable方法
![image](https://user-images.githubusercontent.com/24488282/69778279-aa8cfd80-11de-11ea-89de-b453ed24e9c0.png)

日志未能有效打印这让我很难确定问题。

**Comment by javeme** [comment]
> 日志未能有效打印这让我很难确定问题。

@lihuimintu 说明HbaseSessions这个类的代码没有替换成功，可能是打包过程中引入的问题，最好清空一下`mvn clean`再执行`mvn package`。

**Comment by lihuimintu** [comment]
打包过程一直是先clean再package的。
为了更好的复现问题。决定重新部署环境
我将conf 目录备份，将hugegraph-0.9.2文件夹删除，重新解压tar包并部署了一次hugegraph-0.9.2的环境，将备份的conf目录替换原始conf目录。
同时使用了jd-gui对打包编译出来的jar包确认代码有被更改
![image](https://user-images.githubusercontent.com/24488282/69783798-3870e480-11ef-11ea-812c-7e7b59ce10ed.png)
再将其替换之后测试，发现日志有成功打印HbaseSessions类的truncateTable方法的日志。
![image](https://user-images.githubusercontent.com/24488282/69783961-a0272f80-11ef-11ea-9387-7e9c25381137.png)
观察 HBase Web UI页面看到 Region结构也保持原样，达到预期效果。

从现在的情况看可能是之前图库环境造成的HbaseSessions这个类的代码没有替换成功。感觉很玄学。
 最后感激两位 @imbajin @javeme 的帮助

**Comment by imbajin** [comment]
@lihuimintu 
很赞的issue, 能帖出自己的思路和图, 这样对解决问题的效率很有帮助
其次社区也会更愿意优先回复一些

**PS:** 最后关于Arthas我上个issue里后面给出了完整的用例, 就几步其实挺简单的, 可以试试, 也自带`jad` 方便你快速确认是否改动有生效, 编译打包重启的过程太麻烦了, 特别是这种验证性的小问题. (而且如果线上也有不适合重启的时候)

**Comment by javeme** [comment]
@lihuimintu 解决了就好。
也非常欢迎将代码提交到社区中来，如果有意愿的话接下来可以讨论具体的方案，大体上是按照现在贴的流程，只是把split-keys写到配置文件中即可。

**Comment by lihuimintu** [comment]
@javeme 目前修改的代码如之前所说，个人也愿意参与进来，同时想让代码能够优雅。

两个想法
1. 选择想做预分区的表做指定预分区
2. clear图库实例时，可以选择恢复成一个region，也可以清除数据但保留region结构

希望社区能提供具体的方案设计，争取能够实现并回馈社区。

**Comment by javeme** [comment]
@lihuimintu 我觉得上面的两个想法OK。

预分区配置方式大概可以是这样：
```java
hbase.tables_splits = [
  g_v: [0x000a, 0x000b, 0xFF00],
  g_oe: [0x000a, 0x000b, 0xaabb],
  g_ie: [0x000a, 0x000b, 0xaabb]
]
```
可参考[`rocksdb.data_disks`](https://hugegraph.github.io/hugegraph-doc/config/config-option.html)配置项。

可增加配置`hbase.truncate_preserve_splits=true/false`选择是否保留region结构。

@imbajin @Linary 你们有没有什么补充？

**Comment by imbajin** [comment]
唔, 第二点没啥问题, 默认给`true`清空数据时保留分区结构

主要是第一点预分区这, 假设以下用户场景: 
> 点有3种, 分别是Phone, IP, MD5
> 那数据常见两种情况:
> 1. 使用原生数据作为顶点id, 比如Phone顶点的`137xxx57`, 和IP顶点的 `8.8.8.8`, `md5值`
> 2. 使用主键模式, 比如 `1:137xxx57` 和 `2:8.8.8.8` 和`3:md5`值
>
> 出入边表取决于点ID, 就不单独说了,  另外索引表也是一个数据大表, 也要切分

然后`hbase`默认提供两种分区方式:
1. 如果数据较少(千万/亿级), 或者随机性很强(md5后). 可以简单一些, 直接给一个region数, 比如默认几张数据表初始给`n`个region, 这个应该简单 (可作为默认的分区方式? 默认值是?)
2. 如果数据较大, 或者数据特征很集中, 可以按具体的分裂点去让业务设置, 不过这里细一些:
    - 表的分裂点如何设置更友好, 比如根据上面的case, 手机号在点表中**期望**是以`1:137`, `1:176`, `1:189`等作为分裂点, 配置里能直接写**原始字符串**, 而不需要拼加在头部的byte字节
    - `3:md5`这种天然均匀的数据, 分裂点如何设置呢? 引出是否需要有默认的分裂方式? 
    -  例子里的两种主键ID设置方式, 不知道是不是要分别处理

先就想到这些, 有新的再补充~

**Comment by javeme** [comment]
@lihuimintu @imbajin 看起来预分区由于涉及因素较多，所以比较复杂：

1. 顶点id策略不一样，分区策略需要有所区别
2. id长度也会影响分区
3. 假如是主键策略，也需要依赖label的id，因此必须在创建好元数据之后的时机进行预分区

目前我想到2个方案：
1、预分区在元数据中来设置看起来是比较通用的方式，比如在label中增加一个分区策略，每个label支持，然后把所有label：

1. 枚举分段，任意类型id都可以，输入id类型对应的值，包括字符串或者数字，比如`splits: [137, 176, 189]`
2. 数字类型id（包括自定义数字id、自定义uuid、自动生成id、主键数字属性在内），可以指定固定（平均/随机）分为多少段，比如`splits: 100`
3. 以16进制表示的字符串（实际是数字或字节数组），可以按照数字类型处理，分段之后转为16进制即可

2、对于所有类型的id均使用hash方式加上一段前缀（比如2个字节hash值），这样只需要指定分为多少段即可。

另外，增加配置`hbase.truncate_preserve_splits`项可以独立出来，先完成一部分。

**Comment by JackyYangPassion** [comment]
“方案2：对于所有类型的id均使用hash方式加上一段前缀（比如2个字节hash值），这样只需要指定分为多少段即可。”

使用起来更灵活，用户可以根据数据量 设定段数，这样对后期线上 使用p99 更稳定，不会因为split compact 等 影响线上

**Comment by javeme** [comment]
> 使用起来更灵活，用户可以根据数据量 设定段数，这样对后期线上 使用p99 更稳定，不会因为split compact 等 影响线上

@JackyYangPassion 是的，欢迎进一步交流，另外是否有兴趣贡献代码？大体规划想法可以参考：https://github.com/hugegraph/hugegraph/issues/822

**Comment by JackyYangPassion** [comment]
是的，昨天通篇看了下代码，目前想短平快的落地方案二：
思路：
1. create table 进行预分区
2. 数据读写路径 按照预分区规则序列化rowkey
目前正在研究代码细节，准备下周能否实现一版，进行性能测试

**Comment by javeme** [comment]
@JackyYangPassion hi目前你那边进展如何？规划在近期推进落实这个Feature，打算启动开发，如果你有意愿的话非常欢迎贡献代码。

**Comment by javeme** [comment]
@JackyYangPassion hi 期待贡献代码

**Comment by JackyYangPassion** [comment]
之前预计是11月底能贡献出来 目前由于增加可配置化 修改了core层的一些接口 预期近期会提交PR
