### ISSUE TITLE
获取shard列表后，根据shard拿不到节点和边的数据

### ISSUE THREAD

**Issue by Cesar456** [hugegraph/hugegraph#766]
### Expected behavior 期望表现
根据[文档](https://hugegraph.github.io/hugegraph-doc/clients/restful-api/traverser.html)中对于shard和scan 的描述，传入split size成功获取shard列表，期望scan接口返回某shard的数据。

### Actual behavior 实际表现
scan接口返回值为空。无论节点还是边，都获取不到数据

### Steps to reproduce the problem 复现步骤
1. http://ip:port/graphs/hugegraph/traversers/vertices/shards?split_size=1048576
2. http://ip:port/graphs/hugegraph/traversers/vertices/scan?start=&end=

#### Vertex/Edge summary 数据量
- loaded vertices amount:  20 million
- loaded edges amount: 20 million

### Specifications of environment 环境信息
- hugegraph version:  v0.10.4
- operating system: centos 6, 16 CPUs, 16G RAM}
- hugegraph backend: Hbase with 3nodes

**Comment by javeme** [comment]
@Cesar456 可能是存在某些空的Shard，可以跳过的。
更多Shard迭代可参考: [Iterator\<Vertex\> iteratorVertices(Shard shard, int sizePerPage)](https://github.com/hugegraph/hugegraph-client/blob/master/src/main/java/com/baidu/hugegraph/driver/TraverserManager.java#L315)
