### ISSUE TITLE
查询优化

### ISSUE THREAD

**Issue by 306495389li** [hugegraph/hugegraph#768]
### Expected behavior 期望表现
比如A和1000个用户建立了关系，其中包括B，我现在需要根据A->B的关系，通过B快速查到A

### Actual behavior 实际表现
推荐关系存在过多，查询需要几秒钟的时间

### Specifications of environment 环境信息
- hugegraph version: 0.10.2
- operating system: centos 7.3, 16 CPUs, 32G RAM
- hugegraph backend:mysql

**Comment by javeme** [comment]
@306495389li 是指通过`g.V('B').in('label')`进行查询吗？理论上这种查询耗时在毫秒级，不至于需要几秒钟，这个时间是api返回的时间还是studio中包括渲染邻居图的时间？
若不是上述语句的话具体查询语句可以提供一下吗？

**Comment by 306495389li** [comment]
g.V().hasLabel('KFCD_HK_COFFEE201907').has('userCode','25328298092250748102').inE().path()，用studio查询，他的上家有1000多个下家，这样查询要6S

**Comment by javeme** [comment]
@306495389li 那这应该是studio渲染邻居导致的，studio在绘图时会检测各个点的邻居以绘制出较为完整的图。如果希望仅仅获得查询所需信息，可以不用studio而是通过api查询，或者在studio上只查询id：`g.V().hasLabel('KFCD_HK_COFFEE201907').has('userCode','25328298092250748102').inE().path().by(id)`
