### ISSUE TITLE
hugegraph-tools backup出现问题

### ISSUE THREAD

**Issue by DubheRen** [hugegraph/hugegraph#777]
Vertices has been backup: Exception in thread "main" com.baidu.hugegraph.exception.ToolsException: Exception occurred while querying shards of vertices(after 3 retries)
上面是报错内容，不知道该怎么解决，顶点数据始终不能backup

**Comment by zhoney** [comment]
@DubheRen HugeGraphServer用的是什么存储后端？

用下面的方法获取一下shards信息：

```
GET http://localhost:8080/graphs/hugegraph/traversers/vertices/shards?split_size=67108864
```

- `url`换成你的`HugeGraphServer`地址和端口
- `hugegraph`换成你的图名字

**Comment by DubheRen** [comment]
我的直接用的memory存储后端，{"exception":"class com.baidu.hugegraph.exception.NotSupportException","message":"Not support metadata 'splits'","cause":””}这是获取到的shards信息

**Comment by zhoney** [comment]
@DubheRen memory后端还不支持backup（本质是不支持按shard获取顶点和边），下一版本会支持。

备份的话，可以用顶点和边的分页获取功能暂时替代，链接地址：[顶点](https://hugegraph.github.io/hugegraph-doc/clients/restful-api/vertex.html) ，[边](https://hugegraph.github.io/hugegraph-doc/clients/restful-api/edge.html)

![image](https://user-images.githubusercontent.com/17330028/70316749-48c03980-1857-11ea-81bf-53a1efcf5f6e.png)

![image](https://user-images.githubusercontent.com/17330028/70316775-57a6ec00-1857-11ea-8165-43cc9663c6ee.png)


FYI： 近期在讨论在tools里封装一版这种分页获取的方式，弥补0.9到0.10的MySQL和Memory等后端无法备份、恢复和迁移的问题。

**Comment by javeme** [comment]
#974 中支持了MySQL和memory的shard，并在 [tools pr 56](https://github.com/hugegraph/hugegraph-tools/pull/56)中进行了适配
