### ISSUE TITLE
search索引，部分关键词能搜索到，部分搜索不到。

### ISSUE THREAD

**Issue by tarzanfan** [hugegraph/hugegraph#779]
### Expected behavior 期望表现

希望都可以搜索到

### Actual behavior 实际表现

部分关键词搜索不到

### Steps to reproduce the problem 复现步骤
1. 在edgelabel木马的name属性上建立search索引；
2. 插入木马数据，name为“木马-远控-Trojan.Win32.FakeLPK.7cfa上线包”；
3. 用g.E().hasLabel('木马').has('name', Text.contains('ddos') )搜Trojan、ddos可以搜到，而搜Nitol、Win32等都无法搜到。

### Specifications of environment 环境信息
- hugegraph version: 0.10.4
- hugegraph backend: cassandra

**Comment by tarzanfan** [comment]
发现问题出现在默认分词器上：修改配置文件{graph-name}.properties中：
search.text_analyzer  ：ikanalyzer
search.text_analyzer_mode   ：smart

这种情况支持中文分词比较好。经过比较各种mode组合：结果如下：
word MaximumMatching:[木马, 远, 控, trojan, ., win32, fakelpk, 7cfa, 上线, 包]
word MaximumMatching:[木马, 远, 控, trojan, ., win32, fakelpk, 7cfa, 上线, 包]

jieba SEARCH:[木马, -, 远控, trojan, ., win32, fakelpk, 7cfa, 上线, 包]
jieba INDEX:[木马, -, 远控, trojan, ., win32, fakelpk, 7cfa, 上线, 包]    -------------目前最符合现状要求

smartcn:[木马, 远, 控, trojan, win, 32, fakelpk, 7, cfa, 上, 线, 包]

mmseg4j Simple:[木马, 远, 控, trojan, win32, fakelpk, 7cfa, 上, 线, 包]
mmseg4j Complex:[木马, 远, 控, trojan, win32, fakelpk, 7cfa, 上, 线, 包]

jcseg Simple:[木马, -, 远, 控, trojan.win32.fakelpk.7cfa, trojan, win, 32, fakelpk, 7, cfa, 上线, 包]
jcseg Complex:[木马, -, 远, 控, trojan.win32.fakelpk.7cfa, trojan, win, 32, fakelpk, 7, cfa, 上线, 包]

hanlp standard:[木马, -, 远, 控, -Trojan, ., Win, 32, FakeLPK, 7, cfa, 上, 线, 包]
hanlp nlp:[木马, -, 远控, -Trojan, ., Win, 32, FakeLPK, 7, cfa, 上, 线, 包]

ansj BaseAnalysis:[木马, -, 远, 控, trojan, ., win, 32, fakelpk, 7, cfa, 上线, 包]
ansj IndexAnalysis:[木马, -, 远, 控, trojan, ., win, 32, fakelpk, 7, cfa, 上线, 包]

ik smart:[木马, 远, 控, trojan.win32.fakelpk.7cfa, 上线, 包]     ---------------------默认分词
ik max_word:[木马, 远, 控, trojan.win32.fakelpk.7cfa, trojan, win, 32, fakelpk, 7, cfa, 上线, 包]

具体请查看配置文档：https://hugegraph.github.io/hugegraph-doc/config/config-option.html

**Comment by tarzanfan** [comment]
修改完配置文件之后，数据需要重新插入，才能成功

**Comment by fuling1999** [comment]
> 修改完配置文件之后，数据需要重新插入，才能成功

数据重新插入很麻烦，先把索引删掉，再重新建是否也可以？

**Comment by tarzanfan** [comment]
> > 修改完配置文件之后，数据需要重新插入，才能成功
> 
> 数据重新插入很麻烦，先把索引删掉，再重新建是否也可以？

理论上是可以。我没有尝试
