### ISSUE TITLE
loader工具传输数据问题

### ISSUE THREAD

**Issue by mengquanrun** [hugegraph/hugegraph#78]
### Expected behavior 期望表现
正确传输
119544个结点
8000000条边

### Actual behavior 实际表现
插入成功结点：114044
插入成功边：8005500
结点失败和边失败数均为0

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: 119544
- loaded edges amount: 8000000
- loaded time: {like 101s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: { v0.7.4}
- operating system: {like ubuntu 18.04, 64 CPUs, 64G RAM}
- hugegraph backend: {rocksdb}

**Comment by Linary** [comment]
@mengquanrun 你是说导入过程没有报错，但是有部分顶点的记录统计到边里面去了吗？

**Comment by Linary** [comment]
你是否有设置--timeout参数，还有导入总时间是101秒吗？

**Comment by mengquanrun** [comment]
没有设置多余的参数，只有最基本的-f -s，导入总时间88 ～101s不等

**Comment by Linary** [comment]
感谢你的反馈，我们确实发现了一个与之相关的[BUG](https://github.com/hugegraph/hugegraph-loader/issues/3)，我们会尽快修复。
