### ISSUE TITLE
删除顶点和边后，重新创建相同的顶点和边并增加了creator属性，提示 Invalid property 'creator' for vertex label 'person'

### ISSUE THREAD

**Issue by EnzoLiang** [hugegraph/hugegraph#790]
### Expected behavior 期望表现
后端存储选择的mysql，删除顶点和边后，studio查询不到相应的顶点和边，但是在el和vl数据表中仍能看到label信息，重新创建相同的顶点和边并增加了creator属性，提示 Invalid property 'creator' for vertex label 'person'

### Actual behavior 实际表现
{type something here...}

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by javeme** [comment]
@EnzoLiang 是不是使用了`ifNotExist()`参数进行创建顶点类型？
如果是的话，则因为已经存在顶点类型所以不会进行任何操作，可以验证一下：在创建顶点类型之后，查询一下顶点类型是否正确`schema.getVertexLabel("person")`。
