### ISSUE TITLE
hugegraph-load重复导入顶点，如何移除旧数据中不要的顶点属性

### ISSUE THREAD

**Issue by 860960342** [hugegraph/hugegraph#792]
使用hugegraph-load导入了顶点数据，此时顶点中有has_Category这个属性，
现在在JSON数据集中移除掉has_Category这个属性后，又用hugegraph-load导了一遍，此时查询顶点没有看到has_Category这个属性，但过了一晚后这个属性又可以在顶点上查询到，请问这是什么原因？有什么方法可以删除大量顶点的某个属性？

### Expected behavior 期望表现
hugegraph-loader重复导入顶点，属性以最新的数据集为准。
使用过https://hugegraph.github.io/hugegraph-doc/quickstart/hugegraph-loader.html中的update_strategies=overwrite，由于是旧数据有该属性，新数据没有该属性，貌似没有被真正覆盖。

### Actual behavior 实际表现
第二次导入，当时查询顶点没有看到被移除的属性，过一段时间这个属性又出现了。
![image](https://user-images.githubusercontent.com/58197479/71060302-0f18f800-21a0-11ea-9f97-8a51a86fcbb5.png)

**Comment by Linary** [comment]
@860960342 对于小数据量，你把has_Category属性删掉后，直接重导一遍就会覆盖旧的顶点数据了，不需要使用 update_strategies。对于大量数据的批量移除某旧属性，loader 暂时还不支持。

如果数据量没有那么多，并且has_Category这个属性是可空的，可以用client写java代码，或者用gremlin语句的方式删掉该属性。

另外你的需求是不是可以总结为：第一次导入了一批顶点或边以后，发现某个属性冗余了，然后想在不修改数据源本身的情况下移除掉某属性，是这样吗？

**Comment by 860960342** [comment]
@Linary 感谢，我试试，我们在MALWARE这个label下的顶点有的需要has_Category属性，有的不需要，不能全部删除，目前不需要这个属性的顶点有 60w 个。
我可以修改数据源，但希望重新导入后属性是完全覆盖的，即以前存在但现在不存在的属性删除，以前存在且现在也存在的属性就覆盖，以前不存在但现在存在的属性就增加，不知道是否有方法实现？

**Comment by Linary** [comment]
@860960342 有的顶点需要has_Category属性，有的不需要这个属性，这个的区分条件是什么？我这么问是因为有另一个 issue https://github.com/hugegraph/hugegraph-loader/issues/116 有相似的需求，这个 issue 要实现的功能是根据某个列的值来决定这一行是否需要插入。比如某列`status`的值为 1 时就插入，为 0 时就跳过。如果你的需求也是这样的，我们会尽快实现该功能。

修改数据源之后，再次导入即可，HugeGraph的覆盖策略与你的要求是匹配的。

**Comment by imbajin** [comment]
> @Linary 感谢，我试试，我们在MALWARE这个label下的顶点有的需要has_Category属性，有的不需要，不能全部删除，目前不需要这个属性的顶点有 60w 个。
> 我可以修改数据源，但希望重新导入后属性是完全覆盖的，即以前存在但现在不存在的属性删除，以前存在且现在也存在的属性就覆盖，以前不存在但现在存在的属性就增加，不知道是否有方法实现？

稍微梳理了一下需求, 列了一下对应方案, 你看看是否符合吧:
1. 如果你希望所有的新点/边都是**完全覆盖**旧的 (空也会覆盖已有), 比如旧数据是`a b null, null`, 新数据是` null, null, c, d, 最后得到`null, null, c, d`, 不需要加更新策略, **直接导入**就是完全覆盖. 
2. 设计`OVERRIDE`这个更新策略的用途就是为了避免`1`中新数据的空覆盖了已有的旧数据, 所以是特意判断了, 当新属性不存在(null), 旧属性存在时, 使用旧属性避免丢失数据的.
3. 如果我理解你的样本也有多个数据来源, 不同数据源获得的属性个数不同, 那你也可以约定一个`-1`. 或者`null` (字符串)代表这个数据不存在. 这样它就不是空, 也可以直接覆盖原有数据了.

**Comment by 860960342** [comment]
@Linary @imbajin 感谢回复，直接导入的方式会有想移除的属性复现的情况，我是用的JSON文件，第一次导入{"id":"001","name":"aaa","has_Category":“ok”}和{"id":"002","name":"bbb","has_Category":“ok”}，假设我不想要001顶点的has_Category属性，我重新导入数据{"id":"001","name":"aaa"}和{"id":"002","name":"bbb","has_Category":“ok”}，导完后立即查询g.V('001').values('has_Category')返回结果为empty，符合要求，但20分钟后再查询g.V('001').values('has_Category')返回的结果为['ok']。
这种情况感觉像方案2中避免旧属性数据丢失，不知理解是否正确？

对于方案3，确实来自不同数据源，属性不太好统一。如若统一属性，可能需要借助issue hugegraph/hugegraph-loader#116 这个需求，将为-1或null的属性不插入，避免查询显示时有太多-1或null的情况。

**Comment by imbajin** [comment]
如果你是第一种需求, 那你说**20分钟**后再查出现, 我理解应该是不正常的, 考虑两个情况:
1. 之后又导入了新数据覆盖了原本空的.
2. Server端这里有bug

第一种可能, 你可以直接用[REST-API](https://hugegraph.github.io/hugegraph-doc/clients/restful-api/vertex.html)直接创建一条数据试试看, 默认就是覆盖, 然后再过一段时间看看.

第二种情况, 你可以给出具体的后端信息, 图版本等, 然后尝试用rest-api直接写一个点后, 重启server看看.

**Comment by Linary** [comment]
感谢 @imbajin 童鞋的回复，很全面，很细致！ 👍👍👍

@860960342 如果没有再次导入过数据的话，看起来确实像是一个BUG，你可以按照 @imbajin 说的方式用 REST-API 直接创建一条数据，然后当下查询，这时是没有旧属性的，然后过20分钟再用 REST-API 查试试，如果确实还是有，那就是 server 的 BUG。

如果用 REST-API 查没有但是在 studio 里面查是有的，那说明是 client 或 studio 的 BUG。

**Comment by javeme** [comment]
@860960342 删除属性可以使用[API 2.1.4 删除顶点属性](https://hugegraph.github.io/hugegraph-doc/clients/restful-api/vertex.html)。
另外，按照目前的设计，Cassandra和RocksDB等后端支持自动合并属性，如果不传属性预期的行为是保留旧的属性。不过通过描述“当时查询顶点没有看到被移除的属性”来看，像是有Bug，希望能提供一下环境信息和复现步骤。

**Comment by 860960342** [comment]
@javeme @Linary @imbajin 感谢回复，耽搁了一段时间，根据你们的建议尝试了一下，除了使用**rest-api删除顶点属性**符合预期外，其他方法仍会有顶点属性复现问题。

实验环境：hugegraph-0.10.4，hbase
实验步骤：
首先，使用hugegraph-loader导入或rest-api创建两个顶点
{"id":"001","name":"aaa","has_Category":“ok”}
{"id":"002","name":"bbb","has_Category":“ok”}
然后，分别使用下面五种方式移除001顶点的has_Category属性：
1. 使用rest-api 重新创建id为001且无has_ Category属性的顶点，立即使用studio和rest-api查询这个顶点是没有has_ Category属性的，20分钟后再用studio和rest-api查询这个顶点发现has_ Category属性出现；
2. 使用rest-api创建id为001且无has_ Category属性的顶点，重启hugegraph-server，使用studio和rest-api查询这个顶点发现has_ Category属性出现；
3. 使用hugegraph-loader重新导入001和002顶点，其中001顶点无has_ Category属性，立即使用studio和rest-api查询这个顶点是没有has_ Category属性的，20分钟后再用studio和rest-api查询这个顶点发现has_ Category属性出现；
4. 使用hugegraph-loader重新导入001和002顶点，其中001顶点无has_ Category属性，重启hugegraph-server，使用studio和rest-api查询这个顶点发现has_ Category属性出现；
5. 使用rest-api删除001顶点的"has_Category":“ok”属性，20分钟后再用studio和rest-api查询这个顶点没有has_ Category属性，一小时后再查仍没有，感觉这个方法是可行的。

**Comment by javeme** [comment]
已复现，原因：10分钟之内是因为checkVertexExistIfCustomizedId缓存中删除了该属性，但存储中未删除该属性，默认10分钟缓存失效后与存储中保持一致。注意：需要使用g.V(id)查询。
