### ISSUE TITLE
gremlin计数 HugeGraph OOM

### ISSUE THREAD

**Issue by kidleaf-jiang** [hugegraph/hugegraph#793]
### Actual behavior 实际表现
在数据量比较大的情况下， 运行类似下面语句时，出现HugeGraph OOM

```
g.V().hasLabel('vbsku').count() 
g.V().hasLabel('vbsku').groupCount().by(properties('p_trade').value())
```

### Steps to reproduce the problem 复现步骤

运行上面命令时，查看rocksdb的统计信息，最高点如下:
![image](https://user-images.githubusercontent.com/7587298/71398008-23ef0300-265a-11ea-835d-08e7526d1eab.png)
过两分钟后，rocksdb的统计信息如下：
![image](https://user-images.githubusercontent.com/7587298/71398077-454fef00-265a-11ea-9542-f8c51a5f5082.png)

根据[Memory-usage-in-RocksDB](https://github.com/facebook/rocksdb/wiki/Memory-usage-in-RocksDB)和[RocksDBMetrics](https://github.com/hugegraph/hugegraph/blob/master/hugegraph-rocksdb/src/main/java/com/baidu/hugegraph/backend/store/rocksdb/RocksDBMetrics.java)， 当前hugegraph中rocksdb统计内存，只统计了其中的三个部分，Blocks pinned by iterators没有统计在内。
目前还不能确认是系统的哪个部分把内存吃掉了。

#### Vertex/Edge summary 数据量
1000w级别的点边数据

### Specifications of environment 环境信息
- hugegraph version: 0.10.4
- operating system: centos 6， 32CPUs， 180G RAM
- hugegraph backend: rocksdb

**Comment by imbajin** [comment]
gremlin的`count()`以前看源码就是一个个迭代(不知新版TP有改进没), 所以它等于要遍历所有要统计的点,  然后默认hugeServer开启了比较大的点缓存(应该是1000万?), 所以gremlin遍历的时候可能都进缓存了, 导致堆内存使用不断增大, 所以了可以手动调整一下点缓存个数和时间

但是, 印象里我记得缓存这是有点bug的, 就是修改了缓存个数和时间后, 查询`count()`还是会增大, 你可以修改后试试看

最后这种耗时很长的请求, 可以用[异步gremlin](https://hugegraph.github.io/hugegraph-doc/clients/restful-api/gremlin.html)代替

**Comment by javeme** [comment]
rocksdb内存统计不准确类似问题：#602
