### ISSUE TITLE
如何查询所有顶点？

### ISSUE THREAD

**Issue by OptimusPrimeLee** [hugegraph/hugegraph#826]
1.用gremlin语句查询limit(999)只返回250条数据，limit(x)只有x<250时才起作用，当x>250时只返回250条记录。
2.用/graphs/hugegraph/graph/vertices?limit=99999&label=label接口查询可以返回99999条数据，但是索引不起作用

**Comment by javeme** [comment]
@OptimusPrimeLee `g.V().limit(999)`可以返回全部的，小于250是studio中执行gremlin默认限制的渲染条数；
“但是索引不起作用” 是指什么意思？

**Comment by OptimusPrimeLee** [comment]
@javeme 感谢回复，我检查了一下索引类型是Secondary，查询却用的Search，我的失误造成的。
问题已解决，感谢
