### ISSUE TITLE
restserver.min_free_memory 配置不生效

### ISSUE THREAD

**Issue by JINGXI6** [hugegraph/hugegraph#834]
### Expected behavior 期望表现
{
loader大量数据当free 过低之后插入数据会报异常 

INSERT ERROR: The server available memory 32(MB) is below than threshold 64(MB) and can`t process the request ,you can config restserver.min_free_memory to adjust it or try again later

修改参数restserver.min_free_memory=0

期望不会出现此ERROR
}

### Actual behavior 实际表现
{
INSERT ERROR: The server available memory 32(MB) is below than threshold 64(MB) and can`t process the request ,you can config restserver.min_free_memory to adjust it or try again later
}

### Steps to reproduce the problem 复现步骤
1. 修改配置文件 rest-server.properties  加入restserver.min_free_memory=0 
2. 重启server
3. 同server节点进行loader大量数据

### Vertex/Edge summary 数据量
总数据量490G
未设置max-paese-errors 与 max-insert-errors 导入中断
设置后导入完成（此时loader 与 server 不在同一节点）
Vertex 3302482869
Edge 169271000

### Specifications of environment 环境信息
- hugegraph version: {like v0.10.4}
- operating system: {like centos 7.7 3.10.0-1062.4.1.el7.x86_64, 40 CPUs, 128G RAM}
- hugegraph backend: {hbase}

**Comment by JINGXI6** [comment]
避免此错误 尽量不要server 与 loader同节点 采用-h loader数据，可以定时清理cache/buffer

**Comment by tarzanfan** [comment]
你好，这是我复现你问题的过程：

1.没有修改配置文件之前：
报错信息：
{"exception":"class javax.ws.rs.ServiceUnavailableException","message":"The server available memory 61(MB) is below than threshold 64(MB) and can't process the request, you can config restserver.min_free_memory to adjust it or try again later","cause":""}

2.修改配置文件 rest-server.properties 加入restserver.min_free_memory=10
重启server
经过多次测试，restserver.min_free_memory=10此项已经生效

报错信息：
{"exception":"class javax.ws.rs.ServiceUnavailableException","message":"The server available memory 9(MB) is below than threshold 10(MB) and can't process the request, you can config restserver.min_free_memory to adjust it or try again later","cause":""}


3.修改配置文件 rest-server.properties 加入restserver.min_free_memory=0
重启server
经过多次测试，restserver.min_free_memory=0此项已经生效，没有报错提示

**Comment by tarzanfan** [comment]
![没有修改配置文件之前](https://user-images.githubusercontent.com/43024508/72520747-0dbd1700-3895-11ea-9975-929dc885e4a6.png)
![10MB](https://user-images.githubusercontent.com/43024508/72520754-1281cb00-3895-11ea-8748-e2f240076c60.png)
