### ISSUE TITLE
当边存在，顶点不存在时，gremlin查询异常

### ISSUE THREAD

**Issue by datian9966** [hugegraph/hugegraph#835]
### Expected behavior 期望表现
如果边存在，顶点不存在时，用gremlin查询时应该自动过滤不存在的顶点

### Actual behavior 实际表现
报错
Vertex 'xxx' does not exist

### Steps to reproduce the problem 复现步骤
1. g.V('1:xxx').bothE('xx').otherV().values('xxx').mean() 
    这句可以正常运行
2. g.V('1:xxx').bothE('xx').has('xxx',gt('xxx')).otherV().values('xxx').mean() 
    当给边加上条件时，会报错，说明此时并为自动过滤掉不存在的顶点

**Comment by javeme** [comment]
@datian9966 报错的目的是为了让用户发现不存在的顶点，建议在导入数据的时候尽量导入完全，也可以在导入边的时候进行顶点的检查（通过开关打开`--check-vertex true`，不过会降低导入速度）。报错之后把顶点补全也可以。

**Comment by datian9966** [comment]
@javeme 您好 但是您看我的复现步骤里所写的  如果如您所说 报错是为了帮助用户发现不存在的顶点 那我的第一个第二个 应该都会报错才对呀？为啥第一个没有报错 而 第二个报错了？~

**Comment by javeme** [comment]
@datian9966 这里面确实有一些不一致，原因的话我解释一下，第一个查询语句`g.V('1:xxx').bothE('xx').otherV()`会被优化为`g.V('1:xxx').both('xx')`，后者会忽略不存在的顶点，就像`g.V(id)`一样如果id不存在也不会报错。
你们预期的行为是什么？由于报错和忽略的需求都有，提供配置项来自定义行为是否能接受？比如`check_adjacent_vertex_exist=true|false`

**Comment by datian9966** [comment]
@javeme 哦哦 明白了 非常感谢
关于您提出的 提供配置项 我觉得非常好 这样我可以根据我的实际需求来决定是否报错
