### ISSUE TITLE
后端为postgresSQL时，初始化失败。

### ISSUE THREAD

**Issue by tarzanfan** [hugegraph/hugegraph#838]
### Expected behavior 期望表现
希望能初始化成功

### Actual behavior 实际表现
报错：
![image](https://user-images.githubusercontent.com/43024508/72658454-386db380-39ec-11ea-8e39-b27ebab5d82d.png)

### Steps to reproduce the problem 复现步骤
1. 启动的pgsql服务中只有postgres库
2.初始化时使用的的用户时baidu123
3.提示baidu123库不存在
4.在配置项中指定postgres库后，又报错
![image](https://user-images.githubusercontent.com/43024508/72658478-884c7a80-39ec-11ea-8497-8030f5554ed3.png)
5.新建baidu123库后，去掉配置项中指定的库名
6.初始化成功

### Specifications of environment 环境信息
- hugegraph version: 0.10.4
- hugegraph backend: postgreSQL

**Comment by javeme** [comment]
@tarzanfan ok，也就是说postgre连接目前必须要存在与用户名相同的库。
@zhoney 看看能否改进

**Comment by zhoney** [comment]
fixed in #1293
