### ISSUE TITLE
gremlin查询时返回数据条数800000的限制在哪里设置

### ISSUE THREAD

**Issue by fisherinbox** [hugegraph/hugegraph#84]
### Expected behavior 期望表现
{type something here...}

### Actual behavior 实际表现
{type something here...}

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by javeme** [comment]
这是单次查询结果80w限制规则。

背景：
因为返回过多记录数会导致内存等问题，我们的建议是尽量多加查询条件以限制结果数，因为过多的最终结果对于人去分析也是很难进行的。

当然，如果是想要获取全部的数据可以通过分页API实现，请参考[分页查询](https://hugegraph.github.io/hugegraph-doc/clients/restful-api/vertex.html)

**Comment by yuyang0** [comment]
@javeme 请问下java客户端怎么分页查询？
