### ISSUE TITLE
主键的二进制为什么不是以label的id开头

### ISSUE THREAD

**Issue by RustRw** [hugegraph/hugegraph#841]
主键的二进制为什么不是以label的id开头, 而是字符串的长度开头, 如果想扫描表的话, 这样也无法做到快速过滤了, 会把全部主键扫描一遍了.

**Comment by javeme** [comment]
@RustRw 因为反序列化读的时候才可以知道读取多少字节；扫表是指扫指定label的内容吗？主键id的时候可以把同一类label放一起来优化上述场景，但是其它类型id无法这样，较难做到通用。
