### ISSUE TITLE
hubble-1.1.0 显示数据报错

### ISSUE THREAD

**Issue by fuling1999** [hugegraph/hugegraph#843]
### Expected behavior 期望表现
能够正常查询出边；

### Actual behavior 实际表现
g.E().hasLabel('注册人').limit(1)

报错：Could not write JSON: Can not write a field name, expecting a value; nested exception is com.fasterxml.jackson.core.JsonGenerationException: Can not write a field name, expecting a value

g.E().hasLabel('注册人').limit(1).inV()

正常：        {
            "id": "12:whoisguard protected",
            "label": "registrant",
            "properties": {
                "registrant_name": "whoisguard protected"
            }
        }

g.E().hasLabel('注册人').limit(1).outV()

正常：        {
            "id": "4:8as8.com",
            "label": "domain",
            "properties": {
                "status": "clientTransferProhibited https://icann.org/epp#clientTransferProhibited",
                "creation_time": "2019-01-25 16:00:00.000",
                "main_domain": "8as8.com",
                "expiration_time": "2020-01-25 16:00:00.000",
                "update_time": "2019-01-25 16:00:00.000",
                "state": "Panama",
                "domain_name_search": "8as8.com",
                "domain_name": "8as8.com"
            }
        }

查询出inV和outV之后，双击点，都可以查询出边。

### Specifications of environment 环境信息
"versions":{
"version": "v1",
"core": "0.10.4.0",
"gremlin": "3.4.3",
"api": "0.48.0.0"
}

**Comment by javeme** [comment]
@fuling1999 是仅仅某一个顶点还是所有的这类型顶点都有这个问题？比如`g.E().hasLabel('注册人').range(10, 11)`是否也有问题？

**Comment by fuling1999** [comment]
> @fuling1999 是仅仅某一个顶点还是所有的这类型顶点都有这个问题？比如`g.E().hasLabel('注册人').range(10, 11)`是否也有问题？

总是会返回相同的错误。

使用rest api返回结果如下： GET /graphs/hugegraph/graph/edges?limit=1&label=注册人

{
"edges":[
{
"id": "S4:8as8.com>28>>S12:whoisguard protected",
"label": "注册人",
"type": "edge",
"outV": "4:8as8.com",
"outVLabel": "domain",
"inV": "12:whoisguard protected",
"inVLabel": "registrant",
"properties":{"expiration_time": 1579939200000, "update_time": 1548403200000}
}
]
}

**Comment by javeme** [comment]
@Linary 看起来是Hubble后端问题

**Comment by Linary** [comment]
是hubble后端序列化顶点和边的属性时多写了一次属性的key，已经修复了。
