### ISSUE TITLE
 Gremlin RESTFul API 接口图名不能使用中划线

### ISSUE THREAD

**Issue by suesunss** [hugegraph/hugegraph#850]
### Expected behavior 期望表现

图名中包含中划线时 Gremlin RESTFul API 接口能正常访问。

### Actual behavior 实际表现

图名中包含中划线时 Gremlin RESTFul API 接口报异常。
图名定义为 `my_graph-g1`
通过 Grelmin RESTFul API 访问: 
`
GET http://127.0.0.1:8080/gremlin?gremlin=my_graph-g1.traversal().V('1:marko')
`

`
{"message":"No such property: my_graph for class: Script5","Exception-Class":"groovy.lang.MissingPropertyException","exceptions":["groovy.lang.MissingPropertyException"],"stackTrace":"groovy.lang.MissingPropertyException: No such property: my_graph for class: Script5\n\tat org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)\n\tat org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:52)\n\tat org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:307)\n\tat Script5.run(Script5.groovy:1)\n\tat org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:834)\n\tat org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:547)\n\tat javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233)\n\tat org.apache.tinkerpop.gremlin.groovy.engine.ScriptEngines.eval(ScriptEngines.java:120)\n\tat org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$2(GremlinExecutor.java:314)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat com.baidu.hugegraph.auth.HugeGraphAuthProxy$ContextTask.run(HugeGraphAuthProxy.java:282)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n"}
`

**Comment by javeme** [comment]
请尝试一下：将`my_graph-g1`改为`graph.traversal().V('1:marko')`或者`g.V('1:marko')`试试，后续我们改进一下，限制中划线作为图名称，因为groovy语法中的中划线是减号的意思。
