### ISSUE TITLE
0.10.4 版本 Long 型主键中的数字会被编码

### ISSUE THREAD

**Issue by suesunss** [hugegraph/hugegraph#852]
### Expected behavior 期望表现

数据模型中，点有一个字段是 role_id （用户 id），long 型，用这个字段作为主键建模，显示建模成功：

`
{"vertexlabels": [{"id":1,"name":"role","id_strategy":"PRIMARY_KEY","primary_keys":["role_id"],"nullable_keys":["role_level","role_gender","role_class","role_total_online_time","role_name","server"],"index_labels":["roleByRole_level","roleByRole_gender","roleByRole_class","roleByRole_total_online_time","roleByRole_name","roleByServer"],"properties":["role_id","role_level","role_gender","role_class","role_total_online_time","role_name","server"],"enable_label_index":true,"user_data":{}}]}
`

通过 RESTFful Gremlin API 查询一批点：

`curl -X GET host:port/gremlin?gremlin=mygraph.traversal().V().hasLabel('role').limit(10)`

查询结果正确显示 id 

`
{"requestId":"90facffc-fac7-4a7a-85f9-a69caa1ba28b","status":{"message":"","code":200,"attributes":{}},"result":{"data":[{"id":"1:100100203","label":"role","type":"vertex","properties":{"role_id":100100203,"role_name":"浮生若梦","server":203,"role_gender":1,"role_class":1,"role_level":76,"role_total_online_time":4603019}},{"id":"1:100100209","label":"role","type":"vertex","properties":{"role_id":100100209,"role_name":"血流成河","server":209,"role_gender":0,"role_class":4,"role_level":72,"role_total_online_time":2197938}},{"id":"1:100100232","label":"role","type":"vertex","properties":{"role_id":100100232,"role_name":"何路","server":232,"role_gender":0,"role_class":5,"role_level":76,"role_total_online_time":4400812}},{"id":"1:100100234","label":"role","type":"vertex","properties":{"role_id":100100234,"server":239,"role_gender":1,"role_class":8,"role_level":75,"role_total_online_time":4440427}},{"id":"1:100100242","label":"role","type":"vertex","properties":{"role_id":100100242,"role_name":"黎明丶醉笙","server":242,"role_gender":0,"role_class":1,"role_level":76,"role_total_online_time":5907395}},{"id":"1:100100265","label":"role","type":"vertex","properties":{"role_id":100100265,"role_name":"黑翼大魔","server":265,"role_gender":1,"role_class":6,"role_level":68,"role_total_online_time":1078503}},{"id":"1:100200206","label":"role","type":"vertex","properties":{"role_id":100200206,"role_name":"彼岸","server":206,"role_gender":1,"role_class":6,"role_level":74,"role_total_online_time":3573103}},{"id":"1:100200221","label":"role","type":"vertex","properties":{"role_id":100200221,"server":225,"role_gender":0,"role_class":4,"role_level":79,"role_total_online_time":7192436}},{"id":"1:100200251","label":"role","type":"vertex","properties":{"role_id":100200251,"role_name":"嘉佑丶七叔","server":251,"role_gender":1,"role_class":6,"role_level":69,"role_total_online_time":2061616}},{"id":"1:100200258","label":"role","type":"vertex","properties":{"role_id":100200258,"role_name":"暮辞辞凉絮","server":258,"role_gender":0,"role_class":4,"role_level":77,"role_total_online_time":4704368}}],"meta":{}}}
`

### Actual behavior 实际表现

使用 HugeGraph 0.10.4 查询出来的结果：

`
{"requestId":"ad8166ce-fcc0-43f2-a463-f0f8e33ab8db","status":{"message":"","code":200,"attributes":{}},"result":{"data":[{"id":"1:55yrXg","label":"role","type":"vertex","properties":{"role_id":100100203,"role_level":76,"role_gender":1,"role_class":1,"role_total_online_time":4603019,"role_name":"浮生若梦","server":203}},{"id":"1:55yrXm","label":"role","type":"vertex","properties":{"role_id":100100209,"role_level":72,"role_gender":0,"role_class":4,"role_total_online_time":2197938,"role_name":"血流成河","server":209}},{"id":"1:55yrY8","label":"role","type":"vertex","properties":{"role_id":100100232,"role_level":76,"role_gender":0,"role_class":5,"role_total_online_time":4400812,"role_name":"何路","server":232}},{"id":"1:55yrYA","label":"role","type":"vertex","properties":{"role_id":100100234,"role_level":75,"role_gender":1,"role_class":8,"role_total_online_time":4440427,"server":239}},{"id":"1:55yrYI","label":"role","type":"vertex","properties":{"role_id":100100242,"role_level":76,"role_gender":0,"role_class":1,"role_total_online_time":5907395,"role_name":"黎明丶醉笙","server":242}},{"id":"1:55yrYe","label":"role","type":"vertex","properties":{"role_id":100100265,"role_level":68,"role_gender":1,"role_class":6,"role_total_online_time":1078503,"role_name":"黑翼大魔","server":265}},{"id":"1:55zExE","label":"role","type":"vertex","properties":{"role_id":100200206,"role_level":74,"role_gender":1,"role_class":6,"role_total_online_time":3573103,"role_name":"彼岸","server":206}},{"id":"1:55zExT","label":"role","type":"vertex","properties":{"role_id":100200221,"role_level":79,"role_gender":0,"role_class":4,"role_total_online_time":7192436,"server":225}},{"id":"1:55zExw","label":"role","type":"vertex","properties":{"role_id":100200251,"role_level":69,"role_gender":1,"role_class":6,"role_total_online_time":2061616,"role_name":"嘉佑丶七叔","server":251}},{"id":"1:55zEy2","label":"role","type":"vertex","properties":{"role_id":100200258,"role_level":77,"role_gender":0,"role_class":4,"role_total_online_time":4704368,"role_name":"暮辞辞凉絮","server":258}}],"meta":{}}}
`

id 变成了一个编码过后的字符串。

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by javeme** [comment]
@suesunss 如果使用主键ID策略，则会被编码优化（我们的假设是用户不依赖于id内部格式的含义），但是依然可以按照主键属性方式来查询`g.V().hasLabel('role').has('role_id',123456L)`。如果期望保留id为原始的属性值，则可以使用CUSTOMIZE_NUMBER策略，各种策略介绍如下：

interface | idStrategy | description
-- | -- | --
useAutomaticId | AUTOMATIC | generate id automaticly by Snowflake algorithom
useCustomizeStringId | CUSTOMIZE_STRING | passed id by user, must be string type
useCustomizeNumberId | CUSTOMIZE_NUMBER | passed id by user, must be number type
usePrimaryKeyId | PRIMARY_KEY | choose some important prop as primary key to splice id

**Comment by suesunss** [comment]
@javeme 谢谢回复，看起来不影响查询。

**Comment by suesunss** [comment]
@javeme 这种编码的情况，好像有个问题。

假设我有一条边：`S1:100100234>1>2019-01-25 01:10:29>S1:112600234`
用 `g.E('S1:100100234>1>2019-01-25 01:10:29>S1:112600234')` 可以查到这条边。
然后用 `g.V().hasLabel('role').has('role_id', 112600234)` 也可以定位入射点。
但是当我执行 `g.V().hasLabel('role').has('role_id', 112600234).bothE()`，查询的结果为空集合。我们注意到边的 id 还是用的未经编码的 `role_id`，是这个问题吗？

PS：这种情况下，如果主键是 number，理论上 studio 也不能用了？

**Comment by javeme** [comment]
@suesunss  请检查一下`100100234`这个点看看是否存在：`g.V().hasLabel('role').has('role_id', 100100234)`。不过看起来这种情况查不出来可能是个Bug。

**Comment by suesunss** [comment]
@javeme 

测试了下，出射点和入射点都可以查到。

**Comment by javeme** [comment]
@suesunss 好的，多谢反馈。已标记为BUG，我们会尽快修复

**Comment by javeme** [comment]
@suesunss 我这边验证了一下边查询，结果是正常的。

> 假设我有一条边：S1:100100234>1>2019-01-25 01:10:29>S1:112600234

这个假设的是不成立的，在边ID里面也是会被编码的。

可以尝试在studio中执行如下脚本进行验证：
```groovy
schema=graph.schema()

schema.propertyKey("role_id").asLong()
      .ifNotExist().create();
schema.propertyKey("name").asText()
      .ifNotExist().create();
schema.vertexLabel("person").properties("role_id","name").primaryKeys("role_id")
      .ifNotExist().create();
schema.edgeLabel("follow").link("person","person")
      .ifNotExist().create();

v1=graph.addVertex(T.label,'person','role_id',123,'name','张三')
v2=graph.addVertex(T.label,'person','role_id',456,'name','李四')
v1.addEdge('follow',v2)
```
查询结果：
![image](https://user-images.githubusercontent.com/9625821/75111843-27fac980-5679-11ea-9cd7-5a7f7a8c8095.png)

其它查询语句：
```groovy
g.V().hasLabel('person')
g.V().hasLabel('person').has('role_id',123)

g.V().hasLabel('person').bothE()
g.V().hasLabel('person').has('role_id',123).bothE()

v=g.V().hasLabel('person').next()
g.V(v).bothE()
```

**Comment by suesunss** [comment]
@javeme 感谢回复。

我这边测试版本：
- HugeGraph （0.10.4）
- HugeGraph-Loader （0.10.1）
- RocksDB 

经测试，我这边的边是没有编码过的，schema 通过如下 groovy 脚本构造：

```groovy
schema.propertyKey("role_id").asLong().ifNotExist().create()
schema.propertyKey("role_name").asText().ifNotExist().create()
schema.propertyKey("role_class").asInt().ifNotExist().create()
schema.propertyKey("role_gender").asInt().ifNotExist().create()
schema.propertyKey("role_level").asInt().ifNotExist().create()
schema.propertyKey("server").asInt().ifNotExist().create()
schema.vertexLabel("role").properties("role_id","role_name","role_class","role_gender","role_level","server").nullableKeys("role_name","role_class","role_gender","role_level","server").primaryKeys("role_id").ifNotExist().create()
// 省略点 indexLabels
schema.propertyKey("money").asLong().ifNotExist().create()
schema.propertyKey("datetime").asText().ifNotExist().create()
schema.propertyKey("tradetype").asInt().ifNotExist().create()
schema.edgeLabel("trade_to").multiTimes().sourceLabel("role").targetLabel("role").properties("money","datetime","tradetype","server").nullableKeys("money","tradetype","server").sortKeys("datetime").ifNotExist().create()
// 省略边 indexLabels
```
主要的不同点是：**我这里的边使用了 `datetime` 作为 `sortKeys`。**

测试数据样例：

`vertices.json`
```
{"server":239,"role_gender":1,"role_id":100100234,"role_class":6,"role_level":72}
{"server":215,"role_gender":0,"role_id":112600234,"role_class":5,"role_level":72}
```
`edges.json`
```
{"server":239,"tradetype":1,"datetime":"2019-01-25 01:10:29","money":0,"roleiddst":112600234,"roleidsrc":100100234}
```

`struct.json`

```json
{
    "vertices": [
        {
            "label": "role",
            "input": {
                "type": "file",
                "path": "/{{my_path}}/vertices.json",
                "format": "JSON",
                "charset": "UTF-8"
            }
        }
    ],
    "edges": [
        {
            "label": "trade_to",
            "source": [
                "roleidsrc"
            ],
            "target": [
                "roleiddst"
            ],
            "input": {
                "type": "file",
                "path": "/{{my_path}}/edges.json",
                "format": "JSON",
                "charset": "UTF-8"
            },
            "field_mapping": {
                "roleidsrc": "role_id",
                "roleiddst": "role_id"
            }
        }
    ]
}
```

通过 HugeGraph-Loader 导入成功：

```txt
vertices has been loaded : 2
edges has been loaded : 1
--------------------------------------------------
total vertex metrics
parse:
    parse success           : 2
    parse failure           : 0
    parse time              : 0.027s
    parse rate              : 74(vertices/s)
load:
    load success            : 2
    load failure            : 0
    load time               : 0.066s
    load rate               : 30(vertices/s)
--------------------------------------------------
total edge metrics
parse:
    parse success           : 1
    parse failure           : 0
    parse time              : 0.013s
    parse rate              : 76(edges/s)
load:
    load success            : 1
    load failure            : 0
    load time               : 0.043s
    load rate               : 23(edges/s)
```

通过 Vertices RestFul API:

```txt
http://{{hugegraph_server_ip}}:{{hugegraph_server_port}}/graphs/{{graph_name}}/graph/vertices?page&limit=3
```

返回：

```json
{
    "vertices": [
        {
            "id": "1:55yrYA",
            "label": "role",
            "type": "vertex",
            "properties": {
                "role_id": 100100234,
                "role_class": 6,
                "role_gender": 1,
                "role_level": 72,
                "server": 239
            }
        },
        {
            "id": "1:56iYIf",
            "label": "role",
            "type": "vertex",
            "properties": {
                "role_id": 112600234,
                "role_class": 5,
                "role_gender": 0,
                "role_level": 72,
                "server": 215
            }
        }
    ],
    "page": null
}
```

通过  Edges RestFul API：

```txt
http://{{hugegraph_server_ip}}:{{hugegraph_server_port}}/graphs/{{graph_name}}/graph/edges?page&limit=3`
```

查询的边样例如下：
```json
{
    "edges": [
        {
            "id": "S1:100100234>1>2019-01-25 01:10:29>S1:112600234",
            "label": "trade_to",
            "type": "edge",
            "outV": "1:100100234",
            "outVLabel": "role",
            "inV": "1:112600234",
            "inVLabel": "role",
            "properties": {
                "server": 239,
                "money": 0,
                "datetime": "2019-01-25 01:10:29",
                "tradetype": 1
            }
        }
    ],
    "page": null
}
```

**可见边并未编码**。

使用 Gremlin RestFul API 

```txt
http://{{hugegraph_server_ip}}:{{hugegraph_server_port}}/gremlin?gremlin={{graph_name}}.traversal().E('S1:100100234>1>2019-01-25 01:10:29>S1:112600234')
```

也可以成功查询到对应的边：

```json
{
    "requestId": "ebc964fe-6d13-4b46-bf1f-bc2bcc5083e4",
    "status": {
        "message": "",
        "code": 200,
        "attributes": {}
    },
    "result": {
        "data": [
            {
                "id": "S1:100100234>1>2019-01-25 01:10:29>S1:112600234",
                "label": "trade_to",
                "type": "edge",
                "outV": "1:100100234",
                "outVLabel": "role",
                "inV": "1:112600234",
                "inVLabel": "role",
                "properties": {
                    "server": 239,
                    "tradetype": 1,
                    "item": true,
                    "datetime": "2019-01-25 01:10:29",
                    "money": 0
                }
            }
        ],
        "meta": {}
    }
}
```

使用 Gremlin RestFul API：

```txt
http://{{hugegraph_server_ip}}:{{hugegraph_server_port}}/gremlin?gremlin={{graph_name}}.traversal().V().hasLabel('role').has('role_id', 100100234)
```

可以查到对应的点：

```json
{
    "requestId": "6d580f50-dd4e-4a32-be54-997e93cb859b",
    "status": {
        "message": "",
        "code": 200,
        "attributes": {}
    },
    "result": {
        "data": [
            {
                "id": "1:55yrYA",
                "label": "role",
                "type": "vertex",
                "properties": {
                    "role_id": 100100234,
                    "role_class": 6,
                    "role_gender": 1,
                    "role_level": 72,
                    "server": 239
                }
            }
        ],
        "meta": {}
    }
}
```

使用 Gremlin RestFul API：

```txt
http://{{hugegraph_server_ip}}:{{hugegraph_server_port}}/gremlin?gremlin={{graph_name}}.traversal().V().hasLabel('role').has('role_id', 100100234).bothE()
```

查询的结果：

```json
{
    "requestId": "fb751ec6-d3e2-4942-9559-540267f3f87c",
    "status": {
        "message": "",
        "code": 200,
        "attributes": {}
    },
    "result": {
        "data": [],
        "meta": {}
    }
}
```
查询不到对应的邻接边。

**Comment by javeme** [comment]
@suesunss 那可能是loader导入的时候有问题，方便的话验证一下我上面贴的代码能否正常运行？

@Linary 请检查下在这种场景下loader是否有Bug?

**Comment by suesunss** [comment]
@javeme 可以正常运行，且边被正常编码。

![image](https://user-images.githubusercontent.com/22719158/75124752-23bbc400-56ec-11ea-9cc0-edbdd7f9e14a.png)

**Comment by javeme** [comment]
@suesunss 第2个问题是Loader的bug，导入的时候没有编码导致的，目前已修复。

**Comment by suesunss** [comment]
@javeme 感谢修复，我再尝试一下。
