### ISSUE TITLE
支持Greenplum 6?

### ISSUE THREAD

**Issue by melin** [hugegraph/hugegraph#853]
支持Greenplum  6.0 以上的版本吗？

**Comment by javeme** [comment]
HugeGraph支持PG，但是没有测试过GP，GP理论上是支持的，可以尝：

1. 下载GP驱动jar，并放到hugegraph的lib目录下。
2. 修改hugegraph配置文件，加载GP驱动，重新启动hugegraph服务即可。

```
jdbc.driver=com.pivotal.jdbc.GreenplumDriver
jdbc.url=jdbc:pivotal:greenplum://host:port;DatabaseName=xx
```
