### ISSUE TITLE
hugegraph 如何序列化(serialization)图呢

### ISSUE THREAD

**Issue by chencjiajy** [hugegraph/hugegraph#856]
### Expected behavior 期望表现
想将图保存成GraphSON 格式，在studio中使用
```
graph.io(graphson()).writeGraph("my-graph.json")
```

### Actual behavior 实际表现
报错
> Error!
Not allowed to write file via Gremlin

请问hugegraph 如何实现将图保存成相应的格式呢？ 在API中暂时也没有搜到

**Comment by javeme** [comment]
@chencjiajy 可以使用tools的[backup或dump命令](https://hugegraph.github.io/hugegraph-doc/quickstart/hugegraph-tools.html)，或者直接使用api也可以。另外即将发布的新版Hubble界面也支持保存为Json文件。

**Comment by chencjiajy** [comment]
@javeme 请问api是哪个,我没找到

**Comment by javeme** [comment]
@chencjiajy 这里说的api并不是说直接获取到一个文件，而是说通过api获取到顶点和边（返回结果是json格式），然后保存为json文件。比如：
`http://localhost:8080/graphs/hugegraph/graph/vertices`
`http://localhost:8080/graphs/hugegraph/graph/edges`
