### ISSUE TITLE
no gremlin script supplied

### ISSUE THREAD

**Issue by eternalxj** [hugegraph/hugegraph#860]
你好，使用10版本加载example数据，具体报错如下，请问如何处理

hugegraph-loader-0.10.0]$ bin/hugegraph-loader -g hugegraph -f data/example/example.json -s data/example/schema.groovy -h 192.168.146.129 -p 8182

ERROR: Failed to load
Exception in thread "main" null: no gremlin script supplied
	at com.baidu.hugegraph.exception.ServerException.fromResponse(ServerException.java:44)
	at com.baidu.hugegraph.client.RestClient.checkStatus(RestClient.java:100)
	at com.baidu.hugegraph.rest.RestClient.get(RestClient.java:193)
	at com.baidu.hugegraph.api.version.VersionAPI.get(VersionAPI.java:41)
	at com.baidu.hugegraph.driver.VersionManager.getApiVersion(VersionManager.java:45)
	at com.baidu.hugegraph.driver.HugeClient.checkServerApiVersion(HugeClient.java:122)
	at com.baidu.hugegraph.driver.HugeClient.initManagers(HugeClient.java:108)
	at com.baidu.hugegraph.driver.HugeClient.<init>(HugeClient.java:72)
	at com.baidu.hugegraph.loader.util.HugeClientHolder.newHugeClient(HugeClientHolder.java:45)
	at com.baidu.hugegraph.loader.util.HugeClientHolder.get(HugeClientHolder.java:33)
	at com.baidu.hugegraph.loader.HugeGraphLoader.createSchema(HugeGraphLoader.java:108)
	at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:85)
	at com.baidu.hugegraph.loader.HugeGraphLoader.main(HugeGraphLoader.java:66)

**Comment by eternalxj** [comment]
@Linary @javeme 帮忙看下哈

**Comment by eternalxj** [comment]
配置如下

**Comment by eternalxj** [comment]
#host: 127.0.0.1
#port: 8182
host: 192.168.146.129
port: 8182
# timeout in ms of gremlin query
scriptEvaluationTimeout: 30000

# If you want to start gremlin-server for gremlin-console(web-socket),
# please change `HttpChannelizer` to `WebSocketChannelizer` or comment this line.
channelizer: org.apache.tinkerpop.gremlin.server.channel.HttpChannelizer
graphs: {
  hugegraph: conf/hugegraph.properties
}
scriptEngines: {
  gremlin-groovy: {
    plugins: {
      com.baidu.hugegraph.plugin.HugeGraphGremlinPlugin: {},
      org.apache.tinkerpop.gremlin.server.jsr223.GremlinServerGremlinPlugin: {},
      org.apache.tinkerpop.gremlin.jsr223.ImportGremlinPlugin: {
        classImports: [
          java.lang.Math,
          com.baidu.hugegraph.util.DateUtil,
          com.baidu.hugegraph.traversal.optimize.Text
        ],
        methodImports: [java.lang.Math#*]
      },
      org.apache.tinkerpop.gremlin.jsr223.ScriptFileGremlinPlugin: {
        files: [scripts/empty-sample.groovy]
      }
    }
  }
}
serializers:
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GryoLiteMessageSerializerV1d0,
      config: {
        serializeResultToString: false,
        ioRegistries: [com.baidu.hugegraph.io.HugeGraphIoRegistry]
      }
  }
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GraphBinaryMessageSerializerV1,
      config: {
        serializeResultToString: false,
        ioRegistries: [com.baidu.hugegraph.io.HugeGraphIoRegistry]
      }
  }
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV1d0,
      config: {
        serializeResultToString: false,
        ioRegistries: [com.baidu.hugegraph.io.HugeGraphIoRegistry]
      }
  }
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV2d0,
      config: {
        serializeResultToString: false,
        ioRegistries: [com.baidu.hugegraph.io.HugeGraphIoRegistry]
      }
  }
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV3d0,
      config: {
        serializeResultToString: false,
        ioRegistries: [com.baidu.hugegraph.io.HugeGraphIoRegistry]
      }
  }
metrics: {
  consoleReporter: {enabled: false, interval: 180000},
  csvReporter: {enabled: true, interval: 180000, fileName: /tmp/gremlin-server-metrics.csv},
  jmxReporter: {enabled: false},
  slf4jReporter: {enabled: false, interval: 180000},
  gangliaReporter: {enabled: false, interval: 180000, addressingMode: MULTICAST},
  graphiteReporter: {enabled: false, interval: 180000}
}
maxInitialLineLength: 4096
maxHeaderSize: 8192
maxChunkSize: 8192
maxContentLength: 65536
maxAccumulationBufferComponents: 1024
resultIterationBatchSize: 64
writeBufferLowWaterMark: 32768
writeBufferHighWaterMark: 65536
ssl: {
  enabled: false
}

**Comment by eternalxj** [comment]
# bind url
gremlinserver.url=http://192.168.146.129:8182
restserver.url=http://192.168.146.129:8080
# gremlin server url, need to be consistent with host and port in gremlin-server.yaml
#gremlinserver.url=http://127.0.0.1:8182

# graphs list with pair NAME:CONF_PATH
graphs=[hugegraph:conf/hugegraph.properties]

# authentication
#auth.require_authentication=
#auth.admin_token=
#auth.user_tokens=[]

**Comment by eternalxj** [comment]
cat  hugegraph.properties
# gremlin entrence to create graph
gremlin.graph=com.baidu.hugegraph.HugeFactory


backend=rocksdb
serializer=binary

store=hugegraph

search.text_analyzer=jieba
search.text_analyzer_mode=INDEX


# cassandra backend config
cassandra.host=localhost
cassandra.port=9042
cassandra.username=
cassandra.password=

**Comment by eternalxj** [comment]
还有 这种导入数据报错的情况下用studio的时候 执行不了gremlin语言，一执行就卡住，不知道什么原因，配置是笔记本的虚拟机，3g内存左右

**Comment by javeme** [comment]
> hugegraph-loader-0.10.0]$ bin/hugegraph-loader -g hugegraph -f data/example/example.json -s data/example/schema.groovy -h 192.168.146.129 -p 8182

@eternalxj 导入不能使用8182端口，而是需要使用8080端口：`-p 8080`

**Comment by eternalxj** [comment]
多谢，导入的问题解决的 接下来还有个问题 要请教，hugegraph-studio-0.10.0 我导入完样例数据 ，然后用虚拟机的火狐浏览器 访问 http://192.168.146.129:8088 随便跑一个命令，页面就死掉了 @javeme

**Comment by eternalxj** [comment]
可以给一些比较详细的性能和配置测试数据吗，想在部门看看用hugegraph做点事情哈 @javeme

**Comment by javeme** [comment]
@eternalxj 导入数据可以参考一下 https://blog.csdn.net/u010260089/article/details/84982777。
使用场景正好最近我们对新冠肺炎病例图谱做了一个案例，可以参考：https://zhuanlan.zhihu.com/p/108412973，HugeGraph公众号上发布的文章说明了建模过程。
