### ISSUE TITLE
range查询不同范围得到的结果相同

### ISSUE THREAD

**Issue by 860960342** [hugegraph/hugegraph#864]
hugegraph-v0.10 + hbase
顶点量100w，边量1000w

### Expected behavior 期望表现
使用range查询不同范围的顶点的has_Value属性值：
g.V().has('TEST','has_Category','success').range(0,5).values('has_Value')
g.V().has('TEST','has_Category','success').range(10,15).values('has_Value')
正常情况下这两个语句得到的结果是不一样的

### Actual behavior 实际表现
实际上这两个语句得到的结果是完全相同的，换成其他的范围得到的结果还是一样的。

这种情况出现的比较随机，不一定能完全复现
请问是否有人遇到过类似的情况，可以如何解决？

**Comment by javeme** [comment]
@860960342 是否有部分`has_Value`属性没有值？能否提供更多的信息以帮助定位？

**Comment by 860960342** [comment]
@javeme 可以确定的是TEST类型顶点每个都有has_Value属性值且值不重复，TEST类型顶点量有10w
中间没有做过大批量增加和删除操作，但做过频繁查询（约每秒4次的频率，调用的gremlin-api，查询语句为kgtest.traversal().V().hasId('%s').group().by('has_Value').by(outE('TEST-TEST').has('relationship',within('ip','domain','url')).count())）

当前用 range方法查顶点得到的都是一样的：
例如使用g.V().has('TEST','has_Category','success').range(0,10)可以得到前10个不同的顶点，然后用range(0,5)得到前5个顶点（符合预期），但用range(5,10)得到的还是前5个顶点（正常应该是后5个顶点）
无论range(x, y)中x, y取值多少，得到的顶点结果始终是range(0, (y-x))的结果 。

**Comment by javeme** [comment]
@lxb1111 我目前没有复现这个问题，你看看hbase后端能否复现？

**Comment by lxb1111** [comment]
好的，我尝试复现

**Comment by lxb1111** [comment]
@860960342 目前基于hbase后端这个问题已经复现，会排期尽快解决。

**Comment by 860960342** [comment]
@lxb1111请问这个问题已经解决了吗？我们现在是需要等新版本的hugegraph发布，还是可以怎样操作来规避这个问题？

**Comment by javeme** [comment]
@860960342 问题已经解决了，需要等待新版本发布，或者手动打包[release-0.11](https://github.com/hugegraph/hugegraph/tree/release-0.11)分枝代码。可以使用分页来规避

**Comment by 860960342** [comment]
@javeme 好的，谢谢~

**Comment by javeme** [comment]
cherry-pick #1047
