### ISSUE TITLE
HugeGraph从0.9.2升级到0.10.4的问题

### ISSUE THREAD

**Issue by suesunss** [hugegraph/hugegraph#865]
### Expected behavior 期望表现
0.9.2到0.10.4可以平滑升级。

### Actual behavior 实际表现
升级到0.10.4以后，原来的 rocksdb 可以打开，但是无法查询到数据。

### Steps to reproduce the problem 复现步骤

1. 使用 HugeGraph-0.9.2 导入数据，成功查询到数据
2. 升级到 HugeGraph-0.10.4，init 成功执行，HugeGraph 成功启动
3. 使用 gremlin 查询数据，查询不到数据

问题：
1. 这两个版本，还是需要使用 hg-tools 进行备份恢复吗？
2. hg-tools 1.4.0 支持备份 0.9.2 的数据并回复到 0.10.4 吗？

**Comment by javeme** [comment]
@suesunss 分别解答下：
1. 是的，需要使用 hg-tools 进行备份恢复。
2. hg-tools 1.4.0 支持备份 0.9.2 的数据并恢复到 0.10.4。

两个版本之间的数据格式如果改变了则无法直接使用原来数据，后续我们会尽可能保持对历史版本数据的兼容性。

**Comment by suesunss** [comment]
@javeme 了解，感谢回复。
