### ISSUE TITLE
getVertex报错

### ISSUE THREAD

**Issue by wuzigod** [hugegraph/hugegraph#869]
### Expected behavior 期望表现
通过getVertex(vertexID)能正常获取顶点

### Actual behavior 实际表现
报错，javax.ws.rs.NotFoundException: VERTEX with id '"1:642637192506268962"' does not exist；
使用该id从 hugegraph-studio上查询，可以查到这个顶点

### Steps to reproduce the problem 复现步骤
我在向hugegraph模拟图数据，大致流程为：
1.通过getOrCreate方法创建顶点，并使用Map<cardID, vertexID>,映射顶点ID，如果顶点不存在则创建，存在则通过vertexID获取
2.程序执行一会就会报错，多次执行都不成功
3.使用rocksdb作为存储后端可以正常执行，使用Cassandra就会报错

getOrCreate方法大致实现：
 Map<String, Object> cache = new HashMap<String, Object>();
GraphManager graph = hugeClient.graph()；

protected Vertex getOrCreate(List<Object> value, String label) {
        Vertex vertex;
        String cardID = (String) value.get(2);
              if (cache.containsKey(cardID)) {
                   Object vertexID = cache.get(cardID);
                    vertex = graph.getVertex(vertexID);
                } else {
                    vertex = graph.addVertex(T.label, label, "name", value.get(0), "gender", value.get(1),
                            "cardID", cardID, "phoneNO", value.get(3));
                    cache.put(cardID, vertex.id());
                }
}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: 0.9.2
- operating system: centos 7.5
- hugegraph backend: apache-cassandra-3.11.4, cluster with 3 nodes

**Comment by javeme** [comment]
@userhtm 跑多少条数据之后会报错？另外能否提供一下数据样例以方便复现分析

**Comment by userhtm** [comment]
@javeme 感谢回复
1.每次报错时的条数都不一样，最近一次是跑了6w的顶点，4.5w条边
2.数据样例：
（1）顶点：
> id	label	properties
1:422610198012131387	person	{"name":"戚会思","gender":"男","cardID":"422610198012131387","phoneNO":"15500401626"}
1:222731195111282603	person	{"name":"吴博","gender":"男","cardID":"222731195111282603","phoneNO":"15506412639"}

（2）边

> id	label	source	target	properties
S1:422610198012131387>2>>S1:222731195111282603	call	1:422610198012131387	1:222731195111282603	{"callTime":"2020-01-01 00:00:00","duration":120}

**Comment by Linary** [comment]
@userhtm 你好，能给出一段复现此问题的最小版本的代码吗？

**Comment by userhtm** [comment]
@Linary 你好
1.我是先取一条完整的数据进行插入的，包括源顶点、目标定点、连接两个顶点的边；然后调用GetOrCreate()方法，获取或创建两个顶点，再调用relateNodes()创建边
2.调用方式大致如下：
`
    
    //遍历数据集
    for (...){
        //获取源顶点和目标定点
        Vertex sourceNode = getOrCreate(scrVertexListData, srcVertexLabel);
        Vertex destNode = getOrCreate(destVertexListData, destVertexLabel);
        //创建连接两个顶点的边
        relateNodes(sourceNode, destNode, edgeLabel, edgeProperties);
    }
`

3.relateNodes方法
` 
    
    List<Edge> edges = new LinkedList<>();
    @Override
    protected void relateNodes(Vertex src, Vertex dest, String edgeLabel, List<Object> properties) {
        Edge edge = new Edge(edgeLabel).source(src).target(dest).
                property("callTime", properties.get(0)).property("duration", properties.get(1));
        edges.add(edge);
         //每500条数据执行一次插入
        if (edges.size() % batchSize == 0) {
            //插入边
            graph.addEdges(edges);
            edges = new LinkedList<>();
        }
    }`
