### ISSUE TITLE
能不能改一改hugegraph-common获取version的方式？

### ISSUE THREAD

**Issue by yuyang0** [hugegraph/hugegraph#87]
现在这种做法我想把使用了hugegraph-client的项目打包成jar都不行

**Comment by javeme** [comment]
多谢反馈，希望能详细的说明一下原因。我的理解是你想把这个项目打成一个all-in-one的Jar包是吗？我们建议的方式是通过maven来管理依赖包，如果一定要打成一个离线包，那么建议以lib的方式动态加载各依赖Jar包。
