### ISSUE TITLE
Optimize the semantics of ifNotExist

### ISSUE THREAD

**Issue by Linary** [hugegraph/hugegraph#870]

**Comment by javeme** [comment]
check two schema all the same when create with ifNotExist().
to avoid issues like #977

**Comment by houzhizhen** [comment]
Check for 4 types of schema: propertyKey,vertexLabel,indexLabel,and edgeLabel.
If the two or more create statements as the code follows are identical, the system will only create one quietly.
```
        schema.propertyKey("name").asText().ifNotExist().create();
        schema.propertyKey("name").asText().checkExist(false).create();
```

If the two or more create statements as the code follows with same name and at least one property different, the system will throw ExistedException.

```
        schema.propertyKey("name").asText().ifNotExist().create();
        schema.propertyKey("name").asDouble().checkExist(false).create();
```

**Comment by javeme** [comment]
There is a bug executing the following statement twice:
```java
graph.schema().vertexLabel('person').useCustomizeStringId().ifNotExist().create();
graph.schema().edgeLabel('next').sourceLabel('person').targetLabel('person').ifNotExist().create();
```
![image](https://user-images.githubusercontent.com/9625821/84663050-38e48900-af4f-11ea-91de-c59541c71d65.png)
