### ISSUE TITLE
如何创建edgeLabel，既可以连接A到B，也可以连接B到A

### ISSUE THREAD

**Issue by youngkangrui** [hugegraph/hugegraph#881]
hugeGraph.schema().edgeLabel("RELATE34").link("USER","GPS").create()
这种做法只能支持从USER到GPS

**Comment by javeme** [comment]
@youngkangrui 目前一个EdgeLabel只能描述一对VertexLabel。
如果只是需要反向查询的话，有一个EdgeLabel就可以满足了，比如`g.V("GPS-1").in("RELATE34")`
