### ISSUE TITLE
顶点主键定义为Int类型，使用loader 导入之后，显示的id是随机的字符串

### ISSUE THREAD

**Issue by chencjiajy** [hugegraph/hugegraph#887]
### Expected behavior 期望表现

定义如下节点
```
schema.propertyKey("programDatapointId").asInt().ifNotExist().create();
schema.vertexLabel("Program")
        .properties("programDatapointId", "type")
        .primaryKeys("programDatapointId")
        .ifNotExist()
        .create();
```
比如programDatapointId为4003， 希望得到的id类似于“14:4003”

### Actual behavior 实际表现
得到的实际id为“14:2zZ”
这样本来应该链接到`Program`节点的关系在图中都没有在图中正常存储，无法得到`Program`相关的关系

### Steps to reproduce the problem 复现步骤
设计schema 将一个节点的主键设置为Int类型，并设计一些与这个节点相连的关系就可以复现了

### Specifications of environment 环境信息
- hugegraph version: 0.10.4
- hugegraph backend: hbase 或rocktDB

**Comment by javeme** [comment]
@chencjiajy 这个是预期的，详细信息请参考下：https://github.com/hugegraph/hugegraph/issues/852

**Comment by chencjiajy** [comment]
多谢，总结起来就是：
1. 显示字符串是因为hugegraph 编码了，这是正常的。
2. 但是loader 导入之后，相应边在studio中没有显示，是因为loader 的bug，目前已经修复了
