### ISSUE TITLE
请教：能否提供backen为mysql时的表结构设计文档？

### ISSUE THREAD

**Issue by xpleaf** [hugegraph/hugegraph#899]
如题，可以提供这样一份文档吗？
因为实际上想做一些定制修改以更好支持其它RDB的一些特性，但对表结构这一块的设计缺乏全局性的认识。
**如能提供，不胜感激！**

**Comment by javeme** [comment]
@xpleaf 核心表结构可以参考下这个边邻接表：
![image](https://user-images.githubusercontent.com/9625821/76856909-4aa28b80-688f-11ea-813f-e9dcec312008.png)

设计文档我们后续会整理好进行公布，如果有什么具体问题欢迎交流。

**Comment by xpleaf** [comment]
@javeme 好的，非常感谢！也非常期待！
