### ISSUE TITLE
本机外机器通过studio展示报错：java.net.ConnectException: Connection refused (Connection refused)

### ISSUE THREAD

**Issue by tl890216** [hugegraph/hugegraph#90]
### Expected behavior 期望表现

id	label	properties
3:lop	software	{"price":[{"id":"3:lop>price","value":328}],"name":[{"id":"3:lop>name","value":"lop"}],"lang":[{"id":"3:lop>lang","value":"java"}]}
2:josh	person	{"city":[{"id":"2:josh>city","value":"Beijing"}],"name":[{"id":"2:josh>name","value":"josh"}],"age":[{"id":"2:josh>age","value":32}]}
2:marko	person	{"city":[{"id":"2:marko>city","value":"Beijing"}],"name":[{"id":"2:marko>name","value":"marko"}],"age":[{"id":"2:marko>age","value":29}]}
2:peter	person	{"city":[{"id":"2:peter>city","value":"Shanghai"}],"name":[{"id":"2:peter>name","value":"peter"}],"age":[{"id":"2:peter>age","value":35}]}
2:vadas	person	{"city":[{"id":"2:vadas>city","value":"Hongkong"}],"name":[{"id":"2:vadas>name","value":"vadas"}],"age":[{"id":"2:vadas>age","value":27}]}
3:ripple	software	{"price":[{"id":"3:ripple>price","value":199}],"name":[{"id":"3:ripple>name","value":"ripple"}],"lang":[{"id":"3:ripple>lang","value":"java"}]}
2:li,nary	person	{"city":[{"id":"2:li,nary>city","value":"Wu,han"}],"name":[{"id":"2:li,nary>name","value":"li,nary"}],"age":[{"id":"2:li,nary>age","value":26}]}

### Actual behavior 实际表现

Error!
java.net.ConnectException: Connection refused (Connection refused)

### Steps to reproduce the problem 复现步骤

使用本机访问studio查询展示没有问题，使用其他机器访问报错：java.net.ConnectException: Connection refused (Connection refused)

restserver的ip已确定修改为实际ip，其他机器通过restful访问可以正常返回数据

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: v0.7.4
- operating system: centos 7.4, 32 CPUs, 256G RAM
- hugegraph backend: hbase, cluster with 20 nodes

**Comment by Linary** [comment]
感谢您的反馈，请问studio的配置文件有修改`graph.server.host`和`graph.server.port`为实际ip和port吗？

**Comment by tl890216** [comment]
> 感谢您的反馈，请问studio的配置文件有修改`graph.server.host`和`graph.server.port`为实际ip和port吗？

改了的

**Comment by javeme** [comment]
@tl890216 方便贴一下hugegraph-server和hugegraph-studio的配置文件吗？另外修改完studio配置文件后是否重启了studio服务？
