### ISSUE TITLE
请教：能否提供backend为hbase时的表结构设计文档？

### ISSUE THREAD

**Issue by youngkangrui** [hugegraph/hugegraph#901]

**Comment by redsnow1992** [comment]
+1

**Comment by javeme** [comment]
@youngkangrui @redsnow1992 可以的，整理好会更新到文档中。参考 https://github.com/hugegraph/hugegraph/issues/899#issuecomment-600050895

**Comment by redsnow1992** [comment]
@javeme  Thx
