### ISSUE TITLE
创建了索引，但是gremlin 查询字段为空的数据的时候，会报错没有创建索引

### ISSUE THREAD

**Issue by chencjiajy** [hugegraph/hugegraph#902]
### Expected behavior 期望表现
假设定义了如下
```groovy
schema.propertyKey("name").asText().ifNotExist().create();
schema.propertyKey("city").asText().ifNotExist().create();
schema.vertexLabel("Person")
       .useCustomizeNumberId()
       .properties("name", "city")
       .nullableKeys("city")
       .ifNotExist()
       .create();
schema.indexLabel("PersonByCity").onV("Person").by("city").secondary().ifNotExist().create();
```
查询如下语句可以正常运行
```groovy
g.V().hasLabel('Person').has('city', eq('')).count() 
```
当查询以下不等于''值时报错`Don't accept query based on properties [city] that are not indexed in label 'Person', may not match secondary/range condition`
```groovy
g.V().hasLabel('Person').has('city', neq('')).count() 
```
### Actual behavior 实际表现
报错
`Don't accept query based on properties [city] that are not indexed in label 'Person', may not match secondary/range condition
`

### Specifications of environment 环境信息
- hugegraph version: 0.10.4

**Comment by javeme** [comment]
@chencjiajy 这个是预期的行为，因为目前还不支持neq索引。

**Comment by chencjiajy** [comment]
那你们啥时候支持呢？
有没有哪里记录了什么索引操作支不支持？在文档中没有搜索到
