### ISSUE TITLE
基于HugeGraph重新定义后端存储的表结构是否可行？

### ISSUE THREAD

**Issue by xpleaf** [hugegraph/hugegraph#908]
MySQL作为后端存储引擎时的设计思路是一个DB一个图，但受限于我的场景，只能有一个DB的提供，比如HugeGraph_DB。
我在考虑是否能够重新设计一下存储图的表结构，以支持在一个DB里支持多个图的存储：
1.每个图都有独立的表来存储其自身的顶点和边等信息；
2.用户在创建图时可以指定特定的表来存储其图信息；
其实主要是第1点，因为在我的场景中，用户会有大量的创建图和删除图的操作。
也尝试过改造MySQL的代码，但发现不好做。
实际上我这种改造基于HugeGraph本身的架构特点的话，是否行得通呢？

**希望可以给点建议，非常感谢！**

**Comment by javeme** [comment]
@xpleaf 是的，设计上是一个图实例对应一个DB。如果需要多个图存到一个DB里，这是一个架构上的改动。提供两个思路：

- 如果修改HugeGraph代码的话，可以在表名之前在家图名前缀。修改的内容肯定是不小的，另外需要考虑到初始化和清除的大流程差异。
- 受限于一个DB，是否可以在同一个图中，使用子图来存储数据，在schema上做到隔离就OK。

另外，我有一个疑问：为什么会有一个DB限制，并且还需要大量的创建图和删除图呢？

**Comment by xpleaf** [comment]
@javeme 我们这边产品和用户驱动开发占的因素稍微多一些，从产品和用户反馈来看，他们确实有需要实现这样的功能。**非常感谢提供的思路！后面我结合源码分析一下，也趁这个机会学习一下HugeGraph优秀的代码和架构设计。**

**Comment by javeme** [comment]
@xpleaf 谢谢反馈。
