### ISSUE TITLE
spark导入数据报错

### ISSUE THREAD

**Issue by zkiMaster** [hugegraph/hugegraph#910]
我用spark往hugegraph中写入数据的时候出现很多连接处于ESTABLISHED状态
![image](https://user-images.githubusercontent.com/47882587/77634278-a950bf00-6f8b-11ea-9097-07d8864dcb7e.png)
后面继续用spark往hugegraph中写入数据就会报
class com.baidu.hugegraph.HugeException: The rest server is too busy to write

### Specifications of environment 环境信息
- hugegraph version: 0.10.4
- operating system: centos 7.4, 8 CPUs, 16G RAM
- hugegraph backend: cassandra 3.11.6,  1 nodes, 100g ssd disk each node

**Comment by javeme** [comment]
@zkiMaster 遇到`The rest server is too busy to write`的错误，说明服务端处理请求不过来的（一般是在等待磁盘IO），应对这个的方法有如下几种：

1. 增加线程数
2. 增加写线程占比，参考：https://github.com/hugegraph/hugegraph/issues/256#issuecomment-444347387
3. 增加错误重试机制，等待一段时间服务端处理完成后进行重试
