### ISSUE TITLE
向HugeGraphServer发送gremlin post请求时报错

### ISSUE THREAD

**Issue by mengxifeng** [hugegraph/hugegraph#914]
### Expected behavior 期望表现
发送gremlin post请求

### Actual behavior 实际表现
{"exception":"org.codehaus.groovy.control.MultipleCompilationErrorsException","message":"startup failed:\nIO Exception attempting to load global transforms:/home/work/hugegraph/hugegraph-0.10.4-rocksdb/hugegraph-0.10.4/lib/groovy-2.5.7-indy.jar (No such file or directory)\n\n1 error\n","cause":"[org.codehaus.groovy.control.MultipleCompilationErrorsException]"}

### Steps to reproduce the problem 复现步骤
1. url_prefix = 'http://localhost:8161/gremlin'
2. request_data = {
    "gremlin": "hugegraph.traversal().V('287023627192')",
    "bindings": {},
    "language": "gremlin-groovy",
    "aliases": {}
}
3. response = requests.post(url=url_prefix, data=json.dumps(request_data), headers={'Content-Type': 'application/json'})

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by javeme** [comment]
@mengxifeng 可以收集一下后端的错误日志吗？
