### ISSUE TITLE
直接删除后台数据重建图库，查询schema异常

### ISSUE THREAD

**Issue by qide666** [hugegraph/hugegraph#915]
### Steps to reproduce the problem 复现步骤
图库原始数据使用studio进行schema创建和数据导入
1. {step 1 使用loadGraph api 对原始数据直接进行后端清除} 
![image](https://user-images.githubusercontent.com/50368001/77870507-2b830100-7274-11ea-9ffc-d27101e35b51.png)
日志信息：Hbase表delete之后进行init操作
![image](https://user-images.githubusercontent.com/50368001/77871006-73eeee80-7275-11ea-8727-dafe78f46301.png)

2. {step 2 使用studio 进行schema创建、数据插入}

3. {step 3 studio 使用g.V()可以查询到图库信息，graph.schema()却查询不到schema信息 }
![image](https://user-images.githubusercontent.com/50368001/77871424-ac42fc80-7276-11ea-8681-1a68981e8aaf.png)
![image](https://user-images.githubusercontent.com/50368001/77872634-0ee9c780-727a-11ea-87bf-0a939b0741f1.png)

更改loadGraph clear为false，
![image](https://user-images.githubusercontent.com/50368001/77871923-245df200-7278-11ea-8c29-da3d1e9d1521.png)

使用SchemaManager API 获取schema信息报错：
![image](https://user-images.githubusercontent.com/50368001/77871950-3344a480-7278-11ea-8056-4f8b447ef288.png)
![image](https://user-images.githubusercontent.com/50368001/77871958-36d82b80-7278-11ea-9a32-a1d6224ced03.png)

#### Vertex/Edge example 数据示例
{
u11111 = graph.addVertex(T.label, "userId", "show_no", 11111, "new_userId", "new1111", "old_userId", "old11111")
u22222 = graph.addVertex(T.label, "userId", "show_no", 22222, "new_userId", "new2222", "old_userId", "old22222")
u33333 = graph.addVertex(T.label, "userId", "show_no", 33333, "new_userId", "new3333", "old_userId", "old33333")
u44444 = graph.addVertex(T.label, "userId", "show_no", 44444, "new_userId", "new4444", "old_userId", "old44444")
u55555 = graph.addVertex(T.label, "userId", "show_no", 55555, "new_userId", "new5555", "old_userId", "old55555")
u66666 = graph.addVertex(T.label, "userId", "show_no", 66666, "new_userId", "new6666", "old_userId", "old66666")
u77777 = graph.addVertex(T.label, "userId", "show_no", 77777, "new_userId", "new7777", "old_userId", "old77777")
u88888 = graph.addVertex(T.label, "userId", "show_no", 88888, "new_userId", "new8888", "old_userId", "old88888")
u99999 = graph.addVertex(T.label, "userId", "show_no", 99999, "new_userId", "new9999", "old_userId", "old99999")
d11111 = graph.addVertex(T.label, "deviceId", "device_id", "d11111")
d22222 = graph.addVertex(T.label, "deviceId", "device_id", "d22222")
d33333 = graph.addVertex(T.label, "deviceId", "device_id", "d33333")
d44444 = graph.addVertex(T.label, "deviceId", "device_id", "d44444")
d55555 = graph.addVertex(T.label, "deviceId", "device_id", "d55555")
d66666 = graph.addVertex(T.label, "deviceId", "device_id", "d66666")
d77777 = graph.addVertex(T.label, "deviceId", "device_id", "d77777")
d88888 = graph.addVertex(T.label, "deviceId", "device_id", "d88888")
d99999 = graph.addVertex(T.label, "deviceId", "device_id", "d99999")

ip11111 = graph.addVertex(T.label, "ipAddress", "ip", "ip11111")
ip22222 = graph.addVertex(T.label, "ipAddress", "ip", "ip22222")
ip33333 = graph.addVertex(T.label, "ipAddress", "ip", "ip33333")
ip44444 = graph.addVertex(T.label, "ipAddress", "ip", "ip44444")
ip55555 = graph.addVertex(T.label, "ipAddress", "ip", "ip55555")
ip66666 = graph.addVertex(T.label, "ipAddress", "ip", "ip66666")

u11111.addEdge("use", d11111)
u22222.addEdge("use", d11111)
u22222.addEdge("use", d22222)
u33333.addEdge("use", d22222)

u11111.addEdge("use", d33333)
u44444.addEdge("use", d33333)
u44444.addEdge("use", d44444)
u55555.addEdge("use", d55555)

u11111.addEdge("locate", ip11111)
u11111.addEdge("locate", ip33333)
u11111.addEdge("locate", ip55555)
u66666.addEdge("locate", ip11111)
u66666.addEdge("locate", ip22222)
u77777.addEdge("locate", ip22222)

u22222.addEdge("locate", ip33333)
u22222.addEdge("locate", ip44444)
u33333.addEdge("locate", ip44444)

u88888.addEdge("locate", ip55555)
u88888.addEdge("locate", ip66666)
u99999.addEdge("locate", ip66666)

u11111 = graph.addVertex(T.label, "userId", "show_no", 11111, "new_userId", "new1111", "old_userId", "old11111")
u22222 = graph.addVertex(T.label, "userId", "show_no", 22222, "new_userId", "new2222", "old_userId", "old22222")
u33333 = graph.addVertex(T.label, "userId", "show_no", 33333, "new_userId", "new3333", "old_userId", "old33333")
u44444 = graph.addVertex(T.label, "userId", "show_no", 44444, "new_userId", "new4444", "old_userId", "old44444")
u55555 = graph.addVertex(T.label, "userId", "show_no", 55555, "new_userId", "new5555", "old_userId", "old55555")
u66666 = graph.addVertex(T.label, "userId", "show_no", 66666, "new_userId", "new6666", "old_userId", "old66666")
u77777 = graph.addVertex(T.label, "userId", "show_no", 77777, "new_userId", "new7777", "old_userId", "old77777")
u88888 = graph.addVertex(T.label, "userId", "show_no", 88888, "new_userId", "new8888", "old_userId", "old88888")
u99999 = graph.addVertex(T.label, "userId", "show_no", 99999, "new_userId", "new9999", "old_userId", "old99999")
u11111.addEdge("order3", u22222)
u11111.addEdge("order3", u44444)
u22222.addEdge("order3", u44444)
u44444.addEdge("order3", u55555)
u22222.addEdge("order3", u33333)
}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{
graph.schema().propertyKey("show_no").asInt().ifNotExist().create();
graph.schema().propertyKey("new_userId").asText().ifNotExist().create();
graph.schema().propertyKey("old_userId").asText().ifNotExist().create();
graph.schema().propertyKey("device_id").asText().ifNotExist().create();
graph.schema().propertyKey("ip").asText().ifNotExist().create();
graph.schema().propertyKey("total_Money").asText().ifNotExist().create();
graph.schema().propertyKey("trade_count").asText().ifNotExist().create();
graph.schema().vertexLabel("userId")
		.properties("show_no", "new_userId", "old_userId")
		.primaryKeys("show_no")
		.ifNotExist()
		.create();
graph.schema().vertexLabel("deviceId")
		.properties("device_id")
		.primaryKeys("device_id")
		.ifNotExist()
		.create();
graph.schema().vertexLabel("ipAddress")
		.properties("ip")
		.primaryKeys("ip")
		.ifNotExist()
		.create();
graph.schema().edgeLabel("use")
                .sourceLabel("userId")
                .targetLabel("deviceId")
                .ifNotExist()
                .create();
graph.schema().edgeLabel("locate")
                .sourceLabel("userId")
                .targetLabel("ipAddress")
                .ifNotExist()
                .create();
graph.schema().edgeLabel("order")
			.sourceLabel("userId")
			.targetLabel("userId")
			.properties("total_Money", "trade_count")
			.ifNotExist()
            .create();
graph.schema().edgeLabel("order3")
			.sourceLabel("userId")
			.targetLabel("userId")
			.properties("total_Money", "trade_count")
			.nullableKeys("total_Money", "trade_count")
			.ifNotExist()
            .create();
}

### Specifications of environment 环境信息
- hugegraph version: {v0.9.0}
- operating system: { centos 7.5, 32 CPUs, 64G RAM }
- hugegraph backend: {Hbase}

**Comment by javeme** [comment]
@qide666 清除的时候关闭服务了吗？另外，不建议使用这种方式来操作，因为太容易造成数据不一致了。

**Comment by qide666** [comment]
服务没有关闭。

**Comment by qide666** [comment]
服务没有关闭，因为后台数据量比较大，没有使用studio进行遍历点删除。这边有什么推荐的方式吗？

**Comment by javeme** [comment]
@qide666 可以使用如下gremlin语句清空库（危险，请慎用）：
```
graph.clearBackend()
graph.initBackend()
```

**Comment by chencjiajy** [comment]
@javeme  这个删除是将studio当前使用的图的数据删除，还是所有图的数据都删除
> graph.clearBackend()
graph.initBackend()
