### ISSUE TITLE
以json数据作为导入数据的格式时，值为空的字段也要写上么？

### ISSUE THREAD

**Issue by 597477803** [hugegraph/hugegraph#916]
![image](https://user-images.githubusercontent.com/13493298/77888323-a6f9a800-729e-11ea-8935-92b7fb622ce3.png)

在导入数据时，看到文档上有要求每行json格式需保持一致，是不是只有些key的value是缺失时，这个key也要带上么？比如{“name”: "张三", "age": 18}, {"name": "李四", "age": null}, {name: "王五", "age": null}, 
李四和王五的年龄还没有，就用空代替么？

**Comment by javeme** [comment]
@597477803 请参考：https://github.com/hugegraph/hugegraph-loader/issues/145
