### ISSUE TITLE
能否同时支持 WebSocket and HTTP 

### ISSUE THREAD

**Issue by fisherinbox** [hugegraph/hugegraph#92]
### Expected behavior 期望表现
同时支持

### Actual behavior 实际表现
不能同时支持 

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by javeme** [comment]
Tinkerpop早期版本可以同时支持 WebSocket and HTTP （使用`WsAndHttpChannelizer`），但是新版本不支持WsAndHttpChannelizer。如果一定要实现同时支持的话，可以改造GremlinServer代码。
如果大家对这个需求比较迫切，HugeGraph后续会考虑兼容两种协议。谢谢反馈

**Comment by fisherinbox** [comment]
> Tinkerpop早期版本可以同时支持 WebSocket and HTTP （使用`WsAndHttpChannelizer`），但是新版本不支持WsAndHttpChannelizer。如果一定要实现同时支持的话，可以改造GremlinServer代码。
> 如果大家对这个需求比较迫切，HugeGraph后续会考虑兼容两种协议。谢谢反馈
同时支持相比于只支持一个有什么劣势吗,改代码是否复杂,如果不复杂,请指点一下?
