### ISSUE TITLE
maven中心仓库版本更新

### ISSUE THREAD

**Issue by wanghiver** [hugegraph/hugegraph#920]
Expected behavior 期望表现
HugeGraph-core 0.10.4上传到 Maven 中心仓库，可通过 pom.xml 拉取到相关 jar 包。

Actual behavior 实际表现
目前 Maven 中心仓库上 HugeGraph 的版本还处于 0.9.2 版本。

**Comment by javeme** [comment]
@wanghiver 收到反馈， 谢谢。
