### ISSUE TITLE
节点的属性和边最大上限是多少？

### ISSUE THREAD

**Issue by 597477803** [hugegraph/hugegraph#922]
![image](https://user-images.githubusercontent.com/13493298/78100382-375af880-7417-11ea-832f-e6214484d344.png)
定义一个节点的属性时，发现数量太多，比如到达251个属性参数，load数据时就出错。请问，这个属性定义有数量上限么？可以分行定义同一个节点的不同属性么？

**Comment by javeme** [comment]
可以多次增加，请参考文档[2.3.3 追加 VertexLabel](https://hugegraph.github.io/hugegraph-doc/clients/hugegraph-client.html)

**Comment by 597477803** [comment]
> 可以多次增加，请参考文档[2.3.3 追加 VertexLabel](https://hugegraph.github.io/hugegraph-doc/clients/hugegraph-client.html)

这个找到解决了，谢谢
