### ISSUE TITLE
查询性能问题

### ISSUE THREAD

**Issue by datian9966** [hugegraph/hugegraph#924]
在使用如下gremlin语句时
```
g.V(sourceV).as('self').bothE(edge).otherV().dedup().bothE(edge).has(edgeK,gt(edgeV)).otherV().dedup().where(neq('self')).outE('test_a').has('label',eq(1)).otherV().has(conditionK0,eq(conditionV0)).values(property).count()
```
经常会出现以下错误提示
```
Script evaluation exceeded the configured 'scriptEvaluationTimeout' threshold of 60000 ms or evaluation was otherwise cancelled directly for request 
```

我的使用方式是
同一个gremlin语句，多次反复的查询，但是中间的参数会变，我已经使用了gremlin bingding的传参方式，我应该如何解决？是gremlin语句写的不够优化吗？谢谢

版本0.10 数据量300亿边10亿点 后端是HBase

**Comment by javeme** [comment]
@datian9966 看了一下语句是一个3度查询，主要看触发了多少数据量读取，建议一层一层分析，先把1度的结果数打出来，然后把2度的打出来。。。
另外看看路径中是否遇到超级点，如果有可以使用local limit限制一下degree，或者使用sortkey进行索引查找。
也可以尝试下rest接口：[Customized Paths](https://hugegraph.github.io/hugegraph-doc/clients/restful-api/traverser.html)

**Comment by datian9966** [comment]
@javeme 您好~
现在把三度语句改为二度
g.V(sourceV).as('self').bothE(edge).otherV().dedup().bothE(edge).has(edgeK,gt(edgeV)).otherV()
根据您的建议 我把语句逐层分析 逐层count 一度关系是288个节点 二度关系是58068个 
1度关系很快 几十ms  2度关系 不是很稳定 但最少需要10s以上 
hbase使用的是ssd盘  根据您的经验  我这个数量级的数据 二度关系 10s算正常吗？

另外 因为也无需要 会发送很多个类似请求(只是起点不同) 在请求量稍微一大的时候 server就开始响应变慢了

**Comment by datian9966** [comment]
@javeme 您好
根据您的建议，我先把语句写成二度进行尝试
g.V(sourceV).as('self').bothE(edge).otherV().dedup().bothE(edge).otherV().dedup()
然后一层一层分析
第一层是288个点 第二层是 342659个点
经过逐一排查 确实有比较大的节点出现 通过local limit可以进行限制
针对上述所说的数量级，我有个疑问
  我在查询二度的时候 光count一下大概就是11s以上
  如果我在has一下之类的 消耗的时间更久
  依您的经验来看，这个耗时水平正常吗？

hbase使用的SSD盘

**Comment by javeme** [comment]
@datian9966 感谢反馈，读取34万的数据11秒属于正常水平。优化的方向是尽量在前两度剔除掉不符合条件的数据。

**Comment by datian9966** [comment]
@javeme 明白了 感谢！

**Comment by datian9966** [comment]
@javeme  您好 还想请教几个问题 麻烦帮忙解答一下

```bash
(1)g.V(sourceV).as('self').bothE(edge).otherV().dedup().bothE(edge).has(edgeK,gt(edgeV)).otherV()
```
```bash
(2)g.V(sourceV).as('self').bothE(edge).otherV().dedup().local(bothE(edge).has(edgeK,gt(edgeV))).otherV()
```
```bash
(3)g.V(sourceV).as('self').bothE(edge).otherV().dedup().local(bothE(edge).has(edgeK,gt(edgeV)).limit(100)).otherV()
```
```bash
(4)g.V(sourceV).as('self').bothE(edge).otherV().dedup().local(bothE(edge).limit(100)).otherV()
```


1.请问第(2)句会比第(1句)有优化效果么?我的理解是第(1)句在查询二度关系的时候,把所有二度关系的边都取回到内存中，然后进行过滤。第(2)句是每一个一度顶点查询二度边的时候直接就过滤了，不用全部加载到内存再过滤。不知道我理解的对么？(只有第(4)句种能感觉到明显的快)

2.第(3)句中的limit的结果每次一定是一致的吗？

3.根据您的建议，就是依次减少每一度的点边数量，但是我感觉我的条件限制总是在全部数据都加载到内存后才生效，是否有办法让条件前置呢？从数据库里搜索的时候就已经过滤过一次了，以至于不把所有的边或者点都加载到内存再计算

上述有说的不对的地方 还请见谅！

**Comment by javeme** [comment]
@datian9966 分别解答：
> 1.请问第(2)句会比第(1句)有优化效果么?

这两句是效果上是一样的。

> 2.第(3)句中的limit的结果每次一定是一致的吗？

设置条件的同时，增加了 limit(100)，不至于放出超级点。limit的结果每次一致我不太明确意思，如果是指一定是小于100个的话，是的；如果是指2次查询的最终结果是否相同，是的（如果需要不同请使用sample）。

> 3.是否有办法让条件前置呢？

之前给出的建议：使用`sortkey`进行索引查找，目的就是优化这个，也就是说对于`has(edgeK,gt(edgeV))`查询，请对边属性`edgeK`建立`sortkey`。

**Comment by datian9966** [comment]
@javeme 前两个问题明白了，感谢您的解答！
第三个问题我现在的条件是根据时间去进行筛选，比如has('time',gt('2020-01-01 00:00:00'))
我不太确定在时间属性上建立sortkey是合适的吗？

**Comment by javeme** [comment]
@datian9966 具体看业务，一般来说是合适的，比如通话记录、转账记录等都可以把时间作为sortkey。

**Comment by datian9966** [comment]
@javeme 好的 非常感谢 现在理解的更加透彻一些了
