### ISSUE TITLE
使用api 创建节点，返回201，实际查询不到数据

### ISSUE THREAD

**Issue by chencjiajy** [hugegraph/hugegraph#927]
### Expected behavior 期望表现
使用api `http://localhost:8183/graphs/hugegraph/graph/vertices/batch`创建节点，返回201，可以查询到数据，使用完`http://localhost:8183/graphs/hugegraph/graph/vertices/batch` 之后，可以接着使用`http://localhost:8183/graphs/hugegraph/graph/edges/batch`

### Actual behavior 实际表现
使用api `http://localhost:8183/graphs/hugegraph/graph/vertices/batch`创建节点，返回201，实际查询不到数据， 使用`http://localhost:8183/graphs/hugegraph/graph/edges/batch`时也因为前面插入的节点不存在而报错。

### Steps to reproduce the problem 复现步骤
准备 一批数据，使用api来插入就可以了
注：我上周测试可以，这周测试就查询不到数据

### Specifications of environment 环境信息
- hugegraph version: 0.10.4
- operating system:  centos 7.7
- hugegraph backend: hbase 2.1.3

**Comment by javeme** [comment]
> 使用api http://localhost:8183/graphs/hugegraph/graph/vertices/batch创建节点，返回201，实际查询不到数据

这个属于最基本的API，应该不至于出现数据查不到这么严重的bug，请把复现流程说明下。

**Comment by chencjiajy** [comment]
前几天测试了很多次，确实是返回201，实际查询不到数据，今天同样的代码，再次测试，可以查询到数据。所以很诡异
