### ISSUE TITLE
add 5 TP RESTful API

### ISSUE THREAD

**Issue by zhoney** [hugegraph/hugegraph#929]
### Expected behavior 期望表现
增加5个TP API
1. same neighbors
2. jaccard similarity
3. single source shortest paths
4. weighted shortest path
5. all shortest paths

**Comment by RodJohn** [comment]
可以直接拓展 《Personal Rank API》为多起点PageRank。
将sources改为list<Id>，后面代码基本可以复用

**Comment by zhoney** [comment]
implemented in #919
