### ISSUE TITLE
personalrank并发提升不了

### ISSUE THREAD

**Issue by RodJohn** [hugegraph/hugegraph#932]
# 问题

使用集群无法提升personalrank并发

# 环境

## 硬件环境

单机
ubantu 18.4
CPU  Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz  80核 
内存 500G 
硬盘 6T 机械

## 部署方式

nginx分发请求到docker集群(4个)
docker内部安装hugegraph-server并使用独立的rockDB后端
单个docker不限制cpu和内存

## 测试方式

Jmeter并发测试

# 复现步骤

## 前提：

只有读操作
（docker内部的hugegraph-server已经使用loader导入了数据）

### Jmeter设置
![图片](https://user-images.githubusercontent.com/31351035/78622342-77a6f480-78b7-11ea-8017-1fdebcdd02e0.png)

### 压测单个docker
请求状况
![图片](https://user-images.githubusercontent.com/31351035/78622686-601c3b80-78b8-11ea-99a5-6d5e265f40bb.png)

docker监控
![图片](https://user-images.githubusercontent.com/31351035/78622422-ac1ab080-78b7-11ea-9197-338735965425.png)

### 压测集群docker(通过nginx)
请求状况
![图片](https://user-images.githubusercontent.com/31351035/78623068-6232ca00-78b9-11ea-8728-da698fdd2747.png)
![图片](https://user-images.githubusercontent.com/31351035/78637372-d2067c00-78dc-11ea-891a-8ca60c6bd58e.png)

docker监控
![图片](https://user-images.githubusercontent.com/31351035/78622878-dcaf1a00-78b8-11ea-81eb-25505252fecb.png)

## Jmeter
![图片](https://user-images.githubusercontent.com/31351035/78624214-b179fa00-78bb-11ea-8de0-ddd48b02c9c7.png)

### 压测单个docker（降流）
请求状况
![图片](https://user-images.githubusercontent.com/31351035/78623401-22b8ad80-78ba-11ea-919a-6a082de5958a.png)
docker监控
![图片](https://user-images.githubusercontent.com/31351035/78623441-3bc15e80-78ba-11ea-8849-8b11221dd577.png)

# 期望表现

集群模式下通过负载均衡
降低了单个CPU的占用率
但是平均响应时间并没有降低
并没有降流下单个服务的的效果

**Comment by javeme** [comment]
> 压测集群docker(通过nginx)
> 请求状况

nginx是随机分发的请求吗？是否均衡？
另外，测试结果为什么没有把throughput截出来？理论上这种场景下请求均衡的话，吞吐量是会提升的。
此外，如果需要测并发读建议使用SSD盘。

**Comment by RodJohn** [comment]
> 
> 
> > 压测集群docker(通过nginx)
> > 请求状况
> 
> nginx是随机分发的请求吗？是否均衡？
> 另外，测试结果为什么没有把throughput截出来？理论上这种场景下请求均衡的话，吞吐量是会提升的。
> 此外，如果需要测并发读建议使用SSD盘。

**Comment by RodJohn** [comment]
1

**Comment by RodJohn** [comment]
nginx用的是轮询

`user  nginx;
worker_processes  20;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  10240;
}


http {
   upstream  loader-server {
       least_conn;
       server    192.168.3.202:8081 ;
       server    192.168.3.202:8082 ;
       server    192.168.3.202:8083 ;
       server    192.168.3.202:8084 ;
   }

   server {
       listen       80;
       server_name  0.0.0.0;

       location / {
        add_header backendIP $upstream_addr;
        add_header backendCode $upstream_status;
        proxy_pass http://loader-server;
        proxy_redirect default;
      }

    }

    log_format  main  '$time_local-$msec $remote_addr- "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '$upstream_addr '
                      '$request_time $upstream_connect_time $upstream_header_time $upstream_response_time';

    access_log  /var/log/nginx/access.log  main;
}`

nginx打印的日志上也能看到请求分发的比较平均
![图片](https://user-images.githubusercontent.com/31351035/78635992-fb71d880-78d9-11ea-8873-2a98fffe7aa8.png)
