### ISSUE TITLE
hugegraph-loader导入顶点为空

### ISSUE THREAD

**Issue by tl890216** [hugegraph/hugegraph#94]
### schema
// Define schema
schema.propertyKey("name").asText().ifNotExist().create();
schema.propertyKey("age").asInt().ifNotExist().create();
schema.propertyKey("city").asText().ifNotExist().create();

schema.vertexLabel("person").properties("name", "age", "city").useCustomizeNumberId().ifNotExist().create();

schema.indexLabel("personByName").onV("person").by("name").secondary().ifNotExist().create();
schema.indexLabel("personByAge").onV("person").by("age").range().ifNotExist().create();
schema.indexLabel("personByCity").onV("person").by("city").secondary().ifNotExist().create();
schema.indexLabel("personByAgeAndCity").onV("person").by("age", "city").secondary().ifNotExist().create();

### struct
{
  "vertices": [
    {
      "label": "person",
      "input": {
        "type": "file",
        "path": "example2/vertex_person.csv",
        "format": "CSV",
        "header": ["id","name", "age", "city"],
        "charset": "UTF-8"
      },
      "id":"id"
    }
  ]
}

### data
1,marko,29,Beijing
2,vadas,27,Hongkong
3,josh,32,Beijing
4,peter,35,Shanghai
5,"li,nary",26,"Wu,han"
                 

### Specifications of environment 环境信息
- hugegraph version: v0.7.4
- operating system: centos 7.4, 32 CPUs, 256G RAM
- hugegraph backend: hbase

**Comment by Linary** [comment]
感谢反馈，这确实是一个[BUG](https://github.com/hugegraph/hugegraph-loader/issues/5)，我们会在新版本中修复。
