### ISSUE TITLE
使用kneighbor接口时，想加上label参数过滤，但是怎么写都不对，有没例子呀？

### ISSUE THREAD

**Issue by 597477803** [hugegraph/hugegraph#958]
http://***:8080/graphs/hugegraph-online/traversers/kneighbor?source=%22kg_n_game_1%22&label=%22User%22&max_depth=1
使用kneighbor接口时，想加上label参数过滤，但是怎么写都不对，有没例子呀？多个label的参数又怎么写？

**Comment by javeme** [comment]
@597477803 请去掉请求参数User的引号：`label=%22User%22`，顶点ID使用引号是因为为了区分数字类型和字符串类型的ID，其它参数无需增加特殊的引号。

**Comment by 597477803** [comment]
> @597477803 请去掉请求参数User的引号：`label=%22User%22`，顶点ID使用引号是因为为了区分数字类型和字符串类型的ID，其它参数无需增加特殊的引号。

label支持多个参数么？

**Comment by javeme** [comment]
@597477803 不支持多个，只能是一个或不指定（代表任意label均可）。如果需要支持多label可使用 另一个接口：`Customized Paths`
