### ISSUE TITLE
图分区问题

### ISSUE THREAD

**Issue by jiebaHZ** [hugegraph/hugegraph#961]
### hugegraph有没有具体的图分区策略

1. 比如：当后端存储是hbase时，在导入大量数据时，是直接一次性随机写入hbase，然后hbase自行分区，还是先将数据按照一定策略划分好，再放到hbase指定的region上？

2. 有关这部分的源码是在hugegraph-hbase包还是在hugegraph-core包

**Comment by imbajin** [comment]
> ### hugegraph有没有具体的图分区策略
> 1. 比如：当后端存储是hbase时，在导入大量数据时，是直接一次性随机写入hbase，然后hbase自行分区，还是先将数据按照一定策略划分好，再放到hbase指定的region上？
> 2. 有关这部分的源码是在hugegraph-hbase包还是在hugegraph-core包

1. 当然是建议预分区后导入, 最好是有抓 key 的工具, 没有建议先至少hash 分一些
2. 前者.
