### ISSUE TITLE
java程序添加顶点报错 Method threw 'com.baidu.hugegraph.exception.InvalidOperationException' exception. Cannot evaluate com.sun.proxy.$Proxy173.toString()

### ISSUE THREAD

**Issue by I-DO-NOT-KNOW** [hugegraph/hugegraph#962]
![微信截图_20200422100347](https://user-images.githubusercontent.com/20416323/79933326-5252e280-8482-11ea-9adf-73b344abca50.png)
代码：
VertexLabel.Builder vertexBuilder = schema.vertexLabel(vertex.getLabel());
vertexBuilder对象报错：Method threw 'com.baidu.hugegraph.exception.InvalidOperationException' exception. Cannot evaluate com.sun.proxy.$Proxy173.toString()
不知道为什么以前这个代码是可以用的，现在报错

**Comment by javeme** [comment]
@I-DO-NOT-KNOW hugegraph提供的Vertex类是没有这个方法的：`vertex.getLabel()`，请提供更多信息：getLabel这个方法的返回值是什么？这个代码是在server端还是client端执行的？以前可以现在不可以这个过程之间有什么不一样的变化？以及完整的错误堆栈信息。

**Comment by I-DO-NOT-KNOW** [comment]
> 
> 
> @I-DO-NOT-KNOW hugegraph提供的Vertex类是没有这个方法的：`vertex.getLabel()`，请提供更多信息：getLabel这个方法的返回值是什么？这个代码是在server端还是client端执行的？以前可以现在不可以这个过程之间有什么不一样的变化？以及完整的错误堆栈信息。

vertex.getLabel()是我自己的对象，返回的是个字符串。这个问题似乎是：如果schema中包含已有的label名称的属性、顶点或者边的话，再进行同样名称的添加时会报InvalidOperationException错误。我是直接catch掉后，不让这个异常影响整个流程后就好了。如图
![微信截图_20200422144452](https://user-images.githubusercontent.com/20416323/79949273-dd929f00-84a7-11ea-82d1-af27074456b5.png)
