### ISSUE TITLE
发现restful接口基本都是好使的，但就是发送gremlin的接口是不OK的？

### ISSUE THREAD

**Issue by 597477803** [hugegraph/hugegraph#964]
GET http://127.0.0.1:8080/gremlin?gremlin=hugegraph.traversal().V('1:marko')
返回：
{
"exception": "groovy.lang.MissingPropertyException",
"message": "No such property: hugegraph for class: Script25",
"cause": "[groovy.lang.MissingPropertyException]"
}
我这边是把后端的图数据命名为hugegraph-online，这个有没关系？具体怎么拼url才对？

**Comment by javeme** [comment]
@597477803 请使用`graph.traversal().V('1:marko')`

**Comment by 597477803** [comment]
> @597477803 请使用`graph.traversal().V('1:marko')`
用了之后，错误是一样的呀？
{
"exception": "groovy.lang.MissingPropertyException",
"message": "No such property: graph for class: Script27",
"cause": "[groovy.lang.MissingPropertyException]"
}

**Comment by imbajin** [comment]
`gremlin=`后跟的是**graphName**, 也就是你命的图名字, 所以你应该这样写:

`ip:8080/gremlin?gremlin=hugegraph-online.traversal().V(xx)`

想用其他方式可以参考[文档](https://hugegraph.github.io/hugegraph-doc/clients/restful-api/gremlin.html)

**Comment by 597477803** [comment]
> `gremlin=`后跟的是**graphName**, 也就是你命的图名字, 所以你应该这样写:
> 
> `ip:8080/gremlin?gremlin=hugegraph-online.traversal().V(xx)`
> 
> 想用其他方式可以参考[文档](https://hugegraph.github.io/hugegraph-doc/clients/restful-api/gremlin.html)

试过，一样的错误

**Comment by 597477803** [comment]
> `gremlin=`后跟的是**graphName**, 也就是你命的图名字, 所以你应该这样写:
> 
> `ip:8080/gremlin?gremlin=hugegraph-online.traversal().V(xx)`
> 
> 想用其他方式可以参考[文档](https://hugegraph.github.io/hugegraph-doc/clients/restful-api/gremlin.html)

我怀疑是不是图的名字中间不能用"-", 我做实验试下吧

**Comment by imbajin** [comment]
图命名这是有限制, 昨天复制没注意.
有相同的[issue](https://github.com/hugegraph/hugegraph/issues/850)
