### ISSUE TITLE
多度查询超时和性能问题？

### ISSUE THREAD

**Issue by 597477803** [hugegraph/hugegraph#965]
数据量：5千万实体，10亿边
我们用到了traverser API，但查询涉及到3度关系及以上的便利查询时就经常超时或没结果，查询速度有办法提上么，太慢了大数据的背景下，图谱就变得不可用了？

**Comment by javeme** [comment]
@597477803 3度查询加上max_degree参数限制超级点，在SSD盘上应该是毫无压力的，机械盘可能会有些吃力（如果顶点平均度100的话，3度可能触发1000000的顶点读取），可以把max_degree设置小一些（比如30）。

**Comment by 597477803** [comment]
> @597477803 3度查询加上max_degree参数限制超级点，在SSD盘上应该是毫无压力的，机械盘可能会有些吃力（如果顶点平均度100的话，3度可能触发1000000的顶点读取），可以把max_degree设置小一些（比如30）。

我们用的是hbase

**Comment by 597477803** [comment]
> @597477803 3度查询加上max_degree参数限制超级点，在SSD盘上应该是毫无压力的，机械盘可能会有些吃力（如果顶点平均度100的话，3度可能触发1000000的顶点读取），可以把max_degree设置小一些（比如30）。

请问下：“max_degree: 查询过程中，单个顶点最大边数目，选填项，默认为10000”这个max_degree是具体是限制了什么？是限制了从一个顶点出发的遍历的边的数目么？

**Comment by imbajin** [comment]
性能优化的问题, 一般不是能很简单说清的
1. 得提供基本的机器环境/配置
2. 尝试确定一下遍历的点/边数据量
3. 观察磁盘IOPS+访问hbase的慢日志
4. 使用Arthas监控`HbaseSessions`的方法每秒执行次数, 平均时延等

然后建议先查看一下已有的类似`issue`  🌓
