### ISSUE TITLE
Customized Paths 接口的properties参数问题？

### ISSUE THREAD

**Issue by 597477803** [hugegraph/hugegraph#967]
![image](https://user-images.githubusercontent.com/13493298/80058507-02e0e500-855c-11ea-8eaa-ed0ba4f94d58.png)
当使用sort_by时在step里指定了一个properties的值，是用边的属性还是节点的属性？属性支持是数组么，比如[10.0]? 如果同时指定了sort_by和degree，排序还是不是全局的？

**Comment by 597477803** [comment]
> ![image](https://user-images.githubusercontent.com/13493298/80058507-02e0e500-855c-11ea-8eaa-ed0ba4f94d58.png)
> 当使用sort_by时在step里指定了一个properties的值，是用边的属性还是节点的属性？属性支持是数组么，比如[10.0]? 如果同时指定了sort_by和degree，排序还是不是全局的？

看了下源码，应该是边的属性

**Comment by zhoney** [comment]
@597477803 
1. `step`里指定的`properties`是指的边的属性
2. 属性的值支持`单值`或者`List`，`单值`表示“equal()关系”，`List`表示“within()关系”
3. `degree`和`sort_by`是针对不同阶段的参数，`degree`限定的是遍历过程中每个顶点的边的数目上限，为的是防止遇到超级点而失败（限定后中间过程可能会丢掉部分路径）；`sort_by`是对最终查出的所有符合条件的paths（如果前边指定了`degree`，此时的paths可能已经丢掉了一些path）做排序，并返回前`limit`个paths

**Comment by 597477803** [comment]
> @597477803
> 
> 1. `step`里指定的`properties`是指的边的属性
> 2. 属性的值支持`单值`或者`List`，`单值`表示“equal()关系”，`List`表示“within()关系”
> 3. `degree`和`sort_by`是针对不同阶段的参数，`degree`限定的是遍历过程中每个顶点的边的数目上限，为的是防止遇到超级点而失败（限定后中间过程可能会丢掉部分路径）；`sort_by`是对最终查出的所有符合条件的paths（如果前边指定了`degree`，此时的paths可能已经丢掉了一些path）做排序，并返回前`limit`个paths

了解 3ks
