### ISSUE TITLE
是否支持hasLabel的模糊查询

### ISSUE THREAD

**Issue by iconlee** [hugegraph/hugegraph#970]
huge能否批量对某类表进行字段的局部查询，比如支持语句has('pub_%',propname,propvalue)之类的语句

**Comment by iconlee** [comment]
补充，has语句之前原型是has(labelname,name,value)但是能否对labelname做一定的模式匹配的功能，如果不能简单用gremlin语句一句实现，能否有复杂的gremlin实现这类需求呢

**Comment by javeme** [comment]
@iconlee 不支持hasLabel的模糊查询，可以支持多个label查询，比如：
`g.V().hasLabel('label1', 'label2').has('name1', 'value1')`
