### ISSUE TITLE
请问下HugeGraph-Spark 这个工具开源了么？

### ISSUE THREAD

**Issue by 597477803** [hugegraph/hugegraph#973]
请问下HugeGraph-Spark 这个工具开源了么？
https://hugegraph.github.io/hugegraph-doc/quickstart/hugegraph-spark.html

**Comment by imbajin** [comment]
Why submit duplicate issue and not search the current issues before submit a new one....?
![image](https://user-images.githubusercontent.com/17706099/80369758-5f783300-88c1-11ea-835b-0d53b76420f9.png)
Refer to #265 .. 😿
