### ISSUE TITLE
java client运行Example失败

### ISSUE THREAD

**Issue by kaiqiangmeng** [hugegraph/hugegraph#977]
### Expected behavior 期望表现
运行正常

### Actual behavior 实际表现
报错

### Steps to reproduce the problem 复现如下图
![image](https://user-images.githubusercontent.com/45863353/80565801-fceb7800-8a23-11ea-8992-4fcc9aeb6f00.png)

**Comment by javeme** [comment]
@kaiqiangmeng 可能是已经存在了software的VertexLabel，请先删除原来的再尝试。可以去掉ifNotExist进行验证，ifNotExist会自动忽略掉已存在的schema。
