### ISSUE TITLE
能否关闭缓存机制,设置graph.cache_expire=0 没有效果

### ISSUE THREAD

**Issue by fisherinbox** [hugegraph/hugegraph#98]
### Expected behavior 期望表现
无需缓存,每次请求都重新计算

### Actual behavior 实际表现
无法关闭缓存

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by javeme** [comment]
无法关闭缓存，不过可以调小缓存容量vertex.tx_capacity来进行控制（最小值为1），graph.cache_expire是缓存超时时间。
配置项文档见：https://hugegraph.github.io/hugegraph-doc/guides/config-option.html
