### ISSUE TITLE
hbase 数据转换问题

### ISSUE THREAD

**Issue by LittleWhitec** [hugegraph/hugegraph#980]
### Expected behavior 期望表现
最近在尝试用hbase的bulkload方法导入数据，在数据转换的时候碰到了问题  当属性是int类型的时候，参考了源码

### Actual behavior 实际表现
可以导入，可以查询，但是由于int类型转换异常，查出来的值和想导入的那个数值对不上，想请问下int类型的数据 你们是用什么转bytes的

**Comment by javeme** [comment]
@LittleWhitec 实现的话参考源码应该不是问题。不过不建议使用bulkload方式，bulkload虽然快，但是时间主要是在图数据生成hfile的过程，另外需要考虑开发bulkload程序时间、并引入较多手动干预步骤，兼容性问题多与复杂度高。
如果数据不超过百亿的话，个人觉得调优hbase本身性能，使用在线导入是更好的选择。假如在线导入100亿条数据，速度平均10w/s，大概2天时间也是能完成的。
