### ISSUE TITLE
是否支持SPARQL-Gremlin

### ISSUE THREAD

**Issue by iconlee** [hugegraph/hugegraph#987]
看到tinkerpop有介绍支持SPARQL-Gremlin的插件
http://tinkerpop.apache.org/docs/current/reference/#sparql-gremlin，请问hugegraph是否有该功能支持，如何配置并且在hugegraph上进行执行测试

**Comment by javeme** [comment]
@iconlee 默认没有提供该支持，理论上是可以支持的，请根据文档添加依赖、重新打包、安装插件并进行加载。
