### ISSUE TITLE
hugegraph多机问题?

### ISSUE THREAD

**Issue by 597477803** [hugegraph/hugegraph#990]
请问一下，因为hugegraph不支持集群，后端采用的是hbase，现在想提高服务的并发，是不是可以开多个单点hugegraph查询同一个hbase，这样的方式提高并发是否有效？还有其他更好提高并发的方案么？

**Comment by imbajin** [comment]
首先, 性能问题/优化先别急着下结论, 因为**猜测**的瓶颈点, 很可能不是实际的瓶颈, 如果一开始方向就有偏差, 那后面会做大量无用功... 在你确定提高并发后, 读写速度有**明显下降**的前提下, 还需要确认以下因素至少满足一项, 再去验证排查

Sever可能的**瓶颈点**: 
1. Server机器CPU打满, 且大部分是graph-server占用, 不多见 (CPU瓶颈)
2. 通过`jstack/Arthas`查看, 大部分请求处于阻塞等待状态 (RPC瓶颈)
3. 网卡负载已满, 这个应该也不多见 (IO瓶颈)

问题1/3如果出现, 可以通过加机器(多server)来测试看看是否有效, 问题2可以尝试控制写入数据的线程占比, 以及增大server的处理线程数, 增大请求Hbase的线程数

实际情况来看, 瓶颈往往出现在Hbase/其它存储本身, 比如
1. **随机读**慢, 观察RS磁盘IOPS是否打满, HDD常见 (IO瓶颈)
2. 数据请求量太大, 图给Hbase发的RPC次数过多(图遍历瓶颈)
3. CPU/内存使用打满, 比如Hbase做split/compaction时的影响 (CPU瓶颈)
4. 数据是否分布不均(too busy), RS节点不足, meta-server是否稳定 (RPC瓶颈)

总之, 需要仔细定位一下提高并发的瓶颈点在哪, 做好**测试**和**对比**, 之后再谈优化方案会高效的多

**BTW:** 类似的也不需要开多个loader/client去导入数据, 因为瓶颈往往不是推测的那样线性叠加的
