### ISSUE TITLE
 Customized Paths接口问题sample问题

### ISSUE THREAD

**Issue by 597477803** [hugegraph/hugegraph#992]
![image](https://user-images.githubusercontent.com/13493298/81468633-5406ff00-9213-11ea-9889-be8187882775.png)
请问在使用这个接口进行抽样时，设置了这两个参数如下，
degree：10000
sample：100
问题是：多次调用该接口抽样时，sample的分母是不是同样的（即抽样前总集合是否都是一样的）？实时上，我们是想用该接口进行全局抽样，但是因为存在超时问题，所以只能设置degree进行限制，这样每次抽样是不是就不是全局抽样？

**Comment by javeme** [comment]
@597477803 
> sample的分母是不是同样的

是一样的。

> 这样每次抽样是不是就不是全局抽样？

degree可以跳过超级点，如果需要超级点，并且有超时问题，请使用异步gremlin任务。个人经验，对于超级点抽样无需太精确。
