### ISSUE TITLE
g.V().has('name',not(within('josh','marko'))).elementMap() 执行错误

### ISSUE THREAD

**Issue by iconlee** [hugegraph/hugegraph#993]
g.V().has('name',not(within('josh','marko'))).elementMap() 在thinktop3 console执行正常，但是在hugegraph平台执行错误，提示No signature of method: org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.DefaultGraphTraversal.elementMap() is applicable for argument types: () values: []

**Comment by javeme** [comment]
@iconlee elementMap这个是新加入的特性，可能是你使用的是最新的版本3.4.5+？hugegraph目前支持的版本是thinktop 3.4.3。暂时可使用其它step替代elementMap，比如使用properties 、values等
