### ISSUE TITLE
通过java程序添加有时间类型的字段的顶点，在图数据库中值最终会少8个小时

### ISSUE THREAD

**Issue by I-DO-NOT-KNOW** [hugegraph/hugegraph#996]
代码如下：
Date testDate = new Date();
Vertex vertex=new Vertex("testLabel");
vertex.property("testDate",testDate);
当将这个顶点存入图数据库中发现testDate属性值比存入时少了8个小时

**Comment by imbajin** [comment]
你可以先直接发送rest-api, 添加一个点, 然后设置它的date, 看是否正常.
如果正常可以看看检查/手动设置一下时区,


PS: Loader导入的话, 可以指定时区, 你也可以试试看是否有效, 缩小问题范围
--> [Loader: Support customized timezone for date](https://github.com/hugegraph/hugegraph-loader/pull/107/files)

**Comment by I-DO-NOT-KNOW** [comment]
@imbajin 使用rest-api添加点时间是正常的。但是通过java程序的话不知道为什么会出现少8个小时的情况。图数据库服务器部署到linux的docker上，已经设置时区为CST+0800，java的jvm也设置时区为GMT+8。下面截图是更新图数据库属性代码前打的端点。时间是没有问题的，时区也是GMT+8。但是图数据库中时间少8小时。
![1](https://user-images.githubusercontent.com/20416323/82281440-e05bb380-99c3-11ea-8b16-1db2c881b3c0.png)

**Comment by imbajin** [comment]
没事, 一步步缩小范围呗, 你现在通过rest添加是正常的.  验证了第一个

但是你通过client发送有时差, 那你应该在server端来对比呢. 不管是用断点还是Arthas(推荐后者)
因为client发请求和rest-api发是殊途同归的, 会走到一个server的入口才对.
你就在server观察两者发送来之后, 属性值有什么区别, 就可以进一步确定问题出在哪了

然后你也可以用loader尝试指定一下时区, 导入一条测试数据, 看看效果呗, 也是一个排除方案. loader是完全调用的client去发送数据的, 最后也是发rest请求.

**Comment by I-DO-NOT-KNOW** [comment]
@imbajin 没有找到你说的server，找到了向图数据库中发送请求的代码。从下面两个图中可以看出来，向服务器传的时候时间是正常的，服务器返回的时间戳转换成北京时间也是正常的。但是从Studio中查出来的数据还是少了8个小时。
![2](https://user-images.githubusercontent.com/20416323/82416882-5d168c80-9aad-11ea-81b6-2e30bf790f0d.png)
![3](https://user-images.githubusercontent.com/20416323/82416896-6142aa00-9aad-11ea-8a5a-f700cc1176ef.png)

**Comment by imbajin** [comment]
我说的server就是`hugegraph-server`, 也就是你说的图数据库. 入口就是Vertex/EdgeAPI类这种.

如果你通过rest-api或HugeClient插入点, 然后通过rest-api查询时间都是正常的, 那说明跟图server没有关系呐. 

那问题应该就可以缩小到你从`studio`读为什么有时差了吧?  studio本质也是调用huge-client给huge-sever发请求, 你自己动态调试看看它接受到请求返回的时区和时间是否匹配就可以进一步确定了. 然后看看studio所在节点时区是否有问题, 或者你换一个机器起studio对比一下.

如果你通过rest-api查询图里的数据, 时间正常, 通过studio查询同样数据, 时间不正常, 那这问题就很明显了.

**Comment by I-DO-NOT-KNOW** [comment]
@imbajin 我可能没有表达清楚，我用rest-api修改节点日期属性值在studio中查看是正常的。但是用jiava修改日期属性值后再studio中查看就少8小时。
