### ISSUE TITLE
Undefined edge label

### ISSUE THREAD

**Issue by bingle2000** [hugegraph/hugegraph#997]
### Expected behavior 期望表现
查询 g.V().hasLabel('ip')

### Actual behavior 实际表现
1、Undefined edge label: 'bw'
2、Undefined edge label with id: '42'

### Steps to reproduce the problem 复现步骤
出现错误1后，重建bw edge，再次导入数据后，再查询出现错误2；

### Specifications of environment 环境信息
hugegraph-0.10.4
hugegraph backend: rocksdb

**Comment by imbajin** [comment]
看之前也提过类似的问题, #573 ,可以多描述一些信息么? 或者提供一个可以稳定复现的方式?
你可以发一下可复现的schema, 和一些测试数据, 完整查询语句. 完整的REST操作. (现在太粗略了)

顺便, 几个问题确认一下:
1. 在什么情况下出现**错误1**的, 是和之前一样, 做过REST-API的**删除**Label操作么? 
    - 若有, 删除的是边Label么? 为啥你查询**点**报的边label不存在, 是gremlin语句没写完整么?
    - 若有, 删除完后有通过REST-API查询所有边Label确认么? 没有确认可以再尝试复现看看
    - 没有, 或其他操作, 请详细补充一下.
2. 如果做了`删除 --> 新增`操作, 你之后有重启过server么? (或者一切可能清空schema缓存的操作)
    - 删除 --> 新增Label --> **未重启**Server, 导入数据应该是正常的, 此时你查询正常么? 
    - 删除 --> 新增Label --> **重启**Server后, 才出现查询**删除边**异常的么?
3. 你说的问题1之后重建边, 是用rest-api新增边label么? 然后出现问题2后, 你尝试过以下操作么:
    -  用REST-API查询所有的边labl, 看看`42`是不是不存在, 但是存在一个更大的`4x`  (比如`43`)
    -  如果存在`4x` , 你尝试直接用`g.E().hasLabel("xx").limit(5)` 查询`4x`对应的边label, 看看是否可以正常查询

最后, 之前 #573 提到的问题是怎么解决的呢?

**Comment by fuling1999** [comment]
> 看之前也提过类似的问题, #573 ,可以多描述一些信息么? 或者提供一个可以稳定复现的方式?
> 你可以补发一下以下信息: (现在太粗略了)
> 
> * 可复现的schema
> * 和一点测试数据
> * 完整的gremlin查询语句
> * 完整的REST-CURD操作.
> * 完整的异常栈信息
> 
> 顺便, 几个问题确认一下:
> 
> .......
> 最后, 之前 #573 提到的问题是怎么解决的呢?

感觉的确和 #573 比较像，过去的时间太久了，重现有点困难，因为太偶然，不记得具体步骤了，大体就是删除了 edge label，然后重建edge label、导入数据。

**Comment by imbajin** [comment]
你这个问题我已经可以偶尔复现,  然后给了一个临时解决方案.
大概率是因为数据出现了不一致, 删除过程没有完成进行了新的写入. 导致存在了一批不合法的数据.
所以读的时候就会报错, 这个可以先捕获异常, 输出日志.

根本解决要去把这批过期数据删掉, 可能还比较麻烦
