### ISSUE TITLE
HugeSecurityManager编译找不到符号

### ISSUE THREAD

**Issue by xiuFranklin** [hugegraph/hugegraph#998]
### Expected behavior 期望表现
下载hugegraph源码，执行mave compile编译失败

### Actual behavior 实际表现

![image](https://user-images.githubusercontent.com/15900131/82415164-b3ce9700-9aaa-11ea-93d6-c1970a1b8dd1.png)

**Comment by imbajin** [comment]
windows上不做适配是不能编译的. 本身有脚本兼容问题.

所以你如果需要, 还是换linux/mac环境编译吧. 只有win的话, 就在容器环境里编
